### ISSUE TITLE
Deployed API cannot be invoked after restarting APIM

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#10068]
### Description:
After successfully invoking an API, the following error logs are seen when restarting the APIM server

```
TID: [-1234] [] [2021-03-02 12:20:40,834]  INFO {org.wso2.carbon.core.internal.StartupFinalizerServiceComponent} - Server           :  WSO2 API Manager-4.0.0
TID: [-1234] [] [2021-03-02 12:20:40,835]  INFO {org.wso2.carbon.core.internal.StartupFinalizerServiceComponent} - WSO2 Carbon started in 85 sec
TID: [-1] [] [2021-03-02 12:20:41,042]  INFO {org.wso2.carbon.databridge.core.DataBridge} - user admin connected
TID: [-1] [] [2021-03-02 12:20:41,062] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Could not retrieve subscriptions for tenantDomain : carbon.super
TID: [-1] [] [2021-03-02 12:20:41,090] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Could not retrieve subscriptions for tenantDomain : carbon.super
TID: [-1] [] [2021-03-02 12:20:41,091] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Could not retrieve subscriptions for tenantDomain : carbon.super
TID: [-1] [] [2021-03-02 12:20:41,092] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Could not retrieve subscriptions for tenantDomain : carbon.super
TID: [-1] [] [2021-03-02 12:20:41,096] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Could not retrieve subscriptions for tenantDomain : carbon.super
TID: [-1] [] [2021-03-02 12:20:41,097] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Could not retrieve subscriptions for tenantDomain : carbon.super
TID: [-1] [] [2021-03-02 12:20:41,097] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Could not retrieve subscriptions for tenantDomain : carbon.super
TID: [-1] [] [2021-03-02 12:20:41,113] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl} - Exception while loading ApplicationKeyMapping org.wso2.carbon.apimgt.keymgt.model.exception.Dat
aLoadingException: Error while retrieving subscription from /application-key-mappings
TID: [-1] [] [2021-03-02 12:20:41,115] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl} - Exception while loading Subscriptions org.wso2.carbon.apimgt.keymgt.model.exception.DataLoading
Exception: Error while retrieving subscription from /subscriptions
TID: [-1] [] [2021-03-02 12:20:41,116] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl} - Exception while loading APIs org.wso2.carbon.apimgt.keymgt.model.exception.DataLoadingException
: Error while retrieving subscription from /apis?gatewayLabel=Production+and+Sandbox
TID: [-1] [] [2021-03-02 12:20:41,149] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl} - Exception while loading Subscription Policies org.wso2.carbon.apimgt.keymgt.model.exception.Dat
aLoadingException: Error while retrieving subscription from /subscription-policies
TID: [-1] [] [2021-03-02 12:20:41,149] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl} - Exception while loading api Policies org.wso2.carbon.apimgt.keymgt.model.exception.DataLoadingE
xception: Error while retrieving subscription from /api-policies
TID: [-1] [] [2021-03-02 12:20:41,150] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl} - Exception while loading Application Policies org.wso2.carbon.apimgt.keymgt.model.exception.Data
LoadingException: Error while retrieving subscription from /application-policies
TID: [-1] [] [2021-03-02 12:20:41,150] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl} - Exception while loading Applications org.wso2.carbon.apimgt.keymgt.model.exception.DataLoadingE
xception: Error while retrieving subscription from /applications
TID: [-1] [] [2021-03-02 12:20:41,097] ERROR {org.wso2.carbon.apimgt.throttle.policy.deployer.utils.PolicyUtil} - Error in retrieving throttle policies org.wso2.carbon.apimgt.throttle.policy.deployer.exception.T
hrottlePolicyDeployerException: Event-Hub status code is : 404
        at org.wso2.carbon.apimgt.throttle.policy.deployer.PolicyRetriever.getPolicies(PolicyRetriever.java:203)
        at org.wso2.carbon.apimgt.throttle.policy.deployer.PolicyRetriever.getAllSubscriptionPolicies(PolicyRetriever.java:87)
        at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.PolicyUtil.deployAllPolicies(PolicyUtil.java:157)
        at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.ThrottlePolicyStartupListener.run(ThrottlePolicyStartupListener.java:69)
        at java.base/java.lang.Thread.run(Thread.java:834)

TID: [-1] [] [2021-03-02 12:20:41,201]  INFO {org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener} - Synapse Artifacts deployed Successfully in the Gateway
TID: [-1] [] [2021-03-02 12:20:41,378] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Could not retrieve subscriptions for tenantDomain : carbon.super
TID: [-1] [] [2021-03-02 12:20:41,383] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl} - Exception while loading Scopes org.wso2.carbon.apimgt.keymgt.model.exception.DataLoadingExcepti
on: Error while retrieving subscription from /scopes
TID: [-1] [] [2021-03-02 12:20:41,635]  INFO {org.apache.axis2.transport.http.HTTPSender} - Unable to sendViaPost to url[https://localhost:9443/services/AuthenticationAdmin] org.apache.axis2.AxisFault: Transport error: 404 Error: 
        at org.apache.axis2.transport.http.HTTPSender.handleResponse(HTTPSender.java:395)
        at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:224)
        at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:82)
        at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:459)
        at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:286)
        at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
        at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:442)
        at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228)
        at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
        at org.wso2.carbon.authenticator.stub.AuthenticationAdminStub.login(AuthenticationAdminStub.java:1343)
        at org.wso2.carbon.apimgt.impl.utils.LocalEntryAdminClient.gatewayLogin_aroundBody4(LocalEntryAdminClient.java:122)
        at org.wso2.carbon.apimgt.impl.utils.LocalEntryAdminClient.gatewayLogin(LocalEntryAdminClient.java:105)
        at org.wso2.carbon.apimgt.impl.utils.LocalEntryAdminClient.setup_aroundBody2(LocalEntryAdminClient.java:94)
        at org.wso2.carbon.apimgt.impl.utils.LocalEntryAdminClient.setup(LocalEntryAdminClient.java:91)
        at org.wso2.carbon.apimgt.impl.utils.LocalEntryAdminClient.setupLocalEntryClient_aroundBody0(LocalEntryAdminClient.java:66)
        at org.wso2.carbon.apimgt.impl.utils.LocalEntryAdminClient.setupLocalEntryClient(LocalEntryAdminClient.java:61)
        at org.wso2.carbon.apimgt.impl.utils.LocalEntryAdminClient.<init>(LocalEntryAdminClient.java:82)
        at org.wso2.carbon.apimgt.gateway.GoogleAnalyticsConfigDeployer.deploy_aroundBody0(GoogleAnalyticsConfigDeployer.java:56)
        at org.wso2.carbon.apimgt.gateway.GoogleAnalyticsConfigDeployer.deploy(GoogleAnalyticsConfigDeployer.java:53)
        at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.lambda$0_aroundBody30(GatewayStartupListener.java:125)
        at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.lambda$0(GatewayStartupListener.java:123)
        at java.base/java.lang.Thread.run(Thread.java:834)

TID: [-1] [] [2021-03-02 12:20:41,637] ERROR {org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener} - org.wso2.carbon.apimgt.api.APIManagementException: Error while deploying Google analytics configuration

```

Now trying to invoke the same API results in a 404 being returned

```
<am:fault xmlns:am="http://wso2.org/apimanager"><am:code>404</am:code><am:type>Status report</am:type><am:message>Not Found</am:message><am:description>The requested resource is not available.</am:description></am:fault>
```
### Steps to reproduce:
1. Deploy PIzzashack API
2. Subscribe to and invoke the API
3. Restart the APIM Server
4. Invoke the same API again

**Comment by uvindra** [comment]
After the restart, undeploying the revision and then restoring that same revision resulted in the following NPE

```
TID: [-1] [] [2021-03-02 15:08:40,215] ERROR {org.apache.axis2.transport.base.threads.NativeWorkerPool} - Uncaught exception java.lang.NullPointerException
        at org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl.removeAPI_aroundBody48(SubscriptionDataStoreImpl.java:597)
        at org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl.removeAPI(SubscriptionDataStoreImpl.java:596)
        at org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl.addOrUpdateAPIRevisionWithUrlTemplates_aroundBody80(SubscriptionDataStoreImpl.java:722)
        at org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl.addOrUpdateAPIRevisionWithUrlTemplates(SubscriptionDataStoreImpl.java:714)
        at org.wso2.carbon.apimgt.keymgt.service.KeyManagerDataServiceImpl.updateDeployedAPIRevision_aroundBody46(KeyManagerDataServiceImpl.java:455)
        at org.wso2.carbon.apimgt.keymgt.service.KeyManagerDataServiceImpl.updateDeployedAPIRevision(KeyManagerDataServiceImpl.java:443)
        at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage_aroundBody2(GatewayJMSMessageListener.java:131)
        at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage(GatewayJMSMessageListener.java:118)
        at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage_aroundBody0(GatewayJMSMessageListener.java:93)
        at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage(GatewayJMSMessageListener.java:69)
        at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:645)
        at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:544)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

This could be related to the fact that data wasnt loaded on the restart

**Comment by uvindra** [comment]
Note that the initial startup errors thrown due to **DataLoadingException** do not  show a stack trace in the logs. This indicates that exception may have not been properly logged which makes it difficult to pin point the origin of the exception. So even if this issue is not reproducible we should take another look exception logging in this code and correct it.

**Comment by CrowleyRajapakse** [comment]
possible fix https://github.com/wso2/carbon-apimgt/commit/1d0bb8de0f8880cc3601e68ad8b86b5ccdb09b4c
couldn't reproduce in the latest
