### ISSUE TITLE
Basic Auth invocation gives an error

### ISSUE THREAD

**Issue by chanikag** [wso2/product-apim#10074]
### Description:
When invoking an API which is secured using basic auth gives following error,

ERROR - APIAuthenticationHandler API authentication failure due to Unclassified Authentication Failure
org.wso2.carbon.apimgt.gateway.handlers.security.APISecurityException: org.apache.axis2.databinding.ADBException: Unexpected subelement {http://dto.impl.apimgt.carbon.wso2.org/xsd}cached
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate_aroundBody42(APIAuthenticationHandler.java:436) ~[org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate(APIAuthenticationHandler.java:416) ~[org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest_aroundBody36(APIAuthenticationHandler.java:347) [org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest(APIAuthenticationHandler.java:315) [org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.apache.synapse.api.API.process(API.java:391) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:107) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:127) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:59) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:75) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:67) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:99) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) [axis2_1.6.1.wso2v41.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:369) [synapse-nhttp-transport_2.1.7.wso2v205.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:189) [synapse-nhttp-transport_2.1.7.wso2v205.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]

### Steps to reproduce:

Follow https://apim.docs.wso2.com/en/latest/learn/api-security/api-authentication/secure-apis-using-basic-authentication/

### Affected Product Version:
APIM-4.0.0 Alpha

**Comment by malinthaprasan** [comment]
Fixed by https://github.com/wso2/carbon-apimgt/pull/9985 by @tharindu1st
