### ISSUE TITLE
[3.2.0] Error When Saving OAuth2 Endpoint Security Configurations

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#10112]
### Description:

In APIM v3.2.0, the following NPE/ClassCast Exception trace is produced when trying to save the Production endpoint with OAuth2 Endpoint security configurations. 

```log
ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
    java.lang.ClassCastException: org.json.JSONObject$Null cannot be cast to java.lang.String
    at org.wso2.carbon.apimgt.impl.APIGatewayManager.setSecureVaultPropertyToBeAdded_aroundBody16(APIGatewayManager.java:470) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
    at org.wso2.carbon.apimgt.impl.APIGatewayManager.setSecureVaultPropertyToBeAdded(APIGatewayManager.java:444) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
    at org.wso2.carbon.apimgt.impl.APIGatewayManager.createAPIGatewayDTOtoPublishAPI_aroundBody6(APIGatewayManager.java:374) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
    at org.wso2.carbon.apimgt.impl.APIGatewayManager.createAPIGatewayDTOtoPublishAPI(APIGatewayManager.java:281) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
    at org.wso2.carbon.apimgt.impl.APIGatewayManager.publishAPIToGatewayEnvironment_aroundBody4(APIGatewayManager.java:214) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
    at org.wso2.carbon.apimgt.impl.APIGatewayManager.publishAPIToGatewayEnvironment(APIGatewayManager.java:199) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
    at org.wso2.carbon.apimgt.impl.APIGatewayManager.publishToGateway_aroundBody2(APIGatewayManager.java:148) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
    at org.wso2.carbon.apimgt.impl.APIGatewayManager.publishToGateway(APIGatewayManager.java:118) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.publishToGateway_aroundBody122(APIProviderImpl.java:2458) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.publishToGateway(APIProviderImpl.java:2430) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.updateAPI_aroundBody80(APIProviderImpl.java:1502) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.updateAPI(APIProviderImpl.java:1315) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
    at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.manageAPI_aroundBody12(UserAwareAPIProvider.java:137) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
    at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.manageAPI(UserAwareAPIProvider.java:126) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
    at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.apisApiIdPut(ApisApiServiceImpl.java:921) ~[classes/:?]
    at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.apisApiIdPut(ApisApi.java:690) ~[classes/:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
```

### Steps to reproduce:

- Configure APIM 3.2.0 (1612881524595) with Secure Vault enabled. Following is the `deployment.toml` configuration to enable the SecureVault

  ```toml
  [apim]
  enable_secure_vault = true
  ```
- Execute the `Ciphertool` with the following command from `<apim>/bin` directory

  ```sh
  ./ciphertool.sh -Dconfigure
  ```
- Publish an API and configure the Production endpoint with OAuth2 Security - Resource Owner Credentials configurations (leave the password field as empty)
- Save the configurations and Publish the API (will observe the above-mentioned trace in the logs)
- Once published, again edit the Production endpoint security configurations and change to Client Credentials Grant Type, and save the configurations
- Then Save (Publish) the API (will observe the above-mentioned trace in the logs)

### Additional Observations

The endpoint security configurations are missing the required field validations. The Endpoint security configurations can be stored with an empty (untouched) password field when configuring the Endpoint security with OAuth2 - Resource Owner Credentials grant type. Please find the reproducing steps below

- Start the API Manager and create and publish an API
- Navigate to the Endpoints section and configure the endpoint security for the Production Endpoint with the following
- Choose OAuth2 and Resource Owner Credentials grant and perform the following step
- Fill the `Token`, `Client ID`, `Client Secret`, and `Username` fields and leave the `Password` field as empty and untouched
- Save the configurations

With the above-mentioned steps, it is possible to save the endpoint configurations without the required field `Password`

### Affected Product Version:

- WSO2 APIM 3.2.0

**Comment by RakhithaRR** [comment]
Cannot reproduce this issue in the latest packs
