### ISSUE TITLE
ClassNotFoundException when starting up key manager node in distributed setup

### ISSUE THREAD

**Issue by chanikag** [wso2/product-apim#10124]
### Description:
When starting up the KM node with -Dprofile=api-key-manager it throws the following error.

FATAL - CarbonServerManager WSO2 Carbon initialization Failed
org.apache.axis2.AxisFault: Exception occured while loading the Axis configuration from /Users/chanika/Documents/asyncAPI/alpha/setup/km/wso2am-4.0.0-alpha/repository/conf/axis2/axis2.xml
	at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:194) ~[org.wso2.carbon.core_4.6.1.jar:?]
	at org.apache.axis2.context.ConfigurationContextFactory.createConfigurationContext(ConfigurationContextFactory.java:64) ~[axis2_1.6.1.wso2v41.jar:?]
	at org.wso2.carbon.core.CarbonConfigurationContextFactory.createNewConfigurationContext(CarbonConfigurationContextFactory.java:65) ~[org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:415) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
Caused by: org.apache.axis2.deployment.DeploymentException: org.apache.synapse.transport.passthru.PassThroughHttpSender cannot be found by axis2_1.6.1.wso2v41
	at org.apache.axis2.deployment.AxisConfigBuilder.processTransportSenders(AxisConfigBuilder.java:713) ~[axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.deployment.AxisConfigBuilder.populateConfig(AxisConfigBuilder.java:125) ~[axis2_1.6.1.wso2v41.jar:?]
	at org.wso2.carbon.core.CarbonAxisConfigurator.populateAxisConfiguration(CarbonAxisConfigurator.java:341) ~[org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:192) ~[org.wso2.carbon.core_4.6.1.jar:?]
	... 8 more
Caused by: java.lang.ClassNotFoundException: org.apache.synapse.transport.passthru.PassThroughHttpSender cannot be found by axis2_1.6.1.wso2v41
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_221]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_221]
	at org.apache.axis2.util.Loader.loadClass(Loader.java:261) ~[axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.deployment.AxisConfigBuilder.processTransportSenders(AxisConfigBuilder.java:687) ~[axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.deployment.AxisConfigBuilder.populateConfig(AxisConfigBuilder.java:125) ~[axis2_1.6.1.wso2v41.jar:?]
	at org.wso2.carbon.core.CarbonAxisConfigurator.populateAxisConfiguration(CarbonAxisConfigurator.java:341) ~[org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:192) ~[org.wso2.carbon.core_4.6.1.jar:?]
	... 8 more

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Arshardh** [comment]
When the alpha pack was tested with the profile key manager and optimize flag, I could not reproduce this issue.

**Comment by chanikag** [comment]
The doc doesn't have --optimize flag in the setup guide. Shall we include that if it is a must.

**Comment by malinthaprasan** [comment]
moved to docs-apim.
