### ISSUE TITLE
Issue when enabling email as username for tenants

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#10153]
### Description:
Following issues occurred when enabling email as username for tenants.

If we follow the steps mentioned in the 4.0.0 documentation (which points IS documentation - [1]) and enable email as username following error gets printed in the logs:

```
ERROR - DataEndpointConnectionWorker Error while trying to connect to the endpoint. Cannot borrow client for ssl://172.17.0.1:9712.
org.wso2.carbon.databridge.agent.exception.DataEndpointLoginException: Cannot borrow client for ssl://172.17.0.1:9712.
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:145) ~[org.wso2.carbon.databridge.agent_5.2.34.jar:?]
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:59) [org.wso2.carbon.databridge.agent_5.2.34.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: org.wso2.carbon.databridge.agent.exception.DataEndpointLoginException: Error while trying to login to data receiver :/172.17.0.1:9712
	at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryDataEndpoint.login(BinaryDataEndpoint.java:50) ~[org.wso2.carbon.databridge.agent_5.2.34.jar:?]
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:139) ~[org.wso2.carbon.databridge.agent_5.2.34.jar:?]
	... 6 more
Caused by: org.wso2.carbon.databridge.commons.exception.AuthenticationException: java.lang.NullPointerException
	at sun.reflect.GeneratedConstructorAccessor391.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_171]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_171]
	at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryEventSender.processResponse(BinaryEventSender.java:163) ~[org.wso2.carbon.databridge.agent_5.2.34.jar:?]
	at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryDataEndpoint.login(BinaryDataEndpoint.java:44) ~[org.wso2.carbon.databridge.agent_5.2.34.jar:?]
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:139) ~[org.wso2.carbon.databridge.agent_5.2.34.jar:?]
	... 6 more
```

And the API invocation in tenants is failing with the following error trace:

```
INFO - LogMediator To: local://axis2services/pizzashack/1.0.0/menu, MessageID: urn:uuid:7680c12c-f797-4779-90d5-1a2b12fdb222, Direction: request
```

2. As a workaround when trying the suggestion provided in [2] (Configured super admin username as `admin@wso2.com@carbon.super`), API invocation was successful, but following error is thrown when loading the tenant:

```
ERROR - ReservedUserCreationObserver Error occurred while getting the realm configuration, User store properties might not be returned
org.wso2.carbon.user.core.UserStoreException: 31301 - Username apim_reserved_user is not valid. User name must be a non null string with following format, ^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:210) ~[org.wso2.carbon.user.core_4.6.1.jar:?]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4663) ~[org.wso2.carbon.user.core_4.6.1.jar:?]
	at org.wso2.is.key.manager.core.observers.ReservedUserCreationObserver.createReservedUser(ReservedUserCreationObserver.java:69) [wso2is.key.manager.core_1.2.5.jar:?]
	at org.wso2.is.key.manager.core.observers.ReservedUserCreationObserver.createdConfigurationContext(ReservedUserCreationObserver.java:47) [wso2is.key.manager.core_1.2.5.jar:?]
	at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.createTenantConfigurationContext(TenantAxisUtils.java:356) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.getTenantConfigurationContext(TenantAxisUtils.java:148) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.getTenantAxisConfiguration(TenantAxisUtils.java:104) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.is.key.manager.core.tokenmgt.util.TokenMgtUtil.loadTenantConfigBlockingMode(TokenMgtUtil.java:350) [wso2is.key.manager.core_1.2.5.jar:?]
	at org.wso2.is.key.manager.core.tokenmgt.issuers.AbstractScopesIssuer.getAppScopes(AbstractScopesIssuer.java:136) [wso2is.key.manager.core_1.2.5.jar:?]
	at org.wso2.is.key.manager.core.tokenmgt.issuers.RoleBasedScopesIssuer.getScopes(RoleBasedScopesIssuer.java:299) [wso2is.key.manager.core_1.2.5.jar:?]
	at org.wso2.is.key.manager.core.tokenmgt.issuers.RoleBasedScopesIssuer.validateScope(RoleBasedScopesIssuer.java:120) [wso2is.key.manager.core_1.2.5.jar:?]
	at org.wso2.carbon.identity.oauth2.authz.handlers.AbstractResponseTypeHandler.validateScope(AbstractResponseTypeHandler.java:113) [org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	at org.wso2.carbon.identity.oauth2.authz.AuthorizationHandlerManager.validateScope(AuthorizationHandlerManager.java:198) [org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	at org.wso2.carbon.identity.oauth2.authz.AuthorizationHandlerManager.validateAuthzRequest(AuthorizationHandlerManager.java:157) [org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	at org.wso2.carbon.identity.oauth2.authz.AuthorizationHandlerManager.handleAuthorization(AuthorizationHandlerManager.java:92) [org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	at org.wso2.carbon.identity.oauth2.OAuth2Service.authorize(OAuth2Service.java:105) [org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.authorize(OAuth2AuthzEndpoint.java:2288) [classes/:?]
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleUserConsent(OAuth2AuthzEndpoint.java:964) [classes/:?]
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleConsent(OAuth2AuthzEndpoint.java:1855) [classes/:?]
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.doUserAuthorization(OAuth2AuthzEndpoint.java:1829) [classes/:?]
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleSuccessfulAuthentication(OAuth2AuthzEndpoint.java:714) [classes/:?]
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleAuthenticationResponse(OAuth2AuthzEndpoint.java:685) [classes/:?]
	.....
Caused by: java.security.PrivilegedActionException
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:196) ~[org.wso2.carbon.user.core_4.6.1.jar:?]
	... 83 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:199) ~[org.wso2.carbon.user.core_4.6.1.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:196) ~[org.wso2.carbon.user.core_4.6.1.jar:?]
	... 83 more
Caused by: org.wso2.carbon.user.core.UserStoreException: 31301 - Username apim_reserved_user is not valid. User name must be a non null string with following format, ^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4851) ~[org.wso2.carbon.user.core_4.6.1.jar:?]
	at sun.reflect.NativeMethodAccessorI
```

[1] https://is.docs.wso2.com/en/5.10.0/learn/using-email-address-as-the-username/
[2] https://github.com/wso2/product-apim/issues/2618

**Comment by tharindu1st** [comment]
@Arshardh

**Comment by CrowleyRajapakse** [comment]
Didn't face above issues when following https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords/#setup-an-e-mail-login doc,

API could could be invoked with a tenant user without above error as well.

Tested in carbon-apimgt- 9.0.79

Didn't try to login or do anything with apim_reserved_user, since it might be a user for internal product usage.
<img width="1653" alt="Screenshot 2021-03-25 at 14 21 05" src="https://user-images.githubusercontent.com/23296184/112445838-91b23f00-8d75-11eb-9ad1-689d533d4c85.png">

**Comment by CrowleyRajapakse** [comment]
Above error can be reproduced if we add following config and create a new tenant and login

[user_store]
type = "database_unique_id"
username_java_regex = '^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}'
username_java_script_regex = '^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$'
