### ISSUE TITLE
NPE when undeploying revisions

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim#10179]
### Description:
If one gateway is subscribed to more than one label and an API revision is published to both of these labels, during the undeploy path, if we undeploy one gateway after another, last gateway undeployment will produce a Null pointer exception as below. 
```
[2021-03-08 10:24:05,850] ERROR - NativeWorkerPool Uncaught exception
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl.removeAPI_aroundBody48(SubscriptionDataStoreImpl.java:597) ~[org.wso2.carbon.apimgt.keymgt_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl.removeAPI(SubscriptionDataStoreImpl.java:596) ~[org.wso2.carbon.apimgt.keymgt_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl.addOrUpdateAPIRevisionWithUrlTemplates_aroundBody80(SubscriptionDataStoreImpl.java:722) ~[org.wso2.carbon.apimgt.keymgt_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl.addOrUpdateAPIRevisionWithUrlTemplates(SubscriptionDataStoreImpl.java:714) ~[org.wso2.carbon.apimgt.keymgt_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.keymgt.service.KeyManagerDataServiceImpl.updateDeployedAPIRevision_aroundBody46(KeyManagerDataServiceImpl.java:455) ~[org.wso2.carbon.apimgt.keymgt_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.keymgt.service.KeyManagerDataServiceImpl.updateDeployedAPIRevision(KeyManagerDataServiceImpl.java:443) ~[org.wso2.carbon.apimgt.keymgt_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage_aroundBody2(GatewayJMSMessageListener.java:131) ~[org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage(GatewayJMSMessageListener.java:118) ~[org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage_aroundBody0(GatewayJMSMessageListener.java:93) ~[org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage(GatewayJMSMessageListener.java:69) ~[org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:645) ~[org.wso2.carbon.apimgt.jms.listener_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:544) ~[org.wso2.carbon.apimgt.jms.listener_9.0.5.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

### Steps to reproduce:

1. Subscribe to more than one gateway label for an gateway.
2. Deploy the gateway in both of these labels
3. Undeploy one by one.

### Affected Product Version:
4.0.0-alpha

**Comment by CrowleyRajapakse** [comment]
possible fix and https://github.com/wso2/carbon-apimgt/commit/1d0bb8de0f8880cc3601e68ad8b86b5ccdb09b4c
couldn't reproduce in the latest
