### ISSUE TITLE
Exception Thrown in server shutdown when websocket API used.

### ISSUE THREAD

**Issue by tharindu1st** [wso2/product-apim#10172]
### Description:
Exception Thrown in server shutdown when websocket API used.

### Steps to reproduce:
Create websocket api.
Consume websocket api.
Stop the server.

021-03-07 01:20:12,006] ERROR - InboundEndpoint Unable to destroy Inbound endpoint
java.lang.NullPointerException: null
	at org.apache.axis2.context.AbstractContext.needPropertyDifferences(AbstractContext.java:239) ~[axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.context.AbstractContext.setProperty(AbstractContext.java:202) ~[axis2_1.6.1.wso2v41.jar:?]
	at org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketSourceHandler.createAxis2MessageContext(InboundWebsocketSourceHandler.java:564) ~[org.wso2.carbon.inbound.endpoint_4.7.81.jar:?]
	at org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketSourceHandler.createSynapseMessageContext(InboundWebsocketSourceHandler.java:537) ~[org.wso2.carbon.inbound.endpoint_4.7.81.jar:?]
	at org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketSourceHandler.getSynapseMessageContext(InboundWebsocketSourceHandler.java:513) ~[org.wso2.carbon.inbound.endpoint_4.7.81.jar:?]
	at org.wso2.carbon.inbound.endpoint.protocol.websocket.management.WebsocketEndpointManager.closeEndpoint(WebsocketEndpointManager.java:199) ~[org.wso2.carbon.inbound.endpoint_4.7.81.jar:?]
	at org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketListener.destroy(InboundWebsocketListener.java:59) ~[org.wso2.carbon.inbound.endpoint_4.7.81.jar:?]
	at org.apache.synapse.inbound.InboundEndpoint.destroy(InboundEndpoint.java:156) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.config.SynapseConfiguration.destroy(SynapseConfiguration.java:1576) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.Axis2SynapseController.destroySynapseConfiguration(Axis2SynapseController.java:542) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.ServerManager.stop(ServerManager.java:283) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.wso2.carbon.mediation.initializer.ServiceBusInitializer.deactivate(ServiceBusInitializer.java:230) [org.wso2.carbon.mediation.initializer_4.7.81.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.deactivate(ServiceComponent.java:387) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.deactivate(ServiceComponentProp.java:161) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.dispose(ServiceComponentProp.java:387) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.dispose(ServiceComponentProp.java:102) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.disposeInstances(InstanceProcess.java:344) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.disposeInstances(InstanceProcess.java:306) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:368) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:227) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.application.deployer.internal.AppDeployerServiceComponent.deactivate(AppDeployerServiceComponent.java:138) [org.wso2.carbon.application.deployer_4.6.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.deactivate(ServiceComponent.java:387) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.deactivate(ServiceComponentProp.java:161) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.dispose(ServiceComponentProp.java:387) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.dispose(ServiceComponentProp.java:102) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.disposeInstances(InstanceProcess.java:366) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.disposeInstances(InstanceProcess.java:306) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:368) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.

**Comment by tharindu1st** [comment]
@Nirothipan @senthuran16
