### ISSUE TITLE
[3.1.0 -> 4.0.0 Migration] Error when Migrating API Products

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim#10176]
### Description:
Setup: APIM 3.1.0 with ISKM 5.10.0
When the old APIM version is having API products and when we run the migration client to migtarate to APIM 4.0.0, the following error log in printed on the server console.
```
ERROR - APIMMigrationService Generic exception occurred while migrating
java.lang.NullPointerException: null
	at java.io.StringReader.<init>(StringReader.java:50) ~[?:1.8.0_241]
	at org.wso2.carbon.apimgt.impl.importexport.utils.CommonUtil.writeFile_aroundBody12(CommonUtil.java:205) ~[org.wso2.carbon.apimgt.impl_9.0.7.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.utils.CommonUtil.writeFile(CommonUtil.java:202) ~[org.wso2.carbon.apimgt.impl_9.0.7.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.utils.CommonUtil.writeToYamlOrJson_aroundBody34(CommonUtil.java:451) ~[org.wso2.carbon.apimgt.impl_9.0.7.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.utils.CommonUtil.writeToYamlOrJson(CommonUtil.java:442) ~[org.wso2.carbon.apimgt.impl_9.0.7.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ExportUtils.addAPIProductMetaInformationToArchive(ExportUtils.java:946) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.7.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ExportUtils.exportApiProduct(ExportUtils.java:238) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.7.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.ImportExportAPIServiceImpl.exportAPIProduct(ImportExportAPIServiceImpl.java:127) ~[?:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPIProductRevision_aroundBody602(APIProviderImpl.java:9980) ~[org.wso2.carbon.apimgt.impl_9.0.7.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPIProductRevision(APIProviderImpl.java:9927) ~[org.wso2.carbon.apimgt.impl_9.0.7.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addAPIProductRevision(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_9.0.7.jar:?]
	at org.wso2.carbon.apimgt.migration.client.MigrateFrom320.apiRevisionRelatedMigration(MigrateFrom320.java:296) ~[org.wso2.carbon.apimgt.migrate.client-4.0.0.jar:4.0.0-${buildNumber}]
	at org.wso2.carbon.apimgt.migration.APIMMigrationService.completedServerStartup(APIMMigrationService.java:182) [org.wso2.carbon.apimgt.migrate.client-4.0.0.jar:4.0.0-${buildNumber}]
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.notifyAfter(CarbonCoreServiceComponent.java:264) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:218) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:323) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.registerThrottlingAgent(ThrottlingAgentServiceComponent.java:118) [org.wso2.carbon.tenant.throttling.agent_4.9.8.jar:?]
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.activate(ThrottlingAgentServiceComponent.java:96) [org.wso2.carbon.tenant.throttling.agent_4.9.8.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_241]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
```

### Steps to reproduce:
- Run the APIM migration client when the old APIM version is having an API Product

### Environment details (with versions):
- OS: Ubuntu 20.04.2 LTS
- Database: MySQL Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64

**Comment by isharac** [comment]
This error was not observed in APIM 4.0.0-beta
