### ISSUE TITLE
Tenant Websocket APIS Couldn't invoke

### ISSUE THREAD

**Issue by tharindu1st** [wso2/product-apim#10183]
### Description:
When invoking Tenant WebSocket APIS  Thrrowing
2021-03-08 13:13:33,798]  INFO - LogMediator STATUS = Message dispatched to the main sequence. Invalid URL., RESOURCE = /, HEALTH CHECK URL = null
[2021-03-08 13:13:33,798] ERROR - Axis2Sender  Unexpected error sending message back
org.apache.axis2.AxisFault: Unable to determine wsa:Action for outbound message
	at org.apache.axis2.handlers.addressing.AddressingOutHandler$WSAHeaderWriter.processWSAAction(AddressingOutHandler.java:311) ~[org.wso2.carbon.addressing_4.6.1.jar:?]
	at org.apache.axis2.handlers.addressing.AddressingOutHandler$WSAHeaderWriter.writeHeaders(AddressingOutHandler.java:228) ~[org.wso2.carbon.addressing_4.6.1.jar:?]
	at org.apache.axis2.handlers.addressing.AddressingOutHandler.doInvoke(AddressingOutHandler.java:134) ~[org.wso2.carbon.addressing_4.6.1.jar:?]
	at org.apache.axis2.handlers.AbstractTemplatedHandler.invoke(AbstractTemplatedHandler.java:44) ~[axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340) ~[axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.engine.Phase.invoke(Phase.java:313) ~[axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261) ~[axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:426) ~[axis2_1.6.1.wso2v41.jar:?]
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:213) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:569) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:120) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.mediators.filters.InMediator.mediate(InMediator.java:74) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:1094) [synapse-core_2.1.7.wso2v205.jar:2.1.7-wso2v205]
	at org.wso2.carbon.websocket.transport.WebSocketClientHandler.injectToSequence(WebSocketClientHandler.java:315) [org.wso2.carbon.websocket.transport_4.7.81.jar:?]
	at org.wso2.carbon.websocket.transport.WebSocketClientHandler.handlePassthroughTextFrame(WebSocketClientHandler.java:164) [org.wso2.carbon.websocket.transport_4.7.81.jar:?]
	at org.wso2.carbon.websocket.transport.WebSocketClientHandler.handleWebSocketFrame(WebSocketClientHandler.java:186) [org.wso2.carbon.websocket.transport_4.7.81.jar:?]
	at org.wso2.carbon.websocket.transport.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:244) [org.wso2.carbon.websocket.transport_4.7.81.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [io.netty.codec_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [io.netty.codec_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [io.netty.codec_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [io.netty.common_4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.common_4.1.34.Final.jar:4.1.34.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
[2021-03-08 13:13:33,844]  WARN - Axis2SynapseEnvironment Executing fault handler due to exception encountered

**Comment by senthuran16** [comment]
Closing this since https://github.com/wso2/product-apim/issues/10250 mentions this same issue. Let's use https://github.com/wso2/product-apim/issues/10250 to track this.
