### ISSUE TITLE
JMSException getting printed at APIM-4.0.0 alpha pack startup

### ISSUE THREAD

**Issue by amilam** [wso2/product-apim#10199]
Below ERROR log was observed when starting the pack.

TID: [-1] [] [2021-03-09 12:14:09,391] ERROR {org.wso2.carbon.apimgt.gateway.listeners.APIMgtGatewayCacheMessageListener} - JMSException occurred when processing the received message com.fasterxml.jackson.core.JsonParseException: Unexpected character ('a' (code 97)): was expecting comma to separate Object entries
 at [Source: (String)"{"event":{"payloadData":{"type":"gatewayUsernameCache","value":"["apim_reserved_user@carbon.super"]"}}}"; line: 1, column: 68]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2293)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:917)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:250)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4270)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2720)
	at org.wso2.carbon.apimgt.gateway.listeners.APIMgtGatewayCacheMessageListener.onMessage_aroundBody0(APIMgtGatewayCacheMessageListener.java:53)
	at org.wso2.carbon.apimgt.gateway.listeners.APIMgtGatewayCacheMessageListener.onMessage(APIMgtGatewayCacheMessageListener.java:43)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:645)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:544)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

### Environment details (with versions):
- OS: MacOS

**Comment by 1akshitha** [comment]
Same error can be observed when adding a new user.

**Comment by malinthaprasan** [comment]
Fixed in the latest pack.
