### ISSUE TITLE
ClassMediatorFactory Error loading class : org.wso2.apim.mediators.oauth.OAuthMediator - Class not found

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/product-apim#10235]
### Description:

Occurred during 2.1 to 4.0 mssql - client prod db migration

### Error

`[2021-03-11 11:34:45,056]  INFO - DependencyTracker API : Nexgen_GetApptByProvider:vv1.0 was added to the Synapse configuration successfully
[2021-03-11 11:34:45,057]  INFO - API {api:Nexgen_GetApptByProvider:vv1.0} Initializing API: Nexgen_GetApptByProvider:vv1.0
[2021-03-11 11:34:45,084]  INFO - InMemoryAPIDeployer Deploying synapse artifacts of Nexgen_Native-1
[2021-03-11 11:34:45,117]  INFO - DependencyTracker Local entry : 8ee6352e-9b45-4873-83a3-bca421a23b69 was added to the Synapse configuration successfully
[2021-03-11 11:34:45,137]  INFO - DependencyTracker Endpoint : Nexgen_Native-1--v5.9.0.291_APIsandboxEndpoint was added to the Synapse configuration successfully
[2021-03-11 11:34:45,160]  INFO - DependencyTracker Endpoint : Nexgen_Native-1--v5.9.0.291_APIproductionEndpoint was added to the Synapse configuration successfully
[2021-03-11 11:34:45,164] ERROR - ClassMediatorFactory Error loading class : org.wso2.apim.mediators.oauth.OAuthMediator - Class not found
java.lang.ClassNotFoundException: org.wso2.apim.mediators.oauth.OAuthMediator cannot be found by synapse-core_2.1.7.wso2v207
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_261]
	at org.apache.synapse.config.xml.ClassMediatorFactory.createSpecificMediator(ClassMediatorFactory.java:100) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:225) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:46) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.SequenceMediatorFactory.createSpecificMediator(SequenceMediatorFactory.java:87) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:225) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.SynapseXMLConfigurationFactory.defineSequence(SynapseXMLConfigurationFactory.java:232) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.wso2.carbon.sequences.services.SequenceAdmin.addSequence(SequenceAdmin.java:412) [org.wso2.carbon.sequences_4.7.81.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence_aroundBody0(SequenceAdminServiceProxy.java:58) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence(SequenceAdminServiceProxy.java:54) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:753) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup_aroundBody2(InMemoryAPIDeployer.java:149) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup(InMemoryAPIDeployer.java:129) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup_aroundBody2(GatewayStartupListener.java:105) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup(GatewayStartupListener.java:97) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway_aroundBody16(GatewayStartupListener.java:214) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0_aroundBody26(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run_aroundBody0(GatewayStartupListener.java:297) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run(GatewayStartupListener.java:294) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
[2021-03-11 11:34:45,185]  WARN - SynapseXMLConfigurationFactory Sequence configuration: Nexgen_Native-1:v5.9.0.291--In cannot be built - Continue in fail-safe mode
org.apache.synapse.SynapseException: Error loading class : org.wso2.apim.mediators.oauth.OAuthMediator - Class not found
	at org.apache.synapse.config.xml.ClassMediatorFactory.createSpecificMediator(ClassMediatorFactory.java:105) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:225) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:46) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.SequenceMediatorFactory.createSpecificMediator(SequenceMediatorFactory.java:87) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:225) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.SynapseXMLConfigurationFactory.defineSequence(SynapseXMLConfigurationFactory.java:232) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.wso2.carbon.sequences.services.SequenceAdmin.addSequence(SequenceAdmin.java:412) [org.wso2.carbon.sequences_4.7.81.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence_aroundBody0(SequenceAdminServiceProxy.java:58) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence(SequenceAdminServiceProxy.java:54) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:753) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup_aroundBody2(InMemoryAPIDeployer.java:149) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup(InMemoryAPIDeployer.java:129) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup_aroundBody2(GatewayStartupListener.java:105) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup(GatewayStartupListener.java:97) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway_aroundBody16(GatewayStartupListener.java:214) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0_aroundBody26(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run_aroundBody0(GatewayStartupListener.java:297) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run(GatewayStartupListener.java:294) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.lang.ClassNotFoundException: org.wso2.apim.mediators.oauth.OAuthMediator cannot be found by synapse-core_2.1.7.wso2v207
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_261]
	at org.apache.synapse.config.xml.ClassMediatorFactory.createSpecificMediator(ClassMediatorFactory.java:100) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	... 23 more`

**Comment by CrowleyRajapakse** [comment]
This issue seems to be due to customised mediator, hence closing the issue
