### ISSUE TITLE
[3.1.0 -> 4.0.0 Migration] Error When Migrating an API having Mediation Policies

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim#10238]
### Description:
The following error logs when the old version has an API which has IN, OUT and FAULT mediation policies.
```
ERROR - ClassMediatorFactory Error loading class : org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtFaultHandler - Class not found
java.lang.ClassNotFoundException: org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtFaultHandler cannot be found by synapse-core_2.1.7.wso2v207
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
	at org.apache.synapse.config.xml.ClassMediatorFactory.createSpecificMediator(ClassMediatorFactory.java:100) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:225) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:46) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.SequenceMediatorFactory.createSpecificMediator(SequenceMediatorFactory.java:87) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:225) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.SynapseXMLConfigurationFactory.defineSequence(SynapseXMLConfigurationFactory.java:232) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.wso2.carbon.sequences.services.SequenceAdmin.addSequence(SequenceAdmin.java:412) [org.wso2.carbon.sequences_4.7.81.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence_aroundBody0(SequenceAdminServiceProxy.java:58) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence(SequenceAdminServiceProxy.java:54) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:753) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup_aroundBody2(InMemoryAPIDeployer.java:149) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup(InMemoryAPIDeployer.java:129) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup_aroundBody2(GatewayStartupListener.java:105) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup(GatewayStartupListener.java:97) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway_aroundBody16(GatewayStartupListener.java:214) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0_aroundBody26(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run_aroundBody0(GatewayStartupListener.java:297) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run(GatewayStartupListener.java:294) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
[2021-03-11 13:01:57,519]  WARN - SynapseXMLConfigurationFactory Sequence configuration: PizzaShack_mediation:v1.0.0--Fault cannot be built - Continue in fail-safe mode
org.apache.synapse.SynapseException: Error loading class : org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtFaultHandler - Class not found
	at org.apache.synapse.config.xml.ClassMediatorFactory.createSpecificMediator(ClassMediatorFactory.java:105) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:225) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:46) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.SequenceMediatorFactory.createSpecificMediator(SequenceMediatorFactory.java:87) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:225) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.SynapseXMLConfigurationFactory.defineSequence(SynapseXMLConfigurationFactory.java:232) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.wso2.carbon.sequences.services.SequenceAdmin.addSequence(SequenceAdmin.java:412) [org.wso2.carbon.sequences_4.7.81.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence_aroundBody0(SequenceAdminServiceProxy.java:58) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence(SequenceAdminServiceProxy.java:54) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:753) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup_aroundBody2(InMemoryAPIDeployer.java:149) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup(InMemoryAPIDeployer.java:129) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup_aroundBody2(GatewayStartupListener.java:105) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup(GatewayStartupListener.java:97) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway_aroundBody16(GatewayStartupListener.java:214) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0_aroundBody26(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run_aroundBody0(GatewayStartupListener.java:297) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run(GatewayStartupListener.java:294) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtFaultHandler cannot be found by synapse-core_2.1.7.wso2v207
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
	at org.apache.synapse.config.xml.ClassMediatorFactory.createSpecificMediator(ClassMediatorFactory.java:100) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	... 23 more
[2021-03-11 13:01:57,522] ERROR - InMemoryAPIDeployer Error in deploying PizzaShack_mediation to the Gateway 
org.apache.axis2.AxisFault: Error while adding new sequence
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence_aroundBody0(SequenceAdminServiceProxy.java:64) ~[org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence(SequenceAdminServiceProxy.java:54) ~[org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:753) ~[org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653) ~[org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup_aroundBody2(InMemoryAPIDeployer.java:149) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup(InMemoryAPIDeployer.java:129) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup_aroundBody2(GatewayStartupListener.java:105) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup(GatewayStartupListener.java:97) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway_aroundBody16(GatewayStartupListener.java:214) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0_aroundBody26(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run_aroundBody0(GatewayStartupListener.java:297) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run(GatewayStartupListener.java:294) [org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: org.wso2.carbon.sequences.common.SequenceEditorException: Error adding sequence : null
	at org.wso2.carbon.sequences.services.SequenceAdmin.addSequence(SequenceAdmin.java:429) ~[org.wso2.carbon.sequences_4.7.81.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence_aroundBody0(SequenceAdminServiceProxy.java:58) ~[org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	... 14 more
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.sequences.services.SequenceAdmin.addSequence(SequenceAdmin.java:419) ~[org.wso2.carbon.sequences_4.7.81.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence_aroundBody0(SequenceAdminServiceProxy.java:58) ~[org.wso2.carbon.apimgt.gateway_9.0.33.SNAPSHOT.jar:?]
	... 14 more
```

### Migration Setup:
Old Version: APIM 3.1.0, ISKM 5.10.0
New Version: APIM 4.0.0, IS 5.11.0
Database: MySQL Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64

## Steps to Reproduce:
Run the APIM migration client when the old APIM version is having an API which has IN, OUT and FAULT mediation policies

### Environment details (with versions):
- JDK 1.8.0_241
- Ubuntu 20.04.1 LTS

**Comment by tharindu1st** [comment]
@hisanhunais did you copy older synapse configuration files into 4.0.0 deployment. 
Since new APIM goes with API pull base approach , You didn't need to copy older artifacts into new deployment.

**Comment by tharindu1st** [comment]
We need to remove this code segment from here https://github.com/wso2/carbon-apimgt/commit/4d4ac50f5631c9c688a5fb9a4f764cfae1acbce9 @ruks

**Comment by ruks** [comment]
@hisanhunais Yes, please remove the 
org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtFaultHandler
org.wso2.carbon.apimgt.usage.publisher.APIMgtFaultHandler

But you can org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtFaultHandler class from the sequences if we support migration for synapse configs. This may not be required for the in-memory API deploy scenario.

**Comment by hisanhunais** [comment]
@tharindu1st, I **did not** manually copy older synapse configuration to 4.0.0 pack
