### ISSUE TITLE
APIs created using service catelog does not get deployed in the gateway

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-apim#10247]
### Description:
API deployment failed with the following error log

[2021-03-12 14:10:35,105] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
org.apache.axiom.om.OMException: com.ctc.wstx.exc.WstxEOFException: Unexpected EOF in prolog
 at [row,col {unknown-source}]: [32,24]
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:296) ~[axiom_1.2.11.wso2v17.jar:?]
	at org.apache.axiom.om.impl.llom.OMDocumentImpl.getOMDocumentElement(OMDocumentImpl.java:109) ~[axiom_1.2.11.wso2v17.jar:?]
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.getDocumentElement(StAXOMBuilder.java:570) ~[axiom_1.2.11.wso2v17.jar:?]
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.getDocumentElement(StAXOMBuilder.java:566) ~[axiom_1.2.11.wso2v17.jar:?]
	at org.apache.axiom.om.util.AXIOMUtil.stringToOM(AXIOMUtil.java:55) ~[axiom_1.2.11.wso2v17.jar:?]
	at org.apache.axiom.om.util.AXIOMUtil.stringToOM(AXIOMUtil.java:39) ~[axiom_1.2.11.wso2v17.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.TemplateBuilderUtil.getEndpointName(TemplateBuilderUtil.java:897) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.TemplateBuilderUtil.addEndpoints(TemplateBuilderUtil.java:818) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.TemplateBuilderUtil.createAPIGatewayDTOtoPublishAPI(TemplateBuilderUtil.java:674) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.TemplateBuilderUtil.retrieveGatewayAPIDto(TemplateBuilderUtil.java:455) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.TemplateBuilderUtil.retrieveGatewayAPIDto(TemplateBuilderUtil.java:483) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.SynapseArtifactGenerator.generateGatewayArtifact(SynapseArtifactGenerator.java:128) ~[?:?]
	at org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.RuntimeArtifactGeneratorUtil.generateRuntimeArtifact_aroundBody0(RuntimeArtifactGeneratorUtil.java:63) ~[org.wso2.carbon.apimgt.impl_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.RuntimeArtifactGeneratorUtil.generateRuntimeArtifact(RuntimeArtifactGeneratorUtil.java:37) ~[org.wso2.carbon.apimgt.impl_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.internal.service.impl.RuntimeArtifactsApiServiceImpl.runtimeArtifactsGet(RuntimeArtifactsApiServiceImpl.java:51) ~[classes/:?]
	at org.wso2.carbon.apimgt.internal.service.RuntimeArtifactsApi.runtimeArtifactsGet(RuntimeArtifactsApi.java:47) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:225) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [tomcat-servlet-api_9.0.34.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.34.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107) [org.wso2.carbon.identity.context.rewrite.valve_1.4.25.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.25.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:102) [org.wso2.carbon.identity.auth.valve_1.4.25.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [tomcat_9.0.34.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.34.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.34.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.ctc.wstx.exc.WstxEOFException: Unexpected EOF in prolog
 at [row,col {unknown-source}]: [32,24]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedEOF(StreamScanner.java:685) ~[axiom_1.2.11.wso2v17.jar:?]
	at com.ctc.wstx.sr.BasicStreamReader.handleEOF(BasicStreamReader.java:2141) ~[axiom_1.2.11.wso2v17.jar:?]
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2047) ~[axiom_1.2.11.wso2v17.jar:?]
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1131) ~[axiom_1.2.11.wso2v17.jar:?]
	at org.apache.axiom.util.stax.wrapper.XMLStreamReaderWrapper.next(XMLStreamReaderWrapper.java:225) ~[axiom_1.2.11.wso2v17.jar:?]
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.parserNext(StAXOMBuilder.java:681) ~[axiom_1.2.11.wso2v17.jar:?]
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:214) ~[axiom_1.2.11.wso2v17.jar:?]
	... 67 more
[2021-03-12 14:10:35,112] ERROR - InMemoryAPIDeployer Error deploying 3fc8121d-38ee-4b08-8214-e5b6b592b1fc in Gateway
org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.exception.ArtifactSynchronizerException: {"code":500,"message":"Internal server error","description":"The server encountered an internal error. Please contact administrator.","moreInfo":"","error":[]}Event-Hub status code is : 500
	at org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.DBRetriever.retrieveArtifact_aroundBody4(DBRetriever.java:115) ~[org.wso2.carbon.apimgt.impl_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.DBRetriever.retrieveArtifact(DBRetriever.java:96) ~[org.wso2.carbon.apimgt.impl_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.DBRetriever.retrieveArtifact_aroundBody2(DBRetriever.java:83) ~[org.wso2.carbon.apimgt.impl_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.DBRetriever.retrieveArtifact(DBRetriever.java:67) ~[org.wso2.carbon.apimgt.impl_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:89) [org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:83) [org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody20(InMemoryAPIDeployer.java:374) [org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:370) [org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage_aroundBody2(GatewayJMSMessageListener.java:137) [org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage(GatewayJMSMessageListener.java:118) [org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage_aroundBody0(GatewayJMSMessageListener.java:93) [org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage(GatewayJMSMessageListener.java:69) [org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:645) [org.wso2.carbon.apimgt.jms.listener_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:544) [org.wso2.carbon.apimgt.jms.listener_9.0.5.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[2021-03-12 14:10:35,114] ERROR - GatewayJMSMessageListener Error in deploying artifacts for 3fc8121d-38ee-4b08-8214-e5b6b592b1fcin the Gateway

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by YasasRangika** [comment]
Followed below steps when reproducing:
- Added issue occurred car file into <MI_HOME>/repository/deployment/server/carbonapps
- Started MI server
(Now the "mockapi" is included in service catalog)
- Created API using it
- Deployed new revision
- Published the API
- Logged into devportal
- Invoke get service call using try out feature
- curl http://localhost:8280/mock/v1/services gives response

seems this has been fixed in latest APIM pack. Hence we can close this issue.
