### ISSUE TITLE
Deleting an API which is already deployed failing intermittently - API cannot be deleted from the portals afterwards

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#10255]
### Description:
The issue is not always reproducible.

The API needs to be created, revised and deployed.
Then attempts to delete the API.

Gives the below errror:
```
[2021-03-14 21:59:28,238] ERROR - ApisApiServiceImpl Error while deleting API : 80a325da-f694-44b2-be1f-bcb5cdebce1c
org.wso2.carbon.apimgt.api.APIManagementException: Failed to delete Gateway Artifact80a325da-f694-44b2-be1f-bcb5cdebce1c
	at org.wso2.carbon.apimgt.impl.dao.GatewayArtifactsMgtDAO.handleException_aroundBody8(GatewayArtifactsMgtDAO.java:130) ~[org.wso2.carbon.apimgt.impl_9.0.40.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.GatewayArtifactsMgtDAO.handleException(GatewayArtifactsMgtDAO.java:127) ~[org.wso2.carbon.apimgt.impl_9.0.40.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.GatewayArtifactsMgtDAO.deleteGatewayArtifacts_aroundBody22(GatewayArtifactsMgtDAO.java:294) ~[org.wso2.carbon.apimgt.impl_9.0.40.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.GatewayArtifactsMgtDAO.deleteGatewayArtifacts(GatewayArtifactsMgtDAO.java:278) ~[org.wso2.carbon.apimgt.impl_9.0.40.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.deleteAPI_aroundBody188(APIProviderImpl.java:4113) ~[org.wso2.carbon.apimgt.impl_9.0.40.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.deleteAPI(APIProviderImpl.java:4030) ~[org.wso2.carbon.apimgt.impl_9.0.40.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.deleteAPI(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_9.0.40.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.deleteAPI(ApisApiServiceImpl.java:1498) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.deleteAPI(ApisApi.java:320) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doDelete(AbstractHTTPServlet.java:231) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:666) [tomcat-servlet-api_9.0.34.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.34.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107) [org.wso2.carbon.identity.context.rewrite.valve_1.4.25.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.25.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:102) [org.wso2.carbon.identity.auth.valve_1.4.25.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [tomcat_9.0.34.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.34.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.34.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: org.wso2.carbon.apimgt.api.APIManagementException: Failed to delete Gateway Artifact80a325da-f694-44b2-be1f-bcb5cdebce1c
	at org.wso2.carbon.apimgt.impl.dao.GatewayArtifactsMgtDAO.handleException_aroundBody8(GatewayArtifactsMgtDAO.java:130) ~[org.wso2.carbon.apimgt.impl_9.0.40.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.GatewayArtifactsMgtDAO.handleException(GatewayArtifactsMgtDAO.java:127) ~[org.wso2.carbon.apimgt.impl_9.0.40.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.GatewayArtifactsMgtDAO.deleteGatewayArtifacts_aroundBody22(GatewayArtifactsMgtDAO.java:291) ~[org.wso2.carbon.apimgt.impl_9.0.40.SNAPSHOT.jar:?]
	... 58 more
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referential integrity constraint violation: "CONSTRAINT_986: PUBLIC.AM_GW_API_DEPLOYMENTS FOREIGN KEY(API_ID) REFERENCES PUBLIC.AM_GW_PUBLISHED_API_DETAILS(API_ID) ('80a325da-f694-44b2-be1f-bcb5cdebce1c')"; SQL statement:
DELETE FROM AM_GW_PUBLISHED_API_DETAILS WHERE API_ID = ? [23503-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.message.DbException.get(DbException.java:205) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.message.DbException.get(DbException.java:181) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:373) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:390) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:265) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.table.Table.fireConstraints(Table.java:1020) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.table.Table.fireAfterRow(Table.java:1038) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.command.dml.Delete.update(Delete.java:129) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.command.CommandContainer.update(CommandContainer.java:133) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.command.Command.executeUpdate(Command.java:267) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:200) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:154) ~[h2_1.4.199.wso2v1.jar:?]
	at sun.reflect.GeneratedMethodAccessor156.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[jdbc-pool_9.0.35.wso2v1.jar:?]
	at com.sun.proxy.$Proxy49.executeUpdate(Unknown Source) ~[?:?]
	at org.wso2.carbon.apimgt.impl.dao.GatewayArtifactsMgtDAO.deleteGatewayArtifacts_aroundBody22(GatewayArtifactsMgtDAO.java:286) ~[org.wso2.carbon.apimgt.impl_9.0.40.SNAPSHOT.jar:?]
	... 58 more

```

Once this happens, the API is still visible in the search results but its deleted from the AM_DB. Hence, API cannot be deleted from the portal due to the inconsistency. API needs to be deleted from the carbon console manually.

**Comment by tharindu1st** [comment]
This can't reproduce in newer pack
