### ISSUE TITLE
[3.2.0 -> 4.0.0 Migration] Error When Migrating an API which was Used for Testing using the Test Console

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim#10277]
### Description:
The Old Version APIM had an API which was used for Testing using the Test Console. The test was initialized and a test key was generated. The following error logs when the migration client is run and the server is getting started.
```
ERROR - APIFactory Error initializing API handler: org.wso2.carbon.apimgt.gateway.handlers.security.TestKeyAuthenticator
java.lang.ClassNotFoundException: org.wso2.carbon.apimgt.gateway.handlers.security.TestKeyAuthenticator cannot be found by synapse-core_2.1.7.wso2v207
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
	at org.apache.synapse.config.xml.rest.APIFactory.defineHandler(APIFactory.java:171) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.rest.APIFactory.createAPI(APIFactory.java:113) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.rest.APIFactory.createAPI(APIFactory.java:56) [synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApi(RestApiAdmin.java:846) [org.wso2.carbon.rest.api_4.7.84.jar:?]
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApiFromString(RestApiAdmin.java:114) [org.wso2.carbon.rest.api_4.7.84.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.addApi_aroundBody0(RESTAPIAdminServiceProxy.java:50) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.addApi(RESTAPIAdminServiceProxy.java:46) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:764) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup_aroundBody2(InMemoryAPIDeployer.java:149) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup(InMemoryAPIDeployer.java:129) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup_aroundBody2(GatewayStartupListener.java:105) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup(GatewayStartupListener.java:97) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway_aroundBody16(GatewayStartupListener.java:214) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0_aroundBody26(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run_aroundBody0(GatewayStartupListener.java:297) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run(GatewayStartupListener.java:294) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
[2021-03-16 08:16:45,717] ERROR - InMemoryAPIDeployer Error in deploying PizzaShack_TestConsole to the Gateway 
org.apache.axis2.AxisFault: Error while publishing API to the Gateway. Error initializing API handler: org.wso2.carbon.apimgt.gateway.handlers.security.TestKeyAuthenticator
	at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.addApi_aroundBody0(RESTAPIAdminServiceProxy.java:55) ~[org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.addApi(RESTAPIAdminServiceProxy.java:46) ~[org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:764) ~[org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653) ~[org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup_aroundBody2(InMemoryAPIDeployer.java:149) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup(InMemoryAPIDeployer.java:129) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup_aroundBody2(GatewayStartupListener.java:105) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup(GatewayStartupListener.java:97) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway_aroundBody16(GatewayStartupListener.java:214) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0_aroundBody26(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0(GatewayStartupListener.java:203) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run_aroundBody0(GatewayStartupListener.java:297) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run(GatewayStartupListener.java:294) [org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: org.apache.synapse.SynapseException: Error initializing API handler: org.wso2.carbon.apimgt.gateway.handlers.security.TestKeyAuthenticator
	at org.apache.synapse.config.xml.rest.APIFactory.handleException(APIFactory.java:212) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.rest.APIFactory.defineHandler(APIFactory.java:201) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.rest.APIFactory.createAPI(APIFactory.java:113) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.rest.APIFactory.createAPI(APIFactory.java:56) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApi(RestApiAdmin.java:846) ~[org.wso2.carbon.rest.api_4.7.84.jar:?]
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApiFromString(RestApiAdmin.java:114) ~[org.wso2.carbon.rest.api_4.7.84.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.addApi_aroundBody0(RESTAPIAdminServiceProxy.java:50) ~[org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	... 14 more
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.apimgt.gateway.handlers.security.TestKeyAuthenticator cannot be found by synapse-core_2.1.7.wso2v207
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
	at org.apache.synapse.config.xml.rest.APIFactory.defineHandler(APIFactory.java:171) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.rest.APIFactory.createAPI(APIFactory.java:113) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.config.xml.rest.APIFactory.createAPI(APIFactory.java:56) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApi(RestApiAdmin.java:846) ~[org.wso2.carbon.rest.api_4.7.84.jar:?]
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApiFromString(RestApiAdmin.java:114) ~[org.wso2.carbon.rest.api_4.7.84.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.addApi_aroundBody0(RESTAPIAdminServiceProxy.java:50) ~[org.wso2.carbon.apimgt.gateway_9.0.48.SNAPSHOT.jar:?]
	... 14 more
```

### Migration Setup:
- Old Version: APIM 3.2.0
- New Version: APIM 4.0.0
- Database docker image: microsoft/mssql-server-linux 2017-latest

### Steps to reproduce:
Run the APIM migration client when the old APIM version is having an API which was used for testing using the Test Console by initializing test and obtaining a test key.

### Environment Details:
- JDK 1.8.0_241
- Ubuntu 20.04.1 LTS

**Comment by isharac** [comment]
Duplicate https://github.com/wso2/product-apim/issues/10794
