### ISSUE TITLE
JWT claim based advanced throttling policy without enabling backend JWT throws null pointer exception

### ISSUE THREAD

**Issue by Jayanie** [wso2/product-apim#10273]
### Description:

WIthout enabling the backend JWT, an advanced throttling policy is added with JWT claim condition policy in admin portal and set that throttling policy in publisher for an API, when invoking the API at the throttling limit (Eg: 11th request) it throws a null pointer exception as below in server logs.

(JWT claim condition throttling works as expected when backend JWT is enabled)

 ```
ERROR - ServerWorker Error processing GET request for : /pizzashack/1.0.0/menu. 
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.gateway.utils.GatewayUtils.getJWTClaims_aroundBody12(GatewayUtils.java:217) ~[org.wso2.carbon.apimgt.gateway_9.0.35.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.GatewayUtils.getJWTClaims(GatewayUtils.java:215) ~[org.wso2.carbon.apimgt.gateway_9.0.35.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleConditionEvaluator.isJWTClaimPresent_aroundBody14(ThrottleConditionEvaluator.java:227) ~[org.wso2.carbon.apimgt.gateway_9.0.35.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleConditionEvaluator.isJWTClaimPresent(ThrottleConditionEvaluator.java:224) ~[org.wso2.carbon.apimgt.gateway_9.0.35.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleConditionEvaluator.isThrottledWithinCondition_aroundBody30(ThrottleConditionEvaluator.java:396) ~[org.wso2.carbon.apimgt.gateway_9.0.35.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleConditionEvaluator.isThrottledWithinCondition(ThrottleConditionEvaluator.java:372) ~[org.wso2.carbon.apimgt.gateway_9.0.35.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleConditionEvaluator.getThrottledInCondition_aroundBody28(ThrottleConditionEvaluator.java:359) ~[org.wso2.carbon.apimgt.gateway_9.0.35.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleConditionEvaluator.getThrottledInCondition(ThrottleConditionEvaluator.java:339) ~[org.wso2.carbon.apimgt.gateway_9.0.35.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doRoleBasedAccessThrottlingWithCEP_aroundBody0(ThrottleHandler.java:288) ~[org.wso2.carbon.apimgt.gateway_9.0.35.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doRoleBasedAccessThrottlingWithCEP(ThrottleHandler.java:146) ~[org.wso2.carbon.apimgt.gateway_9.0.35.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doThrottle_aroundBody12(ThrottleHandler.java:608) ~[org.wso2.carbon.apimgt.gateway_9.0.35.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doThrottle(ThrottleHandler.java:585) ~[org.wso2.carbon.apimgt.gateway_9.0.35.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.handleRequest_aroundBody8(ThrottleHandler.java:537) ~[org.wso2.carbon.apimgt.gateway_9.0.35.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.handleRequest(ThrottleHandler.java:510) ~[org.wso2.carbon.apimgt.gateway_9.0.35.jar:?]
	at org.apache.synapse.api.API.process(API.java:391) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:107) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:127) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:59) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:75) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:67) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:99) ~[synapse-core_2.1.7.wso2v207.jar:2.1.7-wso2v207]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v41.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:369) [synapse-nhttp-transport_2.1.7.wso2v207.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:189) [synapse-nhttp-transport_2.1.7.wso2v207.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Steps to reproduce:

1. Add a new advanced throttling policy with JWT claim condition policy in admin portal

![Screenshot from 2021-03-15 16-14-13](https://user-images.githubusercontent.com/35601987/111151129-0dadc980-85b5-11eb-94dd-154168cc1e69.png)

2. Set the throttling policy for the API in publisher portal
3. Invoke the API the throttling limit is reached

In the dev portal try out console the response comes as "failed to fetch" and in the server logs the above mentioned null pointer exception is thrown.

**Comment by malinthaprasan** [comment]
https://github.com/wso2/carbon-apimgt/pull/10025
