### ISSUE TITLE
[2APIM .0.0 -> 4.0.0 Migration] Error while migrating keystore passwords for tenant

### ISSUE THREAD

**Issue by isharac** [wso2/product-apim#10304]
### Description:

Encountered below error[1] when running the identity migration in APIM 4.0.0 
Old keystore has set as the internal keystore. 

[keystore.primary]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[keystore.internal]
file_name =  "internal.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[encryption]
key="2095312189753DE6AD47DFE20CBE97EC"

In migration-resources/migration-config.yaml i have set the transformToSymmetric to true
name: "**KeyStorePasswordMigrator**"
order: 9
parameters:
schema: "identity"
currentEncryptionAlgorithm: "RSA"
migratedEncryptionAlgorithm: "RSA/ECB/OAEPwithSHA1andMGF1Padding"
**transformToSymmetric: "true"**

However, repository/conf/carbon.properties file is not available in APIM 2.0.0 to ensure currentEncryptionAlgorithm.

[1] ERROR - RegistryDataManager Error while migrating keystore passwords for tenant : abc.com
org.wso2.carbon.identity.core.migrate.MigrationClientException: Error while decrypting using 'RSA'. The provided algorithm may be incorrect.Please check if your system have data encrypted with different algorithm.
	at org.wso2.carbon.is.migration.util.EncryptionUtil.retryDecryptionWithSuitableAlgorithm(EncryptionUtil.java:133) ~[org.wso2.carbon.is.migration-1.0.144.jar:?]
	at org.wso2.carbon.is.migration.util.EncryptionUtil.transformToSymmetric(EncryptionUtil.java:103) ~[org.wso2.carbon.is.migration-1.0.144.jar:?]
	at org.wso2.carbon.is.migration.util.RegistryDataManager.updateRegistryProperties(RegistryDataManager.java:513) ~[org.wso2.carbon.is.migration-1.0.144.jar:?]
	at org.wso2.carbon.is.migration.util.RegistryDataManager.migrateKeyStorePasswordForTenant(RegistryDataManager.java:412) ~[org.wso2.carbon.is.migration-1.0.144.jar:?]
	at org.wso2.carbon.is.migration.util.RegistryDataManager.migrateKeyStorePassword(RegistryDataManager.java:230) [org.wso2.carbon.is.migration-1.0.144.jar:?]
	at org.wso2.carbon.is.migration.service.v550.migrator.KeyStorePasswordMigrator.migrateKeystorePasswords(KeyStorePasswordMigrator.java:62) [org.wso2.carbon.is.migration-1.0.144.jar:?]
	at org.wso2.carbon.is.migration.service.v550.migrator.KeyStorePasswordMigrator.migrate(KeyStorePasswordMigrator.java:40) [org.wso2.carbon.is.migration-1.0.144.jar:?]
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52) [org.wso2.carbon.is.migration-1.0.144.jar:?]
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:85) [org.wso2.carbon.is.migration-1.0.144.jar:?]
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:149) [org.wso2.carbon.identity.core_5.18.187.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
Caused by: org.wso2.carbon.core.util.CryptoException: An error occurred while decrypting data.
	at org.wso2.carbon.core.util.CryptoUtil.decrypt(CryptoUtil.java:417) ~[org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.util.CryptoUtil.base64DecodeAndDecrypt(CryptoUtil.java:463) ~[org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.is.migration.util.EncryptionUtil.retryDecryptionWithSuitableAlgorithm(EncryptionUtil.java:124) ~[org.wso2.carbon.is.migration-1.0.144.jar:?]
	... 36 more
Caused by: org.wso2.carbon.crypto.api.CryptoException: No internal crypto providers available. Correctly register a service implementation of 'interface org.wso2.carbon.crypto.api.InternalCryptoProvider' as an OSGi service
	at org.wso2.carbon.crypto.impl.DefaultCryptoService.decrypt(DefaultCryptoService.java:601) ~[org.wso2.carbon.crypto.impl_1.1.9.jar:?]
	at org.wso2.carbon.core.util.CryptoUtil.decrypt(CryptoUtil.java:412) ~[org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.util.CryptoUtil.base64DecodeAndDecrypt(CryptoUtil.java:463) ~[org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.is.migration.util.EncryptionUtil.retryDecryptionWithSuitableAlgorithm(EncryptionUtil.java:124) ~[org.wso2.carbon.is.migration-1.0.144.jar:?]
	... 36 more

**Comment by isharac** [comment]
This issue got resolved after disabling KeyStorePasswordMigrator.
We can keep  transformToSymmetric: "false" as APIM does not enable Symmetric key encryption.
