### ISSUE TITLE
Error when recovering password using Forgot Password option

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/product-apim#10311]
### Description:
The following error can be seen when the password recovery with email option is selected.
```
ERROR - EmailEventAdapter Exception occurred when sending email to rakhitha@wso2.com. 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials p11sm1461685pjo.48 - gsmtp

javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials p11sm1461685pjo.48 - gsmtp

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:965) ~[axiom_1.2.11.wso2v17.jar:?]
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:876) ~[axiom_1.2.11.wso2v17.jar:?]
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:780) ~[axiom_1.2.11.wso2v17.jar:?]
	at javax.mail.Service.connect(Service.java:388) ~[axiom_1.2.11.wso2v17.jar:?]
	at javax.mail.Service.connect(Service.java:246) ~[axiom_1.2.11.wso2v17.jar:?]
	at javax.mail.Service.connect(Service.java:195) ~[axiom_1.2.11.wso2v17.jar:?]
	at javax.mail.Transport.send0(Transport.java:254) ~[axiom_1.2.11.wso2v17.jar:?]
	at javax.mail.Transport.send(Transport.java:124) ~[axiom_1.2.11.wso2v17.jar:?]
	at org.wso2.carbon.event.output.adapter.email.EmailEventAdapter$EmailSender.run(EmailEventAdapter.java:367) [org.wso2.carbon.event.output.adapter.email_5.2.34.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
[2021-03-17 12:38:04,417] ERROR - EmailEventAdapter Event dropped at Output Adapter 'EmailPublisher' for tenant id '-1234', Error in message format, 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials p11sm1461685pjo.48 - gsmtp

javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials p11sm1461685pjo.48 - gsmtp

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:965) ~[axiom_1.2.11.wso2v17.jar:?]
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:876) ~[axiom_1.2.11.wso2v17.jar:?]
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:780) ~[axiom_1.2.11.wso2v17.jar:?]
	at javax.mail.Service.connect(Service.java:388) ~[axiom_1.2.11.wso2v17.jar:?]
	at javax.mail.Service.connect(Service.java:246) ~[axiom_1.2.11.wso2v17.jar:?]
	at javax.mail.Service.connect(Service.java:195) ~[axiom_1.2.11.wso2v17.jar:?]
	at javax.mail.Transport.send0(Transport.java:254) ~[axiom_1.2.11.wso2v17.jar:?]
	at javax.mail.Transport.send(Transport.java:124) ~[axiom_1.2.11.wso2v17.jar:?]
	at org.wso2.carbon.event.output.adapter.email.EmailEventAdapter$EmailSender.run(EmailEventAdapter.java:367) [org.wso2.carbon.event.output.adapter.email_5.2.34.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
```

### Steps to reproduce:
1. Create a new user in management console (either in primary or secondary user store).
2. Update the user profile with email details.
3. Go to the Publisher login page -> Forgot Password
4. Choose the email option and enter the username of the user created in Step 1.

The above error will come up on the console.

### Affected Product Version:
4.0.0-alpha

**Comment by mushthaq33** [comment]
@RakhithaRR - Have we configured this [1].

[1] - https://apim.docs.wso2.com/en/next/install-and-setup/setup/security/user-account-management/

**Comment by RakhithaRR** [comment]
I had this configured. However, I have missed to allow third-party apps to send emails through gmail account as mentioned in [1]. It would be better if we could include this in our docs as well.

[1] - https://is.docs.wso2.com/en/5.10.0/setup/configuring-email-sending/
