### ISSUE TITLE
Token Encryption Issue

### ISSUE THREAD

**Issue by rashm1n** [wso2/product-apim#10376]
### Description:
Cannot log into devportal when the token encryption is enabled

### Steps to reproduce:
1. Stop the running server
2. Change the deployment.toml to enable token encryption

```
[apim.oauth_config]
enable_token_encryption = true
```
3. Start server and log in to publisher/devportal
4. Gives exception

### Environment details (with versions):
- OS: Ubuntu 20.04
- Env (Docker/K8s): APIM 4.0.0  , Oracle Java, DB - Oracle 11g v2 XE on Docker

![image](https://user-images.githubusercontent.com/33457890/111742763-b22e5500-88ae-11eb-8c62-099c29ed8a48.png)

**Comment by rashm1n** [comment]
Stacktrace

[2021-03-19 12:28:20,549] ERROR - OAuth2Service Error when reading the Application Information.
org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: Error while retrieving preprocessed client secret
	at org.wso2.carbon.identity.oauth.tokenprocessor.EncryptionDecryptionPersistenceProcessor.getPreprocessedClientSecret(EncryptionDecryptionPersistenceProcessor.java:64) ~[org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	at org.wso2.carbon.identity.oauth.dao.OAuthAppDAO.getAppInformation(OAuthAppDAO.java:328) ~[org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	at org.wso2.carbon.identity.oauth2.util.OAuth2Util.getAppInformationByClientId(OAuth2Util.java:1958) ~[org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	at org.wso2.carbon.identity.oauth2.util.OAuth2Util.getTenantDomainOfOauthApp(OAuth2Util.java:1992) ~[org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	at org.wso2.carbon.identity.oauth2.OAuth2Service.validateClientInfo(OAuth2Service.java:137) [org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.validateClient(OAuth2AuthzEndpoint.java:1760) [classes/:?]
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleOAuthAuthorizationRequest(OAuth2AuthzEndpoint.java:1276) [classes/:?]
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleInitialAuthorizationRequest(OAuth2AuthzEndpoint.java:831) [classes/:?]
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.authorize(OAuth2AuthzEndpoint.java:246) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:225) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [tomcat-servlet-api_9.0.34.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?]
	at org.wso2.carbon.webapp.mgt.filter.AuthorizationHeaderFilter.doFilter(AuthorizationHeaderFilter.java:85) [org.wso2.carbon.webapp.mgt_4.11.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?]
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53) [org.wso2.carbon.ui_4.6.1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.34.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107) [org.wso2.carbon.identity.context.rewrite.valve_1.4.25.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.25.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:102) [org.wso2.carbon.identity.auth.valve_1.4.25.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [tomcat_9.0.34.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.34.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.34.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.wso2.carbon.core.util.CryptoException: An error occurred while decrypting data.
	at org.wso2.carbon.core.util.CryptoUtil.decrypt(CryptoUtil.java:317) ~[org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.util.CryptoUtil.base64DecodeAndDecrypt(CryptoUtil.java:431) ~[org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.identity.oauth.tokenprocessor.EncryptionDecryptionPersistenceProcessor.decrypt(EncryptionDecryptionPersistenceProcessor.java:141) ~[org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	at org.wso2.carbon.identity.oauth.tokenprocessor.EncryptionDecryptionPersistenceProcessor.getPreprocessedClientSecret(EncryptionDecryptionPersistenceProcessor.java:62) ~[org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	... 69 more
Caused by: org.wso2.carbon.crypto.api.CryptoException: An error occurred while decrypting using the algorithm : 'RSA/ECB/OAEPwithSHA1andMGF1Padding', and crypto provider : 'org.wso2.carbon.crypto.provider.KeyStoreBasedInternalCryptoProvider'
	at org.wso2.carbon.crypto.provider.KeyStoreBasedInternalCryptoProvider.decrypt(KeyStoreBasedInternalCryptoProvider.java:163) ~[org.wso2.carbon.crypto.provider_1.1.9.jar:?]
	at org.wso2.carbon.crypto.impl.DefaultCryptoService.decrypt(DefaultCryptoService.java:132) ~[org.wso2.carbon.crypto.impl_1.1.9.jar:?]
	at org.wso2.carbon.core.util.CryptoUtil.decrypt(CryptoUtil.java:311) ~[org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.util.CryptoUtil.base64DecodeAndDecrypt(CryptoUtil.java:431) ~[org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.identity.oauth.tokenprocessor.EncryptionDecryptionPersistenceProcessor.decrypt(EncryptionDecryptionPersistenceProcessor.java:141) ~[org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	at org.wso2.carbon.identity.oauth.tokenprocessor.EncryptionDecryptionPersistenceProcessor.getPreprocessedClientSecret(EncryptionDecryptionPersistenceProcessor.java:62) ~[org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	... 69 more
Caused by: org.bouncycastle.jcajce.provider.util.BadBlockException: unable to decrypt block
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.getOutput(Unknown Source) ~[bcprov-jdk15on-1.60.jar:1.60.0]
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineDoFinal(Unknown Source) ~[bcprov-jdk15on-1.60.jar:1.60.0]
	at javax.crypto.Cipher.doFinal(Cipher.java:2202) ~[?:?]
	at org.wso2.carbon.crypto.provider.KeyStoreBasedInternalCryptoProvider.decrypt(KeyStoreBasedInternalCryptoProvider.java:152) ~[org.wso2.carbon.crypto.provider_1.1.9.jar:?]
	at org.wso2.carbon.crypto.impl.DefaultCryptoService.decrypt(DefaultCryptoService.java:132) ~[org.wso2.carbon.crypto.impl_1.1.9.jar:?]
	at org.wso2.carbon.core.util.CryptoUtil.decrypt(CryptoUtil.java:311) ~[org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.util.CryptoUtil.base64DecodeAndDecrypt(CryptoUtil.java:431) ~[org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.identity.oauth.tokenprocessor.EncryptionDecryptionPersistenceProcessor.decrypt(EncryptionDecryptionPersistenceProcessor.java:141) ~[org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	at org.wso2.carbon.identity.oauth.tokenprocessor.EncryptionDecryptionPersistenceProcessor.getPreprocessedClientSecret(EncryptionDecryptionPersistenceProcessor.java:62) ~[org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	... 69 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: destination index -1 out of bounds for byte[255]
	at java.lang.System.arraycopy(Native Method) ~[?:?]
	at org.bouncycastle.crypto.encodings.OAEPEncoding.decodeBlock(Unknown Source) ~[bcprov-jdk15on-1.60.jar:1.60.0]
	at org.bouncycastle.crypto.encodings.OAEPEncoding.processBlock(Unknown Source) ~[bcprov-jdk15on-1.60.jar:1.60.0]
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.getOutput(Unknown Source) ~[bcprov-jdk15on-1.60.jar:1.60.0]
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineDoFinal(Unknown Source) ~[bcprov-jdk15on-1.60.jar:1.60.0]
	at javax.crypto.Cipher.doFinal(Cipher.java:2202) ~[?:?]
	at org.wso2.carbon.crypto.provider.KeyStoreBasedInternalCryptoProvider.decrypt(KeyStoreBasedInternalCryptoProvider.java:152) ~[org.wso2.carbon.crypto.provider_1.1.9.jar:?]
	at org.wso2.carbon.crypto.impl.DefaultCryptoService.decrypt(DefaultCryptoService.java:132) ~[org.wso2.carbon.crypto.impl_1.1.9.jar:?]
	at org.wso2.carbon.core.util.CryptoUtil.decrypt(CryptoUtil.java:311) ~[org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.util.CryptoUtil.base64DecodeAndDecrypt(CryptoUtil.java:431) ~[org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.identity.oauth.tokenprocessor.EncryptionDecryptionPersistenceProcessor.decrypt(EncryptionDecryptionPersistenceProcessor.java:141) ~[org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	at org.wso2.carbon.identity.oauth.tokenprocessor.EncryptionDecryptionPersistenceProcessor.getPreprocessedClientSecret(EncryptionDecryptionPersistenceProcessor.java:62) ~[org.wso2.carbon.identity.oauth_6.4.111.jar:?]
	... 69 more

**Comment by rashm1n** [comment]
As per the documentation if this is enabled before any keys have been generated in the system, the feature works fine.
