### ISSUE TITLE
Certificates added against APIs are not in the Gateway trust store after restarting the server

### ISSUE THREAD

**Issue by Dulangi-anuththara** [wso2/product-apim#10464]
### Description:

When certificates are added against APIs in which mutual SSL authentication is enabled, we can use those certificates to invoke those APIs after deploying a new revision of the API. But if we shutdown the server and restart it, we have to deploy a revision of the API again to use those certificates to invoke that API. It has been removed from the truststore once we shutdown the server. It'll be added again only if redeploy a revision.

### Steps to reproduce:
1. Enable mutual SSL in API's runtime configurations and add a certificate.
2. Deploy a new revision. (Wait sometime until certificate get reflected in the Gateway Truststore)
3. Try to invoke the API with the added certificate. (To test that it is working)
4. Shutdown the server and Restart it.
5. Try to invoke the API again with that certificate.

Gives the following warning in the console:
![error](https://user-images.githubusercontent.com/40545407/112675379-1774de00-8e8d-11eb-86df-d8313e0c1804.png)

Postman response:
![mtls](https://user-images.githubusercontent.com/40545407/112675496-3c695100-8e8d-11eb-9a6a-cceaabeed32a.png)

### Affected Product Version:
API-M 4.0.0.

### Environment details (with versions):
- OS: Ubuntu 20.04

#### Suggested Labels:
API-M 4.0.0

**Comment by uvindra** [comment]
Steps followed to reproduce the issue
=======================================
1. Run the following commands to generate a self signed key pair
	
	openssl genrsa 2048 > test.key
	chmod 400 test.key
	openssl req -new -x509 -nodes -sha256 -days 365 -key test.key -out test.cert
	
2. Create a new API in super tennant that points to a mock back end do the following changes
	- In Transport level security, tick Mutual SSL and select Mandatory
	- Attach the above generated test.cert with the alias 'abc'
	- In Application level security, select OAuth2 as optional(To eleimintae the need to send access token for API invocation)
![image](https://user-images.githubusercontent.com/6614042/113258371-7dc48b00-92e9-11eb-9eac-70869e6065b9.png)
	

3. Save, deploy a new revision and Publish the API

4. Run the following command in the <APIM_HOME>/repository/resources/security folder

	`keytool --list --keystore client-truststore-temp.jks --alias abc_-1234`
	
   This should display an output displaying the Certificate fingerprint, which indicates that the cert has been saved in the trust store.
   
5. Wait approximately 10 minutes to allow the cert to be loaded into memory(Watch for the message `PassThroughHttpMultiSSLListener  PassThroughHttpListener reloading SSL Config..` in the wso2carbon.log)

6. Invoke the API using curl with the following command provide key pair,

	`curl --location --request GET 'https://localhost:8243/<context>/<version>' --key test.key --cert test.cert -k -v`
	
   Invocation is successful.
	
7. Restart APIM

8. Re-run the following command in the <APIM_HOME>/repository/resources/security folder

	`keytool --list --keystore client-truststore-temp.jks --alias abc_-1234`
	
   This should display an output displaying the Certificate fingerprint, which indicates that the cert still exists in the trust store.
   
9. Invoke the API using curl with the following command provide key pair,

	`curl --location --request GET 'https://localhost:8243/<context>/<version>' --key test.key --cert test.cert -k -v`
	
   Following error `curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:8243 ` is returned and API invocation fails.
   
   
10. Wait approximately 10 minutes to allow the cert to be loaded into memory(Watch for the message `PassThroughHttpMultiSSLListener  PassThroughHttpListener reloading SSL Config..` in the wso2carbon.log) 
	

11. Invoke the API using curl with the following command provide key pair,

	`curl --location --request GET 'https://localhost:8243/<context>/<version>' --key test.key --cert test.cert -k -v`
	
    Invocation is successful.

**Comment by Nirothipan** [comment]
Got the below error when restarting server
```bash
[2021-04-01 13:36:03,973] FATAL - ServiceBusInitializer Failed to initialize ESB due to a fatal error
java.lang.ExceptionInInitializerError: null
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.initializeAuthenticators_aroundBody34(APIAuthenticationHandler.java:283) ~[org.wso2.carbon.apimgt.gateway_9.0.89.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.initializeAuthenticators(APIAuthenticationHandler.java:243) ~[org.wso2.carbon.apimgt.gateway_9.0.89.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.init_aroundBody16(APIAuthenticationHandler.java:176) ~[org.wso2.carbon.apimgt.gateway_9.0.89.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.init(APIAuthenticationHandler.java:171) ~[org.wso2.carbon.apimgt.gateway_9.0.89.jar:?]
	at org.apache.synapse.api.API.init(API.java:581) ~[synapse-core_2.1.7.wso2v215.jar:2.1.7-wso2v215]
	at org.apache.synapse.config.SynapseConfiguration.init(SynapseConfiguration.java:1785) ~[synapse-core_2.1.7.wso2v215.jar:2.1.7-wso2v215]
	at org.apache.synapse.Axis2SynapseController.createSynapseEnvironment(Axis2SynapseController.java:414) ~[synapse-core_2.1.7.wso2v215.jar:2.1.7-wso2v215]
	at org.apache.synapse.ServerManager.start(ServerManager.java:187) ~[synapse-core_2.1.7.wso2v215.jar:2.1.7-wso2v215]
	at org.wso2.carbon.mediation.initializer.ServiceBusInitializer.initESB(ServiceBusInitializer.java:371) ~[org.wso2.carbon.mediation.initializer_4.7.91.jar:?]
	at org.wso2.carbon.mediation.initializer.ServiceBusInitializer.activate(ServiceBusInitializer.java:170) [org.wso2.carbon.mediation.initializer_4.7.91.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.inbound.endpoint.persistence.service.InboundEndpointPersistenceServiceDSComponent.activate(InboundEndpointPersistenceServiceDSComponent.java:50) [org.wso2.carbon.inbound.endpoint.persistence_4.7.91.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) [org.wso2.carbon.core_4.6.1.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.apimgt.gateway.handlers.security.authenticator.MutualSSLAuthenticator.<clinit>(MutualSSLAuthenticator.java:66) ~[org.wso2.carbon.apimgt.gateway_9.0.89.jar:?]
	... 59 more
```
