### ISSUE TITLE
Websub API Invocation failure with error

### ISSUE THREAD

**Issue by tharindu1st** [wso2/product-apim#10465]
### Description:
Fail Websub API with following error.

TID: [-1234] [] [2021-03-26 17:53:24,110] ERROR {org.apache.synapse.util.xpath.SynapseXPath} - Evaluation of the XPath expression fn:concat('sha-1=', hmac-generate($ctx:ORIGINAL_PAYLOAD, 'ab51f20f06172c4c7d62be997ee9c695', 'HmacSHA-1')) resulted in an error org.jaxen.FunctionCallException: Error while generating HMAC signature
        at org.apache.synapse.util.xpath.HMACGenerateFunction.generateSignature(HMACGenerateFunction.java:91)
        at org.apache.synapse.util.xpath.HMACGenerateFunction.call(HMACGenerateFunction.java:64)
        at org.jaxen.expr.DefaultFunctionCallExpr.evaluate(DefaultFunctionCallExpr.java:181)
        at org.jaxen.expr.DefaultFunctionCallExpr.evaluateParams(DefaultFunctionCallExpr.java:195)
        at org.jaxen.expr.DefaultFunctionCallExpr.evaluate(DefaultFunctionCallExpr.java:179)
        at org.jaxen.expr.DefaultXPathExpr.asList(DefaultXPathExpr.java:102)
        at org.jaxen.BaseXPath.selectNodesForContext(BaseXPath.java:675)
        at org.jaxen.BaseXPath.selectNodes(BaseXPath.java:215)
        at org.jaxen.BaseXPath.evaluate(BaseXPath.java:175)
        at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:411)
        at org.apache.synapse.mediators.builtin.PropertyMediator.getResultValue(PropertyMediator.java:410)
        at org.apache.synapse.mediators.builtin.PropertyMediator.mediate(PropertyMediator.java:133)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.api.Resource.process(Resource.java:342)
        at org.apache.synapse.api.API.process(API.java:463)
        at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:107)
        at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:127)
        at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:59)
        at org.apache.synapse.api.inbound.InboundApiHandler.dispatchToAPI(InboundApiHandler.java:73)
        at org.apache.synapse.api.inbound.InboundApiHandler.process(InboundApiHandler.java:64)
        at org.wso2.carbon.inbound.endpoint.protocol.http.InboundHttpServerWorker.run(InboundHttpServerWorker.java:150)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.NoSuchAlgorithmException: Algorithm HmacSHA-1 not available
        at javax.crypto.Mac.getInstance(Mac.java:181)
        at org.apache.synapse.util.xpath.HMACGenerateFunction.getMacInstance(HMACGenerateFunction.java:106)
        at org.apache.synapse.util.xpath.HMACGenerateFunction.generateSignature(HMACGenerateFunction.java:84)

**Comment by chanikag** [comment]
This is fixed by @lasanthaS https://github.com/wso2/carbon-apimgt/pull/10172
