### ISSUE TITLE
Error when invoking an AWS Lambda API

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/product-apim#10478]
### Description:
The following error can be seen when invoking an AWS Lambda API.

```
ERROR - AWSLambdaMediator Error while invoking the lambda function
com.amazonaws.services.lambda.model.AWSLambdaException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (Service: AWSLambda; Status Code: 403; Error Code: InvalidSignatureException; Request ID: 19e2ba1d-d87b-4433-916c-c73b622e52c8)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639) ~[awslambda_1.11.253.wso2v1.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304) ~[awslambda_1.11.253.wso2v1.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056) ~[awslambda_1.11.253.wso2v1.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743) ~[awslambda_1.11.253.wso2v1.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717) ~[awslambda_1.11.253.wso2v1.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[awslambda_1.11.253.wso2v1.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[awslambda_1.11.253.wso2v1.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[awslambda_1.11.253.wso2v1.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[awslambda_1.11.253.wso2v1.jar:?]
	at com.amazonaws.services.lambda.AWSLambdaClient.doInvoke(AWSLambdaClient.java:2654) ~[awslambda_1.11.253.wso2v1.jar:?]
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:2630) ~[awslambda_1.11.253.wso2v1.jar:?]
	at com.amazonaws.services.lambda.AWSLambdaClient.executeInvoke(AWSLambdaClient.java:1497) ~[awslambda_1.11.253.wso2v1.jar:?]
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:1473) ~[awslambda_1.11.253.wso2v1.jar:?]
	at org.wso2.carbon.apimgt.gateway.mediators.AWSLambdaMediator.invokeLambda_aroundBody2(AWSLambdaMediator.java:143) [org.wso2.carbon.apimgt.gateway_9.0.87.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.mediators.AWSLambdaMediator.invokeLambda(AWSLambdaMediator.java:103) [org.wso2.carbon.apimgt.gateway_9.0.87.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.mediators.AWSLambdaMediator.mediate_aroundBody0(AWSLambdaMediator.java:76) [org.wso2.carbon.apimgt.gateway_9.0.87.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.mediators.AWSLambdaMediator.mediate(AWSLambdaMediator.java:65) [org.wso2.carbon.apimgt.gateway_9.0.87.SNAPSHOT.jar:?]
	at org.apache.synapse.mediators.ext.ClassMediator.updateInstancePropertiesAndMediate(ClassMediator.java:178) [synapse-core_2.1.7.wso2v213.jar:2.1.7-wso2v213]
	at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:97) [synapse-core_2.1.7.wso2v213.jar:2.1.7-wso2v213]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109) [synapse-core_2.1.7.wso2v213.jar:2.1.7-wso2v213]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71) [synapse-core_2.1.7.wso2v213.jar:2.1.7-wso2v213]
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) [synapse-core_2.1.7.wso2v213.jar:2.1.7-wso2v213]
	at org.apache.synapse.api.Resource.process(Resource.java:342) [synapse-core_2.1.7.wso2v213.jar:2.1.7-wso2v213]
	at org.apache.synapse.api.API.process(API.java:463) [synapse-core_2.1.7.wso2v213.jar:2.1.7-wso2v213]
	at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:107) [synapse-core_2.1.7.wso2v213.jar:2.1.7-wso2v213]
	at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:127) [synapse-core_2.1.7.wso2v213.jar:2.1.7-wso2v213]
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:59) [synapse-core_2.1.7.wso2v213.jar:2.1.7-wso2v213]
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:75) [synapse-core_2.1.7.wso2v213.jar:2.1.7-wso2v213]
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:67) [synapse-core_2.1.7.wso2v213.jar:2.1.7-wso2v213]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) [synapse-core_2.1.7.wso2v213.jar:2.1.7-wso2v213]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344) [synapse-core_2.1.7.wso2v213.jar:2.1.7-wso2v213]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:99) [synapse-core_2.1.7.wso2v213.jar:2.1.7-wso2v213]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) [axis2_1.6.1.wso2v41.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:375) [synapse-nhttp-transport_2.1.7.wso2v213.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:434) [synapse-nhttp-transport_2.1.7.wso2v213.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:182) [synapse-nhttp-transport_2.1.7.wso2v213.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]

```

### Steps to reproduce:
1. Follow the steps in https://apim.docs.wso2.com/en/latest/learn/tutorials/create-and-publish-awslambda-api/#create-and-publish-an-aws-lambda-api
2. Deploy and Publish the API
3. Subscribe to the API and Invoke

### Affected Product Version:
APIM-4.0.0 (9.0.87-SNAPSHOT)

### Environment details (with versions):
- OS: Ubuntu 20.04

**Comment by tmkasun** [comment]
Possible duplicate issues : 
- https://github.com/wso2/product-apim/issues/10533
- https://github.com/wso2/product-apim/issues/10540

**Comment by tmkasun** [comment]
It seems like current version of the SDK is using the [aws4 signature method](https://docs.aws.amazon.com/general/latest/gr/signature-v4-troubleshooting.html#signature-v4-troubleshooting-key-signing) and since SDK generate the signature by itself, we might need to update the SDK version

![image](https://user-images.githubusercontent.com/3313885/113080944-62785380-91f5-11eb-8a9a-c5dbdf88b535.png)

**Comment by RakhithaRR** [comment]
> It seems like current version of the SDK is using the [aws4 signature method](https://docs.aws.amazon.com/general/latest/gr/signature-v4-troubleshooting.html#signature-v4-troubleshooting-key-signing) and since SDK generate the signature by itself, we might need to update the SDK version
> 
> ![image](https://user-images.githubusercontent.com/3313885/113080944-62785380-91f5-11eb-8a9a-c5dbdf88b535.png)

The same flow in APIM 3.2.0 seems to be working fine. We have the same SDK version there as well right? So this issue might be due to a different reason.
