### ISSUE TITLE
Cannot invoke APIs when response caching is enabled.

### ISSUE THREAD

**Issue by ShalkiWenushika** [wso2/product-apim#10630]
### Description:
Can't invoke APIs when response caching is enabled.

### Steps to reproduce:
1. Create an API from the publisher.
2.  Enable response caching.
3.  Deploy the API.
4.  Invoke the API (receive `curl: (52) Empty reply from server`).

### Affected Product Version:
APIM 4.0.0-alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tharindu1st** [comment]
This was due to 
:```
 [31] [] [2021-03-31 05:12:43,148]  WARN {org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtGoogleAnalyticsTrackingHandler} - Unable to load Google Analytics configuration using key: ga-config-key
TID: [31] [] [2021-03-31 05:12:43,191] ERROR {org.apache.synapse.mediators.base.SequenceMediator} - {api:basicauthapi:v1.0.0} Runtime error occurred while mediating the message java.lang.NullPointerException
        at org.wso2.carbon.apimgt.gateway.handlers.analytics.SynapseAnalyticsDataProvider.getTargetResponseCode_aroundBody22(SynapseAnalyticsDataProvider.java:224)
        at org.wso2.carbon.apimgt.gateway.handlers.analytics.SynapseAnalyticsDataProvider.getTargetResponseCode(SynapseAnalyticsDataProvider.java:223)
        at org.wso2.carbon.apimgt.gateway.handlers.analytics.SynapseAnalyticsDataProvider.getTarget_aroundBody14(SynapseAnalyticsDataProvider.java:164)
        at org.wso2.carbon.apimgt.gateway.handlers.analytics.SynapseAnalyticsDataProvider.getTarget(SynapseAnalyticsDataProvider.java:160)
        at org.wso2.carbon.apimgt.common.analytics.collectors.impl.SuccessRequestDataCollector.collectData(SuccessRequestDataCollector.java:62)
        at org.wso2.carbon.apimgt.common.analytics.collectors.impl.GenericRequestDataCollector.collectData(GenericRequestDataCollector.java:46)
        at org.wso2.carbon.apimgt.gateway.handlers.analytics.AnalyticsMetricsHandler.handleResponseOutFlow_aroundBody8(AnalyticsMetricsHandler.java:98)
        at org.wso2.carbon.apimgt.gateway.handlers.analytics.AnalyticsMetricsHandler.handleResponseOutFlow(AnalyticsMetricsHandler.java:85)
        at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:184)
        at org.wso2.carbon.mediator.cache.CacheMediator.replaceEnvelopeWithCachedResponse(CacheMediator.java:409)
        at org.wso2.carbon.mediator.cache.CacheMediator.processRequestMessage(CacheMediator.java:324)
        at org.wso2.carbon.mediator.cache.CacheMediator.mediate(CacheMediator.java:251)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.api.Resource.process(Resource.java:342)
        at org.apache.synapse.api.API.process(API.java:463)
        at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:107)
        at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:127)
        at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:59)
        at org.apache.
```
