### ISSUE TITLE
 Swagger Schema Validation issue

### ISSUE THREAD

**Issue by dev-skd** [wso2/product-apim#10780]
### Description:
The JSON schema validation error when invoking an API with enabling **Schema Validation** via **Runtime Configuration** section in the publisher portal.
{ "Fault": { "faultcode": "soapenv:Server",  "faultstring": 1,  "detail": null  } }

In the **wso2carbon.log** file, the below error stack trace can be observed.

```
TID: [-1234] [] [2021-04-05 15:58:53,659] ERROR {org.apache.synapse.transport.passthru.ServerWorker} - Error processing POST request for : /SpecTest/1.0/api/v1/testingEnpoint?inputParameter=Employee. java.lang.ArrayIndexOutOfBoundsException: 1

        at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.extractReference_aroundBody26(SchemaValidator.java:563)

        at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.extractReference(SchemaValidator.java:561)

        at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.extractSchemaFromRequest_aroundBody18(SchemaValidator.java:374)

        at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.extractSchemaFromRequest(SchemaValidator.java:340)

        at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.getSchemaContent_aroundBody16(SchemaValidator.java:327)

        at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.getSchemaContent(SchemaValidator.java:324)

        at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.validateRequest_aroundBody8(SchemaValidator.java:226)

        at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.validateRequest(SchemaValidator.java:224)

        at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.handleRequest_aroundBody2(SchemaValidator.java:127)

        at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.handleRequest(SchemaValidator.java:81)

        at org.apache.synapse.rest.API.process(API.java:373)

        at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:144)

        at org.apache.synapse.rest.RESTRequestHandler.identifyAPI(RESTRequestHandler.java:164)

        at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95)

        at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:73)

        at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:331)

        at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:99)

        at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)

        at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367)

        at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:426)

        at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181)

        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

        at java.lang.Thread.run(Thread.java:748)
```

We have analyzed the source code and noticed that the issue is occurring when executing the below code line in **extractReference()** method. (**SchemaValidator.java**)

`String path = val[1].replaceAll("\"|}|]|\\\\", "");`

### Steps to reproduce:
-  Published an API by using the provided [swagger definition](https://drive.google.com/file/d/1Uf4bU1t2NCcGQypymKRwkpsgs7oDPqp2/view?usp=sharing).
-  Invoked the POST API endpoint  with an empty JSON body as below.
![Screenshot from 2021-04-05 22-28-10](https://user-images.githubusercontent.com/73546297/113659495-c3a19a80-96bf-11eb-9203-7fe7b1738914.png)

### Affected Product Version:
3.2.0

**Comment by tmkasun** [comment]
@hasuniea any insights on this 😃  ?

**Comment by kavishkafernando** [comment]
Not reproducible in master hence closing the issue.
