### ISSUE TITLE
Error when changing Lifecycle state as Publisher user

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/product-apim#10870]
### Description:
Getting a 403 when updating the Lifecycle of the API as a Publisher user.

![Screenshot from 2021-04-08 12-17-34](https://user-images.githubusercontent.com/25485273/113981223-081a6b00-9865-11eb-8884-5149c1fc9dba.png)

### Steps to reproduce:
1. Create a new user with Publisher permissions
2. Try to Publish an API created by a Creator user (or Demote to Created an already published API).

**Comment by tharindu1st** [comment]
D: [-1234] [] [2021-04-08 06:35:12,525]  INFO {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} - 'wso2apim@carbon.super [-1234]' logged in at [2021-04-08 06:35:12,525+0000]
TID: [-1234] [api/am/publisher] [2021-04-08 06:35:24,545] ERROR {org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl} - Authorization failure while updating API : 856b551f-bf36-4dbe-8265-1eb0cf81ece5 org.wso2.carbon.apimgt.api.APIManagementException: User is not authorized to update one or more API fields. None of the required scopes found in user token to update the field. So the request will be failed.
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.PublisherCommonUtils.overrideDTOValues(PublisherCommonUtils.java:429)
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.PublisherCommonUtils.getFieldOverriddenAPIDTO(PublisherCommonUtils.java:463)
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.PublisherCommonUtils.updateApi(PublisherCommonUtils.java:274)
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.updateAPI(ApisApiServiceImpl.java:793)
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.updateAPI(ApisApi.java:1367)
        at sun.reflect.GeneratedMethodAccessor2029.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
        a

**Comment by malinthaprasan** [comment]
Could not reproduce for a new API. But for the rakitha's API it could be reproduced
