### ISSUE TITLE
JWT claim condition throttling not working

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#10885]
### Description:
$subject . 

Additionally, following error was printed when the request is throttled out using the default value

        [2021-04-08 13:20:21,251] ERROR - ServerWorker Error processing GET request for : /pizzashack/1.0.0/menu. 
        java.lang.NullPointerException: null
            at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleConditionEvaluator.isJWTClaimPresent_aroundBody14(ThrottleConditionEvaluator.java:231) ~[org.wso2.carbon.apimgt.gateway_9.0.127.SNAPSHOT.jar:?]
            at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleConditionEvaluator.isJWTClaimPresent(ThrottleConditionEvaluator.java:224) ~[org.wso2.carbon.apimgt.gateway_9.0.127.SNAPSHOT.jar:?]
            at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleConditionEvaluator.isThrottledWithinCondition_aroundBody30(ThrottleConditionEvaluator.java:393) ~[org.wso2.carbon.apimgt.gateway_9.0.127.SNAPSHOT.jar:?]
            at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleConditionEvaluator.isThrottledWithinCondition(ThrottleConditionEvaluator.java:369) ~[org.wso2.carbon.apimgt.gateway_9.0.127.SNAPSHOT.jar:?]
            at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleConditionEvaluator.getThrottledInCondition_aroundBody28(ThrottleConditionEvaluator.java:356) ~[org.wso2.carbon.apimgt.gateway_9.0.127.SNAPSHOT.jar:?]
            at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleConditionEvaluator.getThrottledInCondition(ThrottleConditionEvaluator.java:336) ~[org.wso2.carbon.apimgt.gateway_9.0.127.SNAPSHOT.jar:?]
            at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doRoleBasedAccessThrottlingWithCEP_aroundBody0(ThrottleHandler.java:288) ~[org.wso2.carbon.apimgt.gateway_9.0.127.SNAPSHOT.jar:?]
            at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doRoleBasedAccessThrottlingWithCEP(ThrottleHandler.java:146) ~[org.wso2.carbon.apimgt.gateway_9.0.127.SNAPSHOT.jar:?]
            at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doThrottle_aroundBody12(ThrottleHandler.java:608) ~[org.wso2.carbon.apimgt.gateway_9.0.127.SNAPSHOT.jar:?]
            at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doThrottle(ThrottleHandler.java:585) ~[org.wso2.carbon.apimgt.gateway_9.0.127.SNAPSHOT.jar:?]
            at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.handleRequest_aroundBody8(ThrottleHandler.java:537) ~[org.wso2.carbon.apimgt.gateway_9.0.127.SNAPSHOT.jar:?]
            at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.handleRequest(ThrottleHandler.java:510) ~[org.wso2.carbon.apimgt.gateway_9.0.127.SNAPSHOT.jar:?]
            at org.apache.synapse.api.API.process(API.java:389) ~[synapse-core_2.1.7.wso2v221.jar:2.1.7-wso2v221]
            at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:107) ~[synapse-core_2.1.7.wso2v221.jar:2.1.7-wso2v221]
            at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:127) ~[synapse-core_2.1.7.wso2v221.jar:2.1.7-wso2v221]
            at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:59) ~[synapse-core_2.1.7.wso2v221.jar:2.1.7-wso2v221]
            at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:84) ~[synapse-core_2.1.7.wso2v221.jar:2.1.7-wso2v221]
            at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:70) ~[synapse-core_2.1.7.wso2v221.jar:2.1.7-wso2v221]
            at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) ~[synapse-core_2.1.7.wso2v221.jar:2.1.7-wso2v221]
            at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344) ~[synapse-core_2.1.7.wso2v221.jar:2.1.7-wso2v221]
            at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:99) ~[synapse-core_2.1.7.wso2v221.jar:2.1.7-wso2v221]
            at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v41.jar:?]
            at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:375) [synapse-nhttp-transport_2.1.7.wso2v221.jar:?]
            at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:189) [synapse-nhttp-transport_2.1.7.wso2v221.jar:?]
            at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41.jar:?]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
            at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by chamilaadhi** [comment]
Following error is printed before

    TID: [-1] [] [2021-04-08 05:58:15,561] ERROR {org.wso2.carbon.apimgt.common.gateway.util.JWTUtil} - Error occurred while parsing jwt claims
