### ISSUE TITLE
Failed to create SSE API from service catalogue

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/product-apim#10933]
### Description:
I published an SSE Async API to the service catalogue via the Streaming Integrator. Then attempted to create an API from it using the publisher in the APIM server. If failed with the following error on the UI:
<img width="947" alt="Screen Shot 2021-04-10 at 8 29 54 PM" src="https://user-images.githubusercontent.com/7592890/114274462-1a023680-9a3c-11eb-9a3e-c05e3ac8a1e3.png">

Following error was logged in the APIM log:
```
[2021-04-10 20:23:43,655]  INFO - CommonUtil Creation of folder is successful. Directory Name : sseapi-1.0.0
[2021-04-10 20:25:33,702]  INFO - JMSConnectionFactory JMS ConnectionFactory : tokenRevocationJMSPublisher initialized
[2021-04-10 20:27:06,231]  INFO - DataBridge user admin connected
[2021-04-10 20:27:06,236] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.getSwaggerVersion_aroundBody2(OASParserUtil.java:198) ~[org.wso2.carbon.apimgt.impl_9.0.133.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.getSwaggerVersion(OASParserUtil.java:196) ~[org.wso2.carbon.apimgt.impl_9.0.133.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.getOASParser_aroundBody0(OASParserUtil.java:187) ~[org.wso2.carbon.apimgt.impl_9.0.133.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.getOASParser(OASParserUtil.java:185) ~[org.wso2.carbon.apimgt.impl_9.0.133.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.APIMappingUtil.getScopesFromSwagger(APIMappingUtil.java:2646) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.133.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.APIMappingUtil.fromAPItoDTO(APIMappingUtil.java:1093) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.133.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.APIMappingUtil.fromAPItoDTO(APIMappingUtil.java:864) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.133.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.importAsyncAPISpecification(ApisApiServiceImpl.java:4895) ~[classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.importServiceFromCatalog(ApisApiServiceImpl.java:4677) ~[classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.importServiceFromCatalog(ApisApi.java:1259) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) [cxf-rt-frontend-jaxrs-3.3.7.jar:3.3.7]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) [cxf-rt-frontend-jaxrs-3.3.7.jar:3.3.7]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:215) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-servlet-api_9.0.34.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.34.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107) [org.wso2.carbon.identity.context.rewrite.valve_1.4.25.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.25.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:102) [org.wso2.carbon.identity.auth.valve_1.4.25.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [tomcat_9.0.34.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126) [org.wso2.carbon.tomcat.ext_4.6.1.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.34.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.34.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

### Steps to reproduce:
1. Uncomment `offset` and set to `5` in the wso2am-4.0.0 in wso2am-4.0.0/repository/conf/deployment.toml in the `[server]` section.
2. Enable `async.api.configs` in wso2si-4.0.0/conf/server/deployment.yaml and set `port` as `9448`
3. Installed Kafka extension to both SI and SI tooling (I did this as I used  a Kafka Source. May try with any other source)
4. Start APIM, SI, SI-tooling servers.
5. Create the following siddhi app in SI tooling
```
@App:name('HelloKafka')
@App:description('Consume events from a Kafka Topic and log the messages on the console.')

@source(type='kafka',topic.list = "productions",threading.option = "single.thread",group.id = "group1",bootstrap.servers = "localhost:9092",
	@map(type='json'))
define stream SweetProductionStream (name string,amount double);


@sink(type='log')
define stream OutputStream (name string,amount double);


@sink(type='sse',event.sink.url = "http://localhost:8081",
	@map(type='json'))
define stream OutputStream2 (name string,amount double);

-- Query to transform the name to upper case.
@info(name='query1')
from SweetProductionStream 
select str:upper(name) as name,amount 
insert  into OutputStream2;
```
Then generate the async api for this and deploy it to the SI server.

```
@App:name('HelloKafka')
@App:description('Consume events from a Kafka Topic and log the messages on the console.')

@App:asyncAPI("""asyncapi: 2.0.0
info:
  title: sseapi
  version: 1.0.0
  description: This exposes an API from WSO2 SI
servers:
  production:
    url: 'localhost:8081'
    protocol: http
    security: []
channels:
  /:
    subscribe:
      message:
        $ref: '#/components/messages/OutputStream2Payload'
components:
  messages:
    OutputStream2Payload:
      payload:
        type: object
        properties:
          name:
            $ref: '#/components/schemas/name'
          amount:
            $ref: '#/components/schemas/amount'
  schemas:
    name:
      type: string
    amount:
      type: number
  securitySchemes: {}
""")

@source(type='kafka',topic.list = "productions",threading.option = "single.thread",group.id = "group1",bootstrap.servers = "localhost:9092",
	@map(type='json'))
define stream SweetProductionStream (name string,amount double);

@sink(type='log')
define stream OutputStream (name string,amount double);

@sink(type='sse',event.sink.url = "http://localhost:8081",
	@map(type='json'))
define stream OutputStream2 (name string,amount double);

@info(name='query1')
from SweetProductionStream 
select str:upper(name) as name,amount 
insert  into OutputStream2;

```
Following log was printed in APIM
[2021-04-10 20:23:43,655]  INFO - CommonUtil Creation of folder is successful. Directory Name : sseapi-1.0.0

Following log was printed in SI
[2021-04-10 20:23:40,845]  WARN {io.siddhi.extension.io.http.sink.HttpSSESink} - No subscription foundOutputStream2
[2021-04-10 20:23:48,141]  INFO {org.wso2.carbon.streaming.integrator.core.internal.asyncapi.AsyncAPIDeployer} - Async API: sseapi-1.0.0 uploaded to the service catalogue

Then go to Publisher's service catalog, select the api and click 'create api'. It gave the errors I showed above in the description.

### Affected Product Version:
APIM latest build (10th April)
https://wso2.org/jenkins/view/products/job/products/job/product-apim/2263/

### Environment details (with versions):
- OS: Mac OS
- Client: Google Chrome
- Env (Docker/K8s): standalone

**Comment by vithu30** [comment]
Hi @dilini-muthumala,

In the shared Async API definition, the protocol is set as `http`. During earlier discussions we decided to set relevant async API protocol when publishing from MI / SI to service catalog. I tried changing the protocol as `sse` and API creation was successful.

Is there any reason to use `http` as protocol here?

**Comment by AnuGayan** [comment]
I Observed the same issue when I tried to create API with the WebSub service catalog. There also we pass the protocol as HTTP.
