### ISSUE TITLE
Error when generating keys with Auth0 key manager

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/product-apim#11019]
### Description:
The following error occurs when try to add an Auth0 km and generate keys.
```
java.lang.IllegalArgumentException: Invalid URL port: "9444clients"
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1326) ~[okhttp_4.2.0.wso2v1.jar:?]
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1630) ~[okhttp_4.2.0.wso2v1.jar:?]
	at okhttp3.Request$Builder.url(Request.kt:184) ~[okhttp_4.2.0.wso2v1.jar:?]
	at feign.okhttp.OkHttpClient.toOkHttpRequest(OkHttpClient.java:50) ~[io.github.openfeign.feign-okhttp_11.0.0.jar:?]
	at feign.okhttp.OkHttpClient.execute(OkHttpClient.java:168) ~[io.github.openfeign.feign-okhttp_11.0.0.jar:?]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at com.sun.proxy.$Proxy427.createApplication(Unknown Source) ~[?:?]
	at org.wso2.auth0.client.Auth0OAuthClient.createApplication(Auth0OAuthClient.java:100) ~[auth0.key.manager_1.0.1.jar:?]
	at org.wso2.carbon.apimgt.impl.workflow.AbstractApplicationRegistrationWorkflowExecutor.dogenerateKeysForApplication_aroundBody8(AbstractApplicationRegistrationWorkflowExecutor.java:154) [org.wso2.carbon.apimgt.impl_9.0.159.jar:?]
	at org.wso2.carbon.apimgt.impl.workflow.AbstractApplicationRegistrationWorkflowExecutor.dogenerateKeysForApplication(AbstractApplicationRegistrationWorkflowExecutor.java:125) [org.wso2.carbon.apimgt.impl_9.0.159.jar:?]
	at org.wso2.carbon.apimgt.impl.workflow.AbstractApplicationRegistrationWorkflowExecutor.generateKeysForApplication_aroundBody6(AbstractAppl
```

### Steps to reproduce:
1. Add a key manager following the documentation
2. Try to generate keys for the application from the km

**Comment by Sarangan0219** [comment]
Fixed via https://github.com/wso2-extensions/apim-km-auth0/pull/5
