### ISSUE TITLE
Errors in the server log when undeploying and redeploying SOAPTOREST API

### ISSUE THREAD

**Issue by YasasRangika** [wso2/product-apim#11047]
### Description:
When undeploying SOAPTOREST API it gives below error in the log.

```
[2021-04-16 18:00:22,371] ERROR - SequenceMediatorSerializer Unable to find a serializer for mediator : ScriptMediator
[2021-04-16 18:00:22,371] ERROR - GatewayJMSMessageListener Error in undeploying artifacts
```
Redeployment time it shows another error:

```
[2021-04-16 18:00:45,417] ERROR - SequenceMediatorSerializer Unable to find a serializer for mediator : ScriptMediator
[2021-04-16 18:00:45,417] ERROR - InMemoryAPIDeployer Error deploying d9180d5e-8f54-426c-b4d1-14f23a5eacc4 in Gateway
org.apache.axis2.AxisFault: Error while obtaining API information from gateway. Unable to find a serializer for mediator : ScriptMediator
	at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.getApi_aroundBody2(RESTAPIAdminServiceProxy.java:70) ~[org.wso2.carbon.apimgt.gateway_9.0.167.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.getApi(RESTAPIAdminServiceProxy.java:59) ~[org.wso2.carbon.apimgt.gateway_9.0.167.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.unDeployAPI_aroundBody98(APIGatewayAdmin.java:804) ~[org.wso2.carbon.apimgt.gateway_9.0.167.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.unDeployAPI(APIGatewayAdmin.java:779) ~[org.wso2.carbon.apimgt.gateway_9.0.167.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.unDeployAPI_aroundBody100(APIGatewayAdmin.java:898) ~[org.wso2.carbon.apimgt.gateway_9.0.167.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.unDeployAPI(APIGatewayAdmin.java:886) ~[org.wso2.carbon.apimgt.gateway_9.0.167.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.unDeployAPI_aroundBody6(InMemoryAPIDeployer.java:243) ~[org.wso2.carbon.apimgt.gateway_9.0.167.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.unDeployAPI(InMemoryAPIDeployer.java:201) ~[org.wso2.carbon.apimgt.gateway_9.0.167.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:91) [org.wso2.carbon.apimgt.gateway_9.0.167.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:82) [org.wso2.carbon.apimgt.gateway_9.0.167.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage_aroundBody2(GatewayJMSMessageListener.java:152) [org.wso2.carbon.apimgt.gateway_9.0.167.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage(GatewayJMSMessageListener.java:122) [org.wso2.carbon.apimgt.gateway_9.0.167.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage_aroundBody0(GatewayJMSMessageListener.java:97) [org.wso2.carbon.apimgt.gateway_9.0.167.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage(GatewayJMSMessageListener.java:73) [org.wso2.carbon.apimgt.gateway_9.0.167.jar:?]
	at org.wso2.carbon.apimgt.common.jms.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:656) [org.wso2.carbon.apimgt.common.jms_9.0.167.jar:?]
	at org.wso2.carbon.apimgt.common.jms.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:555) [org.wso2.carbon.apimgt.common.jms_9.0.167.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v63.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: org.apache.synapse.SynapseException: Unable to find a serializer for mediator : ScriptMediator
	at org.apache.synapse.config.xml.AbstractMediatorSerializer.handleException(AbstractMediatorSerializer.java:215) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.AbstractListMediatorSerializer.serializeChildren(AbstractListMediatorSerializer.java:40) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.SequenceMediatorSerializer.serializeAnonymousSequence(SequenceMediatorSerializer.java:46) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.wso2.carbon.rest.api.RestApiAdminUtils.createAnonymousSequenceElement(RestApiAdminUtils.java:144) ~[org.wso2.carbon.rest.api_4.7.99.jar:?]
	at org.wso2.carbon.rest.api.service.RestApiAdmin.convertApiToAPIData(RestApiAdmin.java:794) ~[org.wso2.carbon.rest.api_4.7.99.jar:?]
	at org.wso2.carbon.rest.api.service.RestApiAdmin.getApiByName(RestApiAdmin.java:533) ~[org.wso2.carbon.rest.api_4.7.99.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.getApi_aroundBody2(RESTAPIAdminServiceProxy.java:63) ~[org.wso2.carbon.apimgt.gateway_9.0.167.jar:?]
	... 19 more
[2021-04-16 18:00:45,418] ERROR - GatewayJMSMessageListener Error in deploying artifacts for d9180d5e-8f54-426c-b4d1-14f23a5eacc4in the Gateway
```
But in the UI side it does not show any fault behavior.

![Peek 2021-04-16 18-07](https://user-images.githubusercontent.com/28702407/115025264-c6319a80-9ede-11eb-9ea1-90ef0d76724e.gif)

### Steps to reproduce:
Create REST API from SOAP back-end and follow undeploy and redeploy actions.

### Affected Product Version:
API-M 4.0.0 RC1

#### Suggested Labels:
API-M 4.0.0

**Comment by YasasRangika** [comment]
This is not reproducing anymore. Hence closing this.
