### ISSUE TITLE
[3.0.0] Issue when performing WUM Update with Diff & Profile Optimization

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#11069]
### Description:

The following error-traces are produced when applying the WUM diff and starting the API Manager server again with the same profile optimization

```log
FATAL {org.wso2.carbon.core.init.CarbonServerManager} - WSO2 Carbon initialization Failed org.apache.axis2.AxisFault: Exception occured while loading the Axis configuration from /opt/WSO2/Distributed-3.0/02.TrafficManager/repository/conf/axis2/axis2.xml
    at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:194)
    at org.apache.axis2.context.ConfigurationContextFactory.createConfigurationContext(ConfigurationContextFactory.java:64)
    at org.wso2.carbon.core.CarbonConfigurationContextFactory.createNewConfigurationContext(CarbonConfigurationContextFactory.java:65)
    at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:415)
    at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
    at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: org.apache.axis2.deployment.DeploymentException: org.apache.synapse.transport.passthru.PassThroughHttpSender cannot be found by axis2_1.6.1.wso2v38
    at org.apache.axis2.deployment.AxisConfigBuilder.processTransportSenders(AxisConfigBuilder.java:713)
    at org.apache.axis2.deployment.AxisConfigBuilder.populateConfig(AxisConfigBuilder.java:125)
    at org.wso2.carbon.core.CarbonAxisConfigurator.populateAxisConfiguration(CarbonAxisConfigurator.java:341)
    at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:192)
    ... 8 more
Caused by: java.lang.ClassNotFoundException: org.apache.synapse.transport.passthru.PassThroughHttpSender cannot be found by axis2_1.6.1.wso2v38
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
    at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:315)
    at org.apache.axis2.util.Loader.loadClass(Loader.java:261)
    at org.apache.axis2.deployment.AxisConfigBuilder.processTransportSenders(AxisConfigBuilder.java:687)
    ... 11 more
```

### Steps to reproduce:

- Start the API Manager with TM profile optimization
- Stop the server
- Generate the WUM diff between 1594402104830 and 1617282104859
- Copy the diff artifacts and place them in the existing pack
- Remove the files under the "Removed files" in the update summary PDF from all of the nodes.
- Remove the `/repository/resources/conf/.metadata` folder to avoid profile setup failures.
- Apply the corresponding product profile to each node.
- Get back the old `deployment.toml` named as `deployment.toml.backup` by the `profileSetup.sh`
- Give 755 permissions to all of the new files.
- Start the node again with the profile

### Potential Fix

Enhancing the `profileSetup.sh` to optimize the profiles and to copy the relative J2 templates without replacing (moving and renaming) them with the original artifacts.

### Affected Product Version:

- API Manager v3.x

**Comment by athiththan11** [comment]
### Potential Fix

Updating the `<apim>/bin/profileSetup.sh` with the following enhancements (changing the `mv` command with `cp` command) will resolve the replacement of existing configurations and will allow keeping originals as well inside the J2 template directories.

```sh
replaceAxis2TemplateFile(){
	pathToNewAxis2TemplateXml=$1
	if [ -e $pathToAxis2XMLTemplate ] && [ -e $pathToNewAxis2TemplateXml ]
	then
		...
		# mv $pathToNewAxis2TemplateXml $pathToAxis2XMLTemplate
		cp $pathToNewAxis2TemplateXml $pathToAxis2XMLTemplate
		...
	fi
}

replaceTenantAxis2TemplateFile(){
	pathToNewAxis2TemplateXml=$1
	if [ -e $pathToTenantAxis2XMLTemplate ] && [ -e $pathToNewAxis2TemplateXml ]
	then
		...
		# mv $pathToNewAxis2TemplateXml $pathToTenantAxis2XMLTemplate
		cp $pathToNewAxis2TemplateXml $pathToTenantAxis2XMLTemplate
                ...
	fi
}

replaceRegistryXMLTemplateFile(){
  if [ -e $pathToRegistryTemplate ] && [ -e $pathToRegistryTMTemplate ]
	then
	  	...
		# mv $pathToRegistryTMTemplate $pathToRegistryTemplate
		cp $pathToRegistryTMTemplate $pathToRegistryTemplate
		...
	fi
}
```
