### ISSUE TITLE
NullPointer Exception when trying to create a new API version providing invalid service version

### ISSUE THREAD

**Issue by YasasRangika** [wso2/product-apim#11100]
### Description:
Below exception thrown when trying to create new API version from API created from integration service. Provided version is not valid version.

cURL:

```
curl 'https://localhost:9443/api/am/publisher/v2/apis/copy-api?newVersion=8&defaultVersion=false&serviceVersion=6.0.0&apiId=0243311d-861f-4330-9060-f967e8c3513e' \
  -X 'POST' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 0' \
  -H 'sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'authorization: Bearer 08b5eb06-adc8-36db' \
  -H 'Accept: */*' \
  -H 'Origin: https://localhost:9443' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://localhost:9443/publisher/apis/0243311d-861f-4330-9060-f967e8c3513e/new_version' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Cookie: AM_ACC_TOKEN_DEFAULT_P2=-9fdd-3c5b62db7a0c; requestedURI=../../carbon/admin/index.jsp; region1_configure_menu=none; region3_registry_menu=none; region4_monitor_menu=none; region5_tools_menu=none; menuPanel=visible; menuPanelType=config; current-breadcrumb=; JSESSIONID=4ACA48B6A6DB79E5C8014F34FDCBFE24; commonAuthId=a2ec3576-686f-46bc-8eab-dcc5df834488; opbs=3df02d75-d64c-4a36-a3ff-645a487d0c88' \
  --compressed \
  --insecure
```

Server log error:

```
[2021-04-21 19:07:35,625] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.createNewAPIVersion(ApisApiServiceImpl.java:3738) ~[classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.createNewAPIVersion(ApisApi.java:301) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
```

#### Suggested Labels:
4.0.0-PostRelease

**Comment by YasasRangika** [comment]
This issue is in-progress
