### ISSUE TITLE
java.lang.IllegalStateException: I/O reactor has been shut down

### ISSUE THREAD

**Issue by billpratt** [wso2/product-apim#1111]
We recently stood up a API manager 2.0 cluster and started running performance/load testing. At around 10K users we start seeing the below error and everything stops working. We have each component (key manager (1), traffic manager (1), gateway manager (1), gateway workers (3)) in a distributed state.

```java
TID: [-1234] [] [2016-09-08 15:21:05,414] ERROR {org.apache.synapse.core.axis2.Axis2Sender} -  Unexpected error during sending message out {org.apache.synapse.core.axis2.Axis2Sender}
java.lang.IllegalStateException: I/O reactor has been shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.connect(DefaultConnectingIOReactor.java:225)
	at org.apache.synapse.transport.passthru.connections.TargetConnections.getConnection(TargetConnections.java:97)
	at org.apache.synapse.transport.passthru.DeliveryAgent.submit(DeliveryAgent.java:159)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:255)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.synapse.core.axis2.DynamicAxisOperation$DynamicOperationClient.send(DynamicAxisOperation.java:185)
	at org.apache.synapse.core.axis2.DynamicAxisOperation$DynamicOperationClient.executeImpl(DynamicAxisOperation.java:167)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.synapse.core.axis2.Axis2FlexibleMEPClient.send(Axis2FlexibleMEPClient.java:566)
	at org.apache.synapse.core.axis2.Axis2Sender.sendOn(Axis2Sender.java:78)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:544)
	at org.apache.synapse.endpoints.AbstractEndpoint.send(AbstractEndpoint.java:382)
	at org.apache.synapse.endpoints.HTTPEndpoint.send(HTTPEndpoint.java:85)
	at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:118)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:95)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:57)
	at org.apache.synapse.config.xml.AnonymousListMediator.mediate(AnonymousListMediator.java:37)
	at org.apache.synapse.mediators.filters.FilterMediator.mediate(FilterMediator.java:203)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:95)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:57)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:325)
	at org.apache.synapse.rest.API.process(API.java:399)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:125)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:101)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:300)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:75)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:319)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by chamilaadhi** [comment]
Have you tried tuning the API Manager . see https://docs.wso2.com/display/AM200/Tuning+Performance

**Comment by billpratt** [comment]
We will try that. Thank you

**Comment by billpratt** [comment]
This seems to have fixed it. Thank you!
