### ISSUE TITLE
Error while exporting APIs when having document source type as file and without uploading a file

### ISSUE THREAD

**Issue by Shehanir** [wso2/product-apim#11158]
### Description:
Cannot export APIs when having document source type as file and without uploading a file

### Steps to reproduce:

- Create an API via the publisher portal.
- Navigate to the Documents section.
- Select a document type (any type from How To, Sample & SDK or Other)
- Select File as the Source.
- Save the document without uploading a file.
- Then try to export that API
 
Error: 
<img width="1148" alt="Screenshot 2021-05-03 at 13 34 32" src="https://user-images.githubusercontent.com/47380804/116854052-b1f6d880-ac14-11eb-9d31-ca4908fbf811.png">

Stack trace:

> `java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.impl.importexport.utils.APIAndAPIProductCommonUtil.exportAPIOrAPIProductDocumentation_aroundBody2(APIAndAPIProductCommonUtil.java:163) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.utils.APIAndAPIProductCommonUtil.exportAPIOrAPIProductDocumentation(APIAndAPIProductCommonUtil.java:148) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.utils.APIExportUtil.exportAPIDocumentation_aroundBody6(APIExportUtil.java:265) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.utils.APIExportUtil.exportAPIDocumentation(APIExportUtil.java:262) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.utils.APIExportUtil.retrieveApiToExport_aroundBody0(APIExportUtil.java:133) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.utils.APIExportUtil.retrieveApiToExport(APIExportUtil.java:111) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.APIImportExportManager.exportAPIArtifacts_aroundBody4(APIImportExportManager.java:109) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.APIImportExportManager.exportAPIArtifacts(APIImportExportManager.java:102) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.APIImportExportManager.exportAPIOrAPIProductArchive_aroundBody2(APIImportExportManager.java:78) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.APIImportExportManager.exportAPIOrAPIProductArchive(APIImportExportManager.java:73) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.utils.APIExportUtil.exportApi_aroundBody32(APIExportUtil.java:811) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.utils.APIExportUtil.exportApi(APIExportUtil.java:802) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.rest.api.util.impl.ExportApiUtil.exportApiOrApiProductByParams(ExportApiUtil.java:111) ~[org.wso2.carbon.apimgt.rest.api.util_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.rest.api.admin.v1.impl.ExportApiServiceImpl.exportApiGet(ExportApiServiceImpl.java:67) ~[classes/:?]
	at org.wso2.carbon.apimgt.rest.api.admin.v1.ExportApi.exportApiGet(ExportApi.java:54) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:225) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [tomcat-servlet-api_9.0.31.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86) [org.wso2.carbon.identity.context.rewrite.valve_1.4.0.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.0.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:102) [org.wso2.carbon.identity.auth.valve_1.4.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [tomcat_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:124) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.31.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.31.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by NethmiRanasinghe** [comment]
This issue is not reproducing in the latest version APIM 4.4.0
