### ISSUE TITLE
Verifying the hostname when send the revoked tokens from the Identity Server to the Traffic Manager node even after disable the hostname verification in both nodes

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11184]
### Description:
Verifying the hostname when send the revoked tokens from the Identity Server to the Traffic Manager node even after disable the hostname verification in both nodes.

### Steps to reproduce:

- Configure the WSO2 Identity server with API Manager
- Add a mapping in the /etc/hosts file as below. (to change the hostname from localhost)

`127.0.0.1   apimanager`

- Open the **deployment.toml** file inside the <IS_HOME>/repository/conf directory.
- Change the **[event_listener.properties]** by configuring the notification endpoint with the configured hostname.

```
[event_listener.properties]
notification_endpoint = "https://apimanager:9443/internal/data/v1/notify"
username = "${admin.username}"
password = "${admin.password}"
'header.X-WSO2-KEY-MANAGER' = "WSO2IS"
```

- Start the IS node and API Manager node. When starting nodes, parse below JVM arguments to disable hostname verification in both nodes.

`-Dorg.opensaml.httpclient.https.disableHostnameVerification=true -Dhttpclient.hostnameVerifier="AllowAll"`

- Create an application via the dev portal and generate an access token by referring to the configured IS key manager.
- Try to revoke the access token by calling the revoke endpoint of the key manager and  able to see a similar stacktrace in the IS node.

```
[2021-05-05 18:41:41,178] [324f8412-f06e-4ff4-9aa4-173739248831] ERROR {org.wso2.is.notification.EventSender} - Error while sending Revocation Event to https://apimanager:9443/internal/data/v1/notify javax.net.ssl.SSLException: hostname in certificate didn't match: <apimanager> != <localhost> OR <localhost>
at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:238)
at org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:54)
at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:159)
at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:140)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:301)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:291)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:259)
at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:125)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:319)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
at org.wso2.is.notification.EventSender$EventRunner.run(EventSender.java:116)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

### Affected Product Version:
3.2.0

**Comment by RusJaI** [comment]
Hi all,
Please find the ETA as follows : 
Best case : 2023/05/26
Most likely: 2023/06/02
Worst case : 2023/06/12
