### ISSUE TITLE
Error while downloading wsdl from developer portal

### ISSUE THREAD

**Issue by isharac** [wso2/product-apim#11208]
### Description:

When downloading wsdl of a soap API from the developer portal a NPE is thrawn as below.

WARN - WSDL11SOAPOperationExtractor Cannot access referenced schema for the schema defined at: http://schemas.xmlsoap.org/soap/encoding/
[2021-05-06 14:25:58,686] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: null
at org.wso2.carbon.apimgt.impl.wsdl.WSDL11ProcessorImpl.updateEndpointsOfWSDLArchive_aroundBody16(WSDL11ProcessorImpl.java:290) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
at org.wso2.carbon.apimgt.impl.wsdl.WSDL11ProcessorImpl.updateEndpointsOfWSDLArchive(WSDL11ProcessorImpl.java:288) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
at org.wso2.carbon.apimgt.impl.wsdl.WSDL11ProcessorImpl.updateEndpoints_aroundBody10(WSDL11ProcessorImpl.java:210) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
at org.wso2.carbon.apimgt.impl.wsdl.WSDL11ProcessorImpl.updateEndpoints(WSDL11ProcessorImpl.java:206) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getWSDL_aroundBody236(APIConsumerImpl.java:5186) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getWSDL(APIConsumerImpl.java:5174) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApisApiServiceImpl.getWSDLOfAPI(ApisApiServiceImpl.java:866) ~[classes/:?]
at org.wso2.carbon.apimgt.rest.api.store.v1.ApisApi.getWSDLOfAPI(ApisApi.java:378) ~[classes/:?]
at sun.reflect.GeneratedMethodAccessor358.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]

**Comment by NethmiRanasinghe** [comment]
This issue is not reproducing in the latest version
