### ISSUE TITLE
Error loading alert configurations when subscription deleted

### ISSUE THREAD

**Issue by AshenShalitha** [wso2/product-apim#11236]
### Description:
The issue occurs when the API subscription deleted from an application which already has an alert configuration. The following exception throws when a particular user tries to navigate to the settings page in the devportal after deleting the API subscription. 

`[2021-05-20 16:59:43,233] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NumberFormatException: For input string: "null"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_201]
at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_201]
at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_201]
at org.wso2.carbon.apimgt.rest.api.store.v1.mappings.AlertsMappingUtil.toAlertConfigDTO(AlertsMappingUtil.java:45) ~[classes/:?]
at org.wso2.carbon.apimgt.rest.api.store.v1.impl.AlertsApiServiceImpl.getAllAlertConfigs(AlertsApiServiceImpl.java:91) ~[classes/:?]
at org.wso2.carbon.apimgt.rest.api.store.v1.AlertsApi.getAllAlertConfigs(AlertsApi.java:89) ~[classes/:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
`

The exception throws from [1] , when it tries to retrieve the application name by passing "null" as the applicationId to the parseInt() method. "null" represents the applicationId of the subscription deleted application. 

Furthermore, upon deleting the API subscription, an additional alert configuration is added to the alert configuration list. This additional config is created for the same alert configuration and it represents the subscription deleted alert configuration. This config is where the applicationId becomes "null". Please refer to the below image.

![image](https://user-images.githubusercontent.com/28749597/119086369-04acfe80-ba23-11eb-8b45-a4dd05a0c320.png)

### Steps to reproduce:

1. Configure APIM 3.1.0 with APIM Analytics and start the servers.
2. Publish an API and subscribe through an application.
3. Click on the settings button in the devportal and enable both Abnormal Requests per Minute and Abnormal Resource Access.
4. Add an alert configuration under Abnormal Requests per Minute for the created API application pair.
5. Delete the API subscription.
6. Then, navigate to the Alert section by clicking on Settings button. There will be UI error with the above mentioned exception in the logs.

### Affected Product Version:
APIM-3.1.0  + 1620925753694

[1] https://github.com/wso2-support/carbon-apimgt/blob/ea6988907edd112d478382822667ea8be44158f6/components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/mappings/AlertsMappingUtil.java#L45

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
