### ISSUE TITLE
Cannot create an API product - ClassCastException (MapSchema to ObjectSchema)

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11243]
### Description:
When trying to create an API product by using API resources which has **additionalProperties** in the swagger component schema, that will throw a **java.lang.ClassCastException**

### Steps to reproduce:

- Create an API via the publisher portal by using the below swagger content.

```
openapi: 3.0.1
info:
  title: TEST_API
  version: 1.0.0
servers:
  - url: 'https://localhost.com'
security:
  - default: []
paths:
  /testPath/testResource:
    post:
      description: 'Test resource description'
      requestBody:
        description: sample request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/testResourceRequest'
        required: true
      responses:
        '200':
          description: 'Successful response'
        '400':
          description: 'Bad Request'
        '401':
          description: 'Unauthorized'
        '500':
          description: 'Internal Server Error'
      security:
        - x-jwt-assertion: []
        - default: []
      x-auth-type: None
      x-throttling-tier: Unlimited
components:
  schemas:
    testResourceRequest:
      type: object
      properties:
        sampleProperty:
          type: object
          additionalProperties:
            type: object
            description: sample description of additional properties
          description: sample property description
      description: 'Request to issuer to enroll a new token onto a device.'
  securitySchemes:
    x-jwt-assertion:
      type: apiKey
      name: x-jwt-assertion
      in: header
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://localhost.com'
          scopes: {}
```

- When trying to create an API product by adding the created API resource, could able to see the below error message in the UI.

![Screenshot from 2021-05-24 12-00-04](https://user-images.githubusercontent.com/18566908/119306341-a2086c80-bc87-11eb-9ef6-4fbd10452a41.png)

- Furthermore, can see the below error stack trace.

```
[2021-05-24 12:00:03,993] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.ClassCastException: io.swagger.v3.oas.models.media.MapSchema cannot be cast to io.swagger.v3.oas.models.media.ObjectSchema
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.addSchemaOfSchema_aroundBody40(OASParserUtil.java:721) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.addSchemaOfSchema(OASParserUtil.java:719) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.extractReferenceFromSchema_aroundBody38(OASParserUtil.java:668) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.extractReferenceFromSchema(OASParserUtil.java:659) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.extractReferenceFromSchema_aroundBody38(OASParserUtil.java:713) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.extractReferenceFromSchema(OASParserUtil.java:659) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.processReferenceObjectMap_aroundBody14(OASParserUtil.java:404) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.processReferenceObjectMap(OASParserUtil.java:376) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.setReferenceObjectDefinitions_aroundBody12(OASParserUtil.java:298) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.setReferenceObjectDefinitions(OASParserUtil.java:297) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.updateAPIProductSwaggerOperations_aroundBody8(OASParserUtil.java:267) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.updateAPIProductSwaggerOperations(OASParserUtil.java:244) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApiProductsApiServiceImpl.addAPIProductSwagger(ApiProductsApiServiceImpl.java:774) ~[classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApiProductsApiServiceImpl.apiProductsPost(ApiProductsApiServiceImpl.java:738) ~[classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApiProductsApi.apiProductsPost(ApiProductsApi.java:328) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-servlet-api_9.0.31.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86) [org.wso2.carbon.identity.context.rewrite.valve_1.4.0.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.0.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:102) [org.wso2.carbon.identity.auth.valve_1.4.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [tomcat_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.31.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.31.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

### Affected Product Version:
3.1.0

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/10583
