### ISSUE TITLE
[APIM-3.1.0] - API search in Dev-portal is not working while in the overview page of some other API.

### ISSUE THREAD

**Issue by Prabhashi** [wso2/product-apim#11269]
### Description:
API search in Dev-portal is not working while in the overview page of some other API.

### Steps to reproduce:

**Issue 01:**

- Started the APIM pack (APIM 3.1.0 -t 1621357495190). 
- Created two APIs, one with "-" inside the API name.
- Go to the Dev-portal and go inside one of the APIs. Then search the other API. It will come under the search list as below.
![image](https://user-images.githubusercontent.com/28176167/119931552-37b13e00-bf9f-11eb-97a4-93f984f28f82.png)
- Click on that API. The overview page will not be changed to this new API even-though the URL has been changed with the relevant API ID. Please refer to the below.
![image](https://user-images.githubusercontent.com/28176167/119931634-56173980-bf9f-11eb-897b-d7cb38534070.png)

**Issue 02:**

- After the above last step, if we press enter twice, the relevant API can be seen as below.
![image](https://user-images.githubusercontent.com/28176167/119931834-c7ef8300-bf9f-11eb-92a1-8eec18b9b6ac.png)
-  However, if we do the same for the API with "-", there will be no API. Please refer to the below.
![image](https://user-images.githubusercontent.com/28176167/119931892-e6ee1500-bf9f-11eb-9c68-bb292355f13b.png)

**Workaround for Issue 02:**

If we searched with double quotes (ex: "Sample-API") the above issue 02 can not be seen.
However, we could see below errors in the logs.
```
[2021-05-28 10:32:29,555] ERROR - RequestHandlerBase org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: Cannot parse '*"SAMple-API*': Lexical error at line 1, column 14.  Encountered: <EOF> after : "\"SAMple-API*"
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:216)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:246)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2102)
	at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:178)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:942)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:957)
	at org.wso2.carbon.registry.indexing.solr.SolrClient.query(SolrClient.java:640)
	at org.wso2.carbon.registry.indexing.solr.SolrClient.query(SolrClient.java:555)
	at org.wso2.carbon.registry.indexing.service.ContentBasedSearchService.searchContentInternal(ContentBasedSearchService.java:166)
	at org.wso2.carbon.registry.indexing.service.ContentBasedSearchService.searchByAttribute(ContentBasedSearchService.java:279)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.searchPaginatedAPIsByContent_aroundBody200(AbstractAPIManager.java:2920)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.searchPaginatedAPIsByContent(AbstractAPIManager.java:2813)
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.searchPaginatedAPIsByContent_aroundBody250(APIConsumerImpl.java:5473)
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.searchPaginatedAPIsByContent(APIConsumerImpl.java:5469)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.searchPaginatedAPIs_aroundBody172(AbstractAPIManager.java:2236)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.searchPaginatedAPIs(AbstractAPIManager.java:2137)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.searchPaginatedAPIs_aroundBody170(AbstractAPIManager.java:2133)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.searchPaginatedAPIs(AbstractAPIManager.java:2131)
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.searchPaginatedAPIs_aroundBody66(APIConsumerImpl.java:2328)
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.searchPaginatedAPIs(APIConsumerImpl.java:2325)
	at org.wso2.carbon.apimgt.rest.api.store.v1.impl.SearchApiServiceImpl.searchGet(SearchApiServiceImpl.java:97)
	at org.wso2.carbon.apimgt.rest.api.store.v1.SearchApi.searchGet(SearchApi.java:53)
	at sun.reflect.GeneratedMethodAccessor300.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:225)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:102)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.search.SyntaxError: Cannot parse '*"SAMple-API*': Lexical error at line 1, column 14.  Encountered: <EOF> after : "\"SAMple-API*"
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:157)
	at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:50)
	at org.apache.solr.search.QParser.getQuery(QParser.java:141)
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:159)
	... 74 more
Caused by: org.apache.solr.parser.TokenMgrError: Lexical error at line 1, column 14.  Encountered: <EOF> after : "\"SAMple-API*"
	at org.apache.solr.parser.QueryParserTokenManager.getNextToken(QueryParserTokenManager.java:1585)
	at org.apache.solr.parser.QueryParser.jj_scan_token(QueryParser.java:556)
	at org.apache.solr.parser.QueryParser.jj_3R_3(QueryParser.java:439)
	at org.apache.solr.parser.QueryParser.jj_3_1(QueryParser.java:454)
	at org.apache.solr.parser.QueryParser.jj_2_1(QueryParser.java:432)
	at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:155)
	at org.apache.solr.parser.QueryParser.Query(QueryParser.java:107)
	at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:96)
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:153)
	... 77 more

[2021-05-28 10:32:29,558] ERROR - ContentBasedSearchService Invalid Search Query, query contains invalid characters
org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: Cannot parse '*"SAMple-API*': Lexical error at line 1, column 14.  Encountered: <EOF> after : "\"SAMple-API*"
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:216) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:246) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2102) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:178) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:942) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:957) ~[solr_5.5.5.wso2v1.jar:?]
	at org.wso2.carbon.registry.indexing.solr.SolrClient.query(SolrClient.java:640) ~[org.wso2.carbon.registry.indexing_4.7.32.jar:?]
	at org.wso2.carbon.registry.indexing.solr.SolrClient.query(SolrClient.java:555) ~[org.wso2.carbon.registry.indexing_4.7.32.jar:?]
	at org.wso2.carbon.registry.indexing.service.ContentBasedSearchService.searchContentInternal(ContentBasedSearchService.java:166) [org.wso2.carbon.registry.indexing_4.7.32.jar:?]
	at org.wso2.carbon.registry.indexing.service.ContentBasedSearchService.searchByAttribute(ContentBasedSearchService.java:279) [org.wso2.carbon.registry.indexing_4.7.32.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.searchPaginatedAPIsByContent_aroundBody200(AbstractAPIManager.java:2920) [org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.searchPaginatedAPIsByContent(AbstractAPIManager.java:2813) [org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.searchPaginatedAPIsByContent_aroundBody250(APIConsumerImpl.java:5473) [org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.searchPaginatedAPIsByContent(APIConsumerImpl.java:5469) [org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.searchPaginatedAPIs_aroundBody172(AbstractAPIManager.java:2236) [org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.searchPaginatedAPIs(AbstractAPIManager.java:2137) [org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.searchPaginatedAPIs_aroundBody170(AbstractAPIManager.java:2133) [org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.searchPaginatedAPIs(AbstractAPIManager.java:2131) [org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.searchPaginatedAPIs_aroundBody66(APIConsumerImpl.java:2328) [org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.searchPaginatedAPIs(APIConsumerImpl.java:2325) [org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.impl.SearchApiServiceImpl.searchGet(SearchApiServiceImpl.java:97) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.SearchApi.searchGet(SearchApi.java:53) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor300.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:225) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [tomcat-servlet-api_9.0.31.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86) [org.wso2.carbon.identity.context.rewrite.valve_1.4.0.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.0.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:102) [org.wso2.carbon.identity.auth.valve_1.4.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [tomcat_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.31.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.31.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: org.apache.solr.search.SyntaxError: Cannot parse '*"SAMple-API*': Lexical error at line 1, column 14.  Encountered: <EOF> after : "\"SAMple-API*"
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:157) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:50) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.search.QParser.getQuery(QParser.java:141) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:159) ~[solr_5.5.5.wso2v1.jar:?]
	... 74 more
Caused by: org.apache.solr.parser.TokenMgrError: Lexical error at line 1, column 14.  Encountered: <EOF> after : "\"SAMple-API*"
	at org.apache.solr.parser.QueryParserTokenManager.getNextToken(QueryParserTokenManager.java:1585) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.parser.QueryParser.jj_scan_token(QueryParser.java:556) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.parser.QueryParser.jj_3R_3(QueryParser.java:439) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.parser.QueryParser.jj_3_1(QueryParser.java:454) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.parser.QueryParser.jj_2_1(QueryParser.java:432) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:155) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.parser.QueryParser.Query(QueryParser.java:107) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:96) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:153) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:50) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.search.QParser.getQuery(QParser.java:141) ~[solr_5.5.5.wso2v1.jar:?]
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:159) ~[solr_5.5.5.wso2v1.jar:?]
	... 74 more
```

### Affected Product Version:
APIM 3.1.0

**Comment by Chamindu36** [comment]
This issue is already fixed in the public repository. Hence this issue can be closed.
