### ISSUE TITLE
Error while setting up wso2 apim 3.1.0

### ISSUE THREAD

**Issue by alloh** [wso2/product-apim#11309]
### Description:

  ```[2021-06-07 06:56:46,498]  INFO - StartupFinalizerServiceComponent Server           :  WSO2 API Manager-3.1.0
  [2021-06-07 06:56:46,499]  INFO - StartupFinalizerServiceComponent WSO2 Carbon started in 82 sec
  [2021-06-07 06:56:47,305]  INFO - CarbonUIServiceComponent Mgt Console URL  : https://10.17.114.12:9443/carbon/
  [2021-06-07 06:56:47,306]  INFO - CarbonUIServiceComponent API Developer Portal Default Context : https://10.17.114.12:9443/devportal
  [2021-06-07 06:56:47,306]  INFO - CarbonUIServiceComponent API Publisher Default Context : https://10.17.114.12:9443/publisher
  [2021-06-07 06:57:05,654] ERROR - JMSListener Unable to continue server startup as it seems the JMS Provider is not yet started. Please start the JMS provider now.
  [2021-06-07 06:57:05,656] ERROR - JMSListener Unable to continue server startup as it seems the JMS Provider is not yet started. Please start the JMS provider now.
  [2021-06-07 06:57:05,656] ERROR - JMSListener Connection attempt : 2 for JMS Provider failed. Next retry in 40 seconds
  [2021-06-07 06:57:05,655] ERROR - AMQConnection Throwable Received but no listener set.
  org.wso2.andes.AMQDisconnectedException: Server closed connection and reconnection not permitted.
          at org.wso2.andes.client.protocol.AMQProtocolHandler.closed(AMQProtocolHandler.java:274) [andes_3.3.11.jar:?]
          at org.wso2.andes.transport.network.mina.MinaNetworkHandler.sessionClosed(MinaNetworkHandler.java:150) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain$TailFilter.sessionClosed(AbstractIoFilterChain.java:548) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain.callNextSessionClosed(AbstractIoFilterChain.java:267) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain.access$800(AbstractIoFilterChain.java:51) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain$EntryImpl$1.sessionClosed(AbstractIoFilterChain.java:631) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.IoFilterAdapter.sessionClosed(IoFilterAdapter.java:65) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain.callNextSessionClosed(AbstractIoFilterChain.java:267) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain.access$800(AbstractIoFilterChain.java:51) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain$EntryImpl$1.sessionClosed(AbstractIoFilterChain.java:631) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.filter.executor.ExecutorFilter.processEvent(ExecutorFilter.java:230) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.filter.executor.ExecutorFilter$ProcessEventsRunnable.run(ExecutorFilter.java:264) [andes_3.3.11.jar:?]
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
          at org.wso2.org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:51) [andes_3.3.11.jar:?]
          at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
  [2021-06-07 06:57:05,657] ERROR - JMSListener Connection attempt : 2 for JMS Provider failed. Next retry in 40 seconds
  [2021-06-07 06:57:05,654] ERROR - AMQConnection Throwable Received but no listener set.
  org.wso2.andes.AMQDisconnectedException: Server closed connection and reconnection not permitted.
          at org.wso2.andes.client.protocol.AMQProtocolHandler.closed(AMQProtocolHandler.java:274) [andes_3.3.11.jar:?]
          at org.wso2.andes.transport.network.mina.MinaNetworkHandler.sessionClosed(MinaNetworkHandler.java:150) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain$TailFilter.sessionClosed(AbstractIoFilterChain.java:548) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain.callNextSessionClosed(AbstractIoFilterChain.java:267) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain.access$800(AbstractIoFilterChain.java:51) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain$EntryImpl$1.sessionClosed(AbstractIoFilterChain.java:631) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.IoFilterAdapter.sessionClosed(IoFilterAdapter.java:65) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain.callNextSessionClosed(AbstractIoFilterChain.java:267) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain.access$800(AbstractIoFilterChain.java:51) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain$EntryImpl$1.sessionClosed(AbstractIoFilterChain.java:631) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.filter.executor.ExecutorFilter.processEvent(ExecutorFilter.java:230) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.filter.executor.ExecutorFilter$ProcessEventsRunnable.run(ExecutorFilter.java:264) [andes_3.3.11.jar:?]
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
          at org.wso2.org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:51) [andes_3.3.11.jar:?]
          at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
  [2021-06-07 06:57:05,661] ERROR - JMSListener Unable to continue server startup as it seems the JMS Provider is not yet started. Please start the JMS provider now.
  [2021-06-07 06:57:05,661] ERROR - AMQConnection Throwable Received but no listener set.
  org.wso2.andes.AMQDisconnectedException: Server closed connection and reconnection not permitted.
          at org.wso2.andes.client.protocol.AMQProtocolHandler.closed(AMQProtocolHandler.java:274) [andes_3.3.11.jar:?]
          at org.wso2.andes.transport.network.mina.MinaNetworkHandler.sessionClosed(MinaNetworkHandler.java:150) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain$TailFilter.sessionClosed(AbstractIoFilterChain.java:548) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain.callNextSessionClosed(AbstractIoFilterChain.java:267) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain.access$800(AbstractIoFilterChain.java:51) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain$EntryImpl$1.sessionClosed(AbstractIoFilterChain.java:631) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.IoFilterAdapter.sessionClosed(IoFilterAdapter.java:65) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain.callNextSessionClosed(AbstractIoFilterChain.java:267) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain.access$800(AbstractIoFilterChain.java:51) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain$EntryImpl$1.sessionClosed(AbstractIoFilterChain.java:631) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.filter.executor.ExecutorFilter.processEvent(ExecutorFilter.java:230) [andes_3.3.11.jar:?]
          at org.wso2.org.apache.mina.filter.executor.ExecutorFilter$ProcessEventsRunnable.run(ExecutorFilter.java:264) [andes_3.3.11.jar:?]
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
          at org.wso2.org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:51) [andes_3.3.11.jar:?]
          at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
  [2021-06-07 06:57:05,661] ERROR - JMSListener Connection attempt : 2 for JMS Provider failed. Next retry in 40 seconds
  [2021-06-07 06:57:45,703] ERROR - JMSListener Unable to continue server startup as it seems the JMS Provider is not yet started. Please start the JMS provider now.
  [2021-06-07 06:57:45,707] ERROR - JMSListener Unable to continue server startup as it seems the JMS Provider is not yet started. Please start the JMS provider now.
  [2021-06-07 06:57:45,702] ERROR - AMQConnection Throwable Received but no listener set.
  org.wso2.andes.AMQDisconnectedException: Server closed connection and reconnection not permitted.
  
          at org.wso2.andes.client.protocol.AMQProtocolHandler.closed(AMQProtocolHandler.java:274) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.closeConnection(AMQProtocolHandler.java:755) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolSession.closeProtocolSession(AMQProtocolSession.java:379) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:104) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.handler.ClientMethodDispatcherImpl.dispatchConnectionClose(ClientMethodDispatcherImpl.java:192) [andes_3.3.11.jar:?]
          at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.state.AMQStateManager.methodReceived(AMQStateManager.java:111) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:554) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467) [andes_3.3.11.jar:?]
          at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:92) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:487) [andes_3.3.11.jar:?]
          at org.wso2.andes.pool.Job.processAll(Job.java:111) [andes_3.3.11.jar:?]
          at org.wso2.andes.pool.Job.run(Job.java:158) [andes_3.3.11.jar:?]
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
          at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
  [2021-06-07 06:57:45,702] ERROR - AMQConnection Throwable Received but no listener set.
  org.wso2.andes.AMQDisconnectedException: Server closed connection and reconnection not permitted.
          at org.wso2.andes.client.protocol.AMQProtocolHandler.closed(AMQProtocolHandler.java:274) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.closeConnection(AMQProtocolHandler.java:755) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolSession.closeProtocolSession(AMQProtocolSession.java:379) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:104) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.handler.ClientMethodDispatcherImpl.dispatchConnectionClose(ClientMethodDispatcherImpl.java:192) [andes_3.3.11.jar:?]
          at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.state.AMQStateManager.methodReceived(AMQStateManager.java:111) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:554) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467) [andes_3.3.11.jar:?]
          at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:92) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:487) [andes_3.3.11.jar:?]
          at org.wso2.andes.pool.Job.processAll(Job.java:111) [andes_3.3.11.jar:?]
          at org.wso2.andes.pool.Job.run(Job.java:158) [andes_3.3.11.jar:?]
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
          at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
  [2021-06-07 06:57:45,707] ERROR - JMSListener Connection attempt : 3 for JMS Provider failed. Next retry in 80 seconds
  [2021-06-07 06:57:45,707] ERROR - JMSListener Connection attempt : 3 for JMS Provider failed. Next retry in 80 seconds
  [2021-06-07 06:57:45,713] ERROR - JMSListener Unable to continue server startup as it seems the JMS Provider is not yet started. Please start the JMS provider now.
  [2021-06-07 06:57:45,709] ERROR - AMQConnection Throwable Received but no listener set.
  org.wso2.andes.AMQException: AMQP timed out when attempting to close the connection
          at org.wso2.andes.client.protocol.AMQProtocolHandler.closeConnection(AMQProtocolHandler.java:746) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolSession.closeProtocolSession(AMQProtocolSession.java:379) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:104) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.handler.ClientMethodDispatcherImpl.dispatchConnectionClose(ClientMethodDispatcherImpl.java:192) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.state.AMQStateManager.methodReceived(AMQStateManager.java:111) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:554) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467) [andes_3.3.11.jar:?]
          at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:92) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:487) [andes_3.3.11.jar:?]
          at org.wso2.andes.pool.Job.processAll(Job.java:111) [andes_3.3.11.jar:?]
          at org.wso2.andes.pool.Job.run(Job.java:158) [andes_3.3.11.jar:?]
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
          at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
  Caused by: org.wso2.andes.AMQTimeoutException: Server did not respond in a timely fashion
          at org.wso2.andes.client.util.BlockingWaiter.block(BlockingWaiter.java:176) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.BlockingMethodFrameListener.blockForFrame(BlockingMethodFrameListener.java:122) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.writeCommandFrameAndWaitForReply(AMQProtocolHandler.java:689) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.syncWrite(AMQProtocolHandler.java:711) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.closeConnection(AMQProtocolHandler.java:742) ~[andes_3.3.11.jar:?]
          ... 14 more
  [2021-06-07 06:57:45,708] ERROR - AMQConnection Throwable Received but no listener set.
  org.wso2.andes.AMQException: AMQP timed out when attempting to close the connection
          at org.wso2.andes.client.protocol.AMQProtocolHandler.closeConnection(AMQProtocolHandler.java:746) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolSession.closeProtocolSession(AMQProtocolSession.java:379) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:104) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.handler.ClientMethodDispatcherImpl.dispatchConnectionClose(ClientMethodDispatcherImpl.java:192) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.state.AMQStateManager.methodReceived(AMQStateManager.java:111) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:554) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467) [andes_3.3.11.jar:?]
          at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:92) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:487) [andes_3.3.11.jar:?]
          at org.wso2.andes.pool.Job.processAll(Job.java:111) [andes_3.3.11.jar:?]
          at org.wso2.andes.pool.Job.run(Job.java:158) [andes_3.3.11.jar:?]
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
          at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
  Caused by: org.wso2.andes.AMQTimeoutException: Server did not respond in a timely fashion
          at org.wso2.andes.client.util.BlockingWaiter.block(BlockingWaiter.java:176) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.BlockingMethodFrameListener.blockForFrame(BlockingMethodFrameListener.java:122) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.writeCommandFrameAndWaitForReply(AMQProtocolHandler.java:689) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.syncWrite(AMQProtocolHandler.java:711) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.closeConnection(AMQProtocolHandler.java:742) ~[andes_3.3.11.jar:?]
          ... 14 more
  [2021-06-07 06:57:45,714] ERROR - JMSListener Connection attempt : 3 for JMS Provider failed. Next retry in 80 seconds
  [2021-06-07 06:57:45,714] ERROR - AMQConnection Throwable Received but no listener set.
  org.wso2.andes.AMQDisconnectedException: Server closed connection and reconnection not permitted.
          at org.wso2.andes.client.protocol.AMQProtocolHandler.closed(AMQProtocolHandler.java:274) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.closeConnection(AMQProtocolHandler.java:755) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolSession.closeProtocolSession(AMQProtocolSession.java:379) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:104) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.handler.ClientMethodDispatcherImpl.dispatchConnectionClose(ClientMethodDispatcherImpl.java:192) [andes_3.3.11.jar:?]
          at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.state.AMQStateManager.methodReceived(AMQStateManager.java:111) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:554) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467) [andes_3.3.11.jar:?]
          at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:92) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:487) [andes_3.3.11.jar:?]
          at org.wso2.andes.pool.Job.processAll(Job.java:111) [andes_3.3.11.jar:?]
          at org.wso2.andes.pool.Job.run(Job.java:158) [andes_3.3.11.jar:?]
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
          at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
  [2021-06-07 06:57:45,716] ERROR - AMQConnection Throwable Received but no listener set.
  org.wso2.andes.AMQException: AMQP timed out when attempting to close the connection
          at org.wso2.andes.client.protocol.AMQProtocolHandler.closeConnection(AMQProtocolHandler.java:746) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolSession.closeProtocolSession(AMQProtocolSession.java:379) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:104) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.handler.ClientMethodDispatcherImpl.dispatchConnectionClose(ClientMethodDispatcherImpl.java:192) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.state.AMQStateManager.methodReceived(AMQStateManager.java:111) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:554) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467) [andes_3.3.11.jar:?]
          at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:92) [andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:487) [andes_3.3.11.jar:?]
          at org.wso2.andes.pool.Job.processAll(Job.java:111) [andes_3.3.11.jar:?]
          at org.wso2.andes.pool.Job.run(Job.java:158) [andes_3.3.11.jar:?]
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
          at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
  Caused by: org.wso2.andes.AMQTimeoutException: Server did not respond in a timely fashion
          at org.wso2.andes.client.util.BlockingWaiter.block(BlockingWaiter.java:176) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.BlockingMethodFrameListener.blockForFrame(BlockingMethodFrameListener.java:122) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.writeCommandFrameAndWaitForReply(AMQProtocolHandler.java:689) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.syncWrite(AMQProtocolHandler.java:711) ~[andes_3.3.11.jar:?]
          at org.wso2.andes.client.protocol.AMQProtocolHandler.closeConnection(AMQProtocolHandler.java:742) ~[andes_3.3.11.jar:?]
          ... 14 more```


### Steps to reproduce:
run ./wso2server.sh -DSetup

### Affected Product Version:
<!-- Members can use Affected/*** labels -->
3.1.0

### Environment details (with versions):
- OS: centos
- Client:
- Env (Docker/K8s):

**Comment by Krishanx92** [comment]
Stale issue. Working fine with latest product.
