### ISSUE TITLE
Issues in secured websocket APIs after the passwords encrypted 

### ISSUE THREAD

**Issue by chaliya96** [wso2/product-apim#11319]
### Description:
When the APIM configuration level passwords (keystore password, key_password) are encrypted, secured websocket API invoking are getting failed. Getting the following SSL logs in the wso2carbon.log file. 
`
java.lang.IllegalArgumentException: Failed to initialize the server side SSLContext

	at org.wso2.carbon.inbound.endpoint.protocol.websocket.ssl.SSLHandlerFactory.<init>(SSLHandlerFactory.java:72) ~[?:?]

	at org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketChannelInitializer.initChannel(InboundWebsocketChannelInitializer.java:81) ~[?:?]

	at org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketChannelInitializer.initChannel(InboundWebsocketChannelInitializer.java:34) ~[?:?]

	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]

	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]

	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:953) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]

	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:610) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]

	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]

	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1461) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]

	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1126) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]

	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:651) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]

	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:515) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]

	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:428) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]

	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:487) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]

	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [io.netty.common_4.1.34.Final.jar:4.1.34.Final]

	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [io.netty.common_4.1.34.Final.jar:4.1.34.Final]

	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) [io.netty.transport_4.1.34.Final.jar:4.1.34.Final]

	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [io.netty.common_4.1.34.Final.jar:4.1.34.Final]

	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.common_4.1.34.Final.jar:4.1.34.Final]

	at java.lang.Thread.run(Thread.java:829) [?:?]

Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect

	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:792) ~[?:?]

	at sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222) ~[?:?]

	at java.security.KeyStore.load(KeyStore.java:1479) ~[?:?]

	at org.wso2.carbon.inbound.endpoint.protocol.websocket.ssl.SSLHandlerFactory.getKeyStore(SSLHandlerFactory.java:80) ~[?:?]

	at org.wso2.carbon.inbound.endpoint.protocol.websocket.ssl.SSLHandlerFactory.<init>(SSLHandlerFactory.java:53) ~[?:?]

	... 19 more

Caused by: java.security.UnrecoverableKeyException: Password verification failed

	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:790) ~[?:?]

	at sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222) ~[?:?]

	at java.security.KeyStore.load(KeyStore.java:1479) ~[?:?]

	at org.wso2.carbon.inbound.endpoint.protocol.websocket.ssl.SSLHandlerFactory.getKeyStore(SSLHandlerFactory.java:80) ~[?:?]

	at org.wso2.carbon.inbound.endpoint.protocol.websocket.ssl.SSLHandlerFactory.<init>(SSLHandlerFactory.java:53) ~[?:?]

	... 19 more
`

### Steps to reproduce:
Encrypt keystore password and key password. 
Create a websocket API and invoke it through the WSS port - 8099 

### Affected Product Version:
APIM v3.2.0

**Comment by dushaniw** [comment]
fixed with https://github.com/wso2/wso2-synapse/pull/1817
