### ISSUE TITLE
Saving an API with an invalid URI pattern

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/product-apim#11367]
### Description:
On the second attempt, it is possible to save an API with a new resource as an invalid URI pattern. After this it is not allowed to invoke any resource in the API and receives "404 The requested resource is not available." error. Even after removing the wrong resource and saving the API, the same error is observed. This due to API synapse file not being available in the <APIM_Home>/repository/deployment/server/synapse-configs/default/api directory. In the Publisher portal the API is displayed as in published state but without picking any Gateways in the Environments tab.
It is better to add a validation not to save the API when there is an invalid URI pattern.

### Steps to reproduce:
1. Add a new resource to an API with a typo. ( /test/{abc/123 )

2. Save the API.
![image](https://user-images.githubusercontent.com/30709975/123582029-af6ec480-d7fa-11eb-962d-675b3037220d.png)

```
[2021-06-23 15:35:35,508] ERROR - APIGatewayManager Error occurred when publish to gateway Production and Sandbox
org.apache.axis2.AxisFault: Error while Deploying API 
	at org.wso2.carbon.apimgt.impl.utils.APIGatewayAdminClient.deployAPI_aroundBody14(APIGatewayAdminClient.java:215) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIGatewayAdminClient.deployAPI(APIGatewayAdminClient.java:210) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	.......
Caused by: org.apache.axis2.AxisFault: Error while publishing API to the Gateway. Error while parsing the URI template
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531) ~[axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:382) ~[axis2_1.6.1.wso2v41.jar:?]
	.......
[2021-06-23 15:35:35,658] ERROR - ApisApiServiceImpl Error while updating API : eb7e96f5-37cf-4885-99a5-a184e8f28778
org.wso2.carbon.apimgt.api.FaultGatewaysException: null
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.updateAPI_aroundBody80(APIProviderImpl.java:1585) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.updateAPI(APIProviderImpl.java:1319) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	.......
```

3. Again click on the Save button.
![image](https://user-images.githubusercontent.com/30709975/123582051-ba295980-d7fa-11eb-9213-602fc16eb1c6.png)

4. Invoke a different valid resource in the API.
`INFO - LogMediator STATUS = Message dispatched to the main sequence. Invalid URL., RESOURCE = /pizzashack/1.0.0/menu, HEALTH CHECK URL = /pizzashack/1.0.0/menu  `
 
5. Remove the wrong resource and save the API.

6. Again try to invoke the API and receive the same issue.

After selecting the Gateway from the Environments tab and redeploying the API, the issue gets resolved.

### Affected Product Version:
APIM 3.2.0

**Comment by tharikaGitHub** [comment]
Issue not reproducible in public branch
