### ISSUE TITLE
JNDI lookup of name TopicConnectionFactory returned a org.wso2.andes.client.AMQConnectionFactory while a interface javax.jms.ConnectionFactory was expected

### ISSUE THREAD

**Issue by TomasTokaMrazek** [wso2/product-apim#11380]
### Description:
When I try to create user, I'll get the following error in title. It appears related to some wrong usage of internal broker.

I haven't touch any of the related configurations in deployment.toml, the one thing I did was change primary key in keystore, add CA to truststore and change hostname in deployment.toml to FQDN.

It's not an internal firewall issue, as I am capable of connecting to the broker via curl.
```
curl localhost:5672
AMQP
```

Here's wso2carbon.log from startup:
```
TID: [-1234] [] [2021-06-30 02:11:34,400]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSConnectionFactory} - JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
TID: [-1234] [] [2021-06-30 02:11:34,403]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSConnectionFactory} - JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
TID: [-1234] [] [2021-06-30 02:11:35,742]  INFO {org.wso2.carbon.inbound.endpoint.protocol.websocket.management.WebsocketEndpointManager} - Netty SSL Listener starting on port 8099
TID: [-1234] [] [2021-06-30 02:11:35,752]  INFO {org.wso2.carbon.inbound.endpoint.protocol.websocket.management.WebsocketEndpointManager} - Netty Listener starting on port 9099
TID: [-1234] [] [2021-06-30 02:11:36,098]  INFO {org.wso2.carbon.andes.internal.QpidServiceComponent} - Activating Andes Message Broker Engine...
TID: [-1234] [] [2021-06-30 02:11:36,831]  INFO {qpid.message.broker.listening} - [Broker] BRK-1002 : Starting : Listening on TCP port 5672
TID: [-1234] [] [2021-06-30 02:11:36,838]  INFO {qpid.message.broker.listening} - [Broker] BRK-1002 : Starting : Listening on TCP/SSL port 8672
TID: [-1234] [] [2021-06-30 02:11:36,857]  INFO {org.wso2.carbon.andes.internal.QpidServiceComponent} - AMQP Host Address : 0.0.0.0 Port : 5672
TID: [-1234] [] [2021-06-30 02:11:36,857]  INFO {org.wso2.carbon.andes.internal.QpidServiceComponent} - Successfully connected to AMQP server on port 5672
TID: [-1234] [] [2021-06-30 02:11:36,858]  WARN {org.wso2.carbon.andes.internal.QpidServiceComponent} - MQTT Transport is disabled as per configuration.
TID: [-1234] [] [2021-06-30 02:11:36,859]  INFO {org.wso2.carbon.andes.internal.QpidServiceComponent} - WSO2 Message Broker is started.
TID: [-1234] [] [2021-06-30 02:11:37,924]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} - Started Binary SSL Transport on port : 9711
TID: [-1234] [] [2021-06-30 02:11:37,926]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} - Started Binary TCP Transport on port : 9611
TID: [-1234] [] [2021-06-30 02:11:38,421]  INFO {org.wso2.carbon.databridge.receiver.thrift.internal.ThriftServerStartupObserver} -  Thrift Data Receiver is disabled.
TID: [-1234] [] [2021-06-30 02:11:38,422]  INFO {org.apache.synapse.transport.passthru.PassThroughHttpListener} - Starting Pass-through HTTP Listener...
TID: [-1234] [] [2021-06-30 02:11:38,438]  INFO {org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager} - Pass-through HTTP Listener started on 0.0.0.0:8280
TID: [-1234] [] [2021-06-30 02:11:38,439]  INFO {org.apache.synapse.transport.passthru.PassThroughHttpMultiSSLListener} - Starting Pass-through HTTPS Listener...
TID: [-1234] [] [2021-06-30 02:11:38,446]  INFO {org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager} - Pass-through HTTPS Listener started on 0.0.0.0:8243
TID: [-1234] [] [2021-06-30 02:11:38,525]  WARN {org.apache.tomcat.util.net.SSLUtilBase} - jsseUtil.trustedCertNotValid
TID: [-1234] [] [2021-06-30 02:11:38,526]  WARN {org.apache.tomcat.util.net.SSLUtilBase} - jsseUtil.trustedCertNotValid
TID: [-1234] [] [2021-06-30 02:11:38,527]  WARN {org.apache.tomcat.util.net.SSLUtilBase} - jsseUtil.trustedCertNotValid
TID: [-1234] [] [2021-06-30 02:11:38,527]  WARN {org.apache.tomcat.util.net.SSLUtilBase} - jsseUtil.trustedCertNotValid
TID: [-1234] [] [2021-06-30 02:11:38,528]  WARN {org.apache.tomcat.util.net.SSLUtilBase} - jsseUtil.trustedCertNotValid
TID: [-1234] [] [2021-06-30 02:11:38,528]  WARN {org.apache.tomcat.util.net.SSLUtilBase} - jsseUtil.trustedCertNotValid
TID: [-1234] [] [2021-06-30 02:11:38,529]  WARN {org.apache.tomcat.util.net.SSLUtilBase} - jsseUtil.trustedCertNotValid
TID: [-1234] [] [2021-06-30 02:11:38,529]  WARN {org.apache.tomcat.util.net.SSLUtilBase} - jsseUtil.trustedCertNotValid
TID: [-1234] [] [2021-06-30 02:11:38,530]  WARN {org.apache.tomcat.util.net.SSLUtilBase} - jsseUtil.trustedCertNotValid
TID: [-1234] [] [2021-06-30 02:11:38,816]  INFO {org.wso2.carbon.ntask.core.service.impl.TaskServiceImpl} - Task service starting in STANDALONE mode...
TID: [-1234] [] [2021-06-30 02:11:38,911]  INFO {org.wso2.carbon.registry.eventing.internal.RegistryEventingServiceComponent} - Successfully Initialized Eventing on Registry
TID: [-1234] [] [2021-06-30 02:11:39,109]  INFO {org.wso2.carbon.core.init.JMXServerManager} - JMX Service URL  : service:jmx:rmi://localhost:11111/jndi/rmi://localhost:9999/jmxrmi
TID: [-1234] [] [2021-06-30 02:11:39,406]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSTransportHandler} - Starting jms topic consumer thread for the keyManager topic...
TID: [-1234] [] [2021-06-30 02:11:39,518]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSTransportHandler} - Starting jms topic consumer thread for the throttleData topic...
TID: [-1234] [] [2021-06-30 02:11:39,519]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSTransportHandler} - Starting jms topic consumer thread for the tokenRevocation topic...
TID: [-1234] [] [2021-06-30 02:11:39,522]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSTransportHandler} - Starting jms topic consumer thread for the cacheInvalidation topic...
TID: [-1] [] [2021-06-30 02:11:39,574]  WARN {org.apache.synapse.transport.http.access.AccessConfiguration} - Error loading properties from file: access-log.properties
TID: [-1] [] [2021-06-30 02:11:39,582]  WARN {org.apache.synapse.commons.util.MiscellaneousUtil} - Error loading properties from a file at from the System defined location: access-log.properties
TID: [-1234] [] [2021-06-30 02:11:39,586]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSTransportHandler} - Starting jms topic consumer thread for the notification topic...
TID: [-1] [] [2021-06-30 02:11:39,606]  WARN {org.apache.synapse.commons.util.MiscellaneousUtil} - Error loading properties from a file at from the System defined location: access-log.properties
TID: [-1234] [] [2021-06-30 02:11:40,143]  INFO {org.apache.synapse.mediators.builtin.LogMediator} - STATUS = Message dispatched to the main sequence. Invalid URL., RESOURCE = /echo, HEALTH CHECK URL = /echo
TID: [-1234] [] [2021-06-30 02:11:40,212]  INFO {org.wso2.carbon.core.internal.StartupFinalizerServiceComponent} - Server           :  WSO2 API Manager-3.2.0
TID: [-1234] [] [2021-06-30 02:11:40,213]  INFO {org.wso2.carbon.core.internal.StartupFinalizerServiceComponent} - WSO2 Carbon started in 141 sec
TID: [-1] [] [2021-06-30 02:11:40,633]  INFO {org.wso2.carbon.databridge.core.DataBridge} - user admin connected
TID: [-1] [] [2021-06-30 02:11:40,736]  INFO {org.wso2.callhome.CallHomeExecutor} - 
............................................................................
The latest update level is 'wso2am-3.2.0.53'. 
This consists of 232 updates
applied on top of 'wso2am-3.2.0.0'[WARNING] 
 The update level
'wso2am-3.2.0.53' consists of 12 critical security updates applied on top of
'wso2am-3.2.0.0'. 
WSO2 strongly recommends to use 'wso2am-3.2.0.53'
distribution in production as soon as possible.
............................................................................
TID: [-1234] [] [2021-06-30 02:11:41,981]  INFO {org.wso2.carbon.ui.internal.CarbonUIServiceComponent} - Mgt Console URL  : https://<redacted>:9443/carbon/
TID: [-1234] [] [2021-06-30 02:11:41,982]  INFO {org.wso2.carbon.ui.internal.CarbonUIServiceComponent} - API Developer Portal Default Context : https://<redacted>:9443/devportal
TID: [-1234] [] [2021-06-30 02:11:41,982]  INFO {org.wso2.carbon.ui.internal.CarbonUIServiceComponent} - API Publisher Default Context : https://<redacted>:9443/publisher
TID: [-1] [] [2021-06-30 02:11:42,786]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSListener} - Connection attempt: 1 for JMS Provider for listener: Siddhi-JMS-Consumer#throttleData was successful!
TID: [-1] [] [2021-06-30 02:11:42,795]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager} - Task manager for Siddhi-JMS-Consumer [re-]initialized
TID: [-1] [] [2021-06-30 02:11:42,805]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSListener} - Connection attempt: 1 for JMS Provider for listener: Siddhi-JMS-Consumer#notification was successful!
TID: [-1] [] [2021-06-30 02:11:42,805]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSListener} - Connection attempt: 1 for JMS Provider for listener: Siddhi-JMS-Consumer#keyManager was successful!
TID: [-1] [] [2021-06-30 02:11:42,808]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager} - Task manager for Siddhi-JMS-Consumer [re-]initialized
TID: [-1] [] [2021-06-30 02:11:42,813]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSListener} - Connection attempt: 1 for JMS Provider for listener: Siddhi-JMS-Consumer#cacheInvalidation was successful!
TID: [-1] [] [2021-06-30 02:11:42,818]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager} - Task manager for Siddhi-JMS-Consumer [re-]initialized
TID: [-1] [] [2021-06-30 02:11:42,823]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager} - Task manager for Siddhi-JMS-Consumer [re-]initialized
TID: [-1] [] [2021-06-30 02:11:42,897]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSListener} - Connection attempt: 1 for JMS Provider for listener: Siddhi-JMS-Consumer#tokenRevocation was successful!
TID: [-1] [] [2021-06-30 02:11:42,901]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager} - Task manager for Siddhi-JMS-Consumer [re-]initialized
TID: [-1234] [internal/data/v1] [2021-06-30 02:11:43,059]  INFO {org.wso2.carbon.identity.oauth.config.OAuthServerConfiguration} - An instance of org.wso2.carbon.identity.oauth2.token.OauthTokenIssuerImpl is created for Identity OAuth token generation.
TID: [-1] [] [2021-06-30 02:11:43,843]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils} - Cannot locate destination : throttleData
TID: [-1] [] [2021-06-30 02:11:43,884]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils} - Cannot locate destination : keyManager
TID: [-1] [] [2021-06-30 02:11:43,915]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils} - Cannot locate destination : notification
TID: [-1] [] [2021-06-30 02:11:43,970]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils} - Cannot locate destination : cacheInvalidation
TID: [-1] [] [2021-06-30 02:11:44,515]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils} - Cannot locate destination : tokenRevocation
TID: [-1] [] [2021-06-30 02:11:45,811]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSListener} - Polling tasks on destination : notification of type topic for listener Siddhi-JMS-Consumer#notification have not yet started after 3 seconds ..
TID: [-1] [] [2021-06-30 02:11:45,840]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSListener} - Polling tasks on destination : throttleData of type topic for listener Siddhi-JMS-Consumer#throttleData have not yet started after 3 seconds ..
TID: [-1] [] [2021-06-30 02:11:45,841]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSListener} - Polling tasks on destination : keyManager of type topic for listener Siddhi-JMS-Consumer#keyManager have not yet started after 3 seconds ..
TID: [-1] [] [2021-06-30 02:11:45,855]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSListener} - Polling tasks on destination : cacheInvalidation of type topic for listener Siddhi-JMS-Consumer#cacheInvalidation have not yet started after 3 seconds ..
TID: [-1] [] [2021-06-30 02:11:45,918]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSListener} - Polling tasks on destination : tokenRevocation of type topic for listener Siddhi-JMS-Consumer#tokenRevocation have not yet started after 3 seconds ..
TID: [-1234] [] [2021-06-30 02:13:36,673]  INFO {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} - Initializing of policy store is started at :  Wed Jun 30 02:13:36 CEST 2021
TID: [-1234] [] [2021-06-30 02:13:36,717]  INFO {org.wso2.carbon.identity.entitlement.policy.store.DefaultPolicyDataStore} - Using Global policy combining algorithm that is defined in configuration file.
TID: [-1234] [] [2021-06-30 02:13:36,718]  INFO {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} - Start retrieving policies from org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule@4cd6ea95 at : Wed Jun 30 02:13:36 CEST 2021
TID: [-1234] [] [2021-06-30 02:13:36,731]  INFO {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} - Finish retrieving policies from org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule@4cd6ea95 at : Wed Jun 30 02:13:36 CEST 2021
TID: [-1234] [] [2021-06-30 02:13:36,732]  INFO {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} - Initializing of policy store is finished at :  Wed Jun 30 02:13:36 CEST 2021
TID: [-1234] [] [2021-06-30 02:13:36,752]  INFO {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} - Initializing of policy store is started at :  Wed Jun 30 02:13:36 CEST 2021
TID: [-1234] [] [2021-06-30 02:13:36,759]  INFO {org.wso2.carbon.identity.entitlement.policy.store.DefaultPolicyDataStore} - Using Global policy combining algorithm that is defined in configuration file.
TID: [-1234] [] [2021-06-30 02:13:36,759]  INFO {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} - Start retrieving policies from org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule@4cd6ea95 at : Wed Jun 30 02:13:36 CEST 2021
TID: [-1234] [] [2021-06-30 02:13:36,772]  INFO {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} - Finish retrieving policies from org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule@4cd6ea95 at : Wed Jun 30 02:13:36 CEST 2021
TID: [-1234] [] [2021-06-30 02:13:36,773]  INFO {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} - Initializing of policy store is finished at :  Wed Jun 30 02:13:36 CEST 2021
TID: [-1234] [] [2021-06-30 02:13:37,017] ERROR {org.apache.axis2.transport.base.BaseUtils} - JNDI lookup of name TopicConnectionFactory returned a org.wso2.andes.client.AMQConnectionFactory while a interface javax.jms.ConnectionFactory was expected
TID: [-1234] [] [2021-06-30 02:13:37,018] ERROR {org.wso2.carbon.event.output.adapter.core.internal.OutputAdapterRuntime} - Event dropped at Output Adapter 'cacheInvalidationJMSPublisher' for tenant id '-1234', JNDI lookup of name TopicConnectionFactory returned a org.wso2.andes.client.AMQConnectionFactory while a interface javax.jms.ConnectionFactory was expected org.apache.axis2.transport.base.BaseTransportException: JNDI lookup of name TopicConnectionFactory returned a org.wso2.andes.client.AMQConnectionFactory while a interface javax.jms.ConnectionFactory was expected
	at org.apache.axis2.transport.base.BaseUtils.handleException(BaseUtils.java:168)
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSUtils.lookup(JMSUtils.java:352)
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory.<init>(JMSConnectionFactory.java:85)
	at org.wso2.carbon.event.output.adapter.jms.JMSEventAdapter.initPublisher(JMSEventAdapter.java:202)
	at org.wso2.carbon.event.output.adapter.jms.JMSEventAdapter.connect(JMSEventAdapter.java:135)
	at org.wso2.carbon.event.output.adapter.core.internal.OutputAdapterRuntime.publish(OutputAdapterRuntime.java:68)
	at org.wso2.carbon.event.output.adapter.core.internal.CarbonOutputEventAdapterService.publish(CarbonOutputEventAdapterService.java:148)
	at org.wso2.carbon.event.publisher.core.internal.EventPublisher.process(EventPublisher.java:428)
	at org.wso2.carbon.event.publisher.core.internal.EventPublisher.sendEvent(EventPublisher.java:230)
	at org.wso2.carbon.event.publisher.core.internal.EventPublisher.onEvent(EventPublisher.java:300)
	at org.wso2.carbon.event.stream.core.internal.EventJunction.sendEvent(EventJunction.java:157)
	at org.wso2.carbon.event.receiver.core.internal.management.InputEventDispatcher.onEvent(InputEventDispatcher.java:27)
	at org.wso2.carbon.event.receiver.core.internal.EventReceiver.sendEvent(EventReceiver.java:294)
	at org.wso2.carbon.event.receiver.core.internal.EventReceiver.processTypedEvent(EventReceiver.java:257)
	at org.wso2.carbon.event.receiver.core.internal.EventReceiver$TypedEventSubscription.onEvent(EventReceiver.java:358)
	at org.wso2.carbon.event.input.adapter.core.internal.InputAdapterRuntime.onEvent(InputAdapterRuntime.java:110)
	at org.wso2.carbon.event.input.adapter.wso2event.internal.ds.WSO2EventAdapterServiceDS$1.receive(WSO2EventAdapterServiceDS.java:100)
	at org.wso2.carbon.databridge.core.internal.queue.QueueWorker.run(QueueWorker.java:81)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

I don't understand, how in one line there's successful connection to throttleData topic
`TID: [-1] [] [2021-06-30 02:11:42,786]  INFO {org.wso2.carbon.apimgt.jms.listener.utils.JMSListener} - Connection attempt: 1 for JMS Provider for listener: Siddhi-JMS-Consumer#throttleData was successful!`

Second line says that topic was not found
`TID: [-1] [] [2021-06-30 02:11:43,843]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils} - Cannot locate destination : throttleData`

Third line says that, the connection wasn't in fact successful
`TID: [-1] [] [2021-06-30 02:11:45,811]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSListener} - Polling tasks on destination : notification of type topic for listener Siddhi-JMS-Consumer#notification have not yet started after 3 seconds ..
`

And finally, during a restart procedure, there's a storm of errors related to JMS.
```
TID: [-1] [] [2021-06-30 02:21:55,105] ERROR {org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager} - Error acquiring a JMS connection to : TopicConnectionFactory using JNDI properties : {java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory, transport.jms.DestinationType=topic, connectionfactory.TopicConnectionFactory=amqp://***:***@clientid/carbon?brokerlist='tcp://<redacted>:5672'} javax.jms.JMSException: Error creating connection: Could not open connection
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:346)
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:53)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils.createConnection(JMSUtils.java:391)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.createConnection(JMSTaskManager.java:939)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.getConnection(JMSTaskManager.java:818)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.receiveMessage(JMSTaskManager.java:599)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:522)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.wso2.andes.AMQConnectionFailureException: Could not open connection
	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:496)
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:328)
	... 10 more
Caused by: org.wso2.andes.transport.TransportException: Could not open connection
	at org.wso2.andes.transport.network.mina.MinaNetworkTransport$IoConnectorCreator.connect(MinaNetworkTransport.java:224)
	at org.wso2.andes.transport.network.mina.MinaNetworkTransport.connect(MinaNetworkTransport.java:82)
	at org.wso2.andes.client.AMQConnectionDelegate_8_0.makeBrokerConnection(AMQConnectionDelegate_8_0.java:137)
	at org.wso2.andes.client.AMQConnection$2.run(AMQConnection.java:641)
	at org.wso2.andes.client.AMQConnection$2.run(AMQConnection.java:638)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.andes.client.AMQConnection.makeBrokerConnection(AMQConnection.java:638)
	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:419)
	... 11 more
```

### Steps to reproduce:
Install WSO2 APIM 3.2.0
Run
Create user in Carbon console

### Affected Product Version:
APIM 3.2.0

### Environment details (with versions):
- OS: Cent OS 7
- Env (Docker/K8s): RPM package

**Comment by TomasTokaMrazek** [comment]
It was related to additional dropins for Azure Service Bus. Looks like APIM 3.2.0 is not compatible with following settings.

https://ei.docs.wso2.com/en/latest/micro-integrator/setup/brokers/configure-with-azureservicebus/
