### ISSUE TITLE
Error When Assigning Application Groups to an Application in Dev-Portal

### ISSUE THREAD

**Issue by rashm1n** [wso2/product-apim#11417]
### Description:
$Subject

### Steps to reproduce:
1. Turn on application sharing in deployment.toml.
2.  Create a new user with self-registration providing a group-name
3. Log in with that user and create a new application providing the group name.

**Comment by rashm1n** [comment]
[2021-07-10 12:22:19,010] ERROR - ApiMgtDAO Error while getting the id  of A from the persistence store.
org.h2.jdbc.JdbcSQLDataException: Parameter "#3" is not set; SQL statement:
 SELECT    APP.APPLICATION_ID  FROM       AM_APPLICATION APP,   AM_SUBSCRIBER SUB  WHERE    LOWER(APP.NAME) = LOWER(?)      AND ORGANIZATION = ?    AND APP.SUBSCRIBER_ID = SUB.SUBSCRIBER_ID AND  ( (APP.APPLICATION_ID IN  (SELECT APPLICATION_ID FROM AM_APPLICATION_GROUP_MAPPING WHERE GROUP_ID IN (?) AND TENANT = ?)) OR (LOWER(SUB.USER_ID) = LOWER(?))OR (APP.APPLICATION_ID IN (SELECT APPLICATION_ID FROM AM_APPLICATION WHERE GROUP_ID = ?))) [90012-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:587) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.message.DbException.get(DbException.java:205) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.message.DbException.get(DbException.java:181) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.expression.Parameter.checkSet(Parameter.java:94) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.command.Prepared.checkParameters(Prepared.java:180) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.command.CommandContainer.query(CommandContainer.java:144) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.command.Command.executeQuery(Command.java:202) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:115) ~[h2_1.4.199.wso2v1.jar:?]
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[jdbc-pool_9.0.35.wso2v1.jar:?]
	at com.sun.proxy.$Proxy49.executeQuery(Unknown Source) ~[?:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.isApplicationExist_aroundBody170(ApiMgtDAO.java:3916) [org.wso2.carbon.apimgt.impl_9.0.245.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.isApplicationExist(ApiMgtDAO.java:3840) [org.wso2.carbon.apimgt.impl_9.0.245.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.isApplicationExist_aroundBody424(APIUtil.java:6754) [org.wso2.carbon.apimgt.impl_9.0.245.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.isApplicationExist(APIUtil.java:6751) [org.wso2.carbon.apimgt.impl_9.0.245.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.addApplication_aroundBody130(APIConsumerImpl.java:3448) [org.wso2.carbon.apimgt.impl_9.0.245.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.addApplication(APIConsumerImpl.java:3371) [org.wso2.carbon.apimgt.impl_9.0.245.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIConsumer.addApplication_aroundBody8(UserAwareAPIConsumer.java:79) [org.wso2.carbon.apimgt.impl_9.0.245.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIConsumer.addApplication(UserAwareAPIConsumer.java:78) [org.wso2.carbon.apimgt.impl_9.0.245.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApplicationsApiServiceImpl.preProcessAndAddApplication(ApplicationsApiServiceImpl.java:349) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApplicationsApiServiceImpl.applicationsPost(ApplicationsApiServiceImpl.java:288) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.ApplicationsApi.applicationsPost(ApplicationsApi.java:490) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]

**Comment by hisanhunais** [comment]
Fixed via https://github.com/wso2/carbon-apimgt/pull/10677/commits/9612445076e8c142975fd084a7c5d0053c0c1202
