### ISSUE TITLE
Issue in API creation with OAuth secured endpoints via Publisher REST API

### ISSUE THREAD

**Issue by chaliya96** [wso2/product-apim#11435]
### Description:
When creating an API with oauth secured endpoints in the publisher REST API (POST resource), the following payload will not create secured endpoint but it will create a prototype endpoint.  
`
{
    "name": "api-new",
    "version": "1",
    "context": "/test99",
    "policies": [
        "Unlimited"
    ],
    "endpointConfig": {
        "endpoint_type": "http",
        "sandbox_endpoints": {
            "url": "http://localhost:3001/test/two"
        },
        "production_endpoints": {
            "url": "http://localhost:3001/test/two"
        },
                "endpoint_security": {
            "sandbox": {
                "password": null,
                "tokenUrl": "http://localhost:9443/token",
                "clientId": "cid123",
                "clientSecret": "csecret",
                "customParameters": "{}",
                "type": "OAUTH",
                "grantType": "CLIENT_CREDENTIALS",
                "enabled": true,
                "username": null
            },
            "production": {
                "password": null,
                "tokenUrl": "http://localhost:9443/token",
                "clientId": "cid123",
                "clientSecret": "csecret",
                "customParameters": "{}",
                "type": "OAUTH",
                "grantType": "CLIENT_CREDENTIALS",
                "enabled": true,
                "username": null
            }
        }
    },
    "gatewayEnvironments": [
        "Production and Sandbox"
    ]
}
`
But with the PUT resource same payload will update the endpoint to the secured endpoint. 

### Steps to reproduce:
Generate valid access token for Publisher REST API - api creation. 
Invoke the API using sample payload

### Affected Product Version:
v3.2.0

**Comment by wasuradananjith** [comment]
An error can be observed as below when performing the above operation.

```
[2021-07-16 10:17:06,258] ERROR - APIMappingUtil Error while decrypting client credentials for API: admin-PizzaShackAPI-1.0.0
org.wso2.carbon.core.util.CryptoException: An error occurred while decrypting data.
	at org.wso2.carbon.core.util.CryptoUtil.decrypt(CryptoUtil.java:265) ~[org.wso2.carbon.core_4.6.0.jar:?]
	at org.wso2.carbon.core.util.CryptoUtil.base64DecodeAndDecrypt(CryptoUtil.java:329) ~[org.wso2.carbon.core_4.6.0.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.utils.mappings.APIMappingUtil.fromAPItoDTO(APIMappingUtil.java:877) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.apisPost(ApisApiServiceImpl.java:333) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.apisPost(ApisApi.java:962) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
```

This is coming because it is trying to decrypt the plain text client secret. And as a result, when we do a GET /apis/{apiId} request for this API endpointConfig returned in the response payload is null. 

Fixing this would solve the problem stated in the issue description as well.
