### ISSUE TITLE
[APIM-3.0.0]-Unable to view SDKs or download specific SDK's from DevPortal

### ISSUE THREAD

**Issue by AshenJayasuriya** [wso2/product-apim#11519]
### Description:
In APIM 3.0.0, when configured more supported languages for SDKs in deployment.toml as mentioned in the official document[1], the SDK page in the devportal gets flickering. Also, it is not able to download any of the SDKs from the page. 
Further, some of the mentioned languages in the document[1] are not available to download and give the below error when tries to download those unsupported languages.

```
ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
org.openapitools.codegen.GeneratorNotFoundException: Can't load config class with name 'scala'
	at org.openapitools.codegen.CodegenConfigLoader.forName(CodegenConfigLoader.java:48)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:528)
	at org.wso2.carbon.apimgt.impl.APIClientGenerationManager.generateClient_aroundBody6(APIClientGenerationManager.java:241)
	at org.wso2.carbon.apimgt.impl.APIClientGenerationManager.generateClient(APIClientGenerationManager.java:229)
	at org.wso2.carbon.apimgt.impl.APIClientGenerationManager.generateSDK_aroundBody0(APIClientGenerationManager.java:180)
	at org.wso2.carbon.apimgt.impl.APIClientGenerationManager.generateSDK(APIClientGenerationManager.java:93)
	at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApisApiServiceImpl.apisApiIdSdksLanguageGet(ApisApiServiceImpl.java:536)
	at org.wso2.carbon.apimgt.rest.api.store.v1.ApisApi.apisApiIdSdksLanguageGet(ApisApi.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:225)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:116)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: scala cannot be found by openapi-generator_4.0.1.wso2v2
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.openapitools.codegen.CodegenConfigLoader.forName(CodegenConfigLoader.java:46)
	... 59 more
```

### Steps to reproduce:

1. In the deployment.toml file, add the following line, and save it.
`[apim.sdk]`
`supported_languages = ["android", "java", "scala", "csharp", "dart", "flash", "groovy", "javascript"]`
2. Re-start the server if it's already running.
3. Create and publish an API.
4. In the devportal, click the published API --> SDKs
5. Add the default.svg file to the **/repository/deployment/server/jaggeryapps/devportal/site/public/images/sdks/** location then page gets stable.
6. Then change the deployment.toml configuration as below to be able to download the SDKs
`[apim.sdk]`
`supported_languages = "android,java,scala,csharp,dart,flash,groovy,javascript"`
7. Restart the server.
8. Try to download any of the below languages.

- SCALA
- NODEJS
- SWIFT
- ASYNCSCALA
- CSHARPDOTNET2

[1] https://apim.docs.wso2.com/en/3.0.0/learn/consume-api/generating-sdks/generate-sdks-in-dev-portal/#configuring-supported-languages-for-sdk-generation

### Affected Product Version:
wso2am-3.0.0 U2 level 36

**Comment by wasuradananjith** [comment]
This is already fixed in the master. Hence, closing this issue.
