### ISSUE TITLE
APIM - 3.2.0 Issue with api/am/store/v1/throttling-policies/subscription Store API.

### ISSUE THREAD

**Issue by Thiyanwso2** [wso2/product-apim#11527]
### Description:
We are observing the below issue while invoking the **api/am/store/v1/throttling-policies/subscription** Store API[1] after deleting a custom throttling policy.

```
ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: null
at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ThrottlingPoliciesApiServiceImpl.getThrottlingPolicyList(ThrottlingPoliciesApiServiceImpl.java:133) ~[classes/:?]
at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ThrottlingPoliciesApiServiceImpl.throttlingPoliciesPolicyLevelGet(ThrottlingPoliciesApiServiceImpl.java:42) ~[classes/:?]
at org.wso2.carbon.apimgt.rest.api.store.v1.ThrottlingPoliciesApi.throttlingPoliciesPolicyLevelGet(ThrottlingPoliciesApi.java:54) ~[classes/:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]

```
### Steps to reproduce:

- Create a custom policy in the Admin portal.
- Execute the particular store  API `api/am/store/v1/throttling-policies/subscription[1]`, this time you can see the proper response.
- Then delete that particular custom throttling policy created earlier.
- Again execute the particular store  API `api/am/store/v1/throttling-policies/subscription[1]`, this time you can see the above error (500 internal server error).

### Affected Product Version:
apim-3.20

**Comment by Thiyanwso2** [comment]
**Fix**

Ideally, if the subscription tier is removed, then the tier permissions related to that subscription tier also should be removed from the table AM_THROTTLE_TIER_PERMISSIONS. It seems the corresponding entries are not getting removed from the table when deleting the subscription tier and returned in [1].

I believe we need to fix the subscription policy deletion flow to remove the corresponding entries in AM_THROTTLE_TIER_PERMISSIONS. A similar issue is fixed in the subscription tier update flow with [2], in master.
+1 to fix it.

[1] https://github.com/wso2-support/carbon-apimgt/blob/support-6.7.206/components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/ThrottlingPoliciesApiServiceImpl.java#L130
[2] https://github.com/wso2/carbon-apimgt/pull/10294/files

**Comment by msm1992** [comment]
This error log is not reproducible in master/4.0.0 as we have added a null check at [1] to fix [2]. However the issue with role permissions not getting deleted is still there in master hence fixed it with PR [3]. 

[1]. https://github.com/wso2/carbon-apimgt/pull/9234
[2]. https://github.com/wso2/product-apim/issues/8921
[3]. https://github.com/wso2/carbon-apimgt/pull/10728
