### ISSUE TITLE
DAS Message Trace : Error occured when output is set to be JSON on the event publisher

### ISSUE THREAD

**Issue by nuwankng** [wso2/product-apim#11555]
**Description**

After Message Tracing and Analytics Event Publishing enabled on the carbon management console and using Event publisher  which the Message Format set to be JSON , carbon log generates an error on the requests made through the APIM.

`[2021-08-18 17:49:15,850] ERROR - EventJunction Error while dispatching events: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 460 path $.event.payloadData.username
  com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 460 path $.event.payloadData.username
  at com.google.gson.internal.Streams.parse(Streams.java:60) ~[com.google.gson_2.8.5.jar:?]
  at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[com.google.gson_2.8.5.jar:?]
  at com.google.gson.JsonParser.parse(JsonParser.java:59) ~[com.google.gson_2.8.5.jar:?]
  at com.google.gson.JsonParser.parse(JsonParser.java:45) ~[com.google.gson_2.8.5.jar:?]
  at org.wso2.carbon.event.publisher.core.internal.type.json.JSONOutputMapper.convertToMappedInputEvent(JSONOutputMapper.java:147) ~[?:?]
  at org.wso2.carbon.event.publisher.core.internal.type.json.JSONOutputMapper.convertToTypedInputEvent(JSONOutputMapper.java:159) ~[?:?]
  at org.wso2.carbon.event.publisher.core.internal.EventPublisher.process(EventPublisher.java:394) ~[?:?]
  at org.wso2.carbon.event.publisher.core.internal.EventPublisher.sendEvent(EventPublisher.java:230) ~[?:?]
  at org.wso2.carbon.event.publisher.core.internal.EventPublisher.onEvent(EventPublisher.java:300) ~[?:?]
  at org.wso2.carbon.event.stream.core.internal.EventJunction.sendEvent(EventJunction.java:157) [org.wso2.carbon.event.stream.core_5.2.26.jar:?]
  at org.wso2.carbon.event.stream.core.internal.EventStreamRuntime.publish(EventStreamRuntime.java:92) [org.wso2.carbon.event.stream.core_5.2.26.jar:?]
  at org.wso2.carbon.event.stream.core.internal.CarbonEventStreamService.publish(CarbonEventStreamService.java:356) [org.wso2.carbon.event.stream.core_5.2.26.jar:?]
  at org.wso2.carbon.analytics.message.tracer.handler.publish.Publisher.publish(Publisher.java:70) [org.wso2.carbon.analytics.message.tracer.handler_1.4.5.jar:?]
  at org.wso2.carbon.analytics.message.tracer.handler.modules.ActivityInHandler.invoke(ActivityInHandler.java:103) [org.wso2.carbon.analytics.message.tracer.handler_1.4.5.jar:?]
  at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340) [axis2_1.6.1.wso2v41.jar:?]
  at org.apache.axis2.engine.Phase.invoke(Phase.java:313) [axis2_1.6.1.wso2v41.jar:?]
  at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261) [axis2_1.6.1.wso2v41.jar:?]
  at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167) [axis2_1.6.1.wso2v41.jar:?]
  at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367) [synapse-nhttp-transport_2.1.7.wso2v183.jar:?]
  at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:188) [synapse-nhttp-transport_2.1.7.wso2v183.jar:?]
  at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41.jar:?]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
  at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
  Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 460 path $.event.payloadData.username
  at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568) ~[com.google.gson_2.8.5.jar:?]
  at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491) ~[com.google.gson_2.8.5.jar:?]
  at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[com.google.gson_2.8.5.jar:?]
  at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:722) ~[com.google.gson_2.8.5.jar:?]
  at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723) ~[com.google.gson_2.8.5.jar:?]
  at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723) ~[com.google.gson_2.8.5.jar:?]
  at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698) ~[com.google.gson_2.8.5.jar:?]
  at com.google.gson.internal.Streams.parse(Streams.java:48) ~[com.google.gson_2.8.5.jar:?]
  ... 23 more`

**Affected Product Version:**
APIM  3.2.0

**Steps to Reproduce the Issue:** 
1. -     Start the APIM 3.2.0
2. -     Enable DAS Message Tracing and Analytics Event publishing from console
3. -     Create new Event publisher and set the output format to JSON
4. -     Create API and observe the log behavior when request is made.

**Comment by wasuradananjith** [comment]
This can be closed since the master fix has been done with [1].

[1] https://github.com/wso2/carbon-analytics/pull/1957
