### ISSUE TITLE
APIM 3.2 - Store RESTful API - API listing call returns "ORA-01795" ERROR when the limit is more than 1000

### ISSUE THREAD

**Issue by niranRameshPeiris** [wso2/product-apim#11597]
### Description:
When a user list down APIs using the below REST call, it returns 500 internal server ERROR.
REQUEST
https://localhost:9443/api/am/store/v1/apis?limit=5000
ERROR
```
{     "code": 500,     "message": "Internal server error",     "description": "Error while retrieving APIs",     "moreInfo": "",     "error": [] }
```
In the wso2carbon log, we can see the below ERROR.
```
TID: [-1234] [api/am/store] [2021-08-27 10:23:29,732] ERROR {org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApisApiServiceImpl} - Error while retrieving APIs org.wso2.carbon.apimgt.api.APIManagementException: Failed to Search APIs
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.searchPaginatedAPIs_aroundBody178(AbstractAPIManager.java:2305)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.searchPaginatedAPIs(AbstractAPIManager.java:2195)
--------
Caused by: org.wso2.carbon.apimgt.api.APIManagementException: Failed to retrieve api scopes 
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.handleException_aroundBody320(ApiMgtDAO.java:7360)
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.handleException(ApiMgtDAO.java:7358)
--------
Caused by: java.sql.SQLSyntaxErrorException: ORA-01795: maximum number of expressions in a list is 1000
```
When we set the limit to 1000 or a number below 1000 we could not see this ERROR. (This ERROR only can be reproduced when there are more than 1000 APIs in the environment)

As per the background analysis, we have done this seems like a limitation in the Oracle. In Oracle number of parameterized values for the IN/NOT IN clause must be 1000 or below. If the number of parameterized values for the IN/NOT IN clause exceeds 1000, the subquery should be divided into sets according to the maximum limit of 1000, joined by the OR/AND operator.

### Affected Product Version:
APIM-3.2.0

**Comment by rashm1n** [comment]
This issue has been fixed by the following PR.
* https://github.com/wso2/carbon-apimgt/pull/10794
