### ISSUE TITLE
Cross Tenant Subscription not working in Store REST APIs

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11608]
### Description:
Cannot create subscriptions with APIs that belong to a different tenant and the service call returning the 404 error response.

### Steps to reproduce:

- Create a tenant domain via the carbon management console. (**abc.com**)
- Go to the publisher portal by using the tenant admin's credentials and publish an API (**NEW_API**)
- When publishing the API, enable the cross tenant subscriptions by selecting **Available to all the tenants** under the **Subscriptions** dropdown.
![Screenshot from 2021-08-31 20-13-59](https://user-images.githubusercontent.com/18566908/131694086-3c3af171-c220-41c8-b7aa-a7b681e7f40a.png)

- After publishing the API, log into the store portal by using the super admin's credentials and create an application. (**ADMIN_APP**)
- Create an Oauth2 application and generate an access token by parsing the super admin's user credentials with the **apim:subscribe** scope. [1]

_Create an OAuth2 application_
```
curl -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d @payload.json https://localhost:9443/client-registration/v0.11/register

{"clientId":"FITZo9Y8gZrN_qzNoEOUwr5du2Ia","clientName":"admin_rest_api_store","callBackURL":"www.google.lk","clientSecret":"HcPbZ4QUYckIP_Pqtc3tu8MHqSQa","isSaasApplication":true,"appOwner":"admin","jsonString":"{\"grant_types\":\"password refresh_token\",\"redirect_uris\":\"www.google.lk\",\"client_name\":\"admin_rest_api_store\"}"}
```

_Generate an access token_
```
curl -k -d "grant_type=password&username=admin&password=admin&scope=apim:subscribe" -H "Authorization: Basic RklUWm85WThnWnJOX3F6Tm9FT1V3cjVkdTJJYTpIY1BiWjRRVVlja0lQX1BxdGMzdHU4TUhxU1Fh" https://localhost:8243/token -k -v

{"access_token":"0a4cab64-6fb1-34bd-bb5b-7cdb52c5499b","refresh_token":"a8c66379-24ce-335d-9046-3cfd64d7fad7","scope":"apim:subscribe","token_type":"Bearer","expires_in":3600}
```

- Invoke the REST API [2] to get the list of applications of the super tenant.
```
curl -k GET  -H "Authorization: Bearer 0a4cab64-6fb1-34bd-bb5b-7cdb52c5499b" -k -v https://localhost:9443/api/am/store/v0.11/applications -k -v

{"count":2,"next":"","previous":"","list":[{"applicationId":"d7d78476-187f-41fe-b88c-62acae8fcc35","name":"ADMIN_APP","subscriber":"admin","throttlingTier":"Unlimited","description":"","status":"APPROVED","groupId":""},{"applicationId":"006098ae-da5e-4b02-8fb6-26e9c442f69e","name":"DefaultApplication","subscriber":"admin","throttlingTier":"Unlimited","description":null,"status":"APPROVED","groupId":""}]}
```

- Invoke the REST API [3] to get all the APIs of the **abc.com** tenant by parsing the **X-WSO2-Tenant** header as below.
```
curl -k GET -H "X-WSO2-Tenant: abc.com" https://localhost:9443/api/am/store/v0.11/apis

{"count":1,"next":"","previous":"","list":[{"id":"04b15ba4-ceb1-4c19-bd14-1d1f69096aa7","name":"NEW_API","description":null,"context":"/t/abc.com/api/1.0.0","version":"1.0.0","provider":"admin@abc.com","status":"PUBLISHED","thumbnailUri":null}],"pagination":{"total":1,"offset":0,"limit":25}}
```

- Invoke the REST API [4] to create a subscription with the **NEW_API** and the **ADMIN_APP**.
_JSON Payload_
```
{
    "tier": "Gold",
    "apiIdentifier": "04b15ba4-ceb1-4c19-bd14-1d1f69096aa7",
    "applicationId": "d7d78476-187f-41fe-b88c-62acae8fcc35"
}
```
_cURL command_
```
curl -k -H "Authorization: Bearer 0a4cab64-6fb1-34bd-bb5b-7cdb52c5499b" -H "Content-Type: application/json" -X POST  -d @payload.json "https://localhost:9443/api/am/store/v0.11/subscriptions"

{"code":404,"message":"Not Found","description":"Requested API with Id '04b15ba4-ceb1-4c19-bd14-1d1f69096aa7' not found","moreInfo":"","error":[]}
```

- Furthermore, able to see the below error stack trace in the carbon logs.
```
[2021-08-31 20:02:50,694] ERROR - UserAwareAPIConsumer Failed to get API. API artifact corresponding to artifactId 04b15ba4-ceb1-4c19-bd14-1d1f69096aa7 does not exist
[2021-08-31 20:02:50,695] ERROR - SubscriptionsApiServiceImpl Requested API with Id '04b15ba4-ceb1-4c19-bd14-1d1f69096aa7' not found
org.wso2.carbon.apimgt.api.APIManagementException: Failed to retrieve the API 04b15ba4-ceb1-4c19-bd14-1d1f69096aa7 to check user admin has access to the API
	at org.wso2.carbon.apimgt.rest.api.store.utils.RestAPIStoreUtils.isUserAccessAllowedForAPI(RestAPIStoreUtils.java:198)
	at org.wso2.carbon.apimgt.rest.api.store.impl.SubscriptionsApiServiceImpl.subscriptionsPost(SubscriptionsApiServiceImpl.java:256)
	at org.wso2.carbon.apimgt.rest.api.store.SubscriptionsApi.subscriptionsPost(SubscriptionsApi.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:191)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:309)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:189)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:303)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:222)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:278)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1201)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1782)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1741)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.apimgt.api.APIMgtResourceNotFoundException: Failed to get API. API artifact corresponding to artifactId 04b15ba4-ceb1-4c19-bd14-1d1f69096aa7 does not exist
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getLightweightAPIByUUID_aroundBody24(AbstractAPIManager.java:541)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getLightweightAPIByUUID(AbstractAPIManager.java:515)
	at org.wso2.carbon.apimgt.rest.api.store.utils.mappings.APIMappingUtil.getAPIIdentifierFromApiIdOrUUID(APIMappingUtil.java:72)
	at org.wso2.carbon.apimgt.rest.api.store.utils.RestAPIStoreUtils.isUserAccessAllowedForAPI(RestAPIStoreUtils.java:187)
	... 52 more
```

[1] https://docs.wso2.com/display/AM210/apidocs/store/#guide
[2] https://docs.wso2.com/display/AM210/apidocs/store/#!/operations#ApplicationCollection#applicationsGet
[3] https://docs.wso2.com/display/AM210/apidocs/store/#!/operations#APICollection#apisGet
[4] https://docs.wso2.com/display/AM210/apidocs/store/#!/operations#SubscriptionIndividual#subscriptionsPost

### Affected Product Version:
2.1.0

**Comment by wasuradananjith** [comment]
This is already fixed in master via https://github.com/wso2/carbon-apimgt/pull/7552. Hence, closing the issue.
