### ISSUE TITLE
Registry Oracle db deadlocks while doing concurrent API updates

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#11613]
### Describe your problem(s)
When doing concurrent API updates for API-M 4.0 with Oracle database, following deadlock occurs.

```
ERROR - JDBCResourceDAO Failed to remove properties from resource version 22064. ORA-00060: deadlock detected while waiting for resource
java.sql.BatchUpdateException: ORA-00060: deadlock detected while waiting for resource
at oracle.jdbc.driver.OraclePreparedStatement.executeLargeBatch(OraclePreparedStatement.java:10032) ~[ojdbc8.jar:12.2.0.1.0] at oracle.jdbc.driver.T4CPreparedStatement.executeLargeBatch(T4CPreparedStatement.java:1364) ~[ojdbc8.jar:12.2.0.1.0] at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:9839) ~[ojdbc8.jar:12.2.0.1.0] at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:234) ~[ojdbc8.jar:12.2.0.1.0] at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source) ~[?:?] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251] at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[jdbc-pool_9.0.35.wso2v1.jar:?] at com.sun.proxy.$Proxy49.executeBatch(Unknown Source) ~[?:?] at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.removeProperties(JDBCResourceDAO.java:1802) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.Repository.removeResource(Repository.java:624) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.Repository.prepareUpdate(Repository.java:362) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.Repository.put(Repository.java:287) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:717) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:73) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:816) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:813) [org.wso2.carbon.registry.core_4.6.2.jar:?] at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_251] at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:813) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:292) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2505) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.put(UserDefinedHandlerManager.java:204) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:950) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:705) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.associateAspect(EmbeddedRegistry.java:2490) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.associateAspect(CacheBackedRegistry.java:499) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry.associateAspectInternal(UserRegistry.java:1913) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry.access$3800(UserRegistry.java:73) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry$39.run(UserRegistry.java:1885) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry$39.run(UserRegistry.java:1882) [org.wso2.carbon.registry.core_4.6.2.jar:?] at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_251] at org.wso2.carbon.registry.core.session.UserRegistry.associateAspect(UserRegistry.java:1882) [org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.attachLifecycle(GovernanceArtifactImpl.java:383) [org.wso2.carbon.governance.api_4.8.21.jar:?] at org.wso2.carbon.apimgt.persistence.RegistryPersistenceImpl.addAPI(RegistryPersistenceImpl.java:191) [org.wso2.carbon.apimgt.persistence_9.0.174.12.jar:?] at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPI_aroundBody44(APIProviderImpl.java:928) [org.wso2.carbon.apimgt.impl_9.0.174.14.jar:?] at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPI(APIProviderImpl.java:885) [org.wso2.carbon.apimgt.impl_9.0.174.14.jar:?] at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addAPI_aroundBody0(UserAwareAPIProvider.java:80) [org.wso2.carbon.apimgt.impl_9.0.174.14.jar:?] at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addAPI(UserAwareAPIProvider.java:79) [org.wso2.carbon.apimgt.impl_9.0.174.14.jar:?] at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.PublisherCommonUtils.addAPIWithGeneratedSwaggerDefinition(PublisherCommonUtils.java:757) [org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.174.4.jar:?] at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.createAPI(ApisApiServiceImpl.java:304) [classes/:?] at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.createAPI(ApisApi.java:265) [classes/:?] at sun.reflect.GeneratedMethodAccessor804.invoke(Unknown Source) ~[?:?] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251] at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.3.7.jar:3.3.7] at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.3.7.jar:3.3.7] at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) [cxf-rt-frontend-jaxrs-3.3.7.jar:3.3.7] at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) [cxf-rt-frontend-jaxrs-3.3.7.jar:3.3.7] at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.3.7.jar:3.3.7] at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.3.7.jar:3.3.7] at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.3.7.jar:3.3.7] at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.3.7.jar:3.3.7] at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.3.7.jar:3.3.7] at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.3.7.jar:3.3.7] at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.3.7.jar:3.3.7] at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.3.7.jar:3.3.7] at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) [cxf-rt-transports-http-3.3.7.jar:3.3.7] at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296) [cxf-rt-transports-http-3.3.7.jar:3.3.7] at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:215) [cxf-rt-transports-http-3.3.7.jar:3.3.7] at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-servlet-api_9.0.34.wso2v1.jar:?] at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271) [cxf-rt-transports-http-3.3.7.jar:3.3.7] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.34.wso2v1.jar:?] at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107) [org.wso2.carbon.identity.context.rewrite.valve_1.4.25.jar:?] at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.25.jar:?] at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:102) [org.wso2.carbon.identity.auth.valve_1.4.25.jar:?] at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:101) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?] at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?] at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?] at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?] at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?] at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?] at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.34.wso2v1.jar:?] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251] at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.34.wso2v1.jar:?] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251][2021-08-18 16:30:56,938] ERROR - GovernanceArtifactImpl Error in associating lifecycle for the artifact. id: 75586f7e-edc7-45f9-b0ac-868544a69766, path: /apimgt/applicationdata/provider/instantpayment_technical-AT-db.com/InstantPayment-PE-NFT/v1/api.org.wso2.carbon.registry.core.exceptions.RegistryException: Unable to put resource Failed to remove properties from resource version 22064. ORA-00060: deadlock detected while waiting for resource
at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:299) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2505) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.put(UserDefinedHandlerManager.java:204) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:950) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:705) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.associateAspect(EmbeddedRegistry.java:2490) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.associateAspect(CacheBackedRegistry.java:499) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry.associateAspectInternal(UserRegistry.java:1913) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry.access$3800(UserRegistry.java:73) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry$39.run(UserRegistry.java:1885) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry$39.run(UserRegistry.java:1882) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_251] at org.wso2.carbon.registry.core.session.UserRegistry.associateAspect(UserRegistry.java:1882) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.attachLifecycle(GovernanceArtifactImpl.java:383) [org.wso2.carbon.governance.api_4.8.21.jar:?] at org.wso2.carbon.apimgt.persistence.RegistryPersistenceImpl.addAPI(RegistryPersistenceImpl.java:191) [org.wso2.carbon.apimgt.persistence_9.0.174.12.jar:?] at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPI_aroundBody44(APIProviderImpl.java:928) [org.wso2.carbon.apimgt.impl_9.0.174.14.jar:?] at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPI(APIProviderImpl.java:885) [org.wso2.carbon.apimgt.impl_9.0.174.14.jar:?] at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addAPI_aroundBody0(UserAwareAPIProvider.java:80) [org.wso2.carbon.apimgt.impl_9.0.174.14.jar:?] at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addAPI(UserAwareAPIProvider.java:79) [org.wso2.carbon.apimgt.impl_9.0.174.14.jar:?] at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.PublisherCommonUtils.addAPIWithGeneratedSwaggerDefinition(PublisherCommonUtils.java:757) [org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.174.4.jar:?] at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.createAPI(ApisApiServiceImpl.java:304) [classes/:?] at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.createAPI(ApisApi.java:265) [classes/:?] at sun.reflect.GeneratedMethodAccessor804.invoke(Unknown Source) ~[?:?] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251] at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.3.7.jar:3.3.7] at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.3.7.jar:3.3.7] at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) [cxf-rt-frontend-jaxrs-3.3.7.jar:3.3.7] at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) [cxf-rt-frontend-jaxrs-3.3.7.jar:3.3.7] at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.3.7.jar:3.3.7] at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.3.7.jar:3.3.7] at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.3.7.jar:3.3.7] at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.3.7.jar:3.3.7] at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.3.7.jar:3.3.7] at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.3.7.jar:3.3.7] at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.3.7.jar:3.3.7] at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.3.7.jar:3.3.7] at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) [cxf-rt-transports-http-3.3.7.jar:3.3.7] at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296) [cxf-rt-transports-http-3.3.7.jar:3.3.7] at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:215) [cxf-rt-transports-http-3.3.7.jar:3.3.7] at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-servlet-api_9.0.34.wso2v1.jar:?] at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271) [cxf-rt-transports-http-3.3.7.jar:3.3.7] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.34.wso2v1.jar:?] at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107) [org.wso2.carbon.identity.context.rewrite.valve_1.4.25.jar:?] at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.25.jar:?] at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:102) [org.wso2.carbon.identity.auth.valve_1.4.25.jar:?] at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:101) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?] at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?] at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?] at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?] at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?] at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?] at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat_9.0.34.wso2v1.jar:?] at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.34.wso2v1.jar:?] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251] at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.34.wso2v1.jar:?] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]Caused by: org.wso2.carbon.registry.core.exceptions.RegistryException: Failed to remove properties from resource version 22064. ORA-00060: deadlock detected while waiting for resource
at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.removeProperties(JDBCResourceDAO.java:1815) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.Repository.removeResource(Repository.java:624) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.Repository.prepareUpdate(Repository.java:362) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.Repository.put(Repository.java:287) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:717) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:73) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:816) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_251] at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:292) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] ... 71 moreCaused by: java.sql.BatchUpdateException: ORA-00060: deadlock detected while waiting for resource
at oracle.jdbc.driver.OraclePreparedStatement.executeLargeBatch(OraclePreparedStatement.java:10032) ~[ojdbc8.jar:12.2.0.1.0] at oracle.jdbc.driver.T4CPreparedStatement.executeLargeBatch(T4CPreparedStatement.java:1364) ~[ojdbc8.jar:12.2.0.1.0] at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:9839) ~[ojdbc8.jar:12.2.0.1.0] at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:234) ~[ojdbc8.jar:12.2.0.1.0] at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source) ~[?:?] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251] at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[jdbc-pool_9.0.35.wso2v1.jar:?] at com.sun.proxy.$Proxy49.executeBatch(Unknown Source) ~[?:?] at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.removeProperties(JDBCResourceDAO.java:1802) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.Repository.removeResource(Repository.java:624) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.Repository.prepareUpdate(Repository.java:362) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.Repository.put(Repository.java:287) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:717) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:73) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:816) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_251] at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:292) ~[org.wso2.carbon.registry.core_4.6.2.jar:?] ... 71 more[2021-08-18 16:30:56,976] ERROR - GlobalThrowableMapper Error while persisting API 

```

**Comment by dushaniw** [comment]
This can be fixed by adding following index
```
CREATE INDEX REG_RESC_PROP_BY_REG_PROP_ID ON REG_RESOURCE_PROPERTY(REG_TENANT_ID,REG_PROPERTY_ID)
```
Likewise we need check and add indexes for all other places where such deadlock could occur due to update of parent table.

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
