### ISSUE TITLE
Customizing the JWT generation - (CustomGatewayJWTGenerator) throws Null Pointer Exception on API invocation in WSO2 APIM 4.0.0

### ISSUE THREAD

**Issue by IsuruMaduranga** [wso2/product-apim#11637]
### Description:

I followed the [documentation](https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway/#jwt-self-contained-access-tokens) to set up CustomGatewayJWTGenerator. But then the API manager throws Null Pointer Exception on API invocation.

```
 java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.gateway.handlers.security.jwt.JWTValidator.<init>(JWTValidator.java:108) ~[org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.oauth.OAuthAuthenticator.authenticate_aroundBody4(OAuthAuthenticator.java:130) ~[org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.oauth.OAuthAuthenticator.authenticate(OAuthAuthenticator.java:115) ~[org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate_aroundBody42(APIAuthenticationHandler.java:428) ~[org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate(APIAuthenticationHandler.java:422) ~[org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest_aroundBody36(APIAuthenticationHandler.java:353) ~[org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest(APIAuthenticationHandler.java:317) ~[org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.apache.synapse.api.API.process(API.java:389) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:107) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:127) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:59) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:84) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:70) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v63.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:375) [synapse-nhttp-transport_2.1.7.wso2v227.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:189) [synapse-nhttp-transport_2.1.7.wso2v227.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v63.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

### Steps to reproduce:
Follow the exact steps provided in the  [documentation](https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway/#jwt-self-contained-access-tokens).

### Affected Product Version:

APIM 4.0.0

### Environment details (with versions):
- OS: CentOS 7, JDK 11, 
- Client: Local
- Env (Docker/K8s): Local

---
#### Related Issues:

Customizing the JWT generation - (JWT(Self Contained) Access Tokens) doesn't work as expected and API invocation fails in WSO2 APIM 3.1.0 #8601

[Customizing JWT generation not working in WSO2 APIM 3.1.0](https://stackoverflow.com/questions/62595748/customizing-jwt-generation-not-working-in-wso2-apim-3-1-0)

[Custom JWT Generation Gives Exception in WSO2 3.2.0](https://stackoverflow.com/questions/68107168/custom-jwt-generation-gives-exception-in-wso2-3-2-0)

**Comment by tharindu1st** [comment]
Fixed in https://github.com/wso2/samples-apim/pull/44
