### ISSUE TITLE
Getting exception when enabling analytics in WSO2 APIM 4.0.0

### ISSUE THREAD

**Issue by alijaved94** [wso2/product-apim#11723]
I followed the documentation to enable analytics in APIM 4.0.0. After setting up and invoking api getting this error.

> `ERROR - ParallelQueueWorker Builder instance is not duly filled. Event building failed
org.wso2.am.analytics.publisher.exception.MetricReportingException: keyType is missing in metric data. This metric event will not be processed further.
	at org.wso2.am.analytics.publisher.reporter.cloud.DefaultResponseMetricEventBuilder.validate(DefaultResponseMetricEventBuilder.java:61) ~[org.wso2.am.analytics.publisher.client_1.0.1.jar:?]
	at org.wso2.am.analytics.publisher.reporter.AbstractMetricEventBuilder.build(AbstractMetricEventBuilder.java:32) ~[org.wso2.am.analytics.publisher.client_1.0.1.jar:?]
	at org.wso2.am.analytics.publisher.reporter.cloud.ParallelQueueWorker.run(ParallelQueueWorker.java:56) [org.wso2.am.analytics.publisher.client_1.0.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_292]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]`

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
