### ISSUE TITLE
org.wso2.carbon.consent.mgt.ui.2.8.2.2 bundle is not getting activated in the latest U2 updated product

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim#11742]
### Description:
Latest APIM 3.2.0 binary we get from the U2 channel has an issue where org.wso2.carbon.consent.mgt.ui bundle is not getting activated. 

<img width="489" alt="Screenshot 2021-09-23 at 8 00 10 PM" src="https://user-images.githubusercontent.com/47380453/134549612-ac8b4edd-9ebc-41f9-b397-52c13b3fa83e.png">
<img width="678" alt="Screenshot 2021-09-23 at 8 00 31 PM" src="https://user-images.githubusercontent.com/47380453/134549598-0f08fee7-f8b5-4b69-94b2-7def8829e9f1.png">

Because of this, we can't configure the Self-Sign-Up purposes in the resident IDP configuration as it's leading to a blank page and the following exception logged in the wso2carbon.log.

```
[2021-09-22 08:54:26,355]  INFO - CarbonAuthenticationUtil 'admin@carbon.super [-1234]' logged in at [2021-09-22 08:54:26,354+0530]
[2021-09-22 08:54:36,865] ERROR - [bridgeservlet] Servlet.service() for servlet [bridgeservlet] threw exception
javax.servlet.ServletException: File [&#47;consent&#47;list-purposes.jsp] not found
	at org.apache.jasper.servlet.JspServlet.handleMissingResource(JspServlet.java:407) ~[tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:374) ~[tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) ~[tomcat_9.0.31.wso2v1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-servlet-api_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:207) ~[org.wso2.carbon.ui_4.6.0.50.jar:?]
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80) ~[org.wso2.carbon.ui_4.6.0.50.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-servlet-api_9.0.31.wso2v1.jar:?]
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37) ~[org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) ~[?:?]
```

### Steps to reproduce:
Get the latest 3.2.0 updated product from u2 channel.
Configure purposes in the Self-Sign-Up process

**Comment by 1akshitha** [comment]
closing the issue as the fix is merged
