### ISSUE TITLE
[PKCE] Generating with all ticks enable throws an error.

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#11870]
### Description:
Create application and select all check boxes and generate a token. Following error is generated. If selecting all is not allowed, need to add validation

<img width="1352" alt="Screenshot 2021-10-15 at 2 52 44 PM" src="https://user-images.githubusercontent.com/4861150/137464907-8d79d7d5-f478-43f2-91cc-eb7e573cfc3e.png">

    Caused by: org.wso2.carbon.apimgt.api.APIManagementException: Error occurred while calling token endpoint - The cli
    ent MUST NOT use more than one authentication method in each
            at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.getNewApplicationAccessToken_aroundBody12(AMDefaultK
    eyManagerImpl.java:473)
            at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.getNewApplicationAccessToken(AMDefaultKeyManagerImpl
    .java:442)
            at org.wso2.carbon.apimgt.impl.workflow.AbstractApplicationRegistrationWorkflowExecutor.dogenerateKeysForAp
    plication_aroundBody8(AbstractApplicationRegistrationWorkflowExecutor.java:171)
            ... 63 more
    Caused by: org.wso2.carbon.apimgt.impl.kmclient.KeyManagerClientException: Received status code: 400 Reason: The cl
    ient MUST NOT use more than one authentication method in each
            at org.wso2.carbon.apimgt.impl.kmclient.KMClientErrorDecoder.decode_aroundBody0(KMClientErrorDecoder.java:4
    2)
            at org.wso2.carbon.apimgt.impl.kmclient.KMClientErrorDecoder.decode(KMClientErrorDecoder.java:35)
            at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96)
            at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
            at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
            at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
            at com.sun.proxy.$Proxy439.generate(Unknown Source)
            at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.getNewApplicationAccessToken_aroundBody12(AMDefaultK
    eyManagerImpl.java:469)
            ... 65 more

**Comment by tharikaGitHub** [comment]
This is not reproduced in the latest master branch. Hence closing.
