### ISSUE TITLE
High CPU issue with large malformed XML payloads

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-apim#11954]
### Description:
High CPU issue occurs when trying to send a large malformed payload via the APIM. The payload is geting build from a custom handler. using RelayUtils.buildMessage()

```
ERROR - Axis2Sender Unexpected error during sending message out
org.apache.axis2.AxisFault: Unexpected character '&' (code 38) excepted space, or '>' or "/>"
 at [row,col {unknown-source}]: [46,16]
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430) ~[axis2_1.6.1.wso2v38_2.jar:?]
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:82) ~[axis2_1.6.1.wso2v38_2.jar:?]
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.sendRequestContent(PassThroughHttpSender.java:432) ~[synapse-nhttp-transport_2.1.7.wso2v131_11.jar:?]
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:277) ~[synapse-nhttp-transport_2.1.7.wso2v131_11.jar:?]
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442) ~[axis2_1.6.1.wso2v38_2.jar:?]
	at org.apache.synapse.core.axis2.DynamicAxisOperation$DynamicOperationClient.send(DynamicAxisOperation.java:185) ~[synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.core.axis2.DynamicAxisOperation$DynamicOperationClient.executeImpl(DynamicAxisOperation.java:167) ~[synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149) ~[axis2_1.6.1.wso2v38_2.jar:?]
	at org.apache.synapse.core.axis2.Axis2FlexibleMEPClient.send(Axis2FlexibleMEPClient.java:634) ~[synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.core.axis2.Axis2Sender.sendOn(Axis2Sender.java:85) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:569) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.endpoints.AbstractEndpoint.send(AbstractEndpoint.java:408) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.endpoints.HTTPEndpoint.send(HTTPEndpoint.java:100) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.endpoints.IndirectEndpoint.send(IndirectEndpoint.java:56) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:123) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.mediators.filters.FilterMediator.mediate(FilterMediator.java:169) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.rest.Resource.process(Resource.java:331) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.rest.API.process(API.java:440) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:325) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98) [synapse-core_2.1.7.wso2v131_11.jar:2.1.7-wso2v131.11]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) [axis2_1.6.1.wso2v38_2.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:444) [synapse-nhttp-transport_2.1.7.wso2v131_11.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181) [synapse-nhttp-transport_2.1.7.wso2v131_11.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v38_2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '&' (code 38) excepted space, or '>' or "/>"
 at [row,col {unknown-source}]: [46,16]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedChar(StreamScanner.java:639) ~[axiom_1.2.11.wso2v16_5.jar:?]
	at com.ctc.wstx.sr.BasicStreamReader.handleNsAttrs(BasicStreamReader.java:2994) ~[axiom_1.2.11.wso2v16_5.jar:?]
	at com.ctc.wstx.sr.BasicStreamReader.handleStartElem(BasicStreamReader.java:2961) ~[axiom_1.2.11.wso2v16_5.jar:?]
	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2837) ~[axiom_1.2.11.wso2v16_5.jar:?]
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1072) ~[axiom_1.2.11.wso2v16_5.jar:?]
	at org.apache.axiom.util.stax.wrapper.XMLStreamReaderWrapper.next(XMLStreamReaderWrapper.java:225) ~[axiom_1.2.11.wso2v16_5.jar:?]
	at org.apache.axiom.util.stax.dialect.DisallowDoctypeDeclStreamReaderWrapper.next(DisallowDoctypeDeclStreamReaderWrapper.java:34) ~[axiom_1.2.11.wso2v16_5.jar:?]
	at org.apache.axiom.om.impl.SwitchingWrapper.next(SwitchingWrapper.java:1131) ~[axiom_1.2.11.wso2v16_5.jar:?]
	at javax.xml.stream.util.StreamReaderDelegate.next(StreamReaderDelegate.java:84) ~[?:?]
	at org.apache.axiom.om.impl.serialize.StreamingOMSerializer.serializeNode(StreamingOMSerializer.java:146) ~[axiom_1.2.11.wso2v16_5.jar:?]
	at org.apache.axiom.om.impl.serialize.StreamingOMSerializer.serialize(StreamingOMSerializer.java:107) ~[axiom_1.2.11.wso2v16_5.jar:?]
	at org.apache.axiom.om.impl.serialize.StreamingOMSerializer.serialize(StreamingOMSerializer.java:76) ~[axiom_1.2.11.wso2v16_5.jar:?]
	at org.apache.axiom.om.impl.util.OMSerializerUtil.serializeByPullStream(OMSerializerUtil.java:548) ~[axiom_1.2.11.wso2v16_5.jar:?]
	at org.apache.axiom.soap.impl.llom.SOAPEnvelopeImpl.internalSerialize(SOAPEnvelopeImpl.java:249) ~[axiom_1.2.11.wso2v16_5.jar:?]
	at org.apache.axiom.om.impl.llom.OMSerializableImpl.serializeAndConsume(OMSerializableImpl.java:193) ~[axiom_1.2.11.wso2v16_5.jar:?]
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:78) ~[axis2_1.6.1.wso2v38_2.jar:?]
	... 33 more
```

### Steps to reproduce:
Add the following custom handler
[ExtendedOauthHandler.txt](https://github.com/wso2/product-apim/files/7480867/ExtendedOauthHandler.txt)
Create an API by following https://apim.docs.wso2.com/en/3.0.0/learn/design-api/create-api/expose-a-soap-service-as-a-rest-api/
Invoke the API with large malformed XML payload.

### Affected Product Version:
3.2.0

**Comment by prasa7** [comment]
public fixes

https://github.com/wso2/carbon-apimgt/pull/11663
https://github.com/wso2/wso2-synapse/pull/1873
