### ISSUE TITLE
HTTP-Listener I/O dispatcher Listener getting shutdown when the remote address become null

### ISSUE THREAD

**Issue by AshenShalitha** [wso2/product-apim#11951]
### Description:
When the remote address of the client is getting null , the following line [1] of the getClientConnectionInfo method throws an NPE.

`return session.getRemoteAddress().toString();`

This method is used inside the closed method [2] when printing connection closed warnings. Following example is the connection closed warning which corresponding to the REQUEST_DONE state.

`log.warn("STATE_DESCRIPTION = Connection closed after server accepting the request headers and the "                    + "request body, INTERNAL_STATE = " + state + ", DIRECTION = " + logDetails.get("direction") + ", "                    + "CAUSE_OF_ERROR = Connection between EI and the Client has been closed, HTTP_URL = " + logDetails                    .get("url") + ", " + "HTTP_METHOD = " + logDetails.get("method") + ", CLIENT_ADDRESS = "                    + getClientConnectionInfo(conn) + ", CONNECTION " + conn);`

This NPE is finally leads to the following exception which result in the HTTP-Listener I/O dispatcher Listener getting shutdown [3].

`[2021-10-05 12:38:27,428] FATAL - PassThroughListeningIOReactorManager Exception encountered in the HTTP-Listener I/O dispatcher Listener. No more connections will be accepted by this transport[2021-10-05 12:38:27,428] FATAL - PassThroughListeningIOReactorManager Exception encountered in the HTTP-Listener I/O dispatcher Listener. No more connections will be accepted by this transportorg.apache.http.nio.reactor.IOReactorException: I/O dispatch worker terminated abnormally at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:357) ~[httpcore-nio_4.3.3.wso2v4.jar:?] at org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager$1.run(PassThroughListeningIOReactorManager.java:560) [synapse-nhttp-transport_2.1.7.wso2v183_10.jar:?] at java.lang.Thread.run(Thread.java:834) [?:?]Caused by: java.lang.NullPointerException at org.apache.synapse.transport.passthru.SourceHandler.getClientConnectionInfo(SourceHandler.java:862) ~[synapse-nhttp-transport_2.1.7.wso2v183_10.jar:?] at org.apache.synapse.transport.passthru.SourceHandler.closed(SourceHandler.java:568) ~[synapse-nhttp-transport_2.1.7.wso2v183_10.jar:?] at org.apache.synapse.transport.passthru.ServerIODispatch.onClosed(ServerIODispatch.java:72) ~[synapse-nhttp-transport_2.1.7.wso2v183_10.jar:?] at org.apache.synapse.transport.passthru.ServerIODispatch.onClosed(ServerIODispatch.java:39) ~[synapse-nhttp-transport_2.1.7.wso2v183_10.jar:?] at org.apache.http.impl.nio.reactor.AbstractIODispatch.disconnected(AbstractIODispatch.java:100) ~[httpcore-nio_4.3.3.wso2v4.jar:?] at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionClosed(BaseIOReactor.java:271) ~[httpcore-nio_4.3.3.wso2v4.jar:?] at org.apache.http.impl.nio.reactor.AbstractIOReactor.processClosedSessions(AbstractIOReactor.java:439) ~[httpcore-nio_4.3.3.wso2v4.jar:?] at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:284) ~[httpcore-nio_4.3.3.wso2v4.jar:?] at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105) ~[httpcore-nio_4.3.3.wso2v4.jar:?] at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586) ~[httpcore-nio_4.3.3.wso2v4.jar:?] ... 1 more[2021-10-05 12:38:27,651]  INFO - PassThroughListeningIOReactorManager HTTP-Listener I/O dispatcher Listener shutdown.
`

Once the above NPE handled, the following NPE will also occur.
`[2021-11-09 14:52:46,307] FATAL - PassThroughListeningIOReactorManager Exception encountered in the HTTP-Listener I/O dispatcher Listener. No more connections will be accepted by this transport
org.apache.http.nio.reactor.IOReactorException: I/O dispatch worker terminated abnormally
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:357) ~[httpcore-nio_4.3.3.wso2v4.jar:?]
	at org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager$1.run(PassThroughListeningIOReactorManager.java:560) [synapse-nhttp-transport_2.1.7.wso2v183_10.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at org.apache.synapse.transport.http.conn.LoggingNHttpServiceHandler.exception(LoggingNHttpServiceHandler.java:73) ~[synapse-nhttp-transport_2.1.7.wso2v183_10.jar:?]
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:298) ~[httpcore-nio_4.3.3.wso2v4.jar:?]
	at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection.consumeInput(LoggingNHttpServerConnection.java:114) ~[synapse-nhttp-transport_2.1.7.wso2v183_10.jar:?]
	at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:82) ~[synapse-nhttp-transport_2.1.7.wso2v183_10.jar:?]
	at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:39) ~[synapse-nhttp-transport_2.1.7.wso2v183_10.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:113) ~[httpcore-nio_4.3.3.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159) ~[httpcore-nio_4.3.3.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338) ~[httpcore-nio_4.3.3.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316) ~[httpcore-nio_4.3.3.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277) ~[httpcore-nio_4.3.3.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105) ~[httpcore-nio_4.3.3.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586) ~[httpcore-nio_4.3.3.wso2v4.jar:?]
	... 1 more`

This exception is coming from  [4] since the ex.getMessage() is null. 

### Steps to reproduce:

- Invoke an API and terminate the connection from the client side before receiving the response.
- If the remote address becomes null once the keep alive connection got terminated, the above mentioned exception will be printed in logs. 
- To replicate the remote address getting null behavior, we can set it manually to null during debugging.

### Affected Product Version:
WSO2 API-Manager 3.2.0 update level 91

[1] https://github.com/wso2-support/wso2-synapse/blob/16c19d3e5f035b163dca377e40d2a6ec00f965fe/modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java#L862
[2] https://github.com/wso2-support/wso2-synapse/blob/16c19d3e5f035b163dca377e40d2a6ec00f965fe/modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java#L528
[3] https://github.com/wso2-support/wso2-synapse/blob/16c19d3e5f035b163dca377e40d2a6ec00f965fe/modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/core/PassThroughListeningIOReactorManager.java#L562
[4] https://github.com/wso2-support/wso2-synapse/blob/c1686530bbda8b62aaa00b55df7fd4458b2ec8a0/modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/LoggingNHttpServiceHandler.java#L73

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
