### ISSUE TITLE
NullPointerException when using Endpoint to create an API

### ISSUE THREAD

**Issue by PIPOGit** [wso2/product-apim#11989]
### Description:
Hi.

I'm trying to create an API in WSO2 API Manager 3.2.0, using the REST API: (POST) "http://[SERVER]/api/am/publisher/v1/apis"
As defined in: https://apim.docs.wso2.com/en/3.2.0/develop/product-apis/publisher-apis/publisher-v1/publisher-v1/#tag/APIs/paths/~1apis/post

But, sending a sample JSON, throws a NPE error.

Thanks in advance.

### Steps to reproduce:
Composing the request:

HEADERs:
```
{
    "Authorization":"Bearer c5e43956-2288-3a12-98d3-52775613ce97",
    "Content-Type":"application/json",
    "Accept":"application/json"
}
```

BODY:
```json
{
    "name":  "utilidadesEntidadPruebas",
    "description":  "Api de Utilidades para las pruebas del orquestador de las nuevas versiones del APIM",
    "context":  "/entidades/9997/utilidades",
    "version":  "1.1.5",
    "lifeCycleStatus":  "CREATED",
    "responseCachingEnabled":  false,
    "cacheTimeout":  300,
    "destinationStatsEnabled":  "Disabled",
    "hasThumbnail":  false,
    "isDefaultVersion":  false,
    "enableSchemaValidation":  false,
    "enableStore":  true,
    "type":  "HTTP",
    "transport":  [
                      "http",
                      "https"
                  ],
    "policies":  [
                     "Unlimited"
                 ],
    "visibility":  "PUBLIC",
    "gatewayEnvironments":  [
                                "Production and Sandbox"
                            ],
    "accessControl":  "NONE",
    "corsConfiguration":  {
                              "corsConfigurationEnabled":  false,
                              "accessControlAllowOrigins":  [
                                                                "*"
                                                            ],
                              "accessControlAllowCredentials":  false,
                              "accessControlAllowHeaders":  [
                                                                "authorization",
                                                                "Access-Control-Allow-Origin",
                                                                "Content-Type",
                                                                "SOAPAction",
                                                                "apikey",
                                                                "testKey"
                                                            ],
                              "accessControlAllowMethods":  [
                                                                "GET",
                                                                "PUT",
                                                                "POST",
                                                                "DELETE",
                                                                "PATCH",
                                                                "OPTIONS"
                                                            ]
                          },
    "createdTime":  "2021-11-11T05:38:39.606Z",
    "lastUpdatedTime":  "2021-11-11T05:38:39.606Z",
    "endpointConfig":  {
                           "endpoint_type":  "default",
                           "sandbox_endpoints":  {
                                                     "url":  "https://localhost:9443/am/sample/pizzashack/v1/api/"
                                                 },
                           "production_endpoints":  {
                                                        "url":  "https://localhost:9443/am/sample/pizzashack/v1/api/"
                                                    }
                       },
    "endpointImplementationType":  "ENDPOINT",
    "operations":  [
                       {
                           "target":  "/order/{orderId}",
                           "verb":  "POST",
                           "authType":  "Application \u0026 Application User",
                           "throttlingPolicy":  "Unlimited"
                       },
                       {
                           "target":  "/menu",
                           "verb":  "GET",
                           "authType":  "Application \u0026 Application User",
                           "throttlingPolicy":  "Unlimited"
                       }
                   ]
}
```

REQUEST(PowerShell):
```shell
IRM -Method POST -Header [Header] -Body [Body] -Uri https://localhost:9443/api/am/publisher/v1/apis
```

WSO2Carbon.log:
```
TID: [-1234] [api/am/publisher] [2021-11-11 11:55:50,808] ERROR {org.wso2.carbon.apimgt.rest.api.util.exception.GlobalThrowableMapper} - An unknown exception has been captured by the global exception mapper. java.lang.NullPointerException
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.apisPost(ApisApiServiceImpl.java:256)
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.apisPost(ApisApi.java:962)
	at sun.reflect.GeneratedMethodAccessor911.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
        .....
```

The error/response is always at the same location: **`ApisApiServiceImpl.apisPost(ApisApiServiceImpl.java:256)`**, and I think is something related with: **`prepareToCreateAPIByDTO`**, but I can not see what happens.

The logged in user is "**`admin`**", with all scopes... I think.

### Affected Product Version:
WSO2 API Manager 3.2.0

### Environment details (with versions):
- OS: Windows 10
- Client: same
- Env (Docker/K8s): none; pure Java standalone
- JAVA Version: 1.8.0_172

---

**Comment by PIPOGit** [comment]
Forget it!

I was sending body data in a "non-proper-way". 😁

**Comment by nandika** [comment]
According to the comment, this is due to user error.
