### ISSUE TITLE
APIM Analytics 3.1.0 Dashboard - Error initializing the data provider endpoint - String index out of range

### ISSUE THREAD

**Issue by Manasha11** [wso2/product-apim#11999]
### Description:
Getting the following error in dashboard logs when loading the TOP API CREATORS widget.

```
ERROR {org.wso2.carbon.data.provider.endpoint.DataProviderEndPoint} - Error initializing the data provider endpoint for source type SiddhiStoreDataProvider. String index out of range: 2269 io.siddhi.core.exception.OnDemandQueryCreationException: String index out of range: 2269
	at io.siddhi.core.SiddhiAppRuntimeImpl.getOnDemandQueryOutputAttributes(SiddhiAppRuntimeImpl.java:410)
	at io.siddhi.core.SiddhiAppRuntimeImpl.getStoreQueryOutputAttributes(SiddhiAppRuntimeImpl.java:384)
	at org.wso2.carbon.data.provider.siddhi.SiddhiProvider.init(SiddhiProvider.java:83)
	at org.wso2.carbon.data.provider.endpoint.DataProviderEndPoint.onMessage(DataProviderEndPoint.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.MSF4JWSConnectorListener.executeMethod(MSF4JWSConnectorListener.java:363)
	at org.wso2.msf4j.internal.MSF4JWSConnectorListener.lambda$handleTextWebSocketMessage$3(MSF4JWSConnectorListener.java:199)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.wso2.msf4j.internal.MSF4JWSConnectorListener.handleTextWebSocketMessage(MSF4JWSConnectorListener.java:180)
	at org.wso2.msf4j.internal.MSF4JWSConnectorListener.onMessage(MSF4JWSConnectorListener.java:86)
	at org.wso2.transport.http.netty.contractimpl.websocket.DefaultWebSocketConnectorFuture.notifyWebSocketListener(DefaultWebSocketConnectorFuture.java:52)
	at org.wso2.transport.http.netty.contractimpl.websocket.WebSocketInboundFrameHandler.notifyTextMessage(WebSocketInboundFrameHandler.java:203)
	at org.wso2.transport.http.netty.contractimpl.websocket.WebSocketInboundFrameHandler.channelRead(WebSocketInboundFrameHandler.java:158)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.channelRead(Utf8FrameValidator.java:77)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1476)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1225)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1272)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 2269
	at java.lang.String.substring(String.java:1963)
	at io.siddhi.query.api.util.ExceptionUtil.getContext(ExceptionUtil.java:119)
	at io.siddhi.core.exception.SiddhiAppCreationException.setQueryContextIndexIfAbsent(SiddhiAppCreationException.java:129)
	at io.siddhi.core.exception.SiddhiAppCreationException.<init>(SiddhiAppCreationException.java:110)
	at io.siddhi.core.util.ExceptionUtil.populateQueryContext(ExceptionUtil.java:58)
	at io.siddhi.core.table.record.ExpressionBuilder.buildVariableExecutors(ExpressionBuilder.java:429)
	at io.siddhi.core.table.record.ExpressionBuilder.build(ExpressionBuilder.java:125)
	at io.siddhi.extension.store.rdbms.RDBMSEventTable.compileSelectClause(RDBMSEventTable.java:2003)
	at io.siddhi.extension.store.rdbms.RDBMSEventTable.compileSelection(RDBMSEventTable.java:1983)
	at io.siddhi.core.table.record.AbstractQueryableRecordTable.compileSelection(AbstractQueryableRecordTable.java:827)
	at io.siddhi.core.util.parser.OnDemandQueryParser.constructOptimizedOnDemandQueryRuntime(OnDemandQueryParser.java:352)
	at io.siddhi.core.util.parser.OnDemandQueryParser.constructOnDemandQueryRuntime(OnDemandQueryParser.java:312)
	at io.siddhi.core.util.parser.OnDemandQueryParser.parse(OnDemandQueryParser.java:156)
	at io.siddhi.core.SiddhiAppRuntimeImpl.getOnDemandQueryOutputAttributes(SiddhiAppRuntimeImpl.java:398)
	... 49 more
```

### Affected Product Version:
APIM Analytics 3.1.0

**Comment by nandika** [comment]
Fix is merged
