### ISSUE TITLE
API invocation getting failed after enabling correlation logs. 

### ISSUE THREAD

**Issue by chaliya96** [wso2/product-apim#12091]
### Description:
After enabling the correlation logs in the API-Manager v3.2.0, all the APIs are getting 202 response code. The below error log is getting in the correlation log file. 

2021-12-01 13:55:58,176|e04ee987-3cc1-4339-8ca1-45a706f82d7f|PassThroughMessageProcessor-9|Cannot publish request event. java.util.TreeMap cannot be cast to java.lang.CharSequence
java.lang.ClassCastException: java.util.TreeMap cannot be cast to java.lang.CharSequence
at org.wso2.carbon.apimgt.gateway.handlers.LogsHandler.buildRequestMessage_aroundBody16(LogsHandler.java:336) ~[org.wso2.carbon.apimgt.gateway_6.7.206.202.jar:?]
at org.wso2.carbon.apimgt.gateway.handlers.LogsHandler.buildRequestMessage(LogsHandler.java:330) ~[org.wso2.carbon.apimgt.gateway_6.7.206.202.jar:?]
at org.wso2.carbon.apimgt.gateway.handlers.LogsHandler.handleRequestOutFlow_aroundBody6(LogsHandler.java:143) [org.wso2.carbon.apimgt.gateway_6.7.206.202.jar:?]
at org.wso2.carbon.apimgt.gateway.handlers.LogsHandler.handleRequestOutFlow(LogsHandler.java:138) [org.wso2.carbon.apimgt.gateway_6.7.206.202.jar:?]
at org.apache.synapse.core.axis2.Axis2Sender.sendOn(Axis2Sender.java:81) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:573) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.endpoints.AbstractEndpoint.send(AbstractEndpoint.java:409) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.endpoints.HTTPEndpoint.send(HTTPEndpoint.java:100) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.endpoints.IndirectEndpoint.send(IndirectEndpoint.java:56) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:123) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.mediators.filters.FilterMediator.mediate(FilterMediator.java:171) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.rest.Resource.process(Resource.java:331) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.rest.API.process(API.java:459) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:144) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.rest.RESTRequestHandler.identifyAPI(RESTRequestHandler.java:164) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:73) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:331) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:99) [synapse-core_2.1.7.wso2v183_10.jar:2.1.7-wso2v183.10]
at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) [axis2_1.6.1.wso2v41_4.jar:?]
at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367) [synapse-nhttp-transport_2.1.7.wso2v183_10.jar:?]
at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:188) [synapse-nhttp-transport_2.1.7.wso2v183_10.jar:?]
at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41_4.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292] 

### Steps to reproduce:
Enable correlation logs. 
Invoke the APIs 

### Affected Product Version:
APIM v3.2.0

**Comment by YasasRangika** [comment]
master fix will be tracked via: https://github.com/wso2/product-apim/issues/11836. Hence closing this ticket.
