### ISSUE TITLE
Unable to generate access token for application type with JWT[APIM-3.0.0 and IS-KM-5.9.0]

### ISSUE THREAD

**Issue by dumindurox777** [wso2/product-apim#12103]
### Description:
Unable to generate the JWT access token for newly created application. WHich is created with JWT token type.

### Steps to reproduce:

- Configure API Manager 3.0.0 with IS as key manager-5.9.0 by following the steps in the documentation[1].
- Enable the back end JWT by adding the below config section to both deployment.toml file on is km and api manager. 
- Then start both servers and create a new application with JWT token type.
![Screenshot 2021-12-06 at 12 43 44](https://user-images.githubusercontent.com/29389251/144803459-1f40ac6e-e727-41f5-9556-455b7702fd69.png)
-Then click the Generate token button and try the flow.
![Screenshot 2021-12-06 at 12 43 53](https://user-images.githubusercontent.com/29389251/144803343-00665b07-9a9a-4ef3-8b56-68a870f12b14.png)

IS-KM logs
```
[2021-12-03 19:55:20,291] [f68823a5-3038-4658-834c-0160563cac77] ERROR {org.wso2.carbon.identity.oauth2.OAuth2Service} - Error occurred while issuing the access token for Client ID : fNkgJloXrf6VTbeIkYSVjyiIJ0Ea, User ID null, Scope : [default] and Grant Type : client_credentials java.lang.NullPointerException
at org.wso2.carbon.apimgt.keymgt.token.JWTGenerator.populateCustomClaims_aroundBody2(JWTGenerator.java:203)
at org.wso2.carbon.apimgt.keymgt.token.JWTGenerator.populateCustomClaims(JWTGenerator.java:159)
at org.wso2.carbon.apimgt.keymgt.token.AbstractJWTGenerator.buildBody_aroundBody10(AbstractJWTGenerator.java:196)
at org.wso2.carbon.apimgt.keymgt.token.AbstractJWTGenerator.buildBody(AbstractJWTGenerator.java:193)
at org.wso2.carbon.apimgt.keymgt.token.AbstractJWTGenerator.generateToken_aroundBody6(AbstractJWTGenerator.java:150)
at org.wso2.carbon.apimgt.keymgt.token.AbstractJWTGenerator.generateToken(AbstractJWTGenerator.java:141)
at org.wso2.carbon.apimgt.keymgt.util.APIMTokenIssuerUtil.generateToken_aroundBody4(APIMTokenIssuerUtil.java:229)
at org.wso2.carbon.apimgt.keymgt.util.APIMTokenIssuerUtil.generateToken(APIMTokenIssuerUtil.java:173)
at org.wso2.carbon.apimgt.keymgt.issuers.APIMTokenIssuer.accessToken_aroundBody0(APIMTokenIssuer.java:102)
at org.wso2.carbon.apimgt.keymgt.issuers.APIMTokenIssuer.accessToken(APIMTokenIssuer.java:51)
```
APIM logs
```
[2021-12-03 19:55:20,306] ERROR - APIUtil Error occurred while executing SubscriberKeyMgtClient.
org.wso2.carbon.apimgt.api.APIManagementException: Error occurred while calling token endpoint: HTTP error code : 500
at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.getNewApplicationAccessToken_aroundBody10(AMDefaultKeyManagerImpl.java:392) ~[org.wso2.carbon.apimgt.impl_6.5.349.48.jar:?]
at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.getNewApplicationAccessToken(AMDefaultKeyManagerImpl.java:307) ~[org.wso2.carbon.apimgt.impl_6.5.349.48.jar:?]
at org.wso2.carbon.apimgt.impl.workflow.AbstractApplicationRegistrationWorkflowExecutor.dogenerateKeysForApplication_aroundBody8(AbstractApplicationRegistrationWorkflowExecutor.java:154) [org.wso2.carbon.apimgt.impl_6.5.349.48.jar:?]
at org.wso2.carbon.apimgt.impl.workflow.AbstractApplicationRegistrationWorkflowExecutor.dogenerateKeysForApplication(AbstractApplicationRegistrationWorkflowExecutor.java:123) [org.wso2.carbon.apimgt.impl_6.5.349.48.jar:?]
at org.wso2.carbon.apimgt.impl.workflow.AbstractApplicationRegistrationWorkflowExecutor.generateKeysForApplication_aroundBody6(AbstractApplicationRegistrationWorkflowExecutor.java:119) [org.wso2.carbon.apimgt.impl_6.5.349.48.jar:?]
```

### Affected Product Version:

Affected Product Version:
wso2am-3.0.0.61
wso2is-km-5.9.0.57

Suggested Labels:
APIM-3.0.0

[1] https://apim.docs.wso2.com/en/3.0.0/install-and-setup/deploying-wso2-api-manager/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/

**Comment by HiranyaKavishani** [comment]
The issue is not reproduced in master branch
