### ISSUE TITLE
To enable async logging mechanism for a specific logger

### ISSUE THREAD

**Issue by sajith-madhusanka** [wso2/product-apim#12108]
### Describe your problem(s)
As per the current implementation of the APIM 3.1.0 server, we can not enable the async logging mechanism for a specific logger. It throws the below error when enabling async logging via the log4j2.properties configuration.

```
org.ops4j.pax.logging.pax-logging-api [log4j2] ERROR : Log4J2 configuration problem: com.lmax.disruptor.dsl.Disruptor.<init>(Lcom/lmax/disruptor/EventFactory;ILjava/util/concurrent/ThreadFactory;Lcom/lmax/disruptor/dsl/ProducerType;Lcom/lmax/disruptor/WaitStrategy;)V Ignored FQCN: org.apache.logging.log4j.spi.AbstractLogger
java.lang.NoSuchMethodError: com.lmax.disruptor.dsl.Disruptor.<init>(Lcom/lmax/disruptor/EventFactory;ILjava/util/concurrent/ThreadFactory;Lcom/lmax/disruptor/dsl/ProducerType;Lcom/lmax/disruptor/WaitStrategy;)V
at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor.start(AsyncLoggerConfigDisruptor.java:231)
at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:296)
at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:579)
at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:285)
at org.ops4j.pax.logging.log4j2.internal.PaxLoggingServiceImpl.configureLog4J2(PaxLoggingServiceImpl.java:439)
at org.ops4j.pax.logging.log4j2.internal.PaxLoggingServiceImpl.updated(PaxLoggingServiceImpl.java:272)
at org.ops4j.pax.logging.log4j2.internal.PaxLoggingServiceImpl$1ManagedPaxLoggingService.updated(PaxLoggingServiceImpl.java:581)
at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:279)
at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:40)
```

### Describe your solution
As per the official log4j2 document [1] , to enable async logging, disruptor-3.3.4.jar or higher is required. Currently, the available disruptor bundle version in the APIM 3.1.0 is 3.3.2.wso2v1. Therefore we need to upgrade the disruptor bundle version and then we can enable the async logging for a specific logger by defining the logger type as below in the log4j2.properties configuration.

Please refer to the below sample log4j2 configurations to enable the async logging for the `synapse-wire` logger
```
logger.synapse-wire.type = AsyncLogger
logger.synapse-wire.name = org.apache.synapse.transport.http.wire
logger.synapse-wire.level = DEBUG
```
[1]:  https://logging.apache.org/log4j/2.x/manual/async.html

**Comment by tharikaGitHub** [comment]
We are already using the disruptor version 3.4.2.wso2v1 in the latest public branch. Hence closing.
