### ISSUE TITLE
Error when deploying an API with multiple endpoints

### ISSUE THREAD

**Issue by mushthaq33** [wso2/product-apim#12119]
### Description:
The following error is logged when deploying an API with multiple endpoints.

`[2021-12-09 15:58:36,900] ERROR - SynapseArtifactGenerator Error while creating Synapse configurations
java.lang.IllegalStateException: Not a JSON Object: [{"template_not_supported":false,"url":"https://www.google.lk"},{"endpoint_type":"http","template_not_supported":false,"url":"test.com"}]
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91) ~[com.google.gson_2.8.6.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ImportUtils.preProcessEndpointConfig(ImportUtils.java:764) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.174.70.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ImportUtils.processRetrievedDefinition(ImportUtils.java:688) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.174.70.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ImportUtils.retrievedAPIDtoJson(ImportUtils.java:657) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.174.70.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ImportUtils.retrievedAPIDto(ImportUtils.java:716) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.174.70.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.SynapseArtifactGenerator.generateGatewayArtifact(SynapseArtifactGenerator.java:94) [org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.174.70.jar:?]
	at org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.RuntimeArtifactGeneratorUtil.generateRuntimeArtifact_aroundBody0(RuntimeArtifactGeneratorUtil.java:60) [org.wso2.carbon.apimgt.impl_9.0.174.72.jar:?]
	at org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.RuntimeArtifactGeneratorUtil.generateRuntimeArtifact(RuntimeArtifactGeneratorUtil.java:36) [org.wso2.carbon.apimgt.impl_9.0.174.72.jar:?]
	at org.wso2.carbon.apimgt.internal.service.impl.RuntimeArtifactsApiServiceImpl.runtimeArtifactsGet(RuntimeArtifactsApiServiceImpl.java:51) [classes/:?]
	at org.wso2.carbon.apimgt.internal.service.RuntimeArtifactsApi.runtimeArtifactsGet(RuntimeArtifactsApi.java:47) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) [cxf-rt-frontend-jaxrs-3.3.7.jar:3.3.7]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) [cxf-rt-frontend-jaxrs-3.3.7.jar:3.3.7]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:220) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) [tomcat-servlet-api_9.0.52.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.52.wso2v2.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107) [org.wso2.carbon.identity.context.rewrite.valve_1.4.25.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.25.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:102) [org.wso2.carbon.identity.auth.valve_1.4.25.6.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:101) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [tomcat_9.0.52.wso2v2.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.52.wso2v2.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[2021-12-09 15:58:36,908] ERROR - InMemoryAPIDeployer Error retrieving artifacts for API 85770def-b7f3-49ac-9669-c187aec7215e. Storage returned null
[2021-12-09 15:58:36,909] ERROR - InMemoryAPIDeployer Error deploying 85770def-b7f3-49ac-9669-c187aec7215e in Gateway
org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.exception.ArtifactSynchronizerException: Error retrieving artifacts for API 85770def-b7f3-49ac-9669-c187aec7215e. Storage returned null
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.retrieveArtifact_aroundBody2(InMemoryAPIDeployer.java:125) [org.wso2.carbon.apimgt.gateway_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.retrieveArtifact(InMemoryAPIDeployer.java:110) [org.wso2.carbon.apimgt.gateway_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:87) [org.wso2.carbon.apimgt.gateway_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:82) [org.wso2.carbon.apimgt.gateway_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage_aroundBody2(GatewayJMSMessageListener.java:152) [org.wso2.carbon.apimgt.gateway_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage(GatewayJMSMessageListener.java:122) [org.wso2.carbon.apimgt.gateway_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage_aroundBody0(GatewayJMSMessageListener.java:97) [org.wso2.carbon.apimgt.gateway_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage(GatewayJMSMessageListener.java:73) [org.wso2.carbon.apimgt.gateway_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.common.jms.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:656) [org.wso2.carbon.apimgt.common.jms_9.0.174.50.jar:?]
	at org.wso2.carbon.apimgt.common.jms.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:555) [org.wso2.carbon.apimgt.common.jms_9.0.174.50.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v63_3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[2021-12-09 15:58:36,909] ERROR - InMemoryAPIDeployer Error deploying 85770def-b7f3-49ac-9669-c187aec7215e in Gateway
org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.exception.ArtifactSynchronizerException: Error deploying 85770def-b7f3-49ac-9669-c187aec7215e in Gateway
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.retrieveArtifact_aroundBody2(InMemoryAPIDeployer.java:130) ~[org.wso2.carbon.apimgt.gateway_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.retrieveArtifact(InMemoryAPIDeployer.java:110) ~[org.wso2.carbon.apimgt.gateway_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:87) [org.wso2.carbon.apimgt.gateway_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:82) [org.wso2.carbon.apimgt.gateway_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage_aroundBody2(GatewayJMSMessageListener.java:152) [org.wso2.carbon.apimgt.gateway_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage(GatewayJMSMessageListener.java:122) [org.wso2.carbon.apimgt.gateway_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage_aroundBody0(GatewayJMSMessageListener.java:97) [org.wso2.carbon.apimgt.gateway_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage(GatewayJMSMessageListener.java:73) [org.wso2.carbon.apimgt.gateway_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.common.jms.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:656) [org.wso2.carbon.apimgt.common.jms_9.0.174.50.jar:?]
	at org.wso2.carbon.apimgt.common.jms.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:555) [org.wso2.carbon.apimgt.common.jms_9.0.174.50.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v63_3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.exception.ArtifactSynchronizerException: Error retrieving artifacts for API 85770def-b7f3-49ac-9669-c187aec7215e. Storage returned null
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.retrieveArtifact_aroundBody2(InMemoryAPIDeployer.java:125) ~[org.wso2.carbon.apimgt.gateway_9.0.174.68.jar:?]
	... 13 more`

### Steps to reproduce:
- Create an API.
- Add load balanced or fail over endpoints.
- Create a revision and deploy.

### Affected Product Version:
APIM 4.0.0

**Comment by Krishanx92** [comment]
Not reproduce in latest version.
