### ISSUE TITLE
[3.0.0] Startup failed with traffic-manager, key-manager, publisher and devPortal profiles

### ISSUE THREAD

**Issue by Chamindu36** [wso2/product-apim#12138]
### Description:
When the latest staging pack of (**Update2 level - 3.0.0.64**) startup failed when starting the server after profile optimization for the following profiles with the attached error. 

**Failing profiles**
1. API Publisher profile
2. Store Profile
3. Key Manager Profile
4. The traffic Manager Profile

```
JAVA_HOME environment variable is set to /usr/lib/jvm/java-8-openjdk-amd64
CARBON_HOME environment variable is set to /home/chamindu/Music/3.0.0_peer_test/wso2am-3.0.0
Using Java memory options: -Xms256m -Xmx1024m
[2021-12-16 12:33:15,776]  SEVERE {org.wso2.carbon.server.Main handleConfiguration} - Error while performing configuration changes 
org.wso2.config.mapper.ConfigParserException: Error while reading metadata
	at org.wso2.config.mapper.MetaDataParser.readLastModifiedValue(MetaDataParser.java:76)
	at org.wso2.config.mapper.MetaDataParser.getChangedFiles(MetaDataParser.java:164)
	at org.wso2.config.mapper.ConfigParser.parse(ConfigParser.java:103)
	at org.wso2.carbon.server.Main.handleConfiguration(Main.java:236)
	at org.wso2.carbon.server.Main.main(Main.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.bootstrap.Bootstrap.loadClass(Bootstrap.java:69)
	at org.wso2.carbon.bootstrap.Bootstrap.main(Bootstrap.java:51)
Caused by: java.io.FileNotFoundException: /home/chamindu/Music/3.0.0_peer_test/wso2am-3.0.0/repository/deployment/server/synapse-configs/default/inbound-endpoints/SecureWebSocketInboundEndpoint.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.wso2.config.mapper.MetaDataParser.getMetadata(MetaDataParser.java:97)
	at org.wso2.config.mapper.MetaDataParser.readLastModifiedValue(MetaDataParser.java:74)
	... 10 more

```
### Steps to reproduce:
1. Get the staging pack of APIM 3.0.0 (**Update2 level - 3.0.0.64**)
2. Run profile optimization for traffic manager profile with `sh profileSetup.sh -Dprofile=traffic-manager`
3. Then you will see the logs that say that the following files have been removed.
```
[2021-12-16 12:33:08] INFO - Removed the WebSocketInboundEndpoint.xml file from ../repository/deployment/server/synapse-configs/default/inbound-endpoints/
[2021-12-16 12:33:08] INFO - Removed the SecureWebSocketInboundEndpoint.xml file from ../repository/deployment/server/synapse-configs/default/inbound-endpoints/ 
```
4. Then start the server with `sh wso2server.sh -Dprofile=traffic-manager` command.
5. The you will be able to observe a FileNotFoundException error as stated above.
6. The profile optimization setups haven't changed recently related to this file config. Hence this should be due to some internal change.

### Affected Product Version:
*Update2 level - 3.0.0.64*

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Chamindu36** [comment]
This was happening when starting the profiles after running the pack in default mode. Hence, this is not an issue.
