### ISSUE TITLE
Unable to setup a distributed API-M deployment

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#12155]
### Description:
When trying to setup and run a distributed deployment, there are server start up issues. Please find the erroneous server logs mentioned below:
```
[2021-12-21 09:52:45,396] ERROR - [/] Exception starting filter [CaptchaFilter]
java.lang.ClassNotFoundException: org.wso2.carbon.identity.captcha.filter.CaptchaFilter
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1365) ~[tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188) ~[tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:540) ~[tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:521) ~[tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:150) ~[tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:249) ~[tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:102) ~[tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4538) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5177) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) [tomcat_9.0.34.wso2v1.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_301]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat_9.0.34.wso2v1.jar:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [?:1.8.0_301]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) [tomcat_9.0.34.wso2v1.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_301]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat_9.0.34.wso2v1.jar:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [?:1.8.0_301]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat_9.0.34.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.service.ExtendedStandardService.startInternal(ExtendedStandardService.java:52) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat_9.0.34.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.internal.CarbonTomcat.start(CarbonTomcat.java:113) [org.wso2.carbon.tomcat_4.6.2.jar:?]
	at org.wso2.carbon.tomcat.internal.ServerManager$1.run(ServerManager.java:167) [org.wso2.carbon.tomcat_4.6.2.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
[2021-12-21 09:52:45,415] ERROR - StandardContext One or more Filters failed to start. Full details will be found in the appropriate container log file
[2021-12-21 09:52:45,417] ERROR - StandardContext Context [/] startup failed due to previous errors
```
Also, note that the server start up takes a considerably long time. The publisher fails to load due to the server startup issues.

### Steps to reproduce:

- Follow the steps under [1] to configure and start a distributed deployment.

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated/

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

**Comment by rmsamitha** [comment]
This error is not reproduced now
