### ISSUE TITLE
Error log observed in  APIM 3.0 Traffic Manager profile startup

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/product-apim#12187]
### Description:
Although the profile get started after optimisation following error log is observed.

`
[2022-01-06 13:34:15,519]  INFO - TemplateDeployerServiceTrackerDS Successfully deployed the execution manager tracker service
[2022-01-06 13:34:15,636] ERROR - FrameworkEvent FrameworkEvent ERROR
org.osgi.framework.BundleException: Could not resolve module: org.wso2.carbon.identity.provisioning [334]
  Unresolved requirement: Import-Package: org.wso2.balana.utils.exception; version="[1.1.0,2.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:457) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
[2022-01-06 13:34:17,063]  INFO - ConsentManagerComponent ConsentManagerComponent is activated.`

### Steps to reproduce:
Optmize APIM 3.0 U2 pack to Traffic Manager and then start the profile.

### Affected Product Version:
APIM 3.0 U2

**Comment by HiranyaKavishani** [comment]
Closing the issue as this has been resolved.
