### ISSUE TITLE
Cannot subscribe to an API via a shared application with multiple users

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#12294]
### Description:
Cannot subscribe to an API via a shared application with multiple users. So this occurs when using the application sharing feature, hence the feature becomes futile.
Note: Application sharing is enabled in configurations when reproducing this issue

### Steps to reproduce:
1. Follow steps in [1] to share applications in-between two users. 
    -  user1, user2 are the self-signed up users used here
    -  APP_A is the shared application
2. Subscribe to the an API by user1 via APP_A.
3. Try to subscribe to same API by user2 via APP_A. Below error dialog will appear.

![image](https://user-images.githubusercontent.com/2484781/151966541-bdd9bc37-aa86-4c65-b1ef-72e36f4b9644.png)
And below error log will be logged in carbon logs.

```
[2022-02-01 17:43:56,917] ERROR - ApiMgtDAO Subscription already exists for API/API Prouct TetApi in Application user1_appA
[2022-02-01 17:43:56,933] ERROR - SubscriptionsApiServiceImpl Specified subscription already exists for API bb1048d6-f8e5-4680-b19d-eb4ab1797066, for application 41874734-d029-43e8-9f33-efb27a8f42fa
org.wso2.carbon.apimgt.api.SubscriptionAlreadyExistingException: Subscription already exists for API/API Prouct TetApi in Application user1_appA
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addSubscription_aroundBody224(ApiMgtDAO.java:5122) ~[org.wso2.carbon.apimgt.impl_9.12.4.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addSubscription(ApiMgtDAO.java:5075) ~[org.wso2.carbon.apimgt.impl_9.12.4.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addSubscription_aroundBody24(ApiMgtDAO.java:630) ~[org.wso2.carbon.apimgt.impl_9.12.4.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addSubscription(ApiMgtDAO.java:623) ~[org.wso2.carbon.apimgt.impl_9.12.4.jar:?]
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.addSubscription_aroundBody94(APIConsumerImpl.java:2699) ~[org.wso2.carbon.apimgt.impl_9.12.4.jar:?]
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.addSubscription(APIConsumerImpl.java:2666) ~[org.wso2.carbon.apimgt.impl_9.12.4.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIConsumer.addSubscription_aroundBody0(UserAwareAPIConsumer.java:65) ~[org.wso2.carbon.apimgt.impl_9.12.4.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIConsumer.addSubscription(UserAwareAPIConsumer.java:63) ~[org.wso2.carbon.apimgt.impl_9.12.4.jar:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.impl.SubscriptionsApiServiceImpl.subscriptionsPost(SubscriptionsApiServiceImpl.java:223) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.SubscriptionsApi.subscriptionsPost(SubscriptionsApi.java:112) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor826.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) [cxf-rt-frontend-jaxrs-3.3.7.jar:3.3.7]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) [cxf-rt-frontend-jaxrs-3.3.7.jar:3.3.7]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:215) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-servlet-api_9.0.34.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.34.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107) [org.wso2.carbon.identity.context.rewrite.valve_1.4.25.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.25.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:102) [org.wso2.carbon.identity.auth.valve_1.4.25.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:101) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [tomcat_9.0.34.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.34.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.34.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

[1] https://apim.docs.wso2.com/en/4.1.0/consume/manage-application/sharing-applications/sharing-applications/#sharing-an-application-with-multiple-users

### Affected Product Version:
APIM-4.1.0-SNAPSHOT - carbon-apimgt v9.12.4 ( > APIM-4.1.0-m3)

**Comment by rmsamitha** [comment]
Allowing to resubscribe the API via same shared application should not be allowed. Allowing that is the actual bug here.
Opened new issue https://github.com/wso2/product-apim/issues/12314 to track that.
