### ISSUE TITLE
API can not delete with nested comments

### ISSUE THREAD

**Issue by Krishanx92** [wso2/product-apim#12299]
### Steps to reproduce:

Create API
Add comment and nested comment
Try to delete the API

```
[2022-02-03 09:48:35,294] ERROR - ApiMgtDAO Error while removing the API with UUID: c4f5f7c1-65b8-4e64-a5e8-061494405095 from the database
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referential integrity constraint violation: "CONSTRAINT_77B2: PUBLIC.AM_API_COMMENTS FOREIGN KEY(PARENT_COMMENT_ID) REFERENCES PUBLIC.AM_API_COMMENTS(COMMENT_ID) ('9e38128c-88ff-4e7f-8917-77d79fa65777')"; SQL statement:
DELETE FROM AM_API_COMMENTS WHERE API_ID=?  [23503-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:459) ~[h2_1.4.200.wso2v1.jar:?]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2_1.4.200.wso2v1.jar:?]
	at org.h2.message.DbException.get(DbException.java:205) ~[h2_1.4.200.wso2v1.jar:?]
	at org.h2.message.DbException.get(DbException.java:181) ~[h2_1.4.200.wso2v1.jar:?]
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:373) ~[h2_1.4.200.wso2v1.jar:?]
	at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:390) ~[h2_1.4.200.wso2v1.jar:?]
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:265) ~[h2_1.4.200.wso2v1.jar:?]
	at org.h2.table.Table.fireConstraints(Table.java:1057) ~[h2_1.4.200.wso2v1.jar:?]
	at org.h2.table.Table.fireAfterRow(Table.java:1075) ~[h2_1.4.200.wso2v1.jar:?]
	at org.h2.command.dml.Delete.update(Delete.java:153) ~[h2_1.4.200.wso2v1.jar:?]
	at org.h2.command.CommandContainer.update(CommandContainer.java:198) ~[h2_1.4.200.wso2v1.jar:?]
	at org.h2.command.Command.executeUpdate(Command.java:251) ~[h2_1.4.200.wso2v1.jar:?]
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:240) ~[h2_1.4.200.wso2v1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[jdbc-pool_9.0.35.wso2v1.jar:?]
	at com.sun.proxy.$Proxy52.execute(Unknown Source) ~[?:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.deleteAPI_aroundBody302(ApiMgtDAO.java:6845) [org.wso2.carbon.apimgt.impl_9.12.6.SNAPSHOT.jar:?]
```

**Comment by HiranyaKavishani** [comment]
@Krishanx92 , Could you please add the reproducible snapshot version?

**Comment by Krishanx92** [comment]
> @Krishanx92 , Could you please add the reproducible snapshot version?

Check latest

**Comment by rashm1n** [comment]
Issue was reproduced in the latest version @HiranyaKavishani , @Krishanx92 .
