### ISSUE TITLE
Error in consumer secret hashing and regenerating consumer secret

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/product-apim#12328]
### Description:
Can't generate access token after enabling hashing consumer secret feature since the consumer secret seems not generated properly when application keys are generated. No errors visible in carbon log and in the UI says "Keys generated successfully". But the UI shows option to regenerate consumer secret option. 

<img width="1680" alt="Screenshot 2022-02-09 at 12 07 16" src="https://user-images.githubusercontent.com/23296184/153135476-3783c4ba-d393-4057-9a83-7e5cefe2c162.png">

When "Regenerate Secret" button is clicked it throws following errors in carbon.log but no errors shown in the UI.

`[2022-02-09 12:00:22,531] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.renewConsumerSecret_aroundBody22(APIConsumerImpl.java:878) ~[org.wso2.carbon.apimgt.impl_9.12.4.jar:?]
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.renewConsumerSecret(APIConsumerImpl.java:872) ~[org.wso2.carbon.apimgt.impl_9.12.4.jar:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApplicationsApiServiceImpl.applicationsApplicationIdOauthKeysKeyMappingIdRegenerateSecretPost(ApplicationsApiServiceImpl.java:1304) ~[classes/:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.ApplicationsApi.applicationsApplicationIdOauthKeysKeyMappingIdRegenerateSecretPost(ApplicationsApi.java:395) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]`

### Steps to reproduce:

Followed the steps in https://apim.docs.wso2.com/en/latest/design/api-security/oauth2/hashing-oauth-keys/

### Affected Product Version:
Pre-Alpha APIM 4.1 pack

**Comment by RakhithaRR** [comment]
It seems the oauth-keys call returns the hash value of the secret. However, this is not shown properly in the UI.

![image](https://user-images.githubusercontent.com/25485273/155283395-41f3b352-1e9e-4eb1-9bd7-882fbf863d21.png)

**Comment by rmsamitha** [comment]
Same issue reported in https://github.com/wso2/product-apim/issues/11971

**Comment by rmsamitha** [comment]
Closing as the fix is merged for #11971
