### ISSUE TITLE
Server startup error

### ISSUE THREAD

**Issue by Krishanx92** [wso2/product-apim#12346]
### Description:

Below error thrown when starting the server.

`[2022-02-10 13:36:13,309]  INFO - JMSListener Started to listen on destination : notification of type topic for listener Siddhi-JMS-Consumer#notification
Exception in thread "Timer-15" java.lang.NullPointerException
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService_aroundBody6(KeyTemplateRetriever.java:123)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService(KeyTemplateRetriever.java:121)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run_aroundBody0(KeyTemplateRetriever.java:56)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run(KeyTemplateRetriever.java:52)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
[2022-02-10 13:36:13,389]  INFO - JMSListener Started to listen on destination : asyncWebhooksData of type topic for listener Siddhi-JMS-Consumer#asyncWebhooksData
[2022-02-10 13:36:13,408]  INFO - DBRetriever No artifacts available to deploy
[2022-02-10 13:36:13,483]  INFO - GatewayStartupListener Synapse Artifacts deployed Successfully in the Gateway
Exception in thread "Timer-14" [2022-02-10 13:36:13,524]  INFO - DataBridge user admin connected
java.lang.NullPointerException
	at org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever.loadBlockingConditionsFromWebService_aroundBody6(BlockingConditionRetriever.java:112)
	at org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever.loadBlockingConditionsFromWebService(BlockingConditionRetriever.java:109)
	at org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever.run_aroundBody0(BlockingConditionRetriever.java:52)
	at org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever.run(BlockingConditionRetriever.java:48)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
[2022-02-10 13:36:13,528]  INFO - JMSListener Started to listen on destination : keyManager of type topic for listener Siddhi-JMS-Consumer#keyManager
`

**Comment by rmsamitha** [comment]
Closing as the PR is merged
