### ISSUE TITLE
Unable to generate App keys with Auth0

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/product-apim#12464]
### Description:

Unable to generate App keys after configuring Auth0 KM. Following error trace comes in the carbon.log.

`Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 19 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386) ~[com.google.gson_2.8.6.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[com.google.gson_2.8.6.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[com.google.gson_2.8.6.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[com.google.gson_2.8.6.jar:?]
	at feign.gson.GsonDecoder.decode(GsonDecoder.java:50) ~[io.github.openfeign.feign-gson_11.0.0.jar:?]
	at feign.AsyncResponseHandler.decode(AsyncResponseHandler.java:115) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:87) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at com.sun.proxy.$Proxy468.createApplication(Unknown Source) ~[?:?]
	at org.wso2.auth0.client.Auth0OAuthClient.createApplication(Auth0OAuthClient.java:100) ~[auth0.key.manager_1.0.1.jar:?]
	at org.wso2.carbon.apimgt.impl.workflow.AbstractApplicationRegistrationWorkflowExecutor.dogenerateKeysForApplication_aroundBody8(AbstractApplicationRegistrationWorkflowExecutor.java:153) ~[org.wso2.carbon.apimgt.impl_9.18.8.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.workflow.AbstractApplicationRegistrationWorkflowExecutor.dogenerateKeysForApplication(AbstractApplicationRegistrationWorkflowExecutor.java:124) ~[org.wso2.carbon.apimgt.impl_9.18.8.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.workflow.AbstractApplicationRegistrationWorkflowExecutor.generateKeysForApplication_aroundBody6(AbstractApplicationRegistrationWorkflowExecutor.java:120) ~[org.wso2.carbon.apimgt.impl_9.18.8.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.workflow.AbstractApplicationRegistrationWorkflowExecutor.generateKeysForApplication(AbstractApplicationRegistrationWorkflowExecutor.java:117) ~[org.wso2.carbon.apimgt.impl_9.18.8.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.workflow.ApplicationRegistrationSimpleWorkflowExecutor.complete_aroundBody2(ApplicationRegistrationSimpleWorkflowExecutor.java:77) ~[org.wso2.carbon.apimgt.impl_9.18.8.SNAPSHOT.jar:?]
	... 59 more`

- After debugging App creation request response seems to be with 200 ok status code, but body decoding seems to have an issue.

<img width="1679" alt="Screenshot 2022-02-23 at 16 53 06" src="https://user-images.githubusercontent.com/23296184/155310268-985c15e8-9316-4ad3-a47e-3af8e264375e.png">

Alpha seems to present an older version of the auth0.key.manager jar. need to update version as well.

### Steps to reproduce:

Followed steps in https://apim.docs.wso2.com/en/4.1.0/administer/key-managers/configure-auth0-connector/

### Affected Product Version:
APIM 4.1

**Comment by tharikaGitHub** [comment]
Fixed with https://github.com/wso2/product-apim/pull/12636
