### ISSUE TITLE
Websocket: API gateway not throw any error when the backend is down

### ISSUE THREAD

**Issue by nuwankng** [wso2/product-apim#12473]
### Description:

This is an issue observed on the WebSocket API. The gateway does not throw any error messages when the backend server is down or not reachable or any issue with the backend connectivity. And in the event of backend fault scenario ,the gateway should send the proper error messages to the clients and the connection should be closed.

### Steps to reproduce:

- Started the both secure Websocket-Server and client  according to the[1].

- Created the websocket API through the APIM. And configured to the endpoint (wss://localhost:8090  - as mentioned in [1] ).

- Invoked the created API through the postman under the Websocket-Server running mode. Then we were able to get the logs
successfully to the client.  (to the Postman)

- After that we invoked this API under Websocket-Server down mode. Then it is not able to get any error or updated message to the client side. (to the Postman)

When the backend is unavailable, we saw the following exceptions in the carbon logs when using the websocket API flow in latest update levels of APIM 3.2.0 , 2.6.0 and 4.0.0 as well. The GW is logging error messages, and the log will alert us of Connection rejected issues due to the backend server connection being unavailable as below.

`[2022-02-14 17:14:28,202] ERROR - WebsocketTransportSender Error writting to the websocket channel
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8090
Caused by: java.net.ConnectException: Connection refused
 at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
 at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779) ~[?:?]
 at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[io.netty.transport_4.1.73.Final.jar:4.1.73.Final]
 at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[io.netty.transport_4.1.73.Final.jar:4.1.73.Final]
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710) ~[io.netty.transport_4.1.73.Final.jar:4.1.73.Final]
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[io.netty.transport_4.1.73.Final.jar:4.1.73.Final]
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[io.netty.transport_4.1.73.Final.jar:4.1.73.Final]
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[io.netty.transport_4.1.73.Final.jar:4.1.73.Final]
 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[io.netty.common_4.1.73.Final.jar:4.1.73.Final]
 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.common_4.1.73.Final.jar:4.1.73.Final]
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.common_4.1.73.Final.jar:4.1.73.Final]
 at java.lang.Thread.run(Thread.java:834) [?:?]`

- Still the client didn't receive the proper response about the issue.

### Affected Product Version:

APIM-3.2.0

[1] - https://github.com/JanakaPushpakumara/ClientsAndServers/tree/main/Websocket

**Comment by rmsamitha** [comment]
Duplicate issue https://github.com/wso2/micro-integrator/issues/2657.
