### ISSUE TITLE
Exception in logs when adding IS as 3rd party KM

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#12599]
### Description:
Although the KM can be added successfully through the UI, there is an exception thrown in the APIM console logs as follows. This might be due to the h2 DB version difference in IS 5.11.0 and APIM 4.1.0

```
[2022-03-09 06:39:38,178] ERROR - LogExceptionHandler [ Sequence: 1561 ] Exception occurred while processing inbound events.Event type: MESSAGE_EVENT
org.wso2.andes.store.AndesDataException: Error occurred while inserting message to queue
	at org.wso2.andes.store.rdbms.RDBMSStoreUtils.convertBySQLState(RDBMSStoreUtils.java:177) ~[andes_3.3.21.jar:?]
	at org.wso2.andes.store.rdbms.RDBMSStoreUtils.convertSQLException(RDBMSStoreUtils.java:124) ~[andes_3.3.21.jar:?]
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessage(RDBMSMessageStoreImpl.java:502) ~[andes_3.3.21.jar:?]
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:405) ~[andes_3.3.21.jar:?]
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123) ~[andes_3.3.21.jar:?]
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:173) ~[andes_3.3.21.jar:?]
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:100) ~[andes_3.3.21.jar:?]
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137) ~[andes_3.3.21.jar:?]
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40) ~[andes_3.3.21.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) [disruptor_3.4.2.wso2v1.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) [disruptor_3.4.2.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
Caused by: org.h2.jdbc.JdbcBatchUpdateException: Value too long for column "MESSAGE_CONTENT BINARY(1000)": "CAST(X'7b226576656e74223a7b227061796c6f616444617461223a7b226576656e745f747970652... (1385)"; SQL statement:
INSERT INTO MB_CONTENT(MESSAGE_ID,CONTENT_OFFSET,MESSAGE_CONTENT) VALUES (?, ?, ?) [22001-210]
	at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1269) ~[h2_2.1.210.wso2v1.jar:?]
	at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_301]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_301]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[jdbc-pool_9.0.35.wso2v1.jar:?]
	at com.sun.proxy.$Proxy49.executeBatch(Unknown Source) ~[?:?]
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessage(RDBMSMessageStoreImpl.java:485) ~[andes_3.3.21.jar:?]
	... 11 more
[2022-03-09 06:39:38,978] ERROR - MessageWriter errors encountered while persisting previously failed messages batch,  this incident will result messages being lost
org.wso2.andes.store.AndesDataException: Error occurred while inserting message to queue
	at org.wso2.andes.store.rdbms.RDBMSStoreUtils.convertBySQLState(RDBMSStoreUtils.java:177) ~[andes_3.3.21.jar:?]
	at org.wso2.andes.store.rdbms.RDBMSStoreUtils.convertSQLException(RDBMSStoreUtils.java:124) ~[andes_3.3.21.jar:?]
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessage(RDBMSMessageStoreImpl.java:502) ~[andes_3.3.21.jar:?]
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:405) ~[andes_3.3.21.jar:?]
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123) ~[andes_3.3.21.jar:?]
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:173) ~[andes_3.3.21.jar:?]
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:87) ~[andes_3.3.21.jar:?]
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137) ~[andes_3.3.21.jar:?]
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40) ~[andes_3.3.21.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) [disruptor_3.4.2.wso2v1.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) [disruptor_3.4.2.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
Caused by: org.h2.jdbc.JdbcBatchUpdateException: Value too long for column "MESSAGE_CONTENT BINARY(1000)": "CAST(X'7b226576656e74223a7b227061796c6f616444617461223a7b226576656e745f747970652... (1385)"; SQL statement:
INSERT INTO MB_CONTENT(MESSAGE_ID,CONTENT_OFFSET,MESSAGE_CONTENT) VALUES (?, ?, ?) [22001-210]
	at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1269) ~[h2_2.1.210.wso2v1.jar:?]
	at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_301]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_301]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[jdbc-pool_9.0.35.wso2v1.jar:?]
	at com.sun.proxy.$Proxy49.executeBatch(Unknown Source) ~[?:?]
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessage(RDBMSMessageStoreImpl.java:485) ~[andes_3.3.21.jar:?]
	... 11 more```

**Comment by RakhithaRR** [comment]
We recently changed the db schema for mb_db with the h2 upgrade since in h2 2.x versions, the default size of BINARY type is considered as 1 [1]. We need to discuss this and figure out a proper value for this (currently, we use 1000) [2].

[1] - http://www.h2database.com/html/changelog.html
[2] - https://github.com/wso2/carbon-business-messaging/pull/707

**Comment by Krishanx92** [comment]
https://github.com/wso2/product-apim/issues/12586

**Comment by tharikaGitHub** [comment]
@RakhithaRR and @tharindu1st We can either use the value 1048576 which is the allowed maximum in BINARY type or else use BINARY VARYING type instead. For variable-length binary strings this can be used. WDYT?

**Comment by RakhithaRR** [comment]
Let's go ahead with the max allowed value. I guess this was the default value in H2 1.x versions.
