### ISSUE TITLE
Error while adding a policy and cannot invoke some GraphQL mutations

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#12603]
### Description:
Error while adding a policy and cannot invoke some GraphQL mutations (Not sure whether these two issue are interrelated or not)

### Steps to reproduce:
Follow the steps 1 to 5 in [1].

After finishing the step 1, there was an error as below in the logs.

```
[2022-03-09 09:13:33,849] ERROR - PolicyUtil Error in deploying execution plan
org.wso2.carbon.event.processor.core.exception.ExecutionPlanConfigurationException: Couldn't parse execution plan: 
		@Plan:name('carbon.super_sub_Platinum')

		@Plan:description('ExecutionPlan for sub_Platinum')

		@Import('org.wso2.throttle.processed.request.stream:1.0.0')
		define stream RequestStream (messageID string, appKey string, appTier string, subscriptionKey string, apiKey string, apiTier string, subscriptionTier string, resourceKey string, resourceTier string, userId string,  apiContext string, apiVersion string, appTenant string, apiTenant string, appId string, apiName string, propertiesMap string);

		@Export('org.wso2.throttle.globalThrottle.stream:1.0.0')
		define stream GlobalThrottleStream (throttleKey string, isThrottled bool, expiryTimeStamp long);

		FROM RequestStream
		SELECT messageID, (apiTenant == 'carbon.super' and subscriptionTier == 'Platinum') AS isEligible, subscriptionKey AS throttleKey, propertiesMap
		INSERT INTO EligibilityStream;

				FROM EligibilityStream[isEligible==true]#throttler:timeBatch(-2 min, 0)
				select throttleKey, (count(messageID) >= 2000) as isThrottled, expiryTimeStamp group by throttleKey
				INSERT ALL EVENTS into ResultStream;
		
		from ResultStream#throttler:emitOnStateChange(throttleKey, isThrottled) select * insert into GlobalThrottleStream;


	at org.wso2.carbon.event.processor.core.internal.CarbonEventProcessorService.deployExecutionPlan(CarbonEventProcessorService.java:118) ~[?:?]
	at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.PolicyUtil.deployPolicy(PolicyUtil.java:133) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.20.12.jar:?]
	at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.ThrottlePolicyJMSMessageListener.lambda$handleNotificationMessage$0(ThrottlePolicyJMSMessageListener.java:128) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.20.12.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_251]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_251]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
ANTLR Tool version 4.9.2 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.9.2 used for parser compilation does not match the current runtime version 4.7.1ANTLR Tool version 4.9.2 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.9.2 used for parser compilation does not match the current runtime version 4.7.1[2022-03-09 09:16:51,825]  INFO - CommonUtil Creation of folder is successful. Directory Name : Definitions
```

Then after the 5th step, the UI displayed an error as below.
![image](https://user-images.githubusercontent.com/25246848/157369632-14b06e0d-cb47-4643-a061-7d1772d9663f.png)

The server logs will contain the error as shown below (which is similar to [1])
```
[2022-03-09 09:18:32,920] ERROR - GraphQLQueryAnalysisHandler Policy definition parsing failed. 
graphql.execution.NonNullableValueCoercedAsNullException: Variable 'id' has coerced Null value for NonNull type 'ID!'
	at graphql.execution.ValuesResolver.externalValueToInternalValueForVariables(ValuesResolver.java:407) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.execution.ValuesResolver.coerceVariableValues(ValuesResolver.java:94) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.analysis.QueryTraverser.coerceVariables(QueryTraverser.java:64) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.analysis.QueryTraverser.<init>(QueryTraverser.java:60) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.analysis.QueryTraverser.<init>(QueryTraverser.java:40) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.analysis.QueryTraverser$Builder.build(QueryTraverser.java:297) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.analysis.MaxQueryComplexityInstrumentation.newQueryTraverser(MaxQueryComplexityInstrumentation.java:133) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.analysis.MaxQueryComplexityInstrumentation.lambda$beginValidation$4(MaxQueryComplexityInstrumentation.java:85) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.execution.instrumentation.SimpleInstrumentationContext.onCompleted(SimpleInstrumentationContext.java:51) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.execution.instrumentation.ChainedInstrumentation$ChainedInstrumentationContext.lambda$onCompleted$1(ChainedInstrumentation.java:238) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.com.google.common.collect.ImmutableList.forEach(ImmutableList.java:405) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.execution.instrumentation.ChainedInstrumentation$ChainedInstrumentationContext.onCompleted(ChainedInstrumentation.java:238) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.GraphQL.validate(GraphQL.java:600) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.GraphQL.parseAndValidate(GraphQL.java:562) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.GraphQL.lambda$parseValidateAndExecute$10(GraphQL.java:531) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.execution.preparsed.NoOpPreparsedDocumentProvider.getDocument(NoOpPreparsedDocumentProvider.java:15) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:533) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.GraphQL.executeAsync(GraphQL.java:502) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:433) ~[graphQL_17.3.0.wso2v1.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:315) ~[graphQL_17.3.0.wso2v1.jar:?]
	at org.wso2.carbon.apimgt.common.gateway.graphql.QueryAnalyzer.analyseQueryComplexity(QueryAnalyzer.java:113) ~[org.wso2.carbon.apimgt.common.gateway_9.20.12.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.graphQL.analyzer.QueryMutationAnalyzer.analyseQueryMutationComplexity_aroundBody4(QueryMutationAnalyzer.java:108) ~[org.wso2.carbon.apimgt.gateway_9.20.12.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.graphQL.analyzer.QueryMutationAnalyzer.analyseQueryMutationComplexity(QueryMutationAnalyzer.java:97) ~[org.wso2.carbon.apimgt.gateway_9.20.12.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.graphQL.GraphQLQueryAnalysisHandler.analyseQuery_aroundBody2(GraphQLQueryAnalysisHandler.java:74) ~[org.wso2.carbon.apimgt.gateway_9.20.12.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.graphQL.GraphQLQueryAnalysisHandler.analyseQuery(GraphQLQueryAnalysisHandler.java:70) ~[org.wso2.carbon.apimgt.gateway_9.20.12.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.graphQL.GraphQLQueryAnalysisHandler.handleRequest_aroundBody0(GraphQLQueryAnalysisHandler.java:54) ~[org.wso2.carbon.apimgt.gateway_9.20.12.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.graphQL.GraphQLQueryAnalysisHandler.handleRequest(GraphQLQueryAnalysisHandler.java:42) ~[org.wso2.carbon.apimgt.gateway_9.20.12.jar:?]
	at org.apache.synapse.api.API.process(API.java:403) ~[synapse-core_2.1.7.wso2v263.jar:2.1.7-wso2v263]
	at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:107) ~[synapse-core_2.1.7.wso2v263.jar:2.1.7-wso2v263]
	at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:127) ~[synapse-core_2.1.7.wso2v263.jar:2.1.7-wso2v263]
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:59) ~[synapse-core_2.1.7.wso2v263.jar:2.1.7-wso2v263]
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:90) ~[synapse-core_2.1.7.wso2v263.jar:2.1.7-wso2v263]
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:76) ~[synapse-core_2.1.7.wso2v263.jar:2.1.7-wso2v263]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) ~[synapse-core_2.1.7.wso2v263.jar:2.1.7-wso2v263]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344) ~[synapse-core_2.1.7.wso2v263.jar:2.1.7-wso2v263]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101) ~[synapse-core_2.1.7.wso2v263.jar:2.1.7-wso2v263]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v77.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:376) ~[synapse-nhttp-transport_2.1.7.wso2v263.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:435) ~[synapse-nhttp-transport_2.1.7.wso2v263.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:183) ~[synapse-nhttp-transport_2.1.7.wso2v263.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) ~[axis2_1.6.1.wso2v77.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
[2022-03-09 09:20:11,487]  INFO - PassThroughHttpSSLSender PassThroughHttpSender reloading SSL Config..
[2022-03-09 09:20:11,494]  INFO - ClientConnFactoryBuilder customSSLProfiles configuration is loaded from path: /home/wasura/Desktop/wso2am-4.1.0-SNAPSHOT/repository/resources/security/sslprofiles.xml
[2022-03-09 09:20:11,494]  INFO - ClientConnFactoryBuilder HTTPS Loading custom SSL profiles for the HTTPS sender
[2022-03-09 09:20:11,524]  INFO - ClientConnFactoryBuilder HTTPS Custom SSL profiles initialized for 1 servers
[2022-03-09 09:20:11,528]  INFO - PassThroughHttpSSLSender Pass-through HTTPS Sender updated with Dynamic Configuration Updates ...
[2022-03-09 09:20:11,620]  INFO - PassThroughHttpMultiSSLListener PassThroughHttpListener reloading SSL Config..
[2022-03-09 09:20:11,640]  INFO - ServerConnFactoryBuilder SSLProfile configuration is loaded from path: /home/wasura/Desktop/wso2am-4.1.0-SNAPSHOT/repository/resources/security/listenerprofiles.xml
[2022-03-09 09:20:11,657]  INFO - PassThroughListeningIOReactorManager Pass-through HTTPS Listener started on 0.0.0.0:8243
[2022-03-09 09:20:11,658]  INFO - PassThroughHttpMultiSSLListener HTTPS Reloaded
```

### Affected Product Version:
APIM 4.1.0-Beta

[1] https://github.com/wso2/product-apim/issues/12025

**Comment by msm1992** [comment]
@wasuradananjith First issue was not reproducible in either beta pack or the latest build. Found a similar issue reported for custom policies https://github.com/wso2/product-apim/issues/12472.

Second issue was reproducible in 4.1.0 beta pack, but was not reproducible in the latest build. Hence I will close this issue, please reopen if you have further concerns.
