### ISSUE TITLE
Error while unloading a tenant when tenant loading is unsuccessful

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/product-apim#12653]
### Description:
When a tenant was not loaded correctly, an exception is thrown during the tenant unloading flow. The following error will be printed in the wso2carbon.log continuously based on the configured tenant_idle_timeout interval.

```
TID: [-1] [] [2022-03-09 14:02:49,813] ERROR {org.wso2.carbon.core.multitenancy.MultitenantServerManager} - Error occurred while executing tenant cleanup java.lang.IllegalStateException: The service has been unregistered
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getReferenceImpl(ServiceRegistrationImpl.java:291)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getReference(ServiceRegistrationImpl.java:280)
	at org.wso2.carbon.mediation.initializer.multitenancy.TenantServiceBusInitializer.terminatingConfigurationContext(TenantServiceBusInitializer.java:290)
	at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.doPreConfigContextTermination(TenantAxisUtils.java:558)
	at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.terminateTenantConfigContext(TenantAxisUtils.java:519)
	at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.cleanupTenants(TenantAxisUtils.java:468)
	at org.wso2.carbon.core.multitenancy.MultitenantServerManager$TenantCleanupTask.run(MultitenantServerManager.java:75)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Affected Product Version:
APIM 3.2.0

**Comment by rmsamitha** [comment]
@<public fix creator>
Once fixing this in master, please mention the public PR in patch entry WSO2-CARBON-PATCH-4.6.0-1724 and change the status of the patch entry too accordingly.
