### ISSUE TITLE
Error encountered while processing the large responses in GraphQL 

### ISSUE THREAD

**Issue by Menuka-Senevirathne** [wso2/product-apim#12703]
### Describe your problem(s)
The below error occurs when the frame length of the response is higher than 65536

```
TID: [] [] [2022-03-08 11:27:56,507] ERROR
Unknown macro: {org.wso2.carbon.websocket.transport.WebSocketClientHandler} - Error encountered while processing the response io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Max frame length of 65536 has been exceeded.
at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:424)
at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:286)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
```

---

#### Suggested Labels:
APIM 3.2, GraphQL

**Comment by nandika** [comment]
Fix is applied.
