### ISSUE TITLE
For some migrating APIs , GW_API_ARTIFACTS.ARTIFACT  BLOB column size not sufficient 

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#12747]
### Description:
It seems the ARTIFACT  BLOB column size in  GW_API_ARTIFACTS table is not  sufficient for old migrating APIs, hence we are getting below error during migration. 

`Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'ARTIFACT' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104) ~[mysql-connector-java-8.0.15.jar:8.0.15]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:970) ~[mysql-connector-java-8.0.15.jar:8.0.15]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1109) ~[mysql-connector-java-8.0.15.jar:8.0.15]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1057) ~[mysql-connector-java-8.0.15.jar:8.0.15]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1377) ~[mysql-connector-java-8.0.15.jar:8.0.15]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1042) ~[mysql-connector-java-8.0.15.jar:8.0.15]
	at jdk.internal.reflect.GeneratedMethodAccessor68.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[jdbc-pool_9.0.35.wso2v1.jar:?]
	at com.sun.proxy.$Proxy53.executeUpdate(Unknown Source) ~[?:?]
	at org.wso2.carbon.apimgt.impl.dao.GatewayArtifactsMgtDAO.addGatewayPublishedAPIArtifacts_aroundBody4(GatewayArtifactsMgtDAO.java:103) ~[org.wso2.carbon.apimgt.impl_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.GatewayArtifactsMgtDAO.addGatewayPublishedAPIArtifacts(GatewayArtifactsMgtDAO.java:87) ~[org.wso2.carbon.apimgt.impl_9.0.174.68.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.GatewayArtifactsMgtDAO.addGatewayAPIArtifactAndMetaData_aroundBody36(GatewayArtifactsMgtDAO.java:537) ~[org.wso2.carbon.apimgt.impl_9.0.174.68.jar:?]
	... 48 more`

As a precaution, we can increase the size of the column from BLOB -> MEDIUMBLOB in mysql DB scripts.

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
