### ISSUE TITLE
Error log appears when deploying APIs in CC with APIM scenario

### ISSUE THREAD

**Issue by slahirucd7** [wso2/product-apim#12750]
### Description:
API deployment gives error log for default gateway deployment.
In Choreo-Connect with APIM scenario, default gateway is the choreo-connect. 
(In the pack configurations added to follow that approach.)

We are enabling it by adding below configuration in the `deployment.toml`

```
[apim.sync_runtime_artifacts.gateway]
gateway_labels =["Default"]
enable = false
```

### Steps to reproduce:

1. Change `deployment.toml` configuration as follows.

```
[apim.sync_runtime_artifacts.gateway]
gateway_labels =["Default"]
enable = false
```

2. Start APIM pack.
3. Configure CC to point the started APIM pack.
4. Create and deploy API in API-M (deployment should performed to the default gateway. I.E it's Choreo Connect in this scenario).
5. Below log appears in the API-M.

```
[2022-03-23 16:08:28,466] ERROR - InMemoryAPIDeployer Artifact retriever not found
[2022-03-23 16:08:28,468] ERROR - InMemoryAPIDeployer Error deploying 314f0d34-94aa-4685-855a-6868a9f32141 in Gateway
org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.exception.ArtifactSynchronizerException: Artifact retriever not found
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.retrieveArtifact_aroundBody2(InMemoryAPIDeployer.java:143) ~[org.wso2.carbon.apimgt.gateway_9.20.59.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.retrieveArtifact(InMemoryAPIDeployer.java:118) ~[org.wso2.carbon.apimgt.gateway_9.20.59.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:92) ~[org.wso2.carbon.apimgt.gateway_9.20.59.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:87) ~[org.wso2.carbon.apimgt.gateway_9.20.59.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage_aroundBody2(GatewayJMSMessageListener.java:153) ~[org.wso2.carbon.apimgt.gateway_9.20.59.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage(GatewayJMSMessageListener.java:123) ~[org.wso2.carbon.apimgt.gateway_9.20.59.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage_aroundBody0(GatewayJMSMessageListener.java:98) ~[org.wso2.carbon.apimgt.gateway_9.20.59.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage(GatewayJMSMessageListener.java:74) ~[org.wso2.carbon.apimgt.gateway_9.20.59.jar:?]
	at org.wso2.carbon.apimgt.common.jms.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:656) ~[org.wso2.carbon.apimgt.common.jms_9.20.59.jar:?]
	at org.wso2.carbon.apimgt.common.jms.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:555) ~[org.wso2.carbon.apimgt.common.jms_9.20.59.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) ~[axis2_1.6.1.wso2v80.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
[2022-03-23 16:08:28,469] ERROR - GatewayJMSMessageListener Error in deploying artifacts for 314f0d34-94aa-4685-855a-6868a9f32141in the Gateway
[2022-03-23 16:15:07,643]  INFO - PassThroughHttpSSLSender PassThroughHttpSender reloading SSL Config..
[2022-03-23 16:15:07,689]  INFO - PassThroughHttpMultiSSLListener PassThroughHttpListener reloading SSL Config..
[2022-03-23 16:15:07,724]  INFO - ClientConnFactoryBuilder customSSLProfiles configuration is loaded from path: /Users/lahirud/Downloads/wso2am-4.1.0-SNAPSHOT/repository/resources/security/sslprofiles.xml
[2022-03-23 16:15:07,725]  INFO - ServerConnFactoryBuilder SSLProfile configuration is loaded from path: /Users/lahirud/Downloads/wso2am-4.1.0-SNAPSHOT/repository/resources/security/listenerprofiles.xml
[2022-03-23 16:15:07,725]  INFO - ClientConnFactoryBuilder HTTPS Loading custom SSL profiles for the HTTPS sender
[2022-03-23 16:15:07,733]  INFO - ClientConnFactoryBuilder HTTPS Custom SSL profiles initialized for 1 servers
[2022-03-23 16:15:07,736]  INFO - PassThroughHttpSSLSender Pass-through HTTPS Sender updated with Dynamic Configuration Updates ...
[2022-03-23 16:15:07,751]  INFO - Pa

```

### Affected Product Version:
API-M RC1 release test pack

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by slahirucd7** [comment]
Closing this since as a work around trying control plane profile approach.
