### ISSUE TITLE
Schema validation is not working in distributed setup

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/product-apim#12815]
### Description:
The following issue occurs when schema validation is enabled in a distributed setup.
```
[2022-03-31 13:18:31,170] ERROR - NativeWorkerPool Uncaught exception
java.lang.NoClassDefFoundError: io/swagger/util/Json
	at com.atlassian.oai.validator.schema.SchemaValidator.lambda$new$0(SchemaValidator.java:92) ~[swagger-request-validator-core_2.12.1.wso2v2.jar:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_271]
	at com.atlassian.oai.validator.schema.SchemaValidator.<init>(SchemaValidator.java:92) ~[swagger-request-validator-core_2.12.1.wso2v2.jar:?]
	at com.atlassian.oai.validator.OpenApiInteractionValidator.<init>(OpenApiInteractionValidator.java:149) ~[swagger-request-validator-core_2.12.1.wso2v2.jar:?]
	at com.atlassian.oai.validator.OpenApiInteractionValidator.<init>(OpenApiInteractionValidator.java:46) ~[swagger-request-validator-core_2.12.1.wso2v2.jar:?]
	at com.atlassian.oai.validator.OpenApiInteractionValidator$Builder.build(OpenApiInteractionValidator.java:543) ~[swagger-request-validator-core_2.12.1.wso2v2.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.getOpenAPIValidator_aroundBody0(SchemaValidator.java:67) ~[org.wso2.carbon.apimgt.gateway_9.0.174.131.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.getOpenAPIValidator(SchemaValidator.java:52) ~[org.wso2.carbon.apimgt.gateway_9.0.174.131.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.handleRequest_aroundBody2(SchemaValidator.java:78) ~[org.wso2.carbon.apimgt.gateway_9.0.174.131.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.handleRequest(SchemaValidator.java:71) ~[org.wso2.carbon.apimgt.gateway_9.0.174.131.jar:?]
	at org.apache.synapse.api.API.process(API.java:389) ~[synapse-core_2.1.7.wso2v227_26.jar:2.1.7-wso2v227.26]
	at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:107) ~[synapse-core_2.1.7.wso2v227_26.jar:2.1.7-wso2v227.26]
	at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:127) ~[synapse-core_2.1.7.wso2v227_26.jar:2.1.7-wso2v227.26]
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:59) ~[synapse-core_2.1.7.wso2v227_26.jar:2.1.7-wso2v227.26]
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:84) ~[synapse-core_2.1.7.wso2v227_26.jar:2.1.7-wso2v227.26]
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:70) ~[synapse-core_2.1.7.wso2v227_26.jar:2.1.7-wso2v227.26]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) ~[synapse-core_2.1.7.wso2v227_26.jar:2.1.7-wso2v227.26]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344) ~[synapse-core_2.1.7.wso2v227_26.jar:2.1.7-wso2v227.26]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101) ~[synapse-core_2.1.7.wso2v227_26.jar:2.1.7-wso2v227.26]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v63_3.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:375) ~[synapse-nhttp-transport_2.1.7.wso2v227_18.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:189) ~[synapse-nhttp-transport_2.1.7.wso2v227_18.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v63_3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_271]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
Caused by: java.lang.ClassNotFoundException: io.swagger.util.Json cannot be found by swagger-request-validator-core_2.12.1.wso2v2
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_271]
	... 26 more

```

### Steps to reproduce:
1. Get API Manager 4.0.0 pack.
2. Set a distributed deployment locally with 1 control plane and 1 gateway with a RDBMS.
3. Import the API that the customer provided on the ticket and set a mock endpoint.
4. If is disable, enable the schema validation for the API.
5. Make a request to a resource of the API.

### Affected Product Version:
APIM 4.0.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by damoebius** [comment]
Maybe I found something
I'll try to add missings jar to \repository\components\gateway-worker\configuration\org.eclipse.equinox.simpleconfigurator\bundles.info

**Comment by chamilaadhi** [comment]
@damoebius 


@damoebius thanks for analyzing this. You have to add `io.swagger.annotations` as well to the bundles.info file (other than o.swagger.core)

Following are the entries that need to be in the repository/components/gateway-worker/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info file 
```
io.swagger.annotations,1.6.5,../plugins/io.swagger.annotations_1.6.5.jar,4,true
io.swagger.core,1.6.5,../plugins/io.swagger.core_1.6.5.jar,4,true
```

Hope this resolves the issue
