### ISSUE TITLE
API Creation using WSDL File/Archive not working.

### ISSUE THREAD

**Issue by Prabhashi** [wso2/product-apim#12824]
### Description:
API Creation using WSDL File/Archive not working.

### Steps to reproduce:

- Start the APIM server.
- Create a new SOAP API and attach the WSDL and xsd files as zip files.
- Select "Generate REST APIs"
- Click on "Start creating"
- Check the logs and you will be able to see following errors.
```
ERROR {org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor} -  Error occurred while finding element TransactionDetailsTypein given document {org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor}
; Line#: 1; Column#: -1
net.sf.saxon.trans.XPathException: Finding root of tree: the context item is undefined
	at net.sf.saxon.expr.Expression.dynamicError(Expression.java:1036)
	at net.sf.saxon.expr.RootExpression.getNode(RootExpression.java:77)
	at net.sf.saxon.expr.SingleNodeExpression.evaluateItem(SingleNodeExpression.java:138)
	at net.sf.saxon.expr.SimpleStepExpression.iterate(SimpleStepExpression.java:72)
	at net.sf.saxon.expr.FilterExpression.iterate(FilterExpression.java:1119)
	at net.sf.saxon.xpath.XPathExpressionImpl.rawIterator(XPathExpressionImpl.java:206)
	at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:363)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.findFirstElementByName_aroundBody10(WSDL11SOAPOperationExtractor.java:385)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.findFirstElementByName(WSDL11SOAPOperationExtractor.java:380)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.readExtensionModel_aroundBody6(WSDL11SOAPOperationExtractor.java:361)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.readExtensionModel(WSDL11SOAPOperationExtractor.java:327)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.generateSwaggerModelForComplexType_aroundBody4(WSDL11SOAPOperationExtractor.java:308)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.generateSwaggerModelForComplexType(WSDL11SOAPOperationExtractor.java:290)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.traverseTypeElement_aroundBody2(WSDL11SOAPOperationExtractor.java:262)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.traverseTypeElement(WSDL11SOAPOperationExtractor.java:250)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.traverseTypeElement_aroundBody2(WSDL11SOAPOperationExtractor.java:274)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.traverseTypeElement(WSDL11SOAPOperationExtractor.java:250)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.traverseTypeElement_aroundBody2(WSDL11SOAPOperationExtractor.java:274)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.traverseTypeElement(WSDL11SOAPOperationExtractor.java:250)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.traverseTypeElement_aroundBody2(WSDL11SOAPOperationExtractor.java:274)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.traverseTypeElement(WSDL11SOAPOperationExtractor.java:250)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.init_aroundBody0(WSDL11SOAPOperationExtractor.java:227)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.init(WSDL11SOAPOperationExtractor.java:147)
	at org.wso2.carbon.apimgt.impl.soaptorest.util.SOAPOperationBindingUtils.getWSDLProcessor_aroundBody6(SOAPOperationBindingUtils.java:389)
	at org.wso2.carbon.apimgt.impl.soaptorest.util.SOAPOperationBindingUtils.getWSDLProcessor(SOAPOperationBindingUtils.java:384)
	at org.wso2.carbon.apimgt.impl.soaptorest.util.SOAPOperationBindingUtils.getSoapOperationMapping_aroundBody0(SOAPOperationBindingUtils.java:114)
	at org.wso2.carbon.apimgt.impl.soaptorest.util.SOAPOperationBindingUtils.getSoapOperationMapping(SOAPOperationBindingUtils.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0._c_anonymous_6(/publisher/site/blocks/item-design/ajax/add.jag:232)
	at org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0.call(/publisher/site/blocks/item-design/ajax/add.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
	at org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0._c_script_0(/publisher/site/blocks/item-design/ajax/add.jag:59)
	at org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0.call(/publisher/site/blocks/item-design/ajax/add.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0.call(/publisher/site/blocks/item-design/ajax/add.jag)
	at org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0.exec(/publisher/site/blocks/item-design/ajax/add.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doPost(JaggeryServlet.java:29)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:742)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:484)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:65)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1201)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1782)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1741)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
--------------- linked to ------------------
javax.xml.xpath.XPathExpressionException: net.sf.saxon.trans.XPathException: Finding root of tree: the context item is undefined
	at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:371)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.findFirstElementByName_aroundBody10(WSDL11SOAPOperationExtractor.java:385)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.findFirstElementByName(WSDL11SOAPOperationExtractor.java:380)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.readExtensionModel_aroundBody6(WSDL11SOAPOperationExtractor.java:361)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.readExtensionModel(WSDL11SOAPOperationExtractor.java:327)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.generateSwaggerModelForComplexType_aroundBody4(WSDL11SOAPOperationExtractor.java:308)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.generateSwaggerModelForComplexType(WSDL11SOAPOperationExtractor.java:290)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.traverseTypeElement_aroundBody2(WSDL11SOAPOperationExtractor.java:262)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.traverseTypeElement(WSDL11SOAPOperationExtractor.java:250)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.traverseTypeElement_aroundBody2(WSDL11SOAPOperationExtractor.java:274)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.traverseTypeElement(WSDL11SOAPOperationExtractor.java:250)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.traverseTypeElement_aroundBody2(WSDL11SOAPOperationExtractor.java:274)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.traverseTypeElement(WSDL11SOAPOperationExtractor.java:250)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.traverseTypeElement_aroundBody2(WSDL11SOAPOperationExtractor.java:274)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.traverseTypeElement(WSDL11SOAPOperationExtractor.java:250)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.init_aroundBody0(WSDL11SOAPOperationExtractor.java:227)
	at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.init(WSDL11SOAPOperationExtractor.java:147)
	at org.wso2.carbon.apimgt.impl.soaptorest.util.SOAPOperationBindingUtils.getWSDLProcessor_aroundBody6(SOAPOperationBindingUtils.java:389)
	at org.wso2.carbon.apimgt.impl.soaptorest.util.SOAPOperationBindingUtils.getWSDLProcessor(SOAPOperationBindingUtils.java:384)
	at org.wso2.carbon.apimgt.impl.soaptorest.util.SOAPOperationBindingUtils.getSoapOperationMapping_aroundBody0(SOAPOperationBindingUtils.java:114)
	at org.wso2.carbon.apimgt.impl.soaptorest.util.SOAPOperationBindingUtils.getSoapOperationMapping(SOAPOperationBindingUtils.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0._c_anonymous_6(/publisher/site/blocks/item-design/ajax/add.jag:232)
	at org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0.call(/publisher/site/blocks/item-design/ajax/add.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
	at org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0._c_script_0(/publisher/site/blocks/item-design/ajax/add.jag:59)
	at org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0.call(/publisher/site/blocks/item-design/ajax/add.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0.call(/publisher/site/blocks/item-design/ajax/add.jag)
	at org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0.exec(/publisher/site/blocks/item-design/ajax/add.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doPost(JaggeryServlet.java:29)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:742)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:484)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:65)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1201)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1782)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1741)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: net.sf.saxon.trans.XPathException: Finding root of tree: the context item is undefined
	at net.sf.saxon.expr.Expression.dynamicError(Expression.java:1036)
	at net.sf.saxon.expr.RootExpression.getNode(RootExpression.java:77)
	at net.sf.saxon.expr.SingleNodeExpression.evaluateItem(SingleNodeExpression.java:138)
	at net.sf.saxon.expr.SimpleStepExpression.iterate(SimpleStepExpression.java:72)
	at net.sf.saxon.expr.FilterExpression.iterate(FilterExpression.java:1119)
	at net.sf.saxon.xpath.XPathExpressionImpl.rawIterator(XPathExpressionImpl.java:206)
	at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:363)
	... 85 more
TID: [-1234] [] [2022-03-30 11:42:42,216]  WARN {org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor} -  Couldn't find element TransactionDetailsTypefrom namespace http://ws.arcot.com/WebFortCommonAPI/7.0/xsd {org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor}
```
The issue can be seen when your WSDLs or XSD files have following elements.

- <xsd:choice> element
- <xs:extension> referring to an external XSD file 

For the <xsd:choice>, This issue has already fixed in APIM3.2[1] and we need to back-port the fix.
The <xs:extension> related issue need a fix too(The aforementioned issue can be seen for APIM. 3.2 and 4.0 as well).

[1] https://github.com/wso2/product-apim/issues/11288

### Affected Product Version:
APIM 2.6 U2 80

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by HiranyaKavishani** [comment]
Closing the issue as per above commit
