### ISSUE TITLE
[3.0.0] Calling UserInfo API with Open Id Access Token fails after upgrading Spring jars to 5.3.x

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#12829]
### Description:
After upgrading the Spring jars to 5.3.x, an integration test () was failing with the below log in APIM 3.0.0.

```
INFO: =================== Running the test method org.wso2.am.integration.tests.token.OpenIDTokenAPITestCase.testCallUserInfoApiWithOpenIdAccessToken ===================
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: [2022-04-02 11:02:45,640] ERROR - [OAuth2Endpoints] Servlet.service() for servlet [OAuth2Endpoints] in context with path [/oauth2] threw exception
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: org.apache.cxf.interceptor.Fault: org/wso2/carbon/identity/oauth2/internal/OAuth2ServiceComponentHolder
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:162) ~[cxf-core-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:128) ~[cxf-core-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193) ~[cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103) ~[cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[cxf-core-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[cxf-core-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) ~[cxf-core-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[cxf-core-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) ~[cxf-rt-transports-http-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[cxf-rt-transports-http-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[cxf-rt-transports-http-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[cxf-rt-transports-http-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216) ~[cxf-rt-transports-http-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301) ~[cxf-rt-transports-http-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:225) ~[cxf-rt-transports-http-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) ~[tomcat-servlet-api_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276) ~[cxf-rt-transports-http-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.wso2.carbon.webapp.mgt.filter.AuthorizationHeaderFilter.doFilter(AuthorizationHeaderFilter.java:131) ~[org.wso2.carbon.webapp.mgt_4.9.11.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53) ~[org.wso2.carbon.ui_4.5.1.16.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) ~[tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80) [org.wso2.carbon.identity.context.rewrite.valve_1.3.6.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100) [org.wso2.carbon.identity.authz.valve_1.3.6.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74) [org.wso2.carbon.identity.auth.valve_1.3.6.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:116) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726) [tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.22.wso2v1.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: Caused by: java.lang.NoClassDefFoundError: org/wso2/carbon/identity/oauth2/internal/OAuth2ServiceComponentHolder
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.wso2.carbon.identity.oauth.endpoint.util.ClaimUtil.getServiceProvider(ClaimUtil.java:293) ~[classes/:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.wso2.carbon.identity.oauth.endpoint.util.ClaimUtil.getClaimsFromUserStore(ClaimUtil.java:130) ~[classes/:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.wso2.carbon.identity.oauth.endpoint.util.ClaimUtil.getUserClaimsUsingTokenResponse(ClaimUtil.java:87) ~[classes/:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.wso2.carbon.identity.oauth.endpoint.user.impl.UserInfoJSONResponseBuilder.retrieveUserClaims(UserInfoJSONResponseBuilder.java:37) ~[classes/:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.wso2.carbon.identity.openidconnect.AbstractUserInfoResponseBuilder.getResponseString(AbstractUserInfoResponseBuilder.java:68) ~[org.wso2.carbon.identity.oauth_6.2.28.8.jar:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.wso2.carbon.identity.oauth.endpoint.user.OpenIDConnectUserEndpoint.getUserClaims(OpenIDConnectUserEndpoint.java:77) ~[classes/:?]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[cxf-core-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[cxf-core-3.2.8.jar:3.2.8]
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader run
INFO: 	... 55 more
Apr 02, 2022 11:02:45 AM org.wso2.carbon.automation.engine.testlisteners.TestManagerListener onTestFailure
INFO: =================== On test failure org.wso2.am.integration.tests.token.OpenIDTokenAPITestCase.testCallUserInfoApiWithOpenIdAccessToken ===================
```

The error trace contain NoClassDefFound error (org/wso2/carbon/identity/oauth2/internal/OAuth2ServiceComponentHolder)
The ClaimUtil.java class resides in org.wso2.carbon.identity.oauth.endpoint. It uses a method named getServiceProvider() inside that class, and that method uses OAuth2ServiceComponentHolder which is in the package org.wso2.carbon.identity.oauth2.internal. When this package was not getting packed in the product, the above error occurs.
Hence, this should be fixed by removing this dependency between these two packages. We can use an existing method that resides in the org.wso2.carbon.identity.oauth OAuth2Util.java for this task.

**Comment by wasuradananjith** [comment]
Closing since the PRs sent to the branches U2, WUM and master.
