### ISSUE TITLE
Error while trying to export a tenant API with mediation policy.

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/product-apim#12830]
### Description:

There is an error while trying to export a tenant API with mediation policy , where the  super tenant domain is always passed to  ExportUtils.addOperationPoliciesToArchive() instead of the real tenant domain of the API which is passed by the organization parameter.

Caused by: org.wso2.carbon.apimgt.api.APIManagementException: Error while loading medation policies
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.loadMediationPoliciesToAPI_aroundBody84(APIProviderImpl.java:2067) ~[org.wso2.carbon.apimgt.impl_9.20.74.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.loadMediationPoliciesToAPI(APIProviderImpl.java:1955) ~[org.wso2.carbon.apimgt.impl_9.20.74.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.loadMediationPoliciesToAPI(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_9.20.74.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ExportUtils.addOperationPoliciesToArchive(ExportUtils.java:664) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.20.74.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ExportUtils.exportApi(ExportUtils.java:215) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.20.74.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.ImportExportAPIServiceImpl.exportAPI(ImportExportAPIServiceImpl.java:118) ~[?:?]
	at org.wso2.carbon.apimgt.migration.client.MigrateFrom320.addAPIRevision(MigrateFrom320.java:491) ~[org.wso2.carbon.apimgt.migrate.client-4.1.0.8-SNAPSHOT.jar:?]
	... 47 more
Caused by: org.wso2.carbon.apimgt.persistence.exceptions.MediationPolicyPersistenceException: API not foud 
	at org.wso2.carbon.apimgt.persistence.RegistryPersistenceImpl.getAllMediationPolicies(RegistryPersistenceImpl.java:2664) ~[org.wso2.carbon.apimgt.persistence_9.20.74.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.loadMediationPoliciesToAPI_aroundBody84(APIProviderImpl.java:1962) ~[org.wso2.carbon.apimgt.impl_9.20.74.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.loadMediationPoliciesToAPI(APIProviderImpl.java:1955) ~[org.wso2.carbon.apimgt.impl_9.20.74.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.loadMediationPoliciesToAPI(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_9.20.74.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ExportUtils.addOperationPoliciesToArchive(ExportUtils.java:664) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.20.74.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ExportUtils.exportApi(ExportUtils.java:215) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.20.74.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.ImportExportAPIServiceImpl.exportAPI(ImportExportAPIServiceImpl.java:118) ~[?:?]
	at org.wso2.carbon.apimgt.migration.client.MigrateFrom320.addAPIRevision(MigrateFrom320.java:491) ~[org.wso2.carbon.apimgt.migrate.client-4.1.0.8-SNAPSHOT.jar:?]

**Comment by shnrndk** [comment]
This issue wasn't reproduced.

**Comment by thisaltennakoon** [comment]
The following steps have been followed to reproduce this issue.

- Logged in to the publisher portal using tenant admin
- Created the sample API(PizzaShackAPI)
- Added Policies for that
- Exported the PizzaShackAPI using the apictl
- Deleted the PizzaShackAPI using the UI
- Again, Imported the PizzaShackAPI using the apictl

**This issue wasn't reproduced.**

Also, ExportUtils.addOperationPoliciesToArchive() was debugged, and the correct tenant domain was assigned.
