### ISSUE TITLE
Errors in editing OpenID Connect Configuration when IS-KM is configured

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim#12860]
### Description:

- $Subject

### Steps to reproduce:

This issue is reproducible with APIM 3.0.0 and IS-KM 5.9.0 setup, plugged Read/Write LDAP as a secondary user store.

After this fix  https://github.com/wso2/product-apim/issues/9455 when navigate to` Inbound Authentication Configuration --> OAuth/OpenID Connect Configuration --> Edit` error is popped in logs.

```
TID: [-1234] [] [2022-03-16 18:18:42,617] [5693589b-6be4-448d-ae3a-e45c3f8878b6] ERROR {org.wso2.carbon.identity.oauth.OAuthUtil} - Error while retrieving the app information by app name: Member_VitalityMembers_DMTestApp_PRODUCTION
TID: [-1234] [] [2022-03-16 18:18:42,660] [5693589b-6be4-448d-ae3a-e45c3f8878b6] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/].[bridgeservlet]} - Servlet.service() for servlet [bridgeservlet] threw exception java.lang.NullPointerException
	at org.apache.jsp.oauth.edit_jsp._jspService(edit_jsp.java:779)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:467)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:378)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:326)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:207)
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.wso2.carbon.tomcat.ext.servlet.Delegat
```

### Affected Product Version:

- APIM 3.0.0

**Comment by Sarangan0219** [comment]
Closing this as this is not reproducible in master
