### ISSUE TITLE
Java NullPointer Exception -> when hitting a http://api/rsources/5* 

### ISSUE THREAD

**Issue by felixbecker** [wso2/product-apim#1328]
Hi,

I am not sure if this is the right issue tracker because I acounter a strange behavior which I could not resolve or find any other useful information. We are running wso2 1.1.0.

A customer accessed one of the API's with an asterisk at  the end (http://api/rsources/5*) the same applies also for the bang (!) at the end. He received the famous `0 Contant` message in Swagger Console within the api mgmt.

It looks like the swagger console executes a preflight OPTIONS request to call to a wild card (*).

In the log file I found following Exception that this case is not handled gracefully.

Is this something other folks have encountered. Is this a configuration issue or what would be the best practise to prevend this.

`Java NullPointer Exception im Log-File

TID: [-1234] [] [2017-01-25 09:12:42,714] ERROR {org.apache.synapse.transport.passthru.ServerWorker} - Error processing OPTIONS reguest for : /fasta/v1/stations/7*. Error detail: null. {org.apache.synapse.transport.passthru.ServerWorker}
java.lang.NullPointerException
at org.apache.synapse.transport.passthru.Pipe$ByteBufferInputStream.waitForData(Pipe.java:418)
at org.apache.synapse.transport.passthru.Pipe$ByteBufferInputStream.read(Pipe.java:390)
at java.io.InputStream.read(InputStream.java:101)
at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
at org.apache.synapse.transport.passthru.util.RelayUtils.consumeAndDiscardMessage(RelayUtils.java:300)
at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleAuthFailure(APIAuthenticationHandler.java:196)
at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest(APIAuthenticationHandler.java:161)
at org.apache.synapse.rest.API.process(API.java:322)
at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:86)
at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:65)
at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:295)
at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:83)
at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:317)
at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:149)
at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)`

Any help would be much appreciated...

Best 
Felix

**Comment by harsha89** [comment]
Please check with 2.1.o and reopen the issue
