### ISSUE TITLE
API Manager v 2.1.0 - WSO2Registry error followed by too many connections exception

### ISSUE THREAD

**Issue by nawaz2013** [wso2/product-apim#1465]
Hi,

First of all i would like to congratulate your team for this enormouse platform.

I am using the API Manager version 2.1.0 and and trying to analyze it for production deployment.
In this process I have performed stress api testing on an instance of APi Manager ver 2.1.0 and discovered a memory leak[1] with an exception about too many connection. It seems that at some point of time within some components, the database connections are not closed properly resulting in following exception[1]. This is my perception, then please investigate better by following the steps below.

**Operating System** : Windows 10 Pro, installed memory 16GB, Intel(R) Core(TM)i7-3740QM CPU @2.70 GHz

**Steps to reproduce.**

1. Start an instance of APi manager 2.1.0 (using the configurations in attached zip file api-manager.xml, master-datasources.xml). I downloaded WS02 API manager v 2.1.0 from <http://wso2.com/api-management/>

2. I am using Mysql database using driver (mysql-connector-java-5.1.42.jar) copied in components/lib folder.

3. I created WorldBank - 1.0.0 API - GET (/countries/{code}) following the tutorial provider by publisher component.

4. I have created apache-jmeter ver 3.2 test file (WorlBankAPITest.jmx, attached) to perform load testing.

5. The test worked fine until 61793 samples before throwing exception in [1].

Please let me know if something is unclear while trying to reproduce the issue.

Best regards

[1]

[2017-07-25 12:09:18,256] ERROR - WSO2Registry Error while fetching the resource gov:/apimgt/statistics/ga-config.xml
org.wso2.carbon.registry.core.exceptions.RegistryException: Failed to start new registry transaction.
        at org.wso2.carbon.registry.core.jdbc.dataaccess.JDBCTransactionManager.beginTransaction(JDBCTransactionManager.java:97)
        at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.beginTransaction(EmbeddedRegistry.java:443)
        at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.resourceExists(EmbeddedRegistry.java:631)
        at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.resourceExists(CacheBackedRegistry.java:376)
        at org.wso2.carbon.registry.core.session.UserRegistry.resourceExistsInternal(UserRegistry.java:774)
        at org.wso2.carbon.registry.core.session.UserRegistry.access$800(UserRegistry.java:61)
        at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:757)
        at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:754)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.wso2.carbon.registry.core.session.UserRegistry.resourceExists(UserRegistry.java:754)
        at org.wso2.carbon.mediation.registry.WSO2Registry.getResource(WSO2Registry.java:599)
        at org.wso2.carbon.mediation.registry.WSO2Registry.getRegistryEntry(WSO2Registry.java:437)
        at org.apache.synapse.registry.AbstractRegistry.getResource(AbstractRegistry.java:94)
        at org.apache.synapse.config.SynapseConfiguration.getEntry(SynapseConfiguration.java:837)
        at org.apache.synapse.core.axis2.Axis2MessageContext.getEntry(Axis2MessageContext.java:259)
        at org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtGoogleAnalyticsTrackingHandler.handleRequest(APIMgtGoogleAnalyticsTrackingHandler.java:83)
        at org.apache.synapse.rest.API.process(API.java:325)
        at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:90)
        at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
        at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:304)
        at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:78)
        at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
        at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:325)
        at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Too many connections
        at sun.reflect.GeneratedConstructorAccessor183.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
        at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2194)
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2225)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2024)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
        at sun.reflect.GeneratedConstructorAccessor180.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
        at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:278)
        at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:182)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:701)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:635)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:188)
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:128)
        at org.wso2.carbon.registry.core.jdbc.dataaccess.JDBCTransactionManager.beginTransaction(JDBCTransactionManager.java:80)

[1.zip](https://github.com/wso2/product-apim/files/1172907/1.zip)

**Comment by harsha89** [comment]
We have done fixes on this are please try with the latest branches. Should be available if we release 2.1.x. Currently team is working on C5 bsed product
