### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-apim#1515]
As of now only IPv4 support is available in APIM. This should be extended to support to IPv6 also.

**Comment by isuruw** [comment]
@dinusha92 @nuwand @sanjeewa-malalgoda will this be included in APIM 3.0.0 ?

**Comment by phavekes** [comment]
ipv6 should be supported in the next update.

**Comment by leibarra** [comment]
was ipv6 included in release 3.0.0?

**Comment by NilooAbz** [comment]
I am using wso2 am-2.6.0 and got this error again:
java.lang.NumberFormatException: For input string: "1:61014"
at java.lang.Long.parseLong(Long.java:589)
org.wso2.carbon.apimgt.impl.utils.APIUtil.ipToLong()
is this still because of IPv6?

**Comment by storm367** [comment]
> was ipv6 included in release 3.0.0?

This does not seem to be fixed in 3.0.0 release. Still seeing below error while attempting to connect to published API from Postman (Using https this issue does not allow the API to be invoked even, but with http connection the API is invoked and still throws this error):

Exception in thread "pool-57-thread-13" java.lang.NumberFormatException: For input string: "0:0:0:0:0:0:0:1"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:589)
        at java.lang.Long.parseLong(Long.java:631)
        at org.wso2.carbon.apimgt.impl.utils.APIUtil.ipToLong_aroundBody512(APIUtil.java:7851)
        at org.wso2.carbon.apimgt.impl.utils.APIUtil.ipToLong(APIUtil.java:7847)
        at org.wso2.carbon.apimgt.gateway.throttling.publisher.DataProcessAndPublishingAgent.run_aroundBody4(DataProcessAndPublishingAgent.java:155)
        at org.wso2.carbon.apimgt.gateway.throttling.publisher.DataProcessAndPublishingAgent.run(DataProcessAndPublishingAgent.java:141)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by chamilaadhi** [comment]
Fixed in the upcoming 3.1.0 release
