### ISSUE TITLE
Can't login to publisher : Error while creating the keys for OAuth application : publisher with wso2apim-3.0.0-m6

### ISSUE THREAD

**Issue by yhilem** [wso2/product-apim#1570]
Hi,

Can't login (admin/admin) to publisher at https://localhost:9292/publisher with wso2apim-3.0.0-m6.

The following exception is thrown.

[2017-09-09 11:06:25,908] INFO {org.wso2.carbon.kernel.internal.CarbonStartupHandler} - WSO2 Carbon Kernel started in 9,787 sec
[2017-09-09 11:07:51,799] ERROR {org.wso2.carbon.kernel.internal.configprovider.ConfigProviderImpl} - configuration doesn't exist for the namespace: wso2.carbon.apimgt.publisher.rest.api in deployment yaml. Hence return null object
[2017-09-09 11:09:11,091] ERROR {org.wso2.carbon.apimgt.rest.api.authenticator.AuthenticatorAPI} - Error while creating the keys for OAuth application : publisher
[2017-09-09 11:09:11,101] ERROR {org.wso2.carbon.apimgt.rest.api.authenticator.AuthenticatorAPI} - Error while creating the keys for OAuth application : publisher org.wso2.carbon.apimgt.core.exception.APIManagementException: Error while creating the keys for OAuth application : publisher
at org.wso2.carbon.apimgt.rest.api.authenticator.AuthenticatorService.createDCRApplication(AuthenticatorService.java:322)
at org.wso2.carbon.apimgt.rest.api.authenticator.AuthenticatorService.getConsumerKeySecret(AuthenticatorService.java:236)
at org.wso2.carbon.apimgt.rest.api.authenticator.AuthenticatorService.getTokens(AuthenticatorService.java:141)
at org.wso2.carbon.apimgt.rest.api.authenticator.AuthenticatorAPI.authenticate(AuthenticatorAPI.java:109)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:132)
at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:139)
at org.wso2.msf4j.internal.MSF4JMessageProcessor.lambda$receive$0(MSF4JMessageProcessor.java:81)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.apimgt.core.exception.KeyManagementException: Error occurred while DCR application creation. Error: invalid_client_metadata. Error Description: Service Provider with name: admin_publisher_Application already registered. Status Code: 400
at org.wso2.carbon.apimgt.core.impl.DefaultKeyManagerImpl.createApplication(DefaultKeyManagerImpl.java:124)
at org.wso2.carbon.apimgt.rest.api.authenticator.AuthenticatorService.createDCRApplication(AuthenticatorService.java:318)
... 13 more

Thanks,
Youcef HILEM

**Comment by anuruddhal** [comment]
This error occurs with wso2is-5.4.0 alpha pack.

**Comment by yhilem** [comment]
Hi

I changed wso2is-5.4.0-alpha to wso2is-5.3.0 and I can now login to  https://localhost:9292/publisher 

Thank you
Youcef HILEM
