### ISSUE TITLE
Exception when using callout mediator which calls an endpoint which returns 204 - No Content 

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#1574]
Steps to reproduce:

1. Create an API with extension sequence which calls an endpoint which returns 204 No Content response using a callout mediator (blocking = false)
2. Subscribe and invoke the API 
3. Below exception can be seen

```
[2017-09-12 11:03:08,472]  INFO - HTTPSender Unable to sendViaPut to url[http://localhost:8080/no-content]
org.apache.axis2.AxisFault: InputStream cannot be NULL.
	at org.apache.axis2.transport.http.AbstractHTTPSender.processResponse(AbstractHTTPSender.java:232)
	at org.apache.axis2.transport.http.HTTPSender.handleResponse(HTTPSender.java:289)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPut(HTTPSender.java:250)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:71)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:451)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:278)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:430)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.sendReceive(BlockingMsgSender.java:300)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.send(BlockingMsgSender.java:211)
	at org.apache.synapse.mediators.builtin.CallMediator.handleBlockingCall(CallMediator.java:137)
	at org.apache.synapse.mediators.builtin.CallMediator.mediate(CallMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.mediate(APIManagerExtensionHandler.java:67)
	at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleRequest(APIManagerExtensionHandler.java:78)
	at org.apache.synapse.rest.API.process(API.java:325)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:90)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:304)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:78)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:325)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:371)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2017-09-12 11:03:08,482]  INFO - LogMediator STATUS = Executing default 'fault' sequence, ERROR_CODE = 401001, ERROR_MESSAGE = InputStream cannot be NULL.
```

**Comment by malinthaprasan** [comment]
The issue is caused by axis2 (https://github.com/wso2/wso2-axis2/issues/123) and already fixed in axis2 master branch. Needs to update axis2 version.

**Comment by chamilaadhi** [comment]
axis2 component updated to latest https://github.com/wso2/product-apim/blob/master/pom.xml#L1218
