### ISSUE TITLE
NPE when broker url is configured wrongly

### ISSUE THREAD

**Issue by lahirus** [wso2/product-apim#1639]
**Description:**
Broker url in jndi.properties file was wrong. We might need to fix NPE.

TID: [-1] [] [2017-09-28 21:46:44,980] ERROR {org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory} -  Error acquiring a Connection from the JMS CF : jmsEventPublisher using properties : {transport.jms.ConcurrentPublishers=allow, java.naming.provider.url=repository/conf/jndi.properties, java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory, transport.jms.DestinationType=topic, transport.jms.ConnectionFactoryJNDIName=TopicConnectionFactory, transport.jms.Destination=throttleData} {org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory}
org.wso2.carbon.event.output.adapter.core.exception.OutputEventAdapterRuntimeException: Error acquiring a Connection from the JMS CF : jmsEventPublisher using properties : {transport.jms.ConcurrentPublishers=allow, java.naming.provider.url=repository/conf/jndi.properties, java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory, transport.jms.DestinationType=topic, transport.jms.ConnectionFactoryJNDIName=TopicConnectionFactory, transport.jms.Destination=throttleData}
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory.handleException(JMSConnectionFactory.java:197)
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory.createConnection(JMSConnectionFactory.java:278)
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory$PoolableJMSConnectionFactory.makeObject(JMSConnectionFactory.java:356)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory.getConnectionFromPool(JMSConnectionFactory.java:286)
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSMessageSender.send(JMSMessageSender.java:86)
	at org.wso2.carbon.event.output.adapter.jms.JMSEventAdapter$JMSSender.run(JMSEventAdapter.java:284)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.jms.JMSException: Error creating connection: Could not open connection
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:361)
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:40)
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSUtils.createConnection(JMSUtils.java:387)
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory.createConnection(JMSConnectionFactory.java:268)
	... 10 more
Caused by: org.wso2.andes.AMQConnectionFailureException: Could not open connection
	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:486)
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:351)
	... 13 more
Caused by: org.wso2.andes.transport.TransportException: Could not open connection
	at org.wso2.andes.transport.network.mina.MinaNetworkTransport$IoConnectorCreator.connect(MinaNetworkTransport.java:216)
	at org.wso2.andes.transport.network.mina.MinaNetworkTransport.connect(MinaNetworkTransport.java:74)
	at org.wso2.andes.client.AMQConnectionDelegate_8_0.makeBrokerConnection(AMQConnectionDelegate_8_0.java:130)
	at org.wso2.andes.client.AMQConnection$2.run(AMQConnection.java:631)
	at org.wso2.andes.client.AMQConnection$2.run(AMQConnection.java:628)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.andes.client.AMQConnection.makeBrokerConnection(AMQConnection.java:628)
	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:409)
	... 14 more
TID: [-1] [] [2017-09-28 21:46:44,981] ERROR {org.wso2.carbon.event.output.adapter.jms.internal.util.JMSMessageSender} -   {org.wso2.carbon.event.output.adapter.jms.internal.util.JMSMessageSender}
java.lang.NullPointerException
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSMessageSender.send(JMSMessageSender.java:88)
	at org.wso2.carbon.event.output.adapter.jms.JMSEventAdapter$JMSSender.run(JMSEventAdapter.java:284)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Suggested Labels:**
Type/bug

**Suggested Assignees:**

**Affected Product Version:**
2.1.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Configure wrong host/port for broker URL in jndi.properties file

**Related Issues:**

**Comment by fazlan-nazeem** [comment]
The issue seems to be in [1]. jmsConnectionFactory returns a null when it cannot create a connection with the Topic URL. 


[1] https://github.com/wso2/carbon-analytics-common/blob/v5.1.7/components/event-publisher/event-output-adapters/org.wso2.carbon.event.output.adapter.jms/src/main/java/org/wso2/carbon/event/output/adapter/jms/internal/util/JMSMessageSender.java#L86

**Comment by chamilaadhi** [comment]
This is a user configuration issue. If it is configured correctly this issue won't happen. Stack trace contains information to identify the issue `Error creating connection: Could not open connection`
