### ISSUE TITLE
Logs files are filled with this error

### ISSUE THREAD

**Issue by balajisetty** [wso2/product-apim#1645]
I have got API Manager and API Manager Analytics installed with oracle database successfully running. As API's are used, i keep getting following error and entire log file gets filled with it. Not able to make much out of this. After day or two of running, server freezes and have to kill the application. 

Any insights on this error?

ERROR {org.wso2.carbon.metrics.jdbc.reporter.JDBCReporter} -  Error when reporting timers {org.wso2.carbon.metrics.jdbc.reporter.JDBCReporter}
java.sql.BatchUpdateException: Internal Error: Underflow Exception trying to bind 1.3934662705180957E-131
        at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:10070)
        at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:213)
        at org.wso2.carbon.metrics.jdbc.reporter.JDBCReporter.reportTimers(JDBCReporter.java:389)
        at org.wso2.carbon.metrics.jdbc.reporter.JDBCReporter.report(JDBCReporter.java:200)
        at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:162)
        at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:117)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by chamilaadhi** [comment]
One possible reason for this is that there might be a configuration issue in the metrics-datasources.xml file. Please double-check this file. There is a commented out section for oracle specific configuration. please check whether your configuration is similar to the commented out section

**Comment by tharindu1st** [comment]
Metrics in APIM has disabled  and not in use from the 3.x release .
