### ISSUE TITLE
NPE at server startup

### ISSUE THREAD

**Issue by nu1silva** [wso2/product-apim#1664]
**Description:**
NPE thrown when starting up APIM with IS configured as the KM

**Suggested Labels:**
Bug

**Suggested Assignees:**
N/A

**Affected Product Version:**
APIM 530 wum updated.

**OS, DB, other environment details and versions:**    
Ubuntu 14.04, MySQL 5.6 DB and IS 530 as KM

**Steps to reproduce:**
This happens at startup:
```
[2017-11-01 04:43:05,399]  INFO - CarbonEventManagementService Starting polling event receivers
Exception in thread "Timer-4" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 18 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever.retrieveBlockConditionsData(BlockingConditionRetriever.java:96)
	at org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever.loadBlockingConditionsFromWebService(BlockingConditionRetriever.java:110)
	at org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever.run(BlockingConditionRetriever.java:52)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 18 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 9 more
[2017-11-01 04:43:27,113] ERROR - KeyTemplateRetriever Exception when retrieving throttling data from remote endpoint 
Unexpected character (<) at position 27.
	at org.json.simple.parser.Yylex.yylex(Unknown Source)
	at org.json.simple.parser.JSONParser.nextToken(Unknown Source)
	at org.json.simple.parser.JSONParser.parse(Unknown Source)
	at org.json.simple.parser.JSONParser.parse(Unknown Source)
	at org.json.simple.parser.JSONParser.parse(Unknown Source)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.retrieveKeyTemplateData(KeyTemplateRetriever.java:101)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService(KeyTemplateRetriever.java:117)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run(KeyTemplateRetriever.java:55)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Exception in thread "Timer-5" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
	at java.util.Arrays.asList(Arrays.java:3800)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService(KeyTemplateRetriever.java:117)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run(KeyTemplateRetriever.java:55)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Related Issues:**
N/A

**Comment by chamilaadhi** [comment]
This error happens when the Keymanager node is not fully started when the gateway nodes are started. (KeyTemplateRetriever related webapp is deployed in the keymanager node). Please start it first and then start the keymanager nodes
