### ISSUE TITLE
Hazelcase issue while shutting down instance.

### ISSUE THREAD

**Issue by nu1silva** [wso2/product-apim#1676]
**Description:**
Hazelcase instance not active issue while shutting down the api manager instance. Please note this was shut down after running a load test with gateway cache disabled.

**Suggested Labels:**
Bug

**Suggested Assignees:**
N/A

**Affected Product Version:**
WSO2 APIM 2.1.0 wum updated

**OS, DB, other environment details and versions:**    
Ubuntu 14.04, MySQL 5.6 and IS 5.3.0 as the Key Manager.

**Steps to reproduce:**
1. disable gateway caching.
```
        <EnableGatewayTokenCache>false</EnableGatewayTokenCache>
        <EnableGatewayResourceCache>false</EnableGatewayResourceCache>
```
2. create and api, subscribe and invoke it using 100 concurrent users (used jmeter)
3. shut down the instance.

stack trace:
```
[2017-11-08 10:48:09,426] ERROR - AndesAuthorizationPlugin Error while invoking AndesAuthorizationHandler
org.wso2.carbon.andes.authorization.andes.AndesAuthorizationHandlerException: Error handling delete queue.
	at org.wso2.carbon.andes.authorization.andes.AndesAuthorizationHandler.handleDeleteQueue(AndesAuthorizationHandler.java:657)
	at org.wso2.carbon.andes.authorization.service.andes.AndesAuthorizationPlugin.authorise(AndesAuthorizationPlugin.java:169)
	at org.wso2.andes.server.security.SecurityManager$10.allowed(SecurityManager.java:372)
	at org.wso2.andes.server.security.SecurityManager.checkAllPlugins(SecurityManager.java:238)
	at org.wso2.andes.server.security.SecurityManager.authoriseDelete(SecurityManager.java:368)
	at org.wso2.andes.server.queue.SimpleAMQQueue.delete(SimpleAMQQueue.java:1391)
	at org.wso2.andes.server.queue.SimpleAMQQueue.unregisterSubscription(SimpleAMQQueue.java:505)
	at org.wso2.andes.server.AMQChannel.unsubscribeConsumer(AMQChannel.java:646)
	at org.wso2.andes.server.handler.BasicCancelMethodHandler.methodReceived(BasicCancelMethodHandler.java:63)
	at org.wso2.andes.server.handler.ServerMethodDispatcherImpl.dispatchBasicCancel(ServerMethodDispatcherImpl.java:227)
	at org.wso2.andes.framing.amqp_0_91.BasicCancelBodyImpl.execute(BasicCancelBodyImpl.java:127)
	at org.wso2.andes.server.state.AMQStateManager.methodReceived(AMQStateManager.java:169)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.methodFrameReceived(AMQProtocolEngine.java:388)
	at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:96)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.frameReceived(AMQProtocolEngine.java:333)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.dataBlockReceived(AMQProtocolEngine.java:282)
	at org.wso2.andes.server.protocol.AMQProtocolEngine$1.run(AMQProtocolEngine.java:251)
	at org.wso2.andes.pool.Job.processAll(Job.java:111)
	at org.wso2.andes.pool.Job.run(Job.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while accessing Java Security Manager Privilege Block
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:177)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getRoleListOfUser(AbstractUserStoreManager.java:2689)
	at org.wso2.carbon.andes.authorization.andes.AndesAuthorizationHandler.isAdmin(AndesAuthorizationHandler.java:767)
	at org.wso2.carbon.andes.authorization.andes.AndesAuthorizationHandler.handleDeleteQueue(AndesAuthorizationHandler.java:633)
	... 21 more
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:162)
	... 24 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:165)
	... 26 more
Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.instance.HazelcastInstanceProxy.getOriginal(HazelcastInstanceProxy.java:271)
	at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:75)
	at org.wso2.carbon.core.clustering.hazelcast.HazelcastDistributedMapProvider$DistMap.<init>(HazelcastDistributedMapProvider.java:67)
	at org.wso2.carbon.core.clustering.hazelcast.HazelcastDistributedMapProvider.getMap(HazelcastDistributedMapProvider.java:47)
	at org.wso2.carbon.caching.impl.CacheImpl.<init>(CacheImpl.java:120)
	at org.wso2.carbon.caching.impl.CarbonCacheManager.getCache(CarbonCacheManager.java:121)
	at org.wso2.carbon.user.core.common.UserRolesCache.getUserRolesCache(UserRolesCache.java:66)
	at org.wso2.carbon.user.core.common.UserRolesCache.getRolesListOfUser(UserRolesCache.java:112)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getRoleListOfUserFromCache(AbstractUserStoreManager.java:3609)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getRoleListOfUser(AbstractUserStoreManager.java:2703)
	... 31 more
[2017-11-08 10:48:09,430]  INFO - AMQProtocolEngine Permission denied: tmp_172_17_0_1_34485_1 whilst processing:[BasicCancelBodyImpl: consumerTag=1, nowait=false]
[2017-11-08 10:48:09,430]  INFO - AMQProtocolEngine Closing connection due to: org.wso2.andes.AMQConnectionException: Permission denied: tmp_172_17_0_1_34485_1 [error code 403: access refused]
[2017-11-08 10:48:09,431]  INFO - AMQChannel No consumers to unsubscribe on channel [/192.168.48.63:34485(admin):1]
[2017-11-08 10:48:09,431]  INFO - ConnectionCloseMethodHandler ConnectionClose frame received
[2017-11-08 10:48:09,431]  INFO - FlowControlManager Channel removed (ID: 192.168.48.63:34485)
[2017-11-08 10:48:09,432]  INFO - ConnectionCloseMethodHandler Error :403: access refused:Thread-59
[2017-11-08 10:48:09,432] ERROR - AbstractUserStoreManager Error occurred while accessing Java Security Manager Privilege Block
[2017-11-08 10:48:09,432] ERROR - AMQStateManager No Waiters for error saving as last error:Permission denied: tmp_172_17_0_1_34485_1
[2017-11-08 10:48:09,432] ERROR - JMSTaskManager Error closing JMS consumer
org.wso2.andes.client.JMSAMQException: Error closing consumer: org.wso2.andes.AMQSecurityException: Permission denied: tmp_172_17_0_1_34485_1 [error code 403: access refused]
	at org.wso2.andes.client.BasicMessageConsumer.close(BasicMessageConsumer.java:603)
	at org.wso2.andes.client.BasicMessageConsumer.close(BasicMessageConsumer.java:558)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.closeConsumer(JMSTaskManager.java:909)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:568)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.andes.AMQSecurityException: Permission denied: tmp_172_17_0_1_34485_1 [error code 403: access refused]
	at org.wso2.andes.client.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:85)
	at org.wso2.andes.client.handler.ClientMethodDispatcherImpl.dispatchConnectionClose(ClientMethodDispatcherImpl.java:192)
	at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140)
	at org.wso2.andes.client.state.AMQStateManager.methodReceived(AMQStateManager.java:111)
	at org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:517)
	at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467)
	at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:96)
	at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:468)
	at org.wso2.andes.pool.Job.processAll(Job.java:111)
	at org.wso2.andes.pool.Job.run(Job.java:158)
	... 3 more
[2017-11-08 10:48:09,432] ERROR - AndesAuthorizationPlugin Error while invoking AndesAuthorizationHandler
org.wso2.carbon.andes.authorization.andes.AndesAuthorizationHandlerException: Error handling delete queue.
	at org.wso2.carbon.andes.authorization.andes.AndesAuthorizationHandler.handleDeleteQueue(AndesAuthorizationHandler.java:657)
	at org.wso2.carbon.andes.authorization.service.andes.AndesAuthorizationPlugin.authorise(AndesAuthorizationPlugin.java:169)
	at org.wso2.andes.server.security.SecurityManager$10.allowed(SecurityManager.java:372)
	at org.wso2.andes.server.security.SecurityManager.checkAllPlugins(SecurityManager.java:238)
	at org.wso2.andes.server.security.SecurityManager.authoriseDelete(SecurityManager.java:368)
	at org.wso2.andes.server.queue.SimpleAMQQueue.delete(SimpleAMQQueue.java:1391)
	at org.wso2.andes.server.handler.QueueDeclareHandler$3.doTask(QueueDeclareHandler.java:221)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.closeSession(AMQProtocolEngine.java:759)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.closeConnection(AMQProtocolEngine.java:800)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.methodFrameReceived(AMQProtocolEngine.java:447)
	at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:96)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.frameReceived(AMQProtocolEngine.java:333)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.dataBlockReceived(AMQProtocolEngine.java:282)
	at org.wso2.andes.server.protocol.AMQProtocolEngine$1.run(AMQProtocolEngine.java:251)
	at org.wso2.andes.pool.Job.processAll(Job.java:111)
	at org.wso2.andes.pool.Job.run(Job.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while accessing Java Security Manager Privilege Block
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:177)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getRoleListOfUser(AbstractUserStoreManager.java:2689)
	at org.wso2.carbon.andes.authorization.andes.AndesAuthorizationHandler.isAdmin(AndesAuthorizationHandler.java:767)
	at org.wso2.carbon.andes.authorization.andes.AndesAuthorizationHandler.handleDeleteQueue(AndesAuthorizationHandler.java:633)
	... 18 more
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:162)
	... 21 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:165)
	... 23 more
Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.instance.HazelcastInstanceProxy.getOriginal(HazelcastInstanceProxy.java:271)
	at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:75)
	at org.wso2.carbon.core.clustering.hazelcast.HazelcastDistributedMapProvider$DistMap.<init>(HazelcastDistributedMapProvider.java:67)
	at org.wso2.carbon.core.clustering.hazelcast.HazelcastDistributedMapProvider.getMap(HazelcastDistributedMapProvider.java:47)
	at org.wso2.carbon.caching.impl.CacheImpl.<init>(CacheImpl.java:120)
	at org.wso2.carbon.caching.impl.CarbonCacheManager.getCache(CarbonCacheManager.java:121)
	at org.wso2.carbon.user.core.common.UserRolesCache.getUserRolesCache(UserRolesCache.java:66)
	at org.wso2.carbon.user.core.common.UserRolesCache.getRolesListOfUser(UserRolesCache.java:112)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getRoleListOfUserFromCache(AbstractUserStoreManager.java:3609)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getRoleListOfUser(AbstractUserStoreManager.java:2703)
	... 28 more
[2017-11-08 10:48:09,442] ERROR - AMQProtocolEngine Unexpected exception while processing frame.  Closing connection.
org.wso2.andes.AMQSecurityException: Permission denied: tmp_172_17_0_1_34485_1 [error code 403: access refused]
	at org.wso2.andes.server.queue.SimpleAMQQueue.delete(SimpleAMQQueue.java:1393)
	at org.wso2.andes.server.handler.QueueDeclareHandler$3.doTask(QueueDeclareHandler.java:221)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.closeSession(AMQProtocolEngine.java:759)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.closeConnection(AMQProtocolEngine.java:800)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.methodFrameReceived(AMQProtocolEngine.java:447)
	at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:96)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.frameReceived(AMQProtocolEngine.java:333)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.dataBlockReceived(AMQProtocolEngine.java:282)
	at org.wso2.andes.server.protocol.AMQProtocolEngine$1.run(AMQProtocolEngine.java:251)
	at org.wso2.andes.pool.Job.processAll(Job.java:111)
	at org.wso2.andes.pool.Job.run(Job.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
org.wso2.andes.AMQSecurityException: Permission denied: tmp_172_17_0_1_34485_1 [error code 403: access refused]
	at org.wso2.andes.server.queue.SimpleAMQQueue.delete(SimpleAMQQueue.java:1393)
	at org.wso2.andes.server.handler.QueueDeclareHandler$3.doTask(QueueDeclareHandler.java:221)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.closeSession(AMQProtocolEngine.java:759)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.closeConnection(AMQProtocolEngine.java:800)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.methodFrameReceived(AMQProtocolEngine.java:447)
	at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:96)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.frameReceived(AMQProtocolEngine.java:333)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.dataBlockReceived(AMQProtocolEngine.java:282)
	at org.wso2.andes.server.protocol.AMQProtocolEngine$1.run(AMQProtocolEngine.java:251)
	at org.wso2.andes.pool.Job.processAll(Job.java:111)
	at org.wso2.andes.pool.Job.run(Job.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[2017-11-08 10:48:09,445]  INFO - ConnectionCloseOkMethodHandler Received Connection-close-ok
[2017-11-08 10:48:10,421]  INFO - JMSTaskManager Task manager for jms consumer 1000 shutdown
```

**Related Issues:**

**Comment by chamilaadhi** [comment]
Due to many Hazelcast issues, Current recommendation is to disable Hazelcast clustering in APIM nodes to avoid these kinds of issues. see section 'When to use Hazelcast' section in https://docs.wso2.com/display/AM260/Working+with+Hazelcast+Clustering Unless those are needed you could run the APIM system without HZ
