### ISSUE TITLE
ClassCastException while starting API Manager with slow DB connection

### ISSUE THREAD

**Issue by nu1silva** [wso2/product-apim#1685]
**Description:**
ClassCastException while starting API Manager with slow DB connection

**Suggested Labels:**
Bug

**Suggested Assignees:**
N/A

**Affected Product Version:**
WSO2 APIM 2.1.0 wum updated

**OS, DB, other environment details and versions:**    
Ubuntu 14.04, MySQL 5.6

**Steps to reproduce:**
1. Slow down the database connectivity using wondershaper \[1\]
```
sudo wondershaper eth0 100 100
```
2. start the API Manager.

```
2017-11-10 09:36:26,535]  WARN - AppDeployerServiceComponent Waiting for required OSGi services: org.wso2.carbon.application.deployer.synapse.service.SynapseAppDeployerService,org.wso2.carbon.mediation.initializer.services.SynapseEnvironmentService,
[2017-11-10 09:36:26,860]  WARN - StartupFinalizerServiceComponent Waiting for required OSGi services: org.wso2.carbon.application.deployer.service.CappDeploymentService,org.wso2.carbon.server.admin.common.IServerAdmin,org.wso2.carbon.throttling.agent.ThrottlingAgent,
[2017-11-10 09:37:26,535]  WARN - AppDeployerServiceComponent Waiting for required OSGi services: org.wso2.carbon.application.deployer.synapse.service.SynapseAppDeployerService,org.wso2.carbon.mediation.initializer.services.SynapseEnvironmentService,
[2017-11-10 09:37:26,860]  WARN - StartupFinalizerServiceComponent Waiting for required OSGi services: org.wso2.carbon.application.deployer.service.CappDeploymentService,org.wso2.carbon.server.admin.common.IServerAdmin,org.wso2.carbon.throttling.agent.ThrottlingAgent,
[2017-11-10 09:38:26,535]  WARN - AppDeployerServiceComponent Waiting for required OSGi services: org.wso2.carbon.application.deployer.synapse.service.SynapseAppDeployerService,org.wso2.carbon.mediation.initializer.services.SynapseEnvironmentService,
[2017-11-10 09:38:26,860]  WARN - StartupFinalizerServiceComponent Waiting for required OSGi services: org.wso2.carbon.application.deployer.service.CappDeploymentService,org.wso2.carbon.server.admin.common.IServerAdmin,org.wso2.carbon.throttling.agent.ThrottlingAgent,
Exception in thread "Timer-5" java.lang.ClassCastException: org.json.simple.JSONObject cannot be cast to org.json.simple.JSONArray
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.retrieveKeyTemplateData(KeyTemplateRetriever.java:101)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService(KeyTemplateRetriever.java:117)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run(KeyTemplateRetriever.java:55)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
[2017-11-10 09:39:26,535]  WARN - AppDeployerServiceComponent Waiting for required OSGi services: org.wso2.carbon.application.deployer.synapse.service.SynapseAppDeployerService,org.wso2.carbon.mediation.initializer.services.SynapseEnvironmentService,
```

**Related Issues:**
N/A

\[1\] https://github.com/magnific0/wondershaper

**Comment by evanthika** [comment]
Came across this with a API Manager 2.1.0 vanilla pack as well.

**Comment by chamilaadhi** [comment]
Due to the slow db connection, all the services are not properly started yet. (Waiting for required OSGi services logs). As a result /keyTemplates service is returning an invalid result.

**Comment by isharac** [comment]
Fixed.
