### ISSUE TITLE
[AMHACK][Firefox] unknown_ca SSL exception when invoking an API

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1708]
**Description:**
Unable to invoke an API (ex: PhoneVerification API) from API console in Firefox browser.

**Suggested Labels:**
Bug

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
DB - H2
Browser - Firefox 47.0

**Steps to reproduce:**
1. Create Phone Verification API as mentioned in [1]
2. Sign up to API store and invoke the API

**Observations**
Following certificate exception will appear
```
[2017-11-20 18:34:17,627] ERROR - SourceHandler I/O error: Received fatal alert: unknown_ca
javax.net.ssl.SSLException: Received fatal alert: unknown_ca
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doUnwrap(SSLIOSession.java:245)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.decryptData(SSLIOSession.java:378)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:413)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:119)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	at java.lang.Thread.run(Thread.java:745)
```

**Expected Results**
1. API should be invoked successfully.
2. If there is any solution/workaround exists for a standalone pack, please add that to the documentation. 

[1] https://docs.wso2.com/display/AM210/Quick+Start+Guide

**Comment by anuruddhal** [comment]
Updated the document with steps to resolve the issue. 

The root cause of the issue is because the default pack doesn't ship with a CA signed cert. 
When using the API Console, the web browser sends a https request to the Gateway. Since the cert on the Gateway is not CA signed, the browser will not accept it. To workaround the issue, you need to access the Gateway url (https://<gateway_ip>:8243) on a new tab of the same browser and trust the cert from the browser. This will make the API Console work.

[1]https://docs.wso2.com/display/AM210/Quick+Start+Guide#QuickStartGuide-InvokingtheAPI
