### ISSUE TITLE
[AMHACK] BasicAuthenticationInterceptor Authentication failed error

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#1710]
**Description:**

BasicAuthenticationInterceptor Authentication failed error thrown when restart the server after ciphertool execution.

**Suggested Labels:**
2.1.0

**Suggested Assignees:**

**Affected Product Version:**
APIM-2.1.0

**OS, DB, other environment details and versions:** 
wum pack: wso2am-2.1.0.1510585460470.zip
Oracle 12c jdbc   

**Steps to reproduce:**
- Do relevant configs changes for env
- Configure Email as username changes; note that changes as per [1] has been done
- Up the server => Server up and running succeed
- Login success
- Stop the server 
- Enable "EnableSecureVault" to encrypt passwords; followed doc on [2]
- Run the ciphertool.sh => It was succeed and passwords are encrypted
- Start the server => Observed the error on [3]
Note that login to server again is succeed.

[1] [https://wso2.org/jira/browse/APIMANAGER-4987?focusedCommentId=122956&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-122956]
[2] https://docs.wso2.com/display/AM210/Encrypting+Secure+Endpoint+Passwords
[3] 
`[2017-11-20 19:41:10,018] ERROR - BasicAuthenticationInterceptor Authentication failed. Please check your username/password
[2017-11-20 19:41:10,018] ERROR - BasicAuthenticationInterceptor Authentication failed. Please check your username/password
Exception in thread "Timer-5" java.lang.ClassCastException: org.json.simple.JSONObject cannot be cast to org.json.simple.JSONArray
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.retrieveKeyTemplateData(KeyTemplateRetriever.java:101)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService(KeyTemplateRetriever.java:117)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run(KeyTemplateRetriever.java:55)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
`

**Related Issues:**

**Comment by kavithasub** [comment]
Hi,
The above error has been resolved by adding newly changed admin password value to cipher-text.properties before run the ciphertool.sh for this scenario. Raised a doc jira on [1].
Though I want to keep open this issue since I could login to console/pub/store with the above issue and still I couldn't figure out that why/how login was success. So can you please justify it?

[1] [https://wso2.org/jira/browse/DOCUMENTATION-6621]

**Comment by chamilaadhi** [comment]
You were able to login because you provided the username/password in the login screen. above error happens when APIM gateway does a rest api call to the /keyTemplate endpoint with predefined credentials.
