### ISSUE TITLE
[AMHACK] Unable to configure ip based throttling with a valid IP belongs to IPv6

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1758]
**Description:**
Unable to add IP-based throttling with a valid IP belongs to IPv6

**Suggested Labels:**
Bug
IP based Throttling

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
Ubuntu 15.10
JDK - jdk1.8.0_66
DB - H2
Browser - Chrome Version 58.0.3029.96 (64-bit)

**Steps to reproduce:**
1. Log in to admin console
2. Go to Throttling policies -> Advanced throttling
3. Add a tier with ip based throttling enabled
4. Enter a valid IP belong to IPv6 (ex: 2001:0db8:85a3:0000:0000:8a2e:0370:7334 )

**Observations**
1. Unable to create an IP based throttling policy with valid IPv6 based ip address

![ipv6](https://user-images.githubusercontent.com/14962228/33208747-cbd50c32-d138-11e7-826e-c12ee6af9476.png)

```
[2017-11-24 16:56:08,214] ERROR - ThrottlePolicyTemplateBuilder Velocity Error
java.lang.NumberFormatException: For input string: "2001:0db8:85a3:0000:0000:8a2e:0370:7334"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.wso2.carbon.apimgt.api.model.policy.IPCondition.ipToLong(IPCondition.java:65)
	at org.wso2.carbon.apimgt.api.model.policy.IPCondition.getCondition(IPCondition.java:77)
	at org.wso2.carbon.apimgt.impl.template.ThrottlePolicyTemplateBuilder.getPolicyCondition(ThrottlePolicyTemplateBuilder.java:388)
	at org.wso2.carbon.apimgt.impl.template.ThrottlePolicyTemplateBuilder.getThrottlePolicyForAPILevel(ThrottlePolicyTemplateBuilder.java:114)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addPolicy(APIProviderImpl.java:4408)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.admin.modules.policy.c2._c_anonymous_1(/admin/modules/policy/apiPolicy.jag:17)
	at org.jaggeryjs.rhino.admin.modules.policy.c2.call(/admin/modules/policy/apiPolicy.jag)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.admin.modules.policy.c0._c_anonymous_12(/admin/modules/policy/module.jag:46)
	at org.jaggeryjs.rhino.admin.modules.policy.c0.call(/admin/modules/policy/module.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.admin.site.blocks.policy.resource.policy_add.ajax.c0._c_anonymous_1(/admin/site/blocks/policy/resource/policy-add/ajax/policy-operations.jag:28)
	at org.jaggeryjs.rhino.admin.site.blocks.policy.resource.policy_add.ajax.c0.call(/admin/site/blocks/policy/resource/policy-add/ajax/policy-operations.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
	at org.jaggeryjs.rhino.admin.site.blocks.policy.resource.policy_add.ajax.c0._c_script_0(/admin/site/blocks/policy/resource/policy-add/ajax/policy-operations.jag:5)
	at org.jaggeryjs.rhino.admin.site.blocks.policy.resource.policy_add.ajax.c0.call(/admin/site/blocks/policy/resource/policy-add/ajax/policy-operations.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.admin.site.blocks.policy.resource.policy_add.ajax.c0.call(/admin/site/blocks/policy/resource/policy-add/ajax/policy-operations.jag)
	at org.jaggeryjs.rhino.admin.site.blocks.policy.resource.policy_add.ajax.c0.exec(/admin/site/blocks/policy/resource/policy-add/ajax/policy-operations.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doPost(JaggeryServlet.java:29)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:743)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
[2017-11-24 16:56:08,221] ERROR - APIProviderImpl Error while generating policy
org.wso2.carbon.apimgt.impl.template.APITemplateException: Velocity Error
	at org.wso2.carbon.apimgt.impl.template.ThrottlePolicyTemplateBuilder.getThrottlePolicyForAPILevel(ThrottlePolicyTemplateBuilder.java:131)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addPolicy(APIProviderImpl.java:4408)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.admin.modules.policy.c2._c_anonymous_1(/admin/modules/policy/apiPolicy.jag:17)
	at org.jaggeryjs.rhino.admin.modules.policy.c2.call(/admin/modules/policy/apiPolicy.jag)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.admin.modules.policy.c0._c_anonymous_12(/admin/modules/policy/module.jag:46)
	at org.jaggeryjs.rhino.admin.modules.policy.c0.call(/admin/modules/policy/module.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.admin.site.blocks.policy.resource.policy_add.ajax.c0._c_anonymous_1(/admin/site/blocks/policy/resource/policy-add/ajax/policy-operations.jag:28)
	at org.jaggeryjs.rhino.admin.site.blocks.policy.resource.policy_add.ajax.c0.call(/admin/site/blocks/policy/resource/policy-add/ajax/policy-operations.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
	at org.jaggeryjs.rhino.admin.site.blocks.policy.resource.policy_add.ajax.c0._c_script_0(/admin/site/blocks/policy/resource/policy-add/ajax/policy-operations.jag:5)
	at org.jaggeryjs.rhino.admin.site.blocks.policy.resource.policy_add.ajax.c0.call(/admin/site/blocks/policy/resource/policy-add/ajax/policy-operations.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.admin.site.blocks.policy.resource.policy_add.ajax.c0.call(/admin/site/blocks/policy/resource/policy-add/ajax/policy-operations.jag)
	at org.jaggeryjs.rhino.admin.site.blocks.policy.resource.policy_add.ajax.c0.exec(/admin/site/blocks/policy/resource/policy-add/ajax/policy-operations.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doPost(JaggeryServlet.java:29)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:743)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "2001:0db8:85a3:0000:0000:8a2e:0370:7334"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.wso2.carbon.apimgt.api.model.policy.IPCondition.ipToLong(IPCondition.java:65)
	at org.wso2.carbon.apimgt.api.model.policy.IPCondition.getCondition(IPCondition.java:77)
	at org.wso2.carbon.apimgt.impl.template.ThrottlePolicyTemplateBuilder.getPolicyCondition(ThrottlePolicyTemplateBuilder.java:388)
	at org.wso2.carbon.apimgt.impl.template.ThrottlePolicyTemplateBuilder.getThrottlePolicyForAPILevel(ThrottlePolicyTemplateBuilder.java:114)
	... 72 more
[2017-11-24 16:56:08,224] ERROR - apiPolicy:jag Error occurred while saving policy (Cause:org.wso2.carbon.apimgt.api.APIManagementException: Error while generating policy)

```

**Expected Result**
It should be possible to define an IP that belongs to IPv6 for ip based throttling

**Comment by chamilaadhi** [comment]
IPv6 is not supported at the moment. Please refer to https://github.com/wso2/product-apim/issues/1515 for this feature.
