### ISSUE TITLE
SSL Hostname verification failure when logging into the publisher with IS as the AuthManager

### ISSUE THREAD

**Issue by nu1silva** [wso2/product-apim#1859]
**Description:**
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated when trying to authenticate user with IS 5.3.0 instance

**Suggested Labels:**
Bug

**Suggested Assignees:**
N/A

**Affected Product Version:**
APIM 2.1.0
IS as a KM 5.3.0
WUM updated

**OS, DB, other environment details and versions:**    
Ubuntu 14.04
MySQL 5.6

**Steps to reproduce:**
1. Setup API with pattern-3 puppet and IS as the KM [1]
2. Configure nginx with seperate certificates for publisher,store,KM etc.
3. Add the certificates to the client-truststore of all the instances (Publisher,Store,KM)
4. Try login in to the publisher

[1] https://github.com/wso2/puppet-apim

```
TID: [-1234] [] [2017-11-28 05:43:47,637]  INFO {org.wso2.carbon.core.internal.permission.update.PermissionUpdater} -  Permission cache updated for tenant -1234 {org.wso2.carbon.core.internal.permission.update.PermissionUpdater}
TID: [-1234] [] [2017-11-28 05:43:48,009]  INFO {org.apache.axis2.transport.http.HTTPSender} -  Unable to sendViaPost to url[https://km.dev.wso2.org:443/services/AuthenticationAdmin] {org.apache.axis2.transport.http.HTTPSender}
javax.net.ssl.SSLException: hostname in certificate didn't match: <km.dev.wso2.org> != <gw.dev.wso2.org>
        at org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.verifyHostName(SSLProtocolSocketFactory.java:436)
        at org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.verifyHostName(SSLProtocolSocketFactory.java:302)
        at org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.verifyHostName(SSLProtocolSocketFactory.java:273)
        at org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.createSocket(SSLProtocolSocketFactory.java:183)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.axis2.transport.http.AbstractHTTPSender.executeMethod(AbstractHTTPSender.java:682)
        at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:195)
        at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:77)
        at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:451)
        at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:278)
        at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
        at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:430)
        at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225)
        at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
        at org.wso2.carbon.authenticator.stub.AuthenticationAdminStub.login(AuthenticationAdminStub.java:659)
        at org.wso2.carbon.apimgt.hostobjects.APIProviderHostObject.jsFunction_login(APIProviderHostObject.java:267)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
        at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
```

Full log:
[wso2carbon.log](https://github.com/wso2/product-apim/files/1508658/wso2carbon.log)

**Related Issues:**
N/A

**Comment by pubudu538** [comment]
This is not a product issue or a puppet issue. This is a deployment issue.

**Comment by abimarank** [comment]
@nu1silva 

Have you generated KeyStore for all the nodes? CN property belongs to KeyStore. What's the value you have given to CN when you generate KeyStore? Importing public keys to each other's client-truststore don't have any impact on this problem.

**Comment by nu1silva** [comment]
Please see thread in dev@wso2.org "[DEV] hostname in certificate didn't match: <km.dev.wso2.org> != <gw.dev.wso2.org>"

**Comment by chamilaadhi** [comment]
As mentioned in the above mail thread, Issue was resolved by following the steps in this thread http://mail.wso2.org/mailarchive/dev/2017-November/074715.html
