### ISSUE TITLE
[AMHACK] NullPointerException thrown when creating the first forum

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#1886]
**Description:**
Configured apim with analytics following the quick setup [1] and logged in to api store. Created a sample forum and saved it. A null pointer is thrown. ( observed it intermittently in fresh apim + analytics setup that I worked on )

[1] https://docs.wso2.com/display/AM210/Configuring+APIM+Analytics#309a01728f0a42d69613b37e4f5225c3

**Suggested Labels:**
bug

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip
APIM analytics pack wum updated - wso2am-analytics-2.1.0.1511528208814.zip

**OS, DB, other environment details and versions:**    
APIM and analytics quick setup
Ubuntu 14
JDK - jdk1.8.0
DB - h2
Browser - Chrome Version 62.0.3202.62

**Steps to reproduce:**
Create a setup following the quick setup with apim and analytics
Login to apim store
Create a forum ( the first forum)

**Issue**

A null pointer exception is thrown with the below screen.

![500](https://user-images.githubusercontent.com/17248809/33310959-584d02ec-d449-11e7-8a6e-0c0ffbd87fc8.png)

```
[2017-11-28 14:24:50,725] ERROR - topics:jag null
[2017-11-28 14:24:50,746] ERROR - WebAppManager org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (/store/site/blocks/forum/forum-topic/block.jag#34)
org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (/store/site/blocks/forum/forum-topic/block.jag#34)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:743)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (/store/site/blocks/forum/forum-topic/block.jag#34)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.store.site.blocks.forum.forum_topic.c0._c_anonymous_2(/store/site/blocks/forum/forum-topic/block.jag:34)
	at org.jaggeryjs.rhino.store.site.blocks.forum.forum_topic.c0.call(/store/site/blocks/forum/forum-topic/block.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
	at org.jaggeryjs.rhino.store.jagg.c0._c_anonymous_28(/store/jagg/jagg.jag:266)
	at org.jaggeryjs.rhino.store.jagg.c0.call(/store/jagg/jagg.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.store.jagg.c0._c_anonymous_29(/store/jagg/jagg.jag:338)
	at org.jaggeryjs.rhino.store.jagg.c0.call(/store/jagg/jagg.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.store.jagg.c0._c_anonymous_28(/store/jagg/jagg.jag:273)
	at org.jaggeryjs.rhino.store.jagg.c0.call(/store/jagg/jagg.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.store.jagg.c0._c_anonymous_29(/store/jagg/jagg.jag:338)
	at org.jaggeryjs.rhino.store.jagg.c0.call(/store/jagg/jagg.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.store.jagg.c0._c_anonymous_28(/store/jagg/jagg.jag:273)
	at org.jaggeryjs.rhino.store.jagg.c0.call(/store/jagg/jagg.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.store.jagg.c0._c_anonymous_51(/store/jagg/jagg.jag:683)
	at org.jaggeryjs.rhino.store.jagg.c0.call(/store/jagg/jagg.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.store.site.pages.c3._c_anonymous_1(/store/site/pages/forum.jag:50)
	at org.jaggeryjs.rhino.store.site.pages.c3.call(/store/site/pages/forum.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
	at org.jaggeryjs.rhino.store.site.pages.c3._c_script_0(/store/site/pages/forum.jag:47)
	at org.jaggeryjs.rhino.store.site.pages.c3.call(/store/site/pages/forum.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.store.site.pages.c3.call(/store/site/pages/forum.jag)
	at org.jaggeryjs.rhino.store.site.pages.c3.exec(/store/site/pages/forum.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	... 48 more
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.forum.registry.RegistryForumManager.getRating(RegistryForumManager.java:800)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 81 more
```

**Comment by chamilaadhi** [comment]
I was able to get this issue in wso2am-2.1.0+1510928473100 pack. But couldn't observe it in the latest APIM 2.6.0 pack. Seems like it is resolved in the latest version. Please re-open it if you face this in the latest pack
