### ISSUE TITLE
[AMHACK] Error when generating an invoice for the monetized APIs via billing engine sample

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1911]
**Description:**
Failed to generate an invoice from the billing engine sample [1]

[1] https://docs.wso2.com/display/AM210/Enabling+Monetization+of+APIs

**Suggested Labels:**
Bug
APIM Monetization - billing engine sample

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip
APIM analytics - wso2am-analytics-2.1.0.1510935606971.zip

**OS, DB, other environment details and versions:**    
Standalone
Ubuntu 15.10
JDK - jdk1.8.0_66
DB - Postgres 9.6.3
Browser - Chrome Version 58.0.3029.96 (64-bit)
Tomcat version - apache-tomcat-7.0.68

**Steps to reproduce:**
1. Configure the environment as given in [1]
2. Click the 'invoice' button to generate invoice for the API usage

[1] https://docs.wso2.com/display/AM210/Enabling+Monetization+of+APIs

**Observations**
1. Failed to generate invoice due to 
```
HTTP Status 500 - Request processing failed; nested exception is org.springframework.webflow.execution.ActionExecutionException: Exception thrown executing [AnnotatedAction@3fa06082 targetAction = [EvaluateAction@274d6a91 expression = invoiceService.createInvoice(user), resultExpression = viewScope.invoice], attributes = map[[empty]]] in state 'invoiceHome' of flow 'account' -- action execution attributes were 'map[[empty]]'
```

Tomcat Logs and the Application log appeared can be found from TomcatLogs.zip

[TomcatLogs.zip](https://github.com/wso2/product-apim/files/1516814/TomcatLogs.zip)

**Comment by sashikamw** [comment]
Further, I have deployed the billing engine war file as a web application in the APIM server itself. But still facing the same issue

```
10:42:31,140 DEBUG FlowHandlerMapping:108 - Mapping request with URI '/apim-billing-engine-1.2.0/app/account' to flow with id 'account'
10:42:31,141 DEBUG FlowExecutorImpl:161 - Resuming flow execution with key 'e3s2
10:42:31,141 DEBUG SessionBindingConversationManager:67 - Locking conversation 3
10:42:31,141 DEBUG DefaultFlowExecutionRepository:106 - Getting flow execution with key 'e3s2'
10:42:31,141 DEBUG FlowDefinitionRegistryImpl:59 - Getting FlowDefinition with id 'account'
10:42:31,142 DEBUG ConditionalFlowExecutionListenerLoader:87 - Loaded [3] of possible 3 listeners for this execution request for flow 'account', the listeners to attach are list[org.springframework.webflow.persistence.JpaFlowExecutionListener@3258206f, org.springframework.faces.webflow.FlowFacesContextLifecycleListener@15916df3, org.springframework.webflow.security.SecurityFlowExecutionListener@47c88710]
10:42:31,142 DEBUG FlowExecutionImpl:249 - Resuming in org.springframework.webflow.mvc.servlet.MvcExternalContext@2704b069
10:42:31,143 DEBUG Flow:636 - Restoring [FlowVariable@1fa108e6 name = 'uiUtils', valueFactory = [BeanFactoryVariableValueFactory@16f93142 type = UIUtils]]
10:42:31,143 DEBUG Flow:636 - Restoring [FlowVariable@5ba0be20 name = 'plan', valueFactory = [BeanFactoryVariableValueFactory@4c517b8a type = PlanEntity]]
10:42:31,153 DEBUG ViewState:230 - Event 'createInvoice' returned from view [JSFView = '/WEB-INF/flows/account/invoice.xhtml']
10:42:31,153 DEBUG Transition:213 - Executing [Transition@5cf52070 on = createInvoice, to = invoiceHome]
10:42:31,153 DEBUG Transition:221 - Exiting state 'invoice'
10:42:31,154 DEBUG ViewState:189 - Entering state 'invoiceHome' of flow 'account'
10:42:31,155 DEBUG FlowExecutionImpl:419 - Assigned key e3s3
10:42:31,155 DEBUG Transition:230 - Completed transition execution.  As a result, the new state is 'invoiceHome' in flow 'account'
10:42:31,155 DEBUG DefaultFlowExecutionRepository:121 - Putting flow execution '[FlowExecutionImpl@4bd33054 flow = 'account', flowSessions = list[[FlowSessionImpl@4dda5098 flow = 'account', state = 'invoiceHome', scope = map['viewScope' -> map[[empty]], 'uiUtils' -> org.wso2.apim.billing.ui.utils.UIUtils@3179e6f9, 'plan' -> org.wso2.apim.billing.domain.PlanEntity@3a8be8da, 'user' -> org.wso2.apim.billing.domain.UserEntity@b8bc62b]]]]' into repository
10:42:31,156 DEBUG DefaultFlowExecutionRepository:128 - Adding snapshot to group with id 3
10:42:31,156 DEBUG SessionBindingConversationManager:78 - Putting conversation attribute 'scope' with value map['flashScope' -> map['flowRenderResponse' -> true, 'messagesMemento' -> map[[null] -> list[[empty]]]]]
10:42:31,156 DEBUG SessionBindingConversationManager:99 - Unlocking conversation 3
10:42:31,156 DEBUG FlowHandlerAdapter:367 - Sending flow execution redirect to '/apim-billing-engine-1.2.0/app/account?execution=e3s3'
10:42:31,164 DEBUG FlowHandlerMapping:108 - Mapping request with URI '/apim-billing-engine-1.2.0/app/account' to flow with id 'account'
10:42:31,164 DEBUG FlowExecutorImpl:161 - Resuming flow execution with key 'e3s3
10:42:31,164 DEBUG SessionBindingConversationManager:67 - Locking conversation 3
10:42:31,165 DEBUG DefaultFlowExecutionRepository:106 - Getting flow execution with key 'e3s3'
10:42:31,165 DEBUG FlowDefinitionRegistryImpl:59 - Getting FlowDefinition with id 'account'
10:42:31,166 DEBUG ConditionalFlowExecutionListenerLoader:87 - Loaded [3] of possible 3 listeners for this execution request for flow 'account', the listeners to attach are list[org.springframework.webflow.persistence.JpaFlowExecutionListener@3258206f, org.springframework.faces.webflow.FlowFacesContextLifecycleListener@15916df3, org.springframework.webflow.security.SecurityFlowExecutionListener@47c88710]
10:42:31,166 DEBUG FlowExecutionImpl:249 - Resuming in org.springframework.webflow.mvc.servlet.MvcExternalContext@636ddc5b
10:42:31,167 DEBUG Flow:636 - Restoring [FlowVariable@1fa108e6 name = 'uiUtils', valueFactory = [BeanFactoryVariableValueFactory@16f93142 type = UIUtils]]
10:42:31,167 DEBUG Flow:636 - Restoring [FlowVariable@5ba0be20 name = 'plan', valueFactory = [BeanFactoryVariableValueFactory@4c517b8a type = PlanEntity]]
10:42:31,169 DEBUG ViewState:289 - Rendering + [JSFView = '/WEB-INF/flows/account/invoiceHome.xhtml']
10:42:31,170 DEBUG ViewState:290 -   Flash scope = map['flowRenderResponse' -> true]
10:42:31,170 DEBUG ViewState:291 -   Messages = [DefaultMessageContext@4a2e7be3 sourceMessages = map[[null] -> list[[empty]]]]
10:42:31,171 DEBUG ActionExecutor:49 - Executing [EvaluateAction@66d2b53 expression = invoiceService.createInvoice(user), resultExpression = viewScope.invoice]
10:42:31,171 DEBUG AnnotatedAction:142 - Putting action execution attributes map[[empty]]
host https://172.17.0.1:9443/
[2017-12-01 10:42:31,200]  INFO - PermissionUpdater Permission cache updated for tenant -1234
[2017-12-01 10:42:31,220]  INFO - CarbonAuthenticationUtil 'admin@carbon.super [-1234]' logged in at [2017-12-01 10:42:31,220+0530]
{"error" : false}
no subscription for plan: Diamond
Fri Dec 01 10:42:31 IST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
10:42:31,350 DEBUG AnnotatedAction:149 - Clearing action execution attributes map[[empty]]
10:42:31,351 DEBUG FlowExecutionImpl:590 - Attempting to handle [org.springframework.webflow.execution.ActionExecutionException: Exception thrown executing [AnnotatedAction@3ce28706 targetAction = [EvaluateAction@66d2b53 expression = invoiceService.createInvoice(user), resultExpression = viewScope.invoice], attributes = map[[empty]]] in state 'invoiceHome' of flow 'account' -- action execution attributes were 'map[[empty]]'] with root cause [java.lang.IllegalArgumentException: attempt to create create event with null entity]
10:42:31,351 DEBUG FlowExecutionImpl:611 - Rethrowing unhandled flow execution exception
10:42:31,351 DEBUG SessionBindingConversationManager:99 - Unlocking conversation 3
[2017-12-01 10:42:31,352] ERROR - StandardWrapperValve Servlet.service() for servlet [Spring MVC Dispatcher Servlet] in context with path [/apim-billing-engine-1.2.0] threw exception [Request processing failed; nested exception is org.springframework.webflow.execution.ActionExecutionException: Exception thrown executing [AnnotatedAction@3ce28706 targetAction = [EvaluateAction@66d2b53 expression = invoiceService.createInvoice(user), resultExpression = viewScope.invoice], attributes = map[[empty]]] in state 'invoiceHome' of flow 'account' -- action execution attributes were 'map[[empty]]'] with root cause
java.lang.IllegalArgumentException: attempt to create create event with null entity
	at org.hibernate.event.spi.PersistEvent.<init>(PersistEvent.java:44)
	at org.hibernate.event.spi.PersistEvent.<init>(PersistEvent.java:37)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:818)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:822)
	at org.hibernate.ejb.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:865)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:240)
	at com.sun.proxy.$Proxy154.persist(Unknown Source)
	at org.wso2.apim.billing.commons.dao.GenericJpaDao.save(GenericJpaDao.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:309)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy157.save(Unknown Source)
	at org.wso2.apim.billing.services.impl.InvoiceServiceImpl.createInvoice(InvoiceServiceImpl.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:69)
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:84)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:57)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:102)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:97)
	at org.springframework.binding.expression.spel.SpringELExpression.getValue(SpringELExpression.java:84)
	at org.springframework.webflow.action.EvaluateAction.doExecute(EvaluateAction.java:75)
	at org.springframework.webflow.action.AbstractAction.execute(AbstractAction.java:188)
	at org.springframework.webflow.execution.AnnotatedAction.execute(AnnotatedAction.java:145)
	at org.springframework.webflow.execution.ActionExecutor.execute(ActionExecutor.java:51)
	at org.springframework.webflow.engine.ActionList.execute(ActionList.java:155)
	at org.springframework.webflow.engine.ViewState.render(ViewState.java:294)
	at org.springframework.webflow.engine.ViewState.refresh(ViewState.java:243)
	at org.springframework.webflow.engine.ViewState.resume(ViewState.java:221)
	at org.springframework.webflow.engine.Flow.resume(Flow.java:545)
	at org.springframework.webflow.engine.impl.FlowExecutionImpl.resume(FlowExecutionImpl.java:258)
	at org.springframework.webflow.executor.FlowExecutorImpl.resumeExecution(FlowExecutorImpl.java:169)
	at org.springframework.webflow.mvc.servlet.FlowHandlerAdapter.handle(FlowHandlerAdapter.java:183)
	at org.springframework.faces.webflow.JsfFlowHandlerAdapter.handle(JsfFlowHandlerAdapter.java:48)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:183)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sashikamw** [comment]
Need to try this in a private browser to get this work

**Comment by chamilaadhi** [comment]
Hi,
This billing webapp is provided as a sample and there could be limitations and issues with this sample. (as a result this sample is removed from the AM 2.6.0 documentations as well sicne it is not a production-ready sample)

In APIM 3.0.0 we have provided an out of the box configuration support with an actually billing engine. You could follow this feature in https://github.com/wso2/product-apim/issues/4680
