### ISSUE TITLE
Observed error when deploying sample api

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2085]
OS: Ubuntu 16.04
JDK: 1.8.0_144

Steps
1. Loaded api publisher 
2. Logged in using admin/admin
3. Deployed the sample api

Following error message was seen at the console
```
[2018-01-02 10:47:18,981] ERROR {org.wso2.carbon.apimgt.core.impl.APIStoreImpl} - Couldn't retrieve gateway configuration for apiId e4b22bde-e402-4c59-b357-c810c72594c1 org.wso2.carbon.apimgt.core.exception.APIMgtDAOException: Gateway config of API: e4b22bde-e402-4c59-b357-c810c72594c1 does not exist
	at org.wso2.carbon.apimgt.core.dao.impl.ApiDAOImpl.getGatewayConfigOfAPI(ApiDAOImpl.java:1132)
	at org.wso2.carbon.apimgt.core.impl.APIMgtAdminServiceImpl.getAPIGatewayServiceConfig(APIMgtAdminServiceImpl.java:421)
	at org.wso2.carbon.apimgt.rest.api.core.impl.ApisApiServiceImpl.apisApiIdGatewayConfigGet(ApisApiServiceImpl.java:45)
	at org.wso2.carbon.apimgt.rest.api.core.ApisApi.apisApiIdGatewayConfigGet(ApisApi.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:185)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:142)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:245)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.lambda$receive$58(MSF4JMessageProcessor.java:156)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by CrowleyRajapakse** [comment]
not reproducible
