### ISSUE TITLE
Cannot select subscription tier and move forward when creating an api

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2094]
OS: Ubuntu 16.04
JDK: 1.8.0_144
Pack: Milestone 11
Browser: Chrome Version 63.0.3239.108 (Official Build) (64-bit)

**Steps**
1. Logged in to publisher using admin/admin
2. Tried to create an api

After selecting tier when next is clicked following error was observed

```
[2018-01-02 11:47:28,822] ERROR {org.wso2.carbon.apimgt.rest.api.common.impl.OAuth2Authenticator} - Error while validating access token org.wso2.carbon.apimgt.core.exception.KeyManagementException: Token introspection request failed. HTTP error code: 400 Error Response Body: {"error": "Invalid input"}
	at org.wso2.carbon.apimgt.core.impl.DefaultKeyManagerImpl.getTokenMetaData(DefaultKeyManagerImpl.java:372)
	at org.wso2.carbon.apimgt.rest.api.common.impl.OAuth2Authenticator.getValidatedTokenResponse(OAuth2Authenticator.java:336)
	at org.wso2.carbon.apimgt.rest.api.common.impl.OAuth2Authenticator.validateToken(OAuth2Authenticator.java:139)
	at org.wso2.carbon.apimgt.rest.api.common.impl.OAuth2Authenticator.validateTokenAndScopes(OAuth2Authenticator.java:111)
	at org.wso2.carbon.apimgt.rest.api.common.impl.OAuth2Authenticator.authenticate(OAuth2Authenticator.java:91)
	at org.wso2.carbon.apimgt.rest.api.common.interceptors.RESTAPISecurityInterceptor.preCall(RESTAPISecurityInterceptor.java:222)
	at org.wso2.msf4j.Interceptor.interceptRequest(Interceptor.java:65)
	at org.wso2.msf4j.interceptor.InterceptorExecutor.executeRequestInterceptor(InterceptorExecutor.java:321)
	at org.wso2.msf4j.interceptor.InterceptorExecutor.executeGlobalRequestInterceptors(InterceptorExecutor.java:206)
	at org.wso2.msf4j.interceptor.InterceptorExecutor.executeGlobalRequestInterceptors(InterceptorExecutor.java:52)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:177)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:142)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:245)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.lambda$receive$58(MSF4JMessageProcessor.java:156)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

![apim_issues_2](https://user-images.githubusercontent.com/15624590/34482910-13d6d972-efe1-11e7-892f-66d69801c272.png)

**Comment by chamilaadhi** [comment]
This page is refactored in AM 3.0.0 alpha2. This issue is not visible in that version
