### ISSUE TITLE
Problem with admin password with @

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2148]
Changed the default username and password following [1] and since its indicated there to use the URI encoded value, used %40 as indicated in the following config but recieved below error

`connectionfactory.TopicConnectionFactory = amqp://Administrator:Admin%40123@clientid/carbon?brokerlist='tcp://localhost:5672'`

```
[2018-01-04 10:06:19,944]  INFO - AMQConnection Unable to connect to broker at tcp://172.17.0.1:5672
org.wso2.andes.AMQException: Error occurred while establishing a connection 
	at org.wso2.andes.client.AMQConnectionDelegate_8_0.makeBrokerConnection(AMQConnectionDelegate_8_0.java:142)
	at org.wso2.andes.client.AMQConnection$2.run(AMQConnection.java:631)
	at org.wso2.andes.client.AMQConnection$2.run(AMQConnection.java:628)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.andes.client.AMQConnection.makeBrokerConnection(AMQConnection.java:628)
	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:409)
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:351)
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:40)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils.createConnection(JMSUtils.java:391)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSListener.checkJMSConnection(JMSListener.java:137)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSListener.start(JMSListener.java:79)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSListener.run(JMSListener.java:186)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.andes.client.AMQAuthenticationException: not allowed [error code 530: not allowed]
	at org.wso2.andes.client.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:79)
	at org.wso2.andes.client.handler.ClientMethodDispatcherImpl.dispatchConnectionClose(ClientMethodDispatcherImpl.java:192)
	at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140)
	at org.wso2.andes.client.state.AMQStateManager.methodReceived(AMQStateManager.java:111)
	at org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:517)
	at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467)
	at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:96)
	at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:468)
	at org.wso2.andes.pool.Job.processAll(Job.java:111)
	at org.wso2.andes.pool.Job.run(Job.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

```
Is it not possible to use the @ sign at all even with URI encoding?

[1] https://docs.wso2.com/display/AM2xx/Maintaining+Logins+and+Passwords

**Comment by davewoodward** [comment]
@erandidesilva - Did you ever get this resolved?

**Comment by chamindias** [comment]
Quoted from [1]
"...When specifying username in JMS Connection URL, under <JMSConnectionParameters> in <PRODUCT_HOME>/repository/conf/api-manager.xml, "@" characters should be replaced by "!" character..."

![image](https://user-images.githubusercontent.com/8359365/36375606-e1899e66-1595-11e8-8e60-ca2c930a9097.png)

Answered, hence resolving.

[1] https://docs.wso2.com/display/AM2xx/Maintaining+Logins+and+Passwords
