### ISSUE TITLE
Observed an error when restarting the apim server after sometime from a load test done, while connected to apim-analytics

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2235]
**Description:**
Observed an error when restarting the apim server after 5-10mins from a simple load test done.

**Suggested Labels:**
APIM-2.2.0
Type/bug
Priority/high
Severity/Major

**Suggested Assignees:**

**Affected Product Version:**
apim-2.1.0-update4
apim-analytics-2.1.0-update3

**OS, DB, other environment details and versions:**    
apim-analytics configured 

**Steps to reproduce:**
- Did a load test to access an api (with 3000 threads)
- Finish the load completly
- Kept some time to verify stats etc
- Now I restarted the APIM server only => observed below exeption in carbon log

`TID: [-1234] [] [2018-01-05 14:16:07,238]  INFO {org.wso2.andes.server.handler.ChannelOpenHandler} -  Connecting to: carbon {org.wso2.andes.server.handler.ChannelOpenHandler}
TID: [-1234] [] [2018-01-05 14:16:07,509]  INFO {org.wso2.andes.kernel.AndesChannel} -  Channel created (ID: 10.100.7.104:40436) {org.wso2.andes.kernel.AndesChannel}
TID: [-1] [] [2018-01-05 14:16:07,518]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils} -  Cannot locate destination : throttleData {org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils}
TID: [-1] [] [2018-01-05 14:16:07,654] ERROR {org.wso2.andes.server.protocol.AMQProtocolEngine} -  Unexpected exception while processing frame.  Closing connection. {org.wso2.andes.server.protocol.AMQProtocolEngine}
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.putChild(HandlerManager.java:2676)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.putChild(HandlerLifecycleManager.java:476)
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:694)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.put(CacheBackedRegistry.java:591)
	at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:828)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:61)
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:804)
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:801)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:801)
	at org.wso2.carbon.andes.commons.registry.RegistryClient.createQueue(RegistryClient.java:104)
	at org.wso2.carbon.andes.authorization.andes.AndesAuthorizationHandler.registerAndAuthorizeQueue(AndesAuthorizationHandler.java:727)
	at org.wso2.carbon.andes.authorization.andes.AndesAuthorizationHandler.handleCreateQueue(AndesAuthorizationHandler.java:164)
	at org.wso2.carbon.andes.authorization.service.andes.AndesAuthorizationPlugin.authorise(AndesAuthorizationPlugin.java:148)
	at org.wso2.andes.server.security.SecurityManager$9.allowed(SecurityManager.java:361)
	at org.wso2.andes.server.security.SecurityManager.checkAllPlugins(SecurityManager.java:238)
	at org.wso2.andes.server.security.SecurityManager.authoriseCreateQueue(SecurityManager.java:357)
	at org.wso2.andes.server.queue.AMQQueueFactory.createAMQQueueImpl(AMQQueueFactory.java:177)
	at org.wso2.andes.server.queue.AMQQueueFactory.createAMQQueueImpl(AMQQueueFactory.java:138)
	at org.wso2.andes.server.handler.QueueDeclareHandler.createQueue(QueueDeclareHandler.java:209)
	at org.wso2.andes.server.handler.QueueDeclareHandler.methodReceived(QueueDeclareHandler.java:96)
	at org.wso2.andes.server.handler.ServerMethodDispatcherImpl.dispatchQueueDeclare(ServerMethodDispatcherImpl.java:600)
	at org.wso2.andes.framing.amqp_0_91.QueueDeclareBodyImpl.execute(QueueDeclareBodyImpl.java:187)
	at org.wso2.andes.server.state.AMQStateManager.methodReceived(AMQStateManager.java:169)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.methodFrameReceived(AMQProtocolEngine.java:388)
	at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:96)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.frameReceived(AMQProtocolEngine.java:333)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.dataBlockReceived(AMQProtocolEngine.java:282)
	at org.wso2.andes.server.protocol.AMQProtocolEngine$1.run(AMQProtocolEngine.java:251)
	at org.wso2.andes.pool.Job.processAll(Job.java:111)
	at org.wso2.andes.pool.Job.run(Job.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2018-01-05 14:16:07,670] ERROR {org.wso2.andes.client.state.AMQStateManager} -  No Waiters for error saving as last error:Exception thrown against AMQConnection:
Host: 172.18.0.1
Port: 5672
Virtual Host: carbon
Client ID: clientid
Active session count: 1: org.wso2.andes.AMQDisconnectedException: Server closed connection and reconnection not permitted. {org.wso2.andes.client.state.AMQStateManager}
TID: [-1] [] [2018-01-05 14:16:07,671] ERROR {org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager} -  Error creating JMS consumer for Siddhi-JMS-Consumer {org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager}
javax.jms.JMSException: Error registering consumer: org.wso2.andes.AMQException: Woken up due to class javax.jms.JMSException
	at org.wso2.andes.client.AMQSession$6.execute(AMQSession.java:2143)
	at org.wso2.andes.client.AMQSession$6.execute(AMQSession.java:2086)
	at org.wso2.andes.client.AMQConnectionDelegate_8_0.executeRetrySupport(AMQConnectionDelegate_8_0.java:333)
	at org.wso2.andes.client.AMQConnection$3.run(AMQConnection.java:655)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.andes.client.AMQConnection.executeRetrySupport(AMQConnection.java:652)
	at org.wso2.andes.client.failover.FailoverRetrySupport.execute(FailoverRetrySupport.java:102)
	at org.wso2.andes.client.AMQSession.createConsumerImpl(AMQSession.java:2084)
	at org.wso2.andes.client.AMQSession.createConsumer(AMQSession.java:1072)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils.createConsumer(JMSUtils.java:478)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.createConsumer(JMSTaskManager.java:998)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.getMessageConsumer(JMSTaskManager.java:853)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.receiveMessage(JMSTaskManager.java:600)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:521)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.andes.AMQException: Woken up due to class javax.jms.JMSException
	at org.wso2.andes.client.util.BlockingWaiter.block(BlockingWaiter.java:207)
	at org.wso2.andes.client.protocol.BlockingMethodFrameListener.blockForFrame(BlockingMethodFrameListener.java:123)
	at org.wso2.andes.client.protocol.AMQProtocolHandler.writeCommandFrameAndWaitForReply(AMQProtocolHandler.java:655)
	at org.wso2.andes.client.protocol.AMQProtocolHandler.syncWrite(AMQProtocolHandler.java:676)
	at org.wso2.andes.client.protocol.AMQProtocolHandler.syncWrite(AMQProtocolHandler.java:670)
	at org.wso2.andes.client.AMQSession_0_8.sendQueueDeclare(AMQSession_0_8.java:374)
	at org.wso2.andes.client.AMQSession$12.execute(AMQSession.java:2810)
	at org.wso2.andes.client.AMQSession$12.execute(AMQSession.java:2801)
	at org.wso2.andes.client.failover.FailoverNoopSupport.execute(FailoverNoopSupport.java:67)
	at org.wso2.andes.client.AMQSession.declareQueue(AMQSession.java:2799)
	at org.wso2.andes.client.AMQSession.registerConsumer(AMQSession.java:2944)
	at org.wso2.andes.client.AMQSession.access$800(AMQSession.java:112)
	at org.wso2.andes.client.AMQSession$6.execute(AMQSession.java:2120)
	... 17 more
Caused by: javax.jms.JMSException: Exception thrown against AMQConnection:
Host: 172.18.0.1
Port: 5672
Virtual Host: carbon
Client ID: clientid
Active session count: 1: org.wso2.andes.AMQDisconnectedException: Server closed connection and reconnection not permitted.
	at org.wso2.andes.client.AMQConnection.exceptionReceived(AMQConnection.java:1315)
	at org.wso2.andes.client.protocol.AMQProtocolHandler.closed(AMQProtocolHandler.java:260)
	at org.wso2.andes.transport.network.mina.MinaNetworkHandler.sessionClosed(MinaNetworkHandler.java:138)
	at org.apache.mina.common.support.AbstractIoFilterChain$TailFilter.sessionClosed(AbstractIoFilterChain.java:550)
	at org.apache.mina.common.support.AbstractIoFilterChain.callNextSessionClosed(AbstractIoFilterChain.java:269)
	at org.apache.mina.common.support.AbstractIoFilterChain.access$800(AbstractIoFilterChain.java:53)
	at org.apache.mina.common.support.AbstractIoFilterChain$EntryImpl$1.sessionClosed(AbstractIoFilterChain.java:633)
	at org.apache.mina.common.IoFilterAdapter.sessionClosed(IoFilterAdapter.java:65)
	at org.apache.mina.common.support.AbstractIoFilterChain.callNextSessionClosed(AbstractIoFilterChain.java:269)
	at org.apache.mina.common.support.AbstractIoFilterChain.access$800(AbstractIoFilterChain.java:53)
	at org.apache.mina.common.support.AbstractIoFilterChain$EntryImpl$1.sessionClosed(AbstractIoFilterChain.java:633)
	at org.apache.mina.filter.executor.ExecutorFilter.processEvent(ExecutorFilter.java:230)
	at org.apache.mina.filter.executor.ExecutorFilter$ProcessEventsRunnable.run(ExecutorFilter.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:51)
	... 1 more
Caused by: org.wso2.andes.AMQDisconnectedException: Server closed connection and reconnection not permitted.
	... 16 more
TID: [-1] [] [2018-01-05 14:16:07,674]  INFO {org.wso2.andes.server.AMQChannel} -  No consumers to unsubscribe on channel [/10.100.7.104:40436(admin):1] {org.wso2.andes.server.AMQChannel}
TID: [-1] [] [2018-01-05 14:16:07,671] ERROR {org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager} -  JMS Connection failed : Exception thrown against AMQConnection:
Host: 172.18.0.1
Port: 5672
Virtual Host: carbon
Client ID: clientid
`

**Comment by chamindias** [comment]
Can you please provide more details on this? (Eg : Database used, are there any errors in the consoles [both APIM/Analytic servers] when invoking APIs). Sharing the jmeter script would be ideal (to get the details about the load test such as ramp up period). Reducing the priority since this was not observed in a normal setup.

**Comment by chamilaadhi** [comment]
Since requested information is not provided we will close this ticket. You could try out the latest APIM 2.6.0 as well and see whether this issue is happening.
