### ISSUE TITLE
NEP when user try to change lifecycle from mgt console

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2310]
**Description:**
Getting NullPointerException when user tries to change the lifecylce from mgt console.

**Steps to reproduce:**
1. Add an API to the publisher(added from REST API)
2. Go to mgt console >> Metadata >> APIs section
![image](https://user-images.githubusercontent.com/7115693/34725602-70b2db82-f577-11e7-937c-f07baf5465ef.png)

3. Select the newly created API from the list and go to lifecycle section in the newly opened screen
![image](https://user-images.githubusercontent.com/7115693/34725177-23440ea8-f576-11e7-939f-409e3c7756b4.png)

4. Click on the available state button(Block)
 
**Actual:**
1. Getting below error message in UI
![image](https://user-images.githubusercontent.com/7115693/34725269-6650423e-f576-11e7-9f9f-30ad1445b955.png)

2. And also below exceptions in the log/console
```
[2018-01-09 19:39:44,664] ERROR - InvokeAspectUtil Failed to invoke action Block of aspect APILifeCycle on resource /_system/governance/apimgt/applicationdata/provider/admin/subscriptionCheck_api/1.0/api. An exception occurred while executing handler chain. null
org.wso2.carbon.registry.core.exceptions.RegistryException: An exception occurred while executing handler chain. null
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getAPI(APIUtil.java:662)
	at org.wso2.carbon.apimgt.impl.executors.APIExecutor.execute(APIExecutor.java:111)
	at org.wso2.carbon.governance.registry.extensions.aspects.DefaultLifeCycle.runCustomExecutorsCode(DefaultLifeCycle.java:712)
	at org.wso2.carbon.governance.registry.extensions.aspects.DefaultLifeCycle.invoke(DefaultLifeCycle.java:450)
	at org.wso2.carbon.governance.registry.eventing.handlers.GovernanceEventingHandler.invokeAspect(GovernanceEventingHandler.java:344)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.invokeAspect(HandlerManager.java:2792)
	... 82 more
[2018-01-09 19:39:44,669] ERROR - RPCInOnlyMessageReceiver An exception occurred while executing handler chain. null
org.wso2.carbon.registry.core.exceptions.RegistryException: An exception occurred while executing handler chain. null
....
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getAPI(APIUtil.java:662)
	at org.wso2.carbon.apimgt.impl.executors.APIExecutor.execute(APIExecutor.java:111)
	at org.wso2.carbon.governance.registry.extensions.aspects.DefaultLifeCycle.runCustomExecutorsCode(DefaultLifeCycle.java:712)
	at org.wso2.carbon.governance.registry.extensions.aspects.DefaultLifeCycle.invoke(DefaultLifeCycle.java:450)
	at org.wso2.carbon.governance.registry.eventing.handlers.GovernanceEventingHandler.invokeAspect(GovernanceEventingHandler.java:344)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.invokeAspect(HandlerManager.java:2792)
	... 82 more
```

**Comment by edgars** [comment]
I found the same error, but just after had updated the Lifecycle jar

**Comment by bhathiya** [comment]
@chaminda I don't think we have such a use case in APIM. If you want to change the lifecycle, you should do it from publisher UI or REST API.

Please reopen if you have a valid usecase for this.
