### ISSUE TITLE
Internal server error when invoking a API with POST, without a payload

### ISSUE THREAD

**Issue by SupunS** [wso2/product-apim#2372]
**Description:**
When an API that accept a POST request (with content type appilcation/json) is invoked without a json payload, it prints the below error in the logs, and returns an internal server error (500) as the response.
```
Error while building message
org.apache.axis2.AxisFault: Error while building Passthrough stream
        at org.apache.synapse.transport.passthru.util.RelayUtils.handleException(RelayUtils.java:318)
        at org.apache.synapse.transport.passthru.util.RelayUtils.builldMessage(RelayUtils.java:167)
        at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:111)
        at org.apache.synapse.mediators.AbstractListMediator.buildMessage(AbstractListMediator.java:137)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:86)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:62)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.rest.Resource.process(Resource.java:343)
        at org.apache.synapse.rest.API.process(API.java:399)
        at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:90)
        at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
        at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:304)
        at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:78)
        at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
        at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRESTRequest(MultitenantMessageReceiver.java:641)
        at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doNhttpREST(MultitenantMessageReceiver.java:568)
        at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doREST(MultitenantMessageReceiver.java:373)
        at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRequest(MultitenantMessageReceiver.java:231)
        at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:81)
        at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
        at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:330)
        at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:376)
        at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.axis2.AxisFault: Payload is not a JSON string.
        at org.apache.synapse.commons.json.JsonUtil.toXml(JsonUtil.java:369)
        at org.apache.synapse.commons.json.JsonBuilder.processDocument(JsonBuilder.java:35)
        at org.apache.synapse.transport.passthru.util.DeferredMessageBuilder.getDocument(DeferredMessageBuilder.java:148)
        at org.apache.synapse.transport.passthru.util.RelayUtils.builldMessage(RelayUtils.java:148)
        ... 25 more
```
**Expected Behavior**: Either the API call should be successful with the empty payload, of should return a proper error indicating the POST action is not allowed with an empty payload. Internal server error must never be returned. 

**Suggested Labels:**
API Manager, severity/critical, Bug

**Affected Product Version:**
API Manager 2.1.0

**Steps to reproduce:**
- Create an API which accepts an POST request, and publish the API.
- Invoke the the above API with content-type set as application/json, but without any payload.

**Related Issues:**
https://github.com/wso2/product-apim/issues/2291
https://github.com/wso2/product-ei/issues/1680

**Comment by chamilaadhi** [comment]
Fixed in the latest version. Tested in AM 2.6.0 and not reproduced
