### ISSUE TITLE
Rest API: Partners are unable to create a subscription on an allowed api

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2381]
OS: Ubuntu 16.04
JDK: 1.8.0_144

Steps
1. Created a jmeter script that invokes the create api rest endpoint with the following payload
```
{
   "name": "TestAPI",
   "description": "This document describe a RESTFul API for TestAPIfromREST API.\r\n",
   "context": "test",
   "version": "1.0.0",
   "provider":"Administrator",
   "apiDefinition":"{\"swagger\":\"2.0\",\"paths\":{\"/salary/{id}\":{\"get\":{\"responses\":{\"200\":{\"description\":\"this is test\"}},\"parameters\":[{\"name\":\"id\",\"in\":\"path\",\"allowMultiple\":false,\"required\":true,\"type\":\"string\"}],\"x-auth-type\":\"Application & Application User\",\"x-throttling-tier\":\"Unlimited\"}}},\"info\":{\"title\":\"TestAPI\",\"version\":\"1.0.0\"}}",
   "isDefaultVersion": false,
   "type": "HTTP",
   "transport":    [
      "http",
      "https"
   ],
   "tiers": ["Unlimited"],
   "visibility": "public",
   "endpointConfig": "{\"production_endpoints\":{\"url\":\"http://${tomcathost}:${tomcatport}/${backend}\",\"config\":null},\"sandbox_endpoints\":{\"url\":\"${backend}\",\"config\":null},\"endpoint_type\":\"http\"}",
   "subscriptionAvailability": "specific_tenant",
   "subscriptionAvailableTenants": ["abc.com","def.com"]
}
```
But both the abc.com or def.com cannot subscribe to the relevant api. Fails with the below error.

```
2018-01-12 12:42:11,199] ERROR - UserAwareAPIConsumer Failed to get API. API artifact corresponding to artifactId 98ff7e3f-f3d5-475d-ab90-17a8501902f3 does not exist
[2018-01-12 12:42:11,199] ERROR - SubscriptionsApiServiceImpl Requested API with Id '98ff7e3f-f3d5-475d-ab90-17a8501902f3' not found
org.wso2.carbon.apimgt.api.APIManagementException: Failed to retrieve the API 98ff7e3f-f3d5-475d-ab90-17a8501902f3 to check user jane@operations.abc.com has access to the API
	at org.wso2.carbon.apimgt.rest.api.store.utils.RestAPIStoreUtils.isUserAccessAllowedForAPI(RestAPIStoreUtils.java:179)
	at org.wso2.carbon.apimgt.rest.api.store.impl.SubscriptionsApiServiceImpl.subscriptionsPost(SubscriptionsApiServiceImpl.java:256)
	at org.wso2.carbon.apimgt.rest.api.store.SubscriptionsApi.subscriptionsPost(SubscriptionsApi.java:95)
	at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:189)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:254)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:299)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:218)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:274)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1770)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1729)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.apimgt.api.APIMgtResourceNotFoundException: Failed to get API. API artifact corresponding to artifactId 98ff7e3f-f3d5-475d-ab90-17a8501902f3 does not exist
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getLightweightAPIByUUID(AbstractAPIManager.java:520)
	at org.wso2.carbon.apimgt.rest.api.store.utils.mappings.APIMappingUtil.getAPIIdentifierFromApiIdOrUUID(APIMappingUtil.java:70)
	at org.wso2.carbon.apimgt.rest.api.store.utils.RestAPIStoreUtils.isUserAccessAllowedForAPI(RestAPIStoreUtils.java:168)
	... 51 more

```

**Comment by fazlan-nazeem** [comment]
Tried this and was unable to reproduce. Subscriptions across tenants works fine.
