### ISSUE TITLE
Observed 'ParseException' for api invokation where port (8280) has been blocked for sometime

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2454]
**Description:**
Observed "ParseException" [1] for api invokation where port (8280) has been blocked for sometime

**Suggested Labels:**
APIM-2.20
Type/Query
Priority/medium
Sevirity/normal

**Affected Product Version:**
apim-2.1.0-update6

**OS, DB, other environment details and versions:**    
apim-analytics-2.1.0-update4 has configured

**Steps to reproduce:**
- API, application, subscription and keys are created 
- Start to invoke the API using jmx script (1 user, with forever loop for 30sec time duration) 
- After a while (10sec), down the port 8280 (drop the port from INPUT chain in iptables)
- Verify the invokation and logs 
Observation: invokation was hanged for while and stopped (see the summary report image attached); 
In carbon log observed the error and an exception [1]
Is this an expected behaviour? and if so can we improve the logs ?
![summ](https://user-images.githubusercontent.com/15671620/35037194-d27fb544-fb9c-11e7-94d5-011df651732a.jpeg)

[1]
`[2018-01-17 14:42:45,104] ERROR - SourceHandler HttpException occurred 
org.apache.http.ProtocolException: Invalid request line: §£Z_~tbzßêÕã¤ùÁFÚ9h_ëû£ß:À#À'<À%À)g@À	À/ÀÀ32À+À/À-À1¢À
	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:208)
	at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection$LoggingNHttpMessageParser.parse(LoggingNHttpServerConnection.java:383)
	at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection$LoggingNHttpMessageParser.parse(LoggingNHttpServerConnection.java:365)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:265)
	at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection.consumeInput(LoggingNHttpServerConnection.java:112)
	at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:82)
	at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:113)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.ParseException: Invalid request line: §£Z_~tbzßêÕã¤ùÁFÚ9h_ëû£ß:À#À'<À%À)g@À	À/ÀÀ32À+À/À-À1¢À
	at org.apache.http.message.BasicLineParser.parseRequestLine(BasicLineParser.java:287)
	at org.apache.http.impl.nio.codecs.DefaultHttpRequestParser.createMessage(DefaultHttpRequestParser.java:119)
	at org.apache.http.impl.nio.codecs.DefaultHttpRequestParser.createMessage(DefaultHttpRequestParser.java:51)
	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parseHeadLine(AbstractMessageParser.java:156)
	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:206)
	... 14 more
'

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.

**Comment by aparnaank** [comment]
We have seen a similar issue in API Manager 2.5.0 Gateway pod, what could be the reason for this error?

```
[2022-02-05 02:41:58,096] ERROR - SourceHandler HttpException occurred
org.apache.http.ProtocolException: Invalid request line: SO?G×÷º,îê²`~óý{¹ÕÈwæÄÛ<=Ûoïn(
at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:208)
at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection$LoggingNHttpMessageParser.parse(LoggingNHttpServerConnection.java:407)
at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection$LoggingNHttpMessageParser.parse(LoggingNHttpServerConnection.java:381)
at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:265)
at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection.consumeInput(LoggingNHttpServerConnection.java:114)
at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:82)
at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:39)
at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:113)
at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.ParseException: Invalid request line: SO?G×÷º,îê²`~óý{¹ÕÈwæÄÛ<=Ûoïn(
at org.apache.http.message.BasicLineParser.parseRequestLine(BasicLineParser.java:287)
at org.apache.http.impl.nio.codecs.DefaultHttpRequestParser.createMessage(DefaultHttpRequestParser.java:119)
at org.apache.http.impl.nio.codecs.DefaultHttpRequestParser.createMessage(DefaultHttpRequestParser.java:51)
at org.apache.http.impl.nio.codecs.AbstractMessageParser.parseHeadLine(AbstractMessageParser.java:156)
at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:206)
... 14 more
[2022-02-05 02:41:58,097]  INFO - SourceHandler Writer null when calling informWriterError
[2022-02-05 02:41:58,527] ERROR - SourceHandler HttpException occurred
org.apache.http.ProtocolException: Invalid request line: ieU§ärandom1random2random3random4
/
at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:208)
at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection$LoggingNHttpMessageParser.parse(LoggingNHttpServerConnection.java:407)
at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection$LoggingNHttpMessageParser.parse(LoggingNHttpServerConnection.java:381)
at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:265)
at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection.consumeInput(LoggingNHttpServerConnection.java:114)
at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:82)
at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:39)
at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:113)
at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.ParseException: Invalid request line: ieU§ärandom1random2random3random4
/
at org.apache.http.message.BasicLineParser.parseRequestLine(BasicLineParser.java:287)
at org.apache.http.impl.nio.codecs.DefaultHttpRequestParser.createMessage(DefaultHttpRequestParser.java:119)
at org.apache.http.impl.nio.codecs.DefaultHttpRequestParser.createMessage(DefaultHttpRequestParser.java:51)
at org.apache.http.impl.nio.codecs.AbstractMessageParser.parseHeadLine(AbstractMessageParser.java:156)
at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:206)
... 14 more
```

**Comment by riyazathali** [comment]
This issue arises when you send an HTTPS request using the HTTP listener (Port 8280). We have two available ports in WSO2 APIM for API invocation using HTTP and HTTPS protocols. We have configured HTTP for port 8280 and HTTPS for port 8243 in the default environment. When you send an HTTPS request over this 8280 port, the HTTP listener is unable to parse the request and displays the Invalid request line.

Therefore, could you possibly try sending the request using the HTTPS port (8243) and invoking the API to see whether the issue is solved?
