### ISSUE TITLE
Rest API- Adding a custom mediaton

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2554]
By following [1] tried to add a custom sequence using the following payload, that binds an already added registry resource 

```
{
   "name": "TaskDetails",
   "description": "This document describe a RESTFul API for TestAPIfromREST API.\r\n",
   "context": "tasks",
   "version": "1.0.0",
   "provider":"Administrator",
   "apiDefinition":"{\"swagger\":\"2.0\",\"paths\":{\"/task/{id}\":{\"get\":{\"responses\":{\"200\":{\"description\":\"this is test\"}},\"parameters\":[{\"name\":\"id\",\"in\":\"path\",\"allowMultiple\":false,\"required\":true,\"type\":\"string\"}],\"x-auth-type\":\"Application & Application User\",\"x-throttling-tier\":\"Unlimited\"}}},\"info\":{\"title\":\"TaskDetails\",\"version\":\"1.0.0\"}}",
   "isDefaultVersion": false,
   "type": "HTTP",
   "transport":    [
      "http",
      "https"
   ],
   "tiers": ["Unlimited"],
   "visibility": "PUBLIC",
   "endpointConfig": "{\"production_endpoints\":{\"url\":\"http://localhost:8080//sample-data-backend/rservice/taskservice/\",\"config\":null},\"sandbox_endpoints\":{\"url\":\"/sample-data-backend/rservice/taskservice/\",\"config\":null},\"endpoint_type\":\"http\"}",
   "sequences":[{"name":"custom-in","type": "in","config": "/_system/governance/apimgt/customsequences/in/custom-in.xml"},{"name":"custom-out","type": "out","config": "/_system/governance/apimgt/customsequences/out/custom-out.xml"}],
   "subscriptionAvailability": "current_tenant",
   "subscriptionAvailableTenants": null
}
```
Above payload resulted in the below error

```
[2018-01-22 17:47:37,636] ERROR - GlobalThrowableMapper Unrecognized property 'config'
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "config" (class org.wso2.carbon.apimgt.rest.api.publisher.dto.SequenceDTO), not marked as ignorable (4 known properties: "type", "name", "shared", "id"])
 at [Source: org.apache.cxf.transport.http.AbstractHTTPDestination$1@497e13d3; line: 17, column: 61] (through reference chain: org.wso2.carbon.apimgt.rest.api.publisher.dto.APIDTO["sequences"]->java.util.ArrayList[0]->org.wso2.carbon.apimgt.rest.api.publisher.dto.SequenceDTO["config"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:833)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1096)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1467)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1445)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:282)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1579)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:961)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:808)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBodyReader(JAXRSUtils.java:1366)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBody(JAXRSUtils.java:1317)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.processParameter(JAXRSUtils.java:824)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.processParameters(JAXRSUtils.java:788)
	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.processRequest(JAXRSInInterceptor.java:212)
	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:77)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:254)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:299)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:218)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:274)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1770)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1729)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

Using the information provided in the above error changed the payload to below

```
{
   "name": "TaskDetails",
   "description": "This document describe a RESTFul API for TestAPIfromREST API.\r\n",
   "context": "tasks",
   "version": "1.0.0",
   "provider":"Administrator",
   "apiDefinition":"{\"swagger\":\"2.0\",\"paths\":{\"/task/{id}\":{\"get\":{\"responses\":{\"200\":{\"description\":\"this is test\"}},\"parameters\":[{\"name\":\"id\",\"in\":\"path\",\"allowMultiple\":false,\"required\":true,\"type\":\"string\"}],\"x-auth-type\":\"Application & Application User\",\"x-throttling-tier\":\"Unlimited\"}}},\"info\":{\"title\":\"TaskDetails\",\"version\":\"1.0.0\"}}",
   "isDefaultVersion": false,
   "type": "HTTP",
   "transport":    [
      "http",
      "https"
   ],
   "tiers": ["Unlimited"],
   "visibility": "PUBLIC",
   "endpointConfig": "{\"production_endpoints\":{\"url\":\"http://localhost:8080//sample-data-backend/rservice/taskservice/\",\"config\":null},\"sandbox_endpoints\":{\"url\":\"/sample-data-backend/rservice/taskservice/\",\"config\":null},\"endpoint_type\":\"http\"}",
   "sequences":[{"name":"custom-in","type": "in","id": "/_system/governance/apimgt/customsequences/in/custom-in.xml"},{"name":"custom-out","type": "out","id": "/_system/governance/apimgt/customsequences/out/custom-out.xml"}],
   "subscriptionAvailability": "current_tenant",
   "subscriptionAvailableTenants": null
}

```
The second payload worked. Can we please check this and update the docs? Current documentation in [1] will mislead a user.

[1] https://docs.wso2.com/display/AM210/apidocs/publisher/#!/operations#MediationPolicyCollection#apisApiIdPoliciesMediationPost

**Comment by shaniR** [comment]
This seems to be a bug. Will remove the docs label and report as a bug. 

Investiagtion: 

Create API uses SequenceDTO to convert the payload to DTO, and in the sequence DTO, the properties are "type", "name", "shared", "id". Where as  when adding a mediation to an already existing API using the above API specified in this ticket the MediationDTO is used where the properties are "id, name, type and config". Adding a mediation sequence to an already existing API works as per the documentation. However creating a new API with a sequence does not, because of the difference. This needs to be fixed in code level.
