### ISSUE TITLE
An exception is occurring while add and publish an API with REST API

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2555]
**Description:**
Below issue is getting intermittently(but the possibility is high) while adding and publishing an API through publisher REST Services

**Steps to Recreate:**
1. create an API from the publisher REST API
```
POST: https:<host>:<port>/api/am/publisher/v0.11/apis
header:
Authorization Bearer <token>
Content-Type application/json
body:
{
	"name": "${APIName}",
	"description": "This document describe a RESTFul API for TestAPIfromREST API.\r\n",
	"context": "${APIContext}",
	"version": "${APIVersion}",
	"isDefaultVersion": false,
	"type": "HTTP",
	"transport": [
		"http",
		"https"
	],
	"tiers": ["Unlimited"],
	"visibility": "PUBLIC",
	"endpointConfig": "{\"production_endpoints\":{\"url\":\"http://www.mocky.io/v2/5a5dc947330000a90b1918fe/\",\"config\":null},\"sandbox_endpoints\":{\"url\":\"http://www.mocky.io/v2/5a5dc947330000a90b1918fe/\",\"config\":null},\"endpoint_type\":\"http\"}",
	"apiDefinition": "{\"swagger\": \"2.0\", \"paths\": {\"/test\": {\"get\": {\"responses\": {\"200\": {\"description\":\"Test API with Notification Subscriptions\"}}, \"x-auth-type\": \"Application & Application User\",\"x-throttling-tier\": \"Unlimited\"}}}, \"info\": {\"title\": \"${APIName2}\",\"version\": \"${APIVersion2}\"}}",
	"responseCaching": "Disabled"
}
```
2. Publish the api using below request.
**NOTE:** in addition to the above steps there are steps to generate tokens via same API

While run the above mention scripts, getting below exception intermittently.
```
[2018-01-22 18:29:19,791] ERROR - GovernanceEventingHandler Lifecycle 'APILifeCycle'checkpoint addition failed for state Created
org.wso2.carbon.governance.api.exception.GovernanceException: Error while building OM element to lifecycle configurations of 'APILifeCycle' lifecycle.
        at org.wso2.carbon.governance.lcm.util.LifecycleStateDurationUtils.getLifecycleConfigurationElement(LifecycleStateDurationUtils.java:360)
        at org.wso2.carbon.governance.lcm.util.LifecycleStateDurationUtils.getDurationBeans(LifecycleStateDurationUtils.java:320)
        at org.wso2.carbon.governance.lcm.tasks.LCNotificationScheduler.addScheduler(LCNotificationScheduler.java:137)
        at org.wso2.carbon.governance.registry.eventing.handlers.GovernanceEventingHandler.addLCNotificationScheduler(GovernanceEventingHandler.java:621)
        at org.wso2.carbon.governance.registry.eventing.handlers.GovernanceEventingHandler.put(GovernanceEventingHandler.java:173)
        at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2503)
        at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:970)
        at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:697)
        at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:828)
        at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:61)
        at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:804)
        at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:801)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:801)
        at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:292)
        at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2503)
        at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.put(UserDefinedHandlerManager.java:205)
        at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:949)
        at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:697)
        at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.associateAspect(EmbeddedRegistry.java:2474)
        at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.associateAspect(CacheBackedRegistry.java:499)
        at org.wso2.carbon.registry.core.session.UserRegistry.associateAspectInternal(UserRegistry.java:1901)
        at org.wso2.carbon.registry.core.session.UserRegistry.access$3800(UserRegistry.java:61)
        at org.wso2.carbon.registry.core.session.UserRegistry$39.run(UserRegistry.java:1873)
        at org.wso2.carbon.registry.core.session.UserRegistry$39.run(UserRegistry.java:1870)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.wso2.carbon.registry.core.session.UserRegistry.associateAspect(UserRegistry.java:1870)
        at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.attachLifecycle(GovernanceArtifactImpl.java:383)
        at org.wso2.carbon.apimgt.impl.APIProviderImpl.createAPI(APIProviderImpl.java:2477)
        at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPI(APIProviderImpl.java:645)
        at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addAPI(UserAwareAPIProvider.java:62)
        at org.wso2.carbon.apimgt.rest.api.publisher.impl.ApisApiServiceImpl.apisPost(ApisApiServiceImpl.java:263)
        at org.wso2.carbon.apimgt.rest.api.publisher.ApisApi.apisPost(ApisApi.java:574)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:189)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:254)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:299)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:218)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:274)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
        at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
        at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
        at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1770)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1729)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.governance.api.exception.GovernanceException: Can not get lifecycle configurations of 'APILifeCycle' lifecycle.
        at org.wso2.carbon.governance.lcm.util.LifecycleStateDurationUtils.getLifecycleConfigurationElement(LifecycleStateDurationUtils.java:356)
        ... 82 more
```

**Comment by ChamNDeSilva** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5020
