### ISSUE TITLE
[APIM-Analytics] Exception occurred when system tries to generate email alerts

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2584]
**Description:**
Exception is occuring once the user invoke the api as trigger selected alert types and try to send the email. But user has no clue on the error by looking at the exception.

**Affected Product Version:**
wso2am-analytics-2.1.0-update4

**OS, DB, other environment details and versions:**   
JDK.1.8, macOS

**Steps to reproduce:**
1. Configure alert types from the Manage Alert section in Admin Portal
Abnormal Request Count, Abnormal Resource Access, Abnormal Access Token Renewal, Abnormal API Usage, Health Availability and have put multiple email addresses.

2. Configure email configurations in output-event-adapters.xml in apim-analytics
3. Invoke the API as the throughput in 25/s or around.(just to get triggered the alerts)

**Actual Result:**
Following error can be seen on apim-analytics server console, which is not meaningful to identify the exact issue.
```
[2018-01-23 17:46:33,655] ERROR {org.wso2.carbon.event.output.adapter.email.EmailEventAdapter} 
-  Event dropped at Output Adapter 'org.wso2.analytics.apim.emailAlertStreamPublisher' 
for tenant id '-1234', Error in message format, null
javax.mail.AuthenticationFailedException
	at javax.mail.Service.connect(Service.java:306)
	at javax.mail.Service.connect(Service.java:156)
	at javax.mail.Service.connect(Service.java:105)
	at javax.mail.Transport.send0(Transport.java:168)
	at javax.mail.Transport.send(Transport.java:98)
	at org.wso2.carbon.event.output.adapter.email.EmailEventAdapter$EmailSender.run(EmailEventAdapter.java:306)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Expected Result:**
The Error/Exception should be meaningful to the user for identifying/isolating the exact issue occured in the system/configuration

**Comment by fazlan-nazeem** [comment]
The exception message claims says it is **javax.mail.AuthenticationFailedException**  which implies there is an error in authenticating. Therefore we assume this information is sufficient for the admin to identify the issue.

This happens when analytics server cannot authenticate to the mail server in the configs.
