### ISSUE TITLE
Observing a null pointer thrown when calling an api

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2612]
**Description:**
A null pointer is thrown when a created api is being called. The setup is a distributed setup ( Pattern 6 ). Below are the sequence of the api calls that is done followed by the logs.

**Steps to reproduce:**

You can refer the attaceched JMeter script 
1. Create and API
2. Publish the API
3. Create an application and subscribe to it from the created api
4. Invoke the API
5. Delete the API

```
TID: [-1234] [] [2018-01-25 06:03:41,979] ERROR {org.wso2.carbon.apimgt.gateway.throttling.publisher.ThrottleDataPublisher} -  Error while publishing throttling events to global policy server {org.wso2.carbon.apimgt.gateway.throttling.publisher.ThrottleDataPublisher}
java.lang.NullPointerException
	at org.wso2.carbon.apimgt.gateway.throttling.publisher.ThrottleDataPublisher.publishNonThrottledEvent(ThrottleDataPublisher.java:119)
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doRoleBasedAccessThrottlingWithCEP(ThrottleHandler.java:349)
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doThrottle(ThrottleHandler.java:512)
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.handleRequest(ThrottleHandler.java:460)
	at org.apache.synapse.rest.API.process(API.java:325)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:90)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:304)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:78)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:330)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:159)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
TID: [-1234] [] [2018-01-25 06:03:56,866] ERROR {org.wso2.carbon.apimgt.gateway.throttling.publisher.ThrottleDataPublisher} -  Error while publishing throttling events to global policy server {org.wso2.carbon.apimgt.gateway.throttling.publisher.ThrottleDataPublisher}
java.lang.NullPointerException
	at org.wso2.carbon.apimgt.gateway.throttling.publisher.ThrottleDataPublisher.publishNonThrottledEvent(ThrottleDataPublisher.java:119)
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doRoleBasedAccessThrottlingWithCEP(ThrottleHandler.java:349)
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doThrottle(ThrottleHandler.java:512)
	at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.handleRequest(ThrottleHandler.java:460)
	at org.apache.synapse.rest.API.process(API.java:325)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:90)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:304)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:78)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:330)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:159)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
TID: [-1234] [] [2018-01-25 06:03:57,715]  INFO {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} -  'admin@carbon.super [-1234]' logged in at [2018-01-25 06:03:57,715+0000] {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil}
```

**Observation**
When invoking the API the below null pointer is thrown from the gateway-manager node every time a api invocation is done.

The api request is served successfully and the response is received to the client.

Found [1\] but please note that in this set-up the  `<EnableAdvanceThrottling>true</EnableAdvanceThrottling>`
 & `<EnableAdvanceThrottling>true</EnableAdvanceThrottling>`

**Suggested Labels:**

APIM-2.1.0 wum (1516470910911) 
Type/bug
Priority/high
Sevirity/Major

**OS, DB, other environment details and versions:**    

OS: Ubuntu 14.04
DB: MySQL 5.5.58
JDK: Oracke jdk-8u121
Setup: puppet pattern 6
Note: enabled log4jdbc

**Comment by jsonds** [comment]
Closing this issue because the cause for this was the "DataPublisher" was set to false in the gateway manager's apim-manager.xml. When it was set to true this issue was resolved.
