### ISSUE TITLE
It has been not asked to allow email addresses as username in API Manager - Log in to the API Store using Social Media

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2615]
**Description:**
Document: [Log in to the API Store using Social Media](https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media#LogintotheAPIStoreusingSocialMedia-ConfigureFacebookloginwithIdentityServer)
Section: Configure service providers to the Publisher and Store with the Facebook Identity Provider.

It has been asked only to allow using email addresses as username in IS. But it has to be done in API Manager as well. Otherwise, it gets the following error.

> ERROR - Authenticator wrong userName or password
[2018-01-25 14:25:35,227] ERROR - DataEndpointConnectionWorker Error while trying to login to data receiver :/10.100.5.136:9711
org.wso2.carbon.databridge.agent.exception.DataEndpointAuthenticationException: Error while trying to login to data receiver :/10.100.5.136:9711
	at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryDataEndpoint.login(BinaryDataEndpoint.java:47)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:93)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.databridge.commons.exception.AuthenticationException: wrong userName or password

Therefore the same process needs to be done in APIM>Repository>Conf>user-mgt.xml too.
Please mention this in the doc.

**Suggested Labels:**
Type/Docs
Severity/Major
Priority/High

**Suggested Assignees:**
N/A

**Affected Product Version:**
apim2xx docs

**Comment by ChamNDeSilva** [comment]
Fixed in following
https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media
https://docs.wso2.com/display/AM210/Log+in+to+the+API+Store+using+Social+Media
