### ISSUE TITLE
When enabaling emailasUsername in API Manager, admin@wso2.com gives errors. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2618]
**Description:**
As per doc[1] and issue[2], once emailasUsername is enabled in IS, it has to be enabled in API manager as well.  When we follow the same steps in APIM as in doc[3], following error is encountered. 

```
ERROR - DataEndpointConnectionWorker Error while trying to login to data receiver :/10.100.5.136:9711
org.wso2.carbon.databridge.agent.exception.DataEndpointAuthenticationException: Error while trying to login to data receiver :/10.100.5.136:9711
	at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryDataEndpoint.login(BinaryDataEndpoint.java:47)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:93)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.databridge.commons.exception.AuthenticationException: java.lang.NullPointerException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryEventSender.processResponse(BinaryEventSender.java:162)
	at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryDataEndpoint.login(BinaryDataEndpoint.java:42)
	... 7 more
[2018-01-25 14:21:28,751] ERROR - DataEndpointConnectionWorker Error while trying to connect to the endpoint. Cannot borrow client for ssl://10.100.5.136:9711
org.wso2.carbon.databridge.agent.exception.DataEndpointAuthenticationException: Cannot borrow client for ssl://10.100.5.136:9711
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:99)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.databridge.agent.exception.DataEndpointAuthenticationException: Error while trying to login to data receiver :/10.100.5.136:9711
	at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryDataEndpoint.login(BinaryDataEndpoint.java:47)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:93)
	... 6 more
Caused by: org.wso2.carbon.databridge.commons.exception.AuthenticationException: java.lang.NullPointerException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryEventSender.processResponse(BinaryEventSender.java:162)
	at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryDataEndpoint.login(BinaryDataEndpoint.java:42)

```
But once the configuration is set as below in APIM, no errors are encountered. But in IS, it has been set to admin@wso2.com. 

```
            <AdminUser>
                <UserName>admin@wso2.com@carbon.super</UserName>
                <Password>admin</Password>
            </AdminUser>
```

- Shouldn't be API Manager user-mgt.xml and IS user-mgt.xml containing the same configs when enabling emailasusername?
- If the actual work around is using **admin@wso2.com@carbon.super** as the username, please specify it in the doc. 

**Suggested Labels:**
Type/Docs
Type/Bug
Priority/High
Severity/Major

**Suggested Assignees:**
N/A

**Affected Product Version:**
apim-2.1.0 update 7
am2xx docs

**OS, DB, other environment details and versions:**    
OS: macOS high sierra
Product: api-2.1.0 update 7 / IS 5.4.0

**Steps to reproduce:**
1. Follow the steps in doc[3] in IS and start the Identity Server. 
2. Follow the steps in doc[3] in APIM and start the APIM Server. 

**Expected:** APIM should be started.
**Actual:** Above mentioned error occurs. 

[1] - [Log in to the API Store using Social Media](https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media#LogintotheAPIStoreusingSocialMedia-ConfigureFacebookloginwithIdentityServer)
[2] - https://github.com/wso2/product-apim/issues/2615
[3] - [Using Email Address as the Username](https://docs.wso2.com/display/IS540/Using+Email+Address+as+the+Username)

**Related Issues:**
https://github.com/wso2/product-apim/issues/2615

**Comment by Mariangela** [comment]
@bhathiya & @chaminda can you please let us know the resolution on this Git issue.

Should we use the following in the IS and APIM configurations as suggested in this Git issue?
```
           <AdminUser>
                <UserName>admin@wso2.com@carbon.super</UserName>
                <Password>admin</Password>
            </AdminUser>
```

**Comment by bhathiya** [comment]
@Mariangela This is not a doc issue. We need to test and see if it's a bug. I'll change the label,

**Comment by fazlan-nazeem** [comment]
@Mariangela @ruthryi This issue is reproducible according to the steps given in the documentation. 

We need to follow the steps in [1] under "Setting up an e-mail login". So it is better to link [1] in [2]

[1]https://docs.wso2.com/display/AM210/Maintaining+Logins+and+Passwords#MaintainingLoginsandPasswords-LogininviamultipleuserattributesinAPIStore
[2] https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media#LogintotheAPIStoreusingSocialMedia-ConfigureFacebookloginwithIdentityServer

**Comment by ruthryi** [comment]
Added the **Setting up an e-mail login** section to [1] and [2].
Linked of to the corresponding versions in [3] and [4].

[1] https://docs.wso2.com/display/AM2xx/Maintaining+Logins+and+Passwords#MaintainingLoginsandPasswords-Settingupane-mailloginemaillogin
[2] https://docs.wso2.com/display/AM220/Maintaining+Logins+and+Passwords#MaintainingLoginsandPasswords-Settingupane-mailloginemaillogin
[3] https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media#LogintotheAPIStoreusingSocialMedia-ConfigureserviceproviderstothePublisherandStorewiththeFacebookIdentityProvider
[4] https://docs.wso2.com/display/AM220/Log+in+to+the+API+Store+using+Social+Media#LogintotheAPIStoreusingSocialMedia-ConfigureserviceproviderstothePublisherandStorewiththeFacebookIdentityProvider
