### ISSUE TITLE
[apim-analytics] Spark Error LOGANALYZER_MESSAGE_LEVEL_ERROR_DAILY does not exist

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2656]
**Description:**
Continuously getting below exception on the apim-analytics node in the cluster(pattern-6). No way to get rid of this issue until restart the server. It claims as LOGANALYZER_MESSAGE_LEVEL_ERROR_DAILY table doesn't exist. But table can be seen in the data explorer.

```
TID: [-1234] [] [2018-01-31 05:30:10,182] ERROR {org.wso2.carbon.analytics.spark.core.AnalyticsTask} -  Error while executing the scheduled task for the script: APIM_LOGANALYZER_SCRIPT {org.wso2.carbon.analytics.spark.core.AnalyticsTask}
org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionException: Exception in executing query INSERT OVERWRITE table loganalyzer_message_level_error_daily        SELECT            temp.tenantID AS tenantID,            temp.message AS logMessage,            SUM(temp.messageCount) AS totalMessageCount,            getDateStartingTime(temp.byYear, temp.byMonth, temp.byDay) AS _timestamp        FROM (            SELECT                _content AS message,                getYear(_eventTimeStamp) AS byYear,                getMonth(_eventTimeStamp) AS byMonth,                getDay(_eventTimeStamp) AS byDay,                count(*) as messageCount,                tenantID AS tenantID            FROM CopyOfLoganalyzer            WHERE _level LIKE 'ERROR'            GROUP BY _content, _eventTimeStamp, tenantID            ORDER BY _eventTimeStamp        )temp        GROUP BY temp.tenantID, temp.message, temp.byYear,temp.byMonth, temp.byDay        ORDER BY temp.byYear, temp.byMonth, temp.byDay
	at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQueryLocal(SparkAnalyticsExecutor.java:918)
	at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQuery(SparkAnalyticsExecutor.java:875)
	at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.executeQuery(CarbonAnalyticsProcessorService.java:201)
	at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.executeScript(CarbonAnalyticsProcessorService.java:151)
	at org.wso2.carbon.analytics.spark.core.AnalyticsTask.execute(AnalyticsTask.java:60)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1609490.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1609490.0 (TID 2447846, localhost): java.lang.RuntimeException: Error while inserting data into table LOGANALYZER_MESSAGE_LEVEL_ERROR_DAILY: [-1234:LOGANALYZER_MESSAGE_LEVEL_ERROR_DAILY] does not exist
	at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPutNormal(AnalyticsWritingFunction.java:143)
	at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPut(AnalyticsWritingFunction.java:128)
	at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:119)
	at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:45)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.analytics.datasource.commons.exception.AnalyticsTableNotAvailableException: [-1234:LOGANALYZER_MESSAGE_LEVEL_ERROR_DAILY] does not exist
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.readTableInfo(AnalyticsDataServiceImpl.java:455)
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.lookupTableInfo(AnalyticsDataServiceImpl.java:810)
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecordBatch(AnalyticsDataServiceImpl.java:864)
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecords(AnalyticsDataServiceImpl.java:790)
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.put(AnalyticsDataServiceImpl.java:877)
	at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPutNormal(AnalyticsWritingFunction.java:139)
	... 11 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1858)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1915)
	at org.wso2.carbon.analytics.spark.core.sources.AnalyticsRelation.writeDataFrameToDAL(AnalyticsRelation.java:233)
	at org.wso2.carbon.analytics.spark.core.sources.AnalyticsRelation.insert(AnalyticsRelation.java:223)
	at org.apache.spark.sql.execution.datasources.InsertIntoDataSource.run(InsertIntoDataSource.scala:40)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:58)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:56)
	at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:70)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:130)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:130)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:55)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:55)
	at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:145)
	at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:130)
	at org.apache.spark.sql.DataFrame$.apply(DataFrame.scala:52)
	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:817)
	at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQueryLocal(SparkAnalyticsExecutor.java:914)
	... 11 more
Caused by: java.lang.RuntimeException: Error while inserting data into table LOGANALYZER_MESSAGE_LEVEL_ERROR_DAILY: [-1234:LOGANALYZER_MESSAGE_LEVEL_ERROR_DAILY] does not exist
	at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPutNormal(AnalyticsWritingFunction.java:143)
	at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPut(AnalyticsWritingFunction.java:128)
	at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:119)
	at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:45)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	... 3 more
Caused by: org.wso2.carbon.analytics.datasource.commons.exception.AnalyticsTableNotAvailableException: [-1234:LOGANALYZER_MESSAGE_LEVEL_ERROR_DAILY] does not exist
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.readTableInfo(AnalyticsDataServiceImpl.java:455)
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.lookupTableInfo(AnalyticsDataServiceImpl.java:810)
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecordBatch(AnalyticsDataServiceImpl.java:864)
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecords(AnalyticsDataServiceImpl.java:790)
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.put(AnalyticsDataServiceImpl.java:877)
	at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPutNormal(AnalyticsWritingFunction.java:139)
```

**Affected Product Version:**
apim2.1.0 wum

**OS, DB, other environment details and versions:**    
Ubuntu 14.04, MySql 5.6, JDK1.8

**Steps to reproduce:**
The issue is noticed on a running apim cluster.

**Comment by pedrorozoc** [comment]
@chaminda Did you find any solution?

**Comment by bhathiya** [comment]
Spark scripts are removed from 2.6.0. Hense this issue is irrelevant for 2.6.0
