### ISSUE TITLE
[Chaos] UnknownHostException when event queue is full gateway worker

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2672]
**Description:**
Getting below exception in gateway worker when event queue is full on gw-worker.
Even after stopped the running test, these exceptions are continuously getting and it is claiming UnknownHostException to tm.dev.wso2.org:9711 which is accessible from the gw-worker once checked.

```
TID: [-1] [] [2018-02-02 10:51:06,444]  WARN {org.wso2.carbon.databridge.agent.endpoint.DataEndpointGroup} -  No receiver is reachable at reconnection, will try to reconnect every 30 sec {org.wso2.carbon.databridge.agent.endpoint.DataEndpointGroup}
TID: [-1] [] [2018-02-02 10:51:06,445]  WARN {org.wso2.carbon.databridge.agent.DataPublisher} -  Event queue is full, unable to process the event for endpoint group [ ( Receiver URL : tcp://analytics.dev.wso2.org:7612, Authentication URL : ssl://analytics.dev.wso2.org:7712) ], 98689 events dropped so far. {org.wso2.carbon.databridge.agent.DataPublisher}
TID: [-1] [] [2018-02-02 10:51:06,445] ERROR {org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker} -  Error while trying to connect to the endpoint. Cannot borrow client for ssl://tm.dev.wso2.org:9711 {org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker}
org.wso2.carbon.databridge.agent.exception.DataEndpointAuthenticationException: Cannot borrow client for ssl://tm.dev.wso2.org:9711
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:134)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.databridge.agent.exception.DataEndpointException: Error while opening socket to tm.dev.wso2.org:9711. tm.dev.wso2.org
	at org.wso2.carbon.databridge.agent.endpoint.binary.BinarySecureClientPoolFactory.createClient(BinarySecureClientPoolFactory.java:74)
	at org.wso2.carbon.databridge.agent.client.AbstractClientPoolFactory.makeObject(AbstractClientPoolFactory.java:39)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1212)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:123)
	... 6 more
Caused by: java.net.UnknownHostException: tm.dev.wso2.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:427)
	at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:88)
	at org.wso2.carbon.databridge.agent.endpoint.binary.BinarySecureClientPoolFactory.createClient(BinarySecureClientPoolFactory.java:58)
	... 9 more
```

**Affected Product Version:**
apim2.1.0 wum

**OS, DB, other environment details and versions:**    
Ubuntu14.04, MySql5.6, JDK1.8

**Steps to reproduce:**
Tried to stress out gw worker node in apim cluster pattern-6 sending API invoke request in 300TPS.
Ran the above test continuously for sometime till detecting failures.
Stopped the tests once failing the requests and continuously getting this exception without processing or clearing out the filled queues.
No errors/exceptions detected on analytics or traffic manager consoles.

**Comment by bhathiya** [comment]
Had you configured "tm.dev.wso2.org" in `/etc/hosts` file?

**Comment by bhathiya** [comment]
If you add a proper DNS entry, this should work.
