### ISSUE TITLE
[AM210] latest wum pack (05/01/18) failing for super admin password has special character ("@") while server start up 

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2677]
**Description:**
As $subject, when start the server with super admin having "@" sign in his password. As per [1] jndi.properties file also updated with url encoding.

**Suggested Labels:**
2.1.0
Type/bug
Priority/highest
Sevirity/critical

**Affected Product Version:**
apim-2.1.0 wum update (wso2am-2.1.0.1517251727601.zip)

**OS, DB, other environment details and versions:**    
standalone pack
pointed to AD as primary US

**Steps to reproduce:**
- Add AD configs properly (password e.g. "ADadminwso2@")
- Update the jndi.properties config as adding url encode value
`ADadminwso2%40`
- Start the server => Observed below error[2]
Note that once the password changed to normal charaters it worked.

[1] [https://docs.wso2.com/display/AM210/Maintaining+Logins+and+Passwords#MaintainingLoginsandPasswords-Changingthesuperadmincredentials]
[2]
`[2018-02-05 12:13:52,403] ERROR - AMQStateManager Notifying Waiters([org.wso2.andes.client.state.StateWaiter@28a272bb]) for error:not allowed
[2018-02-05 12:13:52,410] ERROR - AMQProtocolHandler AMQP timed out when attempting to close the connection 
org.wso2.andes.AMQTimeoutException: Server did not respond in a timely fashion [error code 408: Request Timeout]
	at org.wso2.andes.client.util.BlockingWaiter.block(BlockingWaiter.java:176)
	at org.wso2.andes.client.protocol.BlockingMethodFrameListener.blockForFrame(BlockingMethodFrameListener.java:123)
	at org.wso2.andes.client.protocol.AMQProtocolHandler.writeCommandFrameAndWaitForReply(AMQProtocolHandler.java:655)
	at org.wso2.andes.client.protocol.AMQProtocolHandler.syncWrite(AMQProtocolHandler.java:676)
	at org.wso2.andes.client.protocol.AMQProtocolHandler.closeConnection(AMQProtocolHandler.java:707)
	at org.wso2.andes.client.protocol.AMQProtocolSession.closeProtocolSession(AMQProtocolSession.java:379)
	at org.wso2.andes.client.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:104)
	at org.wso2.andes.client.handler.ClientMethodDispatcherImpl.dispatchConnectionClose(ClientMethodDispatcherImpl.java:192)
	at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140)
	at org.wso2.andes.client.state.AMQStateManager.methodReceived(AMQStateManager.java:111)
	at org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:517)
	at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467)
	at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:96)
	at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:468)
	at org.wso2.andes.pool.Job.processAll(Job.java:111)
	at org.wso2.andes.pool.Job.run(Job.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2018-02-05 12:13:52,410]  INFO - AMQConnection Unable to connect to broker at tcp://172.18.0.1:5672
org.wso2.andes.AMQException: Error occurred while establishing a connection 
	at org.wso2.andes.client.AMQConnectionDelegate_8_0.makeBrokerConnection(AMQConnectionDelegate_8_0.java:142)
	at org.wso2.andes.client.AMQConnection$2.run(AMQConnection.java:631)
	at org.wso2.andes.client.AMQConnection$2.run(AMQConnection.java:628)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.andes.client.AMQConnection.makeBrokerConnection(AMQConnection.java:628)
	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:409)
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:351)
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:40)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils.createConnection(JMSUtils.java:391)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSListener.checkJMSConnection(JMSListener.java:137)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSListener.start(JMSListener.java:79)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSListener.run(JMSListener.java:186)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.andes.client.AMQAuthenticationException: not allowed [error code 530: not allowed]
	at org.wso2.andes.client.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:79)
	at org.wso2.andes.client.handler.ClientMethodDispatcherImpl.dispatchConnectionClose(ClientMethodDispatcherImpl.java:192)
	at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140)
	at org.wso2.andes.client.state.AMQStateManager.methodReceived(AMQStateManager.java:111)
	at org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:517)
	at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467)
	at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:96)
	at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:468)
	at org.wso2.andes.pool.Job.processAll(Job.java:111)
	at org.wso2.andes.pool.Job.run(Job.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
org.wso2.andes.AMQConnectionFailureException: not allowed
	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:486)
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:351)
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:40)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils.createConnection(JMSUtils.java:391)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSListener.checkJMSConnection(JMSListener.java:137)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSListener.start(JMSListener.java:79)
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSListener.run(JMSListener.java:186)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.andes.AMQException: Error occurred while establishing a connection 
	at org.wso2.andes.client.AMQConnectionDelegate_8_0.makeBrokerConnection(AMQConnectionDelegate_8_0.java:142)
	at org.wso2.andes.client.AMQConnection$2.run(AMQConnection.java:631)
	at org.wso2.andes.client.AMQConnection$2.run(AMQConnection.java:628)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.andes.client.AMQConnection.makeBrokerConnection(AMQConnection.java:628)
	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:409)
	... 7 more
Caused by: org.wso2.andes.client.AMQAuthenticationException: not allowed [error code 530: not allowed]
	at org.wso2.andes.client.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:79)
	at org.wso2.andes.client.handler.ClientMethodDispatcherImpl.dispatchConnectionClose(ClientMethodDispatcherImpl.java:192)
	at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140)
	at org.wso2.andes.client.state.AMQStateManager.methodReceived(AMQStateManager.java:111)
	at org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:517)
	at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467)
	at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:96)
	at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:468)
	at org.wso2.andes.pool.Job.processAll(Job.java:111)
	at org.wso2.andes.pool.Job.run(Job.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
[2018-02-05 12:13:52,415] ERROR - JMSListener Unable to continue server startup as it seems the JMS Provider is not yet started. Please start the JMS provider now.
[2018-02-05 12:13:52,415] ERROR - JMSListener Connection attempt : 1 for JMS Provider failed. Next retry in 20 seconds
[2018-02-05 12:13:52,416] ERROR - AMQStateManager No Waiters for error saving as last error:Exception thrown against AMQConnection:
Host: 172.18.0.1
Port: 5672
Virtual Host: carbon
Client ID: @clientid
Active session count: 0: org.wso2.andes.AMQDisconnectedException: Server closed connection and reconnection not permitted.
[2018-02-05 12:13:52,416] ERROR - AMQConnection Throwable Received but no listener set: org.wso2.andes.AMQDisconnectedException: Server closed connection and reconnection not permitted.
[2018-02-05 12:13:52,422] ERROR - AMQConnection Throwable Received but no listener set: org.wso2.andes.AMQException: AMQP timed out when attempting to close the connection`

**Comment by chalitha87** [comment]
Observed the same issue in APIM update 14 pack also

**Comment by tgtshanika** [comment]
> The "@" character is a reserved character in the WSO2 messaging component. Therefore, when specifing username in JMS Connection URL, under <JMSConnectionParameters> section in the <PRODUCT_HOME>/repository/conf/api-manager.xml file, "@" characters should be replaced by "!" character. An example is shown below.
Please refer https://docs.wso2.com/display/AM220/Maintaining+Logins+and+Passwords
