### ISSUE TITLE
Error in Multi-environment authentication with SSO enabled for production environment

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#2722]
**Description:**
When SSO is disabled in the Development environment and SSO is enabled in the Production environment, I get an error when trying to access the production environment. Therefore, the multi-environment authentication did not work for me. Please investigate into this and fix it.

[1] `{"error_description":"A valid OAuth client could not be found for client_id: d3ba1cb5-b25a-429c-980b-acb271c410cf","error":"invalid_client"} `

[2]

```
[2018-02-09 10:10:22,284] ERROR {org.wso2.carbon.apimgt.rest.api.authenticator.AuthenticatorAPI} - Error while receiving tokens for OAuth application : publisher
[2018-02-09 10:10:22,331] ERROR {org.wso2.carbon.apimgt.rest.api.authenticator.AuthenticatorAPI} - Error while receiving tokens for OAuth application : publisher org.wso2.carbon.apimgt.core.exception.APIManagementException: Error while receiving tokens for OAuth application : publisher
	at org.wso2.carbon.apimgt.rest.api.authenticator.AuthenticatorService.getTokens(AuthenticatorService.java:226)
	at org.wso2.carbon.apimgt.rest.api.authenticator.AuthenticatorAPI.authenticate(AuthenticatorAPI.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:217)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$57(MSF4JHttpConnectorListener.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.apimgt.core.exception.KeyManagementException: Error occurred while generating an access token. Response is null
	at org.wso2.carbon.apimgt.core.impl.DefaultKeyManagerImpl.getNewAccessToken(DefaultKeyManagerImpl.java:318)
	at org.wso2.carbon.apimgt.rest.api.authenticator.AuthenticatorService.getTokens(AuthenticatorService.java:213)
	... 12 more

```

**Affected Product Version:**
Version that was merged to create M17 pack

**Steps to reproduce:**

1. Access the Publisher of the UI service
2. Select development
3. Enter my credentials
4. Click login. I was able to navigate to the development environment successfully. 
5. From the Publisher UI dropdown menu select Production, which has SSO enabled.
6. Click "View Login".
 I get the following error on the UI [1] and an error [2] in the terminal that is running the production environment APIM distribution. 

**Assignee:**
Renuka Fernando - https://github.com/RenukaFernando

**Related Issues:**
https://github.com/wso2/product-apim/issues/2723

**Comment by Mariangela** [comment]
When I checked all the configurations, I discovered that the steps involved in "Configuring WSO2 API-M with the external Identity Provider" had got omitted when formatting the code and replacing it. In addition, the common multi-environment support configurations for the development configurations had the wrong environmentLabel: tag. This error may have stemmed from one of the latter mentioned mistakes.
