### ISSUE TITLE
Error in Multi-environment authentication with SSO disabled in dev and prod environment

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#2723]
**Description:**
I am able to log into the Development environment successfully and when I do so I get the following INFO messages in the terminal [1],  at the same time I get get error [2] in the IS production terminal I get error [3], and I have to sign in again to access the production environment.

[1]
```
[2018-02-10 22:55:05,770]  INFO {org.wso2.carbon.identity.oauth.config.OAuthServerConfiguration} -  The default OAuth token issuer will be used. No custom token generator is set.
[2018-02-10 22:55:05,771]  INFO {org.wso2.carbon.identity.oauth.config.OAuthServerConfiguration} -  The default Identity OAuth token issuer will be used. No custom token generator is set.

```

[2] 
`[2018-02-10 22:56:09,322] ERROR {org.wso2.carbon.identity.oauth2.grant.jwt.JWTBearerGrantHandler} -  No Registered IDP found for the JWT with issuer name : https://localhost:9443/oauth2/token `

[3] 
```
osgi> [2018-02-10 18:13:29,543] ERROR {org.wso2.carbon.apimgt.rest.api.authenticator.AuthenticatorAPI} - Error while receiving tokens for OAuth application : publisher
[2018-02-10 18:13:29,555] ERROR {org.wso2.carbon.apimgt.rest.api.authenticator.AuthenticatorAPI} - Error while receiving tokens for OAuth application : publisher org.wso2.carbon.apimgt.core.exception.APIManagementException: Error while receiving tokens for OAuth application : publisher
	at org.wso2.carbon.apimgt.rest.api.authenticator.AuthenticatorService.getTokens(AuthenticatorService.java:226)
	at org.wso2.carbon.apimgt.rest.api.authenticator.AuthenticatorAPI.authenticate(AuthenticatorAPI.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:217)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$57(MSF4JHttpConnectorListener.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.apimgt.core.exception.KeyManagementException: Token generation request failed. HTTP error code: 400 Error Response Body: {"error_description":"No Registered IDP found for the JWT with issuer name : https://localhost:9443/oauth2/token","error":"invalid_grant"}
	at org.wso2.carbon.apimgt.core.impl.WSO2ISKeyManagerImpl.getNewAccessToken(WSO2ISKeyManagerImpl.java:338)
	at org.wso2.carbon.apimgt.rest.api.authenticator.AuthenticatorService.getTokens(AuthenticatorService.java:213)
	... 12 more
```

**Suggested Assignees:**
Renuka Fernando

**Affected Product Version:**
Version that was merged to create M17 pack

**OS, DB, other environment details and versions:**    
OS - Mac OS
Browser - Chrome

**Comment by Mariangela** [comment]
I managed to overcome this issue. Therefore, I am closing this issue to indicate that it was not a bug in the first place. The issue was caused due to only the production and development environment APIM packs being replaced when the packs got corrupt, where as when I replaced the corresponding IS packs as well this issue went away. For more information, see [1]

[1] https://wso2.org/jira/browse/DOCUMENTATION-7716?focusedCommentId=142506&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-142506
