### ISSUE TITLE
[APIM] [BPS] [WorkFlow] Unable to perform subscription approval process when a user logged into Admin portal with case insenitve username

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-apim#2750]
**Description:**
When a user who has assigned to a role which is allowed to perform subscription approval in a human task with BPS and the user logged into admin console with a case insensitive username, subscription approval fails.

**Affected Product Version:**
API Manager 2.1.0, Business Process Server 3.6.0

**OS, DB, other environment details and versions:**  
Active Directory as Primary Userstore 
JDK - 1.8
DB - mysql 5.6
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

**Steps to reproduce:**

1. Follow steps in [1] to add an API Subscription Workflow with BPS and APIM. 
       -  Let's assume, we have set 'adminTest' role in 'SubscriptionsApprovalTask.ht' file which has necessary permissions to login to Admin Console.
2. Create and API and Publish to the Store.
3. Create a user with uppercase letters (ex- TESTUSER) for the username and assigned to 'adminTest' role. 
4. Login into the store with a user who has subscriber permissions, create an application and subscribe to the created API.
       - API subscription shouldn't proceed and state should change to 'ON-HOLD'
5. Login to the Admin Portal with the created user who has assigned to 'adminTest' role before. When login to the admin portal just use the username with a mix of case sensitive letters (ex-teSTuseER).
6. Go to 'SUBSCRIPTIONS CREATION' in Admin Portal and click 'Assign to Me' button for the created task to approval.

**Actual Outcome**

Following exception thrown in BPS backend and user unable to perform subscription approval task.

````
[2018-02-15 12:37:18,953] ERROR {org.wso2.carbon.humantask.core.api.client.TaskOperationsImpl} -  The user[MANEESHA] cannot perform loadTask() operation as either he is in EXCLUDED_OWNERS role or he is not in task roles [[ACTUAL_OWNER, BUSINESS_ADMINISTRATORS, NOTIFICATION_RECIPIENTS, POTENTIAL_OWNERS, STAKEHOLDERS, TASK_INITIATOR]]
[2018-02-15 12:37:18,953] ERROR {org.wso2.carbon.humantask.core.api.client.TaskOperationsImpl} -  Error occurred while loading task: 4551
org.wso2.carbon.humantask.core.engine.runtime.api.HumanTaskIllegalAccessException: Access Denied. You are not authorized to perform this task
	at org.wso2.carbon.humantask.core.api.client.TaskOperationsImpl.authoriseToLoadTask(TaskOperationsImpl.java:568)
	at org.wso2.carbon.humantask.core.api.client.TaskOperationsImpl.access$400(TaskOperationsImpl.java:92)
	at org.wso2.carbon.humantask.core.api.client.TaskOperationsImpl$9.call(TaskOperationsImpl.java:529)
	at org.wso2.carbon.humantask.core.api.client.TaskOperationsImpl$9.call(TaskOperationsImpl.java:523)
	at org.wso2.carbon.humantask.core.scheduler.SimpleScheduler.execTransaction(SimpleScheduler.java:879)
	at org.wso2.carbon.humantask.core.scheduler.SimpleScheduler.execTransaction(SimpleScheduler.java:828)
	at org.wso2.carbon.humantask.core.api.client.TaskOperationsImpl.loadTask(TaskOperationsImpl.java:522)
	at org.wso2.carbon.humantask.client.api.HumanTaskClientAPIAdminMessageReceiverInOut.invokeBusinessLogic(HumanTaskClientAPIAdminMessageReceiverInOut.java:605)
	at org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:40)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.axis2.transport.http.HTTPTransportUtils.processHTTPPostRequest(HTTPTransportUtils.java:173)
	at org.apache.axis2.transport.http.AxisServlet.doPost(AxisServlet.java:146)
	at org.wso2.carbon.core.transports.CarbonServlet.doPost(CarbonServlet.java:231)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.CSRFPreventionFilter.doFilter(CSRFPreventionFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.CRLFPreventionFilter.doFilter(CRLFPreventionFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1749)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1708)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[2018-02-15 12:37:18,954] ERROR {org.wso2.carbon.humantask.core.api.client.TaskOperationsImpl} -  org.wso2.carbon.humantask.core.engine.runtime.api.HumanTaskIllegalAccessException: Access Denied. You are not authorized to perform this task
````

**Expected Outcome**

User should be able to perform subscription approval process even he/she logged with case insensitive username.

**Comment by nawaz123** [comment]
Can we create user(custom user other than admin) for read only and api approval in api store.
  "taskType = "ApproveSubscription";"

**Comment by dushaniw** [comment]
Issue occurs in BPS side when loading the task for the user with the case insensitive user name. Issue https://github.com/wso2/product-ei/issues/2263 created.  Hence closing this.

**Comment by bhathiya** [comment]
Closing the ticket as this should be fixed in BPS side.
