### ISSUE TITLE
Getting SQL Exceptions once run the forgetme.sh

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2853]
**Description:**
Getting below exceptions[2] once ran bin/forgetme.sh as below[1]
[1] >./forgetme.sh -U <userName>

[2]
```java
java.util.concurrent.ExecutionException: org.wso2.carbon.privacy.forgetme.api.runtime.InstructionExecutionException: Error occurred while executing sql from : /Users/cjayawardena/Documents/Testing/APIM/update13/wso2am-2.1.0-update13/repository/components/tools/identity-anonymization-tool/conf/sql/identity
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.waitForCompletion(ForgetMeExecutionEngine.java:109)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.execute(ForgetMeExecutionEngine.java:91)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.process(ForgetMeTool.java:188)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.main(ForgetMeTool.java:128)
Caused by: org.wso2.carbon.privacy.forgetme.api.runtime.InstructionExecutionException: Error occurred while executing sql from : /Users/cjayawardena/Documents/Testing/APIM/update13/wso2am-2.1.0-update13/repository/components/tools/identity-anonymization-tool/conf/sql/identity
	at org.wso2.carbon.privacy.forgetme.sql.instructions.RdbmsForgetMeInstruction.execute(RdbmsForgetMeInstruction.java:141)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine$ProcessorPipeline.call(ForgetMeExecutionEngine.java:217)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine$ProcessorPipeline.call(ForgetMeExecutionEngine.java:188)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.privacy.forgetme.sql.exception.SQLModuleException: org.h2.jdbc.JdbcSQLException: Table "IDN_USER_ACCOUNT_ASSOCIATION" not found; SQL statement:
UPDATE IDN_USER_ACCOUNT_ASSOCIATION
SET USER_NAME =  ?
WHERE USER_NAME =  ?
      AND DOMAIN_NAME =  ?
      AND TENANT_ID =  ?  [42102-140]
	at org.wso2.carbon.privacy.forgetme.sql.module.DomainSeparatedSQLExecutionModule.execute(DomainSeparatedSQLExecutionModule.java:95)
	at org.wso2.carbon.privacy.forgetme.sql.module.DomainSeparatedSQLExecutionModule.execute(DomainSeparatedSQLExecutionModule.java:36)
	at org.wso2.carbon.privacy.forgetme.sql.instructions.RdbmsForgetMeInstruction.execute(RdbmsForgetMeInstruction.java:100)
	... 6 more
Caused by: org.h2.jdbc.JdbcSQLException: Table "IDN_USER_ACCOUNT_ASSOCIATION" not found; SQL statement:
UPDATE IDN_USER_ACCOUNT_ASSOCIATION
SET USER_NAME =  ?
WHERE USER_NAME =  ?
      AND DOMAIN_NAME =  ?
      AND TENANT_ID =  ?  [42102-140]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.Parser.readTableOrView(Parser.java:4498)
	at org.h2.command.Parser.readTableOrView(Parser.java:4478)
	at org.h2.command.Parser.readSimpleTableFilter(Parser.java:683)
	at org.h2.command.Parser.parseUpdate(Parser.java:641)
	at org.h2.command.Parser.parsePrepared(Parser.java:414)
	at org.h2.command.Parser.parse(Parser.java:275)
	at org.h2.command.Parser.parse(Parser.java:247)
	at org.h2.command.Parser.prepare(Parser.java:201)
	at org.h2.command.Parser.prepareCommand(Parser.java:214)
	at org.h2.engine.Session.prepareLocal(Session.java:434)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1071)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:234)
	at com.zaxxer.hikari.proxy.ConnectionProxy.prepareStatement(ConnectionProxy.java:265)
	at com.zaxxer.hikari.proxy.HikariConnectionProxy.prepareStatement(HikariConnectionProxy.java)
	at org.wso2.carbon.privacy.forgetme.sql.util.NamedPreparedStatement.<init>(NamedPreparedStatement.java:72)
	at org.wso2.carbon.privacy.forgetme.sql.util.NamedPreparedStatement.<init>(NamedPreparedStatement.java:83)
	at org.wso2.carbon.privacy.forgetme.sql.module.DomainSeparatedSQLExecutionModule.execute(DomainSeparatedSQLExecutionModule.java:70)
	... 8 more
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
wso2apim2.1.0-update13

**OS, DB, other environment details and versions:**    
MacOs, jdk1.8.0_152, H2

**Steps to reproduce:**
1. Start APIM 
2. Register an user on the store
3. login to the store as the new user
4. run ./forgetme.sh -U <userName>

**Comment by chamilaadhi** [comment]
You have to configure the datasources first. You have to configure the datasource files in repository/components/tools/identity-anonymization-tool/conf/datasources location. 

refer https://docs.wso2.com/display/ADMIN44x/Removing+References+to+Deleted+User+Identities+in+WSO2+Products#RemovingReferencestoDeletedUserIdentitiesinWSO2Products-Configuringtheconfig.jsonfile

**Comment by tharikaGitHub** [comment]
Fixed with https://github.com/wso2/identity-anonymization-tool/pull/57

**Comment by tharikaGitHub** [comment]
Fixed by adding relative paths to the config.json so that the user does not have to manually configure the path.
