### ISSUE TITLE
SP initiated SSO / IdP initiated SSO - login failed for Publisher/Store/admin apps.

### ISSUE THREAD

**Issue by ChamNDeSilva** [wso2/product-apim#2981]
**Description:**
The issue https://github.com/wso2/product-is/issues/1903 is existing in the product-is.
And after configuring SP initiated SSO, when login to the store/publisher or admin app following error is observed.

> [2018-03-11 11:19:17,464] ERROR - WebAppManager org.mozilla.javascript.WrappedException: Wrapped java.lang.Exception: Failed to get subject assertion from SAML response. (/store/jagg/jaggery_acs.jag#130)
> org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped java.lang.Exception: Failed to get subject assertion from SAML response. (/store/jagg/jaggery_acs.jag#130)
> 	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)
> 	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
> 	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
> 	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
> 	at org.jaggeryjs.jaggery.core.JaggeryServlet.doPost(JaggeryServlet.java:29)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:743)
> 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
> 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
> 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
> 	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:498)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
> 	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
> 	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
> 	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
> 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
> 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
> 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: org.mozilla.javascript.WrappedException: Wrapped java.lang.Exception: Failed to get subject assertion from SAML response. (/store/jagg/jaggery_acs.jag#130)
> 	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
> 	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
> 	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
> 	at org.jaggeryjs.rhino.store.jagg.c2._c_anonymous_1(/store/jagg/jaggery_acs.jag:130)
> 	at org.jaggeryjs.rhino.store.jagg.c2.call(/store/jagg/jaggery_acs.jag)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
> 	at org.jaggeryjs.rhino.store.jagg.c2._c_script_0(/store/jagg/jaggery_acs.jag:5)
> 	at org.jaggeryjs.rhino.store.jagg.c2.call(/store/jagg/jaggery_acs.jag)
> 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
> 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
> 	at org.jaggeryjs.rhino.store.jagg.c2.call(/store/jagg/jaggery_acs.jag)
> 	at org.jaggeryjs.rhino.store.jagg.c2.exec(/store/jagg/jaggery_acs.jag)
> 	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
> 	... 45 more
> Caused by: java.lang.Exception: Failed to get subject assertion from SAML response.
> 	at org.wso2.carbon.hostobjects.sso.SAMLSSORelyingPartyObject.jsFunction_getSAMLResponseNameId(SAMLSSORelyingPartyObject.java:660)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
> 	... 57 more
> 
> 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ChamNDeSilva** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/commit/07587eeb3d72eb1cdf3c9c007a3f61a1674f7f5c
