### ISSUE TITLE
[Microgateway]  Cannot Disable Hostname verification

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/product-apim#3180]
**Description:**
Cannot disable Hostname verification in  API Microgateway via configurations. 
Cause for the issue is, configurations are not passed when the HTTP client is created [1].

[1]: [Code base](https://www.google.com/url?q=https://github.com/wso2/carbon-apimgt/blob/6.x/components/apimgt/org.wso2.carbon.apimgt.micro.gateway/org.wso2.carbon.apimgt.micro.gateway.api.synchronizer/src/main/java/org/wso2/carbon/apimgt/micro/gateway/api/synchronizer/APISynchronizer.java%23L270&sa=D&source=hangouts&ust=1523085483523000&usg=AFQjCNGmRXYyGvwMbJqZmbzeSktsOGrg3A)

```
api-manager-gateway_1  | [2018-04-06 06:39:26,656] ERROR - APISynchronizer API Synchronization failed.
api-manager-gateway_1  | org.wso2.carbon.apimgt.micro.gateway.api.synchronizer.exceptions.APISynchronizationException: Failed to generate an access token.
api-manager-gateway_1  |        at org.wso2.carbon.apimgt.micro.gateway.api.synchronizer.APISynchronizer.getAccessToken(APISynchronizer.java:217)
api-manager-gateway_1  |        at org.wso2.carbon.apimgt.micro.gateway.api.synchronizer.APISynchronizer.synchronizeApis(APISynchronizer.java:159)
api-manager-gateway_1  |        at org.wso2.carbon.apimgt.micro.gateway.api.synchronizer.APISynchronizer.completedInitialization(APISynchronizer.java:102)
api-manager-gateway_1  |        at org.wso2.carbon.apimgt.micro.gateway.common.GatewayListenerNotifier.notifyListeners(GatewayListenerNotifier.java:44)
api-manager-gateway_1  |        at org.wso2.carbon.apimgt.micro.gateway.tenant.initializer.listener.ServerStartupListener$ScheduledThreadPoolExecutorImpl.run(ServerStartupListener.java:120)
api-manager-gateway_1  |        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
api-manager-gateway_1  |        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
api-manager-gateway_1  |        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
api-manager-gateway_1  |        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
api-manager-gateway_1  |        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
api-manager-gateway_1  |        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
api-manager-gateway_1  |        at java.lang.Thread.run(Thread.java:748)
api-manager-gateway_1  | Caused by: org.wso2.carbon.apimgt.micro.gateway.common.exception.OnPremiseGatewayException: POST request failed for the maximum no. of attempts(3) for URL: https://api-manager:9443/client-registration/v0.12/register
api-manager-gateway_1  |        at org.wso2.carbon.apimgt.micro.gateway.common.util.HttpRequestUtil.handleExceptionWithRetry(HttpRequestUtil.java:205)
api-manager-gateway_1  |        at org.wso2.carbon.apimgt.micro.gateway.common.util.HttpRequestUtil.executeHTTPMethodWithRetry(HttpRequestUtil.java:96)
api-manager-gateway_1  |        at org.wso2.carbon.apimgt.micro.gateway.common.util.TokenUtil.registerClient(TokenUtil.java:152)
api-manager-gateway_1  |        at org.wso2.carbon.apimgt.micro.gateway.common.util.TokenUtil.registerClient(TokenUtil.java:97)
api-manager-gateway_1  |        at org.wso2.carbon.apimgt.micro.gateway.api.synchronizer.APISynchronizer.getAccessToken(APISynchronizer.java:205)
api-manager-gateway_1  |        ... 11 more
api-manager-gateway_1  | Caused by: javax.net.ssl.SSLException: hostname in certificate didn't match: <api-manager> != <localhost>
api-manager-gateway_1  |        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:238)
api-manager-gateway_1  |        at org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:54)
api-manager-gateway_1  |        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:159)
api-manager-gateway_1  |        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:140)
api-manager-gateway_1  |        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:301)
api-manager-gateway_1  |        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:291)
api-manager-gateway_1  |        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:259)
api-manager-gateway_1  |        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:125)
api-manager-gateway_1  |        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:319)
api-manager-gateway_1  |        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
api-manager-gateway_1  |        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
api-manager-gateway_1  |        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
api-manager-gateway_1  |        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
api-manager-gateway_1  |        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
api-manager-gateway_1  |        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
api-manager-gateway_1  |        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
api-manager-gateway_1  |        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
api-manager-gateway_1  |        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
api-manager-gateway_1  |        at org.wso2.carbon.apimgt.micro.gateway.common.util.HttpRequestUtil.executeHTTPMethodWithRetry(HttpRequestUtil.java:86)
api-manager-gateway_1  |        ... 14 more
```

**Affected Product Version:**
2.2.0

**OS, DB, other environment details and versions:**    
Docker Compose

**Steps to reproduce:**
Configure Micro gateway with Hostname for API manager other than "localhost". (Set hostname in /etc/hosts as well)

**Related Issues:**

**Comment by npamudika** [comment]
This issue has been fixed via https://github.com/wso2/carbon-apimgt/pull/5325
