### ISSUE TITLE
Service Provider API ApplicationManagementServiceImpl updateApplication method fails

### ISSUE THREAD

**Issue by jairo-fernandez** [wso2/product-apim#3275]
**Description:**
After creating a service provider using the web console, I use the admin API to update the claims of this service provider and it fails with a Null Pointer Exception.

**Suggested Labels:**
service provider, claims, update application

**Suggested Assignees:**

**Affected Product Version:**
API Manager 2.1.0, 2.2.0, 2.2.0 update 5

**OS, DB, other environment details and versions:**    
Windows 10, fresh install

**Steps to reproduce:**
1. Go to web management console
2. Register a new service provider only specifying its name.
3. Use SOAPUI or any other SOAP client and send the following request to add a claim to the service provider:
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://org.apache.axis2/xsd" xmlns:xsd1="http://model.common.application.identity.carbon.wso2.org/xsd">
   <soap:Header/>
   <soap:Body>
      <xsd:updateApplication>
         <xsd:serviceProvider>
         		<xsd1:applicationID>1</xsd1:applicationID>
         		<xsd1:claimConfig>
				<xsd1:claimMappings>
	                  <xsd1:localClaim>
	                     <xsd1:claimUri>http://wso2.org/claims/role</xsd1:claimUri>
	                  </xsd1:localClaim>
	                  <xsd1:mandatory>true</xsd1:mandatory>
               	</xsd1:claimMappings>
               	<xsd1:localClaimDialect>true</xsd1:localClaimDialect>
            	</xsd1:claimConfig>
            </xsd:serviceProvider>
      </xsd:updateApplication>
   </soap:Body>
</soap:Envelope>

in SOAP UI I get this error:
<faultstring>Exception occurred while trying to invoke service method updateApplication</faultstring>

and the server logs have:
[2018-05-11 14:33:38,518] ERROR - RPCMessageReceiver Exception occurred while trying to invoke service method updateApplication
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)  .... 

Caused by: java.lang.NullPointerException
        at org.wso2.carbon.identity.application.mgt.cache.IdentityServiceProviderCacheKey.hashCode(IdentityServiceProviderCacheKey.java:73)
        at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106)
        at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097)
        at org.wso2.carbon.caching.impl.CacheImpl.removeLocal(CacheImpl.java:524)
        at org.wso2.carbon.caching.impl.CacheImpl.remove(CacheImpl.java:505)
        at org.wso2.carbon.identity.application.common.cache.BaseCache.clearCacheEntry(BaseCache.java:185)
        at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.updateApplication(ApplicationManagementServiceImpl.java:257)
        at org.wso2.carbon.identity.application.mgt.ApplicationManagementAdminService.updateApplication(ApplicationManagementAdminService.java:137)
        ... 59 more	

**Related Issues:**

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
