### ISSUE TITLE
Error publishing APIs for tenant with tenant ID length is about 10 or greater

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#3379]
**Description:**

When trying to publish APIs for a tenant created with a tenant ID having about 10 or greater number of digits, the following error is observed.

[AM]ERROR
{org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO} - Error while executing SQL {org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO}
**com.mysql.jdbc.exceptions.jdbc4.MySQLDataException: '1.528380313E9' in column '4' is outside valid range for the datatype SMALLINT.**
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)
TID: [-1234] [] [2018-06-08 06:00:13,796] ERROR
{JAGGERY.site.blocks.item-design.ajax.add:jag}

**Affected Product Version:**
APIM 2.2

**Comment by tharikaGitHub** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5441/files
