### ISSUE TITLE
Issue creating WS API through the REST API

### ISSUE THREAD

**Issue by chamarasilva** [wso2/product-apim#3468]
I used below request xml in creating WS API through the REST API.

`{
   "name": "sample1235656",
   "description": "This document describe a RESTFul API for Pizza Shack online pizza delivery store.\r\n",
   "context": "/sample1236666",
   "version": "1.0.0",
   "provider": "admin",
   "type": "WS",
   "transport":    ["WS"],
   "tags": ["pizza"],
   "tiers": ["Unlimited"],
   "maxTps":    {
      "sandbox": 5000,
      "production": 1000
   },
   "visibility": "PUBLIC",
   "visibleRoles": [],
   "endpointConfig": "{\"production_endpoints\":{\"url\":\"ws://google.com\",\"config\":null,\"template_not_supported\":false},\"sandbox_endpoints\":{\"url\":\"ws://google.com\",\"config\":null,\"template_not_supported\":false},\"endpoint_type\":\"http\"}",
   "endpointSecurity":    {
      "username": "user",
      "type": "basic",
      "password": "pass"
   },
   "gatewayEnvironments": "Production and Sandbox",
   "sequences": [],
   "isDefaultVersion":true,
   "subscriptionAvailability": null,
   "subscriptionAvailableTenants": [],
   "businessInformation":    {
      "businessOwnerEmail": "marketing@pizzashack.com",
      "technicalOwnerEmail": "architecture@pizzashack.com",
      "technicalOwner": "John Doe",
      "businessOwner": "Jane Roe"
   
   }
}`
There was an error without add transport property. Therefore transport property is made as a mandatory. AFAIK this should not be a mandatory property in WS API. 

Without "transport" property I am getting below error.
`[2018-06-19 12:21:00,064]  INFO - CarbonAuthenticationUtil 'admin@carbon.super [-1234]' logged in at [2018-06-19 12:21:00,064+0100]
[2018-06-19 12:21:00,078]  INFO - DependencyTracker Sequence : _PRODUCTION_-Asdasa-v1 was  removed from the Synapse configuration successfully
[2018-06-19 12:21:00,090]  INFO - DependencyTracker Sequence : _SANDBOX_-Asdasa-v1 was  removed from the Synapse configuration successfully
[2018-06-19 12:22:11,525] ERROR - UserAwareAPIProvider Unsupported Transport []
[2018-06-19 12:22:11,526] ERROR - ApisApiServiceImpl Error while adding new API : admin-sample1235656-1.0.0
org.wso2.carbon.apimgt.api.APIManagementException: Error in adding API :sample1235656
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPI(APIProviderImpl.java:714)
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addAPI(UserAwareAPIProvider.java:63)
	at org.wso2.carbon.apimgt.rest.api.publisher.impl.ApisApiServiceImpl.apisPost(ApisApiServiceImpl.java:259)
	at org.wso2.carbon.apimgt.rest.api.publisher.ApisApi.apisPost(ApisApi.java:574)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)`

With transport with "WS" also giving an error. 
`[2018-06-19 13:47:03,815] ERROR - UserAwareAPIProvider Unsupported Transport [WS]
[2018-06-19 13:47:03,817] ERROR - ApisApiServiceImpl Error while adding new API : admin-sample1235656-1.0.0
org.wso2.carbon.apimgt.api.APIManagementException: Error in adding API :sample1235656`

Having transport= http made the successful WS API creation, but this seems to be wrong.

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
