### ISSUE TITLE
Error on searching for APIs when Debug logs enabled

### ISSUE THREAD

**Issue by Thivya01** [wso2/product-apim#3587]
**Description:**
Executing search API

curl -X GET 'https://localhost:9443/api/am/publisher/v0.11/apis?query=pizza' -H 'Authorization: Bearer c10606e9-65fd-3ded-a3ca-12bcb0272b56' -k -v

Response: Internal server error 500

 ERROR -  An Unknown exception has been captured by global exception mapper. {org.wso2.carbon.apimgt.rest.api.util.exception.GlobalThrowableMapper}
java.lang.NullPointerException
        at org.wso2.carbon.apimgt.rest.api.util.impl.WebAppAuthenticatorImpl.validateScopes(WebAppAuthenticatorImpl.java:151)
        at org.wso2.carbon.apimgt.rest.api.util.impl.WebAppAuthenticatorImpl.authenticate(WebAppAuthenticatorImpl.java:74)
        at org.wso2.carbon.apimgt.rest.api.util.interceptors.auth.OAuthAuthenticationInterceptor.handleRequest(OAuthAuthenticationInterceptor.java:112)
        at org.wso2.carbon.apimgt.rest.api.util.interceptors.auth.OAuthAuthenticationInterceptor.handleMessage(OAuthAuthenticationInterceptor.java:57)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)

When debug logs are  not enabled the search API call works fine.

**Suggested Labels:**
APIM 2.1.0

**Affected Product Version:**

**Steps to reproduce:**

- Change the level of log is changed to "DEBUG" for the following logger.
org.wso2.carbon.apimgt.rest.api.util.impl.WebAppAuthenticatorImpl

- Execute the search API

curl -X GET 'https://localhost:9443/api/am/publisher/v0.11/apis?query=pizza' -H 'Authorization: Bearer c10606e9-65fd-3ded-a3ca-12bcb0272b56' -k -v

**Comment by vithu30** [comment]
Fixed in [Add fix for #3587](https://github.com/wso2/carbon-apimgt/pull/5587)
