### ISSUE TITLE
ClassNotFoundException occurs when using json_validator in a distributed deployment 

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-apim#3590]
**Description:**
When using the json_validator in a distributed deployment of APIM. It gives the following error in the gateway node
`java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonParseException
at org.wso2.carbon.apimgt.gateway.threatprotection.pool.JSONAnalyzerFactory.create(JSONAnalyzerFactory.java:32)
at org.wso2.carbon.apimgt.gateway.threatprotection.pool.JSONAnalyzerFactory.create(JSONAnalyzerFactory.java:29)
at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:60)
at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:458)
at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
at org.wso2.carbon.apimgt.gateway.threatprotection.AnalyzerHolder.getAnalyzer(AnalyzerHolder.java:86)
at org.wso2.carbon.apimgt.gateway.mediators.JsonSchemaValidator.mediate(JsonSchemaValidator.java:79)
at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:93)
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:214)
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.mediate(APIManagerExtensionHandler.java:58)
at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleRequest(APIManagerExtensionHandler.java:75)
at org.apache.synapse.rest.API.process(API.java:325)
at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:90)
at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:303)
at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:92)
at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:337)
at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:383)
at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonParseException cannot be found by org.wso2.carbon.apimgt.gateway_6.2.201
at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 31 more`

**Suggested Labels:**
Bug

**Affected Product Version:**
WSO2 APIM 2.2.0

**Steps to reproduce:**
1. Create a distributed APIM setup
2. Create a sample API and engage json_validator
3. Call the API

**Comment by uvindra** [comment]
Following needs to added to _repository/components/gateway-worker/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info_ in order to fix the issue

`com.fasterxml.jackson.core.jackson-annotations,2.9.3,../plugins/com.fasterxml.jackson.core.jackson-annotations_2.9.3.jar,4,true
com.fasterxml.jackson.core.jackson-core,2.9.3,../plugins/com.fasterxml.jackson.core.jackson-core_2.9.3.jar,4,true
com.fasterxml.jackson.core.jackson-databind,2.9.3,../plugins/com.fasterxml.jackson.core.jackson-databind_2.9.3.jar,4,true
com.fasterxml.jackson.dataformat.jackson-dataformat-yaml,2.9.3,../plugins/com.fasterxml.jackson.dataformat.jackson-dataformat-yaml_2.9.3.jar,4,true`

**Comment by bhathiya** [comment]
Fixed by https://github.com/wso2/carbon-apimgt/pull/5602
