### ISSUE TITLE
Fix EmailUserNameLoginTestCase

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#3636]
**Description:**
With the kernel upgrade to version 4.4.34 from 4.4.32, this test case fails with the following exception.

```
org.wso2.carbon.tenant.mgt.stub.TenantMgtAdminServiceExceptionException: TenantMgtAdminServiceExceptionException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.wso2.carbon.tenant.mgt.stub.TenantMgtAdminServiceStub.addTenant(TenantMgtAdminServiceStub.java:2565)
	at org.wso2.am.integration.tests.login.EmailUserNameLoginTestCase.createTenantWithEmailUserName(EmailUserNameLoginTestCase.java:166)
	at org.wso2.am.integration.tests.login.EmailUserNameLoginTestCase.LoginWithEmailUserNameTestCase(EmailUserNameLoginTestCase.java:100)
```

But no issue is seen when manually trying to addTenant through the management console or even when invoking the TenantMgtAdminService after enabling email username.

This testcase should be fixed after further investigation.

Note: This test doesn't fail when upgraded to kernel version 4.4.33.

**Comment by tharikaGitHub** [comment]
This test case is temporarily commented out with commit https://github.com/wso2/product-apim/pull/3637/commits/132cb0fa76140ac84dc2d385c9c9a31fa73ba719

**Comment by tgtshanika** [comment]
This is fixed
