### ISSUE TITLE
ClassNotFoundException: org.wso2.carbon.context.CarbonContext in micro gateway APIExecutionHandler

### ISSUE THREAD

**Issue by prasa7** [wso2/product-apim#3645]
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.context.CarbonContext cannot be found by org.wso2.carbon.apimgt.micro.gateway.common_6.3.95
at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 87 more

**Comment by kavishkafernando** [comment]
which APIM version is this?
