### ISSUE TITLE
Old session on a restarted server creates exception

### ISSUE THREAD

**Issue by Thivya01** [wso2/product-apim#3662]
**Description:**

[2018-08-13 13:07:36,928] ERROR - WebAppManager org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalStateException: isNew: Session already invalidated (/publisher/jagg/jagg.jag#53)
org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalStateException: isNew: Session already invalidated (/publisher/jagg/jagg.jag#53)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doPost(JaggeryServlet.java:29)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:743)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at 
**Suggested Labels:**
APIM

**Affected Product Version:**
APIM 210

**Steps to reproduce:**
This issue can be reproducible when the same session ID is generated by the browser after the session expires. Most of the time we couldn't reproduce this as every time we are getting new session IDs from the browser. We tried making the session timeout value to few minutes in web.xml file configuration under <APIM_HOME>/repositoy/conf folder and tried logging after keeping the publisher for idle until the session expired.

In this time when the same session Id is generated by the browser after it expired when new login this issue can be reproduced. But we are observing different session IDs when i logged the session id every time.

As a solution we can add  error handling during the session invalidation as follows in jagg.jag file.

 var setUser = function (user) {
        //if jaggery allow session reset
        if (typeof request.getSession == "function") {
	   session =  request.getSession(false);

	    try{
            if (session &&!session.isNew()) {
                session.invalidate();
            }
} catch(e) {
log.warn("Session is already invalidated, continuing the flow");
}
            session = request.getSession(true);
        }
        session.put("logged.user", user);
    };

**Comment by bhathiya** [comment]
Fixed by https://github.com/wso2-support/carbon-apimgt/pull/1023
