### ISSUE TITLE
user-mgt.xml has incorrect tags "ISUserStoreManager'"

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#3676]
**Description:**
The WUM updated pack as of 5/8/2018 has the "ISUserStoreManager" tag. When this is enabled the pack doesn't start and gives the following error.  The tag needs to be corrected as "UserStoreManager"

`[2018-09-05 16:37:55,079] ERROR - Activator Cannot start User Manager Core bundle
java.lang.NullPointerException
	at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:86)
	at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:113)
	at org.wso2.carbon.user.core.internal.Activator.startDeploy(Activator.java:68)
	at org.wso2.carbon.user.core.internal.BundleCheckActivator.start(BundleCheckActivator.java:61)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
	at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:*2.1.0*

**OS, DB, other environment details and versions:**    

**Steps to reproduce:* 1) enable the read write ldap by uncommenting ISUserStoreManager and pointing to a up and running LDAP
2) start the server*

**Related Issues:**

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
