### ISSUE TITLE
Issue when downloading API Documentation in API Store

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#3842]
**Description:**
Error occurred while downloading API documentation in Store.
`JavaScriptFileImpl Invalid file path
java.io.FileNotFoundException: Invalid file path
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:238)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124)
	at org.jaggeryjs.hostobjects.file.JavaScriptFileImpl.open(JavaScriptFileImpl.java:47)
	at org.jaggeryjs.hostobjects.file.FileHostObject.jsFunction_open(FileHostObject.java:82)`

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.5.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
Fixed with a90c2e600f0c81247b18834ce41732ca8ba59ce1
