### ISSUE TITLE
Need support to enable Monetization for APIs in APIM 260

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#3889]
**Description:**
We need to get the implementation details in place so that we can have similar content with regard to enabling monetization in API-M 2.6.0. Currently, this information is not available in API-M 2.6.0.

[1] https://docs.wso2.com/display/AM250/Enabling+Monetization+of+APIs

**Affected Product Version:**
APIM 2.6.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by crognon** [comment]
6 month have passed and still no documentation update for monetization using WSO2 APIM 2.6.0 :) is there some document available ?

**Comment by ruks** [comment]
@crognon Please check the following release[1]. It supports APIM 2.6.0 monetization. We hope to provide the instruction and documentation in this repo[2]. You can try it and let us know if you need further help.

[1] https://github.com/ruks/wso2-am-billing-engine/releases/tag/v2.6.0-alpha
[2] https://github.com/ruks/wso2-am-billing-engine

**Comment by dengrand** [comment]
Hi ruks,

I am trying to use your billing workflow code, and I encountered some errors.
After clicking on subscribe, I got this error in wso2APIM store : 

`Caused by: org.apache.http.ProtocolException: Target host is not specified
`
I have replaced the subscription workflow with yours (in /_system/governance/apimgt/applicationdata/workflow-extensions.xml).
I have setup the billing engine following your documentation (in repository/conf/api-manager.xml)
```
   <BillingEngine>
        <BillingEngineUrl>http://localhost:8080/apim-billing-engine-1.4.0/</BillingEngineUrl>
        <ApimStoreUrl>https://localhost:9443/store/</ApimStoreUrl>
    </BillingEngine> 
```

The stacktrace contains :
```
org.apache.http.client.ClientProtocolException
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.wso2.sample.apimgt.impl.BilllingEngineConnectorImpl.checkSubscription(BilllingEngineConnectorImpl.java:31)
        at org.wso2.sample.apimgt.workflow.SubscriptionBillingWorkflow.execute(SubscriptionBillingWorkflow.java:69)
        at org.wso2.carbon.apimgt.impl.APIConsumerImpl.addSubscription(APIConsumerImpl.java:2328)
        at org.wso2.carbon.apimgt.impl.UserAwareAPIConsumer.addSubscription(UserAwareAPIConsumer.java:59)
```
It seems that my billing engine url is not taken into account.

Have I miss something ?

Thank you.

**Comment by dengrand** [comment]
Forget about my last message, after restarting the whole stack, this error was not here anymore. 

I still got a strange behaviour :
I can't sign-in to the billing-app (even after regitered my user).
I don't have any error, and I see the new user in the ysql db. 

I will do a remote debug in order to understand (because I just see an hibernate select in the tomcat logs).

**Comment by ruks** [comment]
I think this is session related issue. Can you please check on prrivate browser. Once you subscribe again to a billing package your subscription will activate again.

**Comment by dengrand** [comment]
Hello,
Thank you, with a private browser window I can log into the billing app.
But when I subscribe I'm not redirected to the store and I always stay in the billing app (and there is not much to do there).
Here are some screenshots : 
https://drive.google.com/drive/folders/1JIqWdsBDWVCHmM01iZWQLu9EnE_Zlbbl?usp=sharing

This makes my subscriptions to be all in the status ON_HOLD (even the ones attached to a free billing plan).

**Comment by ruks** [comment]
@dengrand once you subscribe to a billing package your subscription should be activated, You need to select a billing plan corresponding to the correct API and version. Also, you check the pending subscription in the billing engine menu.

**Comment by dengrand** [comment]
@ruks Thank you, it works fine.
I just didn't know how to use your billing application.
Maybe you could improve the readme with billing app usage.

**Comment by ruks** [comment]
@dengrand sorry for the confusion. Documentation with complete instructions is work in progress. Will update readme once it is completed.

**Comment by nirmal070125** [comment]
This doc is still not available?

**Comment by ruks** [comment]
@Mariangela can we update the 2.6.0 documentation? We can point the documentation to this[1]

[1] https://github.com/ruks/wso2-am-billing-engine/releases/tag/v2.6.0-alpha
