### ISSUE TITLE
Error when setting up the microgateway project

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#3890]
**Description:**
wso2am-2.6.0+1539888688346 & wso2am-micro-gw-2.6.0(fresh pack)
Tested https://docs.wso2.com/display/AM260/Microgateway+Quick+Start#MicrogatewayQuickStart-GenerateadistributionforasingleAPI

While setting up the project(step2), getting the following error in the error log in microgateway. 
```
[2018-10-25 11:17:29,600] ERROR {org.wso2.apimgt.gateway.cli.cmd.Main} - Error while getting the API with name:PizzaShackAPI, version: 1.0.0 
org.wso2.apimgt.gateway.cli.exception.CLIInternalException: Error while getting the API with name:PizzaShackAPI, version: 1.0.0
	at org.wso2.apimgt.gateway.cli.rest.RESTAPIServiceImpl.getAPI(RESTAPIServiceImpl.java:172)
	at org.wso2.apimgt.gateway.cli.cmd.SetupCmd.execute(SetupCmd.java:275)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.wso2.apimgt.gateway.cli.cmd.Main.main(Main.java:50)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "apiSecurity" (class org.wso2.apimgt.gateway.cli.model.rest.ext.ExtendedAPI), not marked as ignorable (37 known properties: "corsConfiguration", "name", "businessInformation", "apiDefinition", "destinationStatsEnabled", "tiers", "visibility", "version", "tags", "id", "apiLevelPolicy", "thumbnailUri", "isDefaultVersion", "endpointConfigRepresentation", "authorizationHeader", "wsdlUri", "transport", "visibleRoles", "context", "provider", "status", "maxTps", "endpointSecurity", "visibleTenants", "type", "description", "subscriptionAvailableTenants", "responseCaching", "cacheTimeout", "sequences", "subscriptionAvailability", "gatewayEnvironments", "endpointConfig", "additionalProperties", "labels", "accessControl", "accessControlRoles"])
 at [Source: (String)"{"count":1,"next":"","previous":"","list":[{"id":"9741f218-287a-44ff-a7a7-c8985b187c31","name":"PizzaShackAPI","description":"This is a simple API for Pizza Shack online pizza delivery store.","context":"/pizzashack","version":"1.0.0","provider":"admin","status":"PUBLISHED","thumbnailUri":"/apis/9741f218-287a-44ff-a7a7-c8985b187c31/thumbnail","apiDefinition":"{\"paths\":{\"/order\":{\"post\":{\"x-auth-type\":\"Application & Application User\",\"x-throttling-tier\":\"Unlimited\",\"description\":\"[truncated 8281 chars]; line: 1, column: 7661] (through reference chain: org.wso2.apimgt.gateway.cli.model.rest.APIListDTO["list"]->java.util.ArrayList[0]->org.wso2.apimgt.gateway.cli.model.rest.ext.ExtendedAPI["apiSecurity"])
```

**Suggested Labels:**
Priority/High
Severity/Critical
Product/wso2am-2.6.0

**Affected Product Version:**
wso2am-2.6.0+1539888688346

**OS, DB, other environment details and versions:**    
OSX

**Comment by praminda** [comment]
Fixed with wso2/product-microgateway#270
