### ISSUE TITLE
Error in creating REST API from WSDL

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#3960]
**Description:**
Error occurred when creating REST API from WSDL. Following error log is observed:

```
WebAppManager org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (/publisher/site/blocks/item-design/ajax/add.jag#540)
org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (/publisher/site/blocks/item-design/ajax/add.jag#540)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doPost(JaggeryServlet.java:29)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
```

```
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.apimgt.impl.soaptorest.util.SequenceUtils.getNestedDefinitionsFromSwagger(SequenceUtils.java:372)
	at org.wso2.carbon.apimgt.impl.soaptorest.util.SequenceUtils.getResourceParametersFromSwagger(SequenceUtils.java:311)
	at org.wso2.carbon.apimgt.impl.soaptorest.SequenceGenerator.generateSequences(SequenceGenerator.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
```

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.6.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by HiranyaKavishani** [comment]
This was fixed by https://github.com/wso2/carbon-apimgt/pull/5814
