### ISSUE TITLE
Fault event should not be published when a matching resource is not found

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/product-apim#3968]
**Description:**

Following error is thrown when the gateway tries to publish the fault event to the analytics server when a matching resource is not found. 

```
[1] [2018-11-14 14:04:31,824]  INFO - LogMediator STATUS = Executing default 'fault' sequence, ERROR_CODE = 405, ERROR_MESSAGE = Method not allowed for given API resource
[2018-11-14 14:04:31,853] ERROR - APIMgtFaultHandler Cannot publish event. null
java.lang.NullPointerException
	at org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtFaultHandler.mediate(APIMgtFaultHandler.java:59)
	at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:94)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:214)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.wso2.carbon.apimgt.gateway.handlers.security.CORSRequestHandler.onResourceNotFoundError(CORSRequestHandler.java:267)
	at org.wso2.carbon.apimgt.gateway.handlers.security.CORSRequestHandler.handleResourceNotFound(CORSRequestHandler.java:249)
	at org.wso2.carbon.apimgt.gateway.handlers.security.CORSRequestHandler.handleRequest(CORSRequestHandler.java:174)
	at org.apache.synapse.rest.API.process(API.java:325)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:303)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:92)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:337)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:383)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.6.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by fazlan-nazeem** [comment]
The null pointer is due to the message context not having the required fields to populate the event. Ideally we should avoid publishing the fault event if it is due to a resource not found.

**Comment by isharac** [comment]
Fixed.
