### ISSUE TITLE
NullPointerException thrown when undeploying synpase API config from Gateway

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#3971]
**Description:**
Following NPE is thrown when undeploying synpase API config from Gateway when an API is being republished

`at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.NullPointerException 
at org.wso2.carbon.apimgt.gateway.handlers.security.oauth.OAuthAuthenticator.destroy(OAuthAuthenticator.java:72) 
at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.destroy(APIAuthenticationHandler.java:92) at org.apache.synapse.rest.API.destroy(API.java:512)
 at org.wso2.carbon.rest.api.service.RestApiAdmin.addApi(RestApiAdmin.java:843) 
at org.wso2.carbon.rest.api.service.RestApiAdmin.addApiFromString(RestApiAdmin.java:78)`

**Comment by uvindra** [comment]
This issue is already fixed in public branch
