### ISSUE TITLE
Cannot import/export  API using apimCLI

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#4060]
**Description:**
Due to the missing visibility attribute in docs, it is cannot proceed import/export API using apimCLI. When exporting the APIs, visibility field is not exported for the docs. 

**Suggested Labels:**
product-apim

**Affected Product Version:**
2.6.0 

**Steps to reproduce:**
Test the Import/Export for PizzaShackAPI API

Ex:-
$ ./apimcli import-api -f PizzaShackAPI_1.0.0.zip -e dev -u admin -p admin -k
ZipFilePath: {path}/.wso2apimcli/exported/apis/PizzaShackAPI_1.0.0.zip 

Error importing API. Status: 500 Internal Server Error Error importing API

In wso2carbon.log:

[2018-11-29 19:06:14,638] ERROR - AbstractFaultChainInitiatorObserver Error occurred during error handling, give up!
org.apache.cxf.interceptor.Fault
	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:170)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:136)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:204)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:94) ...

**Comment by dushaniw** [comment]
fixed with https://github.com/wso2/carbon-apimgt/pull/5893
