### ISSUE TITLE
Issue in building the reponse payload received from backend when the HTTP status code is 202

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#4108]
**Description:**
Following exception occurs when building the response payload received from back-end when the HTTP status code is 202:

`org.apache.axis2.AxisFault: Payload could not be written as JSON.
	at org.apache.synapse.commons.json.JsonUtil.writeAsJson(JsonUtil.java:266)
	at org.apache.synapse.commons.json.JsonFormatter.writeTo(JsonFormatter.java:62)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:617)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:285)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:222)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:527)
	at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:115)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:95)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:57)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:325)
	at org.apache.synapse.rest.API.process(API.java:338)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:90)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:56)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:300)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:569)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:192)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:261)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by vithu30** [comment]
Closing the issue as it is fixed with [#735](https://github.com/wso2/wso2-synapse/pull/735) and [#736](https://github.com/wso2/wso2-synapse/pull/736/files)
