### ISSUE TITLE
Avoid the getUserClaimValues call to WSO2 UserStore during JWT generation

### ISSUE THREAD

**Issue by NipuniC** [wso2/product-apim#4112]
**Description:**

Due to the call for getUserClaimValues UserStore during JWT generation the following WARN logs get printed. 

```
Caused by: org.wso2.carbon.user.core.UserStoreException: UserNotFound: User xxx@gmail.comdoes not exist in: PRIMARY
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:168)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValues(AbstractUserStoreManager.java:694)
	at org.wso2.carbon.apimgt.impl.token.DefaultClaimsRetriever.getClaims(DefaultClaimsRetriever.java:103)

```
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
AM-2.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5906/

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5906
