### ISSUE TITLE
APIM 2.6.0 is not supported for MySQL 8.0

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/product-apim#4181]
**Description:**

The APIM 2.6.0 is not supported for the MySQL 8.0 and it is throwing the below error and server starting will stop. 

ERROR - Activator Cannot start User Manager Core bundle
java.lang.Exception: Error in creating the database

Started the server with the -Dsetu mode and when checking the tables in the database, identified only has created the below tables in the UM database.
REG_CLUSTER_LOCK              |
| REG_CONTENT                   |
| REG_CONTENT_HISTORY           |
| REG_LOG                       |
| REG_PATH    

**Affected Product Version:**
APIM 2.6.0

**OS, DB, other environment details and versions:**    
MySQL 8.0

**Steps to reproduce:**
- Set up the MySQL 8.0 and created the required databases 
- Configured the master-datasources.xml file by pointing to the User management, Registry and AM databases
- Copy the mysql-connector-java-8.0.11.jar to the lib (<APIM_HOME>/repository/components/lib) directory 
- Did the required changes in the required configuration files      
- Started the server with the -Dsetup mode
- Then server startup stopped with the below exceptions

ERROR - Activator Cannot start User Manager Core bundle
java.lang.Exception: Error in creating the database
	at org.wso2.carbon.user.core.common.DefaultRealmService.initializeDatabase(DefaultRealmService.java:353)
	at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:91)
	at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:115)
	at org.wso2.carbon.user.core.internal.Activator.startDeploy(Activator.java:72)
	at org.wso2.carbon.user.core.internal.BundleCheckActivator.start(BundleCheckActivator.java:61)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
	at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.Exception: Error occurred while executing :   CREATE INDEX REG_LOG_IND_BY_REG_LOGTIME USING HASH ON REG_LOG(REG_LOGGED_TIME, REG_TENANT_ID)
	at org.wso2.carbon.utils.dbcreator.DatabaseCreator.executeSQL(DatabaseCreator.java:177)
	at org.wso2.carbon.utils.dbcreator.DatabaseCreator.executeSQLScript(DatabaseCreator.java:333)
	at org.wso2.carbon.utils.dbcreator.DatabaseCreator.createRegistryDatabase(DatabaseCreator.java:61)
	at org.wso2.carbon.user.core.common.DefaultRealmService.initializeDatabase(DefaultRealmService.java:343)
	... 19 more
Caused by: java.sql.SQLSyntaxErrorException: Duplicate key name 'REG_LOG_IND_BY_REG_LOGTIME'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:790)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:675)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy17.execute(Unknown Source)
	at org.wso2.carbon.utils.dbcreator.DatabaseCreator.executeSQL(DatabaseCreator.java:147)
	... 22 more
[2019-01-17 20:19:17,260]  INFO - TaglibUriRule TLD skipped. URI: http://tiles.apache.org/tags-tiles is already defined

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
