### ISSUE TITLE
 FATAL - CarbonServerManager WSO2 Carbon initialization Failed

### ISSUE THREAD

**Issue by liepinshw** [wso2/product-apim#4195]
**Description:**
Following error is returned when executing wso2server.sh -Dprofile=api-key-manager
(no such issue running wso2server.sh without defined profile)
_[root@gwkm2 inbound-endpoints]# sh /usr/lib64/wso2/wso2gwkm/2.6.0/bin/wso2server.sh -Dprofile=api-key-manager
JAVA_HOME environment variable is set to /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre
CARBON_HOME environment variable is set to /usr/lib64/wso2/wso2gwkm/2.6.0
Using Java memory options: -Xms256m -Xmx1024m
[2019-01-22 14:51:09,353]  INFO - CarbonCoreActivator Starting WSO2 Carbon...
[2019-01-22 14:51:09,355]  INFO - CarbonCoreActivator Operating System : Linux 3.10.0-957.1.3.el7.x86_64, amd64
[2019-01-22 14:51:09,355]  INFO - CarbonCoreActivator Java Home        : /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre
[2019-01-22 14:51:09,355]  INFO - CarbonCoreActivator Java Version     : 1.8.0_191
[2019-01-22 14:51:09,355]  INFO - CarbonCoreActivator Java VM          : OpenJDK 64-Bit Server VM 25.191-b12,Oracle Corporation
[2019-01-22 14:51:09,356]  INFO - CarbonCoreActivator Carbon Home      : /usr/lib64/wso2/wso2gwkm/2.6.0
[2019-01-22 14:51:09,356]  INFO - CarbonCoreActivator Java Temp Dir    : /usr/lib64/wso2/wso2gwkm/2.6.0/tmp
[2019-01-22 14:51:09,356]  INFO - CarbonCoreActivator User             : root, en-US, Europe/Riga
[2019-01-22 14:51:09,500]  INFO - DefaultCryptoProviderComponent 'CryptoService.Secret' property has not been set. 'org.wso2.carbon.crypto.provider.SymmetricKeyInternalCryptoProvider' won't be registered as an internal crypto provider. Please set the secret if the provider needs to be registered.
[2019-01-22 14:51:12,208]  INFO - ConsentManagerComponent ConsentManagerComponent is activated.
[2019-01-22 14:51:13,576]  INFO - EmbeddedRegistryService Configured Registry in 1096ms
[2019-01-22 14:51:15,075]  INFO - RegistryCoreServiceComponent Registry Mode    : READ-WRITE
[2019-01-22 14:51:15,549]  INFO - JmxReporterBuilder Creating JMX reporter for Metrics with domain 'org.wso2.carbon.metrics'
[2019-01-22 14:51:15,552]  INFO - AbstractReporter Started JMX reporter for Metrics
[2019-01-22 14:51:19,995]  INFO - SolrClient Default Embedded Solr Server Initialized
[2019-01-22 14:51:22,457]  INFO - UserStoreMgtDSComponent Carbon UserStoreMgtDSComponent activated successfully.
[2019-01-22 14:51:28,997]  INFO - TaglibUriRule TLD skipped. URI: http://tiles.apache.org/tags-tiles is already defined
[2019-01-22 14:51:29,613] FATAL - CarbonServerManager WSO2 Carbon initialization Failed
org.apache.axis2.AxisFault: Exception occured while loading the Axis configuration from /usr/lib64/wso2/wso2gwkm/2.6.0/repository/conf/axis2/axis2.xml
        at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:194)
        at org.apache.axis2.context.ConfigurationContextFactory.createConfigurationContext(ConfigurationContextFactory.java:64)
        at org.wso2.carbon.core.CarbonConfigurationContextFactory.createNewConfigurationContext(CarbonConfigurationContextFactory.java:65)
        at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:399)
        at org.wso2.carbon.core.init.CarbonServerManager.start(CarbonServerManager.java:220)
        at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.activate(CarbonCoreServiceComponent.java:105)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
        at org.eclipse.equinox.http.servlet.internal.Activator.registerHttpService(Activator.java:81)
        at org.eclipse.equinox.http.servlet.internal.Activator.addProxyServlet(Activator.java:60)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.init(ProxyServlet.java:40)
        at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.init(DelegationServlet.java:38)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1230)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1174)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1066)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5370)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5668)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1700)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1690)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.deployment.DeploymentException: org.wso2.carbon.websocket.transport.WebsocketTransportSender cannot be found by axis2_1.6.1.wso2v28
        at org.apache.axis2.deployment.AxisConfigBuilder.processTransportSenders(AxisConfigBuilder.java:712)
        at org.apache.axis2.deployment.AxisConfigBuilder.populateConfig(AxisConfigBuilder.java:124)
        at org.wso2.carbon.core.CarbonAxisConfigurator.populateAxisConfiguration(CarbonAxisConfigurator.java:341)
        at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:192)
        ... 41 more
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.websocket.transport.WebsocketTransportSender cannot be found by axis2_1.6.1.wso2v28
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.apache.axis2.util.Loader.loadClass(Loader.java:261)
        at org.apache.axis2.deployment.AxisConfigBuilder.processTransportSenders(AxisConfigBuilder.java:686)
        ... 44 more
^C[root@gwkm2 inbound-endpoints]#_

**Suggested Labels:**
bug, defect

**Suggested Assignees:**

**Affected Product Version:**
wso2api Manager 2.6.0

**OS, DB, other environment details and versions:**    
CentOS7, java openjdk 1.8.0, MSSQL 2017, setup on Hyper-V VM

**Steps to reproduce:**
1. Install WSO2APIM as follows:
VM1 - AIO
VM2 - mentioned to be started as GW workes ar KM second node.
2. Configure rsync from VM1 to VM2
3. Configure connections among the components.
4. Try to run sh wso2server.sh -Dprofile=api-key-manager on VM2

**Related Issues:**
https://wso2.org/jira/browse/APIMANAGER-5491

Anyway, did not help. Even if it would, rsync still would copy the deleted file.

**Comment by dushaniw** [comment]
Hi @liepinshw 

Before or while you run the server with profile argument, you need to run the profile optimization script, this would disable unnecessary configs and activate only the related bundles. Refer [1] to run the optimization script.

[1] https://docs.wso2.com/display/AM260/Product+Profiles#ProductProfiles-Method1-Optimizingbeforestartingtheserver

**Comment by liepinshw** [comment]
Hi @dushaniw 

Yes, You're right, I've misread the manual and messed both methods.
I see that I've executed: wso2server.sh -Dprofile=api-key-manager
But I shoud execute either profileSetup.sh -Dprofile=api-key-manager before that or run the --optimize clause.
Closing this task.
