### ISSUE TITLE
'value too long' error when adding alert messages to ApimAllAlerts table

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#4245]
**Description:**
ApimAllAlerts table has a column character length of 255 for message field. But when there are lengthy URItemplates the resulting error messages for AbnormalBackendTime alert type can be exceed that character limit resulting in below error.

Error on 'apim_abnormal_response_time_alert_0'. Error in adding events to 'ApimAllAlert' store: Value too long for column "MESSAGE VARCHAR(254)": "'Abnormal response time detected for http... (332)"; SQL statement:
INSERT INTO ApimAllAlert (type , tenantDomain , message , severity , alertTimestamp ) VALUES (?, ?, ?, ?, ?) [22001-196] Dropping event chunk EventChunk{first=null}, error in processing org.wso2.siddhi.core.query.processor.stream.window.LengthWindowProcessor. org.wso2.extension.siddhi.store.rdbms.exception.RDBMSTableException: Error on 'apim_abnormal_response_time_alert_0'. Error in adding events to 'ApimAllAlert' store: Value too long for column "MESSAGE VARCHAR(254)": "'Abnormal response time detected for http... (332)"; SQL statement:
INSERT INTO ApimAllAlert (type , tenantDomain , message , severity , alertTimestamp ) VALUES (?, ?, ?, ?, ?) [22001-196]
at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.add(RDBMSEventTable.java:438)
at org.wso2.siddhi.core.table.record.AbstractRecordTable.add(AbstractRecordTable.java:98)
at org.wso2.siddhi.core.table.Table.addEvents(Table.java:139)
at org.wso2.siddhi.core.query.output.callback.InsertIntoTableCallback.send(InsertIntoTableCallback.java:74)
at org.wso2.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:88)
at org.wso2.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:46)
at org.wso2.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:98)
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:186)
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:96)
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:121)
at org.wso2.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:156)
at org.wso2.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:375)
at org.wso2.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56)
at org.wso2.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:88)
at org.wso2.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:46)
at org.wso2.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:98)
at org.wso2.siddhi.core.query.input.stream.join.JoinProcessor.process(JoinProcessor.java:110)
at org.wso2.siddhi.core.query.processor.stream.window.LengthWindowProcessor.process(LengthWindowProcessor.java:137)
at org.wso2.siddhi.core.query.processor.stream.window.WindowProcessor.processEventChunk(WindowProcessor.java:66)
at org.wso2.siddhi.core.query.processor.stream.AbstractStreamProcessor.process(AbstractStreamProcessor.java:125)
at org.wso2.siddhi.core.query.input.stream.join.JoinProcessor.process(JoinProcessor.java:118)
at org.wso2.siddhi.core.query.input.MultiProcessStreamReceiver.processAndClear(MultiProcessStreamReceiver.java:173)
at org.wso2.siddhi.core.query.input.MultiProcessStreamReceiver.process(MultiProcessStreamReceiver.java:77)
at org.wso2.siddhi.core.query.input.MultiProcessStreamReceiver.receive(MultiProcessStreamReceiver.java:102)
at org.wso2.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:156)
at org.wso2.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:375)
at org.wso2.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56)
at org.wso2.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:88)
at org.wso2.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:46)
at org.wso2.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:98)
at org.wso2.siddhi.core.query.processor.filter.FilterProcessor.process(FilterProcessor.java:60)
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:186)
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:96)
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:132)
at org.wso2.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:179)
at org.wso2.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:380)
at org.wso2.siddhi.core.stream.input.InputDistributor.send(InputDistributor.java:34)
at org.wso2.siddhi.core.stream.input.InputEntryValve.send(InputEntryValve.java:44)
at org.wso2.siddhi.core.stream.input.InputHandler.send(InputHandler.java:61)
at org.wso2.siddhi.core.stream.input.source.PassThroughSourceHandler.sendEvent(PassThroughSourceHandler.java:35)
at org.wso2.siddhi.core.stream.input.source.InputEventHandler.sendEvent(InputEventHandler.java:76)
at org.wso2.siddhi.core.stream.input.source.PassThroughSourceMapper.mapAndProcess(PassThroughSourceMapper.java:66)
at org.wso2.siddhi.core.stream.input.source.SourceMapper.onEvent(SourceMapper.java:136)
at org.wso2.siddhi.core.stream.input.source.InMemorySource$1.onMessage(InMemorySource.java:66)
at org.wso2.siddhi.core.util.transport.InMemoryBroker$MessageBroker.broadcast(InMemoryBroker.java:110)
at org.wso2.siddhi.core.util.transport.InMemoryBroker$MessageBroker.publish(InMemoryBroker.java:117)
at org.wso2.siddhi.core.util.transport.InMemoryBroker.publish(InMemoryBroker.java:41)
at org.wso2.siddhi.core.stream.output.sink.InMemorySink.publish(InMemorySink.java:95)
at org.wso2.siddhi.core.stream.output.sink.Sink.publish(Sink.java:135)
at org.wso2.siddhi.core.stream.output.sink.PassThroughSinkMapper.mapAndSend(PassThroughSinkMapper.java:74)
at org.wso2.siddhi.core.stream.output.sink.SinkMapper.mapAndSend(SinkMapper.java:165)
at org.wso2.siddhi.core.stream.output.sink.SinkCallback.receive(SinkCallback.java:54)
at org.wso2.siddhi.core.stream.output.StreamCallback.receive(StreamCallback.java:72)
at org.wso2.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:156)
at org.wso2.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:375)
at org.wso2.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56)
at org.wso2.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:88)
at org.wso2.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:46)
at org.wso2.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:98)
at org.wso2.siddhi.core.query.input.stream.join.JoinProcessor.process(JoinProcessor.java:110)
at org.wso2.siddhi.core.query.processor.stream.window.LengthWindowProcessor.process(LengthWindowProcessor.java:137)
at org.wso2.siddhi.core.query.processor.stream.window.WindowProcessor.processEventChunk(WindowProcessor.java:66)
at org.wso2.siddhi.core.query.processor.stream.AbstractStreamProcessor.process(AbstractStreamProcessor.java:125)
at org.wso2.siddhi.core.query.input.stream.join.JoinProcessor.process(JoinProcessor.java:118)
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:186)
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:96)
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:121)
at org.wso2.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:156)
at org.wso2.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:375)
at org.wso2.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56)
at org.wso2.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:88)
at org.wso2.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:46)
at org.wso2.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:98)
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:186)
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:96)
at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:132)
at org.wso2.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:179)
at org.wso2.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:380)
at org.wso2.siddhi.core.stream.input.InputDistributor.send(InputDistributor.java:34)
at org.wso2.siddhi.core.stream.input.InputEntryValve.send(InputEntryValve.java:44)
at org.wso2.siddhi.core.stream.input.InputHandler.send(InputHandler.java:61)
at org.wso2.siddhi.core.stream.input.source.PassThroughSourceHandler.sendEvent(PassThroughSourceHandler.java:35)
at org.wso2.siddhi.core.stream.input.source.InputEventHandler.sendEvent(InputEventHandler.java:76)
at org.wso2.extension.siddhi.map.wso2event.source.WSO2SourceMapper.mapAndProcess(WSO2SourceMapper.java:227)
at org.wso2.siddhi.core.stream.input.source.SourceMapper.onEvent(SourceMapper.java:136)
at org.wso2.extension.siddhi.io.wso2event.source.AgentCallbackImpl.receive(AgentCallbackImpl.java:72)
at org.wso2.carbon.databridge.core.internal.queue.QueueWorker.run(QueueWorker.java:80)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcBatchUpdateException: Value too long for column "MESSAGE VARCHAR(254)": "'Abnormal response time detected for http tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt... (332)"; SQL statement:
INSERT INTO ApimAllAlert (type , tenantDomain , message , severity , alertTimestamp ) VALUES (?, ?, ?, ?, ?) [22001-196]
at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1234)
at com.zaxxer.hikari.proxy.StatementProxy.executeBatch(StatementProxy.java:127)
at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.executeBatch(HikariPreparedStatementProxy.java)
at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.batchExecuteQueriesWithRecords(RDBMSEventTable.java:1198)
at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.add(RDBMSEventTable.java:435)
... 91 more

**Affected Product Version:**
APIM Analytics 2.6.0

**Comment by chamindias** [comment]
The same thing has happened in "ApimRequestPatternChangedAlert" as well.
