### ISSUE TITLE
NPE from Gateway when backend API responds with HTTP 204 No Content, when response caching is enabled

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4269]
**Description:**
When response caching is enabled, and the backend responded with no-content, following NPE is thrown from cache mediator.

```
2019-01-22 18:58:23,429] ERROR - SequenceMediator Runtime error occurred while mediating the message
java.lang.NullPointerException
	at org.wso2.carbon.mediator.cache.CacheMediator.processResponseMessage(CacheMediator.java:300)
	at org.wso2.carbon.mediator.cache.CacheMediator.mediate(CacheMediator.java:256)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:100)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:62)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:355)
	at org.apache.synapse.rest.API.process(API.java:338)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:90)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:56)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:304)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:547)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:186)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:263)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by prasa7** [comment]
Fixed in APIM 3.1.0 with https://github.com/wso2-support/carbon-mediation/pull/791
