### ISSUE TITLE
Error while deleting tenancy created in APIM-2.6.0

### ISSUE THREAD

**Issue by KosalaHerath** [wso2/product-apim#4374]
**Description:**
TenantMgtAdminService admin service can be used for tenant deletion and when we trying to delete an existing tenant APIM 2.6.0 produce following error.

```
[2019-02-23 01:09:06,953] ERROR - TenantMgtAdminService Error deleting tenant with domain: abc.com and tenant id: 1.
java.lang.NullPointerException
	at org.wso2.carbon.tenant.mgt.util.TenantMgtUtil.deleteWorkernodesTenant(TenantMgtUtil.java:506)
	at org.wso2.carbon.tenant.mgt.services.TenantMgtAdminService.deleteTenant(TenantMgtAdminService.java:582)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
Fixes [1] [2] hav been done to carbon-multitenancy version **4.6.1** and APIM-2.6.0 uses carbon-multitenancy version **4.6.15**. Therefore need to add this fix to APIM-2.6.0.

[1] https://www.google.com/url?q=https://github.com/wso2-support/carbon4-kernel/pull/547
[2] https://www.google.com/url?q=https://github.com/wso2-support/carbon-multitenancy/pull/36

**Suggested Labels:**
APIM-2.6.0

**Affected Product Version:**
APIM-2.6.0

**Steps to reproduce:**
1. Add following lines to <PRODUCT_HOME>/repository/conf/carbon.xml

```
 <Tenant>
    … 
    … 
    <!-- Flag to enable or disable tenant deletion. By default tenant deletion is enabled-->
    <TenantDelete>true</TenantDelete>
    <!-- Configurations related to listener invocation by tenant admin service-->
    <ListenerInvocationPolicy>
       <!-- Flag to enable or disable listener invocation on tenant delete. This is disabled by default-->
       <InvokeOnDelete>false</InvokeOnDelete>
    </ListenerInvocationPolicy>
 </Tenant>
```
2. Start APIM-2.6.0 WUM updated server and create a tenat with domain name "abc.com"
3. Using SoapUI request to delete "abc.com" domin named tenant. Use followig request to delete the tenant.
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://services.mgt.tenant.carbon.wso2.org">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:deleteTenant>
         <!--Optional:-->
         <ser:tenantDomain>abc.com</ser:tenantDomain>
      </ser:deleteTenant>
   </soapenv:Body>
</soapenv:Envelope>
```

**Comment by amitvineti** [comment]
@kavishkafernando @KosalaHerath  - I am also getting the same error while trying to delete WSO2 tenant on APIM 2.6.0 . What is the fix?
