### ISSUE TITLE
Getting NullPointerException when invoking the REST API to get all global level mediation policies, when sequence have created without the name in the registry

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-apim#4412]
**Description:**
It is possible to add sequences to the registry without the name as below.

```
<sequence xmlns="http://ws.apache.org/ns/synapse">
    <log level="full">
        <property name="IN_MESSAGE" value="IN_MESSAGE"/>
    </log>
</sequence>
```

But when invoking the REST API to get all global level mediation policies, receive the below Nullpointer exception.

```
ERROR - GlobalThrowableMapper An Unknown exception has been captured by global exception mapper.
java.lang.NullPointerException
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getAllGlobalMediationPolicies_aroundBody44(AbstractAPIManager.java:751)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getAllGlobalMediationPolicies(AbstractAPIManager.java:724)
	at org.wso2.carbon.apimgt.rest.api.publisher.impl.PoliciesApiServiceImpl.policiesMediationGet(PoliciesApiServiceImpl.java:40)
	at org.wso2.carbon.apimgt.rest.api.publisher.PoliciesApi.policiesMediationGet(PoliciesApi.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Affected Product Version:**
APIM 2.6.0

**Comment by AnuGayan** [comment]
This was fixed in the latest version
