### ISSUE TITLE
Can not republish API while accessing even with low concurrency

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-apim#4501]
**Description:**
Fails on republishing APIs while accessing them with a concurrency of around 10. This is reproducible in 2.5.0 latest WUM all in one pack.
`TID: [-1234] [] [2019-03-27 13:53:00,436] ERROR {org.wso2.carbon.endpoint.service.EndpointAdmin} -  The name Test--v1.0.0_APIproductionEndpoint is already used within the configuration {org.wso2.carbon.endpoint.service.EndpointAdmin}
TID: [-1234] [] [2019-03-27 13:53:00,451] ERROR {org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceClient} -  Error adding endpoint file to the gateway {org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceClient}
org.apache.axis2.AxisFault: The name Test--v1.0.0_APIproductionEndpoint is already used within the configuration
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:381)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:456)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:227)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.wso2.carbon.endpoint.stub.types.EndpointAdminStub.addEndpoint(EndpointAdminStub.java:3745)
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceClient.addEndpoint_aroundBody0(EndpointAdminServiceClient.java:53)`

**Suggested Labels:**
Bug

**Affected Product Version:**
2.5.0

**Steps to reproduce:**
1. 2.5.0 latest WUM and deploy an simple API with a GET.
2. Write a Jmeter script to invoke this on 10 concurrency.
3. While Jmeter is running, try to edit and republish the API.

**Comment by sanethmaduranga** [comment]
Fixed in https://github.com/wso2/wso2-synapse/pull/1255, https://github.com/wso2/carbon-mediation/pull/1221

**Comment by sanethmaduranga** [comment]
#https://github.com/wso2/wso2-synapse/pull/1255

**Comment by sanethmaduranga** [comment]
#https://github.com/wso2/carbon-mediation/pull/1221

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-mediation/pull/1262 and https://github.com/wso2/wso2-synapse/pull/1255
