### ISSUE TITLE
High CPU load in Gateway nodes during continuous Authentication Failures

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#4529]
**Description:**
Gateway CPU starts to spin at the following thread when a load test is performed in the Authentication failure flow if there is an exception in the producer. (where producerError = true)

```
"PassThroughMessageProcessor-373" #725 prio=5 os_prio=0 tid=0x00007fc8d4138800 nid=0x34c3 runnable [0x00007fc88b50c000]
   java.lang.Thread.State: RUNNABLE
	at org.apache.synapse.transport.passthru.util.RelayUtils.consume(RelayUtils.java:358)
	at org.apache.synapse.transport.passthru.util.RelayUtils.consumeAndDiscardMessage(RelayUtils.java:379)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleAuthFailure_aroundBody22(APIAuthenticationHandler.java:222)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleAuthFailure(APIAuthenticationHandler.java:202)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest_aroundBody10(APIAuthenticationHandler.java:168)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest(APIAuthenticationHandler.java:114)
	at org.apache.synapse.rest.API.process(API.java:343)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:90)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:304)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:78)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:330)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:376)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- <0x00000000d4784db8> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

**Affected Product Version:**
APIM 2.1.0    

**Steps to reproduce:**
1. Create an API with a POST request to send a large payload ~500kB like an image file.
2. Subscribe the API to an Application and Generate keys.
3. Invoke the API through a load test where the Access Token is invalid.
4. Stop the load test suddenly.
5. Continue step 3 and 4 for around 4 times.
6. Take a thread dump while running the load test and observe the spinning thread.

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1312
