### ISSUE TITLE
APIM-Analytics "apim_unusual_ip_access_alert_0.siddhi" file "ts" Id Issue 

### ISSUE THREAD

**Issue by rahalJayawardane** [wso2/product-apim#4694]
**Description:**
**apim_unusual_ip_access_alert_0.siddhi** gives and error when starting the APIM-Analytics 2.6.0 latest wum update (2019-05-10)

**Suggested Labels:**
APIM-Analytics 2.6.0

**Error:**
> org.wso2.siddhi.core.exception.SiddhiAppCreationException: Error on 'apim_unusual_ip_access_alert_0' @ Line: 86. Position: 32, near 'ts.applicationConsumerKey'. Id 'ts' not defined within the current scope org.wso2.carbon.stream.processor.core.internal.exception.SiddhiAppDeploymentException: org.wso2.siddhi.core.exception.SiddhiAppCreationException: Error on 'apim_unusual_ip_access_alert_0' @ Line: 86. Position: 32, near 'ts.applicationConsumerKey'. Id 'ts' not defined within the current scope
at org.wso2.carbon.stream.processor.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:106)
at org.wso2.carbon.stream.processor.core.internal.StreamProcessorDeployer.deploy(StreamProcessorDeployer.java:330)
at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$deployArtifacts$0(DeploymentEngine.java:291)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.deployArtifacts(DeploymentEngine.java:282)
at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:112)
at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.start(DeploymentEngine.java:121)
at org.wso2.carbon.deployment.engine.internal.DeploymentEngineListenerComponent.onAllRequiredCapabilitiesAvailable(DeploymentEngineListenerComponent.java:216)
at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$7(StartupComponentManager.java:266)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:252)
at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
at java.util.TimerThread.mainLoop(Timer.java:555)
at java.util.TimerThread.run(Timer.java:505)

**Related Issues:**
https://github.com/wso2/product-is/issues/5164

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
