### ISSUE TITLE
Error while starting up traffic-manager profile in HA Mode

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4703]
**Description:**

> Could see the following exception while starting Traffic Manager in HA mode

> `TID: [-1] [] [2016-06-30 16:48:30,163] ERROR {org.wso2.carbon.event.processor.manager.core.internal.HAManager} -  CEP HA State syncing failed, No execution plans exist for tenant  -1234 {org.wso2.carbon.event.processor.manager.core.internal.HAManager}
org.wso2.carbon.event.processor.manager.core.exception.EventManagementException: No execution plans exist for tenant  -1234
	at org.wso2.carbon.event.processor.core.internal.CarbonEventProcessorManagementService.restoreState(CarbonEventProcessorManagementService.java:83)
	at org.wso2.carbon.event.processor.manager.core.internal.HAManager.syncState(HAManager.java:336)
	at org.wso2.carbon.event.processor.manager.core.internal.HAManager.access$100(HAManager.java:49)
	at org.wso2.carbon.event.processor.manager.core.internal.HAManager$2.run(HAManager.java:276)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)`

By @amilad from https://wso2.org/jira/browse/APIMANAGER-5159

**Comment by tgtshanika** [comment]
This is a harmless warning message and does not affect the functionality of the traffic manager. Hence resolving.
