### ISSUE TITLE
Hostname verification bug

### ISSUE THREAD

**Issue by vozzy** [wso2/product-apim#4791]
**Description:**
I believe there is a hostname verification bug within API-M v 2.6.0 when trying to generate Keys for an Application in the Store. I changed the default hostname in the configs as well as the keystore key-pair to reflect that. Started the server (WSO2 Carbon started in 954 sec...), turned on wirelogs, deployed PizzaShack API, tried to generate Keys for the Default application.

Admin services called during deployment of the sample API worked. But not the generation of Keys.

The error is:
```TID: [-1234] [] [2019-05-20 21:16:35,429] DEBUG {httpclient.wire.header} -  >> "POST /services/APIKeyMgtSubscriberService HTTP/1.1[\r][\n]" {httpclient.wire.header} TID: [-1234] [] [2019-05-20 21:16:35,430] DEBUG {httpclient.wire.header} -  >> "Content-Type: application/soap+xml; charset=UTF-8; action="urn:createOAuthApplicationByApplicationInfo"[\r][\n]" {httpclient.wire.header}
TID: [-1234] [] [2019-05-20 21:16:35,430] DEBUG {httpclient.wire.header} -  >> "Authorization: Basic YWRtaW46YWRtaW4=[\r][\n]" {httpclient.wire.header}
TID: [-1234] [] [2019-05-20 21:16:35,430] DEBUG {httpclient.wire.header} -  >> "User-Agent: Axis2[\r][\n]" {httpclient.wire.header}
TID: [-1234] [] [2019-05-20 21:16:35,430] DEBUG {httpclient.wire.header} -  >> "Host: wso2-helper.ozcorp.com:9443[\r][\n]" {httpclient.wire.header}

TID: [-1234] [] [2019-05-20 21:16:38,334] DEBUG {httpclient.wire.header} -  << "HTTP/1.1 200 OK[\r][\n]" {httpclient.wire.header}
TID: [-1234] [] [2019-05-20 21:16:38,335] DEBUG {httpclient.wire.content} -  << "l version='1.0' encoding='UTF-8'?><soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"><soapenv:Body><ns:createOAuthApplicationByApplicationInfoResponse xmlns:ns="http://org.apache.axis2/xsd"><ns:return xmlns:ax2114="http://dto.impl.apimgt.carbon.wso2.org/xsd" xmlns:ax2115="http://util.java/xsd" xmlns:ax2106="http://keymgt.apimgt.carbon.wso2.org/xsd" xmlns:ax2108="http://api.apimgt.carbon.wso2.org/xsd" xmlns:ax2110="http://model.api.apimgt.carbon.wso2.org/xsd" xmlns:ax2112="http://base.identity.carbon.wso2.org/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ax2110:OAuthApplicationInfo"><ax2110:appOwner xsi:nil="true"/><ax2110:callBackURL xsi:nil="true"/><ax2110:clientId>JhMYrhTK3eAF8B02sH1vs_GESfka</ax2110:clientId><ax2110:clientName xsi:nil="true"/><ax2110:clientSecret>s8ofoOJ8UXX1gAG5BcEInh9NECga</ax2110:clientSecret><ax2110:isSaasApplication>false</ax2110:isSaasApplication><ax2110:jsonAppAttribute>{}</ax2110:jsonAppAttribute><ax2110:jsonString>{"grant_types":"refresh_token urn:ietf:params:oauth:grant-type:saml2-bearer password client_credentials iwa:ntlm urn:ietf:params:oauth:grant-type:jwt-bearer","redirect_uris":null,"client_name":"admin_DefaultApplication_PRODUCTION"}</ax2110:jsonString><ax2110:tokenType xsi:nil="true"/></ns:return></ns:createOAuthApplicationByApplicationInfoResponse></soapenv:Body></soapenv:Envelope>" {httpclient.wire.content}

TID: [-1234] [] [2019-05-20 21:16:41,541] ERROR {org.wso2.carbon.apimgt.impl.AbstractKeyManager} -  Error while creating tokens - hostname in certificate didn't match: <172.19.0.1> != <wso2-helper.ozcorp.com> {org.wso2.carbon.apimgt.impl.AbstractKeyManager}
javax.net.ssl.SSLException: hostname in certificate didn't match: <172.19.0.1> != <wso2-helper.ozcorp.com>
        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:238)
        at org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:54)
        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:159)
        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:140)
        at org.apache.http.conn.ssl.SSLSocketFactory.verifyHostname(SSLSocketFactory.java:561)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:536)

Caused by: javax.net.ssl.SSLException: hostname in certificate didn't match: <172.19.0.1> != <wso2-helper.ozcorp.com>

```

As you can see it is for some reason expecting 172.19.0.1, however the requested host header is:
`wso2-helper.ozcorp.com:9443`

**Suggested Labels:**
`2.6.0` `security`

**Affected Product Version:**
`2.6.0`

**OS, DB, other environment details and versions:**    
```
vozzy@wso2-helper ~ λ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

vozzy@wso2-helper default λ echo $JAVA_HOME
/opt/java/jdk1.8.0_131
```

**Steps to reproduce:**
- Install wso2am-2.6.0.zip (pattern-1/AIO)
- Change the default key-pair of the wso2carbon.jks and use a hostname of you choosing as the subject (`wso2-helper.ozcorp.com` in my case) - see 
![image](https://user-images.githubusercontent.com/14307482/58091770-c463dd00-7bca-11e9-8d91-09c99ae7e210.png) - also has `DNS Name=wso2-helper.ozcorp.com` as a SAN name.
- Change the configurations of `conf/api-manager.xml` to reflect the hostname change.  

***Attachments***
[attachments.zip](https://github.com/wso2/product-apim/files/3202375/attachments.zip)
Included `wso2carbon.log`, `carbon.xml`, `api-manager.xml`

**Comment by vozzy** [comment]
I believe I have "solved" the issue. 

I changed the following in `api-manager.xml`:

```xml
<RevokeAPIURL>https://${carbon.local.ip}:${https.nio.port}/revoke</RevokeAPIURL>
```
This is quite confusing as to why this solves the issue, as according to the wire logs the revoke endpoint is not even called upon client registration. I think the following documentation page should be more thoroughly explained to include this little niggle;
https://docs.wso2.com/display/AM260/Changing+the+Hostname#7f7c4947f0f244afab254986deb5c6a7
