### ISSUE TITLE
Publisher UI test button doesnt work during required mutual SSL

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4800]
**Description:**

> API in APIM 1.10 using backend with required mutual SSL.
> click the test button in the publisher UI, getting a bad certificate error as below.
> but API invoking is succeeded without issue
`Using SSLEngineImpl.
Ignoring unavailable cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
Ignoring unavailable cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
Ignoring unavailable cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
Ignoring unavailable cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
Ignoring unavailable cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256
Ignoring unavailable cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
Ignoring unavailable cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384
Ignoring unavailable cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 for TLSv1.1
HTTPS-Listener I/O dispatcher-3, READ: TLSv1 Handshake, length = 149
*** ClientHello, TLSv1
RandomCookie:  GMT: 1489055628 bytes = { 231, 158, 123, 70, 248, 143, 186, 54, 60, 14, 207, 85, 142, 66, 172, 254, 146, 186, 220, 202, 20, 214, 26, 125, 24, 111, 179, 243 }
Session ID:  {}
Cipher Suites: [TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_ECDSA_WITH_RC4_128_SHA, TLS_ECDHE_RSA_WITH_RC4_128_SHA, SSL_RSA_WITH_RC4_128_SHA, TLS_ECDH_ECDSA_WITH_RC4_128_SHA, TLS_ECDH_RSA_WITH_RC4_128_SHA, SSL_RSA_WITH_RC4_128_MD5, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
Compression Methods:  { 0 }
Extension elliptic_curves, curve names: {secp256r1, sect163k1, sect163r2, secp192r1, secp224r1, sect233k1, sect233r1, sect283k1, sect283r1, secp384r1, sect409k1, sect409r1, secp521r1, sect571k1, sect571r1, secp160k1, secp160r1, secp160r2, sect163r1, secp192k1, sect193r1, sect193r2, secp224k1, sect239k1, secp256k1}
Extension ec_point_formats, formats: [uncompressed]
***
%% Initialized:  [Session-22, SSL_NULL_WITH_NULL_NULL]
%% Negotiating:  [Session-22, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA]
*** ServerHello, TLSv1
RandomCookie:  GMT: 1489055628 bytes = { 8, 234, 43, 108, 214, 142, 157, 178, 49, 22, 251, 152, 236, 144, 127, 1, 93, 15, 27, 104, 95, 185, 67, 141, 154, 100, 126, 250 }
Session ID:  {89, 193, 48, 140, 228, 60, 49, 76, 254, 195, 239, 207, 140, 90, 183, 213, 107, 247, 182, 144, 232, 56, 81, 153, 1, 163, 216, 28, 43, 31, 67, 215}
Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
Compression Method: 0
Extension renegotiation_info, renegotiated_connection: <empty>
***
Cipher suite:  TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
*** Certificate chain
chain [0] = [
[
  Version: V3
  Subject: CN=Dilusha, OU=support, O=wso2, L=colomo, ST=north, C=LK
  Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11

  Key:  Sun RSA public key, 1024 bits
  modulus: 113691734523572616705028098273372578526731711899609655385172103852800475137317959455995634316954315895617608179218601081239926219539099134545220471183489639066408680758829448647082232509967663485805245458010725404323789984270110599753613731585879940614344983141080141974841464824488038023066167762024086954827
  public exponent: 65537
  Validity: [From: Tue Sep 19 11:50:08 IST 2017,
               To: Mon Dec 18 11:50:08 IST 2017]
  Issuer: CN=Dilusha, OU=support, O=wso2, L=colomo, ST=north, C=LK
  SerialNumber: [    062f22b4]

Certificate Extensions: 1
[1]: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 33 70 01 21 49 55 C0 1B   ED 9F 7E A9 04 89 27 1F  3p.!IU........'.
0010: B8 A7 07 7F                                        ....
]
]

]
  Algorithm: [SHA256withRSA]
  Signature:
0000: 71 B8 B2 15 B9 BC FE 6E   98 18 CC 44 15 C9 11 C9  q......n...D....
0010: 6D F3 63 72 CC A4 82 F7   EB 25 8A 9A 97 DE 90 A8  m.cr.....%......
0020: 6A 8B A7 8A 44 24 6C 5F   B3 A6 6B CF 73 BC 88 F8  j...D$l_..k.s...
0030: 28 C2 07 8B E2 42 CF B0   5F 3C A8 6E 64 22 E7 A9  (....B.._<.nd"..
0040: 93 51 9F 0F B3 99 76 46   58 76 7C 02 5B 16 A2 7A  .Q....vFXv..[..z
0050: 0A A5 3E 06 D3 1E 18 9C   29 6B 67 10 E8 30 D4 58  ..>.....)kg..0.X
0060: E4 80 F1 BD 0D D5 E4 6F   34 F5 4F F0 78 FB D9 AA  .......o4.O.x...
0070: 7B 67 87 54 5A E0 44 71   43 00 07 CC EE EF ED 7C  .g.TZ.DqC.......

]
***
*** ECDH ServerKeyExchange
Server key: Sun EC public key, 256 bits
  public x coord: 32353841899958817930652980855836811577038465857953582429508108152234048401516
  public y coord: 71310541936420758714524305162261982333248098885822904278718939214691951625811
  parameters: secp256r1 [NIST P-256, X9.62 prime256v1] (1.2.840.10045.3.1.7)
*** CertificateRequest
Cert Types: RSA, DSS, ECDSA
Cert Authorities:
<CN=Dilusha, OU=support, O=wso2, L=colomo, ST=north, C=LK>
<CN=localhost, O=WSO2, L=Mountain View, ST=CA, C=US>
*** ServerHelloDone
HTTPS-Listener I/O dispatcher-3, WRITE: TLSv1 Handshake, length = 1106
HTTPS-Listener I/O dispatcher-3, READ: TLSv1 Handshake, length = 77
*** Certificate chain
***
HTTPS-Listener I/O dispatcher-3, fatal error: 42: null cert chain
javax.net.ssl.SSLHandshakeException: null cert chain
%% Invalidated:  [Session-22, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA]
HTTPS-Listener I/O dispatcher-3, SEND TLSv1 ALERT:  fatal, description = bad_certificate
HTTPS-Listener I/O dispatcher-3, WRITE: TLSv1 Alert, length = 2
HTTPS-Listener I/O dispatcher-3, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLHandshakeException: null cert chain
[2017-09-19 20:28:20,620] ERROR - SourceHandler I/O error: null cert chain
javax.net.ssl.SSLHandshakeException: null cert chain
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1348)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:519)
	at sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1197)
	at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:1169)
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:469)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doWrap(SSLIOSession.java:220)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:254)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:391)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:119)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: null cert chain
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1639)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:281)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:269)
	at sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:1638)
	at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:176)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:913)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:853)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:851)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1285)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doRunTask(SSLIOSession.java:238)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:276)
	... 9 more`

From https://wso2.org/jira/browse/APIMANAGER-5907

**Comment by tgtshanika** [comment]
This has to be validated in the revamped UI of APIM 3.0.0
