### ISSUE TITLE
[Store] Admin user from secondary user store cannot access My Applications

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4875]
> **Description:**
> Steps
> 1. Log in to publisher's carbon console.
> 2. Add secondary userstore-jdbc, 
> 3. Add role giving all permisions on above US
> 4. Add user and grant with created role above.
> 5. Manually sync userstore with other nodes(KM,GW, Store)
> 6. Login to Store app with created users credentials
> 7. Access My Applications section
> 
> Following exception occured and page redirected to error 500 page.
> 
> ```
> TID: [-1234] [] [2015-09-05 09:23:52,853] ERROR
> 
> {org.jaggeryjs.jaggery.core.manager.WebAppManager} - org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.apimgt.api.APIManagementException: User 'MYSQLUS/user1' does not have the required permission: /permission/admin/manage/api/subscribe (<apistore>/scripts/apistore.js#121) (/store/controllers/assets-router.jag#112) {org.jaggeryjs.jaggery.core.manager.WebAppManager}
> org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.apimgt.api.APIManagementException: User 'MYSQLUS/user1' does not have the required permission: /permission/admin/manage/api/subscribe (<apistore>/scripts/apistore.js#121) (/store/controllers/assets-router.jag#112)
> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)
> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
> at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:587)
> at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:507)
> at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
> at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
> at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
> at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
> at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:378)
> at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
> at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
> at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
> at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
> at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
> at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
> at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
> at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
> at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
> at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
> at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1739)
> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1698)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> at java.lang.Thread.run(Thread.java:745)
> Caused by: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.apimgt.api.APIManagementException: User 'MYSQLUS/user1' does not have the required permission: /permission/admin/manage/api/subscribe (<apistore>/scripts/apistore.js#121) (/store/controllers/assets-router.jag#112)
> at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
> at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
> at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
> at org.jaggeryjs.rhino.store.controllers.c0._c_anonymous_5(/store/controllers/assets-router.jag:112)
> at org.jaggeryjs.rhino.store.controllers.c0.call(/store/controllers/assets-router.jag)
> at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
> at org.jaggeryjs.rhino.store.controllers.c0._c_script_0(/store/controllers/assets-router.jag:142)
> at org.jaggeryjs.rhino.store.controllers.c0.call(/store/controllers/assets-router.jag)
> at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
> at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
> at org.jaggeryjs.rhino.store.controllers.c0.call(/store/controllers/assets-router.jag)
> at org.jaggeryjs.rhino.store.controllers.c0.exec(/store/controllers/assets-router.jag)
> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
> ... 41 more
> Caused by: org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.apimgt.api.APIManagementException: User 'MYSQLUS/user1' does not have the required permission: /permission/admin/manage/api/subscribe (<apistore>/scripts/apistore.js#121)
> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)
> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
> at org.jaggeryjs.jaggery.core.manager.WebAppManager.executeScript(WebAppManager.java:308)
> at org.jaggeryjs.jaggery.core.manager.WebAppManager.include(WebAppManager.java:148)
> at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:606)
> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
> ... 53 more
> Caused by: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.apimgt.api.APIManagementException: User 'MYSQLUS/user1' does not have the required permission: /permission/admin/manage/api/subscribe (<apistore>/scripts/apistore.js#121)
> at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
> at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
> at org.jaggeryjs.rhino.<apistore>.scripts.c0._c_anonymous_7(<apistore>/scripts/apistore.js:121)
> at org.jaggeryjs.rhino.<apistore>.scripts.c0.call(<apistore>/scripts/apistore.js)
> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
> at org.jaggeryjs.rhino.store.extensions.assets.api.pages.c1._c_anonymous_1(/store/extensions/assets/api/pages/my_applications.jag:64)
> at org.jaggeryjs.rhino.store.extensions.assets.api.pages.c1.call(/store/extensions/assets/api/pages/my_applications.jag)
> at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
> at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
> at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
> at org.jaggeryjs.rhino.store.modules.c1._c_anonymous_60(/store/modules/store.js:978)
> at org.jaggeryjs.rhino.store.modules.c1.call(/store/modules/store.js)
> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
> at org.jaggeryjs.rhino.<store>.scripts.c0._c_anonymous_18(<store>/scripts/server.js:318)
> at org.jaggeryjs.rhino.<store>.scripts.c0.call(<store>/scripts/server.js)
> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
> at org.jaggeryjs.rhino.store.modules.c1._c_anonymous_59(/store/modules/store.js:972)
> at org.jaggeryjs.rhino.store.modules.c1.call(/store/modules/store.js)
> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
> at org.jaggeryjs.rhino.store.extensions.assets.api.pages.c1._c_script_0(/store/extensions/assets/api/pages/my_applications.jag:21)
> at org.jaggeryjs.rhino.store.extensions.assets.api.pages.c1.call(/store/extensions/assets/api/pages/my_applications.jag)
> at org.jaggeryjs.rhino.store.extensions.assets.api.pages.c1.exec(/store/extensions/assets/api/pages/my_applications.jag)
> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
> ... 60 more
> Caused by: org.wso2.carbon.apimgt.api.APIManagementException: User 'MYSQLUS/user1' does not have the required permission: /permission/admin/manage/api/subscribe
> at org.wso2.carbon.apimgt.impl.utils.APIUtil.checkPermission(APIUtil.java:1857)
> at org.wso2.carbon.apimgt.impl.UserAwareAPIConsumer.checkSubscribePermission(UserAwareAPIConsumer.java:94)
> at org.wso2.carbon.apimgt.impl.UserAwareAPIConsumer.getApplications(UserAwareAPIConsumer.java:89)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:606)
> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
> ... 84 more
> ```

**Comment by tgtshanika** [comment]
By @chaminda from https://wso2.org/jira/browse/APIMANAGER-4101

**Comment by tgtshanika** [comment]
GReg integration has been deprecated in the latest version of APIM. Hence closing the issue
