### ISSUE TITLE
[Intermittent] An Exception getting triggered intermittently in Gateway worker nodes

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4878]
**Description:**
Following exception was seen intermittently in both gateway worker nodes. (Configs attached)

```
TID: [-1] [] [2015-12-16 03:33:09,393] ERROR {com.codahale.metrics.ScheduledReporter} -  RuntimeException thrown from JDBCReporter#report. Exception was suppressed. {com.codahale.metrics.ScheduledReporter}
java.lang.IllegalArgumentException: Underflow
	at oracle.jdbc.driver.OraclePreparedStatement.setDoubleInternal(OraclePreparedStatement.java:6604)
	at oracle.jdbc.driver.OraclePreparedStatement.setDouble(OraclePreparedStatement.java:6574)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.setDouble(OraclePreparedStatementWrapper.java:193)
	at org.wso2.carbon.metrics.reporter.JDBCReporter.reportTimer(JDBCReporter.java:399)
	at org.wso2.carbon.metrics.reporter.JDBCReporter.reportTimers(JDBCReporter.java:365)
	at org.wso2.carbon.metrics.reporter.JDBCReporter.report(JDBCReporter.java:193)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:162)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
TID: [-1] [] [2015-12-16 03:33:37,211] ERROR {org.wso2.carbon.databridge.agent.thrift.AsyncDataPublisher} -  Reconnection failed for for tcp://192.168.48.230:7611 {org.wso2.carbon.databridge.agent.thrift.AsyncDataPublisher}
TID: [-1] [] [2015-12-16 03:33:37,215] ERROR {org.wso2.carbon.databridge.agent.thrift.AsyncDataPublisher} -  Reconnection failed for for tcp://192.168.48.233:7611 {org.wso2.carbon.databridge.agent.thrift.AsyncDataPublisher}
TID: [-1] [] [2015-12-16 03:34:07,214] ERROR {org.wso2.carbon.databridge.agent.thrift.AsyncDataPublisher} -  Reconnection failed for for tcp://192.168.48.233:7611 {org.wso2.carbon.databridge.agent.thrift.AsyncDataPublisher}
TID: [-1] [] [2015-12-16 03:34:07,215] ERROR {org.wso2.carbon.databridge.agent.thrift.AsyncDataPublisher} -  Reconnection failed for for tcp://192.168.48.230:7611 {org.wso2.carbon.databridge.agent.thrift.AsyncDataPublisher}
TID: [-1] [] [2015-12-16 03:34:09,392] ERROR {com.codahale.metrics.ScheduledReporter} -  RuntimeException thrown from JDBCReporter#report. Exception was suppressed. {com.codahale.metrics.ScheduledReporter}
java.lang.IllegalArgumentException: Underflow
	at oracle.jdbc.driver.OraclePreparedStatement.setDoubleInternal(OraclePreparedStatement.java:6604)
	at oracle.jdbc.driver.OraclePreparedStatement.setDouble(OraclePreparedStatement.java:6574)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.setDouble(OraclePreparedStatementWrapper.java:193)
	at org.wso2.carbon.metrics.reporter.JDBCReporter.reportTimer(JDBCReporter.java:399)
	at org.wso2.carbon.metrics.reporter.JDBCReporter.reportTimers(JDBCReporter.java:365)
	at org.wso2.carbon.metrics.reporter.JDBCReporter.report(JDBCReporter.java:193)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:162)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

```
By Pubudu D.P from https://wso2.org/jira/browse/APIMANAGER-4409

**Comment by chamilaadhi** [comment]
Closing Since the issue has been stale for a long time.
