### ISSUE TITLE
UI Improvements for Add Application Level Policy

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4895]
> **Description:**
> 1. Include option buttons for Request Count, Request Bandwidth quota configurations. Because it does not seem like selection buttons
> 
> 2. Include a space in between Unit Time text box and SAVE button
> 
> 3. Provide a proper error message when you try to add application tier by existing name. At the moment it gives : Error occurred while executing the action add and exception is thrown in the backend
> 
> ```
> [2016-05-03 15:25:44,977]  INFO - ThrottlePolicyTemplateBuilder         @Plan:name('app_aaa')
>         @Plan:description('ExecutionPlan for app_aaa')
> 
>         @Import('org.wso2.throttle.processed.request.stream:1.0.0')
>         define stream RequestStream (messageID string, appKey string, appTier string, subscriptionKey string, apiKey string, apiTier string, subscriptionTier string, resourceKey string, resourceTier string, userId string, propertiesMap string);
> 
>         @Export('org.wso2.throttle.globalThrottle.stream:1.0.0')
>         define stream GlobalThrottleStream (throttleKey string, isThrottled bool);
> 
>         FROM RequestStream
>         SELECT messageID, (appTier == 'aaa') AS isEligible, appKey AS throttleKey
>         INSERT INTO EligibilityStream;
> 
>         FROM EligibilityStream[isEligible==true]#window.time(1 sec)
>         select throttleKey, (count(messageID) >= 20) as isThrottled
>         group by throttleKey
>         INSERT ALL EVENTS into ResultStream;
> 
>         from ResultStream#throttler:emitOnStateChange(throttleKey, isThrottled)
>         select *
>         insert into GlobalThrottleStream;
> [2016-05-03 15:25:44,990] ERROR - ApiMgtDAO Failed to add Application Policy: ApplicationPolicy [policyName=aaa, applicationId =0, description=  sfes , defaultQuotaPolicy=QuotaPolicy [type=requestCount, limit=RequestCountLimit [requestCount=20, toString()=Limit [timeUnit=sec, unitTime=1]]]]
> org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "APP_NAME_TENANT_INDEX_D ON PUBLIC.AM_POLICY_APPLICATION(NAME, TENANT_ID)"; SQL statement:
> INSERT INTO AM_POLICY_APPLICATION (NAME, DISPLAY_NAME, TENANT_ID, DESCRIPTION, QUOTA_TYPE, QUOTA, 
>  QUOTA_UNIT, UNIT_TIME, TIME_UNIT, IS_DEPLOYED) 
> VALUES (?,?,?,?,?,?,?,?,?,?) [23001-140]
> 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
> 	at org.h2.message.DbException.get(DbException.java:167)
> 	at org.h2.message.DbException.get(DbException.java:144)
> 	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:157)
> 	at org.h2.index.PageBtree.find(PageBtree.java:121)
> 	at org.h2.index.PageBtreeLeaf.addRow(PageBtreeLeaf.java:138)
> 	at org.h2.index.PageBtreeLeaf.addRowTry(PageBtreeLeaf.java:93)
> 	at org.h2.index.PageBtreeIndex.addRow(PageBtreeIndex.java:90)
> 	at org.h2.index.PageBtreeIndex.add(PageBtreeIndex.java:81)
> 	at org.h2.table.RegularTable.addRow(RegularTable.java:116)
> 	at org.h2.command.dml.Insert.insertRows(Insert.java:120)
> 	at org.h2.command.dml.Insert.update(Insert.java:82)
> 	at org.h2.command.CommandContainer.update(CommandContainer.java:70)
> 	at org.h2.command.Command.executeUpdate(Command.java:199)
> 	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:141)
> 	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:127)
> 	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addApplicationPolicy(ApiMgtDAO.java:8284)
> 	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addPolicy(APIProviderImpl.java:3668)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
> 	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
> 	at org.jaggeryjs.rhino.admin_dashboard.modules.policy.c3._c_anonymous_1(/admin-dashboard/modules/policy/app-policy-edit.jag:15)
> 	at org.jaggeryjs.rhino.admin_dashboard.modules.policy.c3.call(/admin-dashboard/modules/policy/app-policy-edit.jag)
> 	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
> 	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
> 	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
> 	at org.jaggeryjs.rhino.admin_dashboard.modules.policy.c0._c_anonymous_1(/admin-dashboard/modules/policy/module.jag:5)
> 	at org.jaggeryjs.rhino.admin_dashboard.modules.policy.c0.call(/admin-dashboard/modules/policy/module.jag)
> 	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
> 	at org.jaggeryjs.rhino.admin_dashboard.site.blocks.policy.app.edit.ajax.c0._c_anonymous_1(/admin-dashboard/site/blocks/policy/app/edit/ajax/app-policy-edit.jag:33)
> 	at org.jaggeryjs.rhino.admin_dashboard.site.blocks.policy.app.edit.ajax.c0.call(/admin-dashboard/site/blocks/policy/app/edit/ajax/app-policy-edit.jag)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
> 	at org.jaggeryjs.rhino.admin_dashboard.site.blocks.policy.app.edit.ajax.c0._c_script_0(/admin-dashboard/site/blocks/policy/app/edit/ajax/app-policy-edit.jag:4)
> 	at org.jaggeryjs.rhino.admin_dashboard.site.blocks.policy.app.edit.ajax.c0.call(/admin-dashboard/site/blocks/policy/app/edit/ajax/app-policy-edit.jag)
> 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
> 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
> 	at org.jaggeryjs.rhino.admin_dashboard.site.blocks.policy.app.edit.ajax.c0.call(/admin-dashboard/site/blocks/policy/app/edit/ajax/app-policy-edit.jag)
> 	at org.jaggeryjs.rhino.admin_dashboard.site.blocks.policy.app.edit.ajax.c0.exec(/admin-dashboard/site/blocks/policy/app/edit/ajax/app-policy-edit.jag)
> 	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
> 	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
> 	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:587)
> 	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:507)
> 	at org.jaggeryjs.jaggery.core.JaggeryServlet.doPost(JaggeryServlet.java:29)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
> 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
> 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:378)
> 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
> 	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
> 	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
> 	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
> 	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
> 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
> 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
> 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1739)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1698)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:745)
> [2016-05-03 15:25:44,993] ERROR - app-policy-edit:jag Error occurred while saving policy (Cause:org.wso2.carbon.apimgt.api.APIManagementException: Failed to add Application Policy: ApplicationPolicy [policyName=aaa, applicationId =0, description=  sfes , defaultQuotaPolicy=QuotaPolicy [type=requestCount, limit=RequestCountLimit [requestCount=20, toString()=Limit [timeUnit=sec, unitTime=1]]]])
> ```
> ![Screenshot from 2016-05-03 15-15-18](https://user-images.githubusercontent.com/4471756/58428954-cb568800-80c1-11e9-88d2-768510232f46.png)
> ![Screenshot from 2016-05-24 17-51-27](https://user-images.githubusercontent.com/4471756/58428955-cbef1e80-80c1-11e9-8613-600f827ba9c5.png)
> ![test](https://user-images.githubusercontent.com/4471756/58428957-cd204b80-80c1-11e9-8897-246d1236e46e.png)
> 

By Ushani Balasooriya from https://wso2.org/jira/browse/APIMANAGER-4733

**Comment by tgtshanika** [comment]
Issue #3 still exists in the latest APIM release as well (Tested with APIM 3.0.0 milestone 32)
