### ISSUE TITLE
"Could not convert JSON Stream to XML. Cannot handle JSON input" error observed during a load test

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4911]
**Description:**
1. Create an API with the below config

```
<?xml version="1.0" encoding="UTF-8"?>
<api xmlns="http://ws.apache.org/ns/synapse"
     name="admin-AT-evan.com--GreetGWAPI4"
     context="/tevan.com/greetapi4/1.0.0"
     version="1.0.0"
     version-type="context">
   <resource methods="POST" url-mapping="/*" faultSequence="fault">
      <inSequence>
         <property name="api.ut.backendRequestTime"
                   expression="get-property('SYSTEM_TIME')"/>
         <filter source="$ctx:AM_KEY_TYPE" regex="PRODUCTION">
            <then>
               <send>
                  <endpoint name="admin-AT-evan.com--GreetGWAPI4_APIproductionEndpoint_0">
                     <http uri-template="http://esb.wso2.com/greetapi"/>
                     <property name="ENDPOINT_ADDRESS" value="http://esb.wso2.com/greetapi"/>
                  </endpoint>
               </send>
            </then>
            <else>
               <sequence key="_sandbox_key_error_"/>
            </else>
         </filter>
      </inSequence>
      <outSequence>
         <class name="org.wso2.carbon.apimgt.usage.publisher.APIMgtResponseHandler"/>
         <send/>
      </outSequence>
   </resource>
   <handlers>
      <handler class="org.wso2.carbon.apimgt.gateway.handlers.common.APIMgtLatencyStatsHandler"/>
      <handler class="org.wso2.carbon.apimgt.gateway.handlers.security.CORSRequestHandler">
         <property name="apiImplementationType" value="ENDPOINT"/>
      </handler>
      <handler class="org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler"/>
      <handler class="org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler"/>
      <handler class="org.wso2.carbon.apimgt.usage.publisher.APIMgtUsageHandler"/>
      <handler class="org.wso2.carbon.apimgt.usage.publisher.APIMgtGoogleAnalyticsTrackingHandler">
         <property name="configKey" value="gov:/apimgt/statistics/ga-config.xml"/>
      </handler>
      <handler class="org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler"/>
   </handlers>
</api>
```
2. Invoked the API from the attached JMeter script
3. Intermittently, I see the below exception
```
TID: [-1] [] [2016-11-09 11:30:44,700]  WARN {org.apache.synapse.transport.passthru.TargetHandler} -  Connection closed by target host before receiving the response {org.apache.synapse.transport.passthru.TargetHandler}
TID: [1] [] [2016-11-09 11:30:44,766] @evan.com [1] [AM] WARN {org.apache.synapse.endpoints.EndpointContext} -  Endpoint : admin-AT-evan.com--GreetGWAPI4_APIproductionEndpoint_0 will be marked SUSPENDED as it failed {org.apache.synapse.endpoints.EndpointContext}
TID: [1] [] [2016-11-09 11:30:44,770] @evan.com [1] [AM] WARN {org.apache.synapse.endpoints.EndpointContext} -  Suspending endpoint : admin-AT-evan.com--GreetGWAPI4_APIproductionEndpoint_0 - current suspend duration is : 30000ms - Next retry after : Wed Nov 09 11:31:14 UTC 2016 {org.apache.synapse.endpoints.EndpointContext}
TID: [1] [] [2016-11-09 11:30:44,776] @evan.com [1] [AM] INFO {org.apache.synapse.endpoints.EndpointContext} -  Endpoint : admin-AT-evan.com--GreetGWAPI4_APIproductionEndpoint_0 currently SUSPENDED will now be marked active since it processed its last message {org.apache.synapse.endpoints.EndpointContext}
TID: [1] [] [2016-11-09 11:30:44,779] @evan.com [1] [AM] INFO {org.apache.synapse.mediators.builtin.LogMediator} -  To: http://esb.wso2.com/greetapi, MessageID: urn:uuid:7d8a09b1-95b2-44da-8674-96a15bf3a80d, Direction: request, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><jsonObject><sayHi><arg0>Evanthika</arg0></sayHi></jsonObject></soapenv:Body></soapenv:Envelope> {org.apache.synapse.mediators.builtin.LogMediator}
TID: [1] [] [2016-11-09 11:30:44,786] @evan.com [1] [AM]ERROR {org.apache.synapse.commons.json.JsonUtil} -  #toXml. Could not convert JSON Stream to XML. Cannot handle JSON input. Error>>> null {org.apache.synapse.commons.json.JsonUtil}
TID: [1] [] [2016-11-09 11:30:44,794] @evan.com [1] [AM]ERROR {org.apache.synapse.transport.passthru.util.DeferredMessageBuilder} -  Error building message {org.apache.synapse.transport.passthru.util.DeferredMessageBuilder}
org.apache.axis2.AxisFault: Could not convert JSON Stream to XML. Cannot handle JSON input.
        at org.apache.synapse.commons.json.JsonUtil.toXml(JsonUtil.java:285)
        at org.apache.synapse.commons.json.JsonBuilder.processDocument(JsonBuilder.java:35)
        at org.apache.synapse.transport.passthru.util.DeferredMessageBuilder.getDocument(DeferredMessageBuilder.java:148)
        at org.apache.synapse.transport.passthru.util.RelayUtils.builldMessage(RelayUtils.java:137)
        at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:100)
        at org.apache.synapse.mediators.AbstractListMediator.buildMessage(AbstractListMediator.java:127)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:81)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:57)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.mediators.MediatorFaultHandler.onFault(MediatorFaultHandler.java:93)
        at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:53)
        at org.apache.synapse.endpoints.AbstractEndpoint.invokeNextFaultHandler(AbstractEndpoint.java:690)
        at org.apache.synapse.endpoints.AbstractEndpoint.onFault(AbstractEndpoint.java:530)
        at org.apache.synapse.endpoints.HTTPEndpoint.onFault(HTTPEndpoint.java:66)
        at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:101)
        at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:284)
        at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:188)
        at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
        at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processResponse(MultitenantMessageReceiver.java:166)
        at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:82)
        at org.apache.synapse.transport.passthru.TargetErrorHandler$1.run(TargetErrorHandler.java:139)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException
        at org.apache.synapse.commons.staxon.core.base.AbstractXMLStreamReader.initialize(AbstractXMLStreamReader.java:245)
        at org.apache.synapse.commons.staxon.core.json.JsonXMLStreamReader.<init>(JsonXMLStreamReader.java:66)
        at org.apache.synapse.commons.staxon.core.json.JsonXMLInputFactory.createXMLStreamReader(JsonXMLInputFactory.java:165)
        at org.apache.synapse.commons.json.JsonUtil.getReader(JsonUtil.java:320)
        at org.apache.synapse.commons.json.JsonUtil.getReader(JsonUtil.java:302)
        at org.apache.synapse.commons.json.JsonUtil.toXml(JsonUtil.java:281)
        ... 24 more
TID: [-1] [] [2016-11-09 11:30:44,809]  WARN {org.apache.synapse.transport.passthru.TargetHandler} -  Connection closed by target host before receiving the response {org.apache.synapse.transport.passthru.TargetHandler}
```
By Evanthika Amarasiri from https://wso2.org/jira/browse/APIMANAGER-5479

**Comment by Nirothipan** [comment]
This is observed  in APIM 2.2.0 when the payload is empty and there is a content aware mediator in the flow. By default APIM 2.2.0 uses following builders and formatters.
```
<messageBuilder contentType="application/json"
      class="org.apache.synapse.commons.json.JsonBuilder"/>

<messageFormatter contentType="application/json"
      class="org.apache.synapse.commons.json.JsonFormatter"/>
```
I guess, in a load test the payload is getting empty somewhere in the flow and it is leading to this behavior.

Hence if we switch to following, it might solve the issue.
```
<messageBuilder contentType="application/json"
      class="org.apache.synapse.commons.json.JsonStreamBuilder"/>

<messageFormatter contentType="application/json"
      class="org.apache.synapse.commons.json.JsonStreamFormatter"/>
```

**Comment by Arshardh** [comment]
Closing since a solution if found.
