### ISSUE TITLE
[2.5] Error publishing API after updating throttling policy 

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#4988]
1. Make a fresh deployment (Issue only occurs on first API publishing)
2. Go to Admin portal and create Advanced Throttling Policy. 
3. Edit the created policy.
4. Go to Publisher and start creating a new API via" Design New REST API". 
5. Fill in all the forms and click Save&Publish button on the last step (Manage).

```
TID: [-1234] [] [2019-06-09 19:36:20,018] ERROR {org.wso2.carbon.rest.api.service.RestApiAdmin} -  Error trying to add the API to the ESB configuration : admin--Test:v1.0 :: Cache resourceCache already exists {org.wso2.carbon.rest.api.service.RestApiAdmin}
javax.cache.CacheException: Cache resourceCache already exists
	at org.wso2.carbon.caching.impl.CarbonCacheManager.createCacheBuilder(CarbonCacheManager.java:100)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getCache(APIUtil.java:7145)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIKeyValidator.getCache_aroundBody4(APIKeyValidator.java:123)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIKeyValidator.getCache(APIKeyValidator.java:121)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIKeyValidator.getResourceCache_aroundBody12(APIKeyValidator.java:172)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIKeyValidator.getResourceCache(APIKeyValidator.java:167)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIKeyValidator.<init>(APIKeyValidator.java:96)
	at org.wso2.carbon.apimgt.gateway.handlers.security.oauth.OAuthAuthenticator.init_aroundBody0(OAuthAuthenticator.java:76)
	at org.wso2.carbon.apimgt.gateway.handlers.security.oauth.OAuthAuthenticator.init(OAuthAuthenticator.java:75)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.initializeAuthenticator_aroundBody14(APIAuthenticationHandler.java:121)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.initializeAuthenticator(APIAuthenticationHandler.java:120)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.init_aroundBody0(APIAuthenticationHandler.java:87)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.init(APIAuthenticationHandler.java:81)
	at org.apache.synapse.rest.API.init(API.java:517)
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApi(RestApiAdmin.java:821)
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApiFromString(RestApiAdmin.java:82)
...
TID: [-1234] [] [2019-06-09 19:36:20,046] ERROR {org.wso2.carbon.apimgt.impl.APIGatewayManager} -  Error occurred when publish to gateway Production and Sandbox {org.wso2.carbon.apimgt.impl.APIGatewayManager}
org.apache.axis2.AxisFault: Error while publishing API to the Gateway. Error while publishing API to the Gateway. RestApiAdminAPIException
	at org.wso2.carbon.apimgt.impl.utils.APIGatewayAdminClient.addApi_aroundBody2(APIGatewayAdminClient.java:99)
	at org.wso2.carbon.apimgt.impl.utils.APIGatewayAdminClient.addApi(APIGatewayAdminClient.java:88)
	at org.wso2.carbon.apimgt.impl.APIGatewayManager.publishToGateway_aroundBody2(APIGatewayManager.java:178)
	at org.wso2.carbon.apimgt.impl.APIGatewayManager.publishToGateway(APIGatewayManager.java:85)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.publishToGateway_aroundBody82(APIProviderImpl.java:1726)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.publishToGateway(APIProviderImpl.java:1710)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.propergateAPIStatusChangeToGateways_aroundBody70(APIProviderImpl.java:1519)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.propergateAPIStatusChangeToGateways(APIProviderImpl.java:1485)
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.propergateAPIStatusChangeToGateways_aroundBody28(UserAwareAPIProvider.java:171)
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.propergateAPIStatusChangeToGateways(UserAwareAPIProvider.java:168)
	at org.wso2.carbon.apimgt.impl.executors.APIExecutor.execute_aroundBody2(APIExecutor.java:137)
	at org.wso2.carbon.apimgt.impl.executors.APIExecutor.execute(APIExecutor.java:86)
...
Caused by: org.apache.axis2.AxisFault: Error while publishing API to the Gateway. RestApiAdminAPIException
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:381)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:456)
..
```
The reason for the issue, is when updatin an API throttling policy, we try to invalid resource cache. When invalidating the cache, while trying to get cache, the carbon cache manager create the resource cache[1]. So when trying to publish an API for the first time, when initializing the APIKeyValidator, the above error is thrown, while trying to get resource cache using CacheManager.createCacheBuilder() method.

[1] https://github.com/wso2/carbon-apimgt/blob/6.x/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/service/APIAuthenticationService.java#L75
[2] https://github.com/wso2/carbon-apimgt/blob/6.x/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIKeyValidator.java#L173
[3] https://github.com/wso2/carbon-apimgt/blob/6.x/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java#L7466

**Comment by nalakas** [comment]
This bug exists in APIM 2.1.0, APIM 2.6.0 as well.
