### ISSUE TITLE
Creating custom mediation via publisher API fails when API name contains a space character

### ISSUE THREAD

**Issue by brendon-stephens** [wso2/product-apim#5046]
**Description:**
Adding custom mediation to an API using `/api/am/publisher/v0.14/apis/{{wso2.api.id}}/policies/mediation` results in a 500 error when the API name has a space character in it.

```json
{
    "code": 500,
    "message": "Internal server error",
    "description": "Error while getting location header for created mediation policy custom",
    "moreInfo": "",
    "error": []
}
```
```log4j
TID: [39] [] [2019-05-29 10:40:30,589] admin@bstep93.bcz@bstep93.bcz [39] [AM]ERROR {org.wso2.carbon.apimgt.rest.api.publisher.impl.ApisApiServiceImpl} -  Error while getting location header for created mediation policy custom {org.wso2.carbon.apimgt.rest.api.publisher.impl.ApisApiServiceImpl}
java.net.URISyntaxException: Illegal character in path at index 106: /t/bstep93.bcz/registry/resource/_system/governance/apimgt/applicationdata/provider/admin-AT-bstep93.bcz/**SWAGGER API**/2.0.015/out/custom.xml
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at org.wso2.carbon.apimgt.rest.api.publisher.impl.ApisApiServiceImpl.apisApiIdPoliciesMediationPost(ApisApiServiceImpl.java:758)
	at org.wso2.carbon.apimgt.rest.api.publisher.ApisApi.apisApiIdPoliciesMediationPost(ApisApi.java:340)
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
AM 260

**OS, DB, other environments details and versions:**    

**Steps to reproduce:**
1. `POST: api/am/publisher/v0.14/apis` - ensure name property contains a space.
2. `POST: api/am/publisher/v0.14/apis/{{wso2.api.id}}/policies/mediation`

**Related Issues:**

**Comment by tgtshanika** [comment]
API name cannot contain spaces. Hence this is invalid
