### ISSUE TITLE
[Doc] Update master-datasource.xml configuration for postgres and DB2

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#5117]
1. Validation query of DB2 should be changed as "SELECT 1 FROM SYSIBM.SYSDUMMY1" - [1]
Following error is thrown when  "SELECT 1" is added as validation query. Hence, we need to update the validation query.

```
Caused by: java.sql.SQLException: Failed to validate a newly established connection.
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:831)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:648)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:200)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:128)

```
2. defaultAutoCommit should be set as true for PostgreSQL in order to avoid following error [2]:
```
 INFO - CarbonAuthenticationUtil 'admin@carbon.super [-1234]' logged in at [2019-06-28 13:36:58,390+0530] from IP address 
[2019-06-28 13:36:58,404] ERROR - ThriftAuthenticationJDBCPersistenceManager Error when getting a database connection object from the Thrift Authentication data source.
org.postgresql.util.PSQLException: Cannot change transaction isolation level in the middle of a transaction.
	at org.postgresql.jdbc.PgConnection.setTransactionIsolation(PgConnection.java:826)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:127)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:153)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:41)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:80)
	at com.sun.proxy.$Proxy17.setTransactionIsolation(Unknown Source)
	at org.wso2.carbon.identity.thrift.authentication.internal.persistance.ThriftAuthenticationJDBCPersistenceManager.getDBConnection(ThriftAuthenticationJDBCPersistenceManager.java:116)
	at org.wso2.carbon.identity.thrift.authentication.internal.util.ThriftAuthenticationDatabaseUtil.getDBConnection(ThriftAuthenticationDatabaseUtil.java:46)
	at org.wso2.carbon.identity.thrift.authentication.dao.DBThriftSessionDAO.addSession(DBThriftSessionDAO.java:123)
	at org.wso2.carbon.identity.thrift.authentication.internal.ThriftAuthenticatorServiceImpl.addThriftSession(ThriftAuthenticatorServiceImpl.java:67)
	at org.wso2.carbon.identity.thrift.authentication.internal.ThriftAuthenticatorServiceImpl.authenticate(ThriftAuthenticatorServiceImpl.java:150)
	at org.wso2.carbon.identity.thrift.authentication.internal.AuthenticatorServiceImpl.authenticate(AuthenticatorServiceImpl.java:37)
	at org.wso2.carbon.identity.thrift.authentication.internal.generatedCode.AuthenticatorService$Processor$authenticate.getResult(AuthenticatorService.java:164)
	at org.wso2.carbon.identity.thrift.authentication.internal.generatedCode.AuthenticatorService$Processor$authenticate.getResult(AuthenticatorService.java:152)

```
[1] https://docs.wso2.com/display/AM260/Changing+the+Default+API-M+Databases#acab1643eb714fb7ad82b27abc41788f
[2] https://docs.wso2.com/display/AM260/Changing+the+Default+API-M+Databases#927ef8813f644c6591eadad054737427

**Comment by chamilaadhi** [comment]
DB2 configs are added to the latest docs https://apim.docs.wso2.com/en/latest/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-ibm-db2/ .
