### ISSUE TITLE
Usersignup approval workflow is not working in WSO2 API Manager 2.6.0

### ISSUE THREAD

**Issue by jsdjayanga** [wso2/product-apim#5271]
Refer https://wso2.org/jira/browse/WUM-14

TID: [-1234] [] [2019-04-10 14:20:44,240] ERROR

{org.apache.axis2.engine.AxisEngine} - The system is attempting to access an inactive service: WorkflowCallbackService {org.apache.axis2.engine.AxisEngine}
org.apache.axis2.AxisFault: The system is attempting to access an inactive service: WorkflowCallbackService
at org.apache.axis2.engine.AxisConfiguration.getService(AxisConfiguration.java:1049)
at org.apache.axis2.dispatchers.RequestURIBasedServiceDispatcher.findService(RequestURIBasedServiceDispatcher.java:85)
at org.apache.axis2.dispatchers.RequestURIBasedDispatcher.findService(RequestURIBasedDispatcher.java:53)
at org.apache.axis2.engine.AbstractDispatcher.invoke(AbstractDispatcher.java:94)
at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:415)
at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
TID: [-1234] [] [2019-04-10 14:20:44,242] ERROR

{org.apache.synapse.transport.passthru.ServerWorker} - Error processing POST request for : /services/WorkflowCallbackService {org.apache.synapse.transport.passthru.ServerWorker}
org.apache.axis2.AxisFault: The system is attempting to access an inactive service: WorkflowCallbackService
at org.apache.axis2.engine.AxisConfiguration.getService(AxisConfiguration.java:1049)
at org.apache.axis2.dispatchers.RequestURIBasedServiceDispatcher.findService(RequestURIBasedServiceDispatcher.java:85)
at org.apache.axis2.dispatchers.RequestURIBasedDispatcher.findService(RequestURIBasedDispatcher.java:53)
at org.apache.axis2.engine.AbstractDispatcher.invoke(AbstractDispatcher.java:94)
at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:415)
at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by bhathiya** [comment]
@tgtshanika is this not working in 3.0 as well?

**Comment by mastanreddy88** [comment]
Can someone please provide the workaround or solution for this issue. Appreciate your quick help. Thanks in advance!
