### ISSUE TITLE
Error while performing configuration changes org.wso2.config.mapper.ConfigParserException: Template directory

### ISSUE THREAD

**Issue by shaliniatwork** [wso2/product-apim#5414]
Hi I am trying to customize WSO2 api manager. I get the below error when I run the product. Please help

```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; sup
port was removed in 8.0
[2019-08-28 6:41:24,642]  SEVERE {org.wso2.carbon.server.Main handleConfiguratio
n} - Error while performing configuration changes
org.wso2.config.mapper.ConfigParserException: Template directory (D:\projects\ws
o2\product-apim-master\modules\distribution\product\target\wso2am-3.0.0-SNAPSHOT
\null\templates) does not exist or is not a directory
        at org.wso2.config.mapper.ConfigParser.checkTemplateDirExistence(ConfigP
arser.java:271)
        at org.wso2.config.mapper.ConfigParser.backupConfigurations(ConfigParser
.java:168)
        at org.wso2.config.mapper.ConfigParser.deployAndStoreMetadata(ConfigPars
er.java:178)
        at org.wso2.config.mapper.ConfigParser.parse(ConfigParser.java:127)
        at org.wso2.carbon.server.Main.handleConfiguration(Main.java:231)
        at org.wso2.carbon.server.Main.main(Main.java:103)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.wso2.carbon.bootstrap.Bootstrap.loadClass(Bootstrap.java:70)
        at org.wso2.carbon.bootstrap.Bootstrap.main(Bootstrap.java:51)
```

**Comment by ruben2218** [comment]
Hi this error with run wso2 api manager ???

ubuntu@ip-172-31-38-113:~/software/wso2am-3.0.0/bin$ sh wso2server.sh
JAVA_HOME environment variable is set to /opt/jdk/jdk1.8.0_202
CARBON_HOME environment variable is set to /home/ubuntu/software/wso2am-3.0.0
Using Java memory options: -Xms256m -Xmx1024m
[2020-03-02 19:58:59,490]  SEVERE {org.wso2.carbon.server.Main handleConfiguration} - Error while performing configuration changes
org.wso2.config.mapper.ConfigParserException: Error while reading metadata
        at org.wso2.config.mapper.MetaDataParser.readLastModifiedValue(MetaDataParser.java:76)
        at org.wso2.config.mapper.MetaDataParser.getChangedFiles(MetaDataParser.java:156)
        at org.wso2.config.mapper.ConfigParser.parse(ConfigParser.java:103)
        at org.wso2.carbon.server.Main.handleConfiguration(Main.java:231)
        at org.wso2.carbon.server.Main.main(Main.java:103)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.wso2.carbon.bootstrap.Bootstrap.loadClass(Bootstrap.java:70)
        at org.wso2.carbon.bootstrap.Bootstrap.main(Bootstrap.java:51)
Caused by: java.io.FileNotFoundException: /home/ubuntu/software/wso2am-3.0.0/repository\conf\etc\tasks-config.xml (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.wso2.config.mapper.MetaDataParser.getMetadata(MetaDataParser.java:97)
        at org.wso2.config.mapper.MetaDataParser.readLastModifiedValue(MetaDataParser.java:74)
        ... 10 more

**Comment by pkydev** [comment]
@shaliniatwork , did you perhaps move the product from window os installation to ubuntu os?
