### ISSUE TITLE
Cannot generate keys of Applications with space in the name

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#5461]
Looks like we can create apps with spaces in React Store but failing when doing key generation.

```
[2019-09-04 09:52:19,746]  INFO - CarbonAuthenticationUtil 'admin@carbon.super [-1234]' logged in at [2019-09-04 09:52:19,746+0530]
[2019-09-04 09:52:19,754] ERROR - APIUtil Error occurred while creating ServiceProvider for app admin_app1 qwe_PRODUCTION
org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: The Application name admin_app1 qwe_PRODUCTION is not valid! It is not adhering to the regex ^[a-zA-Z0-9._-]*$
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.doAddApplication(ApplicationManagementServiceImpl.java:1679) ~[org.wso2.carbon.identity.application.mgt_5.14.15.jar:?]
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.createApplicationWithTemplate(ApplicationManagementServiceImpl.java:172) ~[org.wso2.carbon.identity.application.mgt_5.14.15.jar:?]
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.createApplication(ApplicationManagementServiceImpl.java:150) ~[org.wso2.carbon.identity.application.mgt_5.14.15.jar:?]
	at org.wso2.carbon.apimgt.keymgt.service.APIKeyMgtSubscriberService.createOAuthApplicationByApplicationInfo_aroundBody0(APIKeyMgtSubscriberService.java:159) [org.wso2.carbon.apimgt.keymgt_6.5.74.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.keymgt.service.APIKeyMgtSubscriberService.createOAuthApplicationByApplicationInfo(APIKeyMgtSubscriberService.java:107) [org.wso2.carbon.apimgt.keymgt_6.5.74.SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
	at org.apache.axis2.rpc.receivers.RPCUtil.invokeServiceClass(RPCUtil.java:212) [axis2_1.6.1.wso2v37.jar:?]
	at org.apache.axis2.rpc.receivers.RPCMessageReceiver.invokeBusinessLogic(RPCMessageReceiver.java:117) [axis2_1.6.1.wso2v37.jar:?]
	at org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:40) [axis2_1.6.1.wso2v37.jar:?]
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110) [axis2_1.6.1.wso2v37.jar:?]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) [axis2_1.6.1.wso2v37.jar:?]
	at org.apache.axis2.transport.http.HTTPTransportUtils.processHTTPPostRequest(HTTPTransportUtils.java:173) [axis2_1.6.1.wso2v37.jar:?]
	at org.apache.axis2.transport.http.AxisServlet.doPost(AxisServlet.java:148) [axis2_1.6.1.wso2v37.jar:?]
```

_Originally posted by @malinthaprasan in https://github.com/wso2/product-apim/issues/5446#issuecomment-527734137_

**Comment by dushansilva** [comment]
fixed from . https://github.com/wso2/product-apim/pull/6317
