### ISSUE TITLE
APIM invocation failure for tenant after tenant unloading

### ISSUE THREAD

**Issue by nalakas** [wso2/product-apim#5497]
In APIM 3.0.0 once the tenant is unloaded we can't invoke API thereafter.
Step to reproduce:
create tenant and publish sample api in tenant space.
subscribed to an application and invoke API using curl command.
wait until the tenant is unloaded and try to invoke it again.

Priority: High

**Comment by nalakas** [comment]
The following error can be see when the tenant is once it is unloaded and try to loading.

[2019-09-19 12:12:51,567]  INFO - TenantAxisConfigurator Creating tenant AxisConfiguration for tenant: foo.com[1]
[2019-09-19 12:12:51,781]  INFO - UserStoreConfigurationDeployer User Store Configuration Deployer initiated.
[2019-09-19 12:12:51,782]  INFO - UserStoreConfigurationDeployer User Store Configuration Deployer initiated.
[2019-09-19 12:12:51,910] ERROR - TenantTransportSender Error while setting up tenant client out service in TenantTransportSender
org.apache.axis2.AxisFault: Two services cannot have same name.  A service with the tenantClientService [null] name already exists in the system.
	at org.apache.axis2.engine.AxisConfiguration.addToAllServicesMap(AxisConfiguration.java:510) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.description.AxisServiceGroup.addService(AxisServiceGroup.java:110) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.wso2.carbon.core.multitenancy.transports.TenantTransportSender.setupTenantClientOutService(TenantTransportSender.java:332) ~[org.wso2.carbon.core_4.5.0.jar:?]
	at org.wso2.carbon.core.multitenancy.transports.TenantTransportSender.<init>(TenantTransportSender.java:80) [org.wso2.carbon.core_4.5.0.jar:?]
	at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.createTenantConfigurationContext(TenantAxisUtils.java:328) [org.wso2.carbon.core_4.5.0.jar:?]
	at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.getTenantConfigurationContext(TenantAxisUtils.java:148) [org.wso2.carbon.core_4.5.0.jar:?]
	at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.getTenantAxisConfiguration(TenantAxisUtils.java:104) [org.wso2.carbon.core_4.5.0.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.loadTenantConfigBlockingMode_aroundBody356(APIUtil.java:6037) [org.wso2.carbon.apimgt.impl_6.5.113.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.loadTenantConfigBlockingMode(APIUtil.java:6033) [org.wso2.carbon.apimgt.impl_6.5.113.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.util.impl.WebAppAuthenticatorImpl.authenticate(WebAppAuthenticatorImpl.java:89) [org.wso2.carbon.apimgt.rest.api.util_6.5.113.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.util.interceptors.auth.OAuthAuthenticationInterceptor.handleRequest(OAuthAuthenticationInterceptor.java:121) [org.wso2.carbon.apimgt.rest.api.util_6.5.113.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.util.interceptors.auth.OAuthAuthenticationInterceptor.handleMessage(OAuthAuthenticationInterceptor.java:66) [org.wso2.carbon.apimgt.rest.api.util_6.5.113.SNAPSHOT.jar:?]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:225) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.22.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80) [org.wso2.carbon.identity.context.rewrite.valve_1.3.4.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100) [org.wso2.carbon.identity.authz.valve_1.3.4.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74) [org.wso2.carbon.identity.auth.valve_1.3.4.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.5.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.5.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.5.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146) [org.wso2.carbon.tomcat.ext_4.5.0.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [tomcat_9.0.22.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.5.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:112) [org.wso2.carbon.tomcat.ext_4.5.0.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.22.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.22.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[2019-09-19 12:12:51,920]  INFO - TenantServiceBusInitializer Intializing the ESB Configuration for the tenant domain : foo.com
[2019-09-19 12:12:51,923]  INFO - SynapseControllerFactory Using Synapse home : /Users/nalaka/Desktop/3.0/9.19/113/repository/tenants/1

**Comment by nalakas** [comment]
https://github.com/wso2/carbon-kernel/pull/2295

**Comment by dushaniw** [comment]
Fixed with  https://github.com/wso2/carbon-kernel/pull/2295
