### ISSUE TITLE
Publishing API with scopes fails if the same scopes were added for a previous API created from Jaggery API and deleted afterwards. .

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#5517]
Hence APIImportExportTest case is failing. 
```
java.io.IOException: Server returned HTTP response code: 500 for URL: https://localhost:9943/api-import-export-test/import-api
	at org.wso2.am.integration.tests.other.APIImportExportTestCase.importAPI(APIImportExportTestCase.java:726)
	at org.wso2.am.integration.tests.other.APIImportExportTestCase.testNewAPIImport(APIImportExportTestCase.java:408)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: https://localhost:9943/api-import-export-test/import-api
	at org.wso2.am.integration.tests.other.APIImportExportTestCase.importAPI(APIImportExportTestCase.java:725)
	at org.wso2.am.integration.tests.other.APIImportExportTestCase.testNewAPIImport(APIImportExportTestCase.java:408)
```
Refer: https://wso2.org/jenkins/view/products/job/products/job/product-apim/org.wso2.am$org.wso2.carbon.am.integration.backend.test/1252/testReport/junit/org.wso2.am.integration.tests.other/APIImportExportTestCase/testNewAPIImport/

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7007/files
