### ISSUE TITLE
IndexOutOfBoundsException when trying to expose backend soap service as REST API

### ISSUE THREAD

**Issue by prats2017** [wso2/product-apim#5534]
I have a legacy SOAP app that we are thinking to hook to WSo2 and expose as rest.
I could successfully create/run a wso2 Pass through SOAP API that would invoke our backend SOAP service. 
Now I am trying to create API that will generate REST APIs but I am getting **_IndexOutOfBoundsException_** when (i think) wso2 tries to parse wsdl.
Also, on Design API Page, Design tab I don't see operations exposed in API Definition section. and the design screen looks like one when I am doing "Pass through".

I am running my logs in debug mode and still am not finding much details than below. Can anyone please look at this please?

[2019-09-11 14:32:25,576] ERROR - **_add:jag org.mozilla.javascript.WrappedException: Wrapped java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 (/publisher/site/blocks/item-design/ajax/add.jag#221)_**
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	.....
	.....
	Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.getComplexTypeMap(WSDL11SOAPOperationExtractor.java:355)
        at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.getParameters(WSDL11SOAPOperationExtractor.java:285)
        at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.getSoapInputParameters(WSDL11SOAPOperationExtractor.java:226)
        at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.getSOAPOperation(WSDL11SOAPOperationExtractor.java:192)
        at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.getSOAPBindingOperations(WSDL11SOAPOperationExtractor.java:163)
        at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.getSoapBindingOperations(WSDL11SOAPOperationExtractor.java:144)
        at org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor.getWsdlInfo(WSDL11SOAPOperationExtractor.java:117)
        at org.wso2.carbon.apimgt.impl.soaptorest.util.SOAPOperationBindingUtils.getSoapOperationMapping(SOAPOperationBindingUtils.java:74)
![image](https://user-images.githubusercontent.com/51544668/64725350-6cffba80-d4a2-11e9-8c23-22fc5e368319.png)

[wsdl.txt](https://github.com/wso2/product-apim/files/3602255/wsdl.txt)

**Comment by prats2017** [comment]
@pubudu538 - Where exactly should I look for wso2am-2.6.0/updates/wum/
I don't think I see  it on my filesystem. I however ran update again today; so looks like patch ran fine yesterday.

c:\Program Files\WUM\bin\bin>wum update wso2am-2.6.0 full
Connecting to WSO2 Update Server...
Using default channel full...
Updating wso2am-2.6.0 via full channel...
**There are no new updates available for the product, 'wso2am-2.6.0'.**

**Comment by prats2017** [comment]
Hi, I installed latest APIM update but it didn't help. I am getting IndexOutOfBoundException when my wsdl is being parsed bt APIM.

[2019-09-16 13:54:22,303] ERROR - add:jag org.mozilla.javascript.WrappedException: **Wrapped java.lang.IndexOutOfBoundsException: Index: 0, Size: 0** (/publisher/site/blocks/item-design/ajax/add.jag#221)
       at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
       at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
