### ISSUE TITLE
Error when adding APIs without endpoint URL

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#5573]
Following error is thrown in console when creating API without specifying endpoints.

```
ERROR - APIMappingUtil Cannot convert endpoint configurations when setting endpoint for API. API ID = admin-test-1
org.json.simple.parser.ParseException: null
	at org.json.simple.parser.JSONParser.parse(Unknown Source) ~[json-simple_1.1.0.wso2v1.jar:?]
	at org.json.simple.parser.JSONParser.parse(Unknown Source) ~[json-simple_1.1.0.wso2v1.jar:?]
	at org.json.simple.parser.JSONParser.parse(Unknown Source) ~[json-simple_1.1.0.wso2v1.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.utils.mappings.APIMappingUtil.fromAPItoDTO(APIMappingUtil.java:622) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.getAPIByID(ApisApiServiceImpl.java:3156) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.apisApiIdGet(ApisApiServiceImpl.java:409) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.apisApiIdGet(ApisApi.java:329) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor320.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]

```
Since, creating API without endpoint is allowed, null check should be added in [1] to avoid this error in console.
[1] https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/utils/mappings/APIMappingUtil.java#L622

**Comment by menakaj** [comment]
Duplicate https://github.com/wso2/product-apim/issues/5570
