### ISSUE TITLE
UI: Subscribe without selecting a tier does not provide any message

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#5594]
Subscribe to an API without selecting any policy in store. No error message is shown in the UI. Error is logged in the carbon console

    [2019-09-18 10:52:59,643] ERROR - GlobalThrowableMapper One or more request body parameters contain disallowed values.
    com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
     at [Source: (org.apache.cxf.transport.http.AbstractHTTPDestination$1); line: 1, column: 123] (through reference chain: org.wso2.carbon.apimgt.rest.api.store.v1.dto.SubscriptionDTO["throttlingPolicy"])
	    at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63) ~[jackson-databind-2.9.9.3.jar:2.9.9.2]
	    at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343) ~[jackson-databind-2.9.9.3.jar:2.9.9.2]

**Comment by prasa7** [comment]
Fixed in 3.x.x
