### ISSUE TITLE
[Store] Rest api resources are not shown in store when API is created APIs using WSDL

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#5606]
Steps: 
1. Select 'I have a SOAP endpoint'
2. Provide a wsdl endpoint (say http://localhost:9000/services/SimpleStockQuoteService?wsdl) and select generate a rest api option
3. publish the api

Go to the store and check the **Resources** section. It has loading message but resources are not shown. Following error is shown in the log

[2019-09-18 14:30:39,064] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
	java.util.NoSuchElementException: null
		at java.util.HashMap$HashIterator.nextNode(HashMap.java:1444) ~[?:1.8.0_161]
		at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_161]
		at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApisApiServiceImpl.apisApiIdSwaggerGet(ApisApiServiceImpl.java:548) ~[classes/:?]
		at org.wso2.carbon.apimgt.rest.api.store.v1.ApisApi.apisApiIdSwaggerGet(ApisApi.java:223) ~[classes/:?]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]

**Comment by chamilaadhi** [comment]
Additionally, there are some parsing errors in the swagger file generated for this API.
