### ISSUE TITLE
[Store] SDK generation fails for API created using WSDL with SOAP to Rest API mapping option

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#5693]
[Store] SDK generation fails for API created using WSDL with SOAP to Rest API mapping option

1. Create a API using the wsdl url (ex: http://localhost:8280/services/Version?wsdl ) and select the Generate REST APIs Option
2. Login to the store and generate a SDK for that API

Following error is thrown and SDK is not generated

	[2019-09-23 10:21:17,611] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
	org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
	 | Error count: 1, Warning count: 3
	Errors:
		-attribute paths.'/getVersion'(get).default.responseSchema is unexpected
	Warnings:
		-attribute paths.'/getVersion'(get).default.responseSchema is unexpected

		at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:606) ~[openapi-generator_4.0.1.wso2v2.jar:?]
		at org.wso2.carbon.apimgt.impl.APIClientGenerationManager.generateClient_aroundBody6(APIClientGenerationManager.java:241) ~[org.wso2.carbon.apimgt.impl_6.5.121.jar:?]
		at org.wso2.carbon.apimgt.impl.APIClientGenerationManager.generateClient(APIClientGenerationManager.java:229) ~[org.wso2.carbon.apimgt.impl_6.5.121.jar:?]
		at org.wso2.carbon.apimgt.impl.APIClientGenerationManager.generateSDK_aroundBody0(APIClientGenerationManager.java:180) ~[org.wso2.carbon.apimgt.impl_6.5.121.jar:?]
		at org.wso2.carbon.apimgt.impl.APIClientGenerationManager.generateSDK(APIClientGenerationManager.java:93) ~[org.wso2.carbon.apimgt.impl_6.5.121.jar:?]
		at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApisApiServiceImpl.apisApiIdSdksLanguageGet(ApisApiServiceImpl.java:523) ~[classes/:?]
		at org.wso2.carbon.apimgt.rest.api.store.v1.ApisApi.apisApiIdSdksLanguageGet(ApisApi.java:187) ~[classes/:?]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]

**Comment by chamilaadhi** [comment]
fix done for https://github.com/wso2/product-apim/issues/5699 fixes this issue. sdk can be downloaded. but when building the sdk it throws an error. 

Reason for that is <version> in the pom file is missing. need to check this

**Comment by chamilaadhi** [comment]
fix the version and title issue in the pom from https://github.com/wso2/carbon-apimgt/pull/7162
