### ISSUE TITLE
Issue in redirection between tenants

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#5753]
**Steps followed:**
Created 3 APIs using super tenant
Created a new tenant
Logged in using the newly created tenant's admin
Then clicked on "GO TO PUBLIC STORE" (without logging out of the tenant's admin)
Navigated to "carbon.super"
As shown in the below screenshot that tenant's admin is still logged in
![WSO2 Developer Portal](https://user-images.githubusercontent.com/30475839/65572148-c4168c80-df84-11e9-8709-5d3e3461c3c9.png)

Then, when trying out one of the created APIs under the "TEST" option, error encountered.
![2](https://user-images.githubusercontent.com/30475839/65572168-da244d00-df84-11e9-9860-ee43582f1049.png)

This is the error found within the browser element inpsect windown
![3](https://user-images.githubusercontent.com/30475839/65572463-d218dd00-df85-11e9-8a41-8b7809c6ab4a.png)

**Comment by chamilaadhi** [comment]
Additionally an error log is printed in the console when select the api

org.wso2.carbon.apimgt.api.APIMgtResourceNotFoundException: Failed to get API. API artifact corresponding to artifactId 9844becd-f317-4d91-9245-e6e3cad10ae6 does not exist
		at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getAPIorAPIProductByUUID_aroundBody22(AbstractAPIManager.java:573) ~[org.wso2.carbon.apimgt.impl_6.5.231.jar:?]
		at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getAPIorAPIProductByUUID(AbstractAPIManager.java:540) ~[org.wso2.carbon.apimgt.impl_6.5.231.jar:?]
		at org.wso2.carbon.apimgt.rest.api.store.v1.impl.SubscriptionsApiServiceImpl.subscriptionsGet(SubscriptionsApiServiceImpl.java:110) [classes/:?]
		at org.wso2.carbon.apimgt.rest.api.store.v1.SubscriptionsApi.subscriptionsGet(SubscriptionsApi.java:57) [classes/:?]

**Comment by chamilaadhi** [comment]
Related issue https://github.com/wso2/product-apim/issues/6378
