### ISSUE TITLE
[APIM 3.0.0] Cannot update keys after editing application name

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#5962]
1) Create Application
2) Generate keys
3) Edit application name
4) Update keys.

**Comment by dushaniw** [comment]
Can be reproduced in 3.1.0 Alpha.

```
[2020-02-11 17:09:46,068] ERROR - APIUtil Error occurred while creating ServiceProvider for app admin_DefaultApplicationUpdated_PRODUCTION
org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error occurred while updating the application: admin_DefaultApplicationUpdated_PRODUCTION. Illegal Access! User: admin does not have access to update the application: 'admin_DefaultApplicationUpdated_PRODUCTION' in tenantDomain: carbon.super
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.updateApplication(ApplicationManagementServiceImpl.java:594) ~[org.wso2.carbon.identity.application.mgt_5.16.39.jar:?]
	at org.wso2.carbon.apimgt.keymgt.service.APIKeyMgtSubscriberService.updateOAuthApplication_aroundBody4(APIKeyMgtSubscriberService.java:429) [org.wso2.carbon.apimgt.keymgt_6.6.35.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.keymgt.service.APIKeyMgtSubscriberService.updateOAuthApplication(APIKeyMgtSubscriberService.java:330) [org.wso2.carbon.apimgt.keymgt_6.6.35.SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at org.apache.axis2.rpc.receivers.RPCUtil.invokeServiceClass(RPCUtil.java:212) [axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.rpc.receivers.RPCMessageReceiver.invokeBusinessLogic
...
Caused by: org.wso2.carbon.identity.application.common.IdentityApplicationManagementClientException: Illegal Access! User: admin does not have access to update the application: 'admin_DefaultApplicationUpdated_PRODUCTION' in tenantDomain: carbon.super
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.buildClientException(ApplicationManagementServiceImpl.java:2407) ~[org.wso2.carbon.identity.application.mgt_5.16.39.jar:?]
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.validateAuthorization(ApplicationManagementServiceImpl.java:2270) ~[org.wso2.carbon.identity.application.mgt_5.16.39.jar:?]
...
[2020-02-11 17:09:46,133] ERROR - AbstractKeyManager Error occurred while updating OAuth Client : 
org.apache.axis2.AxisFault: null
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.wso2.carbon.apimgt.keymgt.stub.subscriber.APIKeyMgtSubscriberServiceStub.fromOM(APIKeyMgtSubscriberServiceStub.java:3386) ~[org.wso2.carbon.apimgt.keymgt.stub_6.6.35.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.keymgt.stub.subscriber.APIKeyMgtSubscriberServiceStub.updateOAuthApplication(APIKeyMgtSubscriberServiceStub.java:1670) ~[org.wso2.carbon.apimgt.keymgt.stub_6.6.35.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.keymgt.client.SubscriberKeyMgtClient.updateOAuthApplication(SubscriberKeyMgtClient.java:100) ~[org.wso2.carbon.apimgt.keymgt.client_6.6.35.SNAPSHOT.jar:?]
...
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.apimgt.api.xsd.ErrorHandler$Factory.parse(ErrorHandler.java:616) ~[org.wso2.carbon.apimgt.keymgt.stub_6.6.35.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.api.xsd.APIManagementException$Factory.parse(APIManagementException.java:416) ~[org.wso2.carbon.apimgt.keymgt.stub_6.6.35.SNAPSHOT.jar:?]
...
[2020-02-11 17:09:46,148] ERROR - ApplicationsApiServiceImpl Error while updating application 90218689-2e38-4d69-94d8-6d105e354526
org.wso2.carbon.apimgt.api.APIManagementException: Error occurred while updating OAuth Client : 
	at org.wso2.carbon.apimgt.impl.AbstractKeyManager.handleException_aroundBody6(AbstractKeyManager.java:165) ~[org.wso2.carbon.apimgt.impl_6.6.35.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractKeyManager.handleException(AbstractKeyManager.java:163) ~[org.wso2.carbon.apimgt.impl_6.6.35.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.updateApplication_aroundBody2(AMDefaultKeyManagerImpl.java:227) ~[org.wso2.carbon.apimgt.impl_6.6.35.SNAPSHOT.jar:?]
...
Caused by: org.apache.axis2.AxisFault
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.wso2.carbon.apimgt.keymgt.stub.subscriber.APIKeyMgtSubscriberServiceStub.fromOM(APIKeyMgtSubscriberServiceStub.java:3386) ~[org.wso2.carbon.apimgt.keymgt.stub_6.6.35.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.keymgt.stub.subscriber.APIKeyMgtSubscriberServiceStub.updateOAuthApplication(APIKeyMgtSubscriberServiceStub.java:1670) ~[org.wso2.carbon.apimgt.keymgt.stub_6.6.35.SNAPSHOT.jar:?]
...
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.apimgt.api.xsd.ErrorHandler$Factory.parse(ErrorHandler.java:616) ~[org.wso2.carbon.apimgt.keymgt.stub_6.6.35.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.api.xsd.APIManagementException$Factory.parse(APIManagementException.java:416) ~[org.wso2.carbon.apimgt.keymgt.stub_6.6.35.SNAPSHOT.jar:?]

```
