### ISSUE TITLE
[Publisher] Unable to update API with sandbox endpoint / production endpoint

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#6287]
When updating API with only sandbox endpoint, following error is logged in console:

```
org.json.JSONException: JSONObject["production_endpoints"] not found.
	at org.json.JSONObject.get(JSONObject.java:473) ~[json_3.0.0.wso2v1.jar:?]
	at org.json.JSONObject.getJSONObject(JSONObject.java:573) ~[json_3.0.0.wso2v1.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.setPrimaryConfig_aroundBody28(OASParserUtil.java:529) ~[org.wso2.carbon.apimgt.impl_6.5.187.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.setPrimaryConfig(OASParserUtil.java:525) ~[org.wso2.carbon.apimgt.impl_6.5.187.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.generateOASConfigForEndpoints_aroundBody22(OASParserUtil.java:439) ~[org.wso2.carbon.apimgt.impl_6.5.187.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.generateOASConfigForEndpoints(OASParserUtil.java:420) ~[org.wso2.carbon.apimgt.impl_6.5.187.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OAS3Parser.getOASDefinitionForPublisher_aroundBody22(OAS3Parser.java:468) ~[org.wso2.carbon.apimgt.impl_6.5.187.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OAS3Parser.getOASDefinitionForPublisher(OAS3Parser.java:452) ~[org.wso2.carbon.apimgt.impl_6.5.187.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.apisApiIdSwaggerGet(ApisApiServiceImpl.java:2225) ~[classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.apisApiIdSwaggerGet(ApisApi.java:796) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]

```

**Comment by vithu30** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/7351
