### ISSUE TITLE
Error when deploying sample API in tenant mode

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#6345]
Following error occrred when a tenant admin deploying sample API:
```
ERROR - APITemplateBuilderImpl Velocity Error
org.wso2.carbon.apimgt.api.APIManagementException: At least one resource is required
	at org.wso2.carbon.apimgt.impl.template.ResourceConfigContext.validate_aroundBody0(ResourceConfigContext.java:60) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ResourceConfigContext.validate(ResourceConfigContext.java:57) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate_aroundBody0(ConfigContextDecorator.java:33) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate(ConfigContextDecorator.java:32) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate_aroundBody0(ConfigContextDecorator.java:33) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate(ConfigContextDecorator.java:32) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.EndpointConfigContext.validate_aroundBody0(EndpointConfigContext.java:41) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.EndpointConfigContext.validate(EndpointConfigContext.java:40) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate_aroundBody0(ConfigContextDecorator.java:33) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate(ConfigContextDecorator.java:32) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate_aroundBody0(ConfigContextDecorator.java:33) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate(ConfigContextDecorator.java:32) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate_aroundBody0(ConfigContextDecorator.java:33) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate(ConfigContextDecorator.java:32) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate_aroundBody0(ConfigContextDecorator.java:33) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate(ConfigContextDecorator.java:32) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate_aroundBody0(ConfigContextDecorator.java:33) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate(ConfigContextDecorator.java:32) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate_aroundBody0(ConfigContextDecorator.java:33) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate(ConfigContextDecorator.java:32) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate_aroundBody0(ConfigContextDecorator.java:33) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.ConfigContextDecorator.validate(ConfigContextDecorator.java:32) ~[org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.APITemplateBuilderImpl.getConfigStringForTemplate_aroundBody0(APITemplateBuilderImpl.java:100) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.template.APITemplateBuilderImpl.getConfigStringForTemplate(APITemplateBuilderImpl.java:86) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIGatewayAdminClient.addApi_aroundBody2(APIGatewayAdminClient.java:94) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIGatewayAdminClient.addApi(APIGatewayAdminClient.java:91) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIGatewayManager.publishToGateway_aroundBody2(APIGatewayManager.java:258) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIGatewayManager.publishToGateway(APIGatewayManager.java:106) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.publishToGateway_aroundBody90(APIProviderImpl.java:1878) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.publishToGateway(APIProviderImpl.java:1855) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.propergateAPIStatusChangeToGateways_aroundBody78(APIProviderImpl.java:1655) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.propergateAPIStatusChangeToGateways(APIProviderImpl.java:1621) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.propergateAPIStatusChangeToGateways_aroundBody28(UserAwareAPIProvider.java:175) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.propergateAPIStatusChangeToGateways(UserAwareAPIProvider.java:172) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.executors.APIExecutor.changeLifeCycle_aroundBody4(APIExecutor.java:178) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.executors.APIExecutor.changeLifeCycle(APIExecutor.java:146) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.executors.APIExecutor.execute_aroundBody2(APIExecutor.java:124) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.executors.APIExecutor.execute(APIExecutor.java:89) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.governance.registry.extensions.aspects.DefaultLifeCycle.runCustomExecutorsCode(DefaultLifeCycle.java:712) [org.wso2.carbon.governance.registry.extensions_4.8.8.jar:?]
	at org.wso2.carbon.governance.registry.extensions.aspects.DefaultLifeCycle.invoke(DefaultLifeCycle.java:450) [org.wso2.carbon.governance.registry.extensions_4.8.8.jar:?]
	at org.wso2.carbon.governance.registry.eventing.handlers.GovernanceEventingHandler.invokeAspect(GovernanceEventingHandler.java:366) [org.wso2.carbon.governance.registry.eventing_4.8.8.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.invokeAspect(HandlerManager.java:2794) [org.wso2.carbon.registry.core_4.5.1.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.invokeAspect(HandlerLifecycleManager.java:518) [org.wso2.carbon.registry.core_4.5.1.jar:?]
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.invokeAspect(EmbeddedRegistry.java:2607) [org.wso2.carbon.registry.core_4.5.1.jar:?]
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.invokeAspect(CacheBackedRegistry.java:510) [org.wso2.carbon.registry.core_4.5.1.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry.invokeAspect(UserRegistry.java:1952) [org.wso2.carbon.registry.core_4.5.1.jar:?]
	at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.invokeAction(GovernanceArtifactImpl.java:829) [org.wso2.carbon.governance.api_4.8.8.jar:?]
	at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.invokeAction(GovernanceArtifactImpl.java:808) [org.wso2.carbon.governance.api_4.8.8.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.changeLifeCycleStatus_aroundBody228(APIProviderImpl.java:4833) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.changeLifeCycleStatus(APIProviderImpl.java:4760) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.changeLifeCycleStatus_aroundBody74(UserAwareAPIProvider.java:326) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.changeLifeCycleStatus(UserAwareAPIProvider.java:322) [org.wso2.carbon.apimgt.impl_6.5.208.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.apisChangeLifecyclePost(ApisApiServiceImpl.java:3147) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.apisChangeLifecyclePost(ApisApi.java:855) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]

```

Cannot publish APIs in tenant mode.

**Comment by vithu30** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/7431
