### ISSUE TITLE
MaxEntityCount property is not supported by the woodstox library

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-apim#6581]
I tried to validate the XML payload against following xml_validator policy.
![image](https://user-images.githubusercontent.com/12996810/67199380-c43c6780-f41e-11e9-824c-e7bdf7c087df.png)

But Im getting an exception 
**[2019-10-21 16:10:35,132]  INFO - LogMediator IN_MESSAGE = xml_validator
[2019-10-21 16:10:35,171] ERROR - AnalyzerHolder Threat Protection: Error occurred while getting an object from the pool.
java.lang.IllegalArgumentException: Unrecognized property 'com.ctc.wstx.maxEntityCount'
	at com.ctc.wstx.api.CommonConfig.reportUnknownProperty(CommonConfig.java:168) ~[woodstox-core-asl-4.4.1.jar:4.4.1]
	at com.ctc.wstx.api.CommonConfig.setProperty(CommonConfig.java:159) ~[woodstox-core-asl-4.4.1.jar:4.4.1]**

**Comment by hasuniea** [comment]
I tried to validate the XML payload against following xml_validator policy.
**<sequence xmlns="http://ws.apache.org/ns/synapse" name="admin--TT:v1.0.0--In">
    <log level="custom">
        <property name="IN_MESSAGE" value="xml_validator"/>
    </log>
    <property name="xmlValidation" value="true"/>
    <property name="dtdEnabled" value="false"/>
    <property name="externalEntitiesEnabled" value="true"/>
    <property name="maxXMLDepth" value="10"/>
    <property name="maxElementCount" value="10"/>
    <property name="maxAttributeCount" value="10"/>
    <property name="maxAttributeLength" value="10"/>
    <property name="entityExpansionLimit" value="10"/>
    <property name="maxChildrenPerElement" value="10"/>
    <property name="schemaValidation" value="false"/>
    <switch xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope" xmlns:ns3="http://org.apache.synapse/xsd" source="get-property('To')">
        
        
        
        
        
        
        
        
        
    </switch>
    <property name="RequestMessageBufferSize" value="1024"/>
    <class name="org.wso2.carbon.apimgt.gateway.mediators.XMLSchemaValidator"/>
</sequence>**

But Im getting an exception 
**[2019-10-21 16:10:35,132]  INFO - LogMediator IN_MESSAGE = xml_validator
[2019-10-21 16:10:35,171] ERROR - AnalyzerHolder Threat Protection: Error occurred while getting an object from the pool.
java.lang.IllegalArgumentException: Unrecognized property 'com.ctc.wstx.maxEntityCount'
	at com.ctc.wstx.api.CommonConfig.reportUnknownProperty(CommonConfig.java:168) ~[woodstox-core-asl-4.4.1.jar:4.4.1]
	at com.ctc.wstx.api.CommonConfig.setProperty(CommonConfig.java:159) ~[woodstox-core-asl-4.4.1.jar:4.4.1]**

**Comment by hasuniea** [comment]
https://github.com/wso2/carbon-apimgt/pull/7691/commits/b67797740dc9a8f8268f4903bf591cbc400e2fd9
