### ISSUE TITLE
 Create new version of API with empty role scope throws NPE

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#6641]
Version: wso2am-2.6.0+1571422065365

Steps:
1. Create an API and assign an empty role scope
2. Create a new version of that API.

The following error is thrown.

	[2019-10-24 10:42:26,795]  INFO - CarbonAuthenticationUtil 'admin@carbon.super [-1234]' logged in at [2019-10-24 10:42:26,795+0530]
	[2019-10-24 10:42:41,418] ERROR - UserAwareAPIProvider Failed to create new version : 2 of : PizzaShackAPI
	java.lang.NullPointerException
		at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
		at com.google.common.base.Splitter.split(Splitter.java:376)
		at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addScopes_aroundBody340(ApiMgtDAO.java:7540)
		at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addScopes(ApiMgtDAO.java:7458)
		at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addAPI_aroundBody218(ApiMgtDAO.java:5069)
		at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addAPI(ApiMgtDAO.java:5027)
		at org.wso2.carbon.apimgt.impl.APIProviderImpl.createNewAPIVersion_aroundBody106(APIProviderImpl.java:2404)
		at org.wso2.carbon.apimgt.impl.APIProviderImpl.createNewAPIVersion(APIProviderImpl.java:2126)
		at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.createNewAPIVersion_aroundBody2(UserAwareAPIProvider.java:73)
		at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.createNewAPIVersion(UserAwareAPIProvider.java:68)
		at org.wso2.carbon.apimgt.hostobjects.APIProviderHostObject.jsFunction_createNewAPIVersion(APIProviderHostObject.java:3658)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

**Comment by chamilaadhi** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/7094/files
