### ISSUE TITLE
Product duplicate context

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#6684]
**labels**
3.0.0 rc3

**Description**
Creation of products with duplicate context is allowed. 
A similar error will be logged,

`Caused by: org.apache.axis2.AxisFault: Error while publishing API to the Gateway. No API exists by the name: prod--jkhkjh:v1.0.0
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:382) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:457) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.wso2.carbon.apimgt.gateway.stub.APIGatewayAdminStub.addApiForTenant(APIGatewayAdminStub.java:6301) ~[org.wso2.carbon.apimgt.gateway.stub_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIGatewayAdminClient.addApi_aroundBody2(APIGatewayAdminClient.java:97) ~[org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	... 62 more
[2019-10-25 12:51:22,577] ERROR - ApiProductsApiServiceImpl Error while adding new API Product : amali@amali.com-jkhkjh - null`

**Comment by HiranyaKavishani** [comment]
Seems this is reproduced for tenant user.
