### ISSUE TITLE
Error while creating product 

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#6706]
**version**
3.0.0 rc3

**steps to reproduce**
Deploy sample api
Create and publish another api (openapi 3).
Create a product with a sample api(pizzashack api) resource and a resource from the created api.

**Error**
`ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.processReferenceObjectMap_aroundBody10(OASParserUtil.java:340) ~[org.wso2.carbon.apimgt.impl_6.5.343.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.processReferenceObjectMap(OASParserUtil.java:314) ~[org.wso2.carbon.apimgt.impl_6.5.343.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.setReferenceObjectDefinitions_aroundBody8(OASParserUtil.java:256) ~[org.wso2.carbon.apimgt.impl_6.5.343.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.setReferenceObjectDefinitions(OASParserUtil.java:255) ~[org.wso2.carbon.apimgt.impl_6.5.343.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.updateAPIProductSwaggerOperations_aroundBody4(OASParserUtil.java:225) ~[org.wso2.carbon.apimgt.impl_6.5.343.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.updateAPIProductSwaggerOperations(OASParserUtil.java:202) ~[org.wso2.carbon.apimgt.impl_6.5.343.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApiProductsApiServiceImpl.addAPIProductSwagger(ApiProductsApiServiceImpl.java:752) ~[classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApiProductsApiServiceImpl.apiProductsPost(ApiProductsApiServiceImpl.java:721) ~[classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApiProductsApi.apiProductsPost(ApiProductsApi.java:328) ~[classes/:?]`

**Comment by tharikaGitHub** [comment]
This issue is not reproducible in the latest pack of API Manager. Hence will be closing the issue.
