### ISSUE TITLE
Exception when using callout mediator which calls an endpoint which returns 202

### ISSUE THREAD

**Issue by Schljk3bnz69** [wso2/product-apim#6713]
1 . Create an API with extension sequence which calls an endpoint (blocking = false)
2.   Below exception can be seen

```
INFO - HTTPSender Unable to sendViaGet to url[http://192.168.20.1:8280/loginAPI/login]
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
        at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
        at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
        at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)
        at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
        at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.axis2.transport.http.AbstractHTTPSender.executeMethod(AbstractHTTPSender.java:712)
        at org.apache.axis2.transport.http.HTTPSender.sendViaGet(HTTPSender.java:108)
        at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:63)
        at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:459)
        at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:286)
        at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
        at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:442)
        at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228)
        at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
        at org.apache.synapse.message.senders.blocking.BlockingMsgSender.sendReceive(BlockingMsgSender.java:492)
        at org.apache.synapse.message.senders.blocking.BlockingMsgSender.send(BlockingMsgSender.java:384)
        at org.apache.synapse.core.axis2.Axis2FlexibleMEPClient.send(Axis2FlexibleMEPClient.java:92)
        at org.apache.synapse.core.axis2.Axis2Sender.sendOn(Axis2Sender.java:85)
        at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:569)
        at org.apache.synapse.endpoints.AbstractEndpoint.send(AbstractEndpoint.java:398)
        at org.apache.synapse.endpoints.AddressEndpoint.send(AddressEndpoint.java:65)
        at org.apache.synapse.mediators.builtin.CalloutMediator.mediate(CalloutMediator.java:229)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.rest.Resource.process(Resource.java:363)
        at org.apache.synapse.rest.API.process(API.java:431)
        at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:135)
        at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:113)
        at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
        at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:325)
        at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:92)
        at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
        at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:338)
        at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:159)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2019-10-29 09:04:07,028] [] ERROR - SourceHandler I/O error: An established connection was aborted by the software in your host machine
java.io.IOException: An established connection was aborted by the software in your host machine
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.apache.synapse.transport.http.conn.LoggingIOSession$LoggingByteChannel.read(LoggingIOSession.java:191)
        at org.apache.http.impl.nio.reactor.SessionInputBufferImpl.fill(SessionInputBufferImpl.java:164)
        at org.apache.http.impl.nio.codecs.AbstractMessageParser.fillBuffer(AbstractMessageParser.java:136)
        at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection$LoggingNHttpMessageParser.fillBuffer(LoggingNHttpServerConnection.java:403)
        at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection.consumeInputWire(LoggingNHttpServerConnection.java:162)
        at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection.consumeInput(LoggingNHttpServerConnection.java:116)
        at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:82)
        at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:39)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:113)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
        at java.lang.Thread.run(Thread.java:748)
[2019-10-29 09:10:53,892] []  INFO - CarbonServerManager Shutdown hook triggered....
[2019-10-29 09:10:53,893] []  INFO - CarbonServerManager Gracefully shutting down WSO2 Enterprise Integrator...
[2019-10-29 09:10:53,897] []  INFO - ServerManagement Starting to switch to maintenance mode...
[2019-10-29 09:10:53,898] []  INFO - VFSTransportListener VFS Listener Shutdown
[2019-10-29 09:10:53,898] []  INFO - PassThroughHttpListener Stopping Pass-through HTTP Listener..
[2019-10-29 09:10:53,899] []  INFO - PassThroughListeningIOReactorManager Shutting down IO Reactor bind for port 8280
[2019-10-29 09:10:53,903] []  INFO - PassThroughListeningIOReactorManager HTTP-Listener I/O dispatcher Listener shutdown.
[2019-10-29 09:10:53,921] []  INFO - PassThroughHttpSSLListener Stopping Pass-through HTTPS Listener..
[2019-10-29 09:10:53,922] []  INFO - PassThroughListeningIOReactorManager Shutting down IO Reactor bind for port 8243
[2019-10-29 09:10:53,926] []  INFO - PassThroughListeningIOReactorManager HTTPS-Listener I/O dispatcher Listener shutdown.
[2019-10-29 09:10:53,927] []  INFO - ServerManagement Stopped all transport listeners
[2019-10-29 09:10:53,927] []  INFO - ServerManagement Waiting for request service completion...
[2019-10-29 09:10:53,933] []  INFO - ServerManagement All requests have been served.
[2019-10-29 09:10:53,933] []  INFO - ServerManagement Waiting for deployment completion...
[2019-10-29 09:10:53,964] []  INFO - WebApplication Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/odata]
[2019-10-29 09:10:53,964] []  INFO - ServerManagement All deployment tasks have been completed.
[2019-10-29 09:10:53,965] []  INFO - ServerManagement Waiting for server task completion...
[2019-10-29 09:10:53,966] []  INFO - ServerManagement All server tasks have been completed.
[2019-10-29 09:10:53,967] []  INFO - CarbonServerManager Shutting down WSO2 Enterprise Integrator...
[2019-10-29 09:10:53,968] []  INFO - CarbonServerManager Shutting down OSGi framework...
[2019-10-29 09:10:54,025] []  WARN - MediationPersistenceManager Mediation persistence manager is either not initialized or not in the 'accepting' mode. Ignoring the save request.
[2019-10-29 09:10:54,025] []  INFO - Axis2SynapseController Undeploying the Synapse service...
[2019-10-29 09:10:54,026] []  INFO - Axis2SynapseController Undeploying Proxy services...
[2019-10-29 09:10:54,027] []  INFO - DeploymentInterceptor Removing Axis2 Service: Sample {super-tenant}
[2019-10-29 09:10:54,029] []  INFO - Axis2SynapseController Undeploying EventSources...
[2019-10-29 09:10:54,031] []  INFO - API Destroying API: HealthcareAPI
[2019-10-29 09:10:54,033] []  INFO - API Destroying API: LoginAPI
[2019-10-29 09:10:54,035] []  INFO - API Destroying API: StaffAPI
[2019-10-29 09:10:54,037] []  INFO - SynapseTaskManager Shutting down the task manager
[2019-10-29 09:10:54,038] []  INFO - SynapseDebugInterface Debug connection closed
```

**Comment by tharikaGitHub** [comment]
Hi @Schljk3bnz69, will you be able to let us know which version of API Manager you are using?
