### ISSUE TITLE
APIM 3.0 : Unable to add mediation policies

### ISSUE THREAD

**Issue by awedi** [wso2/product-apim#6740]
When trying to add a mediation policy into the API, receiving error on windows that the path cannot contain a slash ("\"). This blocks the customization of the API flow completely. I believe it wouldn't fail on a linux/AIX implementation.

Using APIM Binary 3.0

![APIError](https://user-images.githubusercontent.com/34669964/67892041-423cf480-fb2a-11e9-9f42-cfeeaefdc9ab.JPG)

**Error Log:**
[2019-10-30 15:28:37,034] ERROR - ApisApiServiceImpl Error while adding the mediation policy : C:\Users\xxxx\Desktop\xxxx_OUT_Main_SEQ.xmlof API 4169e55a-2e79-486e-8ba8-baa377552d2f
org.wso2.carbon.apimgt.api.APIManagementException: Error while adding the resource to the registry
        at org.wso2.carbon.apimgt.impl.AbstractAPIManager.addResourceFile_aroundBody68(AbstractAPIManager.java:1269) ~[org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
        at org.wso2.carbon.apimgt.impl.AbstractAPIManager.addResourceFile(AbstractAPIManager.java:1247) ~[org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
        at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addResourceFile_aroundBody108(UserAwareAPIProvider.java:449) ~[org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
        at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addResourceFile(UserAwareAPIProvider.java:446) ~[org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.apisApiIdMediationPoliciesPost(ApisApiServiceImpl.java:2024) [classes/:?]
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.apisApiIdMediationPoliciesPost(ApisApi.java:526) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.2.8.jar:3.2.8]
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.2.8.jar:3.2.8]
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.2.8.jar:3.2.8]
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.2.8.jar:3.2.8]
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.2.8.jar:3.2.8]
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.2.8.jar:3.2.8]
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.22.wso2v1.jar:?]
        at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80) [org.wso2.carbon.identity.context.rewrite.valve_1.3.6.jar:?]
        at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100) [org.wso2.carbon.identity.authz.valve_1.3.6.jar:?]
        at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74) [org.wso2.carbon.identity.auth.valve_1.3.6.jar:?]
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [tomcat_9.0.22.wso2v1.jar:?]
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
        at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:116) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.22.wso2v1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.22.wso2v1.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: org.wso2.carbon.registry.core.exceptions.RegistryException: Unable to put resource The path '/_system/governance/apimgt/applicationdata/provider/admin/PartnersAcxiom/1.0/in/C:\Users\xxxx\Desktop\xxxxx_OUT_Main_SEQ.xml' contains one or more illegal characters (~!@#;%^*()+={}|\<>"',)
        at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:299) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2505) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.put(UserDefinedHandlerManager.java:204) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:950) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:705) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.put(CacheBackedRegistry.java:591) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:828) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:61) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:804) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:801) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
        at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:801) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.apimgt.impl.AbstractAPIManager.addResourceFile_aroundBody68(AbstractAPIManager.java:1252) ~[org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
        ... 57 more
Caused by: org.wso2.carbon.registry.core.exceptions.RegistryException: The path '/_system/governance/apimgt/applicationdata/provider/admin/PartnersAcxiom/1.0/in/C:\Users\xxxx\Desktop\xxxx_OUT_Main_SEQ.xml' contains one or more illegal characters (~!@#;%^*()+={}|\<>"',)
        at org.wso2.carbon.registry.core.jdbc.Repository.put(Repository.java:262) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:717) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:828) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:61) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:804) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:801) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
        at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:801) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:292) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2505) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.put(UserDefinedHandlerManager.java:204) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:950) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:705) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.put(CacheBackedRegistry.java:591) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:828) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:61) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:804) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:801) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
        at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:801) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
        at org.wso2.carbon.apimgt.impl.AbstractAPIManager.addResourceFile_aroundBody68(AbstractAPIManager.java:1252) ~[org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
        ... 57 more

**Comment by awedi** [comment]
The issue is not present if a Windows installation is used for API Manager.  Issue present only in the binary version of the software
