### ISSUE TITLE
Bot Detection Data display error in Admin portal

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#6779]
Once analytics is configured with API Manager a user should be able to view Bot Detection data. Eventhough there is bot detection information there is an error when viewing the data in the admin portal.

<img width="1676" alt="Screen Shot 2019-11-07 at 10 52 56 AM" src="https://user-images.githubusercontent.com/19324135/68362885-dc1a2800-014e-11ea-9a66-d2e2e42af736.png">

**Comment by tharikaGitHub** [comment]
This is the error that is logged in the server console.

```
[2019-11-08 15:29:35,324] ERROR - APIUtil Error while invoking SP rest api :  404 Not Found
[2019-11-08 15:29:35,350] ERROR - alert-list:jag Error occurred while getting alerts (Cause:org.wso2.carbon.apimgt.api.APIManagementException: Error while invoking SP rest api :  404 Not Found)
[2019-11-08 15:29:35,368] ERROR - WebAppManager org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from undefined (/admin/site/themes/wso2/templates/bot-detected-data-list/template.jag#12)
org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from undefined (/admin/site/themes/wso2/templates/bot-detected-data-list/template.jag#12)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:587) ~[org.jaggeryjs.scriptengine_0.14.11.jar:?]
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:289) ~[org.jaggeryjs.scriptengine_0.14.11.jar:?]
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:589) [org.jaggeryjs.jaggery.core_0.14.11.jar:?]
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508) [org.jaggeryjs.jaggery.core_0.14.11.jar:?]
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24) [org.jaggeryjs.jaggery.core_0.14.11.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) [tomcat_9.0.22.wso2v1.jar:?]
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:76) [org.jaggeryjs.jaggery.core_0.14.11.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53) [org.wso2.carbon.ui_4.5.1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.22.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80) [org.wso2.carbon.identity.context.rewrite.valve_1.3.6.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100) [org.wso2.carbon.identity.authz.valve_1.3.6.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74) [org.wso2.carbon.identity.auth.valve_1.3.6.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [tomcat_9.0.22.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:116) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.22.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.22.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from undefined (/admin/site/themes/wso2/templates/bot-detected-data-list/template.jag#12)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3687) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3665) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3693) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3712) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.ScriptRuntime.undefReadError(ScriptRuntime.java:3725) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1483) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.jaggeryjs.rhino.admin.site.themes.wso_2.templates.bot_detected_data_list.c0._c_anonymous_1(/admin/site/themes/wso2/templates/bot-detected-data-list/template.jag:12) ~[?:?]
	at org.jaggeryjs.rhino.admin.site.themes.wso_2.templates.bot_detected_data_list.c0.call(/admin/site/themes/wso2/templates/bot-detected-data-list/template.jag) ~[?:?]
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.jaggeryjs.rhino.admin.jagg.c0._c_anonymous_32(/admin/jagg/jagg.jag:205) ~[?:?]
	at org.jaggeryjs.rhino.admin.jagg.c0.call(/admin/jagg/jagg.jag) ~[?:?]
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.jaggeryjs.rhino.admin.jagg.c0._c_anonymous_57(/admin/jagg/jagg.jag:644) ~[?:?]
	at org.jaggeryjs.rhino.admin.jagg.c0.call(/admin/jagg/jagg.jag) ~[?:?]
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.jaggeryjs.rhino.admin.site.themes.wso_2.templates.layout.base.c0._c_anonymous_1(/admin/site/themes/wso2/templates/layout/base/template.jag:30) ~[?:?]
	at org.jaggeryjs.rhino.admin.site.themes.wso_2.templates.layout.base.c0.call(/admin/site/themes/wso2/templates/layout/base/template.jag) ~[?:?]
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.jaggeryjs.rhino.admin.jagg.c0._c_anonymous_32(/admin/jagg/jagg.jag:205) ~[?:?]
	at org.jaggeryjs.rhino.admin.jagg.c0.call(/admin/jagg/jagg.jag) ~[?:?]
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.jaggeryjs.rhino.admin.jagg.c0._c_anonymous_57(/admin/jagg/jagg.jag:641) ~[?:?]
	at org.jaggeryjs.rhino.admin.jagg.c0.call(/admin/jagg/jagg.jag) ~[?:?]
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.jaggeryjs.rhino.admin.site.themes.wso_2.templates.page.base.c0._c_anonymous_1(/admin/site/themes/wso2/templates/page/base/template.jag:119) ~[?:?]
	at org.jaggeryjs.rhino.admin.site.themes.wso_2.templates.page.base.c0.call(/admin/site/themes/wso2/templates/page/base/template.jag) ~[?:?]
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.jaggeryjs.rhino.admin.jagg.c0._c_anonymous_55(/admin/jagg/jagg.jag:624) ~[?:?]
	at org.jaggeryjs.rhino.admin.jagg.c0.call(/admin/jagg/jagg.jag) ~[?:?]
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.jaggeryjs.rhino.admin.site.pages.c4._c_anonymous_1(/admin/site/pages/bot-detected-data-list.jag:20) ~[?:?]
	at org.jaggeryjs.rhino.admin.site.pages.c4.call(/admin/site/pages/bot-detected-data-list.jag) ~[?:?]
	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.jaggeryjs.rhino.admin.site.pages.c4._c_script_0(/admin/site/pages/bot-detected-data-list.jag:9) ~[?:?]
	at org.jaggeryjs.rhino.admin.site.pages.c4.call(/admin/site/pages/bot-detected-data-list.jag) ~[?:?]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.jaggeryjs.rhino.admin.site.pages.c4.call(/admin/site/pages/bot-detected-data-list.jag) ~[?:?]
	at org.jaggeryjs.rhino.admin.site.pages.c4.exec(/admin/site/pages/bot-detected-data-list.jag) ~[?:?]
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:583) ~[org.jaggeryjs.scriptengine_0.14.11.jar:?]
	... 50 more
[2019-11-08 15:29:35,387] ERROR - [JaggeryServlet] Servlet.service() for servlet [JaggeryServlet] threw exception
java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
	at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:456) ~[tomcat_9.0.22.wso2v1.jar:?]
	at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:120) ~[tomcat-servlet-api_9.0.22.wso2v1.jar:?]
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:595) ~[org.jaggeryjs.jaggery.core_0.14.11.jar:?]
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508) ~[org.jaggeryjs.jaggery.core_0.14.11.jar:?]
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24) ~[org.jaggeryjs.jaggery.core_0.14.11.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[tomcat-servlet-api_9.0.22.wso2v1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-servlet-api_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) [tomcat_9.0.22.wso2v1.jar:?]
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:76) [org.jaggeryjs.jaggery.core_0.14.11.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53) [org.wso2.carbon.ui_4.5.1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.22.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80) [org.wso2.carbon.identity.context.rewrite.valve_1.3.6.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100) [org.wso2.carbon.identity.authz.valve_1.3.6.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74) [org.wso2.carbon.identity.auth.valve_1.3.6.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [tomcat_9.0.22.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:116) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.22.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.22.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
[2019-11-08 15:29:35,391] ERROR - [default] Servlet.service() for servlet [default] in context with path [/admin] threw exception
java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
	at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:456) ~[tomcat_9.0.22.wso2v1.jar:?]
	at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:120) ~[tomcat-servlet-api_9.0.22.wso2v1.jar:?]
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:595) ~[org.jaggeryjs.jaggery.core_0.14.11.jar:?]
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508) ~[org.jaggeryjs.jaggery.core_0.14.11.jar:?]
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24) ~[org.jaggeryjs.jaggery.core_0.14.11.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[tomcat-servlet-api_9.0.22.wso2v1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-servlet-api_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:76) ~[org.jaggeryjs.jaggery.core_0.14.11.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53) ~[org.wso2.carbon.ui_4.5.1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.22.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80) [org.wso2.carbon.identity.context.rewrite.valve_1.3.6.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100) [org.wso2.carbon.identity.authz.valve_1.3.6.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74) [org.wso2.carbon.identity.auth.valve_1.3.6.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [tomcat_9.0.22.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:116) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.22.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.22.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
```

**Comment by tharikaGitHub** [comment]
Fixed with the documentation change in https://github.com/wso2/docs-apim/pull/419
