### ISSUE TITLE
APIM Analytics profile failed to start with error

### ISSUE THREAD

**Issue by chanakaudaya** [wso2/product-apim#6784]
I'm trying to start APIM Analytics 3.0.0 runtime by executing the worker.sh in the bin directory. I have downloaded the binary with WUM. Here is the error I'm getting.

Environment: Mac OS Catalina
JDK : 1.8.0_221

`[2019-11-07 12:51:50,983]  SEVERE {org.wso2.carbon.launcher.Main initAndVerifySysProps} - pax-logging.properties should be available to start the server
Exception in thread "main" java.lang.RuntimeException: pax-logging.properties should be available to start the server
	at org.wso2.carbon.launcher.Main.initAndVerifySysProps(Main.java:172)
	at org.wso2.carbon.launcher.Main.main(Main.java:68)`

**Comment by chanakaudaya** [comment]
This issue happened with the binary downloaded using the WUM tool (vanilla pack).

**Comment by chanakaudaya** [comment]
This issue was identified as a problem in the downloaded binary file. WUM team is fixing the behavior in the next release. Nothing related to API Manager products.
