### ISSUE TITLE
Unable to add endpoint certificate when Postgres is used as backend database

### ISSUE THREAD

**Issue by Tomas-Mrazek** [wso2/product-apim#6795]
APIM: 3.0.0
Backend Database: PostgreSQL 11

Reason:
Init script in `/dbscripts/apimgt/postgresql.sql` contains wrong value in table `AM_CERTIFICATE_METADATA`. 
Current column definition:  `END_POINT VARCHAR(45) NOT NULL`
Should be:  `END_POINT VARCHAR(100) NOT NULL`

There are multiple inconsistencies with varchar length across h2, mysql and postgres scripts.

Stack Trace:
```
TID: [-1234] [api/am/publisher/v1.0] [2019-11-08 07:58:08,496] ERROR {org.wso2.carbon.apimgt.impl.certificatemgt.CertificateManagerImpl} - Error when persisting/ deleting certificate metadata. org.wso2.carbon.apimgt.impl.certificatemgt.exceptions.CertificateManagementException: Error while persisting certificate metadata.
        at org.wso2.carbon.apimgt.impl.dao.CertificateMgtDAO.handleException_aroundBody34(CertificateMgtDAO.java:791)
        at org.wso2.carbon.apimgt.impl.dao.CertificateMgtDAO.handleException(CertificateMgtDAO.java:789)
        at org.wso2.carbon.apimgt.impl.dao.CertificateMgtDAO.addCertificate_aroundBody12(CertificateMgtDAO.java:292)
        at org.wso2.carbon.apimgt.impl.dao.CertificateMgtDAO.addCertificate(CertificateMgtDAO.java:255)
        at org.wso2.carbon.apimgt.impl.certificatemgt.CertificateManagerImpl.addCertificateToParentNode_aroundBody2(CertificateManagerImpl.java:121)
        at org.wso2.carbon.apimgt.impl.certificatemgt.CertificateManagerImpl.addCertificateToParentNode(CertificateManagerImpl.java:118)
        at org.wso2.carbon.apimgt.impl.APIProviderImpl.addCertificate_aroundBody318(APIProviderImpl.java:6138)
        at org.wso2.carbon.apimgt.impl.APIProviderImpl.addCertificate(APIProviderImpl.java:6128)
        at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addCertificate_aroundBody126(UserAwareAPIProvider.java:524)
        at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addCertificate(UserAwareAPIProvider.java:522)
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.EndpointCertificatesApiServiceImpl.endpointCertificatesPost(EndpointCertificatesApiServiceImpl.java:281)
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.EndpointCertificatesApi.endpointCertificatesPost(EndpointCertificatesApi.java:146)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
        at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100)
        at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
        at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:116)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(45)
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
        at sun.reflect.GeneratedMethodAccessor122.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
        at com.sun.proxy.$Proxy48.executeUpdate(Unknown Source)
        at org.wso2.carbon.apimgt.impl.dao.CertificateMgtDAO.addCertificate_aroundBody12(CertificateMgtDAO.java:285)
        ... 61 more
```

**Comment by dushaniw** [comment]
Fixed this for next release 3.1.0. @Tomas-Mrazek You would need to increase the column size of the endpoint column in 30 script. Because from 3.0 onwards, we store the entire endpoint url in the endpoint table.
