### ISSUE TITLE
Schema Validation feature of APIM 3.0.0 is not working properly with a valid Json 

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/product-apim#6852]
When invoking a post resource with the below valid json it will throw the below errors.
1. **Payload 1**
```
{
  "bank_account_holder_name": "abcd",
  "name": "abcd",
  "payment_types": ["regular"],
  "beneficiary_address": [
    "1 small house"
  ],
  "beneficiary_country": "US"
}
```
**Error**:
```
 ERROR - ServerWorker Error processing POST request for : /testtwo/v1/testPost. 
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.extractReference_aroundBody26(SchemaValidator.java:532) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.extractReference(SchemaValidator.java:530) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.extractSchemaFromRequest_aroundBody18(SchemaValidator.java:317) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.extractSchemaFromRequest(SchemaValidator.java:287) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.getSchemaContent_aroundBody16(SchemaValidator.java:274) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.getSchemaContent(SchemaValidator.java:271) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.validateRequest_aroundBody8(SchemaValidator.java:202) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.validateRequest(SchemaValidator.java:200) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.handleRequest_aroundBody2(SchemaValidator.java:105) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.handleRequest(SchemaValidator.java:75) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.apache.synapse.rest.API.process(API.java:366) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:325) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367) [synapse-nhttp-transport_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:412) [synapse-nhttp-transport_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181) [synapse-nhttp-transport_2.1.7.wso2v131.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v38.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```
```
{"Fault":{"faultcode":"soapenv:Server","faultstring":1,"detail":null}}
```
2. **Payload 2**
```
{
  "bank_account_holder_name": "abc",
  "name": "abc",
  "payment_types": ["regular"],
  "beneficiary_address": [
    "1 small house"
  ],
  "beneficiary_country": "US",
  "beneficiary_entity_type": "individual",
  "beneficiary_first_name": "abc",
  "beneficiary_last_name": "dd",
  "beneficiary_city": "LA",
  "beneficiary_postcode": "LA1",
  "beneficiary_state_or_province": "California",
  "bank_country": "US",
  "currency": "USD",
  "account_number": "34567",
  "routing_code_type_1": "aba",
  "routing_code_value_1": "12456780"
}
```
**Error**:
```
ERROR - ServerWorker Error processing POST request for : /test/0.0.1/. 
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433) ~[json_3.0.0.wso2v1.jar:?]
	at org.json.JSONObject.<init>(JSONObject.java:194) ~[json_3.0.0.wso2v1.jar:?]
	at org.json.JSONObject.<init>(JSONObject.java:321) ~[json_3.0.0.wso2v1.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.validateContent_aroundBody6(SchemaValidator.java:168) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.validateContent(SchemaValidator.java:163) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.validateRequest_aroundBody8(SchemaValidator.java:207) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.validateRequest(SchemaValidator.java:200) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.handleRequest_aroundBody2(SchemaValidator.java:105) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.handleRequest(SchemaValidator.java:75) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.apache.synapse.rest.API.process(API.java:366) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:325) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367) [synapse-nhttp-transport_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:412) [synapse-nhttp-transport_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181) [synapse-nhttp-transport_2.1.7.wso2v131.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v38.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```
```
{"Fault":{"faultcode":"soapenv:Server","faultstring":"A JSONObject text must begin with '{' at 1 [character 2 line 1]","detail":null}}
```
The above two payloads are valid json but when invoking the resources it will throw the above errors.

**Reproducing Steps**:

1. Created and API with Post resource
2. Passed a body parameter with application/json type
3. Published the API and enable the Schema Validation feature
4. Invoked the post resource by passing above type json payloads

**Comment by hasuniea** [comment]
PR[1]
[1] https://github.com/wso2/carbon-apimgt/pull/7912

**Comment by tmkasun** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7912 hence closing this issue
