### ISSUE TITLE
[Developer Portal] Error: Invoking GraphQL API with API Console

### ISSUE THREAD

**Issue by knightbeat** [wso2/product-apim#7073]
The relevant **cURL** command generated by the Developer Portal is,
`curl -X POST "https://localhost:8243/country/1.0.0/" -H  "accept: */*" -H  "Content-Type: application/json" -H  "Authorization: Bearer eyJ ... FgQ" -d "{  countries   {    code     name  }}"`

The same API works with POSTMAN as it modifies the request payload 
from `{  countries   {    code     name  }}` 
to `{"query":"{countries {code name}}"}` —a JSON object.

**Error**
```
[2019-12-03 14:31:35,341] ERROR - OMSourcedElementImpl Could not get parser from data source for element jsonObject
javax.xml.stream.XMLStreamException: java.io.IOException: Illegal character: <c>
	at org.apache.synapse.commons.staxon.core.base.AbstractXMLStreamReader.initialize(AbstractXMLStreamReader.java:245) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.JsonXMLStreamReader.<init>(JsonXMLStreamReader.java:88) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.JsonXMLInputFactory.createXMLStreamReader(JsonXMLInputFactory.java:170) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.json.JsonUtil.getReader(JsonUtil.java:353) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.json.JsonDataSource.getReader(JsonDataSource.java:154) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.getDirectReader(OMSourcedElementImpl.java:224) [axiom_1.2.11.wso2v16.jar:?]
	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.forceExpand(OMSourcedElementImpl.java:253) [axiom_1.2.11.wso2v16.jar:?]
	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.getFirstElement(OMSourcedElementImpl.java:481) [axiom_1.2.11.wso2v16.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.graphQL.GraphQLAPIHandler.handleRequest_aroundBody4(GraphQLAPIHandler.java:112) [org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.graphQL.GraphQLAPIHandler.handleRequest(GraphQLAPIHandler.java:96) [org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.apache.synapse.rest.API.process(API.java:366) [synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149) [synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95) [synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71) [synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:325) [synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98) [synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) [axis2_1.6.1.wso2v38.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367) [synapse-nhttp-transport_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:412) [synapse-nhttp-transport_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181) [synapse-nhttp-transport_2.1.7.wso2v131.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v38.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.io.IOException: Illegal character: <c>
	at org.apache.synapse.commons.staxon.core.json.stream.impl.JsonScanner.yylex(JsonScanner.java:777) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.stream.impl.JsonScanner.nextSymbol(JsonScanner.java:310) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.stream.impl.JsonStreamSourceImpl.next(JsonStreamSourceImpl.java:136) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.stream.impl.JsonStreamSourceImpl.peek(JsonStreamSourceImpl.java:272) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.JsonXMLStreamReader.consume(JsonXMLStreamReader.java:151) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.JsonXMLStreamReader.consume(JsonXMLStreamReader.java:184) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.JsonXMLStreamReader.consume(JsonXMLStreamReader.java:154) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.JsonXMLStreamReader.consume(JsonXMLStreamReader.java:184) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.base.AbstractXMLStreamReader.initialize(AbstractXMLStreamReader.java:243) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	... 23 more
[2019-12-03 14:31:35,344] ERROR - ServerWorker Error processing POST request for : /country/1.0.0/. 
java.lang.RuntimeException: Error obtaining parser from data source:java.io.IOException: Illegal character: <c>
	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.getDirectReader(OMSourcedElementImpl.java:230) ~[axiom_1.2.11.wso2v16.jar:?]
	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.forceExpand(OMSourcedElementImpl.java:253) ~[axiom_1.2.11.wso2v16.jar:?]
	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.getFirstElement(OMSourcedElementImpl.java:481) ~[axiom_1.2.11.wso2v16.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.graphQL.GraphQLAPIHandler.handleRequest_aroundBody4(GraphQLAPIHandler.java:112) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.graphQL.GraphQLAPIHandler.handleRequest(GraphQLAPIHandler.java:96) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.apache.synapse.rest.API.process(API.java:366) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:325) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367) [synapse-nhttp-transport_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:412) [synapse-nhttp-transport_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181) [synapse-nhttp-transport_2.1.7.wso2v131.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v38.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: javax.xml.stream.XMLStreamException: java.io.IOException: Illegal character: <c>
	at org.apache.synapse.commons.staxon.core.base.AbstractXMLStreamReader.initialize(AbstractXMLStreamReader.java:245) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.JsonXMLStreamReader.<init>(JsonXMLStreamReader.java:88) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.JsonXMLInputFactory.createXMLStreamReader(JsonXMLInputFactory.java:170) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.json.JsonUtil.getReader(JsonUtil.java:353) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.json.JsonDataSource.getReader(JsonDataSource.java:154) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.getDirectReader(OMSourcedElementImpl.java:224) ~[axiom_1.2.11.wso2v16.jar:?]
	... 18 more
Caused by: java.io.IOException: Illegal character: <c>
	at org.apache.synapse.commons.staxon.core.json.stream.impl.JsonScanner.yylex(JsonScanner.java:777) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.stream.impl.JsonScanner.nextSymbol(JsonScanner.java:310) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.stream.impl.JsonStreamSourceImpl.next(JsonStreamSourceImpl.java:136) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.stream.impl.JsonStreamSourceImpl.peek(JsonStreamSourceImpl.java:272) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.JsonXMLStreamReader.consume(JsonXMLStreamReader.java:151) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.JsonXMLStreamReader.consume(JsonXMLStreamReader.java:184) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.JsonXMLStreamReader.consume(JsonXMLStreamReader.java:154) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.JsonXMLStreamReader.consume(JsonXMLStreamReader.java:184) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.base.AbstractXMLStreamReader.initialize(AbstractXMLStreamReader.java:243) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.JsonXMLStreamReader.<init>(JsonXMLStreamReader.java:88) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.staxon.core.json.JsonXMLInputFactory.createXMLStreamReader(JsonXMLInputFactory.java:170) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.json.JsonUtil.getReader(JsonUtil.java:353) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.commons.json.JsonDataSource.getReader(JsonDataSource.java:154) ~[synapse-commons_2.1.7.wso2v131.jar:?]
	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.getDirectReader(OMSourcedElementImpl.java:224) ~[axiom_1.2.11.wso2v16.jar:?]
	... 18 more

```

**Comment by knightbeat** [comment]
I am closing this issue as the Tryout/API-Console only provides a resource for a POST request.  Assuming that users must know A standard GraphQL POST request should use the application/json content type, and include a JSON-encoded body which should follow the required format above.
