### ISSUE TITLE
APIM & Identity Server - Error when updating the permission cache for tenant: -1234

### ISSUE THREAD

**Issue by imchivaa** [wso2/product-apim#7118]
API Manager: 3.1.0-M2
Identity Server with Key Manager: 5.9.0
Operating System: Window Server 2012

Hi there,

I've successfully setup API Manager with Identity Server as Key Manager. Everything works from login, generate authentication tokens for applications, syncing users and user roles.

The issue i am facing right now is when i start up either Identity Server or API Manager, this error is thrown in the carbon log:

```
TID: [-1234] [] [2019-12-09 00:23:11,277] ERROR {org.wso2.carbon.core.internal.permission.update.PermissionUpdater} - Error when updating the permission cache for tenant : -1234 java.lang.NullPointerException
	at org.wso2.carbon.core.internal.permission.update.PermissionUpdater.update(PermissionUpdater.java:72)
	at org.wso2.carbon.core.internal.permission.update.PermissionUpdateServiceComponent.activate(PermissionUpdateServiceComponent.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

TID: [-1234] [] [2019-12-09 00:23:13,230]  WARN {org.wso2.carbon.identity.application.mgt.internal.ApplicationManagementServiceComponent} - Templates directory not found at C:\WOS2\APIM\WSO2AM~1.0-M\bin\..\repository\resources\identity\authntemplates
```

I've also setup seperate database. API Manager, Identity Server & Database all running in separate servers. Can i know what i configured wrongly? Let me know if need to attach other configuration files.

Thanks.

**Comment by dushaniw** [comment]
Hi @imchivaa 

There is no compatible version of is-km to use with APIM 3.1 yet. Hence, we only recommend using IS-KM 5.9 with APIM 3.0

**Comment by imchivaa** [comment]
Hi @dushaniw ,

Ah, i see. But the current release version of APIM 3.0.0 is very buggy, I can't even apply mediation without breaking the api. I tested M2 and M3 so far, quite stable with no major issues. 

If i go with this config but not planning to use the tenant feature, will it like break any other part of the project?

**Comment by dushaniw** [comment]
hi @imchivaa 

According to the error, it seems this is related to updating the super tenant permission cache. It could be a configuration issue. Can you attach the deployment.toml, registry.xml and user-mgt.xml? Please remove any sensitive information in the files before doing so.

**Comment by imchivaa** [comment]
This only happens in one of our environment that doesn't use deployment.toml. We reconfigured all environment to utilize deployment.toml and didn't face this issue anymore. Probably because APIM logins doesn't use IS as Key Manager, we have option to configure publisher and devportal logins to use IS as KM when configuring via api-manager.xml instead of deployment.toml

**Comment by prasad4491** [comment]
I am also getting this error after migrating APIM from 2.6.0 to 3.1.0
Attached log files
[audit.log](https://github.com/wso2/product-apim/files/4912872/audit.log)
[wso2-apigw-errors.log](https://github.com/wso2/product-apim/files/4912873/wso2-apigw-errors.log)
[wso2carbon.log](https://github.com/wso2/product-apim/files/4912874/wso2carbon.log)

**Comment by rksk** [comment]
Related https://github.com/wso2/product-is/issues/6754
