### ISSUE TITLE
Getting peer not authenticated issue after migrating from APIM 2.0.0 to 3.0.0 and IS 5.2.0 to IS-KM 5.9.0

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#7174]
In the migrated setup of API Manager from 2.0.0 to 3.0.0 and IS 5.2.0 to IS-KM 5.9.0:

Following error occurs while generating token and viewing the token page if the token is already generated:

```
INFO - HTTPSender Unable to sendViaPost to url[https://localhost:9444/services/APIKeyMgtSubscriberService]
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:450) ~[?:1.8.0_201]
	at org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.verifyHostName(SSLProtocolSocketFactory.java:276) ~[commons-httpclient_3.1.0.wso2v6.jar:?]
	at org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.createSocket(SSLProtocolSocketFactory.java:186) ~[commons-httpclient_3.1.0.wso2v6.jar:?]
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707) ~[commons-httpclient_3.1.0.wso2v6.jar:?]
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361) ~[commons-httpclient_3.1.0.wso2v6.jar:?]
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387) ~[commons-httpclient_3.1.0.wso2v6.jar:?]
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171) ~[commons-httpclient_3.1.0.wso2v6.jar:?]
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) ~[commons-httpclient_3.1.0.wso2v6.jar:?]
	at org.apache.axis2.transport.http.AbstractHTTPSender.executeMethod(AbstractHTTPSender.java:712) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:223) [axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:82) [axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:459) [axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:286) [axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442) [axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:442) [axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228) [axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149) [axis2_1.6.1.wso2v38.jar:?]
	at org.wso2.carbon.apimgt.keymgt.stub.subscriber.APIKeyMgtSubscriberServiceStub.retrieveOAuthApplication(APIKeyMgtSubscriberServiceStub.java:458) [org.wso2.carbon.apimgt.keymgt.stub_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.keymgt.client.SubscriberKeyMgtClient.getOAuthApplication(SubscriberKeyMgtClient.java:92) [org.wso2.carbon.apimgt.keymgt.client_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.getOAuthApplication_aroundBody48(AMDefaultKeyManagerImpl.java:758) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.getOAuthApplication(AMDefaultKeyManagerImpl.java:753) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.retrieveApplication_aroundBody8(AMDefaultKeyManagerImpl.java:269) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.retrieveApplication(AMDefaultKeyManagerImpl.java:261) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getApplicationKey_aroundBody212(AbstractAPIManager.java:3130) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getApplicationKey(AbstractAPIManager.java:3125) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getApplicationKeys_aroundBody210(AbstractAPIManager.java:3093) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getApplicationKeys(AbstractAPIManager.java:3091) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getApplicationByUUID_aroundBody118(AbstractAPIManager.java:1803) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getApplicationByUUID(AbstractAPIManager.java:1800) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApplicationsApiServiceImpl.applicationsApplicationIdGet(ApplicationsApiServiceImpl.java:212) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.ApplicationsApi.applicationsApplicationIdGet(ApplicationsApi.java:139) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216) [cxf-rt-transp
```

```
ERROR - AbstractKeyManager Can not retrieve OAuth application for the given consumer key : dfVF0r05a5iLNqGrD9pO0767EXAa
org.apache.axis2.AxisFault: peer not authenticated
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:227) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:82) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:459) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:286) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:442) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.wso2.carbon.apimgt.keymgt.stub.subscriber.APIKeyMgtSubscriberServiceStub.retrieveOAuthApplication(APIKeyMgtSubscriberServiceStub.java:458) ~[org.wso2.carbon.apimgt.keymgt.stub_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.keymgt.client.SubscriberKeyMgtClient.getOAuthApplication(SubscriberKeyMgtClient.java:92) ~[org.wso2.carbon.apimgt.keymgt.client_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.getOAuthApplication_aroundBody48(AMDefaultKeyManagerImpl.java:758) ~[org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.getOAuthApplication(AMDefaultKeyManagerImpl.java:753) ~[org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.retrieveApplication_aroundBody8(AMDefaultKeyManagerImpl.java:269) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.retrieveApplication(AMDefaultKeyManagerImpl.java:261) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getApplicationKey_aroundBody212(AbstractAPIManager.java:3130) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getApplicationKey(AbstractAPIManager.java:3125) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getApplicationKeys_aroundBody210(AbstractAPIManager.java:3093) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getApplicationKeys(AbstractAPIManager.java:3091) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getApplicationByUUID_aroundBody118(AbstractAPIManager.java:1803) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getApplicationByUUID(AbstractAPIManager.java:1800) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApplicationsApiServiceImpl.applicationsApplicationIdGet(ApplicationsApiServiceImpl.java:212) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.ApplicationsApi.applicationsApplicationIdGet(ApplicationsApi.java:139) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103) [cxf-rt-frontend-jaxrs-3.2.8.jar
```

```
Caused by: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:450) ~[?:1.8.0_201]
	at org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.verifyHostName(SSLProtocolSocketFactory.java:276) ~[commons-httpclient_3.1.0.wso2v6.jar:?]
	at org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.createSocket(SSLProtocolSocketFactory.java:186) ~[commons-httpclient_3.1.0.wso2v6.jar:?]
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707) ~[commons-httpclient_3.1.0.wso2v6.jar:?]
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361) ~[commons-httpclient_3.1.0.wso2v6.jar:?]
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387) ~[commons-httpclient_3.1.0.wso2v6.jar:?]
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171) ~[commons-httpclient_3.1.0.wso2v6.jar:?]
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) ~[commons-httpclient_3.1.0.wso2v6.jar:?]
	at org.apache.axis2.transport.http.AbstractHTTPSender.executeMethod(AbstractHTTPSender.java:712) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:223) ~[axis2_1.6.1.wso2v38.jar:?]
```

There were no errors when doing migration of both API Manager and IS. I added the public certificate of IS into APIM trust store.
Might be due to any missing configuration.

**Comment by manuel-di-iorio** [comment]
Same using 2.6.0
