### ISSUE TITLE
WSO2 3.0.0 Exception occured while loading the Axis configuration

### ISSUE THREAD

**Issue by Savidude** [wso2/product-apim#7185]
Issue created in [Ansible Resources](https://github.com/wso2/ansible-apim/issues/99) by @kalevivek11 

**Description:**

While trying to run key-manager profile getting issue below:

2019-12-19 15:31:11,470] INFO - UserStoreMgtDSComponent Carbon UserStoreMgtDSComponent activated successfully.
[2019-12-19 15:31:12,362] FATAL - CarbonServerManager WSO2 Carbon initialization Failed
org.apache.axis2.AxisFault: Exception occured while loading the Axis configuration from C:\WSO2\Distributed3.0.0\KeyManager/repository/conf/axis2/axis2.xml
at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:194) ~[org.wso2.carbon.core_4.5.1.jar:?]
at org.apache.axis2.context.ConfigurationContextFactory.createConfigurationContext(ConfigurationContextFactory.java:64) ~[axis2_1.6.1.wso2v38.jar:?]
at org.wso2.carbon.core.CarbonConfigurationContextFactory.createNewConfigurationContext(CarbonConfigurationContextFactory.java:65) ~[org.wso2.carbon.core_4.5.1.jar:?]
at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:415) [org.wso2.carbon.core_4.5.1.jar:?]
at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) [org.wso2.carbon.core_4.5.1.jar:?]
at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) [org.wso2.carbon.core_4.5.1.jar:?]
at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
Caused by: org.apache.axis2.deployment.DeploymentException: org.apache.synapse.transport.passthru.PassThroughHttpSender cannot be found by axis2_1.6.1.wso2v38
at org.apache.axis2.deployment.AxisConfigBuilder.processTransportSenders(AxisConfigBuilder.java:713) ~[axis2_1.6.1.wso2v38.jar:?]
at org.apache.axis2.deployment.AxisConfigBuilder.populateConfig(AxisConfigBuilder.java:125) ~[axis2_1.6.1.wso2v38.jar:?]
at org.wso2.carbon.core.CarbonAxisConfigurator.populateAxisConfiguration(CarbonAxisConfigurator.java:341) ~[org.wso2.carbon.core_4.5.1.jar:?]
at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:192) ~[org.wso2.carbon.core_4.5.1.jar:?]

**Comment by dushaniw** [comment]
Tagging https://github.com/wso2/product-apim/issues/7229
