### ISSUE TITLE
Getting an Error for traffic Manager profiling-WSO2 3.0.0

### ISSUE THREAD

**Issue by arun-1983** [wso2/product-apim#7195]
We are getting when starting profiling with latest version of WSO2 APIM 3.0.0.
steps to re produce issue.

1.profileSetup.bat -Dprofile=traffic-manager
2.wso2server.bat -Dprofile=traffic-manager

after running we got an error as Axis2.TM.xml is not available in conf folder ,but we manually added the file but we got below error. when running wso2server.bat -Dprofile=traffic-manager

2019-12-24 19:34:25,925]  INFO - UserStoreMgtDSComponent Carbon UserStoreMgtDSComponent activated successfully.
[2019-12-24 19:34:28,050] FATAL - CarbonServerManager WSO2 Carbon initialization Failed
org.apache.axis2.AxisFault: Exception occured while loading the Axis configuration from C:\Users\arunkumar.patil01\Downloads\wso2am-3.0.0\wso2am-3.0.0\bin\../repository/conf/axis2/axis2.xml
        at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:194) ~[org.wso2.carbon.core_4.5.1.jar:?]
        at org.apache.axis2.context.ConfigurationContextFactory.createConfigurationContext(ConfigurationContextFactory.java:64) ~[axis2_1.6.1.wso2v38.jar:?]
        at org.wso2.carbon.core.CarbonConfigurationContextFactory.createNewConfigurationContext(CarbonConfigurationContextFactory.java:65) ~[org.wso2.carbon.core_4.5.1.jar:?]
        at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:415) [org.wso2.carbon.core_4.5.1.jar:?]
        at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) [org.wso2.carbon.core_4.5.1.jar:?]
        at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) [org.wso2.carbon.core_4.5.1.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
Caused by: org.apache.axis2.deployment.DeploymentException: org.apache.synapse.transport.passthru.PassThroughHttpMultiSSLListener cannot be found by axis2_1.6.1.wso2v38
        at org.apache.axis2.deployment.AxisConfigBuilder.processTransportReceivers(AxisConfigBuilder.java:640) ~[axis2_1.6.1.wso2v38.jar:?]
        at org.apache.axis2.deployment.AxisConfigBuilder.populateConfig(AxisConfigBuilder.java:131) ~[axis2_1.6.1.wso2v38.jar:?]
        at org.wso2.carbon.core.CarbonAxisConfigurator.populateAxisConfiguration(CarbonAxisConfigurator.java:341) ~[org.wso2.carbon.core_4.5.1.jar:?]
        at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:192) ~[org.wso2.carbon.core_4.5.1.jar:?]
        ... 8 more
Caused by: java.lang.ClassNotFoundException: org.apache.synapse.transport.passthru.PassThroughHttpMultiSSLListener cannot be found by axis2_1.6.1.wso2v38
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191-1-redhat]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191-1-redhat]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_191-1-redhat]
        at org.apache.axis2.util.Loader.loadClass(Loader.java:261) ~[axis2_1.6.1.wso2v38.jar:?]
        at org.apache.axis2.deployment.AxisConfigBuilder.processTransportReceivers(AxisConfigBuilder.java:626) ~[axis2_1.6.1.wso2v38.jar:?]
        at org.apache.axis2.deployment.AxisConfigBuilder.populateConfig(AxisConfigBuilder.java:131) ~[axis2_1.6.1.wso2v38.jar:?]
        at org.wso2.carbon.core.CarbonAxisConfigurator.populateAxisConfiguration(CarbonAxisConfigurator.java:341) ~[org.wso2.carbon.core_4.5.1.jar:?]
        at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:192) ~[org.wso2.carbon.core_4.5.1.jar:?]
        ... 8 more

**Comment by kavishkafernando** [comment]
Hi @arun-1983 

Please attach the deployment.toml file to investigate this further.

**Comment by arun-1983** [comment]
Hi,

Please find below deployment.toml.
The issue seems to be with profileSetup.bat file .it delete the axis2_TM.xml file and do not replace it with axis2.xml file.
We use the profileSetup.sh file and it works fine. 
[server]
hostname = "localhost"
node_ip = "127.0.0.1"
server_role = "traffic-manager"
offset=4

[user_store]
type = "database"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://localhost:3306/shared_db?autoReconnect=true"
username = "root"
password = "1111"
driver = "com.mysql.cj.jdbc.Driver"



[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

**Comment by Krishanx92** [comment]
tagging: https://github.com/wso2/product-apim/issues/7229
