### ISSUE TITLE
Issue while running Analytics dashboard in wso2 3.0.0

### ISSUE THREAD

**Issue by kalevivek11** [wso2/product-apim#7232]
I am following link
https://apim.docs.wso2.com/en/latest/Learn/Analytics/configuring-apim-analytics/#quick-setup

database: Mysql

steps to reproduce:

keep analytics and apim(ALL-IN-ONE) in same directory
change the database connections
start worker profile
start apim
start dashboard

Issue:

 ERROR {org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager} - Runtime Exception occurred while calling onAllRequiredCapabilitiesAvailable of component carbon-datasource-service java.lang.IllegalArgumentException: Can not set java.lang.String field com.zaxxer.hikari.HikariConfig.password to java.lang.Integer
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
        at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
        at java.lang.reflect.Field.set(Field.java:764)
        at org.wso2.carbon.datasource.rdbms.hikari.utils.HikariDataSourceUtils.buildConfiguration(HikariDataSourceUtils.java:93)
        at org.wso2.carbon.datasource.rdbms.hikari.HikariDataSourceReader.createDataSource(HikariDataSourceReader.java:70)
        at org.wso2.carbon.datasource.core.DataSourceBuilder.buildDataSourceObject(DataSourceBuilder.java:79)
        at org.wso2.carbon.datasource.core.DataSourceBuilder.buildDataSourceObject(DataSourceBuilder.java:60)
        at org.wso2.carbon.datasource.core.DataSourceBuilder.buildCarbonDataSource(DataSourceBuilder.java:44)
        at org.wso2.carbon.datasource.core.DataSourceManager.initDataSources(DataSourceManager.java:153)
        at org.wso2.carbon.datasource.core.internal.DataSourceListenerComponent.onAllRequiredCapabilitiesAvailable(DataSourceListenerComponent.java:125)
        at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$7(StartupComponentManager.java:266)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:252)
        at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

**Comment by RAVEENSR** [comment]
According to this error, it looks like you have entered either **username** or **password** for a data source defined under **wso2.datasources** was not included inside apostrophes. Please include those inside apostrophes and try and let us know whether this fixed your issue.

Example:
- name: APIM_ANALYTICS_DB
       description: "The datasource used for APIM statistics aggregated data."
       jndiConfig:
         name: jdbc/APIM_ANALYTICS_DB
       definition:
         type: RDBMS
         configuration:
           jdbcUrl: 'jdbc:mysql://localhost:3306/stats_db'
           **username: 'root'
           password: '123'**
           driverClassName: com.mysql.jdbc.Driver
           maxPoolSize: 50
           idleTimeout: 60000
        connectionTestQuery: SELECT 1
        validationTimeout: 30000
        isAutoCommit: false

**Comment by Krishanx92** [comment]
@kalevivek11 Is this resolve now?

**Comment by kalevivek11** [comment]
@Krishanx92 yes
