### ISSUE TITLE
Help with WSO2 APIM and Analytics setup

### ISSUE THREAD

**Issue by sbk2020** [wso2/product-apim#7294]
### Description:
Hello, I am trying to learn WSO2 using their self-paced learning online.  But the documentation could use improvement for a newbie like me.  Following the instructions, I downloaded and installed WSO2 Analytics (which happens to be the Stream Processor and it is not mentioned anywhere only to figure out on our own).  When trying to now start the WSO2 APIM, I get the below error.  I believe this is due to the templatized properties in various files where we have properties like the below.  And the documentation isn't clear as to where we should configure these properties and what the values of these fields should be.  Can you please help?  See the errors I am getting below on WSO2 APIM.

Fields to be configured somewhere:
- ${carbon.protocol}
- ${carbon.host}
- ${carbon.management.port}
- There could be many others.

Properties from WSO2\API Manager\3.0.0\repository\conf\identity\**EndpointConfig.properties**
tenantListEnabled=false
mutualSSLManagerEnabled=true
hostname.verification.enabled=true
mutual.ssl.username=admin
client.keyStore=./repository/resources/security/wso2carbon.jks
Carbon.Security.KeyStore.Password=wso2carbon
client.trustStore=./repository/resources/security/client-truststore.jks
Carbon.Security.TrustStore.Password=wso2carbon
username.header=UserName
key.manager.type=JKS
trust.manager.type=JKS
tls.protocol=TLSv1.2
app.name=dashboard
app.password=dashboard
identity.server.origin=**$**{carbon.protocol}://${carbon.host}:${carbon.management.port}

I believe the console throws the error at the $ sign in the identity.server.origin property declaration above.  I could be wrong.  But it is 

I see carbon.xml and carbon.properties files.  This is probably where we configure but unsure.

**Errors I am getting on Windows 10 console**:

**First Error**:
[2020-01-20 18:32:15,082]  INFO - WebsocketEndpointManager Netty Listener starting on port 9099
[2020-01-20 18:32:15,083]  INFO - InboundEndpoint Initializing Inbound Endpoint: SecureWebSocketEP
[2020-01-20 18:32:15,127]  INFO - WebsocketEndpointManager Netty SSL Listener starting on port 8099
[2020-01-20 18:32:15,130]  INFO - API Initializing API: _WSO2AMAuthorizeAPI_
[2020-01-20 18:32:15,131]  INFO - API Initializing API: _WSO2AMUserInfoAPI_
[2020-01-20 18:32:15,137]  INFO - API Initializing API: _OpenService_
[2020-01-20 18:32:15,138]  INFO - API Initializing API: _WSO2AMRevokeAPI_
[2020-01-20 18:32:15,140]  INFO - API Initializing API: _WSO2AMTokenAPI_
[2020-01-20 18:32:15,142]  INFO - ServerManager Server ready for processing...
Exception in thread "Timer-8" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
        at com.google.gson.Gson.fromJson(Gson.java:939)
        at com.google.gson.Gson.fromJson(Gson.java:892)
Exception in thread "Timer-6"   at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at org.wso2.carbon.apimgt.gateway.jwt.RevokedJWTTokensRetriever.retrieveRevokedJWTTokensData_aroundBody2(RevokedJWTTokensRetriever.java:100)
        at org.wso2.carbon.apimgt.gateway.jwt.RevokedJWTTokensRetriever.retrieveRevokedJWTTokensData(RevokedJWTTokensRetriever.java:61)
        at org.wso2.carbon.apimgt.gateway.jwt.RevokedJWTTokensRetriever.loadRevokedJWTTokensFromWebService_aroundBody4(RevokedJWTTokensRetriever.java:110)
        at org.wso2.carbon.apimgt.gateway.jwt.RevokedJWTTokensRetriever.loadRevokedJWTTokensFromWebService(RevokedJWTTokensRetriever.java:108)
        at org.wso2.carbon.apimgt.gateway.jwt.RevokedJWTTokensRetriever.run_aroundBody0(RevokedJWTTokensRetriever.java:53)[2020-01-20 18:32:15,504] ERROR - KeyTemplateRetriever Exception when retrieving throttling data from remote endpoint
org.json.simple.parser.ParseException: null
        at org.json.simple.parser.Yylex.yylex(Unknown Source) ~[json-simple_1.1.0.wso2v1.jar:?]
        at org.json.simple.parser.JSONParser.nextToken(Unknown Source) ~[json-simple_1.1.0.wso2v1.jar:?]
        at org.json.simple.parser.JSONParser.parse(Unknown Source) ~[json-simple_1.1.0.wso2v1.jar:?]
        at org.json.simple.parser.JSONParser.parse(Unknown Source) ~[json-simple_1.1.0.wso2v1.jar:?]
        at org.json.simple.parser.JSONParser.parse(Unknown Source) ~[json-simple_1.1.0.wso2v1.jar:?]
        at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.retrieveKeyTemplateData_aroundBody2(KeyTemplateRetriever.java:101) [org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
        at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.retrieveKeyTemplateData(KeyTemplateRetriever.java:64) [org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
        at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService_aroundBody6(KeyTemplateRetriever.java:117) [org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
        at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService(KeyTemplateRetriever.java:116) [org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
        at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run_aroundBody0(KeyTemplateRetriever.java:55) [org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
        at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run(KeyTemplateRetriever.java:51) [org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_241]
        at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_241]

        at org.wso2.carbon.apimgt.gateway.jwt.RevokedJWTTokensRetriever.run(RevokedJWTTokensRetriever.java:50)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Exception in thread "Timer-7" Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        ... 11 more
java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
        at java.util.Arrays.asList(Arrays.java:3800)
        at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService_aroundBody6(KeyTemplateRetriever.java:117)
        at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService(KeyTemplateRetriever.java:116)
        at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run_aroundBody0(KeyTemplateRetriever.java:55)
        at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run(KeyTemplateRetriever.java:51)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever.retrieveBlockConditionsData_aroundBody2(BlockingConditionRetriever.java:96)
        at org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever.retrieveBlockConditionsData(BlockingConditionRetriever.java:60)
        at org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever.loadBlockingConditionsFromWebService_aroundBody6(BlockingConditionRetriever.java:110)
        at org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever.loadBlockingConditionsFromWebService(BlockingConditionRetriever.java:109)
        at org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever.run_aroundBody0(BlockingConditionRetriever.java:52)
        at org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever.run(BlockingConditionRetriever.java:48)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
**Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $**
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
        ... 12 more
[2020-01-20 18:32:16,009]  INFO - WebsocketEndpointManager Netty Listener already started on port 8099
[2020-01-20 18:32:16,010]  INFO - WebsocketEndpointManager Netty Listener already started on port 9099
[2020-01-20 18:32:16,093]  INFO - QpidServiceComponent Activating Andes Message Broker Engine...

**Second Error**:
[2020-01-20 18:32:18,225]  INFO - JMSListener Started to listen on destination : throttleData of type topic for listener Siddhi-JMS-Consumer#throttleData
[2020-01-20 18:32:18,231]  INFO - PassThroughListeningIOReactorManager Pass-through HTTPS Listener started on 0:0:0:0:0:0:0:0:8243
[2020-01-20 18:32:18,272] **ERROR - LifecycleBase Failed to start component [Connector[HTTP/1.1-9443]]**
org.apache.catalina.LifecycleException: Protocol handler start failed
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:1008) ~[tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat_9.0.22.wso2v1.jar:?]
        at org.wso2.carbon.tomcat.internal.CarbonTomcat.startConnectors(CarbonTomcat.java:434) [org.wso2.carbon.tomcat_4.5.1.jar:?]
        at org.wso2.carbon.tomcat.ext.transport.ServletTransportManager.startTransports(ServletTransportManager.java:78) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_241]
        at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:199) [org.wso2.carbon.core_4.5.1.jar:?]
        at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:323) [org.wso2.carbon.core_4.5.1.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.registerThrottlingAgent(ThrottlingAgentServiceComponent.java:118) [org.wso2.carbon.tenant.throttling.agent_4.7.11.jar:?]
        at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.activate(ThrottlingAgentServiceComponent.java:96) [org.wso2.carbon.tenant.throttling.agent_4.7.11.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_241]
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529) [org.wso2.carbon.core_4.5.1.jar:?]
        at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) [org.wso2.carbon.core_4.5.1.jar:?]
        at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) [org.wso2.carbon.core_4.5.1.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
Caused by: java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_241]
        at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_241]
        at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_241]
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_241]
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_241]
        at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:230) ~[tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:213) ~[tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1124) ~[tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1210) ~[tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:585) ~[tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:1005) ~[tomcat_9.0.22.wso2v1.jar:?]
        ... 48 more
[2020-01-20 18:32:18,403]  INFO - TaskServiceImpl Task service starting in STANDALONE mode...
[2020-01-20 18:32:18,444]  INFO - RegistryEventingServiceComponent Successfully Initialized Eventing on Registry
[2020-01-20 18:32:18,553]  INFO - JMXServerManager JMX Service URL  : service:jmx:rmi://localhost:11111/jndi/rmi://localhost:9999/jmxrmi
[2020-01-20 18:32:18,555]  INFO - StartupFinalizerServiceComponent Server           :  WSO2 API Manager-3.0.0
[2020-01-20 18:32:18,556]  INFO - StartupFinalizerServiceComponent WSO2 Carbon started in 86 sec
[2020-01-20 18:32:19,072]  INFO - CarbonUIServiceComponent Mgt Console URL  : https://localhost:9443/carbon/
[2020-01-20 18:32:19,073]  INFO - CarbonUIServiceComponent API Developer Portal Default Context : https://localhost:9443/devportal
[2020-01-20 18:32:19,074]  INFO - CarbonUIServiceComponent API Publisher Default Context : https://localhost:9443/publisher

I get a blank page on the browser if I try the localhost /carbon, /devportal and /publisher URLs mentioned above. 
Thank you for your help.

### Content Positioning in Documentation:

- Link:

- Heading (& Step):

- Any other reference:

---

**Comment by kalevivek11** [comment]
I am also getting the same error in the production environment, it very urgent for us to get it fixed, but as usual i don't think we can get a prompt reply

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
