### ISSUE TITLE
[APIM 2.1][Tenant] DB Lookup/Report Mediator not working in Tenant

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#7306]
### Description:

The `DB Lookup` & `DB Report` mediators are not working as expected in sub-tenants when using DS configurations. Given below is a sample sequence

> The UM_DB configurations are defined in the APIM/repository/conf/datasources/master-datasources.xml

```xml
<dblookup description="Get Details from UM DB">
    <connection>
        <pool>
            <dsName>jdbc/WSO2UM_DB</dsName>
        </pool>
    </connection>
    ...
</dblookup>
```

The above-sequence is working as expected when using it in the Super (Carbon) tenant mode.

### Steps to reproduce:

* Start a fresh WSO2 APIM 2.1 server
* Create a new tenant using the Carbon management console
* Sign-in to the Publisher portal with the created tenant admin and Publish an API with the following sample sequence
  ```xml
  <?xml version="1.0" encoding="UTF-8"?>

  <sequence name="simple-demo-sequence" xmlns="http://ws.apache.org/ns/synapse">
      <dblookup>
          <connection>
              <pool>
                  <dsName>jdbc/WSO2AM_DB</dsName>
              </pool>
          </connection>
          <statement>
              <sql>select * from AM_API</sql>
              <result name="APIID" column="API_ID" />
          </statement>
      </dblookup>
      <log level="custom">
          <property name="API ID Results" expression="get-property('APIID')" />
      </log>
  </sequence>
  ```
* Navigate to the Tenant Store portal, subscribe, generate access token and invoke the API
* The following error-trace will be printed
  ```log
  [2020-01-22 14:02:54,052] ERROR - com--PizzaShackAPI Error looking up DataSource : jdbc/WSO2AM_DB using JNDI properties : javax.naming.InitialContext@5ddb6b3e
  org.apache.synapse.commons.SynapseCommonsException: Error looking up DataSource : jdbc/WSO2AM_DB using JNDI properties : javax.naming.InitialContext@5ddb6b3e	
      at org.apache.synapse.commons.datasource.DataSourceFinder.find(DataSourceFinder.java:81)	
      at org.apache.synapse.commons.datasource.DataSourceFinder.find(DataSourceFinder.java:54)	
      at org.apache.synapse.mediators.db.AbstractDBMediator.lookupDataSource(AbstractDBMediator.java:496)	
      at org.apache.synapse.mediators.db.AbstractDBMediator.mediate(AbstractDBMediator.java:165)	
      at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)	
      at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)	
      at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)	
      at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.mediate(APIManagerExtensionHandler.java:67)	
      at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleRequest(APIManagerExtensionHandler.java:78)	
      at org.apache.synapse.rest.API.process(API.java:325)	
      at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:90)	
      at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)	
      at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:304)	
      at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:78)	
      at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)	
      at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRESTRequest(MultitenantMessageReceiver.java:621)	
      at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doNhttpREST(MultitenantMessageReceiver.java:560)	
      at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doREST(MultitenantMessageReceiver.java:370)	
      at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRequest(MultitenantMessageReceiver.java:228)	
      at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:78)	
      at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)	
      at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:326)	
      at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)	
      at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)	
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)	
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)	
      at java.lang.Thread.run(Thread.java:748)
  Caused by: javax.naming.NameNotFoundException: Name [jdbc/WSO2AM_DB] is not bound in this Context. Unable to find [jdbc].	
      at org.apache.naming.NamingContext.lookup(NamingContext.java:825)	
      at org.apache.naming.NamingContext.lookup(NamingContext.java:173)	
      at org.wso2.carbon.context.internal.CarbonContextDataHolder$CarbonInitialJNDIContext.lookup(CarbonContextDataHolder.java:709)	
      at javax.naming.InitialContext.lookup(InitialContext.java:417)
      at org.apache.synapse.commons.datasource.DataSourceFinder.find(DataSourceFinder.java:72)
  ```

### Affected Product Version:

* WSO2 APIM 2.1 onwards

**Comment by athiththan11** [comment]
By implementation, it is not achievable to access the datasources defined in the `master-datasources.xml` in sub-tenants.

If it is required, then it is possible to define the Datasource configuration via Carbon management console and able to use it through the sequence.
