### ISSUE TITLE
Running the devportal profile fails with axis2.xml exception

### ISSUE THREAD

**Issue by domgoodwin** [wso2/product-apim#7314]
### Description:
When running, via the docker container (wso2/wso2am:3.0.0) with `-Dprofile=api-devportal` set it fails with axis2.xml exception
### Steps to reproduce:

Server started with:
`/home/wso2carbon/wso2am-3.0.0/bin/wso2server.sh -Dprofile=api-devportal`

Publisher, trafficmanager, keymgr, mysql, analytics worker already up with profiles

**Config:**
```
# Deployment config for identity server deployment
[server]
hostname = "$env{HOST_NAME}"
node_ip = "$env{NODE_IP}"
server_role="api-devportal"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database"

[database.apim_db]
type = "mysql"
url = "jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_SHARED_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

[[apim.gateway.environment]]
name = "Production and Sandbox"
type = "hybrid"
display_in_api_console = true
description = "This is a hybrid gateway that handles both production and sandbox token traffic."
service_url = "https://localhost:${mgt.transport.https.port}/services/"
username= "${admin.username}"
password= "${admin.password}"

[apim.key_manager]
service_url = "https://wso2am-keymgr-service:${mgt.transport.https.port}/services/"
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"

[apim.analytics]
store_api_url = "https://wso2am-analytics-worker-service:7444"
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"

[[apim.analytics.analytics_node]]
analytics_url="tcp://wso2am-analytics-worker-service:7612"
analytics_auth_url="ssl://wso2am-analytics-worker-service:7712"

[apim.oauth_config]
revoke_endpoint = "https://wso2am-gateway-service:${https.nio.port}/revoke"
```

Error message:
```
+ sh /home/wso2carbon/wso2am-3.0.0/bin/wso2server.sh -Dprofile=api-devportal
JAVA_HOME environment variable is set to /opt/java/openjdk
CARBON_HOME environment variable is set to /home/wso2carbon/wso2am-3.0.0
Using Java memory options: -Xms256m -Xmx1024m
[2020-01-23 16:46:49,288]  INFO {org.wso2.config.mapper.ConfigParser} - Applying Configurations upon new Templates
[2020-01-23 16:46:49,291]  WARN {org.wso2.config.mapper.ConfigParser} - Overriding files in configuration directory /home/wso2carbon/wso2am-3.0.0
[2020-01-23 16:46:50,325]  INFO {org.wso2.config.mapper.ConfigParser} - Writing Metadata Entries...
[2020-01-23 16:47:01,138]  INFO - CarbonCoreActivator Starting WSO2 Carbon...
[2020-01-23 16:47:01,154]  INFO - CarbonCoreActivator Operating System : Linux 3.10.0-1062.9.1.el7.x86_64, amd64
[2020-01-23 16:47:01,154]  INFO - CarbonCoreActivator Java Home        : /opt/java/openjdk/jre
[2020-01-23 16:47:01,155]  INFO - CarbonCoreActivator Java Version     : 1.8.0_222
[2020-01-23 16:47:01,155]  INFO - CarbonCoreActivator Java VM          : OpenJDK 64-Bit Server VM 25.222-b10,AdoptOpenJDK
[2020-01-23 16:47:01,155]  INFO - CarbonCoreActivator Carbon Home      : /home/wso2carbon/wso2am-3.0.0
[2020-01-23 16:47:01,155]  INFO - CarbonCoreActivator Java Temp Dir    : /home/wso2carbon/wso2am-3.0.0/tmp
[2020-01-23 16:47:01,156]  INFO - CarbonCoreActivator User             : wso2carbon, en-US, GMT
[2020-01-23 16:47:01,417]  INFO - DefaultCryptoProviderComponent 'CryptoService.Secret' property has not been set. 'org.wso2.carbon.crypto.provider.SymmetricKeyInternalCryptoProvider' won't be registered as an internal crypto provider. Please set the secret if the provider needs to be registered.
[2020-01-23 16:47:01,836]  INFO - KafkaEventAdapterServiceDS Successfully deployed the Kafka output event adaptor service
[2020-01-23 16:47:06,288]  INFO - ConsentManagerComponent ConsentManagerComponent is activated.
[2020-01-23 16:47:07,321]  INFO - EmbeddedRegistryService Configured Registry in 240ms
[2020-01-23 16:47:07,460]  INFO - EmbeddedRegistryService Connected to mount at configregistry in 13ms
[2020-01-23 16:47:07,461]  INFO - EmbeddedRegistryService Connected to mount at govregistry in 14ms
[2020-01-23 16:47:07,794]  INFO - EmbeddedRegistryService Connected to mount at configregistry in 7ms
[2020-01-23 16:47:07,795]  INFO - EmbeddedRegistryService Connected to mount at govregistry in 8ms
[2020-01-23 16:47:08,101]  INFO - RegistryCoreServiceComponent Registry Mode    : READ-WRITE
[2020-01-23 16:47:08,240]  INFO - JmxReporterBuilder Creating JMX reporter for Metrics with domain 'org.wso2.carbon.metrics'
[2020-01-23 16:47:08,245]  INFO - AbstractReporter Started JMX reporter for Metrics
[2020-01-23 16:47:11,250]  INFO - SolrClient Default Embedded Solr Server Initialized
[2020-01-23 16:47:12,088]  INFO - UserStoreMgtDSComponent Carbon UserStoreMgtDSComponent activated successfully.
[2020-01-23 16:47:12,833] FATAL - CarbonServerManager WSO2 Carbon initialization Failed
org.apache.axis2.AxisFault: Exception occured while loading the Axis configuration from /home/wso2carbon/wso2am-3.0.0/repository/conf/axis2/axis2.xml
	at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:194) ~[org.wso2.carbon.core_4.5.1.jar:?]
	at org.apache.axis2.context.ConfigurationContextFactory.createConfigurationContext(ConfigurationContextFactory.java:64) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.wso2.carbon.core.CarbonConfigurationContextFactory.createNewConfigurationContext(CarbonConfigurationContextFactory.java:65) ~[org.wso2.carbon.core_4.5.1.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:415) [org.wso2.carbon.core_4.5.1.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) [org.wso2.carbon.core_4.5.1.jar:?]
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) [org.wso2.carbon.core_4.5.1.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
Caused by: org.apache.axis2.deployment.DeploymentException: org.wso2.carbon.websocket.transport.WebsocketTransportSender cannot be found by axis2_1.6.1.wso2v38
	at org.apache.axis2.deployment.AxisConfigBuilder.processTransportSenders(AxisConfigBuilder.java:713) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.deployment.AxisConfigBuilder.populateConfig(AxisConfigBuilder.java:125) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.wso2.carbon.core.CarbonAxisConfigurator.populateAxisConfiguration(CarbonAxisConfigurator.java:341) ~[org.wso2.carbon.core_4.5.1.jar:?]
	at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:192) ~[org.wso2.carbon.core_4.5.1.jar:?]
	... 8 more
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.websocket.transport.WebsocketTransportSender cannot be found by axis2_1.6.1.wso2v38
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_222]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_222]
	at org.apache.axis2.util.Loader.loadClass(Loader.java:261) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.deployment.AxisConfigBuilder.processTransportSenders(AxisConfigBuilder.java:687) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.axis2.deployment.AxisConfigBuilder.populateConfig(AxisConfigBuilder.java:125) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.wso2.carbon.core.CarbonAxisConfigurator.populateAxisConfiguration(CarbonAxisConfigurator.java:341) ~[org.wso2.carbon.core_4.5.1.jar:?]
	at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:192) ~[org.wso2.carbon.core_4.5.1.jar:?]
	... 8 more
```

### Affected Product Version:
3.0.0

### Environment details (with versions):
- OS: Centos
- Env: Docker on Kubernetes

**Comment by CrowleyRajapakse** [comment]
Hi @domgoodwin , as a workaround you can change config to **server_role="api-store"** in deployment.toml **after** running the profile optimization script.

This is a previously reported issue https://github.com/wso2/product-apim/issues/6797, it's fixed in the latest version.

**Comment by domgoodwin** [comment]
Thanks for the quick reply, that fixed my issue.
