### ISSUE TITLE
3.x - Admin SSO fails

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#7315]
### Description:
Cannot login to the admin portal using SAML SSO with IS 5.10.0-Alpha2.

Below errors can be seen in the terminal 
```
TID: [-1234] [admin] [2020-01-22 01:08:40,735] ERROR {org.jaggeryjs.jaggery.core.manager.WebAppManager} - org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.hostobjects.sso.exception.SSOHostObjectException: Error while signing the SAML Request message (/admin/site/themes/wso2/templates/sso/filter/template.jag#60) (/admin/site/pages/index.jag#3) org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.hostobjects.sso.exception.SSOHostObjectException: Error while signing the SAML Request message (/admin/site/themes/wso2/templates/sso/filter/template.jag#60) (/admin/site/pages/index.jag#3)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:587)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:289)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:589)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.hostobjects.sso.exception.SSOHostObjectException: Error while signing the SAML Request message (/admin/site/themes/wso2/templates/sso/filter/template.jag#60) (/admin/site/pages/index.jag#3)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.admin.site.pages.c0._c_script_0(/admin/site/pages/index.jag:3)
	at org.jaggeryjs.rhino.admin.site.pages.c0.call(/admin/site/pages/index.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.admin.site.pages.c0.call(/admin/site/pages/index.jag)
	at org.jaggeryjs.rhino.admin.site.pages.c0.exec(/admin/site/pages/index.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:583)
	... 47 more
Caused by: org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.hostobjects.sso.exception.SSOHostObjectException: Error while signing the SAML Request message (/admin/site/themes/wso2/templates/sso/filter/template.jag#60)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:587)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:289)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.executeScript(WebAppManager.java:309)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.include(WebAppManager.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 56 more
Caused by: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.hostobjects.sso.exception.SSOHostObjectException: Error while signing the SAML Request message (/admin/site/themes/wso2/templates/sso/filter/template.jag#60)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
	at org.jaggeryjs.rhino.admin.site.themes.wso_2.templates.sso.filter.c0._c_anonymous_1(/admin/site/themes/wso2/templates/sso/filter/template.jag:60)
	at org.jaggeryjs.rhino.admin.site.themes.wso_2.templates.sso.filter.c0.call(/admin/site/themes/wso2/templates/sso/filter/template.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.admin.jagg.c0._c_anonymous_32(/admin/jagg/jagg.jag:205)
	at org.jaggeryjs.rhino.admin.jagg.c0.call(/admin/jagg/jagg.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.admin.jagg.c0._c_anonymous_56(/admin/jagg/jagg.jag:628)
	at org.jaggeryjs.rhino.admin.jagg.c0.call(/admin/jagg/jagg.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.admin.site.pages.c1._c_script_0(/admin/site/pages/header.jag:9)
	at org.jaggeryjs.rhino.admin.site.pages.c1.call(/admin/site/pages/header.jag)
	at org.jaggeryjs.rhino.admin.site.pages.c1.exec(/admin/site/pages/header.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:583)
	... 64 more
Caused by: org.wso2.carbon.hostobjects.sso.exception.SSOHostObjectException: Error while signing the SAML Request message
	at org.wso2.carbon.hostobjects.sso.internal.builder.AuthReqBuilder.handleException(AuthReqBuilder.java:170)
	at org.wso2.carbon.hostobjects.sso.internal.builder.AuthReqBuilder.setSignature(AuthReqBuilder.java:161)
	at org.wso2.carbon.hostobjects.sso.internal.builder.AuthReqBuilder.buildSignedAuthRequest(AuthReqBuilder.java:102)
	at org.wso2.carbon.hostobjects.sso.SAMLSSORelyingPartyObject.jsFunction_getSAMLAuthRequest(SAMLSSORelyingPartyObject.java:448)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 79 more
Caused by: org.opensaml.xmlsec.signature.support.SignatureException: Could not load a signer implementation via service API
	at org.opensaml.xmlsec.signature.support.Signer.getSignerProvider(Signer.java:89)
	at org.opensaml.xmlsec.signature.support.Signer.signObjects(Signer.java:57)
	at org.wso2.carbon.hostobjects.sso.internal.builder.AuthReqBuilder.setSignature(AuthReqBuilder.java:154)
	... 86 more
```

If we disable signing attributes in the ssoConfiguration of site.json. I am able to login. 
```
  "ssoConfiguration": {
    "enabled": "true",
    "issuer": "API_ADMIN",
    "identityProviderURL": "https://is.wso2.com:9444/samlsso",
    "keyStorePassword": "wso2carbon",
    "identityAlias": "wso2carbon",
    "keyStoreName": "/home/malintha/wso2apim/cur/samesite/wso2am-3.1.0-SNAPSHOT/repository/resources/security/wso2carbon.jks",
    "verifyAssertionValidityPeriod": "true",
    "audienceRestrictionsEnabled": "true",
    "responseSigningEnabled": "false",
    "assertionSigningEnabled": "false",
    "assertionEncryptionEnabled": "false",
    "signRequests" : "false",
    "idpInit" : "false",
    "idpInitSSOURL" : "https://localhost:9443/samlsso?spEntityID=API_WORKFLOW_ADMIN",
    "externalLogoutPage" : "https://localhost:9444/samlsso?slo=true",
    "loginUserNameAttribute" : ""
  },
```

But still, logout doesn't work and gives a 500.

```
TID: [-1234] [admin] [2020-01-22 12:18:35,194] ERROR {org.jaggeryjs.jaggery.core.manager.WebAppManager} - org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (/admin/site/themes/wso2/templates/sso/logout/template.jag#12) org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (/admin/site/themes/wso2/templates/sso/logout/template.jag#12)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:587)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:289)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:589)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (/admin/site/themes/wso2/templates/sso/logout/template.jag#12)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.admin.site.themes.wso_2.templates.sso.logout.c0._c_anonymous_1(/admin/site/themes/wso2/templates/sso/logout/template.jag:12)
	at org.jaggeryjs.rhino.admin.site.themes.wso_2.templates.sso.logout.c0.call(/admin/site/themes/wso2/templates/sso/logout/template.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.admin.jagg.c0._c_anonymous_32(/admin/jagg/jagg.jag:205)
	at org.jaggeryjs.rhino.admin.jagg.c0.call(/admin/jagg/jagg.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.admin.jagg.c0._c_anonymous_56(/admin/jagg/jagg.jag:628)
	at org.jaggeryjs.rhino.admin.jagg.c0.call(/admin/jagg/jagg.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.admin.site.pages.c3._c_script_0(/admin/site/pages/logout.jag:19)
	at org.jaggeryjs.rhino.admin.site.pages.c3.call(/admin/site/pages/logout.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.admin.site.pages.c3.call(/admin/site/pages/logout.jag)
	at org.jaggeryjs.rhino.admin.site.pages.c3.exec(/admin/site/pages/logout.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:583)
	... 47 more
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.hostobjects.sso.SAMLSSORelyingPartyObject.clearSessionDataFromSessionId(SAMLSSORelyingPartyObject.java:1404)
	at org.wso2.carbon.hostobjects.sso.SAMLSSORelyingPartyObject.handleLogoutBySessionId(SAMLSSORelyingPartyObject.java:1322)
	at org.wso2.carbon.hostobjects.sso.SAMLSSORelyingPartyObject.jsFunction_invalidateSessionBySessionId(SAMLSSORelyingPartyObject.java:848)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 65 more
```

### Affected Product Version:
3.1.0-SNAPSHOT build on 2020-01-22

**Comment by msm1992** [comment]
Fixed in APIM 3.1.0 with https://github.com/wso2/carbon-apimgt/pull/8113 and https://github.com/wso2/carbon-apimgt/pull/8122. Hence resolving the issue.
