### ISSUE TITLE
Cannot add documents when containing special charactors in the filename

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#7323]
### Description:
Upload a document named "update-summary-wso2am-2.6.0+1575989710760.full.pdf" from Publisher UI.

below error can be seen:
```
[2020-01-25 22:12:48,640] ERROR - ApisApiServiceImpl Failed to add content to the document d8ce436b-55d9-43a2-931c-f18568cf7824
org.wso2.carbon.apimgt.api.APIManagementException: Failed to add file to document sasa
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.handleException_aroundBody124(AbstractAPIManager.java:1833) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.handleException(AbstractAPIManager.java:1831) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addFileToDocumentation_aroundBody126(APIProviderImpl.java:2649) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addFileToDocumentation(APIProviderImpl.java:2630) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addFileToDocumentation_aroundBody36(UserAwareAPIProvider.java:201) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addFileToDocumentation(UserAwareAPIProvider.java:198) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.utils.RestApiPublisherUtils.attachFileToDocument(RestApiPublisherUtils.java:220) ~[classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.apisApiIdDocumentsDocumentIdContentPost(ApisApiServiceImpl.java:1656) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.apisApiIdDocumentsDocumentIdContentPost(ApisApi.java:256) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.22.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86) [org.wso2.carbon.identity.context.rewrite.valve_1.3.16.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.3.16.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74) [org.wso2.carbon.identity.auth.valve_1.3.16.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.0.alpha3.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [tomcat_9.0.22.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119) [org.wso2.carbon.tomcat.ext_4.6.0.alpha3.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.22.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.22.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: org.wso2.carbon.apimgt.api.APIManagementException: Error while adding the resource to the registry
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.addResourceFile_aroundBody68(AbstractAPIManager.java:1270) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.addResourceFile(AbstractAPIManager.java:1248) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addResourceFile_aroundBody108(UserAwareAPIProvider.java:449) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addResourceFile(UserAwareAPIProvider.java:446) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addFileToDocumentation_aroundBody126(APIProviderImpl.java:2646) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	... 58 more
Caused by: org.wso2.carbon.registry.core.exceptions.RegistryException: Unable to put resource The path '/_system/governance/apimgt/applicationdata/provider/admin/wsdl1/1.0/documentation/files/update-summary-wso2am-2.6.0+1575989710760.full.pdf' contains one or more illegal characters (~!@#;%^*()+={}|\<>"',)
	at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:299) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2505) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.put(UserDefinedHandlerManager.java:204) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:950) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:705) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.put(CacheBackedRegistry.java:591) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:73) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:816) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_231]
	at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.addResourceFile_aroundBody68(AbstractAPIManager.java:1253) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.addResourceFile(AbstractAPIManager.java:1248) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addResourceFile_aroundBody108(UserAwareAPIProvider.java:449) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addResourceFile(UserAwareAPIProvider.java:446) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addFileToDocumentation_aroundBody126(APIProviderImpl.java:2646) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	... 58 more
Caused by: org.wso2.carbon.registry.core.exceptions.RegistryException: The path '/_system/governance/apimgt/applicationdata/provider/admin/wsdl1/1.0/documentation/files/update-summary-wso2am-2.6.0+1575989710760.full.pdf' contains one or more illegal characters (~!@#;%^*()+={}|\<>"',)
	at org.wso2.carbon.registry.core.jdbc.Repository.put(Repository.java:262) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:717) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:73) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:816) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_231]
	at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:292) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2505) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.put(UserDefinedHandlerManager.java:204) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:950) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:705) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.put(CacheBackedRegistry.java:591) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:73) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:816) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_231]
	at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.6.0.alpha3.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.addResourceFile_aroundBody68(AbstractAPIManager.java:1253) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.addResourceFile(AbstractAPIManager.java:1248) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addResourceFile_aroundBody108(UserAwareAPIProvider.java:449) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addResourceFile(UserAwareAPIProvider.java:446) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addFileToDocumentation_aroundBody126(APIProviderImpl.java:2646) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	... 58 more
[2020-01-25 22:12:55,326] ERROR - DocumentIndexer No document associated to API
[2020-01-25 22:12:55,327] ERROR - DocumentIndexer Error while updating indexed document.
org.wso2.carbon.apimgt.api.APIManagementException: No document associated to API
	at org.wso2.carbon.apimgt.impl.indexing.indexer.DocumentIndexer.fetchDocumentContent_aroundBody4(DocumentIndexer.java:179) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.indexing.indexer.DocumentIndexer.fetchDocumentContent(DocumentIndexer.java:163) ~[org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.indexing.indexer.DocumentIndexer.getIndexedDocument_aroundBody0(DocumentIndexer.java:97) [org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.indexing.indexer.DocumentIndexer.getIndexedDocument(DocumentIndexer.java:74) [org.wso2.carbon.apimgt.impl_6.6.17.SNAPSHOT.jar:?]
	at org.wso2.carbon.registry.indexing.indexer.IndexDocumentCreator.getIndexDocument(IndexDocumentCreator.java:333) [org.wso2.carbon.registry.indexing_4.7.28.jar:?]
	at org.wso2.carbon.registry.indexing.indexer.IndexDocumentCreator.createIndexDocument(IndexDocumentCreator.java:96) [org.wso2.carbon.registry.indexing_4.7.28.jar:?]
	at org.wso2.carbon.registry.indexing.AsyncIndexer$IndexingTask.createIndexDocument(AsyncIndexer.java:245) [org.wso2.carbon.registry.indexing_4.7.28.jar:?]
	at org.wso2.carbon.registry.indexing.AsyncIndexer$IndexingTask.run(AsyncIndexer.java:210) [org.wso2.carbon.registry.indexing_4.7.28.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_231]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]

```

**Comment by Sarangan0219** [comment]
The above issue is not present in the latest version of APIM. Publisher UI is accepting the files with special characters.
![Screenshot from 2020-02-14 11-06-30](https://user-images.githubusercontent.com/60866295/74504498-62969080-4f1a-11ea-8f81-254277b0cf2b.png)
