### ISSUE TITLE
[APIM 3.0.0] Failed to commit the DB connections during CON_APP_KEY violation recovery

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#7380]
### Description:
In the CON_APP_KEY violation recovery flow, the AutoCommit property of the database connection is set to true [1]. At the end of the flow, the connection is explicitly committed [2]. Therefore, the following exception occurs when trying to execute the connection committing

```logs
Caused by: org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: An rolling back transactions error occurred while trying to recover 'CON_APP_KEY' constraint violation .
    at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.recoverFromConAppKeyConstraintViolation(AccessTokenDAOImpl.java:1902) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
    at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:238) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
    at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:97) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
    at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:299) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
    at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.storeAccessToken(AbstractAuthorizationGrantHandler.java:291) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
    ... 69 more
Caused by: java.sql.SQLNonTransientConnectionException: Can''t call rollback when autocommit=true
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
    ...
    at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.recoverFromConAppKeyConstraintViolation(AccessTokenDAOImpl.java:1899) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
    at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:238) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
    at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:97) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
    at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:299) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
    at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.storeAccessToken(AbstractAuthorizationGrantHandler.java:291) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
    ... 69 more
```

### Affected Product Version:
- APIM 3.0.0

### Environment details (with versions):
 - APIM 3.0.0- Alpine3.10 Docker

A similar issue has been reported previously in [3]

1: https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/v6.2.25/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/dao/AccessTokenDAOImpl.java#L1851
2: https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/v6.2.25/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/dao/AccessTokenDAOImpl.java#L1895
3: https://github.com/wso2/product-is/issues/7421

**Comment by isharac** [comment]
Fixes for this issue is available with https://github.com/wso2/product-is/issues/6977
https://github.com/wso2/product-is/issues/6942

**Comment by Krishanx92** [comment]
This is fixed with PR: https://github.com/wso2-support/identity-inbound-auth-oauth/pull/575 and https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1307
