### ISSUE TITLE
Configuring Single Sign-on with OpenID Connect:Unexpected token at position 0

### ISSUE THREAD

**Issue by YatinArora-NEC** [wso2/product-apim#7492]
I am using WSO2 Identity Server  and APIM. I am using Single Sign on for  APIM-store 
 reference "https://docs.wso2.com/display/AM250/Configuring+Single+Sign-on+with+OpenID+Connect".

**Affected version : Identity-Server- 5.3.0
API Manager: 2.1.0**

I'm able to redirect to Identity server page when accessing API-store. After entering credentials it asks for credentials and permission . After granting permission it gives 500 :The Page cannot be displayed.

![image](https://user-images.githubusercontent.com/46880065/74730268-cea32c80-526b-11ea-9419-2b69d3a6ea24.png)
Logs at APIM side:
`ERROR {org.jaggeryjs.jaggery.core.manager.WebAppManager} -  org.mozilla.javascript.WrappedException: Wrapped java.text.ParseException: Invalid JSON: Unexpected token  at position 0. (/store/jagg/jaggery_oidc_acs.jag#36) {org.jaggeryjs.jaggery.core.manager.WebAppManager}
org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped java.text.ParseException: Invalid JSON: Unexpected token  at position 0. (/store/jagg/jaggery_oidc_acs.jag#36)
        at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)
        at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
        at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
        at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
        at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
`

I have also made Claim configuration as mentioned below
![image](https://user-images.githubusercontent.com/46880065/74730025-6ce2c280-526b-11ea-99f6-16ebc6431322.png)

**Comment by tharindu1st** [comment]
invalid issue due to ui revamp
