### ISSUE TITLE
Cannot generate application keys for secondary user

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#7526]
When APIM is configured for the read-write LDAP secondary user store, a user from the user store can log in to the dev portal. 
Once an app is created and tries to generate keys, it shows error and keygen get failed. 

```
TID: [-1234] [] [2020-02-21 14:11:26,284] ERROR {org.wso2.carbon.apimgt.impl.utils.APIUtil} - Error occurred while creating ServiceProvider for app WSO2.COM_user1_one_PRODUCTION org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error while creating application role: Application/WSO2.COM_user1_one_PRODUCTION with user WSO2.COM/user1
	at org.wso2.carbon.identity.application.mgt.ApplicationMgtUtil.assignRoleToUser(ApplicationMgtUtil.java:227)
	at org.wso2.carbon.identity.application.mgt.ApplicationMgtUtil.createAppRole(ApplicationMgtUtil.java:175)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.doAddApplication(ApplicationManagementServiceImpl.java:1826)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.createApplication(ApplicationManagementServiceImpl.java:2088)
	at org.wso2.carbon.apimgt.keymgt.service.APIKeyMgtSubscriberService.createOAuthApplicationByApplicationInfo_aroundBody0(APIKeyMgtSubscriberService.java:159)
	at org.wso2.carbon.apimgt.keymgt.service.APIKeyMgtSubscriberService.createOAuthApplicationByApplicationInfo(APIKeyMgtSubscriberService.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.axis2.rpc.receivers.RPCUtil.invokeServiceClass(RPCUtil.java:212)
	at org.apache.axis2.rpc.receivers.RPCMessageReceiver.invokeBusinessLogic(RPCMessageReceiver.java:117)
	at org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:40)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.axis2.transport.http.HTTPTransportUtils.processHTTPPostRequest(HTTPTransportUtils.java:173)
	at org.apache.axis2.transport.http.AxisServlet.doPost(AxisServlet.java:148)
	at org.wso2.carbon.core.transports.CarbonServlet.doPost(CarbonServlet.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
```

```
<?xml version="1.0" encoding="UTF-8"?><UserStoreManager class="org.wso2.carbon.user.core.ldap.ReadWriteLDAPUserStoreManager">
      <Property name="ConnectionURL">ldap://localhost:10390</Property>
      <Property name="ConnectionName">uid=admin,ou=system</Property>
      <Property encrypted="true" name="ConnectionPassword">eyJjIjoiUUhLZXlJd3hKTXpPckpKUThsODJCL0NiOEMvaWF4cWlYV0IrRGk4cTk4b3o1YkFMZk1DSTd2QTdHcG9Xc3dPMHhpSDhOTGVjb2JneHZnajBpek1uM1NTWDlHN0hYS2RySlZhbkt1ckVhaWhlb3AvOGllc29oQ3lFNDdUSDd4ODZVRkNoVVFWUC9JL294dUVXZ3k0VFVwOVZGbEluem9HK3d4QWJVVW5IeXkzVVloWDF2c2szMnBwWWVHNk9DTjZvZmRWSk1lL0VGS1RZcGtXbmc3TCtYenVVL0J0YnFnMkQvejRIUmdGNnhab2k4VHBVNFhreG1LUEQ2bVk1KzZ6cXN2bWNQd0diS1pNaTZBVkUxZ1RsN2tnSnV1dHVtU090N2FUblVRZWtKVGhaUGQ0U0RqemlFeTlUcjM5cTd6cmdPL2JtcVA2ZHMyaFhwcXFGa3Y2a3BRXHUwMDNkXHUwMDNkIiwidCI6IlJTQS9FQ0IvT0FFUHdpdGhTSEExYW5kTUdGMVBhZGRpbmciLCJ0cCI6IjU3RkYzOEQ5NzY2NEM3OTJGRjg4MDExNzFGMDQxOTFERUQ4ODc3OEQiLCJ0cGQiOiJTSEEtMSJ9</Property>
      <Property name="UserSearchBase">ou=Users,dc=wso2,dc=org</Property>
      <Property name="UserEntryObjectClass">identityPerson</Property>
      <Property name="UserNameAttribute">uid</Property>
      <Property name="UserNameSearchFilter">(&amp;(objectClass=person)(uid=?))</Property>
      <Property name="UserNameListFilter">(objectClass=person)</Property>
      <Property name="UserDNPattern"/>
      <Property name="DisplayNameAttribute"/>
      <Property name="Disabled">false</Property>
      <Property name="ReadGroups">true</Property>
      <Property name="WriteGroups">true</Property>
      <Property name="GroupSearchBase">ou=Groups,dc=wso2,dc=org</Property>
      <Property name="GroupEntryObjectClass">groupOfNames</Property>
      <Property name="GroupNameAttribute">cn</Property>
      <Property name="GroupNameSearchFilter">(&amp;(objectClass=groupOfNames)(cn=?))</Property>
      <Property name="GroupNameListFilter">(objectClass=groupOfNames)</Property>
      <Property name="RoleDNPattern"/>
      <Property name="MembershipAttribute">member</Property>
      <Property name="MemberOfAttribute"/>
      <Property name="BackLinksEnabled">false</Property>
      <Property name="UserNameJavaRegEx">[a-zA-Z0-9._-|//]{3,30}$</Property>
      <Property name="UserNameJavaScriptRegEx">^[\S]{3,30}$</Property>
      <Property name="UsernameJavaRegExViolationErrorMsg">Username pattern policy violated.</Property>
      <Property name="PasswordJavaRegEx">^[\S]{5,30}$</Property>
      <Property name="PasswordJavaScriptRegEx">^[\S]{5,30}$</Property>
      <Property name="PasswordJavaRegExViolationErrorMsg">Password pattern policy violated.</Property>
      <Property name="RoleNameJavaRegEx">[a-zA-Z0-9._-|//]{3,30}$</Property>
      <Property name="RoleNameJavaScriptRegEx">^[\S]{3,30}$</Property>
      <Property name="LDAPInitialContextFactory">com.sun.jndi.ldap.LdapCtxFactory</Property>
      <Property name="BulkImportSupported">true</Property>
      <Property name="EmptyRolesAllowed">true</Property>
      <Property name="PasswordHashMethod">PLAIN_TEXT</Property>
      <Property name="MultiAttributeSeparator">,</Property>
      <Property name="MaxUserNameListLength">100</Property>
      <Property name="MaxRoleNameListLength">100</Property>
      <Property name="kdcEnabled">false</Property>
      <Property name="defaultRealmName">WSO2.ORG</Property>
      <Property name="UserRolesCacheEnabled">true</Property>
      <Property name="ConnectionPoolingEnabled">false</Property>
      <Property name="LDAPConnectionTimeout">5000</Property>
      <Property name="ReadTimeout">5000</Property>
      <Property name="RetryAttempts">0</Property>
      <Property name="CountRetrieverClass"/>
      <Property name="java.naming.ldap.attributes.binary"> </Property>
      <Property name="ClaimOperationsSupported">true</Property>
      <Property name="MembershipAttributeRange">0</Property>
      <Property name="UserCacheExpiryMilliseconds"/>
      <Property name="UserDNCacheEnabled">true</Property>
      <Property name="StartTLSEnabled">false</Property>
      <Property name="ConnectionRetryDelay">120000</Property>
      <Property name="SSLCertificateValidationEnabled">true</Property>
      <Property name="DomainName">wso2.com</Property>
      <Property name="Description"/>
</UserStoreManager>
```

**Comment by ruks** [comment]
This issue does not occur when recommending user store managers(Listed below) are used. 
```
org.wso2.carbon.user.core.ldap.UniqueIDReadOnlyLDAPUserStoreManager
org.wso2.carbon.user.core.ldap.UniqueIDReadWriteLDAPUserStoreManager
```
