### ISSUE TITLE
Incorrect error message when Thrift session is not found in DB

### ISSUE THREAD

**Issue by ankit-agrawal07** [wso2/product-apim#7568]
### Description:

When thrift session with given ID is not found in DB, the exception contains an invalid error message.
The call to update last access time and remove session in DBThriftSessionDAO class throws IdentityException with incorrect message.

A pull request has been created to fix the issue here:
https://github.com/wso2-attic/carbon-identity/pull/1758

Since that repository has not been maintained for over 4 years, I am raising the ticket to review/merge the PR here. Please guide me if this is not the right place to report the issue.

### Steps to reproduce:
A setup where WSO2 IS (5.7.0) is used as key manager for WSO2 APIM (2.6.0). The communication is set to works via thrift client. 
The error was seen intermittently and disappeared after some time. Stacktrace is:

Thrift session with given Session Id already exists.
at org.wso2.carbon.identity.base.IdentityException.error(IdentityException.java:52)
at org.wso2.carbon.identity.thrift.authentication.dao.DBThriftSessionDAO.updateLastAccessTime(DBThriftSessionDAO.java:221)
at org.wso2.carbon.identity.thrift.authentication.internal.ThriftAuthenticatorServiceImpl.isAuthenticated(ThriftAuthenticatorServiceImpl.java:196)
at org.wso2.carbon.apimgt.keymgt.service.thrift.APIKeyValidationServiceImpl.validateKey(APIKeyValidationServiceImpl.java:103)
at org.wso2.carbon.apimgt.impl.generated.thrift.APIKeyValidationService$Processor$validateKey.getResult(APIKeyValidationService.java:379)
at org.wso2.carbon.apimgt.impl.generated.thrift.APIKeyValidationService$Processor$validateKey.getResult(APIKeyValidationService.java:367)
at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:32)
at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:34)
at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:176)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

### Affected Product Version:

APIM 2.6.0 with IS 5.7.0

### Environment details (with versions):
- OS: Ubuntu
- Client:
- Env (Docker/K8s): standalone instances

---

**Comment by pubudu538** [comment]
Hi, 

We do recommend to use WSClient for API Key validation. You can find the docs related to this in https://docs.wso2.com/display/AM260/Deploying+WSO2+API-M+in+a+Distributed+Setup#DeployingWSO2API-MinaDistributedSetup-Step6.1-ConfigureandstarttheKeyManager. From going forward from API Manager v3.0.0, we have switched default to WSClient.

I am closing the issue as we have a solution here. We don't have any plans to fix thrift related to issues in key validation as the production we use WSCLient and we have moved to WSCLient by default.

Thank you!
Pubudu.
