### ISSUE TITLE
JWT validation fails in the API invocation when public certificate imports with a custom alias.

### ISSUE THREAD

**Issue by AshenJayasuriya** [wso2/product-apim#7570]
Step 01: Export the public certificate from WSO2 APIManager's key store. (APIM 3.0.0)
Step 02: Remove the client-tuststore.jks file.
Step 03: Import the public certificate into the trust store with different alias(not default "gateway_certificate_alias").
Step 04: Run the APIM server.
Step 05: Create an API and publish it.
Step 06: Create an Application and secure the API  using JWT Tokens.
Step 07: Retrieve the JWT access token and invoke the API.

This shows an authentication error stated missing public key with alias "gateway_certificate-alias".

```
[2020-01-24 20:09:09,181] ERROR - GatewayUtils Couldn't find a public certificate to verify signature with alias gateway_certificate_alias
[2020-01-24 20:09:09,185] ERROR - APIAuthenticationHandler API authentication failure due to Unclassified Authentication Failure
org.wso2.carbon.apimgt.gateway.handlers.security.APISecurityException: Unclassified Authentication Failure
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate_aroundBody42(APIAuthenticationHandler.java:433) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate(APIAuthenticationHandler.java:413) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest_aroundBody36(APIAuthenticationHandler.java:349) [org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest(APIAuthenticationHandler.java:320) [org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.apache.synapse.rest.API.process(API.java:366) [synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149) [synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95) [synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71) [synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:325) [synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98) [synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) [axis2_1.6.1.wso2v38.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367) [synapse-nhttp-transport_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:188) [synapse-nhttp-transport_2.1.7.wso2v131.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v38.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
```

Token signature validation happens from the public certificate with mentioned alias. Couldn't add custom alias in the public certificates.

**Comment by pubudu538** [comment]
Hi @AshenJayasuriya,

First, let me explain how the JWT tokens work. When you generate a JWT token, the private key of the server (Key manager) is used to sign the token. When validating the JWT token which happens at the gateway, we ask the users to add the public key of the key manager to the client trust store of the gateway. When you are adding the certificate to the client trust store, you need to use the alias as the gateway_certificate-alias. This is not the alias that needs to be in the public certificate. 

You can check the JWT token related docs in [1] and importing cert to trust store in [2].

As this is not an issue, I am closing this issue for the moment. If you need any information or to discuss further on this, please do reopen this issue.

[1] - https://apim.docs.wso2.com/en/latest/learn/api-security/oauth2/access-token-types/jwt-tokens/
[2] - https://docs.wso2.com/display/ADMIN44x/Creating+New+Keystores

Thank you!
Pubudu.
