### ISSUE TITLE
Password reset via OTP: Configured callback URL does not match with the provided callback URL

### ISSUE THREAD

**Issue by manuel-di-iorio** [wso2/product-apim#7578]
There seems to be an issue with the offline OTP user password reset form. The error is `Configured callback URL does not match with the provided callback URL`

This is my actual callback URL configured on the service provider: `regexp=(http://localhost:2000/api/v1/auth/callback|http://localhost:2000/api/v1/auth/logout/callback)`
I also tried by not using the regex, so only `http://localhost:2000/api/v1/auth/callback` without success

This is the authorize URL: `https://localhost:9443/oauth2/authorize?client_id=<clientid>&scope=openid&response_type=code&redirect_uri=http://localhost:2000/api/v1/auth/callback`

**Detailed error in the logs:**
```
SetPasswordApiServiceImpl Error occurred in the server while performing the task.
org.wso2.carbon.identity.recovery.IdentityRecoveryServerException: 
Configured callback URL does not match with the provided callback URL: http://localhost:2000/api/v1/auth/callback in the request.

	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.wso2.carbon.identity.base.IdentityException.error(IdentityException.java:81) ~[org.wso2.carbon.identity.base_5.14.97.jar:?]
	at org.wso2.carbon.identity.recovery.util.Utils.handleServerException(Utils.java:181) ~[org.wso2.carbon.identity.recovery_1.3.15.jar:?]
	at org.wso2.carbon.identity.recovery.password.NotificationPasswordRecoveryManager.updatePassword(NotificationPasswordRecoveryManager.java:187) ~[org.wso2.carbon.identity.recovery_1.3.15.jar:?]
	at org.wso2.carbon.identity.recovery.endpoint.impl.SetPasswordApiServiceImpl.setPasswordPost(SetPasswordApiServiceImpl.java:27) [classes/:?]
	at org.wso2.carbon.identity.recovery.endpoint.SetPasswordApi.setPasswordPost(SetPasswordApi.java:46) [classes/:?]

```
### Steps to reproduce:
1) Force reset an user password via SOAP API
2) In the service provider login page, enter the username and OTP retrieved from the claims
3) Enter the new password in the reset password form and submit.
4) The error with code 20044 is shown on the page

![image](https://user-images.githubusercontent.com/2255291/75253475-df5d2080-57de-11ea-8ea6-3e89490f10b3.png)

### Affected Product Version:

3.0.0

### Environment details (with versions):

OS: Ubuntu 19.10

---

#### Related Issues:
Maybe related: https://github.com/wso2/product-is/issues/7145

**Comment by manuel-di-iorio** [comment]
We managed to find the answer, it's not a bug, just an unclear thing.
It's needed to change the Identity Provider > Resident configuration > Account Recovery > Recovery callback URL regex, from the default WSO2 one, which has to match with the provided redirect uri.

![image](https://user-images.githubusercontent.com/2255291/75262085-492ff700-57ec-11ea-862b-58e4ab16658b.png)

Hope this can help someone else!

**Comment by kalevivek11** [comment]
@manuel-di-iorio I tried same thing but it is not working for me
