### ISSUE TITLE
Issue while invoking GraphQL mutation operation

### ISSUE THREAD

**Issue by chaamini** [wso2/product-apim#7645]
I am trying to test GraphQL endpoint (https://api.graph.cool/simple/v1/ciz751zxu2nnd01494hr653xl) with WSO2 API Manager 3.0.0. When I try to invoke following mutation query Im getting the error attached

**Mutation Query** - 
{
	"query": "mutation createAuthorAndContactDetails { createAuthor( description: \"GraphQL Testing \" contactDetails: { email: \"test@graph.cool\" }) {id contactDetails { id email } }}"
}

**Error Log** - 
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.gateway.handlers.security.oauth.OAuthAuthenticator.authenticate_aroundBody4(OAuthAuthenticator.java:229) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.oauth.OAuthAuthenticator.authenticate(OAuthAuthenticator.java:107) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate_aroundBody42(APIAuthenticationHandler.java:419) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate(APIAuthenticationHandler.java:413) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest_aroundBody36(APIAuthenticationHandler.java:349) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest(APIAuthenticationHandler.java:320) ~[org.wso2.carbon.apimgt.gateway_6.5.349.jar:?]
	at org.apache.synapse.rest.API.process(API.java:366) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:325) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98) ~[synapse-core_2.1.7.wso2v131.jar:2.1.7-wso2v131]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v38.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367) [synapse-nhttp-transport_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:412) [synapse-nhttp-transport_2.1.7.wso2v131.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181) [synapse-nhttp-transport_2.1.7.wso2v131.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v38.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]

**Comment by HiranyaKavishani** [comment]
We have to support the nested level operation for mutation as well
