### ISSUE TITLE
WSO2 APIManager 3.1.0-beta crashes when connected with Oracle DB (java.sql.BatchUpdateException: ORA-01400)

### ISSUE THREAD

**Issue by pkowanski** [wso2/product-apim#7653]
### Description:
WSO2 APIManager cannot launch, after few seconds appears an error and application crashes.

```[2020-03-03 16:41:37,697] []  WARN {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Admin User :admin is already added. Hence, continue without adding the user.
[2020-03-03 16:41:37,760] [] ERROR {org.wso2.carbon.user.core.common.DefaultRealm} - nullType class java.lang.reflect.InvocationTargetException org.wso2.carbon.user.core.UserStoreException: nullType class java.lang.reflect.InvocationTargetException
        at org.wso2.carbon.user.core.common.DefaultRealm.createObjectWithOptions(DefaultRealm.java:397)
        at org.wso2.carbon.user.core.common.DefaultRealm.initializeObjects(DefaultRealm.java:224)
        at org.wso2.carbon.user.core.common.DefaultRealm.init(DefaultRealm.java:129)
        at org.wso2.carbon.user.core.common.DefaultRealmService.initializeRealm(DefaultRealmService.java:276)
        at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:102)
        at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:115)
        at org.wso2.carbon.user.core.internal.Activator.startDeploy(Activator.java:72)
        at org.wso2.carbon.user.core.internal.BundleCheckActivator.start(BundleCheckActivator.java:61)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
        at org.eclipse.osgi.container.Module.doStart(Module.java:598)
        at org.eclipse.osgi.container.Module.start(Module.java:462)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.wso2.carbon.user.core.common.DefaultRealm.createObjectWithOptions(DefaultRealm.java:351)
        ... 25 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Admin role has not been created. Error occurs while creating Admin role inprimary user store.
        at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addInitialAdminData(AbstractUserStoreManager.java:8390)
        at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:319)
        at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:258)
        ... 30 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while getting database type from DB connection
        at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.doAddRole(JDBCUserStoreManager.java:1617)
        at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addInitialAdminData(AbstractUserStoreManager.java:8379)
        ... 32 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Using sql : INSERT INTO UM_USER_ROLE (UM_USER_ID, UM_ROLE_ID, UM_TENANT_ID) VALUES ((SELECT UM_ID FROM UM_USER WHERE LOWER(UM_USER_NAME)=LOWER(?) AND UM_TENANT_ID=?),(SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME=? AND UM_TENANT_ID=?), ?) ORA-01400: cannot insert NULL into ("WSOOO_KUBE"."UM_USER_ROLE"."UM_USER_ID")
        at org.wso2.carbon.user.core.util.DatabaseUtil.udpateUserRoleMappingInBatchMode(DatabaseUtil.java:1005)
        at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.doAddRole(JDBCUserStoreManager.java:1591)
        ... 33 more
Caused by: java.sql.BatchUpdateException: ORA-01400: cannot insert NULL into ("WSOOO_KUBE"."UM_USER_ROLE"."UM_USER_ID")
        at oracle.jdbc.driver.OraclePreparedStatement.executeLargeBatch(OraclePreparedStatement.java:10032)
        at oracle.jdbc.driver.T4CPreparedStatement.executeLargeBatch(T4CPreparedStatement.java:1364)
        at `oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:9839)
        at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:234)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
        at com.sun.proxy.$Proxy49.executeBatch(Unknown Source)
        at org.wso2.carbon.user.core.util.DatabaseUtil.udpateUserRoleMappingInBatchMode(DatabaseUtil.java:994)
        ... 34 more

[2020-03-03 16:41:37,817] [] ERROR {org.wso2.carbon.user.core.internal.Activator} - Cannot start User Manager Core bundle org.wso2.carbon.user.core.UserStoreException: Cannot initialize the realm.
        at org.wso2.carbon.user.core.common.DefaultRealmService.initializeRealm(DefaultRealmService.java:286)
        at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:102)
        at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:115)
        at org.wso2.carbon.user.core.internal.Activator.startDeploy(Activator.java:72)
        at org.wso2.carbon.user.core.internal.BundleCheckActivator.start(BundleCheckActivator.java:61)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
        at org.eclipse.osgi.container.Module.doStart(Module.java:598)
        at org.eclipse.osgi.container.Module.start(Module.java:462)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: org.wso2.carbon.user.core.UserStoreException: nullType class java.lang.reflect.InvocationTargetException
        at org.wso2.carbon.user.core.common.DefaultRealm.initializeObjects(DefaultRealm.java:318)
        at org.wso2.carbon.user.core.common.DefaultRealm.init(DefaultRealm.java:129)
        at org.wso2.carbon.user.core.common.DefaultRealmService.initializeRealm(DefaultRealmService.java:276)
        ... 22 more
Caused by: org.wso2.carbon.user.core.UserStoreException: nullType class java.lang.reflect.InvocationTargetException
        at org.wso2.carbon.user.core.common.DefaultRealm.createObjectWithOptions(DefaultRealm.java:397)
        at org.wso2.carbon.user.core.common.DefaultRealm.initializeObjects(DefaultRealm.java:224)
        ... 24 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.wso2.carbon.user.core.common.DefaultRealm.createObjectWithOptions(DefaultRealm.java:351)
        ... 25 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Admin role has not been created. Error occurs while creating Admin role inprimary user store.
        at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addInitialAdminData(AbstractUserStoreManager.java:8390)
        at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:319)
        at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:258)
        ... 30 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while getting database type from DB connection
        at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.doAddRole(JDBCUserStoreManager.java:1617)
        at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addInitialAdminData(AbstractUserStoreManager.java:8379)
        ... 32 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Using sql : INSERT INTO UM_USER_ROLE (UM_USER_ID, UM_ROLE_ID, UM_TENANT_ID) VALUES ((SELECT UM_ID FROM UM_USER WHERE LOWER(UM_USER_NAME)=LOWER(?) AND UM_TENANT_ID=?),(SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME=? AND UM_TENANT_ID=?), ?) ORA-01400: cannot insert NULL into ("WSOOO_KUBE"."UM_USER_ROLE"."UM_USER_ID")

        at org.wso2.carbon.user.core.util.DatabaseUtil.udpateUserRoleMappingInBatchMode(DatabaseUtil.java:1005)
        at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.doAddRole(JDBCUserStoreManager.java:1591)
        ... 33 more
Caused by: java.sql.BatchUpdateException: ORA-01400: cannot insert NULL into ("WSOOO_KUBE"."UM_USER_ROLE"."UM_USER_ID")

        at oracle.jdbc.driver.OraclePreparedStatement.executeLargeBatch(OraclePreparedStatement.java:10032)
        at oracle.jdbc.driver.T4CPreparedStatement.executeLargeBatch(T4CPreparedStatement.java:1364)
        at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:9839)
        at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:234)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
        at com.sun.proxy.$Proxy49.executeBatch(Unknown Source)
        at org.wso2.carbon.user.core.util.DatabaseUtil.udpateUserRoleMappingInBatchMode(DatabaseUtil.java:994)
        ... 34 more
```

It appears that the default admin user cannot be added during the application start for unknown reason which breaks constraints in Oracle DB.

### Steps to reproduce:
1. Setup the Oracle Database - two schemas WSO2AM_DB and WSO2AM_SHARED_DB using official scripts for Oracle from WSO2 product-apim repository.
2. Launch an application WSO2 API Manager
3. After a few second it appears an error

### Affected Product Version:
3.1.0-beta

### Environment details (with versions):
- OS: CentOS 7
- Client: 
- Env (Docker/K8s): Kubernetes v1.17.0

**Comment by shilmyhasan** [comment]
The issue is not reproducible in the beta pack. The above error can occur when the trigger (UM_USER_ROLE_TRIGGER) is not executed in the script. Please check whether the sequence(UM_USER_ROLE_SEQUENCE) and trigger(UM_USER_ROLE_TRIGGER) is created in your Database.

**Comment by pkowanski** [comment]
These trigger and sequence were created successfully. But I see that UM_USER_ROLE_TRIGGER inserts value to column UM_ID and exception was thrown by occurence of NULL in column UM_USER_ID.

**Comment by guschakray** [comment]
We are experiencing this error in RC3 too. Any plans to solve before GA? Thanks

**Comment by shilmyhasan** [comment]
Are you trying this against a db thats created using the 3.0 scripts, then the above error can occur since UM_USER_ID is a newly added column.

**Comment by guschakray** [comment]
Using 3.1.0-RC3 dbscripts and verified that UM_USER_ROLE table has columns : UM_ID, UM_ROLE_ID, UM_USER_ID, UM_TENAT_ID
It seems the error raises because product tries to insert a null value on startup.
We are trying to install RC3 with Oracle 12.1.0.2.0.

**Comment by scholtz** [comment]
The same issue occurs to me using MSSQL with wso2/wso2am:3.2.0 docker image. I am running kubernetes environment and only difference with the original docker image is the deployment.toml file.

Steps to reproduce:
1) setup db schema using all mssql sql files found in /home/wso2carbon/wso2am-3.2.0/dbscripts/ folder
2) setup deployment config:
```
[database.shared_db]
type = "mssql"
url = "jdbc:sqlserver://server:1433;databaseName=db;SendStringParametersAsUnicode=false"
username = "..."
password = "..."
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
validationQuery = "SELECT 1"

[database.apim_db]
type = "mssql"
url = "jdbc:sqlserver://server:1433;databaseName=db;SendStringParametersAsUnicode=false"
username = "..."
password = "..."
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
validationQuery = "SELECT 1"
```
3) start deployment 

The start has failed with: 
```
Activator Cannot start User Manager Core bundle
nullType class java.lang.reflect.InvocationTargetException
Admin user has not been created. Error occurs while creating Admin user in primary user store.
Error while persisting user : admin
Error occurred while updating string values to database.
Cannot insert the value NULL into column 'UM_USER_ID', table 'db.dbo.UM_USER'; column does not allow nulls. INSERT fails.
```

Full log:
[logs-from-wso2apim-with-analytics-apim-worker-in-wso2apim-with-analytics-apim-59f7b56457-2wthx.txt](https://github.com/wso2/product-apim/files/5647110/logs-from-wso2apim-with-analytics-apim-worker-in-wso2apim-with-analytics-apim-59f7b56457-2wthx.txt)

**Comment by scholtz** [comment]
I have solved this issue for me in MSSQL environment by running:
```sql
ALTER TABLE UM_USER ALTER COLUMN UM_USER_ID VARCHAR(255) NULL;
```
