### ISSUE TITLE
NPE is thrown out when observerbility logs are enabled

### ISSUE THREAD

**Issue by NipuniC** [wso2/product-apim#7676]
### Description:

When logs are enabled the following NPE throws out during API invocation.

```
TID: [-1] [] [2020-03-06 14:40:01,294] ERROR {org.apache.synapse.transport.passthru.TargetHandler} -  Unexpected error. {org.apache.synapse.transport.passthru.TargetHandler}
TID: [-1] [] [2020-03-06 14:40:01,294]  WARN {org.apache.synapse.transport.passthru.PassThroughHttpSSLSender} -  System may be unstable: HTTPS ConnectingIOReactor encountered a runtime exception : null {org.apache.synapse.transport.passthru.PassThroughHttpSSLSender}
java.lang.NullPointerException
	at org.apache.synapse.transport.passthru.TargetHandler.logHttpRequestErrorInCorrelationLog(TargetHandler.java:846)
	at org.apache.synapse.transport.passthru.TargetHandler.exception(TargetHandler.java:804)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.produceOutput(DefaultNHttpClientConnection.java:312)
	at org.apache.synapse.transport.http.conn.LoggingNHttpClientConnection.produceOutput(LoggingNHttpClientConnection.java:134)
	at org.apache.synapse.transport.passthru.ClientIODispatch.onOutputReady(ClientIODispatch.java:88)
	at org.apache.synapse.transport.passthru.ClientIODispatch.onOutputReady(ClientIODispatch.java:41)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.outputReady(AbstractIODispatch.java:150)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.writable(BaseIOReactor.java:180)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:342)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2020-03-06 14:40:01,295]  WARN {org.apache.synapse.transport.passthru.TargetHandler} -  Connection closed by target host before receiving the response  Remote Address : 58.26.233.132/58.26.233.132:8243 {org.apache.synapse.transport.passthru.TargetHandler}
TID: [-1] [] [2020-03-06 14:40:01,296]  WARN {org.apache.synapse.transport.passthru.PassThroughHttpSSLSender} -  System may be unstable: HTTPS ConnectingIOReactor encountered a runtime exception : null {org.apache.synapse.transport.passthru.PassThroughHttpSSLSender}
java.lang.NullPointerException
	at org.apache.synapse.transport.passthru.TargetContext.updateState(TargetContext.java:173)
	at org.apache.synapse.transport.passthru.TargetHandler.closed(TargetHandler.java:599)
	at org.apache.synapse.transport.passthru.ClientIODispatch.onClosed(ClientIODispatch.java:73)
	at org.apache.synapse.transport.passthru.ClientIODispatch.onClosed(ClientIODispatch.java:41)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.disconnected(AbstractIODispatch.java:100)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionClosed(BaseIOReactor.java:271)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processClosedSessions(AbstractIOReactor.java:439)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:284)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	at java.lang.Thread.run(Thread.java:748)
```

### Affected Product Version:
AM-2.2.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by AmaliMatharaarachchi** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1397
