### ISSUE TITLE
WSO2 APIM 300 issue of authentication 

### ISSUE THREAD

**Issue by chkishorebabu** [wso2/product-apim#7701]
WSO2 API manager is installed behind a load balancer and tried to login into the publisher portal. I get an error of HTTP ERROR 500 on the WSO2 Web console after a default user name and password is input (admin/admin). 
**In the server logs I see the following error :**

TID: [-1234] [publisher] [2020-03-11 12:17:45,346] ERROR {org.jaggeryjs.jaggery.core.manager.WebAppManager} - org.mozilla.javascript.EcmaError: **TypeError: Cannot read property "length" from undefined (/publisher/services/login/login_callback.jag#53)** org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from undefined (/publisher/services/login/login_callback.jag#53)
    at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:587)
    at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:289)
    at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:589)
    at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
    at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
    at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
    at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352)

**Comment by tmkasun** [comment]
Did you change the hostname in the `deployment.toml`, It seems that there is a connection issue from the server to that hostname, i:e if you are running the server in docker, is the server hostname accessible from the server node itself ?

**Comment by chkishorebabu** [comment]
Thank you for a quick response. I have kept log in the login_callback.jag file and observed that the issue is due to the redirection as I have not updated the hostname in deployment.toml file. Thank you for the response and the issue is now resolved after updating the hostname.
