### ISSUE TITLE
Microgateway analytics via gRPC intermittently failing (during load test).

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-apim#7754]
### Description:
When microgateway sends events to the analytics node via gRPC (during a load test), it fails intermittently. The load test was 100 concurrent users where each user send 1000 requests. 

The following error log is visible in the analytics node.
```
osgi> [2020-03-16 22:25:50,729] ERROR {io.grpc.internal.SerializingExecutor} - Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@12c58f69 java.util.concurrent.RejectedExecutionException: Task io.siddhi.extension.io.grpc.source.GrpcWorkerThread@1c027299 rejected from java.util.concurrent.ThreadPoolExecutor@4d71871[Running, pool size = 100, active threads = 99, queued tasks = 99, completed tasks = 487836]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at io.siddhi.extension.io.grpc.source.GenericServiceServer$1$1.onNext(GenericServiceServer.java:161)
	at io.siddhi.extension.io.grpc.source.GenericServiceServer$1$1.onNext(GenericServiceServer.java:154)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:249)
	at io.grpc.ForwardingServerCallListener.onMessage(ForwardingServerCallListener.java:33)
	at io.grpc.Contexts$ContextualizedServerCallListener.onMessage(Contexts.java:76)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:773)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

In the microgateway, we could see the following log repeatedly.

```
2020-03-16 22:26:59,306 INFO  [wso2/gateway/src/gateway/utils] - [gRPCAnalytics] [-] Error from Connector: {ballerina/grpc}CancelledError - Failed to send the message 
2020-03-16 22:26:59,318 INFO  [wso2/gateway/src/gateway/utils] - [gRPCAnalytics] [-] Error from Connector: {ballerina/grpc}InternalError - Failed to frame message 
2020-03-16 22:26:59,337 INFO  [wso2/gateway/src/gateway/utils] - [gRPCAnalytics] [-] Error from Connector: {ballerina/grpc}InternalError - Failed to frame message
```
### Steps to reproduce:
Enable microgateway analytics to use gRPC. Start the microgateway and do a load test with jmeter setting concurrency to 100. 
Please note that this is a rare scenario.

### Affected Product Version:
3.1.0-rc1

### Environment details (with versions):
- OS: MacOS Mojave
- Client:
- Env (Docker/K8s):
- Microgateway: 3.1.0-beta

---
#### Suggested Labels:
Affected/3.1.0-rc1

**Comment by VirajSalaka** [comment]
This is due to the lack of resources in the analytics node. We need to increase the thread pool size parameter via defining the pool size parameter.
https://siddhi-io.github.io/siddhi-io-grpc/api/1.0.8/#grpc-source

This is the location where it needs to be added.
https://github.com/wso2/analytics-apim/blob/ccb18832940e3e62e6183c4c5a0357432bff83da/product/distribution/carbon-home/conf/worker/deployment.yaml#L440

We could increase the value by default after performing load testing several times. Needs to check whether it is going to make a huge impact in terms of memory utilization.

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
