### ISSUE TITLE
NPE prints at APIM side server log for migrated 3.1.0 Is-km setup 

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#7808]
### Description:
The apim server log has been printed the following exception when it calling the key template retriever.

```
Exception in thread "Timer-13" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
	at java.util.Arrays.asList(Arrays.java:3800)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService_aroundBody6(KeyTemplateRetriever.java:117)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService(KeyTemplateRetriever.java:116)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run_aroundBody0(KeyTemplateRetriever.java:55)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run(KeyTemplateRetriever.java:51)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

### Steps to reproduce:
* Setup APIM 3.0.0 with is-km 5.9
* Create, Publish, Subscribe and invoke API for both tenant and super tenant users
* Do the migration steps the for APIM 3.1.0  with is-km 5.10
* Start the Iskm first and the APIM
* APIM prints NPE for timer task to retrieve templates

### Affected Product Version:
3.1.0

### Environment details (with versions):
Mac Os

### DBs:
Mysql, PostgreSQL 

---

**Comment by HiranyaKavishani** [comment]
This is reproducible in normal  APIM3.0.0 - iskm5.10  setup.
It seems there is a difference between ResourceAccessControl configuration at identity.xml at Iskm as it has been configured as default-access="deny"

**Comment by HiranyaKavishani** [comment]
Solution: 
We have to make the following config[1] to true for Is-km.

_"resource_access_control.default_access_allow":true,_

[1] https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/org.wso2.carbon.identity.core.server.feature.default.json#L405

**Comment by SiluniPathirana** [comment]
In real deployment adding the following configuration to deployment.toml file resides in the <IS_KM>/repository/conf folder will solve the issue

{code}
[resource_access_control]
default_access_allow= true
{code}

**Comment by HiranyaKavishani** [comment]
Thanks. We will fix this issue via WUM.

**Comment by adityamajeti** [comment]
@SiluniPathirana, yeah it worked for me. thanks.
