### ISSUE TITLE
Tenant API creation fails intermittently.

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#7816]
### Description:
This issue is intermittent and reproducible for only non-admin tenant users at the first login to the publisher. Issue gets resolved in next logins.

### Steps to reproduce:
unzip an apim pack.
start the server.
goto carbon and create a tenant. login as the tenant. create a tenant user without admin role but with all other roles.
login to publisher with the tenant user. 
create a rest api. 

Error:
`ERROR - Repository Failed to add new resource. User subscriber does not have authorization to update the collection /_system/governance/apimgt/applicationdata.
[2020-03-24 12:08:33,195] ERROR - GovernanceArtifactManager Failed to add artifact: artifact id: a554b447-bdfe-4087-90df-301ab504451a. Unable to put resource Failed to add new resource. User subscriber does not have authorization to update the collection /_system/governance/apimgt/applicationdata.
org.wso2.carbon.registry.core.exceptions.RegistryException: Unable to put resource Failed to add new resource. User subscriber does not have authorization to update the collection /_system/governance/apimgt/applicationdata.
	at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:299) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2505) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.put(UserDefinedHandlerManager.java:204) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:950) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:705) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.put(CacheBackedRegistry.java:591) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:828) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:61) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:804) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:801) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:801) ~[org.wso2.carbon.registry.core_4.5.1.jar:?]
	at org.wso2.carbon.governance.api.common.GovernanceArtifactManager.addGovernanceArtifact(GovernanceArtifactManager.java:221) [org.wso2.carbon.governance.api_4.8.10.jar:?]
	at org.wso2.carbon.governance.api.generic.GenericArtifactManager.addGenericArtifact(GenericArtifactManager.java:208) [org.wso2.carbon.governance.api_4.8.10.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.createAPI_aroundBody142(APIProviderImpl.java:3277) [org.wso2.carbon.apimgt.impl_6.5.349.jar:?]`

### Affected Product Version:

3.0.0 Wum updated
3.1.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Meruja** [comment]
This issue is reproducible for both 3.0.0 wum updated pack and 3.1.0 for the unzipped fresh pack and first tenant-user only.
 
Getting the following error as well:

```
[2020-04-01 15:57:19,350] ERROR - TenantServiceCreator Error while copying API manager specific synapse sequencesjava.io.IOException: Failed to copy full contents from '/Users/meruja/Desktop/RC3/tenant/repository/resources/apim-synapse-config/_throttle_out_handler_.xml' to '/Users/meruja/Desktop/RC3/tenant/repository/tenants/1/synapse-configs/default/sequences/_throttle_out_handler_.xml'
[2020-04-01 15:57:19,382]  INFO - PermissionUpdater Permission cache updated for tenant 1

```

**Comment by Meruja** [comment]
> This issue is reproducible for both 3.0.0 wum updated pack and 3.1.0 for the unzipped fresh pack and first tenant-user only.
> 
> Getting the following error when tenant admin log in:
> 
> ```
> [2020-04-01 15:57:19,350] ERROR - TenantServiceCreator Error while copying API manager specific synapse sequencesjava.io.IOException: Failed to copy full contents from '/Users/meruja/Desktop/RC3/tenant/repository/resources/apim-synapse-config/_throttle_out_handler_.xml' to '/Users/meruja/Desktop/RC3/tenant/repository/tenants/1/synapse-configs/default/sequences/_throttle_out_handler_.xml'
> [2020-04-01 15:57:19,382]  INFO - PermissionUpdater Permission cache updated for tenant 1
> ```

Could able to resolve this when we remove the else part of updateResourcePermissionsBy class.
[https://github.com/wso2/carbon-kernel/pull/2346/files](url)

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
