### ISSUE TITLE
NPE in ThrottlerDataHolder when subject in JWT is not set

### ISSUE THREAD

**Issue by Jacobski-fr** [wso2/product-apim#7822]
### Description:
I'm trying to integrate API Manager with an external Key Manager (Identity Server 4), but I get a NPE when invoking the API resource with a JWT issued by my KM with grant_type = client_credentials.
I get a NullPointerException in ThrottleDataHolder.isRequestBlocked because userBlockingKey is null.
userBlockingKey is null because the username in the authorization context is null (see ThrottlerHandler.doRoleBasedAccessThrottlingWithCEP)
Username is null in the context because the authorization context is generated using the following method in GatewayUtils which extracts the username from the subject of the JWT. But there is no subject in my JWT as it was issued with grant_type = client_credentials.

``` java
public static AuthenticationContext generateAuthenticationContext(String tokenSignature, JWTClaimsSet payload,
                                                                      JSONObject api,
                                                                      APIKeyValidationInfoDTO apiKeyValidationInfoDTO,
                                                                      String apiLevelPolicy, String endUserToken,
                                                                      boolean isOauth) throws java.text.ParseException {


        AuthenticationContext authContext = new AuthenticationContext();
        authContext.setAuthenticated(true);
        authContext.setApiKey(tokenSignature);
        authContext.setUsername(payload.getSubject());
```

Example of payload generated by my KM : 
``` json
{
  "nbf": 1585063135,
  "exp": 1585066735,
  "iss": "http://localhost:5000",
  "aud": "api1",
  "client_id": "0139a030-ef74-4743-be73-321246a9349d",
  "scope": [
    "myapi.read"
  ]
}
```

The stack trace of the exception is : 
```
ERROR - ServerWorker Error processing GET request for : /myapi/v1/WeatherForecast.
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964) ~[?:?]
        at org.wso2.carbon.apimgt.gateway.throttling.ThrottleDataHolder.isRequestBlocked_aroundBody54(ThrottleDataHolder.java:263) ~[org.wso2.carbon.apimgt.gateway_6.6.163.jar:?]
        at org.wso2.carbon.apimgt.gateway.throttling.ThrottleDataHolder.isRequestBlocked(ThrottleDataHolder.java:259) ~[org.wso2.carbon.apimgt.gateway_6.6.163.jar:?]
        at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doRoleBasedAccessThrottlingWithCEP_aroundBody0(ThrottleHandler.java:205) ~[org.wso2.carbon.apimgt.gateway_6.6.163.jar:?]
        at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doRoleBasedAccessThrottlingWithCEP(ThrottleHandler.java:144) ~[org.wso2.carbon.apimgt.gateway_6.6.163.jar:?]
        at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doThrottle_aroundBody12(ThrottleHandler.java:575) ~[org.wso2.carbon.apimgt.gateway_6.6.163.jar:?]
        at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doThrottle(ThrottleHandler.java:552) ~[org.wso2.carbon.apimgt.gateway_6.6.163.jar:?]
        at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.handleRequest_aroundBody8(ThrottleHandler.java:512) ~[org.wso2.carbon.apimgt.gateway_6.6.163.jar:?]
        at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.handleRequest(ThrottleHandler.java:498) ~[org.wso2.carbon.apimgt.gateway_6.6.163.jar:?]
        at org.apache.synapse.rest.API.process(API.java:367) ~[synapse-core_2.1.7.wso2v147.jar:2.1.7-wso2v147]
        at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149) ~[synapse-core_2.1.7.wso2v147.jar:2.1.7-wso2v147]
        at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95) ~[synapse-core_2.1.7.wso2v147.jar:2.1.7-wso2v147]
        at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71) ~[synapse-core_2.1.7.wso2v147.jar:2.1.7-wso2v147]
        at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:327) ~[synapse-core_2.1.7.wso2v147.jar:2.1.7-wso2v147]
        at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98) ~[synapse-core_2.1.7.wso2v147.jar:2.1.7-wso2v147]
        at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v41.jar:?]
        at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:368) [synapse-nhttp-transport_2.1.7.wso2v147.jar:?]
        at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:189) [synapse-nhttp-transport_2.1.7.wso2v147.jar:?]
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```
### Steps to reproduce:
 - Configure API Manager to use Identity Server 4 as an external Key Manager
 - Create a REST API in Publisher with a single operation with Unlimited throttling
 - Create an application in Dev Portal with Unlimited throttling
 - Generate an access token using the Dev Portal with grant_type = client_credentials
 - Subscribe to the API with the application (Unlimited throttling on th subscription too)
 - Try out the operation in Dev Portal after putting the access token in the Authorization header

I get an error "Failed to fetch data" in the UI and the stack trace above in the console.

### Affected Product Version:
API Manager 3.1.0-rc3

### Environment details (with versions):
- OS: Windows 10
- Client:
- Env (Docker/K8s):

**Comment by Jacobski-fr** [comment]
I've just found that the sub claim must be present in a JWT. See https://tools.ietf.org/html/rfc7523 :
```
2.   The JWT MUST contain a "sub" (subject) claim identifying the
        principal that is the subject of the JWT.  Two cases need to be
        differentiated:

        A.  For the authorization grant, the subject typically
            identifies an authorized accessor for which the access token
            is being requested (i.e., the resource owner or an
            authorized delegate), but in some cases, may be a
            pseudonymous identifier or other value denoting an anonymous
            user.

        B.  For client authentication, the subject MUST be the
            "client_id" of the OAuth client.
```

So I close this issue and open one in Identity Server 4.

**Comment by Jacobski-fr** [comment]
My bad. The RFC I quoted above seems to be about requesting an access token by using a JWT. So, it doesn't seem relevant in this case.
The RFC on JWT itself (https://tools.ietf.org/html/rfc7519#section-4.1.2) states that sub claim is optional. So I guess API Manager should not rely on it being present

**Comment by malinthaprasan** [comment]
Hi @Jacobski-fr 
It seems the token validation is hard-bound to the sub claim at the moment.
In WSO2, when we generate a JWT using client-credentials, we add the "sub" claim with the owner of the application. Is there any chance to add the sub claim in the IS4 side?

**Comment by Jacobski-fr** [comment]
Hello,
  There are some extension points in IS4 allowing to add this claim but I have to check how to do it without unwanted side-effect. I'm going to ask the IS4 team how to do it safely.

**Comment by Jacobski-fr** [comment]
Question https://github.com/IdentityServer/IdentityServer4/issues/4214 submitted to IS4 team.
