### ISSUE TITLE
Concurrent issue noticed during perf test

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#7834]
### Description:

Noticed a concurrent issue during the perf test in the GW node.

```
TID: [-1234] [] [2020-03-27 03:22:34,789] ERROR {org.apache.synapse.transport.passthru.ServerWorker} - Error processing GET request for : /sample/1.0.0/menu. java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList.sort(ArrayList.java:1751)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.initializeAuthenticators_aroundBody34(APIAuthenticationHandler.java:309)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.initializeAuthenticators(APIAuthenticationHandler.java:234)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest_aroundBody36(APIAuthenticationHandler.java:347)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest(APIAuthenticationHandler.java:320)
	at org.apache.synapse.rest.API.process(API.java:367)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:327)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:368)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:189)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Steps to reproduce:
Did perf test with 3000TPS using a JWT token.
APIM 3.1.0
Open JDK 11

**Comment by natechols** [comment]
I have also encountered this upon switching from APIM 2.0.0 to 3.2.0.  It only seems to happen when trying to access multiple API endpoints immediately after authenticating.  Usually it's just one request that chokes but I just saw it happen three times in a row.

**Comment by ruks** [comment]
Close since it is fixed
