### ISSUE TITLE
[APIM-3.1.0] Publisher issue on Publish API

### ISSUE THREAD

**Issue by jkirch57** [wso2/product-apim#7843]
### Description:
Hello, I'm having an error when trying to publish an API from the publisher. I'm in a distributed environment with the gateway / publisher / traffic-manager... on different server. I've deployed everything as I did with the Alpha but now I'm not able to publish an API. It looks like it's published when create and publisher at the creation but then when I demote and try to remote it's not working. Same issue if I create the API without publishing it at creation. You can find my log from the publisher server below in attachment.

[wso2carbon.log](https://github.com/wso2/product-apim/files/4395251/wso2carbon.log)

### Steps to reproduce:
Try to publish a created API in publisher

### Affected Product Version:
Version : 3.1.0 release

Regards,
Jérôme.

**Comment by tmkasun** [comment]
Hi J


```log
TID: [-1234] [] [2020-03-27 19:13:06,144] ERROR {org.wso2.carbon.apimgt.impl.APIGatewayManager} - Error occurred when publish to gateway Production and Sandbox org.apache.axis2.AxisFault: Error while Deploying API 
	at org.wso2.carbon.apimgt.impl.utils.APIGatewayAdminClient.deployAPI_aroundBody12(APIGatewayAdminClient.java:173)
	at org.wso2.carbon.apimgt.impl.utils.APIGatewayAdminClient.deployAPI(APIGatewayAdminClient.java:168)
	at org.wso2.carbon.apimgt.impl.APIGatewayManager.publishToGateway_aroundBody2(APIGatewayManager.java:216)
	at org.wso2.carbon.apimgt.impl.APIGatewayManager.publishToGateway(APIGatewayManager.java:104)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.publishToGateway_aroundBody94(APIProviderImpl.java:2037)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.publishToGateway(APIProviderImpl.java:2009)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.propergateAPIStatusChangeToGateways_aroundBody82(APIProviderImpl.java:1809)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.propergateAPIStatusChangeToGateways(APIProviderImpl.java:1775)
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.propergateAPIStatusChangeToGateways_aroundBody28(UserAwareAPIProvider.java:175)
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.propergateAPIStatusChangeToGateways(UserAwareAPIProvider.java:172)
	at org.wso2.carbon.apimgt.impl.executors.APIExecutor.changeLifeCycle_aroundBody4(APIExecutor.java:182)
	at org.wso2.carbon.apimgt.impl.executors.APIExecutor.changeLifeCycle(APIExecutor.java:150)
	at org.wso2.carbon.apimgt.impl.executors.APIExecutor.execute_aroundBody2(APIExecutor.java:128)
	at org.wso2.carbon.apimgt.impl.executors.APIExecutor.execute(APIExecutor.java:89)
	at org.wso2.carbon.governance.registry.extensions.aspects.DefaultLifeCycle.runCustomExecutorsCode(DefaultLifeCycle.java:712)
	at org.wso2.carbon.governance.registry.extensions.aspects.DefaultLifeCycle.invoke(DefaultLifeCycle.java:450)
	at org.wso2.carbon.governance.registry.eventing.handlers.GovernanceEventingHandler.invokeAspect(GovernanceEventingHandler.java:366)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.invokeAspect(HandlerManager.java:2794)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.invokeAspect(HandlerLifecycleManager.java:518)
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.invokeAspect(EmbeddedRegistry.java:2607)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.invokeAspect(CacheBackedRegistry.java:510)
	at org.wso2.carbon.registry.core.session.UserRegistry.invokeAspect(UserRegistry.java:1964)
	at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.invokeAction(GovernanceArtifactImpl.java:829)
	at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.invokeAction(GovernanceArtifactImpl.java:808)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.changeLifeCycleStatus_aroundBody242(APIProviderImpl.java:5140)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.changeLifeCycleStatus(APIProviderImpl.java:5067)
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.changeLifeCycleStatus_aroundBody74(UserAwareAPIProvider.java:339)
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.changeLifeCycleStatus(UserAwareAPIProvider.java:335)
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.apisChangeLifecyclePost(ApisApiServiceImpl.java:3696)
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.apisChangeLifecyclePost(ApisApi.java:818)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:75)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.axis2.AxisFault: java.io.IOException: Unexpected end of stream while reading request body
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:382)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:457)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.wso2.carbon.apimgt.gateway.stub.APIGatewayAdminStub.deployAPI(APIGatewayAdminStub.java:4705)
	at org.wso2.carbon.apimgt.impl.utils.APIGatewayAdminClient.deployAPI_aroundBody12(APIGatewayAdminClient.java:171)
	... 81 more
```

It seems like there is a connection issue with the Gateway node, Can you share the `deployment.toml` files with us

@tharindu1st , @Krishanx92  Is this a known issue in 3.1 ?

**Comment by tharindu1st** [comment]
Hi @jkirch57,
Is there any error log printed at the Gateway node corresponds to this time, Or could you please share us the wso2carbon.log of gateway node.

**Comment by jkirch57** [comment]
Hello @tharindu1st, @tmkasun,

I've no error on the gateway worker logs, i've tried with bothe gateway worker node up and only with each one only up. I've found that I can Publish my API from the Overview screen without any error, it works well, but if I try from the Lifecycle page I'm having the issue with the log I gave you...

I'm not sur my configuration file will help if it work from another menu, what do you think ?

Any idea ?

Regards,
Jérôme.

**Comment by jkirch57** [comment]
Hi again,

After another test, I detected that, now it's working randomly from the Lifecycle page. Sometimes it's working, sometimes not... Maybe we have a issue with our network somewhere :-(...

Regards,
Jérôme.

**Comment by jkirch57** [comment]
Hello again,

Another update, when I try to make mark an API as the default version after a publish, I'm facing the same issue than when i try to publish, it's working randomly... but when i've the error on the publisher (with the same log error like for the publish one), i've also an error log on the gateway, which are :

`TID: [-1234] [APIGatewayAdmin] [2020-03-30 09:21:05,007] ERROR {org.apache.axis2.rpc.receivers.RPCMessageReceiver} - [com.ctc.wstx.exc.WstxLazyException] java.io.IOException: Invalid end of line sequence (no data available to read) [com.ctc.wstx.exc.WstxLazyException] com.ctc.wstx.exc.WstxIOException: java.io.IOException: Invalid end of line sequence (no data available to read)
        at com.ctc.wstx.exc.WstxLazyException.throwLazily(WstxLazyException.java:45)
        at com.ctc.wstx.sr.StreamScanner.throwLazyError(StreamScanner.java:720)
        at com.ctc.wstx.sr.BasicStreamReader.safeFinishToken(BasicStreamReader.java:3677)
        at com.ctc.wstx.sr.BasicStreamReader.getText(BasicStreamReader.java:858)
        at org.apache.axiom.util.stax.wrapper.XMLStreamReaderWrapper.getText(XMLStreamReaderWrapper.java:164)
        at org.apache.axiom.om.impl.builder.StAXBuilder.createOMText(StAXBuilder.java:289)
        at org.apache.axiom.om.impl.builder.StAXBuilder.createOMText(StAXBuilder.java:250)
        at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:252)
        at org.apache.axiom.om.impl.llom.OMElementImpl.buildNext(OMElementImpl.java:653)
        at org.apache.axiom.om.impl.llom.OMElementImpl.getFirstOMChild(OMElementImpl.java:670)
        at org.apache.axiom.om.impl.llom.OMElementImpl.getText(OMElementImpl.java:785)
        at org.apache.axis2.databinding.typemapping.SimpleTypeMapper.getSimpleTypeObject(SimpleTypeMapper.java:77)
        at org.apache.axis2.databinding.utils.BeanUtil.deserialize(BeanUtil.java:482)
        at org.apache.axis2.databinding.utils.BeanUtil.processObject(BeanUtil.java:852)
        at org.apache.axis2.databinding.utils.BeanUtil.ProcessElement(BeanUtil.java:771)
        at org.apache.axis2.databinding.utils.BeanUtil.deserialize(BeanUtil.java:680)
        at org.apache.axis2.rpc.receivers.RPCUtil.processRequest(RPCUtil.java:153)
        at org.apache.axis2.rpc.receivers.RPCUtil.invokeServiceClass(RPCUtil.java:206)
        at org.apache.axis2.rpc.receivers.RPCMessageReceiver.invokeBusinessLogic(RPCMessageReceiver.java:117)
        at org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:40)
        at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
        at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
        at org.apache.axis2.transport.http.HTTPTransportUtils.processHTTPPostRequest(HTTPTransportUtils.java:173)
        at org.apache.axis2.transport.http.AxisServlet.doPost(AxisServlet.java:148)
        at org.wso2.carbon.core.transports.CarbonServlet.doPost(CarbonServlet.java:238)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86)
        at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
        at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:75)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
        at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.ctc.wstx.exc.WstxIOException: java.io.IOException: Invalid end of line sequence (no data available to read)
        at com.ctc.wstx.sr.StreamScanner.constructFromIOE(StreamScanner.java:625)
        at com.ctc.wstx.sr.StreamScanner.loadMore(StreamScanner.java:997)
        at com.ctc.wstx.sr.BasicStreamReader.readTextSecondary(BasicStreamReader.java:4647)
        at com.ctc.wstx.sr.BasicStreamReader.readCoalescedText(BasicStreamReader.java:4147)
        at com.ctc.wstx.sr.BasicStreamReader.finishToken(BasicStreamReader.java:3719)
        at com.ctc.wstx.sr.BasicStreamReader.safeFinishToken(BasicStreamReader.java:3675)
        ... 72 more
Caused by: org.apache.catalina.connector.ClientAbortException: java.io.IOException: Invalid end of line sequence (no data available to read)
        at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:340)
        at org.apache.catalina.connector.InputBuffer.checkByteBufferEof(InputBuffer.java:632)
        at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:362)
        at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:132)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
        at org.apache.axiom.om.util.DetachableInputStream.read(DetachableInputStream.java:147)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
        at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:183)
        at com.ctc.wstx.io.BaseReader.readBytes(BaseReader.java:155)
        at com.ctc.wstx.io.UTF8Reader.loadMore(UTF8Reader.java:368)
        at com.ctc.wstx.io.UTF8Reader.read(UTF8Reader.java:111)
        at com.ctc.wstx.io.MergedReader.read(MergedReader.java:105)
        at com.ctc.wstx.io.ReaderSource.readInto(ReaderSource.java:87)
        at com.ctc.wstx.io.BranchingReaderSource.readInto(BranchingReaderSource.java:57)
        at com.ctc.wstx.sr.StreamScanner.loadMore(StreamScanner.java:991)
        ... 76 more
Caused by: java.io.IOException: Invalid end of line sequence (no data available to read)
        at org.apache.coyote.http11.filters.ChunkedInputFilter.throwIOException(ChunkedInputFilter.java:597)
        at org.apache.coyote.http11.filters.ChunkedInputFilter.parseCRLF(ChunkedInputFilter.java:399)
        at org.apache.coyote.http11.filters.ChunkedInputFilter.doRead(ChunkedInputFilter.java:160)
        at org.apache.coyote.http11.Http11InputBuffer.doRead(Http11InputBuffer.java:247)
        at org.apache.coyote.Request.doRead(Request.java:551)
        at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:336)
        ... 93 more

TID: [-1234] [AuthenticationAdmin] [2020-03-30 09:21:05,094]  INFO {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} - 'wso2admin@carbon.super [-1234]' logged in at [2020-03-30 09:21:05,094+0200]
`

**Comment by jkirch57** [comment]
I'm sorry to overflood this issue, but something more strange i've discovered, I was able to publish an API after x retry with success in the Front page point of view, but with nothing on the gateway log (no error, no success trace of the publish)... after a check in the [WSO2_INSTALLATION]/repository/deployment/server/synapse-configs/default/api/ the API  isn't deployed... but on the publisher front, it's marked as deployed.

I've tried again, create a new API then update resources, try to deploy, with error and after x retry same behavior... (with only one gateway node active). I deleted the API, then try to Create and Publish directly and it worked. For the server folder we have a NFS share to share it with both node... now I can try without the share to check if it's coming from there.

**Comment by jkirch57** [comment]
Hello @tharindu1st, @tmkasun,

As you said it's a connection issue with the Gateway. I've moved the gateway on the publisher server, change the publisher configuration to adapt the gateway configuration for local, and then it worked.

I'll check with out with our network team what's the problem. It looks like something change since the 3.1.0 RC because I do not have this kind of issue when I start back the Alpha and I saw that there is difference with port on listen. So maybe our network team should adapt our FW...

Sorry for the disturb.

**Comment by mounirloubari** [comment]
Hello @tharindu1st @tmkasun ,

did you change some thing in 3.2.0-M1 ( patches, ... ) to overcome this behaviour because actually we are still facing difficulties in publishing API's updates to gateway.

PS: we are in distributed architecture with rsync deployment synchronisation, where every module is deployed in different virtual machine.

**Comment by Arshardh** [comment]
In the latest APIM version (4.0.0) we do not use the file system to deploy these artifacts, which mitigates all these issues.

**Comment by mounirloubari** [comment]
Yes i understand,  but for moment do you have any solution to bypass this issue in wso2 3.1.0 ? because migration to 4.0.0 we will do it later.

**Comment by tmkasun** [comment]
Hi @mounirloubari ,

You have to check the gateway service URL in deployment.toml.

Are you using a load balancer?

This error occurs when the publisher node could connect the gateway environment properly. So it could be a load balancer issue 

Check ✅ 
- Connectivity between the publisher node and the gateway services. You can telnet the internal gateway service URL from the publisher node.
   - can use a tool like `nslookup` from the publisher node
- If using an LB Try skipping the LB and deploying an API to the gateway.

**Comment by mounirloubari** [comment]
Hi @tmkasun
I checked without passing by LB and it works , but when I switch to LB i have this log in addition of "unexpected end of stream while reading request body" ( discussed before ) in gateway side:

**TID: [-1234] [APIGatewayAdmin] [2021-12-31 15:11:03,343] ERROR {org.wso2.carbon.statistics.internal.ResponseTimeCalculator} - wso2statistics.request.received.time is null in the IN MessageContex**

If you have any idea i will appreciate it.
