### ISSUE TITLE
wso2am-analytics-3.0.0 Error:java.security.cert.CertificateException:No subject alternative names matching IP address<IP Address> found executing POST

### ISSUE THREAD

**Issue by chkishorebabu** [wso2/product-apim#7856]
I have downloaded wso2am-analytics-3.0.0 and installed it in Linux instance. 
I am facing an issue when logging into WSO analytics dashboard after I have configured the self signed certificate in the Analytics instance. Issue is related to : java.security.cert.CertificateException: No subject alternative names matching IP address found executing POST Below is the stacktrace of the issue:

ERROR {org.wso2.carbon.analytics.auth.rest.api.impl.LoginApiServiceImpl} - Error occurred: java.security.cert.CertificateException: No subject alternative names matching IP address <IP Address> found executing POST https://<IP Address>:9443/oauth2/token feign.RetryableException: java.security.cert.CertificateException: No subject alternative names matching IP address <IP Address> found executing POST https://<IP Address>:9443/oauth2/token
        at feign.FeignException.errorExecuting(FeignException.java:67)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:104)
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
        at com.sun.proxy.$Proxy83.generateAccessToken(Unknown Source)
        at org.wso2.carbon.analytics.idp.client.external.impl.OAuth2ServiceStubs$TokenServiceStub.generateAuthCodeGrantAccessToken(OAuth2ServiceStubs.java:157)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
        at feign.DefaultMethodHandler.invoke(DefaultMethodHandler.java:60)
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
        at com.sun.proxy.$Proxy83.generateAuthCodeGrantAccessToken(Unknown Source)
        at org.wso2.analytics.apim.idp.client.ApimIdPClient.authCodeLogin(ApimIdPClient.java:470)
        at org.wso2.carbon.analytics.auth.rest.api.impl.LoginApiServiceImpl.loginCallbackAppNameGet(LoginApiServiceImpl.java:257)
        at org.wso2.carbon.analytics.auth.rest.api.LoginApi.loginCallbackAppNameGet(LoginApi.java:105)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
        at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
        at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
        at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$57(MSF4JHttpConnectorListener.java:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative names matching IP address <IP Address> found
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
        at feign.Client$Default.convertAndSend(Client.java:133)
        at feign.Client$Default.execute(Client.java:73)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)
        ... 22 more
Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address <IP Address> found
        at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:168)
        at sun.security.util.HostnameChecker.match(HostnameChecker.java:94)
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:200)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
        ... 37 more

**Comment by vfbaldovin** [comment]
Hello. Kindly tell me if you have solved this problem?

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
