### ISSUE TITLE
Importing a SOAP API via Admin /import-api doesn't store the WSDL

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#7862]
### Description:
1. Create a SOAP API
2. Download the API
3. Delete the created API
4. Reimport using the Admin REST API (/import-api)

Check the WSDL-Definition page, shows the below:

![image](https://user-images.githubusercontent.com/1591316/78162707-e07c1000-7464-11ea-8af6-c0761e163fc2.png)

Try to download the WSDL from the devportal in the API. It is failing with below error in the server terminal.

```
[2020-04-01 22:04:55,922] ERROR - GlobalThrowableMapper A defined exception has been captured and mapped to an HTTP response by the global exception mapper 
org.wso2.carbon.apimgt.api.APIManagementException: No WSDL found for the API: admin-stockSOAP-1.0.2
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getWSDL_aroundBody58(AbstractAPIManager.java:1119) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getWSDL(AbstractAPIManager.java:1087) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getWSDL_aroundBody234(APIConsumerImpl.java:5152) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getWSDL(APIConsumerImpl.java:5149) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApisApiServiceImpl.getWSDLOfAPI(ApisApiServiceImpl.java:845) ~[classes/:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.ApisApi.getWSDLOfAPI(ApisApi.java:378) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
```

**Comment by wasuradananjith** [comment]
I checked with different types of users, but both downloading/exporting and importing worked as expected.
