### ISSUE TITLE
Message Mediation Policies (xml_validator and json_validator) and Global Mediation Extensions with FULL log cannot be used at the same time

### ISSUE THREAD

**Issue by riyazathali** [wso2/product-apim#7866]
### Description:
When we use the global custom sequence which includes the log mediator(**level full**) and with the Message Mediation Policies (xml_validator and json_validator) the validation is not working for both scenario.
For the XML scenario, we are getting the following error message.
```
ERROR - XMLSchemaValidator Bad Request
org.wso2.carbon.apimgt.gateway.threatprotection.APIMThreatAnalyzerException: XML Validation Failed: due to Unexpected EOF in prolog
 at [row,col {unknown-source}]: [1,0]
	at org.wso2.carbon.apimgt.gateway.threatprotection.analyzer.XMLAnalyzer.analyze(XMLAnalyzer.java:99)
	at org.wso2.carbon.apimgt.gateway.mediators.XMLSchemaValidator.mediate(XMLSchemaValidator.java:104)
	at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:93)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.mediate(APIManagerExtensionHandler.java:66)
	at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleRequest(APIManagerExtensionHandler.java:75)
	at org.apache.synapse.rest.API.process(API.java:325)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:90)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:303)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:92)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:337)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:383)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
For the JSON scenario, there is no error like the above But the JSON schema validation is not working when we use log full in the global in-sequence.
### Steps to reproduce:
1. Add a Global sequence with a log full mediator.
2. Add the xml_validator in the custom in_seqence of the API(to test the XML scenario) and Add the json_validator in the custom in_sequence(To test the JSON scenario).
3. Change the 'maxElementCount=10' in the custom xml _validator in sequence or Change **MaxPropertyCount** to 3  in json_validator(These are for example validation configuration)
4. Create a payload with the POST request and check the scenario. (To verify, change the log level to custom it will wok without any issues.)

### Affected Product Version:
APIM 2.5.0

**Comment by kavishkafernando** [comment]
public fix PR: #https://github.com/wso2/carbon-apimgt/pull/8413
