### ISSUE TITLE
Invalid arguments when setting sso configuration values APIM 2.0.0

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-apim#7925]
Description:
After configuring SAML SSO APIM publisher and store, the following error occurred while trying to access the publisher.

`Caused by: org.mozilla.javascript.WrappedException: Wrapped javax.script.ScriptException: Invalid arguments when setting sso configuration values. (/publisher/site/themes/wso2/templates/sso/filter/template.jag#50)
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
        at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
        at org.jaggeryjs.rhino.publisher.site.themes.wso_2.templates.sso.filter.c0._c_anonymous_1(/publisher/site/themes/wso2/templates/sso/filter/template.jag:50)
        at org.jaggeryjs.rhino.publisher.site.themes.wso_2.templates.sso.filter.c0.call(/publisher/site/themes/wso2/templates/sso/filter/template.jag)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at org.jaggeryjs.rhino.publisher.jagg.c0._c_anonymous_31(/publisher/jagg/jagg.jag:197)
        at org.jaggeryjs.rhino.publisher.jagg.c0.call(/publisher/jagg/jagg.jag)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
        at org.jaggeryjs.rhino.publisher.jagg.c0._c_anonymous_55(/publisher/jagg/jagg.jag:602)
        at org.jaggeryjs.rhino.publisher.jagg.c0.call(/publisher/jagg/jagg.jag)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
        at org.jaggeryjs.rhino.publisher.site.pages.c1._c_script_0(/publisher/site/pages/header.jag:11)
        at org.jaggeryjs.rhino.publisher.site.pages.c1.call(/publisher/site/pages/header.jag)
        at org.jaggeryjs.rhino.publisher.site.pages.c1.exec(/publisher/site/pages/header.jag)
        at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
        ... 59 more
Caused by: javax.script.ScriptException: Invalid arguments when setting sso configuration values.
        at org.wso2.carbon.hostobjects.sso.SAMLSSORelyingPartyObject.jsFunction_setProperty(SAMLSSORelyingPartyObject.java:655)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
        ... 74 more`

The issue occurred because in the template.jag trying to set  assertionEncryptionEnabled property as follows

ssoRelyingParty.setProperty("assertionEncryptionEnabled", site.ssoConfiguration.assertionEncryptionEnabled);

If the above property not set in site.json this error occurred.

**Comment by Krishanx92** [comment]
This issue no longer valid with latest now hence closing
