### ISSUE TITLE
[APIM][3.1.0] Error after database configuration removed in deployment.toml of Gateway Node 

### ISSUE THREAD

**Issue by chaliya96** [wso2/product-apim#7976]
### Description:
In a fully distributed setup, APIM server is not starting when database connection is removed from gateway node by removing database configuration in deployment.toml. As per the implementation APIM gateway node should run without connecting to the database when multi-tenancy is not used

### Steps to reproduce:

- Remove [shared_db] configuration from deployment.toml.
- Start APIM server using the gateway profile

The following error log will be observed.

> [2020-04-30 15:36:19,995]  WARN {org.wso2.config.mapper.ConfigParser} - Configurations Changed in :repository/conf/deployment.toml
[2020-04-30 15:36:19,998]  WARN {org.wso2.config.mapper.ConfigParser} - Overriding files in configuration directory /home/chalith/Music/3.1.0
[2020-04-30 15:36:20,272]  SEVERE {org.wso2.carbon.server.Main handleConfiguration} - Error while performing configuration changes 
org.wso2.config.mapper.ConfigParserException: Configuration with key database.shared_db.username doesn't exist
	at org.wso2.config.mapper.ReferenceResolver.resolvePropertyPlaceholders(ReferenceResolver.java:288)
	at org.wso2.config.mapper.ReferenceResolver.resolveConfigReferences(ReferenceResolver.java:124)
	at org.wso2.config.mapper.ReferenceResolver.resolve(ReferenceResolver.java:91)
	at org.wso2.config.mapper.ReferenceResolver.resolve(ReferenceResolver.java:71)
	at org.wso2.config.mapper.ConfigParser.parse(ConfigParser.java:253)
	at org.wso2.config.mapper.ConfigParser.deploy(ConfigParser.java:217)
	at org.wso2.config.mapper.ConfigParser.deployAndStoreMetadata(ConfigParser.java:180)
	at org.wso2.config.mapper.ConfigParser.parse(ConfigParser.java:127)
	at org.wso2.carbon.server.Main.handleConfiguration(Main.java:231)
	at org.wso2.carbon.server.Main.main(Main.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.bootstrap.Bootstrap.loadClass(Bootstrap.java:70)
	at org.wso2.carbon.bootstrap.Bootstrap.main(Bootstrap.java:51)

  
### Affected Product Version:
WSO2 API manager 3.1.0.

---

**Comment by Krishanx92** [comment]
Added a note in a doc: https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m/
