### ISSUE TITLE
In WSO2 API Management(2.1.0) getting Error in  tenant activation status 

### ISSUE THREAD

**Issue by prasad-repository** [wso2/product-apim#8030]
We have multiple tenant in Single Server, after running API Management server for 2 days we are getting Error while getting tenant activation status , I'm able to see following exception

Error when loading tenant before executing the task. {org.wso2.carbon.mediation.ntask.internal.NtaskService}
java.lang.RuntimeException: Error while getting tenant activation status.
        at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.getTenantConfigurationContext(TenantAxisUtils.java:126)
        at org.wso2.carbon.mediation.ntask.internal.NtaskService.loadTenant(NtaskService.java:160)
        at org.wso2.carbon.mediation.ntask.NTaskAdapter.checkLoadTenant(NTaskAdapter.java:107)
        at org.wso2.carbon.mediation.ntask.NTaskAdapter.init(NTaskAdapter.java:60)
        at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:66)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.user.core.UserStoreException: Error while building user store manager from file
        at org.wso2.carbon.user.core.config.UserStoreConfigXMLProcessor.buildUserStoreConfigurationFromFile(UserStoreConfigXMLProcessor.java:127)
        at org.wso2.carbon.user.core.common.UserStoreDeploymentManager.getUserStoreConfiguration(UserStoreDeploymentManager.java:183)
        at org.wso2.carbon.user.core.tenant.JDBCTenantManager.setSecondaryUserStoreConfig(JDBCTenantManager.java:710)
        at org.wso2.carbon.user.core.tenant.JDBCTenantManager.getTenant(JDBCTenantManager.java:333)
        at org.wso2.carbon.user.core.tenant.JDBCTenantManager.isTenantActive(JDBCTenantManager.java:600)
        at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.getTenantConfigurationContext(TenantAxisUtils.java:123)
        ... 10 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: too much data for RSA block
        at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineDoFinal(Unknown Source)
        at javax.crypto.Cipher.doFinal(Cipher.java:2165)
        at org.wso2.carbon.user.core.config.UserStoreConfigXMLProcessor.resolveEncryption(UserStoreConfigXMLProcessor.java:319)
        at org.wso2.carbon.user.core.config.UserStoreConfigXMLProcessor.getChildPropertyElements(UserStoreConfigXMLProcessor.java:235)
        at org.wso2.carbon.user.core.config.UserStoreConfigXMLProcessor.buildUserStoreConfiguration(UserStoreConfigXMLProcessor.java:146)
        at org.wso2.carbon.user.core.config.UserStoreConfigXMLProcessor.buildUserStoreConfigurationFromFile(UserStoreConfigXMLProcessor.java:121)
        ... 15 more
TID: [1] [] [2020-05-11 12:21:04,565] @iccc-mp.com [1] [AM]ERROR {org.wso2.carbon.registry.core.session.UserRegistry} -  An error occurred while obtaining the user realm for the tenant: 1. {org.wso2.carbon.registry.core.session.UserRegistry}
TID: [1] [] [2020-05-11 12:21:04,565] @iccc-mp.com [1] [AM] WARN {org.wso2.carbon.registry.indexing.ResourceSubmitter} -  Unable to submit resource for tenant 1. Unable to get registry instance {org.wso2.carbon.registry.indexing.ResourceSubmitter}
TID: [2] [] [2020-05-11 12:21:04,624] @bhopal.com [2] [AM]ERROR {org.wso2.carbon.registry.core.session.UserRegistry} -  An error occurred while obtaining the user realm for the tenant: 2. {org.wso2.carbon.registry.core.session.UserRegistry}
TID: [2] [] [2020-05-11 12:21:04,624] @bhopal.com [2] [AM] WARN {org.wso2.carbon.registry.indexing.ResourceSubmitter} -  Unable to submit resource for tenant 2. Unable to get registry instance {org.wso2.carbon.registry.indexing.ResourceSubmitter}

After Causing this Exception, unable to generate Access Token and Could not able to login tenent and even API store is  also not loading properly
If we restart the API Management it will work for 2 days after that same issue repeats
Any Suggestion Appreciable..

**Comment by gabrielpolo** [comment]
Is there any update for this scenario?
