### ISSUE TITLE
[2.6] Cannot create API using WSDL file

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#8063]
### Description:
The issue occurs in latest wum updated 2.6 distribution (timestamp: 1588873471478). We cannot create a SOAP API using a WSDL file itself, getting the following.

```
TID: [-1234] [] [2020-05-14 11:30:34,848] ERROR {org.wso2.carbon.apimgt.impl.utils.APIFileUtil} -  Failed to extract archive file: /home/dushaniw/Support/2.6/CLOUDPROD-1440/wso2am-2.6.0/tmp/WSDL-archives/ee3e8064-67a8-4dad-be8b-b512b987a5ec/wsdl-archive.zip to destination: /home/dushaniw/Support/2.6/CLOUDPROD-1440/wso2am-2.6.0/tmp/WSDL-archives/ee3e8064-67a8-4dad-be8b-b512b987a5ec/extracted {org.wso2.carbon.apimgt.impl.utils.APIFileUtil}
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.wso2.carbon.apimgt.impl.utils.APIFileUtil.extractArchive_aroundBody8(APIFileUtil.java:132)
	at org.wso2.carbon.apimgt.impl.utils.APIFileUtil.extractArchive(APIFileUtil.java:128)
	at org.wso2.carbon.apimgt.impl.utils.APIFileUtil.extractUploadedArchive_aroundBody0(APIFileUtil.java:59)
	at org.wso2.carbon.apimgt.impl.utils.APIFileUtil.extractUploadedArchive(APIFileUtil.java:49)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.extractAndValidateWSDLArchive_aroundBody72(APIUtil.java:1732)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.extractAndValidateWSDLArchive(APIUtil.java:1727)
	at org.wso2.carbon.apimgt.hostobjects.APIProviderHostObject.jsFunction_extractAndGetPath(APIProviderHostObject.java:1069)
...
	at java.lang.Thread.run(Thread.java:748)
TID: [-1234] [] [2020-05-14 11:30:34,857] ERROR {org.wso2.carbon.apimgt.impl.utils.APIFileUtil} -  Error in accessing uploaded API archive {org.wso2.carbon.apimgt.impl.utils.APIFileUtil}
org.wso2.carbon.apimgt.api.APIManagementException: Failed to extract archive file: /home/dushaniw/Support/2.6/CLOUDPROD-1440/wso2am-2.6.0/tmp/WSDL-archives/ee3e8064-67a8-4dad-be8b-b512b987a5ec/wsdl-archive.zip to destination: /home/dushaniw/Support/2.6/CLOUDPROD-1440/wso2am-2.6.0/tmp/WSDL-archives/ee3e8064-67a8-4dad-be8b-b512b987a5ec/extracted
	at org.wso2.carbon.apimgt.impl.utils.APIFileUtil.extractArchive_aroundBody8(APIFileUtil.java:173)
	at org.wso2.carbon.apimgt.impl.utils.APIFileUtil.extractArchive(APIFileUtil.java:128)
	at org.wso2.carbon.apimgt.impl.utils.APIFileUtil.extractUploadedArchive_aroundBody0(APIFileUtil.java:59)
	at org.wso2.carbon.apimgt.impl.utils.APIFileUtil.extractUploadedArchive(APIFileUtil.java:49)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.extractAndValidateWSDLArchive_aroundBody72(APIUtil.java:1732)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.extractAndValidateWSDLArchive(APIUtil.java:1727)
	at org.wso2.carbon.apimgt.hostobjects.APIProviderHostObject.jsFunction_extractAndGetPath(APIProviderHostObject.java:1069)
...
        at
org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0._c_anonymous_6(/publisher/site/blocks/item-design/ajax/add.jag:221)
	at org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0.call(/publisher/site/blocks/item-design/ajax/add.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
	at org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0._c_script_0(/publisher/site/blocks/item-design/ajax/add.jag:59)
	at org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0.call(/publisher/site/blocks/item-design/ajax/add.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0.call(/publisher/site/blocks/item-design/ajax/add.jag)
	at org.jaggeryjs.rhino.publisher.site.blocks.item_design.ajax.c0.exec(/publisher/site/blocks/item-design/ajax/add.jag)
...
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.wso2.carbon.apimgt.impl.utils.APIFileUtil.extractArchive_aroundBody8(APIFileUtil.java:132)
	... 80 more
```

As a workaround, we can compress the WSDL as a zip file and create the API.

### Steps to reproduce:
1. Create a SOAP Passthrough API using a WSDL file.

### Affected Product Version:
2.6 WUM

**Comment by dushaniw** [comment]
Fixed in latest wum 2.6
