### ISSUE TITLE
Forgot password link not working on developer Portal

### ISSUE THREAD

**Issue by kalevivek11** [wso2/product-apim#8162]
Hi,
I am using version APIM 3.0.0 
we have done the distributed setup, on developer portal login page, forgot password link not working

see the logs:

 ERROR - [jsp] Servlet.service() for servlet [jsp] threw exception

[2020-05-27 04:40:33,158] ERROR - [jsp] Servlet.service() for servlet [jsp] threw exception



10:10:33

java.net.URISyntaxException: Illegal character in query at index 307: https://km.ecosystem-a2.posti.fi:443/authenticationendpoint/login.do?client_id=dfIZaE88SfUtzp8hraDYTg0qHxEa&commonAuthCallerPath=/oauth2/authorize&forceAuth=false&passiveAuth=false&redirect_uri=https://portal.ecosystem-a2.posti.fi/devportal/services/auth/callback/login&response_type=code&scope=apim:api_key apim:app_manage apim:a

java.net.URISyntaxException: Illegal character in query at index 307: https://km.ecosystem-a2.posti.fi:443/authenticationendpoint/login.do?client_id=dfIZaE88SfUtzp8hraDYTg0qHxEa&commonAuthCallerPath=/oauth2/authorize&forceAuth=false&passiveAuth=false&redirect_uri=https://portal.ecosystem-a2.posti.fi/devportal/services/auth/callback/login&response_type=code&scope=apim:api_key apim:app_manage apim:app_update apim:dedicated_gateway apim:self-signup apim:store_settings apim:sub_alert_manage apim:sub_manage apim:subscribe openid&state=/home&tenantDomain=carbon.super&sessionDataKey=ea8903d9-8f0d-48c1-b27d-c5d103a25aae&relyingParty=dfIZaE88SfUtzp8hraDYTg0qHxEa&type=oidc&sp=admin-AT-wso2.com_admin_external_store&isSaaSApp=true&authenticators=BasicAuthenticator:LOCAL



10:10:33

at java.net.URI$Parser.fail(URI.java:2848) ~[?:1.8.0_222]



10:10:33

at java.net.URI$Parser.checkChars(URI.java:3021) ~[?:1.8.0_222]



10:10:33

at java.net.URI$Parser.parseHierarchical(URI.java:3111) ~[?:1.8.0_222]



10:10:33

at java.net.URI$Parser.parse(URI.java:3053) ~[?:1.8.0_222]



10:10:33

at java.net.URI.<init>(URI.java:588) ~[?:1.8.0_222]



10:10:33

at org.wso2.carbon.identity.mgt.endpoint.IdentityManagementEndpointUtil.getURLEncodedCallback(IdentityManagementEndpointUtil.java:467) ~[classes/:?]



10:10:33

at org.apache.jsp.password_002drecovery_jsp._jspService(password_002drecovery_jsp.java:488) ~[?:?]



10:10:33

at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-servlet-api_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476) ~[tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) ~[tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) ~[tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-servlet-api_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.jsp.account_002drecovery_002drouter_jsp._jspService(account_002drecovery_002drouter_jsp.java:138) [accountrecoveryendpoint/:?]



10:10:33

at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53) [org.wso2.carbon.ui_4.5.1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80) [org.wso2.carbon.identity.context.rewrite.valve_1.3.6.jar:?]



10:10:33

at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100) [org.wso2.carbon.identity.authz.valve_1.3.6.jar:?]



10:10:33

at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74) [org.wso2.carbon.identity.auth.valve_1.3.6.jar:?]



10:10:33

at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]



10:10:33

at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]



10:10:33

at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]



10:10:33

at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]



10:10:33

at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]



10:10:33

at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:116) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]



10:10:33

at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]



10:10:33

at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]



10:10:33

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]



10:10:33

at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.22.wso2v1.jar:?]



10:10:33

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]



10:10:33

[2020-05-27 04:40:33,162] ERROR - do] Servlet.service() for servlet [recoveraccountrouter.do] in context with path [/accountrecoveryendpoint] threw exception [An exception occurred processing [password-recovery.jsp] at line [226]



10:10:33

223: <td>&nbsp;&nbsp;</td>



10:10:33

224: <td>



10:10:33

225: <button type="button" id="recoveryCancel" class="wr-btn grey-bg col-xs-12 col-md-12 col-lg-12 uppercase font-extra-large"



10:10:33

226: onclick="location.href='<%=Encode.forJavaScript(IdentityManagementEndpointUtil.getURLEncodedCallback(callback))%>';">



10:10:33

227: <%=IdentityManagementEndpointUtil.i18n(recoveryResourceBundle, "Cancel")%>



10:10:33

228: </button>



10:10:33

229: </td>



10:10:33

Stacktrace:] with root cause

**Comment by kalevivek11** [comment]
i think issue is due to space after "scope=apim:api_key"

**Comment by kalevivek11** [comment]
@dushaniw can you confirm and accept this bug?
