### ISSUE TITLE
[APIM][2.6.0] Issue in user role permission with message tracing option and IDP list

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/product-apim#8205]
### Steps to reproduce:
1. If a new user role is created and assigned with the permission, All Permissions->Admin Permissions->Configure, for the user who is having only this role can view 'message tracing' option in configure section in the management console. But when we click on that, below exception was observed in the console.
`
Caused by: java.lang.NullPointerException at org.apache.jsp.bampubsvcstat.configure_005fmessage_005ftracing_jsp._jspService(configure_005fmessage_005ftracing_jsp.java:241) at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:472) ... 115 more [2020-05-27 12:29:16,784] ERROR - RoleSecurityTagSupport IO Error executing tag: JSPException while including path '/bampubsvcstat/configure_message_tracing.jsp'. ServletException while including page. java.io.IOException: JSPException while including path '/bampubsvcstat/configure_message_tracing.jsp'. ServletException while including page. at org.apache.tiles.jsp.context.JspTilesRequestContext.include(JspTilesRequestContext.java:91) at org.apache.tiles.jsp.context.JspTilesRequestContext.dispatch(JspTilesRequestContext.java:82) at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:465)
`
2. There is no option to select in role permission for the user to have view-only IDP list permission level. If we assign All Permissions->Admin Permissions->Manage-Identity->Identity Provider Management, the user can view and modify the IDP list.

### Affected Product Version:
Affected/2.6.0

#### Suggested Labels:
WUM,Priority/Normal,Type/Bug,Affected/2.6.0

**Comment by RAVEENSR** [comment]
This is fixed in 2.6.0
