### ISSUE TITLE
[APIM 2.6.0] Throttling error when IPv6 address is used

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/product-apim#8216]
### Description:

```
Exception in thread "pool-146-thread-1" java.lang.NumberFormatException: For input string: "2001:0db8:85a3:0000:0000:8a2e:0370:7334"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.ipToLong_aroundBody440(APIUtil.java:7011)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.ipToLong(APIUtil.java:7007)
	at org.wso2.carbon.apimgt.gateway.throttling.publisher.DataProcessAndPublishingAgent.run_aroundBody4(DataProcessAndPublishingAgent.java:169)
	at org.wso2.carbon.apimgt.gateway.throttling.publisher.DataProcessAndPublishingAgent.run(DataProcessAndPublishingAgent.java:155)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce:
Invoke an API using IPv6 address.
### Affected Product Version:

APIM 2.6.0

**Comment by Sarangan0219** [comment]
Closing this as this was fixed in master.
