### ISSUE TITLE
Application Import is not working

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#8358]
### Description:

Getting the below exception when importing an application using APICTL.

```
apictl import-app -f app1.zip --update -e dev --skipKeys --skipSubscriptions
```

```
[2020-06-16 10:11:21,334] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.api.model.Application.getOAuthApp(Application.java:156) ~[org.wso2.carbon.apimgt.api_6.6.251.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.admin.v1.impl.ImportApiServiceImpl.importApplicationsPost(ImportApiServiceImpl.java:229) ~[classes/:?]
	at org.wso2.carbon.apimgt.rest.api.admin.v1.ImportApi.importApplicationsPost(ImportApi.java:94) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

```

```
    public Map<String, OAuthApplicationInfo> getOAuthApp(String keyType) {
        return keyManagerWiseOAuthApp.get(keyType);   //keyManagerWiseOAuthApp becomes null
    }

```

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by chathuranga95** [comment]
This is not reproducible on a latest pack (APIM 3.2.0) with `apictl-3.1.3` tool.
Environment: Linux x64
![app import sucess](https://user-images.githubusercontent.com/25490163/86094268-ecac5380-bacd-11ea-9588-ff9832544ccd.png)

**Comment by Arshardh** [comment]
Closing issue as this is not reproduced in the latest pack.
