### ISSUE TITLE
Error while running apictl import-api 

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#8373]
### Description:
Below Error is logged when trying to import an API using apictl
```
[2020-06-17 09:54:25,932] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.validateKeyManagers_aroundBody78(APIProviderImpl.java:1543) ~[org.wso2.carbon.apimgt.impl_6.7.10.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.validateKeyManagers(APIProviderImpl.java:1538) ~[org.wso2.carbon.apimgt.impl_6.7.10.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPI_aroundBody46(APIProviderImpl.java:802) ~[org.wso2.carbon.apimgt.impl_6.7.10.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPI(APIProviderImpl.java:797) ~[org.wso2.carbon.apimgt.impl_6.7.10.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addAPI_aroundBody0(UserAwareAPIProvider.java:81) ~[org.wso2.carbon.apimgt.impl_6.7.10.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addAPI(UserAwareAPIProvider.java:79) ~[org.wso2.carbon.apimgt.impl_6.7.10.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.utils.APIImportUtil.importAPI_aroundBody2(APIImportUtil.java:259) ~[org.wso2.carbon.apimgt.impl_6.7.10.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.utils.APIImportUtil.importAPI(APIImportUtil.java:114) ~[org.wso2.carbon.apimgt.impl_6.7.10.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.APIImportExportManager.importAPIArchive_aroundBody8(APIImportExportManager.java:154) ~[org.wso2.carbon.apimgt.impl_6.7.10.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.APIImportExportManager.importAPIArchive(APIImportExportManager.java:144) ~[org.wso2.carbon.apimgt.impl_6.7.10.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.admin.impl.ImportApiServiceImpl.importApiPost(ImportApiServiceImpl.java:102) ~[classes/:?]
	at org.wso2.carbon.apimgt.rest.api.admin.ImportApi.importApiPost(ImportApi.java:52) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-servlet-api_9.0.31.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86) [org.wso2.carbon.identity.context.rewrite.valve_1.4.0.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.0.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:75) [org.wso2.carbon.identity.auth.valve_1.4.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [tomcat_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.31.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.31.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

Verbose output for apictl command
```
Executed ImportExportCLI (apictl) on Wed, 17 Jun 2020 09:54:17 +0530
[INFO]: Insecure: true
[INFO]: import-api called
Login to dev
Username:admin
Password:
Getting ClientID, ClientSecret: Status - 200 
Logged into dev environment
WARNING: credentials are stored as a plain text in /home/sachini/.wso2apictl/keys.json

[INFO]: Resolving for API path...
[INFO]: API Location: /home/sachini/wso2/2020/3.2.0_bug_fixes/apictl/Petstore
[INFO]: Creating workspace
[INFO]: Copying from /home/sachini/wso2/2020/3.2.0_bug_fixes/apictl/Petstore to /tmp/apim544982835
[INFO]: Substituting environment variables in API files...
[INFO]: Substituting env variables of files in folder path:  /tmp/apim544982835/Petstore/Meta-information
[INFO]: Substituting env variables in:  /tmp/apim544982835/Petstore/Meta-information/api.yaml
[INFO]: Substituting env variables in:  /tmp/apim544982835/Petstore/Meta-information/swagger.yaml
[INFO]: Substituting env variables of files in folder path:  /tmp/apim544982835/Petstore/Sequences
[INFO]: Pre Processing API...
[INFO]: Loading /tmp/apim544982835/Petstore/Meta-information/api.yaml
[INFO]: Loading API definition from:  /tmp/apim544982835/Petstore/Meta-information/api.yaml
[INFO]: Writing preprocessed API to: /tmp/apim544982835/Petstore/Meta-information/api.yaml
[INFO]: Attempting to inject parameters to the API from api_params.yaml (if exists)
[INFO]: Scanning for parameters file
[INFO]: Scanning for /home/sachini/wso2/2020/3.2.0_bug_fixes/apictl/Petstore/api_params.yaml
[INFO]: Loading parameters from /home/sachini/wso2/2020/3.2.0_bug_fixes/apictl/Petstore/api_params.yaml
Using default values as the environment is not present in api_param.yaml file
[INFO]: Loading /tmp/apim544982835/Petstore/Meta-information/api.yaml
[INFO]: API is populated with defaults
[INFO]: Writing /tmp/apim544982835/Petstore/Meta-information/api.yaml
[INFO]: Validating API
[INFO]: Creating API artifact /tmp/api-artifact819711734.zip
[INFO]: Creating: Petstore/
[INFO]: Creating: Petstore/Docs/
[INFO]: Creating: Petstore/Docs/FileContents/
[INFO]: Creating: Petstore/Image/
[INFO]: Creating: Petstore/Interceptors/
[INFO]: Creating: Petstore/Meta-information/
[INFO]: Creating: Petstore/Meta-information/api.yaml
[INFO]: Creating: Petstore/Meta-information/swagger.yaml
[INFO]: Creating: Petstore/README.md
[INFO]: Creating: Petstore/Sequences/
[INFO]: Creating: Petstore/Sequences/fault-sequence/
[INFO]: Creating: Petstore/Sequences/in-sequence/
[INFO]: Creating: Petstore/Sequences/out-sequence/
[INFO]: Creating: Petstore/api_params.yaml
[INFO]: Creating: Petstore/libs/
[INFO]: connecting to https://localhost:8243/token
[INFO]: Import URL: https://localhost:9443/api/am/admin/v0.16/import/api?preserveProvider=true
Error importing API.
Status: 500 
Response: {"code":500,"message":"Internal server error","description":"The server encountered an internal error. Please contact administrator.","moreInfo":"","error":[]}
[INFO]: Deleting /tmp/api-artifact819711734.zip
[INFO]: Deleting /tmp/apim544982835/Petstore
apictl: Error importing API Reason: 500 
Exit status 1
```

### Steps to reproduce:
Follow instruction in https://apim.docs.wso2.com/en/latest/learn/api-controller/importing-apis-via-dev-first-approach/ and import API

### Affected Product Version:
APIM 3.2.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

**Comment by msm1992** [comment]
duplicate issue of https://github.com/wso2/product-apim/issues/8294, hence closing
