### ISSUE TITLE
NPE when advanced throttling disabled - APIM 3.1

### ISSUE THREAD

**Issue by vinok88** [wso2/product-apim#8607]
### Description:
Following error occurs both at server startup and try to login if advanced throttling is disabled in APIM 3.1 in the latest WUM.
[apim.throttling]
enable_advanced_throttling = false

[2020-07-07 07:19:28,739] ERROR - APIKeyMgtServiceComponent Failed to initialize key management service.
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.keymgt.internal.APIKeyMgtServiceComponent.configureTokenRevocationEventPublisher_aroundBody24(APIKeyMgtServiceComponent.java:276) ~[org.wso2.carbon.apimgt.keymgt_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.keymgt.internal.APIKeyMgtServiceComponent.configureTokenRevocationEventPublisher(APIKeyMgtServiceComponent.java:268) ~[org.wso2.carbon.apimgt.keymgt_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.keymgt.internal.APIKeyMgtServiceComponent.activate_aroundBody0(APIKeyMgtServiceComponent.java:85) [org.wso2.carbon.apimgt.keymgt_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.keymgt.internal.APIKeyMgtServiceComponent.activate(APIKeyMgtServiceComponent.java:71) [org.wso2.carbon.apimgt.keymgt_6.6.163.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]

The reason for this is we expect the TM is always there at the code 

### Steps to reproduce:
Disable advanced throttling and start the server.

### Affected Product Version:

APIM 3.1.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
#### Suggested Labels:

priority/high

**Comment by isharac** [comment]
fixed
