### ISSUE TITLE
NullPointerException while trying regex threat protection mediation policy

### ISSUE THREAD

**Issue by NikithaUdeshana** [wso2/product-apim#8673]
### Description:
API Manager 2.6.0 version throws following NullPointerException while trying to invoke an API request with an illegal content in the request path when regex threat protection is enabled via a mediation policy.

`TID: [-1234] [] [2020-07-13 11:24:02,284] ERROR {org.apache.synapse.transport.passthru.ServerWorker} -  Error processing GET request for : /v2/2.14.0/ping?test=DROP%20TABLE%20insurances;. Error detail: null.  {org.apache.synapse.transport.passthru.ServerWorker}
java.lang.NullPointerException
	at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleRequest_aroundBody2(APIManagerExtensionHandler.java:82)
	at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleRequest(APIManagerExtensionHandler.java:75)
	at org.apache.synapse.rest.API.process(API.java:352)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:303)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:365)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:186)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)`

### Steps to reproduce:

- Please follow the steps given in the documentation[1] and use the sample regex threat protection mediation policy to recreate the error.
- Invoke the API with an illegal content in the request path.

[1] https://docs.wso2.com/display/AM260/Regular+Expression+Threat+Protection+for+API+Gateway

### Affected Product Version:
APIM 2.6.0

**Comment by hisanhunais** [comment]
Fixed with https://github.com/wso2-support/carbon-apimgt/pull/2225
