### ISSUE TITLE
Identity Component migration error when migrating from APIM 2.1 to 3.2

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/product-apim#8706]
### Description:
Following error trace gets logged in the console.

`[2020-07-16 14:20:14,971]  INFO - VersionMigration  WSO2 Product Migration Service Task : Version : 5.7.0, Migration Step : OIDCScopeDataMigrator of order : 5 is starting...........................
[2020-07-16 14:20:14,972]  INFO - OIDCScopeDataMigrator  WSO2 Product Migration Service Task : Started to migrate OIDC scopes
[2020-07-16 14:20:15,003] ERROR - OIDCScopeDataMigrator  WSO2 Product Migration Service Task : Error while obtaining registry collection from registry path:/oidc
org.wso2.carbon.registry.core.exceptions.ResourceNotFoundException: Resource does not exist at path /_system/config/oidc
	at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.get(MountHandler.java:449) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.get(HandlerManager.java:2446) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.get(UserDefinedHandlerManager.java:199) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.get(HandlerLifecycleManager.java:915) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.get(EmbeddedRegistry.java:512) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.getGhostResourceFromCache(CacheBackedRegistry.java:225) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.get(CacheBackedRegistry.java:198) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry.getInternal(UserRegistry.java:629) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry.access$400(UserRegistry.java:73) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry$5.run(UserRegistry.java:609) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry$5.run(UserRegistry.java:606) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_251]
	at org.wso2.carbon.registry.core.session.UserRegistry.get(UserRegistry.java:606) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator.getOIDCScopeProperties(OIDCScopeDataMigrator.java:183) [org.wso2.carbon.is.migration-1.0.101.jar:?]
	at org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator.migrateOIDCScopes(OIDCScopeDataMigrator.java:114) [org.wso2.carbon.is.migration-1.0.101.jar:?]
	at org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator.migrate(OIDCScopeDataMigrator.java:100) [org.wso2.carbon.is.migration-1.0.101.jar:?]
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52) [org.wso2.carbon.is.migration-1.0.101.jar:?]
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:85) [org.wso2.carbon.is.migration-1.0.101.jar:?]
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:147) [org.wso2.carbon.identity.core_5.17.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529) [org.wso2.carbon.core_4.6.0.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) [org.wso2.carbon.core_4.6.0.jar:?]
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) [org.wso2.carbon.core_4.6.0.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
[2020-07-16 14:20:15,013] ERROR - OIDCScopeDataMigrator  WSO2 Product Migration Service Task : OIDC scope resource cannot be found at /oidc for tenantDomain: carbon.super
[2020-07-16 14:20:15,072]  INFO - OIDCScopeDataMigrator  WSO2 Product Migration Service Task : Started to migrate OIDC scopes for tenant: abc.com
[2020-07-16 14:20:15,079] ERROR - OIDCScopeDataMigrator  WSO2 Product Migration Service Task : Error while obtaining registry collection from registry path:/oidc
org.wso2.carbon.registry.core.exceptions.ResourceNotFoundException: Resource does not exist at path /_system/config/oidc
	at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.get(MountHandler.java:449) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.get(HandlerManager.java:2446) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.get(UserDefinedHandlerManager.java:199) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.get(HandlerLifecycleManager.java:915) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.get(EmbeddedRegistry.java:512) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.getGhostResourceFromCache(CacheBackedRegistry.java:225) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.get(CacheBackedRegistry.java:198) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry.getInternal(UserRegistry.java:629) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry.access$400(UserRegistry.java:73) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry$5.run(UserRegistry.java:609) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry$5.run(UserRegistry.java:606) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_251]
	at org.wso2.carbon.registry.core.session.UserRegistry.get(UserRegistry.java:606) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator.getOIDCScopeProperties(OIDCScopeDataMigrator.java:183) [org.wso2.carbon.is.migration-1.0.101.jar:?]
	at org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator.migrateOIDCScopes(OIDCScopeDataMigrator.java:127) [org.wso2.carbon.is.migration-1.0.101.jar:?]
	at org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator.migrate(OIDCScopeDataMigrator.java:100) [org.wso2.carbon.is.migration-1.0.101.jar:?]
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52) [org.wso2.carbon.is.migration-1.0.101.jar:?]
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:85) [org.wso2.carbon.is.migration-1.0.101.jar:?]
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:147) [org.wso2.carbon.identity.core_5.17.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529) [org.wso2.carbon.core_4.6.0.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) [org.wso2.carbon.core_4.6.0.jar:?]
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) [org.wso2.carbon.core_4.6.0.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
[2020-07-16 14:20:15,081] ERROR - OIDCScopeDataMigrator  WSO2 Product Migration Service Task : OIDC scope resource cannot be found at /oidc for tenantDomain: abc.com
[2020-07-16 14:20:15,081]  INFO - MigrationClientImpl  WSO2 Product Migration Service Task : Start Version : 5.7.0 to 5.8.0
[2020-07-16 14:20:15,082]  INFO - VersionMigration  WSO2 Product Migration Service Task : Version : 5.8.0, Migration Step : SchemaMigrator of order : 1 is starting...........................
[2020-07-16 14:20:15,083]  INFO - SchemaMigrator  WSO2 Product Migration Service Task : Executing Identity Migration Scripts.
[2020-07-16 14:20:15,711]  INFO - SchemaMigrator  WSO2 Product Migration Service Task : Identity DB Migration script executed successfully.`

## Environment
Tested in both postgres and oracle dbs

**Comment by nandika** [comment]
Should migrate to 4.x
