### ISSUE TITLE
[APIM 2.6.0] Unable to download WSDL from store when API created using  WSDL Archive/File option

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-apim#8715]
Steps to reproduce the issue

1. Create an API using WSDL Archive/File option and publish the API.
2. Try to download the WSDL of the API from the store portal.
3. Then you will encounter an issue as follows.
![image](https://user-images.githubusercontent.com/30020227/87747134-09f05a00-c810-11ea-8c20-f1930379f95f.png)
4. And the following exception logged in the wso2carbon.log

```
Caused by: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:545)
at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:521)
at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:691)
at org.wso2.carbon.apimgt.impl.utils.APIFileUtil.searchFilesWithMatchingExtension_aroundBody14(APIFileUtil.java:211)
at org.wso2.carbon.apimgt.impl.utils.APIFileUtil.searchFilesWithMatchingExtension(APIFileUtil.java:210)
at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getWSDLDocument_aroundBody206(APIConsumerImpl.java:4432)
at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getWSDLDocument(APIConsumerImpl.java:4400)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
... 57 mor
```

While debugging the method [1], I observed that the issue caused due to the passing incorrect file path for the WSDL file location, as a parameter to the method APIFileUtil.searchFilesWithMatchingExtension  since there is no such path the exception has occurred.This behaviour occurred due to when creating the following folderToImport  file object we are appending "extracted" to the file path, and the file path is created as "/home/siluni/.wum3/products/wso2am/2.6.0/full/wso2am-2.6.0/tmp/WSDL-archives/631b96bd-d440-4ecf-af55-df8024b5622a/extracted/extracted"

```
File folderToImport = new File(archiveInfo.getLocation() + File.separator  + APIConstants.API_WSDL_EXTRACTED_DIRECTORY);
Collection<File> wsdlFiles = APIFileUtil.searchFilesWithMatchingExtension(folderToImport, APIFileUtil.WSDL_FILE_EXTENSION);
```
Due to file path include double "extracted" word it creates an incorrect file path. And this can be fixed by remove appending APIConstants.API_WSDL_EXTRACTED_DIRECTORY.

Therefore, shall we take a step to fix this at the product level.
Thanks,
Siluni

[1] https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java#L5016

**Comment by hisanhunais** [comment]
Fixed with https://github.com/wso2-support/carbon-apimgt/pull/2222

**Comment by vithu30** [comment]
This is not reproducible in 3.0.0

**Comment by hisanhunais** [comment]
This is not reproducible in the master branch as well.

**Comment by vithu30** [comment]
Closing as it is not reproducible.
