### ISSUE TITLE
Configuration Issue in profiles

### ISSUE THREAD

**Issue by isharac** [wso2/product-apim#8720]
### Description:
Fail to start api-devportal api-publisher gateway-worker profiles with below error.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.bootstrap.Bootstrap.loadClass(Bootstrap.java:70)
	at org.wso2.carbon.bootstrap.Bootstrap.main(Bootstrap.java:51)
Caused by: com.hubspot.jinjava.interpret.FatalTemplateErrorsException: TemplateSyntaxException: Cannot find method toList with 0 parameters in class java.lang.String
	at com.hubspot.jinjava.Jinjava.render(Jinjava.java:155)
	at org.wso2.config.mapper.JinjaParser.lambda$parse$0(JinjaParser.java:57)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.wso2.config.mapper.JinjaParser.parse(JinjaParser.java:53)
	at org.wso2.config.mapper.ConfigParser.parse(ConfigParser.java:258)
	at org.wso2.config.mapper.ConfigParser.deploy(ConfigParser.java:217)
	at org.wso2.config.mapper.ConfigParser.deployAndStoreMetadata(ConfigParser.java:180)
	at org.wso2.config.mapper.ConfigParser.parse(ConfigParser.java:127)
	at org.wso2.carbon.server.Main.handleConfiguration(Main.java:231)
	at org.wso2.carbon.server.Main.main(Main.java:103)
	... 6 more

**Comment by isharac** [comment]
fixed with https://github.com/wso2/product-apim/pull/8721

**Comment by isharac** [comment]
fixed
