### ISSUE TITLE
[Artifact Synchronizer] NPE when Demoting API to Created state

### ISSUE THREAD

**Issue by jaadds** [wso2/product-apim#8723]
### Description:
When Artifact Synchronizer is enabled, changing Lifecycle of an API to Created from Publish gives an NPE on the Gateway

Error on Gateway
[2020-07-17 13:58:51,283] ERROR - NativeWorkerPool Uncaught exception
java.lang.NullPointerException: null
        at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.unDeployAPI_aroundBody100(APIGatewayAdmin.java:899) ~[org.wso2.carbon.apimgt.gateway_6.7.111.jar:?]
        at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.unDeployAPI(APIGatewayAdmin.java:895) ~[org.wso2.carbon.apimgt.gateway_6.7.111.jar:?]
        at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.unDeployAPI_aroundBody4(InMemoryAPIDeployer.java:149) ~[org.wso2.carbon.apimgt.gateway_6.7.111.jar:?]
        at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.unDeployAPI(InMemoryAPIDeployer.java:138) ~[org.wso2.carbon.apimgt.gateway_6.7.111.jar:?]
        at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage_aroundBody2(GatewayJMSMessageListener.java:117) ~[org.wso2.carbon.apimgt.gateway_6.7.111.jar:?]
        at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage(GatewayJMSMessageListener.java:101) ~[org.wso2.carbon.apimgt.gateway_6.7.111.jar:?]
        at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage_aroundBody0(GatewayJMSMessageListener.java:84) ~[org.wso2.carbon.apimgt.gateway_6.7.111.jar:?]
        at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage(GatewayJMSMessageListener.java:59) ~[org.wso2.carbon.apimgt.gateway_6.7.111.jar:?]
        at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:645) ~[org.wso2.carbon.apimgt.jms.listener_6.7.111.jar:?]
        at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:544) ~[org.wso2.carbon.apimgt.jms.listener_6.7.111.jar:?]
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231] 

### Affected Product Version:
Post-beta pack built with  6.7.111 components

**Comment by 1akshitha** [comment]
Closing the issue as this is not reproduced in the latest.
