### ISSUE TITLE
[GDPR] Running forgetme tool for an API Provider breaks retreiving APIs in Publisher

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#8822]
### Description:
In a scenario where an API Provider leaves the organization and the API Provider has APIs that were created that are still been used in the organization. Running the _forgetme_ tool will obfuscate the providers information, including rows such as the API_PROVIDER column in the AM_API table.

![image](https://user-images.githubusercontent.com/6614042/88554147-c5e92a80-d043-11ea-95ba-5761faac4f54.png)

This causes issues since the registry still contains the original publisher name in the rxt. When trying to read the corresponding API from the AM_API table by passing the provider name at rxt level the API cannot be found since the data has now been changed.

```
19:19:16,553 ApiMgtDAO  Unable to find the API: publisher-pub1-1.0.0 in the database
19:19:16,633 ApisApiServiceImpl  Error while retrieving API : 42a9e32e-906a-4218-90d7-983307e5cbbe
org.wso2.carbon.apimgt.api.APIManagementException: Unable to find the API: publisher-pub1-1.0.0 in the database
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getAPIID_aroundBody314(ApiMgtDAO.java:7178)
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getAPIID(ApiMgtDAO.java:7147)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getAPIForPublishing_aroundBody10(APIUtil.java:641)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getAPIForPublishing(APIUtil.java:632)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getApiForPublishing_aroundBody16(AbstractAPIManager.java:469)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getApiForPublishing(AbstractAPIManager.java:468)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getAPIbyUUID_aroundBody20(AbstractAPIManager.java:512)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getAPIbyUUID(AbstractAPIManager.java:486)
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.getAPIByID(ApisApiServiceImpl.java:4264)
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.apisApiIdGet(ApisApiServiceImpl.java:470)
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.apisApiIdGet(ApisApi.java:380)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:225)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:75)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce:
1. Create and publish APIs belonging to a given API Provider user.
2. Run forgetme tool for the given user.
3. Login to publisher UI and attempt to view details of APIs that belonged to the above mentioned provider.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tharikaGitHub** [comment]
@uvindra The forget me tool should be run for deleted users. Do you get the issue even after deleting the user?

**Comment by uvindra** [comment]
@tharikaGitHub Yes you are correct, this issue does not occur if the tool is run after deleting the user. Closing the issue.
