### ISSUE TITLE
Scope Update UI getting stuck due to a connection pool issue

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#8909]
### Description:
When updating shared scopes from UI, sometimes the Scopes UI is getting suck (keep on loading). After some minutes, getting a Thread Death error.

```
[2020-08-04 10:10:00,049]  WARN - CarbonStuckThreadDetectionValve Thread [https-jsse-nio-9443-exec-39] (id=[{6}]) has been active for [607,497] milliseconds (since [8/4/20 9:59 AM]) to serve the same request for [https://localhost:9443/api/am/publisher/v1/scopes/85f6f860-9832-49a6-bae5-b7ad740d0fd4] and may be stuck (configured threshold for this StuckThreadDetectionValve is [600] seconds). There is/are [6] thread(s) in total that are monitored by this Valve and may be stuck., tenantDomain=carbon.super
java.lang.Throwable: null
	at sun.misc.Unsafe.park(Native Method) ~[?:1.8.0_231]
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175) ~[?:1.8.0_231]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039) ~[?:1.8.0_231]
	at org.apache.http.impl.conn.tsccm.WaitingThread.await(WaitingThread.java:159) ~[httpclient_4.3.6.wso2v2.jar:?]
	at org.apache.http.impl.conn.tsccm.ConnPoolByRoute.getEntryBlocking(ConnPoolByRoute.java:398) ~[httpclient_4.3.6.wso2v2.jar:?]
	at org.apache.http.impl.conn.tsccm.ConnPoolByRoute$1.getPoolEntry(ConnPoolByRoute.java:298) ~[httpclient_4.3.6.wso2v2.jar:?]
	at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager$1.getConnection(ThreadSafeClientConnManager.java:238) ~[httpclient_4.3.6.wso2v2.jar:?]
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:423) ~[httpclient_4.3.6.wso2v2.jar:?]
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863) ~[httpclient_4.3.6.wso2v2.jar:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient_4.3.6.wso2v2.jar:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106) ~[httpclient_4.3.6.wso2v2.jar:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57) ~[httpclient_4.3.6.wso2v2.jar:?]
	at org.wso2.carbon.apimgt.impl.kmclient.ApacheFeignHttpClient.execute_aroundBody0(ApacheFeignHttpClient.java:83) ~[org.wso2.carbon.apimgt.impl_6.7.166.jar:?]
	at org.wso2.carbon.apimgt.impl.kmclient.ApacheFeignHttpClient.execute(ApacheFeignHttpClient.java:76) ~[org.wso2.carbon.apimgt.impl_6.7.166.jar:?]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at com.sun.proxy.$Proxy484.getScopeByName(Unknown Source) ~[?:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.getScopeByName_aroundBody46(AMDefaultKeyManagerImpl.java:722) ~[org.wso2.carbon.apimgt.impl_6.7.166.jar:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.getScopeByName(AMDefaultKeyManagerImpl.java:718) ~[org.wso2.carbon.apimgt.impl_6.7.166.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.getSharedScopeByUUID_aroundBody478(APIProviderImpl.java:8656) ~[org.wso2.carbon.apimgt.impl_6.7.166.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.getSharedScopeByUUID(APIProviderImpl.java:8648) ~[org.wso2.carbon.apimgt.impl_6.7.166.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.getSharedScopeByUUID(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_6.7.166.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ScopesApiServiceImpl.updateSharedScope(ScopesApiServiceImpl.java:235) ~[?:?]

```

### Steps to reproduce:

1. Create a shared scope
2. Update the shared scope and click on Save button.

### Affected Product Version:
3.2.0-RC

**Comment by mushthaq33** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/9130
