### ISSUE TITLE
Jars loading issue when server start

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#8915]
The following issues noticed for multiple jars. Adding all of them in the catalina.properties as jarsToSkip solved the issue.

[catalina.properties.txt](https://github.com/wso2/product-apim/files/5020642/catalina.properties.txt)

[full_error.log](https://github.com/wso2/product-apim/files/5020644/full_error.log)

Environment:
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
```

```
[2020-08-04 07:04:10,892]  WARN - StandardJarScanner Failed to scan [file:/home/ubuntu/ansible-apim/files/packs/wso2am-3.2.0-SNAPSHOT/repository/components/plugins/lib/org.jaggeryjs.jaggery.core-0.14.12.jar] from classloader hierarchy
java.io.IOException: java.lang.reflect.InvocationTargetException
	at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:236) ~[tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.scan.JarFileUrlJar.<init>(JarFileUrlJar.java:65) ~[tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:49) ~[tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:383) ~[tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.scan.StandardJarScanner.processURLs(StandardJarScanner.java:318) [tomcat_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.scan.CarbonTomcatJarScanner.doScanClassPath(CarbonTomcatJarScanner.java:123) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:233) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.startup.ContextConfig.processJarsForWebFragments(ContextConfig.java:1968) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1128) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:774) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:301) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5051) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) [tomcat_9.0.31.wso2v1.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat_9.0.31.wso2v1.jar:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) [?:?]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) [tomcat_9.0.31.wso2v1.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat_9.0.31.wso2v1.jar:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) [?:?]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.service.ExtendedStandardService.startInternal(ExtendedStandardService.java:52) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.internal.CarbonTomcat.start(CarbonTomcat.java:113) [org.wso2.carbon.tomcat_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.internal.ServerManager$1.run(ServerManager.java:167) [org.wso2.carbon.tomcat_4.6.0.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:233) ~[tomcat_9.0.31.wso2v1.jar:?]
	... 36 more
```

**Comment by ruks** [comment]
This is due to a wrong classpath in the manifest file of the org.jaggeryjs.jaggery.tools_0.14.12.jar. In there classpath is prefix is /lib and hence looking for the jars in plugin/lib directory. SInce org.jaggeryjs.jaggery.tools_0.14.12.jar is not required, this jar need to be moved from the pack.
