### ISSUE TITLE
[3.2.0] NullType error when starting server with `database` as the `user_store` type

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#8935]
### Description:

When the `user_store` type is configured as `database` (rather than `database_unique_id`) and when starting the API Manager server, the following error is observed

```log
[2020-08-05 13:55:47,980] ERROR - DefaultRealm nullType class java.lang.reflect.InvocationTargetException
org.wso2.carbon.user.core.UserStoreException: nullType class java.lang.reflect.InvocationTargetException
	at org.wso2.carbon.user.core.common.DefaultRealm.createObjectWithOptions(DefaultRealm.java:397) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealm.initializeObjects(DefaultRealm.java:224) [org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealm.init(DefaultRealm.java:129) [org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealmService.initializeRealm(DefaultRealmService.java:276) [org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:102) [org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:115) [org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.internal.Activator.startDeploy(Activator.java:72) [org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.internal.BundleCheckActivator.start(BundleCheckActivator.java:61) [org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_201]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.Module.doStart(Module.java:598) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.Module.start(Module.java:462) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201]
	at org.wso2.carbon.user.core.common.DefaultRealm.createObjectWithOptions(DefaultRealm.java:351) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	... 25 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Admin role has not been created. Error occurs while creating Admin role in primary user store.
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addInitialAdminData(AbstractUserStoreManager.java:8423) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:319) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:258) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201]
	at org.wso2.carbon.user.core.common.DefaultRealm.createObjectWithOptions(DefaultRealm.java:351) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	... 25 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while getting database type from DB connection
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.doAddRole(JDBCUserStoreManager.java:1617) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addInitialAdminData(AbstractUserStoreManager.java:8412) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:319) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:258) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201]
	at org.wso2.carbon.user.core.common.DefaultRealm.createObjectWithOptions(DefaultRealm.java:351) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	... 25 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Using sql : INSERT INTO UM_USER_ROLE (UM_USER_ID, UM_ROLE_ID, UM_TENANT_ID) VALUES ((SELECT UM_ID FROM UM_USER WHERE LOWER(UM_USER_NAME)=LOWER(?) AND UM_TENANT_ID=?),(SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME=? AND UM_TENANT_ID=?), ?) NULL not allowed for column "UM_USER_ID"; SQL statement:
INSERT INTO UM_USER_ROLE (UM_USER_ID, UM_ROLE_ID, UM_TENANT_ID) VALUES ((SELECT UM_ID FROM UM_USER WHERE LOWER(UM_USER_NAME)=LOWER(?) AND UM_TENANT_ID=?),(SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME=? AND UM_TENANT_ID=?), ?) [23502-199]
	at org.wso2.carbon.user.core.util.DatabaseUtil.udpateUserRoleMappingInBatchMode(DatabaseUtil.java:1005) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.doAddRole(JDBCUserStoreManager.java:1591) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addInitialAdminData(AbstractUserStoreManager.java:8412) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:319) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:258) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201]
	at org.wso2.carbon.user.core.common.DefaultRealm.createObjectWithOptions(DefaultRealm.java:351) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	... 25 more
Caused by: org.h2.jdbc.JdbcBatchUpdateException: NULL not allowed for column "UM_USER_ID"; SQL statement:
INSERT INTO UM_USER_ROLE (UM_USER_ID, UM_ROLE_ID, UM_TENANT_ID) VALUES ((SELECT UM_ID FROM UM_USER WHERE LOWER(UM_USER_NAME)=LOWER(?) AND UM_TENANT_ID=?),(SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME=? AND UM_TENANT_ID=?), ?) [23502-199]
	at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1298) ~[h2_1.4.199.wso2v1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
	at com.sun.proxy.$Proxy49.executeBatch(Unknown Source) ~[?:?]
	at org.wso2.carbon.user.core.util.DatabaseUtil.udpateUserRoleMappingInBatchMode(DatabaseUtil.java:994) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.doAddRole(JDBCUserStoreManager.java:1591) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addInitialAdminData(AbstractUserStoreManager.java:8412) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:319) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:258) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201]
	at org.wso2.carbon.user.core.common.DefaultRealm.createObjectWithOptions(DefaultRealm.java:351) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	... 25 more
[2020-08-05 13:55:48,001] ERROR - Activator Cannot start User Manager Core bundle
org.wso2.carbon.user.core.UserStoreException: Cannot initialize the realm.
	at org.wso2.carbon.user.core.common.DefaultRealmService.initializeRealm(DefaultRealmService.java:286) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:102) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:115) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.internal.Activator.startDeploy(Activator.java:72) [org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.internal.BundleCheckActivator.start(BundleCheckActivator.java:61) [org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_201]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.Module.doStart(Module.java:598) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.Module.start(Module.java:462) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
Caused by: org.wso2.carbon.user.core.UserStoreException: nullType class java.lang.reflect.InvocationTargetException
	at org.wso2.carbon.user.core.common.DefaultRealm.initializeObjects(DefaultRealm.java:318) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealm.init(DefaultRealm.java:129) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealmService.initializeRealm(DefaultRealmService.java:276) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	... 22 more
Caused by: org.wso2.carbon.user.core.UserStoreException: nullType class java.lang.reflect.InvocationTargetException
	at org.wso2.carbon.user.core.common.DefaultRealm.createObjectWithOptions(DefaultRealm.java:397) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealm.initializeObjects(DefaultRealm.java:224) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealm.init(DefaultRealm.java:129) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealmService.initializeRealm(DefaultRealmService.java:276) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	... 22 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201]
	at org.wso2.carbon.user.core.common.DefaultRealm.createObjectWithOptions(DefaultRealm.java:351) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealm.initializeObjects(DefaultRealm.java:224) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealm.init(DefaultRealm.java:129) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealmService.initializeRealm(DefaultRealmService.java:276) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	... 22 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Admin role has not been created. Error occurs while creating Admin role in primary user store.
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addInitialAdminData(AbstractUserStoreManager.java:8423) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:319) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:258) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201]
	at org.wso2.carbon.user.core.common.DefaultRealm.createObjectWithOptions(DefaultRealm.java:351) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealm.initializeObjects(DefaultRealm.java:224) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealm.init(DefaultRealm.java:129) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealmService.initializeRealm(DefaultRealmService.java:276) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	... 22 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while getting database type from DB connection
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.doAddRole(JDBCUserStoreManager.java:1617) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addInitialAdminData(AbstractUserStoreManager.java:8412) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:319) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:258) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201]
	at org.wso2.carbon.user.core.common.DefaultRealm.createObjectWithOptions(DefaultRealm.java:351) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealm.initializeObjects(DefaultRealm.java:224) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealm.init(DefaultRealm.java:129) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealmService.initializeRealm(DefaultRealmService.java:276) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	... 22 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Using sql : INSERT INTO UM_USER_ROLE (UM_USER_ID, UM_ROLE_ID, UM_TENANT_ID) VALUES ((SELECT UM_ID FROM UM_USER WHERE LOWER(UM_USER_NAME)=LOWER(?) AND UM_TENANT_ID=?),(SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME=? AND UM_TENANT_ID=?), ?) NULL not allowed for column "UM_USER_ID"; SQL statement:
INSERT INTO UM_USER_ROLE (UM_USER_ID, UM_ROLE_ID, UM_TENANT_ID) VALUES ((SELECT UM_ID FROM UM_USER WHERE LOWER(UM_USER_NAME)=LOWER(?) AND UM_TENANT_ID=?),(SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME=? AND UM_TENANT_ID=?), ?) [23502-199]
	at org.wso2.carbon.user.core.util.DatabaseUtil.udpateUserRoleMappingInBatchMode(DatabaseUtil.java:1005) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.doAddRole(JDBCUserStoreManager.java:1591) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addInitialAdminData(AbstractUserStoreManager.java:8412) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:319) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:258) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201]
	at org.wso2.carbon.user.core.common.DefaultRealm.createObjectWithOptions(DefaultRealm.java:351) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealm.initializeObjects(DefaultRealm.java:224) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealm.init(DefaultRealm.java:129) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealmService.initializeRealm(DefaultRealmService.java:276) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	... 22 more
Caused by: org.h2.jdbc.JdbcBatchUpdateException: NULL not allowed for column "UM_USER_ID"; SQL statement:
INSERT INTO UM_USER_ROLE (UM_USER_ID, UM_ROLE_ID, UM_TENANT_ID) VALUES ((SELECT UM_ID FROM UM_USER WHERE LOWER(UM_USER_NAME)=LOWER(?) AND UM_TENANT_ID=?),(SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME=? AND UM_TENANT_ID=?), ?) [23502-199]
	at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1298) ~[h2_1.4.199.wso2v1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
	at com.sun.proxy.$Proxy49.executeBatch(Unknown Source) ~[?:?]
	at org.wso2.carbon.user.core.util.DatabaseUtil.udpateUserRoleMappingInBatchMode(DatabaseUtil.java:994) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.doAddRole(JDBCUserStoreManager.java:1591) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addInitialAdminData(AbstractUserStoreManager.java:8412) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:319) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:258) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201]
	at org.wso2.carbon.user.core.common.DefaultRealm.createObjectWithOptions(DefaultRealm.java:351) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealm.initializeObjects(DefaultRealm.java:224) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealm.init(DefaultRealm.java:129) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.DefaultRealmService.initializeRealm(DefaultRealmService.java:276) ~[org.wso2.carbon.user.core_4.6.0.jar:?]
	... 22 more
```

### Steps to reproduce:

1. Download the API Manager v3.2.0 - RC1 server and extract
2. Go to `<apim>/repository/conf/deployment.toml` and change the following configurations as follows
    
    ```toml
    [user_store]
    type = "database"
    # type = "database_unique_id"
    ```
3. And start the server

### Affected Product Version:

- API Manager v3.2.0 - RC1
- API Manager v3.1.0

**Comment by bashidagha** [comment]
It's happened for me several times.
Check that if you have same instance of wso on localhost
or other tools that you maybe have on your localhost for example apache
stop them
for apache2:
` sudo systemctl stop apache2`
