### ISSUE TITLE
Intermittent NPE in startup log

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#9004]
Following error log can be observed intermittenly during APIM 3.2.0 startup(Observed when the startup time is high).

```
[2020-08-10 10:22:00,228] ERROR - SubscriptionDataLoaderImpl Could not retrieve subscriptions for tenantDomain : carbon.super
[2020-08-10 10:22:00,228] ERROR - SubscriptionDataLoaderImpl Could not retrieve subscriptions for tenantDomain : carbon.super
[2020-08-10 10:22:00,228] ERROR - SubscriptionDataLoaderImpl Could not retrieve subscriptions for tenantDomain : carbon.super
[2020-08-10 10:22:00,228] ERROR - SubscriptionDataLoaderImpl Could not retrieve subscriptions for tenantDomain : carbon.super
[2020-08-10 10:22:00,232] ERROR - SubscriptionDataLoaderImpl Could not retrieve subscriptions for tenantDomain : carbon.super
[2020-08-10 10:22:00,232] ERROR - SubscriptionDataLoaderImpl Could not retrieve subscriptions for tenantDomain : carbon.super
[2020-08-10 10:22:00,230] ERROR - SubscriptionDataLoaderImpl Could not retrieve subscriptions for tenantDomain : carbon.super
Exception in thread "Timer-15" java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Arrays$ArrayList.<init>(Arrays.java:4323)
	at java.base/java.util.Arrays.asList(Arrays.java:4310)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService_aroundBody6(KeyTemplateRetriever.java:116)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService(KeyTemplateRetriever.java:115)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run_aroundBody0(KeyTemplateRetriever.java:55)
	at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run(KeyTemplateRetriever.java:51)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
[2020-08-10 10:22:00,240] ERROR - SubscriptionDataStoreImpl Exception while loading Application Policies org.wso2.carbon.apimgt.keymgt.model.exception.DataLoadingException: Error while retrieving subscription from /application-policies
[2020-08-10 10:22:00,240] ERROR - SubscriptionDataStoreImpl Exception while loading ApplicationKeyMapping org.wso2.carbon.apimgt.keymgt.model.exception.DataLoadingException: Error while retrieving subscription from /application-key-mappings
[2020-08-10 10:22:00,240] ERROR - SubscriptionDataStoreImpl Exception while loading APIs org.wso2.carbon.apimgt.keymgt.model.exception.DataLoadingException: Error while retrieving subscription from /apis
[2020-08-10 10:22:00,240] ERROR - SubscriptionDataStoreImpl Exception while loading Subscriptions org.wso2.carbon.apimgt.keymgt.model.exception.DataLoadingException: Error while retrieving subscription from /subscriptions
```

**Comment by rahul096d** [comment]
Is this issue fixed in any latest patches?

**Comment by Krishanx92** [comment]
This is not reproducing in latest pack, hence closing
