### ISSUE TITLE
Unable to add remove api properties after key manager delete

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#9020]
### Description:
Create a key manager from admin app.
Go to publisher
Select an API "PizzaApi"
Go to *Runtime Configurations -> Application Level Security -> Key Managers*
Select *Allow Selected* and check the newly created key manager.
Now go back to the admin app key manager list and delete the key manager.
Go to the publisher app and select "PizzaApi" again.
Try to add API properties or update design configurations. or add local scopes.

Following error displays in the terminal
```
[2020-08-10 22:18:14,367] ERROR - ApisApiServiceImpl Error while updating the API : 618e01f2-bd4d-448f-98a4-015f8407f263 - Key Manager(s) Not found :test123
org.wso2.carbon.apimgt.api.APIManagementException: Key Manager(s) Not found :test123
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.validateKeyManagers_aroundBody82(APIProviderImpl.java:1582) ~[org.wso2.carbon.apimgt.impl_6.7.185.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.validateKeyManagers(APIProviderImpl.java:1562) ~[org.wso2.carbon.apimgt.impl_6.7.185.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.updateAPI_aroundBody80(APIProviderImpl.java:1287) ~[org.wso2.carbon.apimgt.impl_6.7.185.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.updateAPI(APIProviderImpl.java:1281) ~[org.wso2.carbon.apimgt.impl_6.7.185.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.manageAPI_aroundBody12(UserAwareAPIProvider.java:137) ~[org.wso2.carbon.apimgt.impl_6.7.185.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.manageAPI(UserAwareAPIProvider.java:126) ~[org.wso2.carbon.apimgt.impl_6.7.185.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.apisApiIdPut(ApisApiServiceImpl.java:913) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.apisApiIdPut(ApisApi.java:690) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(A
```

Go back to the run time configurations and select all key manager's options.
Now we are able to do update the API properties, Design-time configuration, or local scopes as expected.

**Comment by Krishanx92** [comment]
We are closing the issue due to a long period of inactivity.
