### ISSUE TITLE
Key manager add/edit long description gives error in the backend

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#9021]
### Description:
Enter a long description as the key manager description.
Try to save it.
Following exception occurs

```
 Caused by: org.h2.jdbc.JdbcSQLDataException: Value too long for column """DESCRIPTION"" VARCHAR(256)": "STRINGDECODE('Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tristique sodales orci, vitae tincidunt sem porttitor ... (2886)"; SQL statement:
UPDATE AM_KEY_MANAGER SET NAME = ?,DESCRIPTION = ?,TYPE = ?,CONFIGURATION = ?,TENANT_DOMAIN = ?,ENABLED = ?,DISPLAY_NAME = ? WHERE UUID = ? [22001-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:455) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.message.DbException.get(DbException.java:205) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.table.Column.validateConvertUpdat

```

**Comment by NethmiRanasinghe** [comment]
This issue is fixed in latest version
