### ISSUE TITLE
[3.2.0][DB2] Error when updating Advanced Policies with DB2

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#9086]
### Description:

Following error-traces are observed when trying to update an existing (or newly created) Advanced Policies with DB2 database configured

```log
[2020-08-16 21:39:30,990] ERROR - ApiMgtDAO Failed to update api policy: 5PerMin--1234
com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-798, SQLSTATE=428C9, SQLERRMC=POLICY_ID, DRIVER=4.26.14
    at com.ibm.db2.jcc.am.b7.a(b7.java:810) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.b7.a(b7.java:66) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.b7.a(b7.java:140) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.k4.c(k4.java:2824) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.k4.a(k4.java:2261) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.t4.ab.r(ab.java:1654) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.t4.ab.l(ab.java:751) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.t4.ab.d(ab.java:112) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.t4.p.c(p.java:44) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.t4.av.j(av.java:162) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.k4.an(k4.java:2256) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.k5.a(k5.java:4637) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.k5.b(k5.java:4182) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.k5.be(k5.java:827) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.k5.executeUpdate(k5.java:801) ~[db2jcc4.jar:?]
    at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
    at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
    at com.sun.proxy.$Proxy49.executeUpdate(Unknown Source) ~[?:?]
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.updateAPIPolicy_aroundBody496(ApiMgtDAO.java:10545) [org.wso2.carbon.apimgt.impl_6.7.192.jar:?]
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.updateAPIPolicy(ApiMgtDAO.java:10526) [org.wso2.carbon.apimgt.impl_6.7.192.jar:?]
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.updateAPIPolicy_aroundBody552(ApiMgtDAO.java:11771) [org.wso2.carbon.apimgt.impl_6.7.192.jar:?]
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.updateAPIPolicy(ApiMgtDAO.java:11721) [org.wso2.carbon.apimgt.impl_6.7.192.jar:?]
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.updatePolicy_aroundBody300(APIProviderImpl.java:6433) [org.wso2.carbon.apimgt.impl_6.7.192.jar:?]
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.updatePolicy(APIProviderImpl.java:6394) [org.wso2.carbon.apimgt.impl_6.7.192.jar:?]
    at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.updatePolicy(UserAwareAPIProvider.java:1) [org.wso2.carbon.apimgt.impl_6.7.192.jar:?]
    at org.wso2.carbon.apimgt.rest.api.admin.v1.impl.ThrottlingApiServiceImpl.throttlingPoliciesAdvancedPolicyIdPut(ThrottlingApiServiceImpl.java:209) [classes/:?]
    at org.wso2.carbon.apimgt.rest.api.admin.v1.ThrottlingApi.throttlingPoliciesAdvancedPolicyIdPut(ThrottlingApi.java:211) [classes/:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
    at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.2.8.jar:3.2.8]
    at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.2.8.jar:3.2.8]
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.2.8.jar:3.2.8]
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.2.8.jar:3.2.8]
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.2.8.jar:3.2.8]
    at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.2.8.jar:3.2.8]
    at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
    at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
    at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPut(AbstractHTTPServlet.java:237) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:663) [tomcat-servlet-api_9.0.31.wso2v1.jar:?]
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.31.wso2v1.jar:?]
    at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86) [org.wso2.carbon.identity.context.rewrite.valve_1.4.0.jar:?]
    at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.0.jar:?]
    at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:75) [org.wso2.carbon.identity.auth.valve_1.4.0.jar:?]
    at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
    at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
    at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
    at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [tomcat_9.0.31.wso2v1.jar:?]
    at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
    at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.31.wso2v1.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.31.wso2v1.jar:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[2020-08-16 21:39:31,062] ERROR - ThrottlingApiServiceImpl Error while updating Advanced level policy: 5PerMin
org.wso2.carbon.apimgt.api.APIManagementException: Failed to update api policy: 5PerMin--1234
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.handleException_aroundBody320(ApiMgtDAO.java:7297) ~[org.wso2.carbon.apimgt.impl_6.7.192.jar:?]
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.handleException(ApiMgtDAO.java:7295) ~[org.wso2.carbon.apimgt.impl_6.7.192.jar:?]
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.updateAPIPolicy_aroundBody552(ApiMgtDAO.java:11783) ~[org.wso2.carbon.apimgt.impl_6.7.192.jar:?]
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.updateAPIPolicy(ApiMgtDAO.java:11721) ~[org.wso2.carbon.apimgt.impl_6.7.192.jar:?]
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.updatePolicy_aroundBody300(APIProviderImpl.java:6433) ~[org.wso2.carbon.apimgt.impl_6.7.192.jar:?]
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.updatePolicy(APIProviderImpl.java:6394) ~[org.wso2.carbon.apimgt.impl_6.7.192.jar:?]
    at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.updatePolicy(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_6.7.192.jar:?]
    at org.wso2.carbon.apimgt.rest.api.admin.v1.impl.ThrottlingApiServiceImpl.throttlingPoliciesAdvancedPolicyIdPut(ThrottlingApiServiceImpl.java:209) [classes/:?]
    at org.wso2.carbon.apimgt.rest.api.admin.v1.ThrottlingApi.throttlingPoliciesAdvancedPolicyIdPut(ThrottlingApi.java:211) [classes/:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
    at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.2.8.jar:3.2.8]
    at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.2.8.jar:3.2.8]
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.2.8.jar:3.2.8]
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.2.8.jar:3.2.8]
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.2.8.jar:3.2.8]
    at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.2.8.jar:3.2.8]
    at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
    at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
    at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPut(AbstractHTTPServlet.java:237) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:663) [tomcat-servlet-api_9.0.31.wso2v1.jar:?]
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.31.wso2v1.jar:?]
    at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86) [org.wso2.carbon.identity.context.rewrite.valve_1.4.0.jar:?]
    at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.0.jar:?]
    at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:75) [org.wso2.carbon.identity.auth.valve_1.4.0.jar:?]
    at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
    at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
    at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
    at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [tomcat_9.0.31.wso2v1.jar:?]
    at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
    at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639) [tomcat_9.0.31.wso2v1.jar:?]
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.31.wso2v1.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.31.wso2v1.jar:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-798, SQLSTATE=428C9, SQLERRMC=POLICY_ID, DRIVER=4.26.14
    at com.ibm.db2.jcc.am.b7.a(b7.java:810) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.b7.a(b7.java:66) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.b7.a(b7.java:140) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.k4.c(k4.java:2824) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.k4.a(k4.java:2261) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.t4.ab.r(ab.java:1654) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.t4.ab.l(ab.java:751) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.t4.ab.d(ab.java:112) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.t4.p.c(p.java:44) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.t4.av.j(av.java:162) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.k4.an(k4.java:2256) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.k5.a(k5.java:4637) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.k5.b(k5.java:4182) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.k5.be(k5.java:827) ~[db2jcc4.jar:?]
    at com.ibm.db2.jcc.am.k5.executeUpdate(k5.java:801) ~[db2jcc4.jar:?]
    at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
    at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
    at com.sun.proxy.$Proxy49.executeUpdate(Unknown Source) ~[?:?]
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.updateAPIPolicy_aroundBody496(ApiMgtDAO.java:10545) ~[org.wso2.carbon.apimgt.impl_6.7.192.jar:?]
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.updateAPIPolicy(ApiMgtDAO.java:10526) ~[org.wso2.carbon.apimgt.impl_6.7.192.jar:?]
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.updateAPIPolicy_aroundBody552(ApiMgtDAO.java:11771) ~[org.wso2.carbon.apimgt.impl_6.7.192.jar:?]
    ... 58 more
```

### Steps to reproduce:

- Configure API Manager v3.2.0 - RC5 with DB2
- Start the API Manager
- Go to Admin Portal and try editing an existing `Advanced Policy`

### Affected Product Version:

- API Manager 3.2.0 - RC5

**Comment by renuka-fernando** [comment]
Tested in APIM Snapshot 6.7.206 and IBM DB2 version 11.5.4 as the DB.
Could update Advanced Policies successfully.

**Comment by hisanhunais** [comment]
Fixed via https://github.com/wso2/carbon-apimgt/pull/9211
