### ISSUE TITLE
Ciphertool is not working properly with commented out values in deployment.toml

### ISSUE THREAD

**Issue by arunans23** [wso2/product-apim#9127]
### Description:

With commented out values in deployment.toml, Ciphertool.sh is not working properly. It throws the following errors.

```
➜  wso2am-3.2.0 ./bin/ciphertool.sh -Dconfigure

Encrypting using Internal KeyStore.
{type: JKS, alias: wso2carbon, path: /Users/arunan/mytmp/wso2am-3.2.0/repository/resources/security/wso2carbon.jks}

[Please Enter Internal KeyStore Password of Carbon Server : ]

Internal KeyStore of Carbon Server is initialized Successfully


Encryption is done Successfully

Exception in thread "main" java.lang.NullPointerException
	at java.lang.String.concat(String.java:2027)
	at org.wso2.ciphertool.CipherTool.updateDeploymentConfigurationWithEncryptedKeys(CipherTool.java:394)
	at org.wso2.ciphertool.CipherTool.main(CipherTool.java:75)
```

### Steps to reproduce:

Use the following deployment.toml (I have added a secret value in the middle). Use ciphertool to encrypt the secret. The above error is throw and all configuration defined below secret section will be removed.

[deployment.txt](https://github.com/wso2/product-apim/files/5094268/deployment.txt)

### Affected Product Version:

3.2.0-RC5

**Comment by arunans23** [comment]
Fix with https://github.com/wso2/cipher-tool/pull/66
Relevant cipher tool version is updated in the product.
