### ISSUE TITLE
"WARN - DataProcessAndPublishingAgent Client port will be ignored and only the IP address will concern from 0:0:0:0:0:0:0:1" Log printed when invoking an API.

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/product-apim#9149]
### Description:
When invoking an API in windows environment the following warn logs were printed:

```
[2020-08-20 14:22:06,122]  WARN - DataProcessAndPublishingAgent Client port will be ignored and only the IP address will concern from 0:0:0:0:0:0:0:1
Exception in thread "pool-117-thread-1" java.lang.ArrayIndexOutOfBoundsException: 1
        at org.wso2.carbon.apimgt.impl.utils.APIUtil.ipToLong_aroundBody556(APIUtil.java:8550)
        at org.wso2.carbon.apimgt.impl.utils.APIUtil.ipToLong(APIUtil.java:8545)
        at org.wso2.carbon.apimgt.gateway.throttling.publisher.DataProcessAndPublishingAgent.run_aroundBody4(DataProcessAndPublishingAgent.java:210)
        at org.wso2.carbon.apimgt.gateway.throttling.publisher.DataProcessAndPublishingAgent.run(DataProcessAndPublishingAgent.java:186)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce:
Configure APIM 3.2.0-RC5 in Windows with MsSQL and create an API from the publisher. Then, log into the DevPortal and invoke an API.

### Environment details (with versions):
- OS: Windows 10 Home
- DB: MsSQL Server 2019

**Comment by RAVEENSR** [comment]
You can also see an error in the APIM 2.6.0 pack as following:

```
[2020-09-17 15:57:07,592]  WARN - DataProcessAndPublishingAgent Client port will be ignored and only the IP address will concern from 2a02:c7f:1eb9:a00:d595:20c2:5b9b:743a
[2020-09-17 15:57:07,596] ERROR - DataProcessAndPublishingAgent Error while parsing host IP 2a02
java.net.UnknownHostException: 2a02: nodename nor servname provided, or not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at java.net.InetAddress.getByName(InetAddress.java:1077)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getAddress_aroundBody446(APIUtil.java:7051)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getAddress(APIUtil.java:7050)
	at org.wso2.carbon.apimgt.gateway.throttling.publisher.DataProcessAndPublishingAgent.run_aroundBody4(DataProcessAndPublishingAgent.java:181)
	at org.wso2.carbon.apimgt.gateway.throttling.publisher.DataProcessAndPublishingAgent.run(DataProcessAndPublishingAgent.java:159)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

We can reproduce this error by invoking an API using the cURL with an IPv6 address in the x-forwarded-for header.
Ex:
`curl -k -X POST "https://192.168.1.15:8243/pizzashack/1.0.0/order" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer 098362ad-4d63-35ba-90b9-3dc7f05c724b" -d "{ \"customerName\": \"string\", \"delivered\": true, \"address\": \"string\", \"pizzaType\": \"string\", \"creditCardNumber\": \"string\", \"quantity\": 0, \"orderId\": \"string\"}" --header "X-Forwarded-For: 2a02:c7f:1eb9:a00:d595:20c2:5b9b:743a"`
