### ISSUE TITLE
ClassNotFoundException when running forgetme tool

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#9182]
### Description:
Getting the ClassNotFoundException error when running forgetme.sh.

```
2020-08-25 13:39:36 INFO  ForgetMeTool:183 - Generating pseudonym as pseudo name is not provided : 818ccf3c-e212-470c-b1bd-a33a727a0ccf
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/istack/Pool
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1126)                                                                           
...
dushaniw@dushaniw:~/RnD/3.2_testing/RC6/wso2am-3.2.0/bin$ sh forgetme.sh -U user1@abc.com
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/dushaniw/RnD/3.2_testing/RC6/wso2am-3.2.0/repository/components/tools/forget-me/lib/slf4j-log4j12-1.7.26.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dushaniw/RnD/3.2_testing/RC6/wso2am-3.2.0/repository/components/tools/forget-me/lib/pax-logging-api-1.11.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2020-08-25 13:39:36 INFO  ForgetMeTool:183 - Generating pseudonym as pseudo name is not provided : 818ccf3c-e212-470c-b1bd-a33a727a0ccf
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/istack/Pool
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1126)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:247)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:234)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:441)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:641)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:584)
	at org.wso2.carbon.datasource.utils.DataSourceUtils.loadJAXBConfiguration(DataSourceUtils.java:344)
	at org.wso2.carbon.datasource.core.DataSourceManager.initDataSource(DataSourceManager.java:159)
	at org.wso2.carbon.datasource.core.DataSourceManager.initDataSources(DataSourceManager.java:137)
	at org.wso2.carbon.datasource.core.DataSourceManager.initDataSources(DataSourceManager.java:109)
	at org.wso2.carbon.privacy.forgetme.sql.instructions.DatasourceProcessorConfigReader.readProcessorConfig(DatasourceProcessorConfigReader.java:45)
	at org.wso2.carbon.privacy.forgetme.sql.instructions.DatasourceProcessorConfigReader.readProcessorConfig(DatasourceProcessorConfigReader.java:32)
	at org.wso2.carbon.privacy.forgetme.ConfigReader.loadExtensions(ConfigReader.java:213)
	at org.wso2.carbon.privacy.forgetme.ConfigReader.readSystemConfig(ConfigReader.java:112)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.process(ForgetMeTool.java:201)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.main(ForgetMeTool.java:141)
Caused by: java.lang.ClassNotFoundException: com.sun.istack.Pool
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 21 more

```

### Steps to reproduce:
Run forgetme.sh by providing a deleted username.

### Affected Product Version:
API-M 3.2 RC

**Comment by dushaniw** [comment]
Need to add jar [1] to `repository/components/tools/forget-me/lib`

[1] https://mvnrepository.com/artifact/com.sun.istack/istack-commons-runtime

**Comment by dushaniw** [comment]
Getting following afterwards,
```
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:repository/database/WSO2METRICS_DB;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
```

Change the `metrics-datasource.xml`
`                 <url>jdbc:h2:./repository/database/WSO2METRICS_DB;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE</url>`

**Comment by isharac** [comment]
missing lib  fix is available in [1]

[1] https://github.com/wso2/identity-anonymization-tool/issues/120

metrics-datasource.xml issue is fixed with [2]
https://github.com/wso2/carbon-metrics/pull/97
