### ISSUE TITLE
[3.2.0][MySQL] Error in  creating Users and Roles

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim#9193]
### Description:

When listing the created users or roles in carbon console error encountered. And the users and roles are also not getting created.

![Screenshot from 2020-08-27 10-28-44](https://user-images.githubusercontent.com/60866295/91386230-2a202980-e850-11ea-85f7-4f0a34e85d5f.png)

Error Stack:

```
[2020-08-27 10:02:47,704] ERROR - JDBCUserStoreManager Error while retrieving roles from Internal JDBC role store
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'OPTION SQL_SELECT_LIMIT=100' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_251]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_251]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1031) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3376) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3308) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1837) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1961) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2537) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.StatementImpl.executeSimpleNonQuery(StatementImpl.java:1463) ~[com.mysql.jdbc_5.1.5.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1875) ~[com.mysql.jdbc_5.1.5.jar:?]
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
	at com.sun.proxy.$Proxy49.executeQuery(Unknown Source) ~[?:?]
	at org.wso2.carbon.user.core.hybrid.HybridRoleManager.getHybridRoles(HybridRoleManager.java:299) [org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getHybridRoles(AbstractUserStoreManager.java:8188) [org.wso2.carbon.user.core_4.6.0.jar:?]
	at org.wso2.carbon.user.mgt.UserRealmProxy.getRolesOfUser(UserRealmProxy.java:1452) [org.wso2.carbon.user.mgt_5.17.5.jar:?]
	at org.wso2.carbon.user.mgt.UserAdmin.getRolesOfUser(UserAdmin.java:424) [org.wso2.carbon.user.mgt_5.17.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at org.apache.axis2.rpc.receivers.RPCUtil.invokeServiceClass(RPCUtil.java:212) [axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.rpc.receivers.RPCMessageReceiver.invokeBusinessLogic(RPCMessageReceiver.java:117) [axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:40) [axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110) [axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) [axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:170) [axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:82) [axis2_1.6.1.wso2v41.jar:?]
	at org.wso2.carbon.core.transports.local.CarbonLocalTransportSender.finalizeSendWithToAddress(CarbonLocalTransportSender.java:45) [org.wso2.carbon.core_4.6.0.jar:?]
	at org.apache.axis2.transport.local.LocalTransportSender.invoke(LocalTransportSender.java:77) [axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442) [axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:442) [axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228) [axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149) [axis2_1.6.1.wso2v41.jar:?]
	at org.wso2.carbon.user.mgt.stub.UserAdminStub.getRolesOfUser(UserAdminStub.java:2530) [org.wso2.carbon.user.mgt.stub_5.17.5.jar:?]
	at org.wso2.carbon.user.mgt.ui.UserAdminClient.getRolesOfUser(UserAdminClient.java:154) [org.wso2.carbon.user.mgt.ui_5.17.5.jar:?]
	at org.apache.jsp.user.add_002dstep2_jsp._jspService(add_002dstep2_jsp.java:297) [hc_14950485/:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [tomcat_9.0.31.wso2v1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.31.wso2v1.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) [tomcat_9.0.31.wso2v1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:207) [org.wso2.carbon.ui_4.6.0.jar:?]
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80) [org.wso2.carbon.ui_4.6.0.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.31.wso2v1.jar:?]
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37) [org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:580) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:516) [tomcat_9.0.31.wso2v1.jar:?]
	at org.eclipse.equinox.http.servlet.internal.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:37) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor$RequestDispatcherAdaptor.include(ContextPathServletAdaptor.java:369) [org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:955) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.jasper.runtime.PageContextImpl.include(PageContextImpl.java:496) [tomcat_9.0.31.wso2v1.jar:?]
	at sun.reflect.GeneratedMethodAccessor181.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at org.apache.tiles.jsp.context.JspUtil.doInclude(JspUtil.java:87) [tiles-jsp_2.0.5.wso2v1.jar:?]
	at org.apache.tiles.jsp.context.JspTilesRequestContext.include(JspTilesRequestContext.java:88) [tiles-jsp_2.0.5.wso2v1.jar:?]
	at org.apache.tiles.jsp.context.JspTilesRequestContext.dispatch(JspTilesRequestContext.java:82) [tiles-jsp_2.0.5.wso2v1.jar:?]
	at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:465) [tiles-jsp_2.0.5.wso2v1.jar:?]
	at org.apache.tiles.jsp.taglib.InsertAttributeTag.render(InsertAttributeTag.java:140) [tiles-jsp_2.0.5.wso2v1.jar:?]
	at org.apache.tiles.jsp.taglib.InsertAttributeTag.render(InsertAttributeTag.java:117) [tiles-jsp_2.0.5.wso2v1.jar:?]
	at org.apache.tiles.jsp.taglib.RenderTagSupport.execute(RenderTagSupport.java:171) [tiles-jsp_2.0.5.wso2v1.jar:?]
	at org.apache.tiles.jsp.taglib.RoleSecurityTagSupport.doEndTag(RoleSecurityTagSupport.java:75) [tiles-jsp_2.0.5.wso2v1.jar:?]
	at org.apache.tiles.jsp.taglib.ContainerTagSupport.doEndTag(ContainerTagSupport.java:80) [tiles-jsp_2.0.5.wso2v1.jar:?]
	at org.apache.jsp.admin.layout.template_jsp._jspx_meth_tiles_005finsertAttribute_005f7(template_jsp.java:780) [hc_14950485/:?]
```

### Steps to reproduce:

1. Login to carbon console.
2. Create a new user.
3. List the created users

### Affected Product Version:
APIM 3.2.0

**Comment by Sarangan0219** [comment]
This issue is related to the MySQL Driver version. Upgrading the driver version Resolves this issue.
