### ISSUE TITLE
Error in invoking API after Custom Correlation Header Name

### ISSUE THREAD

**Issue by chaliya96** [wso2/product-apim#9239]
### Description:
In APIM v3.1.0 after changing the correlation header using correlation_header_name property, the following error is getting when invoking an API. 

`[2020-09-07 18:15:32,500] ERROR - NativeWorkerPool Uncaught exception
java.lang.NullPointerException: null Exception in thread "PassThroughMessageProcessor-21" java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:460)
	at org.ops4j.pax.logging.spi.support.EventAdminTracker.createEvent(EventAdminTracker.java:195)
	at org.ops4j.pax.logging.spi.support.EventAdminTracker.postEvent(EventAdminTracker.java:60)
	at org.ops4j.pax.logging.log4j2.internal.PaxLoggingServiceImpl.handleEvents(PaxLoggingServiceImpl.java:322)
	at org.ops4j.pax.logging.log4j2.internal.PaxLoggerImpl.doLog0(PaxLoggerImpl.java:358).     at org.ops4j.pax.logging.log4j2.internal.PaxLoggerImpl.doLog(PaxLoggerImpl.java:337)	at org.ops4j.pax.logging.log4j2.internal.PaxLoggerImpl.error(PaxLoggerImpl.java:163)	at org.ops4j.pax.logging.internal.TrackingLogger.error(TrackingLogger.java:130)
	at org.ops4j.pax.logging.jcl.JclLogger.error(JclLogger.java:133)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:174)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

### Steps to reproduce:
Add the following property to deployment.toml 
```
[passthru_http] 
correlation_header_name="custom-header-name"
```
Start the APIM with -DenableCorrelationLogs=true
### Affected Product Version:
3.1.0

**Comment by mushthaq33** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/9263
