### ISSUE TITLE
Improve the products to use with MariaDB driver for MariaDB database

### ISSUE THREAD

**Issue by Methma** [wso2/product-apim#9266]
### Describe your problem(s)
Currently, we are recommending to use the MySQL JDBC driver to connect with MariaDB. Several errors can be observed as below if someone uses the MariaDB connector.

> ERROR {org.wso2.carbon.apimgt.impl.internal.APIManagerComponent} - Error while initializing the API manager component org.wso2.carbon.apimgt.api.APIManagementException: Error occurred while initializing SQL Constants Manager
>         at org.wso2.carbon.apimgt.impl.factory.SQLConstantManagerFactory.initializeSQLConstantManager_aroundBody0(SQLConstantManagerFactory.java:79)
>         at org.wso2.carbon.apimgt.impl.factory.SQLConstantManagerFactory.initializeSQLConstantManager(SQLConstantManagerFactory.java:50)
>         at org.wso2.carbon.apimgt.impl.internal.APIManagerComponent.activate_aroundBody0(APIManagerComponent.java:222)
>         at org.wso2.carbon.apimgt.impl.internal.APIManagerComponent.activate(APIManagerComponent.java:139)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

> ERROR {org.wso2.carbon.identity.application.authentication.framework.store.SessionDataStore} - Error while retrieving session data java.sql.SQLSyntaxErrorException: (conn=103622) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE ROWNUM < 2' at line 1
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)

There is a request to make the products compatible with the MariaDB driver.

**Comment by acotty** [comment]
More details on mariadb issue including some code analysis:
http://wso2-oxygen-tank.10903.n7.nabble.com/MariaDB-support-for-WSO2-API-Manager-3-1-0-or-newer-td161753.html

**Comment by scara** [comment]
Hello Everybody,
any update?

APIM 400 (the one released here in GH) is affected too: the _Control Plane_ breaks while the _Gateway Worker_ runs fine even with MariaDB Connector/J 2.7.3.

It looks like `DriverName` of the Connector/J is taken into account to verify if the DB Server WSO2 is running on is MySQL or "a MySQL drop-in replacement" i.e. you need to stick with the MySQL driver since the MariaDB one is named in a different way (!).

TIA,
Matteo
