### ISSUE TITLE
Error when confirguring access log rotation with the modified date format

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#9354]
### Description:
After the fix for https://github.com/wso2/product-apim/issues/7632 following error can be observed when access log rotation is enabled.

```
[2020-10-13 11:27:07,872] ERROR - access Error occurred when parsing the date from existing log file
java.text.ParseException: Unparseable date: "13/Oct/2020:11:21:16.640 +0530"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at org.apache.synapse.transport.http.access.AccessLogger.open(AccessLogger.java:227)
	at org.apache.synapse.transport.http.access.AccessLogger.initOpen(AccessLogger.java:183)
	at org.apache.synapse.transport.http.access.AccessLogger.<init>(AccessLogger.java:67)
	at org.apache.synapse.transport.http.access.AccessHandler.<clinit>(AccessHandler.java:32)
	at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection$LoggingNHttpMessageParser.parse(LoggingNHttpServerConnection.java:430)
	at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection$LoggingNHttpMessageParser.parse(LoggingNHttpServerConnection.java:381)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:265)
	at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection.consumeInput(LoggingNHttpServerConnection.java:114)
	at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:82)
	at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	at java.lang.Thread.run(Thread.java:745)
```

This is because the DATE_FORMAT_STRING in AccessLogger.java [1] has not been updated properly in the support branch along with the fix for https://github.com/wso2/product-apim/issues/7632. The fix is already there in the synapse master branch.

*Proposed Fix*
```
private final static String DATE_FORMAT_STRING = "dd/MMM/yyyy:HH:mm:ss.SSS Z";
```

[1]. https://github.com/wso2-support/wso2-synapse/blob/support-2.1.7-wso2v80/modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/AccessLogger.java#L61

### Steps to reproduce:
1. Configure access logs with log rotation enabled per date. https://docs.wso2.com/display/AM260/Monitoring+Access+Logs
2. Start the server and invoke an API

### Affected Product Version:
APIM 2.6.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by HiranyaKavishani** [comment]
Fixed by https://github.com/wso2/wso2-synapse/blob/master/modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/AccessLogger.java#L59
