### ISSUE TITLE
[2.6.0] Error when Populating Standard Claims with JWT Generator

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#9366]
### Description:

The following error-trace is observed when trying to generate a Backend JWT with the latest improvements in the JWT Generator and with Third-party Key Managers in place

```log
TID: [-1234] [] [2020-10-14 18:21:42,065] ERROR {org.wso2.carbon.apimgt.keymgt.handlers.AbstractKeyValidationHandler} - Error occurred while generating JWT.
org.wso2.carbon.apimgt.api.APIManagementException: Error occurred while getting JWT Token client ID : xxxxx-xxxxxx-xxxxxxx-xxxx 
    at org.wso2.carbon.apimgt.keymgt.token.JWTGenerator.populateStandardClaims_aroundBody0(JWTGenerator.java:115) 
    at org.wso2.carbon.apimgt.keymgt.token.JWTGenerator.populateStandardClaims(JWTGenerator.java:67) 
    ...
    at org.wso2.carbon.apimgt.keymgt.handlers.AbstractKeyValidationHandler.generateConsumerToken_aroundBody6(AbstractKeyValidationHandler.java:135)
Caused by: org.wso2.carbon.identity.oauth.common.exception.InvalidOAuthClientException: Cannot find an application associated with the given consumer key : xxxxx-xxxxxx-xxxxxxx-xxxx 
    at org.wso2.carbon.identity.oauth.dao.OAuthAppDAO.handleRequestForANonExistingConsumerKey(OAuthAppDAO.java:1202) 
    at org.wso2.carbon.identity.oauth.dao.OAuthAppDAO.getAppInformation(OAuthAppDAO.java:389) 
    at org.wso2.carbon.identity.oauth2.util.OAuth2Util.getAppInformationByClientId(OAuth2Util.java:1737) 
    at org.wso2.carbon.apimgt.keymgt.token.JWTGenerator.populateStandardClaims_aroundBody0(JWTGenerator.java:104)
```

### Affected Product Version:
- API Manager v2.6.0 + 1601313472144

**Comment by dushaniw** [comment]
@Arshardh can we close this issue if this is not related to the latest build?
