### ISSUE TITLE
Swagger Schema Validation issue

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/product-apim#9491]
### Description:
The below error trace can be observed when there is a schema validation for a resource with a trailing slash - ex: /items/.

```
ERROR - ServerWorker Error processing POST request for : /test/0.1.0/items/. 

java.lang.ArrayIndexOutOfBoundsException: 1

	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.extractReference_aroundBody26(SchemaValidator.java:547) ~[org.wso2.carbon.apimgt.gateway_6.7.206.jar:?]

	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.extractReference(SchemaValidator.java:545) ~[org.wso2.carbon.apimgt.gateway_6.7.206.jar:?]

	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.extractSchemaFromRequest_aroundBody18(SchemaValidator.java:358) ~[org.wso2.carbon.apimgt.gateway_6.7.206.jar:?]

	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.extractSchemaFromRequest(SchemaValidator.java:329) ~[org.wso2.carbon.apimgt.gateway_6.7.206.jar:?]

	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.getSchemaContent_aroundBody16(SchemaValidator.java:316) ~[org.wso2.carbon.apimgt.gateway_6.7.206.jar:?]

	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.getSchemaContent(SchemaValidator.java:313) ~[org.wso2.carbon.apimgt.gateway_6.7.206.jar:?]

	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.validateRequest_aroundBody8(SchemaValidator.java:221) ~[org.wso2.carbon.apimgt.gateway_6.7.206.jar:?]

	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.validateRequest(SchemaValidator.java:219) ~[org.wso2.carbon.apimgt.gateway_6.7.206.jar:?]

	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.handleRequest_aroundBody2(SchemaValidator.java:122) ~[org.wso2.carbon.apimgt.gateway_6.7.206.jar:?]

	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.handleRequest(SchemaValidator.java:79) ~[org.wso2.carbon.apimgt.gateway_6.7.206.jar:?]

	at org.apache.synapse.rest.API.process(API.java:373) ~[synapse-core_2.1.7.wso2v183.jar:2.1.7-wso2v183]

	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:144) ~[synapse-core_2.1.7.wso2v183.jar:2.1.7-wso2v183]

	at org.apache.synapse.rest.RESTRequestHandler.identifyAPI(RESTRequestHandler.java:164) ~[synapse-core_2.1.7.wso2v183.jar:2.1.7-wso2v183]

	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95) ~[synapse-core_2.1.7.wso2v183.jar:2.1.7-wso2v183]

	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:73) ~[synapse-core_2.1.7.wso2v183.jar:2.1.7-wso2v183]

	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:331) ~[synapse-core_2.1.7.wso2v183.jar:2.1.7-wso2v183]

	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:99) ~[synapse-core_2.1.7.wso2v183.jar:2.1.7-wso2v183]

	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v41.jar:?]

	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367) [synapse-nhttp-transport_2.1.7.wso2v183.jar:?]

	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:426) [synapse-nhttp-transport_2.1.7.wso2v183.jar:?]

	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181) [synapse-nhttp-transport_2.1.7.wso2v183.jar:?]

	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41.jar:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
```
The cause for the issue is the "schemaNode" that passed for the "extractReference" method is empty and while checking below it fails.
```
String[] val = schemaNode.split("" + APIMgtGatewayConstants.HASH);
String path = val[1].replaceAll("\"|}|]|\\\\", "");
```
There is a difference between the resource which we get from the swagger definition (/items/) and one we got from the "messageContext.getProperty(APIMgtGatewayConstants.API_ELECTED_RESOURCE).toString();" (/items - without trailing slash). Due to that, the schema is not correctly picking by "$..paths../items..requestBody.content.application/json.schema" and became empty.
```
jsonPath.append(APIMgtGatewayConstants.PATHS)
        .append(resourcePath).append(APIMgtGatewayConstants.BODY_CONTENT);
schema = JsonPath.read(Swagger, jsonPath.toString()).toString();
```

### Affected Product Version:
3.2.0

**Comment by riyazathali** [comment]
Affected Product Version:
3.1.0 and 3.2.0

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/9430
