### ISSUE TITLE
Issues due to unavailability of primary key constraint in some tables when MySQL database cluster is used with Group Replication

### ISSUE THREAD

**Issue by Prasadi-R** [wso2/product-apim#9505]
### Describe your problem(s)
When MySQL database cluster is used with Group Replication, it is mandatory to have the primary key constraint for all the tables. 

But the available dbscripts in the APIM server for 'apim_db' and 'shared_db' is missing the primary key constraint for some of the tables. Hence, could observe below error stack traces at the server startup and when the server is running.
````
TID: [-1234] [] [2020-11-05 15:49:14,250] ERROR {org.wso2.carbon.registry.core.utils.RegistryUtils} - Unable to create fixed remote mounts. org.wso2.carbon.registry.core.exceptions.RegistryException: Unable to put resource Failed to add properties to the resource /_system/config/repository/components/org.wso2.carbon.governance/media-types/index. The table does not comply with the requirements by an external plugin.
	at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:299)
. . . .
Caused by: org.wso2.carbon.registry.core.exceptions.RegistryException: Failed to add properties to the resource /_system/config/repository/components/org.wso2.carbon.governance/media-types/index. The table does not comply with the requirements by an external plugin.
. . . .
Caused by: java.sql.SQLException: The table does not comply with the requirements by an external plugin.
. . . .
````
````
TID: [-1234] [] [2020-11-09 17:12:00,412] ERROR {org.wso2.carbon.identity.oauth2.util.OAuth2Util} - Error while registering OAuth scopes with permissions bindings org.wso2.carbon.identity.oauth2.IdentityOAuth2ScopeServerException: SQL error occurred while creating scope :internal_feature_management
at org.wso2.carbon.identity.oauth2.dao.OAuthScopeDAOImpl.addScope(OAuthScopeDAOImpl.java:90)
. . . .
```` 
### Describe your solution
The following table list need to have the primary key constraint,
**shared_db:**
REG_RESOURCE_COMMENT
REG_RESOURCE_PROPERTY
REG_RESOURCE_RATING
REG_RESOURCE_TAG
UM_SHARED_USER_ROLE

**apim_db:**
IDN_OAUTH2_ACCESS_TOKEN_AUDIT
IDN_OAUTH2_SCOPE_BINDING
IDN_AUTH_USER_SESSION_MAPPING
IDN_OAUTH2_CIBA_REQUEST_SCOPES
CM_SP_PURPOSE_PURPOSE_CAT_ASSC
CM_PURPOSE_PII_CAT_ASSOC
CM_SP_PURPOSE_PII_CAT_ASSOC
CM_CONSENT_RECEIPT_PROPERTY
AM_ALERT_EMAILLIST_DETAILS
AM_ALERT_TYPES_VALUES

It would be better if a note can be added to the respective documents [1], [2] as well.

#### Related Issues:
https://github.com/wso2/product-apim/issues/3923
https://github.com/wso2/product-is/issues/3898

#### Affected Product Version:
APIM-3.1.0, APIM-3.2.0

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql/
[2] https://apim.docs.wso2.com/en/3.1.0/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql/#!

**Comment by Prasadi-R** [comment]
#### Correction:
The following two tables in the **apim_db** already contain the primary key constraint.

AM_ALERT_EMAILLIST_DETAILS
AM_ALERT_TYPES_VALUES

**Comment by isharac** [comment]
Fixed in the docs.
