### ISSUE TITLE
Throwing errors when starting with -Dprofile=gateway-worker

### ISSUE THREAD

**Issue by chanakaudaya** [wso2/product-apim#9548]
### Description:
When I'm trying to start the worker profile, it throws the below error. Full error is attached as a file since it was too large for a comment. 

```
java.lang.ClassNotFoundException: org.wso2.carbon.identity.captcha.filter.CaptchaFilter
	at org.wso2.carbon.webapp.mgt.loader.CarbonWebappClassLoader.loadClass(CarbonWebappClassLoader.java:195) ~[org.wso2.carbon.webapp.mgt_4.10.1.jar:?]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188) ~[tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:540) ~[tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:521) ~[tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:150) ~[tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:249) ~[tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:102) ~[tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4538) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5177) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705) [tomcat_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.internal.CarbonTomcat.addWebApp(CarbonTomcat.java:303) [org.wso2.carbon.tomcat_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.internal.CarbonTomcat.addWebApp(CarbonTomcat.java:209) [org.wso2.carbon.tomcat_4.6.0.jar:?]
	at org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer.handleWebappDeployment(TomcatGenericWebappsDeployer.java:255) [org.wso2.carbon.webapp.mgt_4.10.1.jar:?]
	at org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer.handleWarWebappDeployment(TomcatGenericWebappsDeployer.java:206) [org.wso2.carbon.webapp.mgt_4.10.1.jar:?]
	at org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer.handleHotDeployment(TomcatGenericWebappsDeployer.java:175) [org.wso2.carbon.webapp.mgt_4.10.1.jar:?]
	at org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer.deploy(TomcatGenericWebappsDeployer.java:140) [org.wso2.carbon.webapp.mgt_4.10.1.jar:?]
	at org.wso2.carbon.webapp.mgt.AbstractWebappDeployer.deployThisWebApp(AbstractWebappDeployer.java:224) [org.wso2.carbon.webapp.mgt_4.10.1.jar:?]
	at org.wso2.carbon.webapp.mgt.AbstractWebappDeployer.deploy(AbstractWebappDeployer.java:114) [org.wso2.carbon.webapp.mgt_4.10.1.jar:?]
	at org.wso2.carbon.webapp.deployer.WebappDeployer.deploy(WebappDeployer.java:42) [org.wso2.carbon.webapp.deployer_4.10.1.jar:?]
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136) [axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807) [axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144) [axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377) [axis2_1.6.1.wso2v41.jar:?]
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254) [axis2_1.6.1.wso2v41.jar:?]
	at org.apache.synapse.Axis2SynapseController.deployMediatorExtensions(Axis2SynapseController.java:783) [synapse-core_2.1.7.wso2v183.jar:2.1.7-wso2v183]
	at org.apache.synapse.Axis2SynapseController.createSynapseEnvironment(Axis2SynapseController.java:407) [synapse-core_2.1.7.wso2v183.jar:2.1.7-wso2v183]
	at org.apache.synapse.ServerManager.start(ServerManager.java:187) [synapse-core_2.1.7.wso2v183.jar:2.1.7-wso2v183]
	at org.wso2.carbon.mediation.initializer.ServiceBusInitializer.initESB(ServiceBusInitializer.java:371) [org.wso2.carbon.mediation.initializer_4.7.61.jar:?]
	at org.wso2.carbon.mediation.initializer.ServiceBusInitializer.activate(ServiceBusInitializer.java:170) [org.wso2.carbon.mediation.initializer_4.7.61.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.inbound.endpoint.persistence.service.InboundEndpointPersistenceServiceDSComponent.activate(InboundEndpointPersistenceServiceDSComponent.java:50) [org.wso2.carbon.inbound.endpoint.persistence_4.7.61.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529) [org.wso2.carbon.core_4.6.0.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) [org.wso2.carbon.core_4.6.0.jar:?]
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) [org.wso2.carbon.core_4.6.0.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
[2020-11-23 21:19:11,106] ERROR - StandardContext One or more Filters failed to start. Full details will be found in the appropriate container log file
[2020-11-23 21:19:11,106] ERROR - StandardContext Context [/api/identity/recovery/v0.9] startup failed due to previous errors
```
### Steps to reproduce:
Start the WSO2 API Manager server with below command
sh bin/wso2server.sh -Dprofile=gateway-worker

### Affected Product Version:
APIM 3.2.0 WUM (wso2am-3.2.0+1599802896156.full)
### Environment details (with versions):
- OS:Mac OS Catalina 10.15.7
- Client: iTerm
- Env (Docker/K8s): Standard binary

**Comment by chanakaudaya** [comment]
[apim-worker-profile-start-error.txt](https://github.com/wso2/product-apim/files/5584174/apim-worker-profile-start-error.txt)

**Comment by DaniduWijendra** [comment]
These errors can happen when you have started the APIM server as a gateway worker profile without running the profile optimization script. Once you have updated the APIM pack, you need to run a profile optimization script to remove unwanted jar files and war files.

You can follow the below steps to profile optimize the gateway-worker node.

Go to the <APIM_HOME>/repository/conf directory and backup the deployment.toml file.

Go to the **<APIM_HOME>/bin** directory and execute the below command to optimize the API Manager pack as a gateway worker. (This will optimize and remove files in the API Manager pack that are not needed to run the API manager as a gateway-worker profile)
`sh profileSetup.sh -Dprofile=gateway-worker`


Restore the deployment.toml file and execute the below command to start the API Manager as a gateway-worker.
`sh wso2server.sh -Dprofile=gateway-worker
`
[1] https://apim.docs.wso2.com/en/3.2.0/install-and-setup/setup/distributed-deployment/product-profiles/

**Comment by anjuchamantha** [comment]
Hi @DaniduWijendra ,

I got the same error as above and ran the `sh profileSetup.sh -Dprofile=gateway-worker` as mentioned. It removed multiple files. 

> $ sh profileSetup.sh -Dprofile=gateway-worker
[2024-12-13 11:57:14] INFO - Starting to optimize API Manager for the Gateway worker profile
[2024-12-13 11:57:14] INFO - Starting to optimize configs in deployment.toml
[2024-12-13 11:57:14] INFO - Renamed the existing ../repository/conf/deployment.toml file as deployment.toml.backup
[2024-12-13 11:57:14] INFO - Copied the existing ../repository/resources/conf/deployment-templates/gateway-worker.toml file as ../repository/conf/deployment.toml
[2024-12-13 11:57:14] INFO - Renamed the existing ../repository/resources/conf/templates/repository/conf/tomcat/carbon/WEB-INF/web.xml.j2 file as web.xml.j2.backup
[2024-12-13 11:57:14] INFO - Renamed the existing ../repository/resources/conf/templates/repository/conf/tomcat/carbon/WEB-INF/web_TM_GW.xml.j2 file as web.xml.j2
[2024-12-13 11:57:14] INFO - Removed the file ../repository/resources/conf/templates/repository/deployment/server/webapps/authenticationendpoint/WEB-INF/web.xml.j2
[2024-12-13 11:57:14] INFO - Removed the file ../repository/resources/conf/templates/repository/deployment/server/webapps/accountrecoveryendpoint/WEB-INF/web.xml.j2
[2024-12-13 11:57:14] INFO - Removed the api#am#service-catalog#v1 file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the devportal file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the api#identity#oauth2#dcr#v1.1.war file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed api#identity#oauth2#dcr#v1.1 directory from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the api#am#publisher.war file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed api#am#publisher directory from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the api#identity#user#v1.0.war file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed api#identity#user#v1.0 directory from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the admin file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the accountrecoveryendpoint file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the api#am#gateway#v2 file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the api#identity#oauth2#v1.0.war file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed api#identity#oauth2#v1.0 directory from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the publisher file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the authenticationendpoint file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the api#identity#recovery#v0.9.war file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed api#identity#recovery#v0.9 directory from ../repository/deployment/server/webapps
rm: cannot remove '../repository/deployment/server/webapps/api#identity#user#v1.0': No such file or directory
[2024-12-13 11:57:14] INFO - Removed the api#identity#user#v1.0 file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the package.json file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the am#sample#calculator#v1.war file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed am#sample#calculator#v1 directory from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the client-registration#v0.17 file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the am#sample#pizzashack#v1 file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the api#am#devops#v0 file from ../repository/deployment/server/webapps
rm: cannot remove '../repository/deployment/server/webapps/api#identity#oauth2#dcr#v1.1': No such file or directory
[2024-12-13 11:57:14] INFO - Removed the api#identity#oauth2#dcr#v1.1 file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the keymanager-operations file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the api#am#devportal file from ../repository/deployment/server/webapps
rm: cannot remove '../repository/deployment/server/webapps/api#am#publisher': No such file or directory
[2024-12-13 11:57:14] INFO - Removed the api#am#publisher file from ../repository/deployment/server/webapps
rm: cannot remove '../repository/deployment/server/webapps/api#identity#recovery#v0.9': No such file or directory
[2024-12-13 11:57:14] INFO - Removed the api#identity#recovery#v0.9 file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the api#openbanking#uk#backend file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the api#identity#consent-mgt#v1.0 file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the api#am#admin.war file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed api#am#admin directory from ../repository/deployment/server/webapps
rm: cannot remove '../repository/deployment/server/webapps/api#identity#oauth2#v1.0': No such file or directory
[2024-12-13 11:57:14] INFO - Removed the api#identity#oauth2#v1.0 file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the keymanager-operations.war file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the lerna.json file from ../repository/deployment/server/webapps
rm: cannot remove '../repository/deployment/server/webapps/api#am#admin': No such file or directory
[2024-12-13 11:57:14] INFO - Removed the api#am#admin file from ../repository/deployment/server/webapps
[2024-12-13 11:57:14] INFO - Removed the api#am#devops#v0.war file from ../repository/deployment/server/webapps
[2024-12-13 11:57:15] INFO - Removed the api#openbanking#uk#backend.war file from ../repository/deployment/server/webapps
[2024-12-13 11:57:15] INFO - Removed the internal#data#v1 file from ../repository/deployment/server/webapps
[2024-12-13 11:57:15] INFO - Removed the api#openbanking#backend file from ../repository/deployment/server/webapps
[2024-12-13 11:57:15] INFO - Removed the client-registration#v0.17.war file from ../repository/deployment/server/webapps
[2024-12-13 11:57:15] INFO - Removed the api#identity#consent-mgt#v1.0.war file from ../repository/deployment/server/webapps
[2024-12-13 11:57:15] INFO - Removed the api#am#devportal.war file from ../repository/deployment/server/webapps
rm: cannot remove '../repository/deployment/server/webapps/am#sample#calculator#v1': No such file or directory
[2024-12-13 11:57:15] INFO - Removed the am#sample#calculator#v1 file from ../repository/deployment/server/webapps
[2024-12-13 11:57:15] INFO - Removed the oauth2 file from ../repository/deployment/server/webapps
[2024-12-13 11:57:15] INFO - Removed the oauth2.war file from ../repository/deployment/server/webapps
[2024-12-13 11:57:15] INFO - Removed the api#am#service-catalog#v1.war file from ../repository/deployment/server/webapps
[2024-12-13 11:57:15] INFO - Removed the internal#data#v1.war file from ../repository/deployment/server/webapps
Finished the optimizations

Then when the `sh api-manager.sh -Dprofile=gateway-worker` is ran it gives File not found errors.

> SEVERE {org.wso2.carbon.server.Main handleConfiguration} - Error while performing configuration changes 
org.wso2.config.mapper.ConfigParserException: Error while reading metadata
        at org.wso2.config.mapper.MetaDataParser.readLastModifiedValue(MetaDataParser.java:76)
        at org.wso2.config.mapper.MetaDataParser.getChangedFiles(MetaDataParser.java:164)
        at org.wso2.config.mapper.ConfigParser.parse(ConfigParser.java:108)
        at org.wso2.carbon.server.Main.handleConfiguration(Main.java:235)
        at org.wso2.carbon.server.Main.main(Main.java:106)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.wso2.carbon.bootstrap.Bootstrap.loadClass(Bootstrap.java:69)
        at org.wso2.carbon.bootstrap.Bootstrap.main(Bootstrap.java:51)
Caused by: java.io.FileNotFoundException: /home/azureuser/pack-node1/wso2am-4.2.0/repository/deployment/server/webapps/authenticationendpoint/WEB-INF/web.xml (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at org.wso2.config.mapper.MetaDataParser.getMetadata(MetaDataParser.java:97)
        at org.wso2.config.mapper.MetaDataParser.readLastModifiedValue(MetaDataParser.java:74)
        
There is only 2 wars are in `repository/deployment/server/webapps` now.

 Thank you.

**Comment by kavindasr** [comment]
@anjuchamantha I encountered a similar issue. Initially, I attempted to run:
`sh api-manager.sh -Dprofile=gateway-worker`
without first executing:
`sh profileSetup.sh -Dprofile=gateway-worker.`

This resulted in the following error:
```java.lang.ClassNotFoundException: org.wso2.carbon.identity.captcha.filter.CaptchaFilter.```

After that, I ran the `sh profileSetup.sh -Dprofile=gateway-worker` command and then tried to start the server with the profile. However, this led to a "File not found" error.

The root cause of this issue is that starting the server without first running the profile setup modifies some configurations, which ultimately causes the "File not found" error.

To resolve this, use a fresh APIM pack. Start by running the profile setup, then make the necessary changes to the deployment.toml file, and finally, start the server with the specified profile.
