### ISSUE TITLE
A duplicate permission error thrown when starts up in APIM Analytics 3.2.0

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-apim#9571]
### Description:
The following error thrown with APIM Analytics 3.2.0 pack at starts up.

`ERROR {org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager} - Runtime Exception occurred while calling onAllRequiredCapabilitiesAvailable of component carbon-deployment-service org.wso2.carbon.analytics.permissions.exceptions.PermissionException: Unable to add permission.
at org.wso2.carbon.analytics.permissions.internal.dao.PermissionsDAO.addPermission(PermissionsDAO.java:209)
at org.wso2.carbon.analytics.permissions.internal.impl.DefaultPermissionProvider.addPermission(DefaultPermissionProvider.java:83)
at org.wso2.carbon.dashboards.core.internal.DashboardMetadataProviderImpl.add(DashboardMetadataProviderImpl.java:174)
at org.wso2.carbon.dashboards.core.internal.DashboardImporter.importDashboards(DashboardImporter.java:78)
at org.wso2.carbon.dashboards.core.internal.DashboardMetadataProviderImpl.init(DashboardMetadataProviderImpl.java:111)
at org.wso2.carbon.dashboards.api.internal.DashboardRestApiProvider.getMicroservices(DashboardRestApiProvider.java:83)
at org.wso2.carbon.uiserver.internal.deployment.listener.RestApiDeployer.collectMicroservices(RestApiDeployer.java:127)
at org.wso2.carbon.uiserver.internal.deployment.listener.RestApiDeployer.appDeploymentEvent(RestApiDeployer.java:86)
at org.wso2.carbon.uiserver.internal.io.deployment.ArtifactAppDeployer.publishAppDeploymentEvent(ArtifactAppDeployer.java:154)
at org.wso2.carbon.uiserver.internal.io.deployment.ArtifactAppDeployer.deploy(ArtifactAppDeployer.java:103)
at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$deployArtifacts$0(DeploymentEngine.java:291)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.deployArtifacts(DeploymentEngine.java:282)
at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:112)
at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.start(DeploymentEngine.java:121)
at org.wso2.carbon.deployment.engine.internal.DeploymentEngineListenerComponent.onAllRequiredCapabilitiesAvailable(DeploymentEngineListenerComponent.java:216)
at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$7(StartupComponentManager.java:266)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:252)
at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
at java.util.TimerThread.mainLoop(Timer.java:555)
at java.util.TimerThread.run(Timer.java:505)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'DASH-apis.owner' for key 'PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61)
at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.executeUpdate(HikariPreparedStatementProxy.java)
at org.wso2.carbon.analytics.permissions.internal.dao.PermissionsDAO.addPermission(PermissionsDAO.java:205)
... 22 more`

### Affected Product Version:
APIM Analytics 3.2.0

**Comment by xarhang** [comment]
i have the same issue

**Comment by RAVEENSR** [comment]
Related issue: https://github.com/wso2/carbon-dashboards/issues/1223

**Comment by AnuGayan** [comment]
This is invalid since the analytics solution has been revamped
