### ISSUE TITLE
[APIM 2.5.0] Exception thrown when throttle data publishing when IPv6 address is used

### ISSUE THREAD

**Issue by akila95fernando** [wso2/product-apim#9592]
### Description:
The following exception is thrown when invoking an api with ipv6 adress.

`
Exception in thread "pool-140-thread-11151" java.lang.NumberFormatException: For input string: "23:64433" at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Long.parseLong(Long.java:589) 
at java.lang.Long.parseLong(Long.java:631) 
at org.wso2.carbon.apimgt.impl.utils.APIUtil.ipToLong(APIUtil.java:6917) 
at org.wso2.carbon.apimgt.gateway.throttling.publisher.DataProcessAndPublishingAgent.run_aroundBody4(DataProcessAndPublishingAgent.java:154) 
at org.wso2.carbon.apimgt.gateway.throttling.publisher.DataProcessAndPublishingAgent.run(DataProcessAndPublishingAgent.java:140) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
at java.lang.Thread.run(Thread.java:748)
`

This is identified and fixed in APIM 2.6.0 - https://github.com/wso2/product-apim/issues/8216
### Steps to reproduce:
Invoke an API using IPv6 address.
### Affected Product Version:
APIM 2.5.0

**Comment by mushthaq33** [comment]
Fixed with https://github.com/wso2-support/carbon-apimgt/pull/2682/files
