### ISSUE TITLE
[2.6.0] Failed to Publish API with Email Notification & Access Control

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#9601]
### Description:

The following error is produced when trying to create a new version of an API with Email notification enabled.

```log
TID: [-1234] [] [2020-12-02 15:15:45,144] ERROR {org.wso2.carbon.apimgt.impl.executors.APIExecutor} -  Failed to publish service to API store while executing APIExecutor.  {org.wso2.carbon.apimgt.impl.executors.APIExecutor}
org.wso2.carbon.apimgt.api.APIManagementException: User is not authorized to view or modify the API ...
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.checkAccessControlPermission_aroundBody340(APIProviderImpl.java:6044)
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.checkAccessControlPermission(APIProviderImpl.java:5988)
    at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.getAPI_aroundBody106(UserAwareAPIProvider.java:427)
    at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.getAPI(UserAwareAPIProvider.java:424)
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.getAPIsByProvider_aroundBody4(APIProviderImpl.java:271)
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.getAPIsByProvider(APIProviderImpl.java:256)
    at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.getAPIsByProvider(UserAwareAPIProvider.java:1)
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.getOldPublishedAPIList_aroundBody84(APIProviderImpl.java:1767)
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.getOldPublishedAPIList(APIProviderImpl.java:1765)
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.sendEmailNotification_aroundBody86(APIProviderImpl.java:1800)
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.sendEmailNotification(APIProviderImpl.java:1786)
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.propergateAPIStatusChangeToGateways_aroundBody70(APIProviderImpl.java:1545)
    at org.wso2.carbon.apimgt.impl.APIProviderImpl.propergateAPIStatusChangeToGateways(APIProviderImpl.java:1508)
```

### Steps to reproduce:

- Create a new role called **test**.
- Create a new user called **user1** and assign the role **test** to that user.
- Login to the publisher portal using **user1** and create two APIs called **API1** and **API2**.
- Restrict publisher access control of the **API1** to role **test**.
- Then enable email notification when a new version of an API is created.
- Login to the carbon console and remove the **test** role from **user1**.
- Restart to remove caches.
- Login to the publisher using **user1** => API1 won't be visible to user1.
- But when we try to create a new version of **API2** and try to publish, the above-reported error-trace is produced.
- Even when we are trying to create a new API and publish, the above error is prompted

### Affected Product Version:

- API Manager 2.6.0

**Comment by RakhithaRR** [comment]
This issue is already fixed in the master.
