### ISSUE TITLE
Issue while publishing a GraphQL API to multiple gateways

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/product-apim#9731]
### Description:
When a GraphQL API is published to multiple Gateways, following error is observed.

`[2021-01-15 12:17:33,676] ERROR - GovernanceArtifactImpl Invoking lifecycle action "Publish" failed. An exception occurred while executing handler chain. null
org.wso2.carbon.registry.core.exceptions.RegistryException: An exception occurred while executing handler chain. null
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.invokeAspect(HandlerManager.java:2818) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.invokeAspect(HandlerLifecycleManager.java:518) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.invokeAspect(EmbeddedRegistry.java:2607) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
...................
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.apimgt.impl.definitions.GraphQLSchemaDefinition.buildSchemaWithAdditionalInfo_aroundBody6(GraphQLSchemaDefinition.java:244) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.GraphQLSchemaDefinition.buildSchemaWithAdditionalInfo(GraphQLSchemaDefinition.java:137) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.APIGatewayManager.createAPIGatewayDTOtoPublishAPI_aroundBody6(APIGatewayManager.java:292) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
..................
[2021-01-15 12:17:33,901] ERROR - ApisApiServiceImpl Error while updating lifecycle of API 6ed025d5-267c-44af-9fbf-5af49da693b2
org.wso2.carbon.apimgt.api.APIManagementException: Failed to change the life cycle status : An exception occurred while executing handler chain. null
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.handleException_aroundBody132(AbstractAPIManager.java:1868) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.handleException(AbstractAPIManager.java:1867) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.changeLifeCycleStatus_aroundBody272(APIProviderImpl.java:5790) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
.................
Caused by: org.wso2.carbon.governance.api.exception.GovernanceException: An exception occurred while executing handler chain. null
	at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.invokeAction(GovernanceArtifactImpl.java:833) ~[org.wso2.carbon.governance.api_4.8.19.jar:?]
	at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.invokeAction(GovernanceArtifactImpl.java:808) ~[org.wso2.carbon.governance.api_4.8.19.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.changeLifeCycleStatus_aroundBody272(APIProviderImpl.java:5697) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	... 57 more
Caused by: org.wso2.carbon.registry.core.exceptions.RegistryException: An exception occurred while executing handler chain. null
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.invokeAspect(HandlerManager.java:2818) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.invokeAspect(HandlerLifecycleManager.java:518) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
.................
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.apimgt.impl.definitions.GraphQLSchemaDefinition.buildSchemaWithAdditionalInfo_aroundBody6(GraphQLSchemaDefinition.java:244) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.GraphQLSchemaDefinition.buildSchemaWithAdditionalInfo(GraphQLSchemaDefinition.java:137) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
	at org.wso2.carbon.apimgt.impl.APIGatewayManager.createAPIGatewayDTOtoPublishAPI_aroundBody6(APIGatewayManager.java:292) ~[org.wso2.carbon.apimgt.impl_6.7.206.jar:?]
.................
`

### Steps to reproduce:

1. Configure publishing through multiple API gateways.
2. Create a GraphQL API
3. Select multiple gateways
4. Publish the API

### Affected Product Version:
APIM 3.2.0 #

**Comment by sashansamarajeewa** [comment]
The issue can be fixed with PR - https://github.com/wso2-support/carbon-apimgt/pull/2785
