### ISSUE TITLE
Error When invoking an apiwith empty json payload

### ISSUE THREAD

**Issue by prasa7** [wso2/product-apim#9754]
TID: [23268] [] [2021-01-12 01:48:53,267] @pureplanetltd [23268] [AM] WARN {org.apache.synapse.util.xpath.SynapseJsonPath} -  Json Payload is empty. {org.apache.synapse.util.xpath.SynapseJsonPath} 
TID: [23268] [] [2021-01-12 01:48:53,270] @pureplanetltd [23268] [AM] INFO {org.apache.synapse.mediators.builtin.LogMediator} -  Pure-Tracking-Id = 321, client-Id = localhost:8243, Event-Type  = BEGIN, Resource = /2000486199, getAccountSyncRequest =  {org.apache.synapse.mediators.builtin.LogMediator} 
TID: [23268] [] [2021-01-12 01:48:53,348] @pureplanetltd [23268] [AM]ERROR {org.apache.synapse.commons.json.JsonUtil} -  #writeAsJson. Payload could not be written as JSON. MessageID: urn:uuid:b1c788c3-29e4-4e41-8930-cd0b8cc76907 {org.apache.synapse.commons.json.JsonUtil} 
TID: [23268] [] [2021-01-12 01:48:53,352] @pureplanetltd [23268] [AM]ERROR {org.apache.synapse.core.axis2.Axis2Sender} -  Unexpected error during sending message out {org.apache.synapse.core.axis2.Axis2Sender} 
org.apache.axis2.AxisFault: Payload could not be written as JSON. 
	at org.apache.synapse.commons.json.JsonUtil.writeAsJson(JsonUtil.java:302) 
	at org.apache.synapse.commons.json.JsonStreamFormatter.writeTo(JsonStreamFormatter.java:70) 
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.sendRequestContent(PassThroughHttpSender.java:405) 
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:276) 
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442) 
	at org.wso2.carbon.core.multitenancy.transports.TenantTransportSender.invoke(TenantTransportSender.java:290) 
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442) 
	at org.apache.synapse.core.axis2.DynamicAxisOperation$DynamicOperationClient.send(DynamicAxisOperation.java:185) 
	at org.apache.synapse.core.axis2.DynamicAxisOperation$DynamicOperationClient.executeImpl(DynamicAxisOperation.java:167) 
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149) 
	at org.apache.synapse.core.axis2.Axis2FlexibleMEPClient.send(Axis2FlexibleMEPClient.java:626) 
	at org.apache.synapse.core.axis2.Axis2Sender.sendOn(Axis2Sender.java:85) 
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:547) 
	at org.apache.synapse.endpoints.AbstractEndpoint.send(AbstractEndpoint.java:384) 
	at org.apache.synapse.endpoints.HTTPEndpoint.send(HTTPEndpoint.java:89) 
	at org.apache.synapse.endpoints.IndirectEndpoint.send(IndirectEndpoint.java:55) 
	at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:123) 
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108) 
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70) 
	at org.apache.synapse.mediators.filters.FilterMediator.mediate(FilterMediator.java:169) 
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108) 
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70) 
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) 
	at org.apache.synapse.rest.Resource.process(Resource.java:358) 
	at org.apache.synapse.rest.API.process(API.java:426) 
	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149) 
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95) 
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71) 
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:303) 
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98) 
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) 
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRESTRequest(MultitenantMessageReceiver.java:682) 
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doNhttpREST(MultitenantMessageReceiver.java:584) 
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doREST(MultitenantMessageReceiver.java:394) 
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRequest(MultitenantMessageReceiver.java:244) 
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:84) 
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) 
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:365) 
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:186) 
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
	at java.lang.Thread.run(Thread.java:748) 
TID: [23268] [] [2021-01-12 01:48:53,371] @pureplanetltd [23268] [AM] INFO {org.apache.synapse.mediators.builtin.LogMediator} -  Pure-Tracking-Id = null, Event-Type = END, System-Name = ESB, Tag-Name = TBD, Response-Code = 503, seqGatewayFaultHandlerResponse = { 
	            "code" : "05", 
	            "message" : "The service is temporarily unavailable. ESB - Unexpected error during sending message out" 
	            } {org.apache.synapse.mediators.builtin.LogMediator} 
TID: [-1] [] [2021-01-12 01:48:53,376] DEBUG {org.apache.synapse.transport.http.headers} -  http-incoming-3 << HTTP/1.1 503 Service Unavailable {org.apache.synapse.transport.http.headers} 
TID: [-1] [] [2021-01-12 01:48:53,376] DEBUG {org.apache.synapse.transport.http.headers} -  http-incoming-3 << X-JWT-Assertion:

**Comment by wasuradananjith** [comment]
This is fixed via https://github.com/wso2-support/wso2-synapse/pull/1055. Hence, can close the issue.

**Comment by wasuradananjith** [comment]
This id fixed in master via https://github.com/wso2/wso2-synapse/pull/1699 and a test was added in https://github.com/wso2/product-apim/pull/9915. Hence, closing the issue.
