### ISSUE TITLE
Self Registration on DevPortal under tenant domain not working

### ISSUE THREAD

**Issue by lpastor74** [wso2/product-apim#9774]
### Description:

New subscriber on dev portal created under tenant domain is created but Internal/Subscriber role is not assigned
A new subscriber cannot log in.

### Steps to reproduce:

1. Create a tenant
2. go to devportal and choose a tenant domain
3. Start the self-registration process
4. Create a user name with tenant domain (username@tenantdomain)
5. Populate the rest fields and click on create button

NOTE: 
- no confirmation of successful user creation
- in carbon portal user is created with internal/everyone and internal/selfsignup BUT no internal/subscriber role

### Error message:
TID: [-1234] [] [2021-01-22 17:24:06,877]  INFO {org.wso2.carbon.databridge.core.DataBridge} - user admin connected
TID: [-1234] [UserAdmin] [2021-01-22 17:24:07,022]  WARN {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} - Login failed. Unauthorized login attempt 'xxxx[-1234]' at [2021-01-22 17:24:07,022-0600]
TID: [-1234] [UserAdmin] [2021-01-22 17:24:07,051]  WARN {org.wso2.carbon.server.admin.module.handler.AuthenticationHandler} - Illegal access attempt at [2021-01-22 17:24:07,0051] from IP address 127.0.0.1 while trying to authenticate access to service UserAdmin
TID: [1] [] [2021-01-22 17:24:07,058] ERROR {org.wso2.carbon.identity.user.endpoint.impl.MeApiServiceImpl} - Error occurred in the server while performing the task. org.wso2.carbon.identity.recovery.IdentityRecoveryServerException: Error while adding self signup user
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.wso2.carbon.identity.base.IdentityException.error(IdentityException.java:103)
	at org.wso2.carbon.identity.recovery.util.Utils.handleServerException(Utils.java:280)
	at org.wso2.carbon.identity.recovery.signup.UserSelfRegistrationManager.handleClientException(UserSelfRegistrationManager.java:339)
	at org.wso2.carbon.identity.recovery.signup.UserSelfRegistrationManager.registerUser(UserSelfRegistrationManager.java:225)
	at org.wso2.carbon.identity.user.endpoint.impl.MeApiServiceImpl.mePost(MeApiServiceImpl.java:88)
	at org.wso2.carbon.identity.user.endpoint.MeApi.mePost(MeApi.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.identity.captcha.filter.CaptchaFilter.doFilter(CaptchaFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:110)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:123)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.user.core.UserStoreException: Error when handling event : POST_ADD_USER
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:208)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4388)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4374)
	at org.wso2.carbon.identity.recovery.signup.UserSelfRegistrationManager.registerUser(UserSelfRegistrationManager.java:212)
	... 62 more
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:194)
	... 65 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:197)
	... 67 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Error when handling event : POST_ADD_USER
	at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.handleEvent(IdentityMgtEventListener.java:1660)
	at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.handleEvent(IdentityMgtEventListener.java:1620)
	at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.handleEvent(IdentityMgtEventListener.java:1608)
	at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.doPostAddUser(IdentityMgtEventListener.java:217)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4689)
	... 72 more
Caused by: org.wso2.carbon.identity.event.IdentityEventException: Error while adding custom roles to the user
	at org.wso2.carbon.apimgt.impl.handlers.UserPostSelfRegistrationHandler.handleEvent_aroundBody2(UserPostSelfRegistrationHandler.java:75)
	at org.wso2.carbon.apimgt.impl.handlers.UserPostSelfRegistrationHandler.handleEvent(UserPostSelfRegistrationHandler.java:64)
	at org.wso2.carbon.identity.event.services.IdentityEventServiceImpl.handleEvent(IdentityEventServiceImpl.java:56)
	at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.handleEvent(IdentityMgtEventListener.java:1644)
	... 76 more
Caused by: org.wso2.carbon.identity.recovery.IdentityRecoveryServerException: Unexpected error
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.wso2.carbon.identity.base.IdentityException.error(IdentityException.java:103)
	at org.wso2.carbon.identity.recovery.util.Utils.handleServerException(Utils.java:280)
	at org.wso2.carbon.apimgt.impl.handlers.UserPostSelfRegistrationHandler.executeUserRegistrationWorkflow_aroundBody4(UserPostSelfRegistrationHandler.java:130)
	at org.wso2.carbon.apimgt.impl.handlers.UserPostSelfRegistrationHandler.executeUserRegistrationWorkflow(UserPostSelfRegistrationHandler.java:87)
	at org.wso2.carbon.apimgt.impl.handlers.UserPostSelfRegistrationHandler.handleEvent_aroundBody2(UserPostSelfRegistrationHandler.java:73)
	... 79 more
Caused by: org.wso2.carbon.apimgt.impl.workflow.WorkflowException: Error while assigning role to user
	at org.wso2.carbon.apimgt.impl.workflow.UserSignUpSimpleWorkflowExecutor.complete_aroundBody4(UserSignUpSimpleWorkflowExecutor.java:91)
	at org.wso2.carbon.apimgt.impl.workflow.UserSignUpSimpleWorkflowExecutor.complete(UserSignUpSimpleWorkflowExecutor.java:57)
	at org.wso2.carbon.apimgt.impl.workflow.UserSignUpSimpleWorkflowExecutor.execute_aroundBody2(UserSignUpSimpleWorkflowExecutor.java:51)
	at org.wso2.carbon.apimgt.impl.workflow.UserSignUpSimpleWorkflowExecutor.execute(UserSignUpSimpleWorkflowExecutor.java:46)
	at org.wso2.carbon.apimgt.impl.handlers.UserPostSelfRegistrationHandler.executeUserRegistrationWorkflow_aroundBody4(UserPostSelfRegistrationHandler.java:124)
	... 81 more
Caused by: org.apache.axis2.AxisFault: Access Denied. Authentication failed - Invalid credentials provided.
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:382)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:457)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.wso2.carbon.user.mgt.stub.UserAdminStub.getRolesOfUser(UserAdminStub.java:2530)
	at org.wso2.carbon.apimgt.impl.workflow.UserSignUpWorkflowExecutor.updateRolesOfUser_aroundBody2(UserSignUpWorkflowExecutor.java:124)
	at org.wso2.carbon.apimgt.impl.workflow.UserSignUpWorkflowExecutor.updateRolesOfUser(UserSignUpWorkflowExecutor.java:97)
	at org.wso2.carbon.apimgt.impl.workflow.UserSignUpSimpleWorkflowExecutor.complete_aroundBody4(UserSignUpSimpleWorkflowExecutor.java:85)
	... 85 more

### Environment details (with versions):
- OS:MAC IOS
- Client: APIM 3.2
- Env (Docker/K8s): VM binary installation

**Comment by tharikaGitHub** [comment]
Hi @lpastor74 

     You have to enable self registration for tenants as mentioned in documentation [1]. 

[1] https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/enabling-or-disabling-self-signup/

**Comment by lpastor74** [comment]
Hi Tharika 

I did all steps.
On /_system/governance/apimgt/applicationdata/ directory I enables the 


```
<SelfSignUp>

    <EnableSignup>true</EnableSignup>

    <!-- user storage to store users -->
    <SignUpDomain>PRIMARY</SignUpDomain>

    <!-- Tenant admin information. (for clustered setup credentials for AuthManager) -->
    <AdminUserName>xxxx</AdminUserName>
    <AdminPassword>xxxx</AdminPassword>

    <!-- List of roles for the tenant user -->
    <SignUpRoles>
        <SignUpRole>
            <RoleName>subscriber</RoleName>
            <IsExternalRole>false</IsExternalRole>
        </SignUpRole>
    </SignUpRoles>

</SelfSignUp>
```
Question: is Domain need to change and put my tenant domain?

Also on the Identity Providers menu on the Resident section, I checked and self-registration is enabled.

Still, the new account on the Dev portal not finishing the registration (no account created message), and the account do not have a subscriber role.

**Comment by tharikaGitHub** [comment]
Hi @lpastor74 you need to specify the specific tenant admin credentials in <AdminUserName> and <AdminPassword> sections replacing the xxxx strings as mentioned in the documentation. The <AdminUserName> should have the tenant domain as well.

**Comment by tharikaGitHub** [comment]
Hi @lpastor74 I will close this issue as this is resolved by following the steps in the documentation shared above. The Git Issue https://github.com/wso2/docs-apim/issues/3090 is created to improve the documentation to remove any ambiguity.
