### ISSUE TITLE
[2.6.0] NoSuchMethodError: JsonUtil.removeJsonStream

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#9789]
### Description:

The following error is produced in the APIM 2.6 (1611075098533) when trying out the XSLT Mediators in the mediation sequences.

```log
java.lang.NoSuchMethodError: org.apache.synapse.commons.json.JsonUtil.removeJsonStream(Lorg/apache/axis2/context/MessageContext;)Vjava.lang.NoSuchMethodError: org.apache.synapse.commons.json.JsonUtil.removeJsonStream(Lorg/apache/axis2/context/MessageContext;)V 
    at org.apache.synapse.mediators.transform.XSLTMediator.mediate(XSLTMediator.java:266) 
    at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108) 
    at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70) 
    at org.apache.synapse.config.xml.AnonymousListMediator.mediate(AnonymousListMediator.java:37) 
    at org.apache.synapse.config.xml.SwitchCase.mediate(SwitchCase.java:69) 
    at org.apache.synapse.mediators.filters.SwitchMediator.mediate(SwitchMediator.java:134) 
    at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108) 
    at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70) 
    at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) 
    at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.mediate_aroundBody0(APIManagerExtensionHandler.java:69) 
    at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.mediate(APIManagerExtensionHandler.java:54) 
    at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleResponse_aroundBody4(APIManagerExtensionHandler.java:104) 
    at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleResponse(APIManagerExtensionHandler.java:100) 
    at org.apache.synapse.rest.API.process(API.java:350) 
    at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149) 
    at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95) 
    at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:58) 
    at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:303) 
    at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:583) 
    at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:195) 
    at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) 
    at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:282) 
    at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
    at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce:

- Publish an API with a mediation sequence having an XSLT mediator
- Invoke the API and verify the behavior

### Affected Product Version:

- APIM 2.6 (1611075098533) (WUM updates after October)

**Comment by Jayanie** [comment]
Fixed in https://github.com/wso2/wso2-synapse/pull/1410
