### ISSUE TITLE
Cannot call the created APIs normally on WSO2 API-M 3.2.0 after changing the password of administrator

### ISSUE THREAD

**Issue by zhangjg-js** [wso2/product-apim#9874]
### Description:
**After changing the password of administrator and restarting WSO2 API-M, when calling a created API, we got an error,** 
\<faultstring\>unknown\<\/faultstring\>

### Steps to reproduce:
**First, To create and publish an API or a set of APIs on the publisher UI, and create an application and the application subscribed the APIs on the devportal UI. Then using the curl command to call one of the APIs with the obtained the access token, it can work normally. 
curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $access_token" -k "https://127.0.0.1:8243/api/v1.0/n/version"
Next, I changed the password of administrator on the devportal UI, and modified the password field as below in the deployment.toml file simultaneously.**   
[super_admin]
username = "admin"
password = "admin"
**After changing password, there are some error messages output in the wso2carbon.log file,**
TID: [-1] [] [2021-02-07 21:41:38,547] ERROR {org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker} - Error while trying to connect to the endpoint. Cannot borrow client for ssl://10.124.6.166:9711. org.wso2.carbon.databridge.agent.exception.DataEndpointLoginException: Cannot borrow client for ssl://10.124.6.166:9711.
        at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:145)
        at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:59)
        at org.wso2.carbon.databridge.agent.endpoint.DataEndpoint.syncConnect(DataEndpoint.java:151)
        at org.wso2.carbon.databridge.agent.endpoint.DataEndpoint$EventPublisher.run(DataEndpoint.java:277)
        at java.lang.Thread.run(Thread.java:748)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.databridge.agent.exception.DataEndpointLoginException: Error while trying to login to data receiver :/10.124.6.166:9711
        at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryDataEndpoint.login(BinaryDataEndpoint.java:50)
        at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:139)
        ... 9 more
Caused by: org.wso2.carbon.databridge.commons.exception.AuthenticationException: wrong userName or password
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryEventSender.processResponse(BinaryEventSender.java:163)
        at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryDataEndpoint.login(BinaryDataEndpoint.java:44)
        ... 10 more

TID: [-1] [] [2021-02-07 21:41:38,590] ERROR {org.wso2.carbon.databridge.agent.endpoint.DataEndpoint} - Unexpected error occurred while sending the event. org.wso2.carbon.databridge.commons.exception.SessionTimeoutException: Binary Session Expired Exception
        at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryDataEndpoint.send(BinaryDataEndpoint.java:85)
        at org.wso2.carbon.databridge.agent.endpoint.DataEndpoint$EventPublisher.publish(DataEndpoint.java:332)
        at org.wso2.carbon.databridge.agent.endpoint.DataEndpoint$EventPublisher.run(DataEndpoint.java:279)
        at java.lang.Thread.run(Thread.java:748)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.databridge.commons.exception.SessionTimeoutException: a1cf5087-ad3b-4c60-8361-2f7e140c81c7 expired
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryEventSender.processResponse(BinaryEventSender.java:163)
        at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryDataEndpoint.send(BinaryDataEndpoint.java:78)
        ... 8 more

**Then restarted the WSO2 API Manager with the commands (wso2server.sh stop/start). There is no error message output in wso2carbon.log during startup. But when I tried to the above same curl command to call one of APIs, the following message was output,**
<faultstring>unknown</faultstring>
**And some error messages also are showed in the wso2carbon.log file, please check the following messages for more details,**
 TID: [-1234] [] [2021-02-07 23:37:31,749] ERROR {org.wso2.carbon.apimgt.gateway.handlers.security.APIKeyValidator} - Did not found valid API Validation Information cache configuration. Use default configurationjava.lang.NullPointerException
TID: [-1234] [] [2021-02-07 23:37:31,787] ERROR {org.wso2.carbon.apimgt.gateway.handlers.security.APIKeyValidator} - Did not found valid API Resource Validation Information cache configuration. Use default configurationjava.lang.NullPointerException
TID: [-1234] [] [2021-02-07 23:37:31,825] ERROR {org.wso2.carbon.apimgt.gateway.utils.GatewayUtils} - Did not found valid API Validation Information cache configuration. Use default configuration. java.lang.NullPointerException
	at org.wso2.carbon.apimgt.gateway.internal.ServiceReferenceHolder.getAPIManagerConfiguration_aroundBody12(ServiceReferenceHolder.java:100)
	at org.wso2.carbon.apimgt.gateway.internal.ServiceReferenceHolder.getAPIManagerConfiguration(ServiceReferenceHolder.java:99)
	at org.wso2.carbon.apimgt.gateway.utils.GatewayUtils.isGatewayTokenCacheEnabled_aroundBody56(GatewayUtils.java:868)
	at org.wso2.carbon.apimgt.gateway.utils.GatewayUtils.isGatewayTokenCacheEnabled(GatewayUtils.java:865)
	at org.wso2.carbon.apimgt.gateway.handlers.security.jwt.JWTValidator.<init>(JWTValidator.java:76)
	at org.wso2.carbon.apimgt.gateway.handlers.security.oauth.OAuthAuthenticator.init_aroundBody0(OAuthAuthenticator.java:103)
	at org.wso2.carbon.apimgt.gateway.handlers.security.oauth.OAuthAuthenticator.init(OAuthAuthenticator.java:101)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.initializeAuthenticators_aroundBody34(APIAuthenticationHandler.java:300)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.initializeAuthenticators(APIAuthenticationHandler.java:239)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest_aroundBody36(APIAuthenticationHandler.java:352)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest(APIAuthenticationHandler.java:325)
	at org.apache.synapse.rest.API.process(API.java:373)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:144)
	at org.apache.synapse.rest.RESTRequestHandler.identifyAPI(RESTRequestHandler.java:164)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:73)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:331)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:99)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:188)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

TID: [-1234] [] [2021-02-07 23:37:31,865] ERROR {org.apache.synapse.transport.passthru.ServerWorker} - Error processing GET request for : /api/v1.0/n/version. java.lang.NullPointerException
	at org.wso2.carbon.apimgt.gateway.internal.ServiceReferenceHolder.getAPIManagerConfiguration_aroundBody12(ServiceReferenceHolder.java:100)
	at org.wso2.carbon.apimgt.gateway.internal.ServiceReferenceHolder.getAPIManagerConfiguration(ServiceReferenceHolder.java:99)
	at org.wso2.carbon.apimgt.gateway.handlers.security.jwt.JWTValidator.<init>(JWTValidator.java:79)
	at org.wso2.carbon.apimgt.gateway.handlers.security.oauth.OAuthAuthenticator.init_aroundBody0(OAuthAuthenticator.java:103)
	at org.wso2.carbon.apimgt.gateway.handlers.security.oauth.OAuthAuthenticator.init(OAuthAuthenticator.java:101)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.initializeAuthenticators_aroundBody34(APIAuthenticationHandler.java:300)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.initializeAuthenticators(APIAuthenticationHandler.java:239)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest_aroundBody36(APIAuthenticationHandler.java:352)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest(APIAuthenticationHandler.java:325)
	at org.apache.synapse.rest.API.process(API.java:373)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:144)
	at org.apache.synapse.rest.RESTRequestHandler.identifyAPI(RESTRequestHandler.java:164)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:73)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:331)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:99)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:188)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Affected Product Version:
WSO2 API Manager 3.2.0

### Environment details (with versions):
- OS: CentOS 7
- Client: FireFox, Linux terminal
- Env (Docker/K8s):

---

**Comment by MPincay** [comment]
Chicos que tal, el tema de cambio de clave del super administrador en el repository/conf/deployment.toml, debes bajar el wso2am y si tienes analytics también bajarlo o detenerlo, luego hacer el cambio de claves en el repository/conf/deployment.toml de wso2am, hacer el cambio de clave en el deployemt.yml del conf/worker de analytics y en el deployment.yml de conf/dashboard de analitycs. Luego de eso levantas wso2am y wso2 analytics, una vez levantado ve a la consola de carbon y cambia la clave "admin" por tu nueva clave que agregaste en el deployment.toml y lo demás ya es tuyo puedes probar todas las apis como si nada pasará.

Asegúrate de que las apis respondan bien y que se puedan visualizar a través del dashboard de analytics.

**Comment by zhangjg-js** [comment]
Hi MPincay,
Thanks for your reply. I tried to change the password of admin according to your suggestion, but got the same error. \<faultstring\>unknown\<\/faultstring\>

**Comment by MPincay** [comment]
> Hola MPincay,
> Gracias por tu respuesta. Intenté cambiar la contraseña de administrador de acuerdo con su sugerencia y llamar a un recurso de API, pero obtuve el mismo error. <faultstring> desconocido </faultstring>





Estimado borraste de casualidad los objetos de la carpeta tmp de wso2 api mánager???
Te recomendaría  bajar el wso2 , borrar los objetos dentro de tmp, por si acaso si usas H2 si tienes alguna tabla con extensión .lock borrala, y luego levanta wso2.

**Comment by zhangjg-js** [comment]
> > Hola MPincay,
> > Gracias por tu respuesta. Intenté cambiar la contraseña de administrador de acuerdo con su sugerencia y llamar a un recurso de API, pero obtuve el mismo error.  desconocido
> 
> Estimado borraste de casualidad los objetos de la carpeta tmp de wso2 api mánager???
> Te recomendaría bajar el wso2 , borrar los objetos dentro de tmp, por si acaso si usas H2 si tienes alguna tabla con extensión .lock borrala, y luego levanta wso2.

Actually, I didn't change and delete any files under the "tmp" folder. Currently, we are using MySQL as the database for WSO2 API-M.

**Comment by MPincay** [comment]
> > > Hola MPincay, 
> > > Gracias por tu respuesta. Intenté cambiar la contraseña de administrador de acuerdo con su sugerencia y llamar a un recurso de API, pero obtuve el mismo error. desconocido
> > 
> > 
> > Estimado borraste de casualidad los objetos de la carpeta tmp de wso2 api mánager ??? 
> > Te recomendaría bajar el wso2, borrar los objetos dentro de tmp, por si acaso si usas H2 si tienes alguna tabla con extensión .lock borrala, y luego levanta wso2.
> 
> En realidad, no cambié ni eliminé ningún archivo en la carpeta "tmp". Actualmente, usamos MySQL como base de datos para WSO2 API-M.

Esta bien si usas MYSQL, baja el wso2am y elimina los archivos que están dentro de la carpeta  tmp  e inicia nuevamente WSO2 si te da problemas podemos coordinar un zoom para reunirnos y apoyarte con gusto.

**Comment by zhangjg-js** [comment]
This issue has been resolved. Thanks.

**Comment by MPincay** [comment]
> Este problema ha sido resuelto. Gracias.

Me alegro 😃
