### ISSUE TITLE
[APIM-3.X.X] - Unable to import api definitions with apictl

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#9889]
### Description:
When trying to import APIs via apictl, receiving the following error.
```
2021-01-28T10:09:02,698 - DEBUG {org.wso2.carbon.apimgt.rest.api.util.impl.WebAppAuthenticatorImpl} - Scope validation successful for access token: null with scope: apim:api_import_export for resource
 path: /api/am/admin/v0.16/import/api and verb POST
2021-01-28T10:09:02,699 - DEBUG {org.wso2.carbon.apimgt.rest.api.util.impl.WebAppAuthenticatorImpl} - username = WSO2.ORG/admin
2021-01-28T10:09:02,699 - INFO {org.wso2.carbon.apimgt.impl.importexport.utils.CommonUtil} - Creation of folder is successful. Directory Name : megisextract-1.0.0
2021-01-28T10:09:02,700 - INFO {org.wso2.carbon.apimgt.impl.importexport.utils.CommonUtil} - Creation of folder is successful. Directory Name : Meta-information
2021-01-28T10:09:02,728 - ERROR {org.wso2.carbon.apimgt.rest.api.util.exception.GlobalThrowableMapper} - An unknown exception has been captured by the global exception mapper. java.lang.NullPointerExc
eption
 at org.wso2.carbon.apimgt.impl.APIProviderImpl.getResourcesToBeRemovedFromAPIProducts_aroundBody448(APIProviderImpl.java:8047)
 at org.wso2.carbon.apimgt.impl.APIProviderImpl$AjcClosure449.run(APIProviderImpl.java:1)
 at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
 at org.wso2.carbon.apimgt.impl.MethodTimeLogger.log(MethodTimeLogger.java:105)
 at org.wso2.carbon.apimgt.impl.APIProviderImpl.getResourcesToBeRemovedFromAPIProducts(APIProviderImpl.java:8038)
 at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.getResourcesToBeRemovedFromAPIProducts(UserAwareAPIProvider.java:1)
 at org.wso2.carbon.apimgt.impl.importexport.utils.APIImportUtil.importAPI_aroundBody6(APIImportUtil.java:397)
 at org.wso2.carbon.apimgt.impl.importexport.utils.APIImportUtil.importAPI(APIImportUtil.java:233)
```

When the API definition in the publisher portal is opened we can observe the following error.
![image](https://user-images.githubusercontent.com/20519000/107330272-587c8300-6ad7-11eb-9657-59a903e44b2f.png)

This is mainly because, in the original swagger definition, we have not used any security-related objects. When importing the API via apictl the security and securitySchemes have been introduced. The implicit flow is added in this scenario. According to the OAS3 specification, the security or securitySchemes are not mandatory [1]. But if we defined for code or implicit grants then we need to provide authorizationURL as it is a mandatory field [2]. Since it is left empty, we are facing this issue. Our main concerns are as follows.

- If the swagger is not valid, then the appropriate error message should have been shown while importing
- What is the purpose of introducing security and securitySchemes components that are not available in the original file. 

### Affected Product Version:
wso2am-3.1.0, wso2am-3.2.0

### Proposed solution:
When we try to create a new API in the publisher portal by importing the swagger file, a mock authorizatoinURL (https://test.com) is added automatically. If the same approach can be implemented while importing via apictl it seems that we can resolve this issue.
![image](https://user-images.githubusercontent.com/20519000/107330737-fb350180-6ad7-11eb-97d3-29bde9ea1061.png)

The same issue has been identified in wso2am-3.2.0 [3,4,5]. 
[1] [https://swagger.io/specification/#components-object](https://swagger.io/specification/#components-object)
[2] [https://swagger.io/specification/#security-scheme-object](https://swagger.io/specification/#security-scheme-object)
[3] [https://github.com/wso2/product-apim/issues/9298](https://github.com/wso2/product-apim/issues/9298)
[4] [https://github.com/wso2/product-apim/issues/8748](https://github.com/wso2/product-apim/issues/8748)
[5] [https://github.com/wso2/product-apim/issues/9128](https://github.com/wso2/product-apim/issues/9128)

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/9927
