### ISSUE TITLE
[3.1.0] Subscription Policy Limitation with 2048 MB

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#9919]
### Description:

In APIM 3.1.0 server, there is a limitation on creating a subscription policy with greater than 2048 MB request bandwidth. Following error is observed when creating a sub policy with 2048 MB

```log
TID: [-1234] [] [2021-02-11 14:05:26,564] ERROR {org.wso2.carbon.event.processor.core.EventProcessorDeployer} - Can't deploy the execution plan: carbon.super_sub_SamplePolicy.siddhiql org.apache.axis2.deployment.DeploymentException: Execution plan not deployed properly.
	at org.wso2.carbon.event.processor.core.EventProcessorDeployer.deploy(EventProcessorDeployer.java:71)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.event.processor.core.exception.ExecutionPlanConfigurationException: For input string: "2147483648"
	at org.wso2.carbon.event.processor.core.EventProcessorDeployer.processDeploy(EventProcessorDeployer.java:154)
	at org.wso2.carbon.event.processor.core.EventProcessorDeployer.deploy(EventProcessorDeployer.java:69)
	... 17 more
Caused by: java.lang.NumberFormatException: For input string: "2147483648"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:587)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.wso2.siddhi.query.compiler.internal.SiddhiQLBaseVisitorImpl.visitSigned_int_value(SiddhiQLBaseVisitorImpl.java:2067)
	at org.wso2.siddhi.query.compiler.internal.SiddhiQLBaseVisitorImpl.visitSigned_int_value(SiddhiQLBaseVisitorImpl.java:90)
	at org.wso2.siddhi.query.compiler.SiddhiQLParser$Signed_int_valueContext.accept(SiddhiQLParser.java:7121)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at org.wso2.siddhi.query.compiler.internal.SiddhiQLBaseVisitorImpl.visitConstant_value(SiddhiQLBaseVisitorImpl.java:1855)
	at org.wso2.siddhi.query.compiler.internal.SiddhiQLBaseVisitorImpl.visitConstant_value(SiddhiQLBaseVisitorImpl.java:90)
	at org.wso2.siddhi.query.compiler.SiddhiQLParser$Constant_valueContext.accept(SiddhiQLParser.java:6145)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at org.wso2.siddhi.query.compiler.internal.SiddhiQLBaseVisitorImpl.visitBasic_math_operation(SiddhiQLBaseVisitorImpl.java:1502)
	at org.wso2.siddhi.query.compiler.SiddhiQLParser$Basic_math_operationContext.accept(SiddhiQLParser.java:4593)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at org.wso2.siddhi.query.compiler.internal.SiddhiQLBaseVisitorImpl.visitGreaterthan_lessthan_math_operation(SiddhiQLBaseVisitorImpl.java:1417)
	at org.wso2.siddhi.query.compiler.internal.SiddhiQLBaseVisitorImpl.visitGreaterthan_lessthan_math_operation(SiddhiQLBaseVisitorImpl.java:90)
	at org.wso2.siddhi.query.compiler.SiddhiQLParser$Greaterthan_lessthan_math_operationContext.accept(SiddhiQLParser.java:4570)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at org.wso2.siddhi.query.compiler.internal.SiddhiQLBaseVisitorImpl.visitBasic_math_operation(SiddhiQLBaseVisitorImpl.java:1498)
	at org.wso2.siddhi.query.compiler.SiddhiQLParser$Basic_math_operationContext.accept(SiddhiQLParser.java:4593)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at org.wso2.siddhi.query.compiler.SiddhiQLBaseVisitor.visitAttribute(SiddhiQLBaseVisitor.java:264)
	at org.wso2.siddhi.query.compiler.SiddhiQLParser$AttributeContext.accept(SiddhiQLParser.java:4468)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at org.wso2.siddhi.query.compiler.internal.SiddhiQLBaseVisitorImpl.visitOutput_attribute(SiddhiQLBaseVisitorImpl.java:1346)
	at org.wso2.siddhi.query.compiler.SiddhiQLParser$Output_attributeContext.accept(SiddhiQLParser.java:4419)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at org.wso2.siddhi.query.compiler.internal.SiddhiQLBaseVisitorImpl.visitQuery_section(SiddhiQLBaseVisitorImpl.java:1128)
	at org.wso2.siddhi.query.compiler.internal.SiddhiQLBaseVisitorImpl.visitQuery_section(SiddhiQLBaseVisitorImpl.java:90)
	at org.wso2.siddhi.query.compiler.SiddhiQLParser$Query_sectionContext.accept(SiddhiQLParser.java:3776)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at org.wso2.siddhi.query.compiler.internal.SiddhiQLBaseVisitorImpl.visitQuery(SiddhiQLBaseVisitorImpl.java:488)
	at org.wso2.siddhi.query.compiler.internal.SiddhiQLBaseVisitorImpl.visitQuery(SiddhiQLBaseVisitorImpl.java:90)
	at org.wso2.siddhi.query.compiler.SiddhiQLParser$QueryContext.accept(SiddhiQLParser.java:2055)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at org.wso2.siddhi.query.compiler.SiddhiQLBaseVisitor.visitExecution_element(SiddhiQLBaseVisitor.java:216)
	at org.wso2.siddhi.query.compiler.SiddhiQLParser$Execution_elementContext.accept(SiddhiQLParser.java:635)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at org.wso2.siddhi.query.compiler.internal.SiddhiQLBaseVisitorImpl.visitExecution_plan(SiddhiQLBaseVisitorImpl.java:132)
	at org.wso2.siddhi.query.compiler.internal.SiddhiQLBaseVisitorImpl.visitExecution_plan(SiddhiQLBaseVisitorImpl.java:90)
	at org.wso2.siddhi.query.compiler.SiddhiQLParser$Execution_planContext.accept(SiddhiQLParser.java:255)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at org.wso2.siddhi.query.compiler.internal.SiddhiQLBaseVisitorImpl.visitParse(SiddhiQLBaseVisitorImpl.java:103)
	at org.wso2.siddhi.query.compiler.SiddhiQLParser$ParseContext.accept(SiddhiQLParser.java:141)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at org.wso2.siddhi.query.compiler.SiddhiCompiler.parse(SiddhiCompiler.java:67)
	at org.wso2.carbon.event.processor.core.internal.util.helper.EventProcessorHelper.validateExecutionPlan(EventProcessorHelper.java:76)
	at org.wso2.carbon.event.processor.core.EventProcessorDeployer.processDeploy(EventProcessorDeployer.java:121)
	... 18 more
```

### Steps to reproduce:

1. Log-in to the Admin portal of the APIM 3.1.0
2. Create a new Subscription policy with 2048 MB Request bandwidth
3. Save and deploy

### Affected Product Version:

- APIM 3.1.0

**Comment by tharikaGitHub** [comment]
Not reproduced in Public branch. Hence closing the issue.
