### ISSUE TITLE
[APIM 3.2] Upload document of an api error

### ISSUE THREAD

**Issue by roberto539** [wso2/product-apim#9921]
### Description:
When I want to upload a document for an API I have an error when source is a file.
But Inline, URL is working fine. 

Documents Add New Document
Name : my_doc
Summary : upload for test
Type : howto
source:file
![image](https://user-images.githubusercontent.com/78908909/107632231-83e1a800-6c66-11eb-9d41-cb604c0f977d.png)

Its a pdf file (same error with doc or docx file)

I have not error in publisher portal but in a consol 

TID: [-1234] [api/am/publisher] [2021-02-11 12:40:10,484] ERROR {org.wso2.carbon.apimgt.rest.api.util.exception.GlobalThrowableMapper} - An unknown exception has been captured by the global exception mapper. org.apache.cxf.attachment.HeaderSizeExceededException
        at org.apache.cxf.attachment.AttachmentDeserializer.readLine(AttachmentDeserializer.java:398)
        at org.apache.cxf.attachment.AttachmentDeserializer.loadPartHeaders(AttachmentDeserializer.java:350)
        at org.apache.cxf.attachment.AttachmentDeserializer.readNext(AttachmentDeserializer.java:208)
        at org.apache.cxf.attachment.LazyAttachmentCollection$1.hasNext(LazyAttachmentCollection.java:95)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.cacheInput(AbstractHTTPDestination.java:591)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.flushHeaders(AbstractHTTPDestination.java:624)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.flushHeaders(AbstractHTTPDestination.java:617)
        at org.apache.cxf.transport.http.AbstractHTTPDestination$WrappedOutputStream.onFirstWrite(AbstractHTTPDestination.java:807)
        at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:47)
        at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:51)
        at org.apache.cxf.io.AbstractThresholdOutputStream.unBuffer(AbstractThresholdOutputStream.java:89)
        at org.apache.cxf.io.AbstractThresholdOutputStream.close(AbstractThresholdOutputStream.java:100)
        at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
        at org.apache.cxf.transport.http.AbstractHTTPDestination$BackChannelConduit.close(AbstractHTTPDestination.java:756)
        at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:90)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86)
        at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
        at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:75)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
        at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

TID: [-1] [] [2021-02-11 12:40:10,510] ERROR {org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve} - Could not handle request: null java.lang.NullPointerException

Can you help me please ?
 
### Steps to reproduce:
Create an API
addition a documentation file
### Affected Product Version:

WSO2 APIM 3.2
with
- LINUX Redhat 7
- Postgres 10

### Environment details (with versions):
- OS:RHEL7
- Client:firefox
- Env (Docker/K8s):

---

**Comment by tharikaGitHub** [comment]
Hi @roberto539 I tried this in a WUM updated pack of WSO2 API Manager 3.2.0. But file upload worked for me. Are you using the GA (Vanilla) pack?

Do you get the same error when you try to upload any other file to the API other than the file that you have shown in the screenshot?

**Comment by roberto539** [comment]
Hello, thanks you for the answers.

I have the problem only for upload document and i don't use GA Pack.

i just found that when i use the following api in local server with curl  
https://wwwwwww:9443/api/am/publisher/v1/apis/[xxxxx]/documents/[xxxxxxxx]/content/
The document was uploader but not with publisher or postman.
I think the problem must come from a network problem.

So, it's not a bug...

**Comment by tharikaGitHub** [comment]
Yes this can be a problem with the attachment or the headers that gets appended to the request. [1]

If the same file works in 3.1.0, probably there should be a difference in the headers we add in 3.2.0.  @roberto539 will you able to provide a document that would help us reproduce the issue?

[1] https://stackoverflow.com/questions/47077818/header-size-exceeds-fixed-maximum-size

**Comment by roberto539** [comment]
Thank you Tharika,

[Guide_utilisation_APIEscale2.pdf](https://github.com/wso2/product-apim/files/5971379/Guide_utilisation_APIEscale2.pdf)
Here is a file for which the error occurs.
In addition, in this file you will also find the details of the error.

**Comment by tharikaGitHub** [comment]
Hi @roberto539, thanks for providing the file. I tried this in both API Manager 3.1.0 and 3.2.0 versions. But it actually worked for me. Couldn't reproduce. Are you using the latest WUM update for API Manager 3.2.0?

**Comment by Krishanx92** [comment]
Stale issue hence closing.
