### ISSUE TITLE
Creating a new user throws an error in console

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#9960]
### Description:

When a new user is created from the carbon console, following error is displayed in the logs

	[2021-02-17 11:15:19,274] ERROR - APIMgtGatewayCacheMessageListener JMSException occurred when processing the received message 
	com.fasterxml.jackson.core.JsonParseException: Unexpected character ('t' (code 116)): was expecting comma to separate Object entries
	 at [Source: (String)"{"event":{"payloadData":{"type":"gatewayUsernameCache","value":"["testuser@carbon.super"]"}}}"; line: 1, column: 68]
		at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840) ~[com.fasterxml.jackson.core.jackson-core_2.10.3.jar:2.9.8]
		at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712) ~[com.fasterxml.jackson.core.jackson-core_2.10.3.jar:2.9.8]
		at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637) ~[com.fasterxml.jackson.core.jackson-core_2.10.3.jar:2.9.8]
		at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2293) ~[com.fasterxml.jackson.core.jackson-core_2.10.3.jar:2.9.8]
		at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:917) ~[com.fasterxml.jackson.core.jackson-core_2.10.3.jar:2.9.8]
		at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:250) ~[com.fasterxml.jackson.core.jackson-databind_2.10.3.jar:2.9.9.2]
		at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258) ~[com.fasterxml.jackson.core.jackson-databind_2.10.3.jar:2.9.9.2]
		at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258) ~[com.fasterxml.jackson.core.jackson-databind_2.10.3.jar:2.9.9.2]
		at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68) ~[com.fasterxml.jackson.core.jackson-databind_2.10.3.jar:2.9.9.2]
		at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15) ~[com.fasterxml.jackson.core.jackson-databind_2.10.3.jar:2.9.9.2]
		at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4270) ~[com.fasterxml.jackson.core.jackson-databind_2.10.3.jar:2.9.9.2]
		at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2720) ~[com.fasterxml.jackson.core.jackson-databind_2.10.3.jar:2.9.9.2]
		at org.wso2.carbon.apimgt.gateway.listeners.APIMgtGatewayCacheMessageListener.onMessage_aroundBody0(APIMgtGatewayCacheMessageListener.java:53) [org.wso2.carbon.apimgt.gateway_6.8.193.jar:?]
		at org.wso2.carbon.apimgt.gateway.listeners.APIMgtGatewayCacheMessageListener.onMessage(APIMgtGatewayCacheMessageListener.java:43) [org.wso2.carbon.apimgt.gateway_6.8.193.jar:?]
		at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:645) [org.wso2.carbon.apimgt.jms.listener_6.8.193.jar:?]
		at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:544) [org.wso2.carbon.apimgt.jms.listener_6.8.193.jar:?]
		at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41.jar:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
		at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]    
### Steps to reproduce:
Create user and view the console logs. This is applicable for tenant users as well
### Affected Product Version:
APIM 4.0.0 M7

**Comment by chamilaadhi** [comment]
@HiranyaKavishani @tharindu1st I think this has something to do with this PR https://github.com/wso2/carbon-apimgt/pull/9560

**Comment by uvindra** [comment]
This issue is there in Alpha pack as well and can be seen soon after starting the pack without needing to take any actions as below,

```
TID: [-1] [] [2021-03-01 16:13:15,152] ERROR {org.wso2.carbon.apimgt.gateway.listeners.APIMgtGatewayCacheMessageListener} - JMSException occurred when processing the received message com.fasterxml.jackson.core.JsonParseException: Unexpected character ('a' (code 97)): was expecting comma to separate Object entries
 at [Source: (String)"{"event":{"payloadData":{"type":"gatewayUsernameCache","value":"["apim_reserved_user@carbon.super"]"}}}"; line: 1, column: 68]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2293)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:917)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:250)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4270)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2720)
        at org.wso2.carbon.apimgt.gateway.listeners.APIMgtGatewayCacheMessageListener.onMessage_aroundBody0(APIMgtGatewayCacheMessageListener.java:53)
        at org.wso2.carbon.apimgt.gateway.listeners.APIMgtGatewayCacheMessageListener.onMessage(APIMgtGatewayCacheMessageListener.java:43)
        at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:645)
        at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:544)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
