### ISSUE TITLE
Endpoints having https urls fail in gateway 

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-apim#9995]
### Description:
Https back end invocation fails

### Steps to reproduce:
Create a mocky endpoint and give the https endpoint as the prod endpoint. Then invoke the API using jwt token.
Following error logs and the invocation fails.

```
TargetHandler ERROR_CODE = 101500, STATE_DESCRIPTION = Exception occurred when Server establishing a connection to the backend, INTERNAL_STATE = REQUEST_READY, DIRECTION = REQUEST, CAUSE_OF_ERROR = I/O exception : Received fatal alert: unrecognized_name, TARGET_HOST = 185.42.117.109, TARGET_PORT = 443, TARGET_CONTEXT = https://run.mocky.io/v3/933e58eb-89a2-4c2b-855c-5508133a942d, HTTP_METHOD = GET, TRIGGER_TYPE = api, TRIGGER_NAME = Mock:v1.0.0, REMOTE_ADDRESS = run.mocky.io/185.42.117.109:443, CONNECTION = http-outgoing-4
[2021-02-22 19:21:59,025] ERROR - TargetHandler I/O error: Received fatal alert: unrecognized_name
javax.net.ssl.SSLHandshakeException: Received fatal alert: unrecognized_name
	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:337) ~[?:?]
	at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293) ~[?:?]
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:186) ~[?:?]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:681) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:636) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:454) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:433) ~[?:?]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637) ~[?:?]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doUnwrap(SSLIOSession.java:278) ~[httpcore-nio_4.4.14.wso2v1.jar:?]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:332) ~[httpcore-nio_4.4.14.wso2v1.jar:?]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:541) ~[httpcore-nio_4.4.14.wso2v1.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120) [httpcore-nio_4.4.14.wso2v1.jar:?]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) [httpcore-nio_4.4.14.wso2v1.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) [httpcore-nio_4.4.14.wso2v1.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) [httpcore-nio_4.4.14.wso2v1.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) [httpcore-nio_4.4.14.wso2v1.jar:?]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) [httpcore-nio_4.4.14.wso2v1.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) [httpcore-nio_4.4.14.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Affected Product Version:
4.0.0-m8

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tharindu1st** [comment]
This couldn't reproduce in latest pack
